Add unit tests for API models
wazuh/wazuh pull request #10037
Opened 2021-09-09 14:58 UTC by vicferpoy

|Related issue|
|---|
|#10008|

This closes #10008 .

New API unit tests have been added to cover all the API models.

| | | | | |
|--|--|--|--|--|
| **Name** | **Stmts** | **Miss** | **Cover** | **Status** |
| models/__init__.py | 3 | 0 | 100% | :green_square: |
| models/active_response_model.py | 36 | 0 | 100% | :green_square: |
| models/agent_added_model.py | 29 | 0 | 100% | :green_square: |
| models/agent_inserted_model.py | 48 | 0 | 100% | :green_square: |
| models/base_model_.py | 104 | 0 | 100% | :green_square: |
| models/basic_info_model.py | 59 | 0 | 100% | :green_square: |
| models/configuration_model.py | 212 | 0 | 100% | :green_square: |
| models/group_added_model.py | 15 | 0 | 100% | :green_square: |
| models/security_model.py | 72 | 0 | 100% | :green_square: |
| models/security_token_response_model.py | 19 | 0 | 100% | :green_square: |
| TOTAL | 597 | 0 | 100% | :green_square: |

## Test results
```shellsession
========================================= test session starts ==========================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /home/vicferpoy/venvs/unittest-env/bin/python3
cachedir: .pytest_cache
rootdir: /home/vicferpoy/Desktop/Git/wazuh/api
plugins: cov-2.12.0, asyncio-0.15.1
collected 27 items                                                                                     

models/test/test_model.py::test_model_from_dict PASSED                                           [  3%]
models/test/test_model.py::test_model_to_dict PASSED                                             [  7%]
models/test/test_model.py::test_model_to_str PASSED                                              [ 11%]
models/test/test_model.py::test_model_operator_overloading PASSED                                [ 14%]
models/test/test_model.py::test_allof PASSED                                                     [ 18%]
models/test/test_model.py::test_allof_to_dict PASSED                                             [ 22%]
models/test/test_model.py::test_data PASSED                                                      [ 25%]
models/test/test_model.py::test_data_from_dict PASSED                                            [ 29%]
models/test/test_model.py::test_items PASSED                                                     [ 33%]
models/test/test_model.py::test_items_from_dict PASSED                                           [ 37%]
models/test/test_model.py::test_body_get_kwargs[additional_kwargs0] PASSED                       [ 40%]
models/test/test_model.py::test_body_get_kwargs[additional_kwargs1] PASSED                       [ 44%]
models/test/test_model.py::test_body_get_kwargs_ko PASSED                                        [ 48%]
models/test/test_model.py::test_body_from_dict PASSED                                            [ 51%]
models/test/test_model.py::test_body_decode_body PASSED                                          [ 55%]
models/test/test_model.py::test_body_decode_body_ko PASSED                                       [ 59%]
models/test/test_model.py::test_body_validate_content_type PASSED                                [ 62%]
models/test/test_model.py::test_body_validate_content_type_ko PASSED                             [ 66%]
models/test/test_model.py::test_all_models[agent_added_model.py] PASSED                          [ 70%]
models/test/test_model.py::test_all_models[agent_inserted_model.py] PASSED                       [ 74%]
models/test/test_model.py::test_all_models[basic_info_model.py] PASSED                           [ 77%]
models/test/test_model.py::test_all_models[logtest_model.py] PASSED                              [ 81%]
models/test/test_model.py::test_all_models[security_token_response_model.py] PASSED              [ 85%]
models/test/test_model.py::test_all_models[active_response_model.py] PASSED                      [ 88%]
models/test/test_model.py::test_all_models[configuration_model.py] PASSED                        [ 92%]
models/test/test_model.py::test_all_models[security_model.py] PASSED                             [ 96%]
models/test/test_model.py::test_all_models[group_added_model.py] PASSED                          [100%]

=================================== 27 passed, 10 warnings in 0.94s ====================================
```

Regards,
Víctor

2021-09-10 10:16 UTC, mcarmona99 requested changes

2021-09-10 10:26 UTC, vicferpoy commented on api/api/models/test/test_model.py
>      assert isinstance(dikt, dict)
It is part of the testing process. Why would we populate a new dictionary using dict comprehension to compare types? If the main object is not even a dictionary, we skip that step.

2021-09-10 10:38 UTC, mcarmona99 approved these changes
LGTM!

2021-09-23 15:15 UTC, davidjiglesias approved these changes

2021-09-23 15:15 UTC, merged