Add unit test for api controllers
wazuh/wazuh pull request #10041
Opened 2021-09-09 18:10 UTC by Kondent

|Related issue|
|---|
| This PR closes #9939 |

In this PR, i'm adding unit tests for every api controller in the following list:
- [x] api/controllers/active_response_controller.py
- [x] api/controllers/agent_controller.py
- [x] api/controllers/cdb_list_controller.py
- [x] api/controllers/ciscat_controller.py 
- [x] api/controllers/decoder_controller.py
- [x] api/controllers/default_controller.py
- [x] api/controllers/experimental_controller.py
- [x] api/controllers/manager_controller.py
- [x] api/controllers/mitre_controller.py
- [x] api/controllers/overview_controller.py
- [x] api/controllers/rootcheck_controller.py
- [x] api/controllers/rule_controller.py
- [x] api/controllers/sca_controller.py
- [x] api/controllers/security_controller.py
- [x] api/controllers/syscheck_controller.py
- [x] api/controllers/syscollector_controller.py
- [x] api/controllers/task_controller.py
- [x] api/controllers/vulnerability_controller.py

<details>
  <summary>Test Coverage - click to expand</summary>

## Before
### API
| | | | | |
|--|--|--|--|--|
| **Name** | **Stmts** | **Miss** | **Cover** | **Status** |
| api/__init__.py | 0 | 0 | 100% | :green_square: |
| api/alogging.py | 43 | 3 | 93% | :green_square: |
| api/api_exception.py | 11 | 0 | 100% | :green_square: |
| api/authentication.py | 107 | 7 | 93% | :green_square: |
| api/configuration.py | 85 | 4 | 95% | :green_square: |
| api/constants.py | 10 | 0 | 100% | :green_square: |
| api/controllers/__init__.py | 0 | 0 | 100% | :green_square: |
| api/controllers/active_response_controller.py | 15 | 15 | 0% | :red_square: |
| api/controllers/agent_controller.py | 228 | 228 | 0% | :red_square: |
| api/controllers/cdb_list_controller.py | 40 | 40 | 0% | :red_square: |
| api/controllers/ciscat_controller.py | 13 | 13 | 0% | :red_square: |
| api/controllers/cluster_controller.py | 143 | 143 | 0% | :red_square: |
| api/controllers/decoder_controller.py | 45 | 45 | 0% | :red_square: |
| api/controllers/default_controller.py | 15 | 15 | 0% | :red_square: |
| api/controllers/experimental_controller.py | 109 | 109 | 0% | :red_square: |
| api/controllers/manager_controller.py | 96 | 96 | 0% | :red_square: |
| api/controllers/mitre_controller.py | 41 | 41 | 0% | :red_square: |
| api/controllers/overview_controller.py | 12 | 12 | 0% | :red_square: |
| api/controllers/rootcheck_controller.py | 27 | 27 | 0% | :red_square: |
| api/controllers/rule_controller.py | 57 | 57 | 0% | :red_square: |
| api/controllers/sca_controller.py | 20 | 20 | 0% | :red_square: |
| api/controllers/security_controller.py | 233 | 233 | 0% | :red_square: |
| api/controllers/syscheck_controller.py | 31 | 31 | 0% | :red_square: |
| api/controllers/syscollector_controller.py | 65 | 65 | 0% | :red_square: |
| api/controllers/task_controller.py | 13 | 13 | 0% | :red_square: |
| api/controllers/vulnerability_controller.py | 12 | 12 | 0% | :red_square: |
| api/encoder.py | 24 | 24 | 0% | :red_square: |
| api/middlewares.py | 101 | 101 | 0% | :red_square: |
| api/models/__init__.py | 3 | 0 | 100% | :green_square: |
| api/models/active_response_model.py | 36 | 36 | 0% | :red_square: |
| api/models/agent_added_model.py | 29 | 29 | 0% | :red_square: |
| api/models/agent_inserted_model.py | 48 | 48 | 0% | :red_square: |
| api/models/base_model_.py | 104 | 21 | 80% | :green_square: |
| api/models/basic_info_model.py | 59 | 24 | 59% | :yellow_square: |
| api/models/configuration_model.py | 212 | 212 | 0% | :red_square: |
| api/models/group_added_model.py | 15 | 15 | 0% | :red_square: |
| api/models/security_model.py | 72 | 72 | 0% | :red_square: |
| api/models/security_token_response_model.py | 19 | 6 | 68% | :yellow_square: |
| api/signals.py | 2 | 2 | 0% | :red_square: |
| api/uri_parser.py | 29 | 29 | 0% | :red_square: |
| api/util.py | 108 | 7 | 94% | :green_square: |
| api/validator.py | 145 | 10 | 93% | :green_square: |
| TOTAL | 2477 | 1865 | 25% | :orange_square: |

OVERALL COVERAGE PERCENTAGE: 63% (FRAMEWORK + API + WODLES)

## After
### API
| | | | | |
|--|--|--|--|--|
| **Name** | **Stmts** | **Miss** | **Cover** | **Status** |
| api/__init__.py | 0 | 0 | 100% | :green_square: |
| api/alogging.py | 43 | 3 | 93% | :green_square: |
| api/api_exception.py | 11 | 0 | 100% | :green_square: |
| api/authentication.py | 107 | 7 | 93% | :green_square: |
| api/configuration.py | 85 | 4 | 95% | :green_square: |
| api/constants.py | 10 | 0 | 100% | :green_square: |
| api/controllers/__init__.py | 0 | 0 | 100% | :green_square: |
| api/controllers/active_response_controller.py | 15 | 0 | 100% | :green_square: |
| api/controllers/agent_controller.py | 228 | 2 | 99% | :green_square: |
| api/controllers/cdb_list_controller.py | 40 | 0 | 100% | :green_square: |
| api/controllers/ciscat_controller.py | 13 | 0 | 100% | :green_square: |
| api/controllers/cluster_controller.py | 143 | 143 | 0% | :red_square: |
| api/controllers/decoder_controller.py | 45 | 0 | 100% | :green_square: |
| api/controllers/default_controller.py | 15 | 0 | 100% | :green_square: |
| api/controllers/experimental_controller.py | 109 | 1 | 99% | :green_square: |
| api/controllers/manager_controller.py | 96 | 1 | 99% | :green_square: |
| api/controllers/mitre_controller.py | 41 | 0 | 100% | :green_square: |
| api/controllers/overview_controller.py | 12 | 0 | 100% | :green_square: |
| api/controllers/rootcheck_controller.py | 27 | 0 | 100% | :green_square: |
| api/controllers/rule_controller.py | 57 | 0 | 100% | :green_square: |
| api/controllers/sca_controller.py | 20 | 0 | 100% | :green_square: |
| api/controllers/security_controller.py | 233 | 6 | 97% | :green_square: |
| api/controllers/syscheck_controller.py | 31 | 0 | 100% | :green_square: |
| api/controllers/syscollector_controller.py | 65 | 0 | 100% | :green_square: |
| api/controllers/task_controller.py | 13 | 0 | 100% | :green_square: |
| api/controllers/vulnerability_controller.py | 12 | 0 | 100% | :green_square: |
| api/encoder.py | 24 | 2 | 92% | :green_square: |
| api/middlewares.py | 101 | 68 | 33% | :orange_square: |
| api/models/__init__.py | 3 | 0 | 100% | :green_square: |
| api/models/active_response_model.py | 36 | 14 | 61% | :yellow_square: |
| api/models/agent_added_model.py | 29 | 11 | 62% | :yellow_square: |
| api/models/agent_inserted_model.py | 48 | 20 | 58% | :yellow_square: |
| api/models/base_model_.py | 104 | 21 | 80% | :green_square: |
| api/models/basic_info_model.py | 59 | 7 | 88% | :green_square: |
| api/models/configuration_model.py | 212 | 92 | 57% | :yellow_square: |
| api/models/group_added_model.py | 15 | 5 | 67% | :yellow_square: |
| api/models/security_model.py | 72 | 32 | 56% | :yellow_square: |
| api/models/security_token_response_model.py | 19 | 2 | 89% | :green_square: |
| api/signals.py | 2 | 2 | 0% | :red_square: |
| api/uri_parser.py | 29 | 29 | 0% | :red_square: |
| api/util.py | 108 | 7 | 94% | :green_square: |
| api/validator.py | 145 | 10 | 93% | :green_square: |
| TOTAL | 2477 | 489 | 80% | :green_square: |

OVERALL COVERAGE PERCENTAGE: 72% (FRAMEWORK + API + WODLES)

</details>

---

Regards,
Alexis

2021-09-10 11:08 UTC, vicferpoy requested changes
The overall test design is fine, but there are a few improvements that need to be applied.

2021-09-10 11:08 UTC, vicferpoy commented on api/api/controllers/test/test_active_response_controller.py
> +                                   side_effect=AsyncMock, return_value={}):
You can mock this from the abstract class and reduce the lines.

2021-09-10 11:08 UTC, vicferpoy commented on api/api/controllers/test/test_active_response_controller.py
> +                   return_value=None) as mock_dapi:
Why don't you mock the DAPI module using a decorator? It would apply to all tests and you reduce indentation.

2021-09-10 11:08 UTC, vicferpoy commented on api/api/controllers/test/test_active_response_controller.py
> +        mock_dapi.assert_has_calls(calls)
Maybe the `assert_called_with` is more accurate.

2021-09-14 15:07 UTC, Kondent commented on api/api/controllers/test/test_active_response_controller.py
> +@pytest.mark.parametrize('mock_request', [{'token_info': {'rbac_policies': 'rbac_policies_value'}}])
As we discussed and decided, Im going to replace this with a `MagicMock()`

2021-09-21 07:36 UTC, vicferpoy approved these changes
LGTM!

2021-09-23 15:00 UTC, davidjiglesias approved these changes

2021-09-23 15:01 UTC, merged