8473 add rules gcp vpc storage access
wazuh/wazuh pull request #10128
Opened 2021-09-14 14:22 UTC by JavierBejMen

|Related issue|
|---|
|Closes #8473 |

## Description
Added generic rules for GCP storage and usage logs.
Added tests in gcp.ini

## Configuration options

## Logs/Alerts example

## Tests

- Decoder/Rule tests
  - [x] Added unit testing files ".ini"
  - [x] runtests.py executed without errors

2021-09-14 14:45 UTC, jcruzlp requested changes

2021-09-14 14:45 UTC, jcruzlp commented on ruleset/rules/0690-gcp_rules.xml
> +
Missing `</rule>`

2021-09-14 14:46 UTC, JavierBejMen commented on ruleset/rules/0690-gcp_rules.xml
> +
:1st_place_medal:

2021-09-14 14:56 UTC, jcruzlp approved these changes
LGTM

2021-09-15 10:57 UTC, 72nomada approved these changes
LGTM

2021-09-15 10:57 UTC, merged