Feature/9086 add iam role session duration
wazuh/wazuh pull request #10198
Opened 2021-09-20 07:59 UTC by noise-kngdm

|Related issue|
|---|
|Closes #9086 |
## Description
In this PR we have added a new parameter to the AWS integration module that allows users to set the duration of the session assumed when using the `--iam_role_arn` parameter. After the changes, the user can specify a session duration between 900 and 3600 seconds using either the `--duration-seconds` parameter or modifyng the `ossec.conf` file.

## Tests
### Manual tests performed
To test the changes we temporary added some code to the module that would add a delay after the `assume_role` call to test if the module would return a timeout when trying to use a session after it has expired.
The execution did return an error, as expected.
### Testing a bucket
```
root@ff5389d2ebf2:/var/ossec/wodles/aws# /var/ossec/framework/python/bin/python3 ./aws-s3.py -b cloudtrail-bucket -t cloudtrail -ds 900 -i arn:aws:iam::xxxxxxx:role/test_role
Time now: 09:03:43
Role assumed. role_session_duration variable is set to 900. Sleeping for 910 seconds.
Time after sleep: 09:18:53
ERROR: Invalid credentials to access S3 Bucket
```
### Testing a service
```
root@ff5389d2ebf2:/var/ossec/wodles/aws# py ./aws-s3.py -sr inspector -ds 900 -i arn:aws:iam::xxxxxxx:role/test_role
Time now: 10:37:26
Role assumed. role_session_duration variable is set to 900. Sleeping for 910 seconds.
Time after sleep: 10:52:36
ERROR: An error occurred (ExpiredTokenException) when calling the ListFindings operation: The security token included in the request is expired
```

We have also tested that the new parameter works fine in the configuration of both a service and a bucket by adding the following configuration items (one at a time) to the `ossec.conf` file and modifying the python program to write the value of the `role_session_variable`, if specified, to a temporary file. 
#### Bucket testing configuration
```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>10m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>yes</skip_on_error>
  <bucket type="cloudtrail">
     <name>wazuh-test-bucket</name>
     <access_key>XXXXXX</access_key>
     <secret_key>XXXXXX</secret_key>
     <iam_role_arn>arn:aws:iam::XXXXX:role/test_role</iam_role_arn>
     <role_session_duration>1300</role_session_duration>
  </bucket>  
</wodle>
```
#### Service testing configuration
```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>1m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>yes</skip_on_error>
  <service type="cloudwatchlogs">
     <access_key>XXXXXX</access_key>
     <secret_key>XXXXXX</secret_key>
     <iam_role_arn>arn:aws:iam::XXXXX:role/test_role</iam_role_arn>
     <role_session_duration>1300</role_session_duration>
     <aws_log_groups>framework-test-apache</aws_log_groups>
  </service>  
</wodle>
```
### Automatic tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2021-09-20 10:17 UTC, CarlosRS9 requested changes

2021-09-20 10:17 UTC, CarlosRS9 commented on wodles/aws/aws_s3.py
> +    parser.add_argument('-ds', '--duration-seconds', type=int, dest='role_session_duration', default=None,
Replace `-ds` and `--duration-seconds` with a more descriptive parameter name, such as `--iam_role_duration`.

2021-09-20 10:17 UTC, CarlosRS9 commented on wodles/aws/aws_s3.py
> +    if parsed_args.role_session_duration is not None and parsed_args.iam_role_arn is None:
Create a new `arg_valid_iam_role_duration` function and handle this there instead

2021-09-20 10:17 UTC, CarlosRS9 commented on wodles/aws/aws_s3.py
> +    if not tools.check_role_session_duration(options.role_session_duration):
Perform this check in the suggested `arg_valid_iam_role_duration` function` function

2021-09-20 10:17 UTC, CarlosRS9 commented on wodles/aws/tools.py
> +def check_role_session_duration(duration: int or None) -> bool:
There is no need for a new `tools.py` module just for this function as this check can be performed in a `arg_valid_iam_role_duration` function in the `aws_s3.py` module

2021-09-20 10:19 UTC, CarlosRS9 commented
We should also try to use the same name for the ossec.conf tag option (`role_session_duration`) and the aws-s3.py parameter (`duration-seconds`) if possible

2021-09-20 15:40 UTC, CarlosRS9 requested changes

2021-09-20 15:40 UTC, CarlosRS9 commented on src/wazuh_modules/wm_aws.h
> +    char *iam_role_duration;        // IAM role session duration
Tabulate this accordingly

2021-09-20 15:40 UTC, CarlosRS9 commented on src/wazuh_modules/wm_aws.h
> +    char *iam_role_duration;        // IAM role session duration
Tabulate this accordingly

2021-09-20 15:40 UTC, CarlosRS9 commented on wodles/aws/aws_s3.py
> +def arg_valid_iam_role_duration(duration: int or None, iam_role_arn: str or None):
```suggestion
def arg_valid_iam_role_duration(arg_string):
```

Argument validation functions will receive only one parameter when called

2021-09-20 15:40 UTC, CarlosRS9 commented on wodles/aws/aws_s3.py
> +    if duration is not None and iam_role_arn is None:
Remove this. As you cannot access the `iam_role_arn` value from here you will need to move this condition to the `main` body. See the next comment for more details.

2021-09-20 15:40 UTC, CarlosRS9 commented on wodles/aws/aws_s3.py
> +        raise ValueError("Invalid session duration specified. Value must be between 900 and 3600.")
This should raise a `argparse.ArgumentTypeError` instead of `ValueError`

2021-09-20 15:40 UTC, CarlosRS9 commented on wodles/aws/aws_s3.py
Add the `iam_role_arn` validation from the `arg_valid_iam_role_duration` here:
```suggestion
if duration is not None and iam_role_arn is None:
    raise argparse.ArgumentTypeError('Used --iam_role_duration argument but no --iam_role_arn provided.')
```

2021-09-21 14:13 UTC, CarlosRS9 requested changes

2021-09-21 14:13 UTC, CarlosRS9 commented on wodles/aws/aws_s3.py
> +        raise Exception('Used --iam_role_duration argument but no --iam_role_arn provided.')
```suggestion
        raise argparse.ArgumentTypeError('Used --iam_role_duration argument but no --iam_role_arn provided.')
```

2021-09-22 09:21 UTC, CarlosRS9 approved these changes

2021-09-23 14:28 UTC, davidjiglesias approved these changes

2021-09-23 14:29 UTC, merged