Fix AIT cluster race condition
wazuh/wazuh pull request #10289
Opened 2021-09-24 23:14 UTC by Kondent

|Related issue|
|---|
| This PR closes #10204 |

## Description
One of the API integration tests failed during a PR check. It only failed once.

## Solution
Test `GET /cluster/configuration/validation`.
Stages:
- Between `Upload corrupted configuration` and `Request validation`: a delay must be awaited between these two. At `Request validation` we were testing that both workers got a valid configuration but master got it corrupted. Here is a race condition between corrupted file sync and the test itself. So I think it should be awaited and after that, test these three nodes as invalid.
- Between `Delete rules file` and `Request validation`: exact same as before, but this time corrupted file is deleted. Here we should test all three nodes as valid after certain amount of time.

## Test results
```
↪ ~/git/wazuh/api/test/integration ⊶ fix/10204-cluster-validation-fail ⨘ pytest -vv -x --disable-warnings test_cluster_endpoints.tavern.yaml
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.0.0, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/inttest-env/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.5', 'Platform': 'Linux-5.11.0-36-generic-x86_64-with-glibc2.31', 'Packages': {'pytest': '5.0.0', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.11.0', 'tavern': '1.2.2'}}
rootdir: /home/kondent/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, metadata-1.11.0, tavern-1.2.2
collected 45 items                                                                                                                                                                           

test_cluster_endpoints.tavern.yaml::GET /cluster/local/config PASSED                                                                                                                   [  2%]
test_cluster_endpoints.tavern.yaml::GET /cluster/healthcheck PASSED                                                                                                                    [  4%]
test_cluster_endpoints.tavern.yaml::GET /cluster/local/info PASSED                                                                                                                     [  6%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes PASSED                                                                                                                          [  8%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[master-node] PASSED                                                                                                             [ 11%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[worker1] PASSED                                                                                                                 [ 13%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[worker2] PASSED                                                                                                                 [ 15%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[ip] PASSED                                                                                                               [ 17%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[name] PASSED                                                                                                             [ 20%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[type] PASSED                                                                                                             [ 22%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[version] PASSED                                                                                                          [ 24%]
test_cluster_endpoints.tavern.yaml::GET /cluster/status PASSED                                                                                                                         [ 26%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration PASSED                                                                                                        [ 28%]
test_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation PASSED                                                                                                       [ 31%]
test_cluster_endpoints.tavern.yaml::GET /cluster/api/config PASSED                                                                                                                     [ 33%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration/{component}/{configuration} PASSED                                                                            [ 35%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[master-node] PASSED                                                                                                    [ 37%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[worker1] PASSED                                                                                                        [ 40%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[worker2] PASSED                                                                                                        [ 42%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[master-node] PASSED                                                                                                    [ 44%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[worker1] PASSED                                                                                                        [ 46%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[worker2] PASSED                                                                                                        [ 48%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary[worker1] PASSED                                                                                                [ 51%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary[worker2] PASSED                                                                                                [ 53%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[master-node] PASSED                                                                                                   [ 55%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[worker1] PASSED                                                                                                       [ 57%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[worker2] PASSED                                                                                                       [ 60%]
test_cluster_endpoints.tavern.yaml::GET /cluster/wrong_node/stats PASSED                                                                                                               [ 62%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[master-node] PASSED                                                                                         [ 64%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[worker1] PASSED                                                                                             [ 66%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[worker2] PASSED                                                                                             [ 68%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[master-node] PASSED                                                                                            [ 71%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[worker1] PAS [...]

2021-09-27 14:13 UTC, mcarmona99 requested changes

2021-09-27 14:13 UTC, mcarmona99 commented on api/test/integration/test_cluster_endpoints.tavern.yaml
> +    delay_before: 12
Don't use `delay_before`. The delay must be set in the test case causing the possible race condition. In this case, the delay must be in the test `Upload corrupted configuration` and it should be a `delay_after`.

Add a variable to common.yaml as this value is repeated below.

2021-09-27 14:13 UTC, mcarmona99 commented on api/test/integration/test_cluster_endpoints.tavern.yaml
> +    delay_before: 12
Same as above, delay_after + variable

2021-09-27 14:13 UTC, mcarmona99 commented on api/test/integration/test_cluster_endpoints.tavern.yaml
> +    delay_before: 12
I would also suggest changing the delay value from 12 to 15 or 20 as it is only used twice and we could avoid future problems this way.

2021-09-27 15:22 UTC, mcarmona99 requested changes

2021-09-27 15:22 UTC, mcarmona99 commented on api/test/integration/test_cluster_endpoints.tavern.yaml
>          error: !anyint
Review all error values in this file to indicate the correct ones instead of `!anyint`

2021-09-27 15:44 UTC, mcarmona99 approved these changes
LGTM

2021-09-28 08:55 UTC, vicferpoy requested changes

2021-09-28 08:55 UTC, vicferpoy commented on api/test/integration/common.yaml
> +  cluster_sync_delay: 20
This value is too high. The cluster synchronization should last 10 seconds at worst in the testing environment. To save some time, this should be reduced to `12`. A 30% margin must be enough. 
```suggestion
  cluster_sync_delay: 12
```

2021-09-28 09:23 UTC, vicferpoy approved these changes
LGTM!

2021-09-29 09:08 UTC, davidjiglesias approved these changes

2021-09-29 09:09 UTC, davidjiglesias approved these changes

2021-09-29 09:09 UTC, merged