Improving the logs generated during the agents' registration and replacement
wazuh/wazuh pull request #10325
Opened 2021-09-27 21:54 UTC by pereyra-m

|Related issue|
|---|
|#10268|

## Description

This PR changes the logs generated when an agent tries to register and a duplicate is found
- If the replacement is successful, only one **INFO** message is printed
- If the replacement failed, only a **WARNING** message is printed indicating the cause

## Logs/Alerts example

All the messages generated are detailed in the comments.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Review logs syntax and correct language

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Valgrind (memcheck and descriptor leaks check)

- [x] Working on cluster environments
- [x] Added unit tests (for new features)

2021-09-27 22:04 UTC, pereyra-m commented
## Scan-build

No bugs were found

![scan-build](https://user-images.githubusercontent.com/65046601/134991102-38a021bd-5361-43bd-86b7-da0804e082a4.png)

## Valgrind

No memory leaks were found

![valgrind](https://user-images.githubusercontent.com/65046601/134991305-35f1bc91-d067-496f-94a0-d5ae0b9351c6.png)

## UT Coverage

- The method `w_auth_replace_agent()` is completely covered

2021-09-27 22:25 UTC, pereyra-m commented
## Example messages

**Successful replacement**
![success](https://user-images.githubusercontent.com/65046601/134992749-2d05058c-f834-446d-9193-69af0ed9f128.png)

**Force disabled**
![disabled](https://user-images.githubusercontent.com/65046601/134992614-ec8d54d0-7e62-4a16-ab28-925b756207b5.png)

**Existent key**
![existent_key](https://user-images.githubusercontent.com/65046601/134992946-eae03aa8-af43-45ef-8586-9efb05e128f0.png)

**Not disconnected agent**
![agent_not_disconnected](https://user-images.githubusercontent.com/65046601/134993161-66a4bfd0-39e6-4ca2-bc21-4778d259decb.png)

**Recently disconnected**
![recently_disconnected](https://user-images.githubusercontent.com/65046601/134993365-3c639a40-e766-46a5-8a67-0040ca0a428b.png)

**Recently registered**
![registration_time](https://user-images.githubusercontent.com/65046601/134993590-17050213-bc48-4d98-ab50-85e7ffa29a4b.png)

2021-09-27 23:03 UTC, DProvinciani requested changes
Please, apply changes according to the comments.

2021-09-28 01:17 UTC, pereyra-m commented on src/os_auth/auth.c
>          if (OS_SUCCESS != w_auth_validate_groups(groups, response)) {
Yes. it'd be more clear. Fixed!

2021-09-28 01:18 UTC, pereyra-m commented on src/os_auth/auth.h
>  w_err_t w_auth_replace_agent(keyentry *key,
The doxygen wasn't updated. Fixed!

2021-09-28 03:22 UTC, DProvinciani approved these changes
Looks good!

2021-09-28 03:26 UTC, merged