Fix `agent_upgrade` script
wazuh/wazuh pull request #10320
Opened 2021-09-27 12:31 UTC by Selutario

|Related issue|
|---|
| Closes #10314 |

## Description

This PR fixes the error reported in #10314 when `/var/ossec/bin/agent_upgrade` script is used. The problem appeared after the changes performed in https://github.com/wazuh/wazuh/pull/8919, when API configuration started being used in the `dapi.py` module:
https://github.com/wazuh/wazuh/blob/a59b4e3f19b5689e582496bd62fe747b3abd176d/framework/wazuh/core/cluster/dapi/dapi.py#L107

The `api_conf` variable is an empty dict by default:
https://github.com/wazuh/wazuh/blob/a59b4e3f19b5689e582496bd62fe747b3abd176d/api/api/configuration.py#L277

It is after being updated in the `wazuh-apid.py` or `wazuh-clusterd.py` when it can be correctly used, inside those processes:
https://github.com/wazuh/wazuh/blob/a59b4e3f19b5689e582496bd62fe747b3abd176d/api/scripts/wazuh-apid.py#L60

However, it was not being updated in the `agent_upgrade` script. As it is a different process, the `api_conf` variable remained empty, so a KeyError was raised:
https://github.com/wazuh/wazuh/blob/a59b4e3f19b5689e582496bd62fe747b3abd176d/framework/scripts/agent_upgrade.py#L111-L115

Instead of loading the content of the `api.yaml` in `agent_upgrade`, we decided to load it when starting the `api/configuration.py` module, so it has the default configuration.

The bug seems to be fixed now:
```
root@wazuh-master:/# /var/ossec/bin/agent_upgrade -a 001 -f /wazuh_agent_v4.2.1_windows.wpk -F

Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.2.1 -> Wazuh v4.2.1

```

2021-09-28 15:34 UTC, AdriiiPRodri requested changes

2021-09-28 15:34 UTC, AdriiiPRodri commented on api/scripts/wazuh-apid.py
> +                        default='')
```suggestion
                        default=None)
```

2021-09-28 15:34 UTC, AdriiiPRodri commented on api/scripts/wazuh-apid.py
> +    if config_file:
```suggestion
    if config_file is not None:
```

2021-09-29 07:40 UTC, AdriiiPRodri approved these changes

2021-09-29 10:36 UTC, davidjiglesias approved these changes

2021-09-29 10:36 UTC, merged