Fix RBAC experimental API integration test expecting a 1760 code in implicit requests
wazuh/wazuh pull request #10322
Opened 2021-09-27 15:58 UTC by mcarmona99

|Related issue|
|---|
| #10311  |

This PR closes #10311.

In this pull request, I have deleted the expected code 1760 in RBAC experimental syscheck test cases of our API integration tests as this code is excluded when using the endpoint with the `all` keyword (implicit request).

### Test results

```
test_rbac_black_rootcheck_endpoints.tavern.yaml 
	 4 passed, 6 warnings

test_rbac_black_syscheck_endpoints.tavern.yaml 
	 4 passed, 6 warnings

test_rbac_white_rootcheck_endpoints.tavern.yaml 
	 4 passed, 6 warnings

test_rbac_white_syscheck_endpoints.tavern.yaml 
	 4 passed, 6 warnings

test_rootcheck_endpoints.tavern.yaml 
	 4 passed, 6 warnings
	 
test_syscheck_endpoints.tavern.yaml 
	 35 passed, 37 warnings

test_experimental_endpoints.tavern.yaml 
	 11 passed, 1 xpassed, 14 warnings

test_rbac_black_experimental_endpoints.tavern.yaml 
	 12 passed, 14 warnings

test_rbac_white_experimental_endpoints.tavern.yaml 
	 12 passed, 14 warnings
```

2021-09-28 09:08 UTC, vicferpoy approved these changes
LGTM!

2021-09-29 09:28 UTC, davidjiglesias requested changes

2021-09-29 09:28 UTC, davidjiglesias commented on api/test/integration/test_rbac_black_experimental_endpoints.tavern.yaml
>            affected_items: []
```suggestion
          affected_items: []  # Some agents are allowed but they raise error 1706, which is excluded as the agents newer than 3.12 are not affected.
```

2021-09-29 09:28 UTC, davidjiglesias commented on api/test/integration/test_rbac_white_experimental_endpoints.tavern.yaml
>            affected_items: []
```suggestion
          affected_items: []  # Some agents are allowed but they raise error 1706, which is excluded as the agents newer than 3.12 are not affected.
```

2021-09-29 09:29 UTC, davidjiglesias approved these changes

2021-09-29 09:29 UTC, merged