Handle more exceptions in the wodles and remove duplicated functions from framework file
wazuh/wazuh pull request #10478
Opened 2021-10-11 14:24 UTC by noise-kngdm

|Related issue|
|---|
|Closes #10155 |

## Description
In this PR we start handling exceptions that were in a `try: except: pass` block in the external integration modules, and move some unused and duplicated code out of the framework code.

The fixed vulnerabilities has been removed in [this PR](https://github.com/wazuh/wazuh-qa/pull/2339) from the wazuh-qa's `known_flaws` files.
## Tests performed

### Unit tests
<details><summary>Framework unit tests</summary>
<p><pre>
==================================== test session starts ====================================
platform linux -- Python 3.9.7, pytest-6.0.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/wazuh/git/wazuh/framework
collected 1655 items                                                                        

framework/wazuh/core/cluster/dapi/tests/test_dapi.py .........................        [  1%]
framework/wazuh/core/cluster/tests/test_cluster.py ...................                [  2%]
framework/wazuh/core/cluster/tests/test_common.py .......                             [  3%]
framework/wazuh/core/cluster/tests/test_control.py sssss                              [  3%]
framework/wazuh/core/cluster/tests/test_local_client.py .                             [  3%]
framework/wazuh/core/cluster/tests/test_utils.py .......                              [  3%]
framework/wazuh/core/cluster/tests/test_worker.py ............ssss.s                  [  4%]
framework/wazuh/core/tests/test_active_response.py ..............                     [  5%]
framework/wazuh/core/tests/test_agent.py ............................................ [  8%]
..................................................................................... [ 13%]
.....................................                                                 [ 15%]
framework/wazuh/core/tests/test_cdb_list.py ......................................    [ 18%]
framework/wazuh/core/tests/test_common.py .......                                     [ 18%]
framework/wazuh/core/tests/test_configuration.py .................................... [ 20%]
                                                                                      [ 20%]
framework/wazuh/core/tests/test_database.py .............                             [ 21%]
framework/wazuh/core/tests/test_decoder.py ................                           [ 22%]
framework/wazuh/core/tests/test_exception.py ...                                      [ 22%]
framework/wazuh/core/tests/test_input_validator.py ...                                [ 22%]
framework/wazuh/core/tests/test_logtest.py ..                                         [ 22%]
framework/wazuh/core/tests/test_manager.py ...............                            [ 23%]
framework/wazuh/core/tests/test_mitre.py .............                                [ 24%]
framework/wazuh/core/tests/test_pyDaemonModule.py .....                               [ 24%]
framework/wazuh/core/tests/test_results.py ........................................   [ 27%]
framework/wazuh/core/tests/test_rootcheck.py .............                            [ 28%]
framework/wazuh/core/tests/test_rule.py ......................                        [ 29%]
framework/wazuh/core/tests/test_sca.py ............                                   [ 30%]
framework/wazuh/core/tests/test_security.py ............                              [ 30%]
framework/wazuh/core/tests/test_stats.py ............                                 [ 31%]
framework/wazuh/core/tests/test_syscheck.py ......                                    [ 32%]
framework/wazuh/core/tests/test_syscollector.py ...                                   [ 32%]
framework/wazuh/core/tests/test_task.py ........                                      [ 32%]
framework/wazuh/core/tests/test_utils.py ............................................ [ 35%]
..................................................................................... [ 40%]
..................................................................................... [ 45%]
..............                                                                        [ 46%]
framework/wazuh/core/tests/test_vulnerability.py .                                    [ 46%]
framework/wazuh/core/tests/test_wazuh_queue.py ..................                     [ 47%]
framework/wazuh/core/tests/test_wazuh_socket.py ....................                  [ 48%]
framework/wazuh/core/tests/test_wdb.py ......................                         [ 50%]
framework/wazuh/core/tests/test_wlogging.py ........                                  [ 50%]
framework/wazuh/rbac/tests/test_auth_context.py ..                                    [ 50%]
framework/wazuh/rbac/tests/test_decorators.py ....................................... [ 53%]
..................................................................                    [ 57%]
framework/wazuh/rbac/tests/test_default_configuration.py ............................ [ 58%]
...........................                                                           [ 60%]
framework/wazuh/rbac/tests/test_orm.py .............................................. [ 63%]
........                                                                              [ 63%]
framework/wazuh/rbac/tests/test_preprocessor.py ...........                           [ 64%]
framework/wazuh/tests/test_active_response.py ............                            [ 65%]
framework/wazuh/tests/test_agent.py ................................................. [ 68%]
............................................................                          [ 71%]
framework/wazuh/tests/test_cdb_list.py .............................................. [ 74%]
.......                                                                               [ 74%]
framework/wazuh/tests/test_ciscat.py .................................                [ 76%]
framework/wazuh/tests/test_cluster.py .....ss                                         [ 77%]
framework/wazuh/tests/test_decoder.py ...................................             [ 79%]
framework/wazuh/tests/test_group.py ........                                          [ 79%]
framework/wazuh/tests/test_logtest.py ......                                          [ 80%]
framework/wazuh/tests/test_manager.py ....................................            [ 82%]
framework/wazuh/tests/test_mitre.py .......                                           [ 82%]
framework/wazuh/tests/test_rootcheck.py ............................................. [ 85%]
.....                                                                                 [ 85%]
framework/wazuh/tests/test_rule.py .................................................. [ 88%]
......                                                                                [ 89%]
framework/wazuh/tests/test_sca.py .......                                             [ 89%]
framework/wazuh/tests/test_security.py .............................................. [ 92%]
...........................                                                           [ 94%]
framework/wazuh/tests/test_stats.py .......                                           [ 94%]
framework/wazuh/tests/test_syscheck.py .........................                      [ 96%]
framework/wazuh/tests/test_syscollector.py ............                               [ 96%]
framework/wazuh/tests/test_task.py ............................                       [ 98%]
framework/wazuh/tests/test_vulnerability.py ..........................                [100%]

================= 1643 passed, 12 skipped, 36 warnings in 265.13s (0:04:25) =================
</pre></p>
</details>  

#### API
<details><summary>API unit tests</summary>
<p><pre>
==================================== test session starts ====================================
platform linux -- Python 3.9.7, pytest-6.0.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/wazuh/git/wazuh/api
collected 451 items                                   [...]

2021-11-04 10:54 UTC, CarlosRS9 requested changes

2021-11-04 10:54 UTC, CarlosRS9 commented on wodles/utils.py
> +    Dynamically gets the Wazuh installation path.
```suggestion
    Get the Wazuh installation path.
```
Try to use infinitive for the docstrings. Review the rest of the docstrings.

2021-11-04 10:54 UTC, CarlosRS9 commented on wodles/utils.py
> +    Executes the wazuh-control script with the parameters specified.
Same as above

2021-11-10 16:14 UTC, CarlosRS9 approved these changes

2021-12-30 12:14 UTC, davidjiglesias approved these changes

2021-12-30 12:14 UTC, merged