Create tests for `worker.py` file
wazuh/wazuh pull request #10678
Opened 2021-10-28 13:53 UTC by yanazaeva

|Related issue|
|---|
|#9999|

## Description

Hi team,

This PR was created in order to update the unit tests. Raised the test coverage up to 100% for the `test_worker.py` test.

## Tests results
```
Name                                     Stmts   Miss  Cover   Missing
----------------------------------------------------------------------
framework/wazuh/core/cluster/worker.py     370      0   100%
----------------------------------------------------------------------
TOTAL                                      370      0   100%
```

2021-11-02 09:27 UTC, AdriiiPRodri requested changes

2021-11-02 09:27 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/tests/test_worker.py
> +            with patch("shutil.rmtree") as rmtree_mock:
Remove all unused alias

2021-11-02 09:27 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/tests/test_worker.py
> +            with patch("os.remove") as os_remove_mock:
Remove all unused alias

2021-11-02 09:27 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/tests/test_worker.py
> +                 call("Removing agent group assigments from database")], any_order=True)
Typo here and inside the tested function

2021-11-02 09:27 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/tests/test_worker.py
>                  assert expected_message in caplog.records[-(i+1)].message
```suggestion
                assert expected_message in caplog.records[-(i + 1)].message

```

2021-11-03 07:48 UTC, yanazaeva commented on framework/wazuh/core/cluster/tests/test_worker.py
> +import os
This one is used.

2021-11-03 07:49 UTC, yanazaeva commented on framework/wazuh/core/cluster/tests/test_worker.py
> +import json
This one is used too.

2021-11-16 08:28 UTC, AdriiiPRodri reviewed
This does not match with what is indicated in the issue (https://github.com/wazuh/wazuh/issues/9999#issuecomment-959405933): 
```
Name                                     Stmts   Miss  Cover   Missing
----------------------------------------------------------------------
framework/wazuh/core/cluster/worker.py     421     27    94%   791-802, 807-832, 872-875, 883-885
----------------------------------------------------------------------
TOTAL                                      421     27    94%
```

2022-01-24 12:38 UTC, yanazaeva commented
The checks executed in this commit were constantly failing due to the error attached [here.](https://github.com/wazuh/wazuh/files/7925529/test_worker_failure.zip) 

We had run these tests in a docker image that contains the exact environment used by Jenkins, and the tests were randomly passing and failing, so this pass seems to be random too. Further investigation is needed.

2022-01-26 10:07 UTC, AdriiiPRodri approved these changes

2022-01-26 10:42 UTC, davidjiglesias approved these changes

2022-01-26 10:42 UTC, merged