Improve `dapi.py` unittests and increase the overall coverage
wazuh/wazuh pull request #10689
Opened 2021-10-29 13:56 UTC by AdriiiPRodri

|Related issue|
|---|
|#10004|

This PR closes #10004. In this PR we have improved the existing unit tests for the dapi.py file. Now we set the behavior of the functions and improved the overall coverage of the file. The uncovered lines are not relevant because they are basic operations and make the complexity of the test to be greatly increased in case they are covered.

```
~/git/wazuh feature/10004-dapi-unittests *1 !1 ?2 ❯ PYTHONPATH=/mnt/c/Users/adr_i/git/wazuh/api:/mnt/c/Users/adr_i/git/wazuh/framework python3 -m coverage run --source=wazuh.core.cluster.dapi -m pytest -xs -vv framework/wazuh/core/cluster/dapi/tests/test_dapi.py
/home/adriiiprodri/.venvs/wazuh/lib/python3.9/site-packages/_testinfra_renamed.py:5: DeprecationWarning: testinfra package has been renamed to pytest-testinfra. Please `pip install pytest-testinfra` and `pip uninstall testinfra` and update your package requirements to avoid this message
  warnings.warn((
============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.9.5, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /home/adriiiprodri/.venvs/wazuh/bin/python3
cachedir: .pytest_cache
rootdir: /mnt/c/Users/adr_i/git/wazuh/framework
plugins: trio-0.7.0, asyncio-0.16.0, testinfra-6.0.0, testinfra-6.4.0, aiohttp-0.3.0
collected 30 items

framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI[kwargs0] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI[kwargs1] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_debug_log PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_distribute_function[get_agents_summary_status-local_master-master-local-True-None] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_distribute_function[restart_agents-distributed_master-master-forward-True-None] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_distribute_function[get_node_wrapper-local_any-worker-local-True-token_nbf_time] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_distribute_function[get_ciscat_results-distributed_master-worker-remote-True-None] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_distribute_function[status-local_master-worker-local-False-f_kwargs4] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_distribute_function[status-local_master-worker-local-False-None] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_distribute_function_mock_solver[restart_agents-distributed_master-master-local] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_distribute_function_exception PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_invalid_json PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_local_request_errors PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_local_request PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_get_client PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_remote_request_errors PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_remote_request PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_forward_request_errors PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_logger PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_tmp_file PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_tmp_file_cluster_error PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_get_solver_node PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_check_wazuh_status[get_agents_summary_status] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_check_wazuh_status[status] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_check_wazuh_status_exception[failed] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_check_wazuh_status_exception[restarting] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI_check_wazuh_status_exception[stopped] PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_APIRequestQueue_init PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_APIRequestQueue_run PASSED
framework/wazuh/core/cluster/dapi/tests/test_dapi.py::test_SendSyncRequestQueue_run PASSED

========================================================================================= 30 passed, 9 warnings in 2.75s =========================================================================================
```
```
~/git/wazuh feature/10004-dapi-unittests *1 !1 ?2 ❯ python3 -m coverage report -m                                                                                                                     4s Py wazuh
Name                                            Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------
framework/wazuh/core/cluster/dapi/__init__.py       0      0   100%
framework/wazuh/core/cluster/dapi/dapi.py         375     17    95%   177, 421-423, 451, 484-486, 515-516, 535, 539-543, 590, 656
-----------------------------------------------------------------------------
TOTAL                                             375     17    95%
```

2021-11-04 17:34 UTC, yanazaeva requested changes

2021-11-04 17:34 UTC, yanazaeva commented on framework/wazuh/core/cluster/dapi/tests/test_dapi.py
>          with patch('wazuh.core.cluster.cluster.get_node', return_value={'type': node}):
These mocks can be outside the test

2021-11-05 08:29 UTC, yanazaeva approved these changes

2021-11-11 11:42 UTC, davidjiglesias approved these changes

2021-11-11 11:42 UTC, merged