Add a variable for agent name length limit
wazuh/wazuh pull request #10700
Opened 2021-11-01 16:45 UTC by Kondent

|Related issue|
|---|
| This PR closes #10427 |

After this PR, the maximum permitted length for an agent name is set under a variable at `/core/common.py`.

Regards,
Alexis

2021-11-02 09:00 UTC, vicferpoy requested changes

2021-11-02 09:00 UTC, vicferpoy commented on framework/wazuh/core/common.py
> +agent_name_len_limit = 128
This should be in the `core/agent.py` module.

2021-11-02 13:53 UTC, Kondent commented
## Update
I left `exception.py` as is (with hardcoded maximum agent name length) since there are a few others length values that are being used that way.
https://github.com/wazuh/wazuh/blob/d5769017125968f8002f073a5327f64f75a35a85/framework/wazuh/core/exception.py#L303-L304
https://github.com/wazuh/wazuh/blob/d5769017125968f8002f073a5327f64f75a35a85/framework/wazuh/core/exception.py#L258-L259
https://github.com/wazuh/wazuh/blob/d5769017125968f8002f073a5327f64f75a35a85/framework/wazuh/core/exception.py#L537-L538

2021-11-03 08:52 UTC, vicferpoy approved these changes
LGTM

2021-11-11 11:54 UTC, davidjiglesias submitted a review, later dismissed

2021-11-11 16:43 UTC, davidjiglesias approved these changes

2021-11-11 16:43 UTC, merged