Update run_test script to run the API integration tests in the new standalone environment
wazuh/wazuh pull request #10709
Opened 2021-11-02 16:27 UTC by mcarmona99

|Related issue|
|---|
|#10594|

This PR closes #10594.

The run_test.py script has been updated to pass AIT using the new `standalone` and `cluster` marks.

The usage is the same, there aren't any new parameters or different behaviours. 

Some of the functions or code we already had in the script have been improved. Docstrings have also been added to make the code more human-readable.

`run_tests.py` examples:

### `-l` parameter

```
$ python3 run_tests.py -l test_cdb_list,test_overview
Collected tests [2]:
test_cdb_list_endpoints.tavern.yaml, test_overview_endpoints.tavern.yaml

test_cdb_list_endpoints.tavern.yaml - Standalone environment 
	 1 passed, 4 deselected, 9 warnings

test_cdb_list_endpoints.tavern.yaml - Cluster environment 
	 2 passed, 3 deselected, 9 warnings

test_overview_endpoints.tavern.yaml - Standalone environment 
	 1 passed, 4 warnings

test_overview_endpoints.tavern.yaml - Cluster environment 
	 1 deselected, 4 warnings
```

### `-k` and `-i`

```
$ python3 run_tests.py -k test_cdb -i 2
Collected tests [1]:
test_cdb_list_endpoints.tavern.yaml

test_cdb_list_endpoints.tavern.yaml - Standalone environment [1/2]
	 1 passed, 4 deselected, 9 warnings

test_cdb_list_endpoints.tavern.yaml - Cluster environment [1/2]
	 2 passed, 3 deselected, 9 warnings

test_cdb_list_endpoints.tavern.yaml - Standalone environment [2/2]
	 1 passed, 4 deselected, 9 warnings

test_cdb_list_endpoints.tavern.yaml - Cluster environment [2/2]
	 2 passed, 3 deselected, 9 warnings
```

```
$ ls _test_results/
 html_reports   logs  'test_cdb_list_endpoints_cluster'  'test_cdb_list_endpoints_cluster2'  'test_cdb_list_endpoints_standalone'  'test_cdb_list_endpoints_standalone2'
```

```
$ ls _test_results/html_reports/
'test_cdb_list_endpoints_cluster.html'  'test_cdb_list_endpoints_cluster2.html'  'test_cdb_list_endpoints_standalone.html'  'test_cdb_list_endpoints_standalone2.html'
```

### `-e` parameter

I only added the standalone and cluster marks to overview and cdb list endpoints API integration tests. This is why all are deselected.

```
$ python3 run_tests.py -e
Collected tests [64]:
test_active_response_endpoints.tavern.yaml, test_agent_DELETE_endpoints.tavern.yaml, test_agent_GET_endpoints.tavern.yaml, test_agent_POST_endpoints.tavern.yaml, test_agent_PUT_endpoints.tavern.yaml, test_ciscat_endpoints.tavern.yaml, test_cluster_endpoints.tavern.yaml, test_decoder_endpoints.tavern.yaml, test_default_endpoints.tavern.yaml, test_experimental_endpoints.tavern.yaml, test_logtest_endpoints.tavern.yaml, test_manager_endpoints.tavern.yaml, test_mitre_endpoints.tavern.yaml, test_overview_endpoints.tavern.yaml, test_rbac_black_active_response_endpoints.tavern.yaml, test_rbac_black_agent_endpoints.tavern.yaml, test_rbac_black_cdb_list_endpoints.tavern.yaml, test_rbac_black_ciscat_endpoints.tavern.yaml, test_rbac_black_cluster_endpoints.tavern.yaml, test_rbac_black_decoder_endpoints.tavern.yaml, test_rbac_black_experimental_endpoints.tavern.yaml, test_rbac_black_logtest_endpoints.tavern.yaml, test_rbac_black_manager_endpoints.tavern.yaml, test_rbac_black_mitre_endpoints.tavern.yaml, test_rbac_black_overview_endpoints.tavern.yaml, test_rbac_black_rootcheck_endpoints.tavern.yaml, test_rbac_black_rule_endpoints.tavern.yaml, test_rbac_black_sca_endpoints.tavern.yaml, test_rbac_black_security_endpoints.tavern.yaml, test_rbac_black_syscheck_endpoints.tavern.yaml, test_rbac_black_syscollector_endpoints.tavern.yaml, test_rbac_black_task_endpoints.tavern.yaml, test_rbac_black_vulnerability_endpoints.tavern.yaml, test_rbac_white_active_response_endpoints.tavern.yaml, test_rbac_white_agent_endpoints.tavern.yaml, test_rbac_white_all_endpoints.tavern.yaml, test_rbac_white_cdb_list_endpoints.tavern.yaml, test_rbac_white_ciscat_endpoints.tavern.yaml, test_rbac_white_cluster_endpoints.tavern.yaml, test_rbac_white_decoder_endpoints.tavern.yaml, test_rbac_white_experimental_endpoints.tavern.yaml, test_rbac_white_logtest_endpoints.tavern.yaml, test_rbac_white_manager_endpoints.tavern.yaml, test_rbac_white_mitre_endpoints.tavern.yaml, test_rbac_white_overview_endpoints.tavern.yaml, test_rbac_white_rootcheck_endpoints.tavern.yaml, test_rbac_white_rule_endpoints.tavern.yaml, test_rbac_white_sca_endpoints.tavern.yaml, test_rbac_white_security_endpoints.tavern.yaml, test_rbac_white_syscheck_endpoints.tavern.yaml, test_rbac_white_syscollector_endpoints.tavern.yaml, test_rbac_white_task_endpoints.tavern.yaml, test_rbac_white_vulnerability_endpoints.tavern.yaml, test_rootcheck_endpoints.tavern.yaml, test_rule_endpoints.tavern.yaml, test_sca_endpoints.tavern.yaml, test_security_DELETE_endpoints.tavern.yaml, test_security_GET_endpoints.tavern.yaml, test_security_POST_endpoints.tavern.yaml, test_security_PUT_endpoints.tavern.yaml, test_syscheck_endpoints.tavern.yaml, test_syscollector_endpoints.tavern.yaml, test_task_endpoints.tavern.yaml, test_vulnerability_endpoints.tavern.yaml

test_active_response_endpoints.tavern.yaml - Standalone environment 
	 2 deselected, 4 warnings

test_active_response_endpoints.tavern.yaml - Cluster environment 
	 2 deselected, 4 warnings

test_agent_DELETE_endpoints.tavern.yaml - Standalone environment 
	 6 deselected, 8 warnings

test_agent_DELETE_endpoints.tavern.yaml - Cluster environment 
	 6 deselected, 8 warnings

...

test_mitre_endpoints.tavern.yaml - Standalone environment 
	 7 deselected, 13 warnings

test_mitre_endpoints.tavern.yaml - Cluster environment 
	 7 deselected, 13 warnings

test_overview_endpoints.tavern.yaml - Standalone environment 
	 1 passed, 4 warnings

test_overview_endpoints.tavern.yaml - Cluster environment 
	 1 deselected, 4 warnings

...

test_vulnerability_endpoints.tavern.yaml - Standalone environment 
	 1 deselected, 3 warnings

test_vulnerability_endpoints.tavern.yaml - Cluster environment 
	 1 deselected, 3 warnings
```

### `-r` parameter

```
$ python3 run_tests.py -r
test_cdb_list_endpoints_standalone- Standalone environment
	 1 passed, 4 deselected, 9 warnings

test_cdb_list_endpoints_standalone2- Standalone environment
	 1 passed, 4 deselected, 9 warnings

test_cdb_list_endpoints_cluster- Cluster environment
	 2 passed, 3 deselected, 9 warnings

test_cdb_list_endpoints_cluster2- Cluster environment
	 2 passed, 3 deselected, 9 warnings
```

### `-rbac` parameter

```
$ python3 run_tests.py -k cdb -rbac yes
Collected tests [2]:
test_rbac_black_cdb_list_endpoints.tavern.yaml, test_rbac_white_cdb_list_endpoints.tavern.yaml

test_rbac_black_cdb_list_endpoints.tavern.yaml 
	 5 passed, 7 warnings

test_rbac_white_cdb_list_endpoints.tavern.yaml 
	 5 passed, 7 warnings
```

```
$ python3 run_tests.py -k cdb -rbac no
Collected tests [1]:
test_cdb_list_endpoints.tavern.yaml

test_cdb_list_endpoints.tavern.yaml - Standalone environment 
	 1 passed, 4 deselected, 9 warnings

test_cdb_list_endpoints.tavern.yaml - Cluster environment 
	 2 passed, 3 deselected, 9 warnings
```

```
$ python3 run_tests.py -k cdb -rbac both
Collected tests [3]:
test_cdb_list_endpoints.tavern.yaml, test_rbac_black_cdb_list_endpoints.tavern.yaml, test_rbac_white_cdb_list_endpoints.tavern.yaml

test_cdb_list_endpoints.tavern.yaml - Standalone environment 
	 1 passed, 4 deselected, 9 warnings

test_cdb_list_endpoints.tavern.yaml - Cluster environment 
	 2 passed, 3 deselected, 9 warnings

test_rbac_black_cdb_list_endpoints.tavern.yaml 
	 5 passed, 7 warnings

test_rbac_white_cdb_list_endpoints.tavern.yaml 
	 5 passed, 7 warnings
```

2021-11-10 13:57 UTC, mcarmona99 commented
## PR update

A new parameter has been added to the script. This parameter is `-mode` and it is used to choose between passing the tests in a standalone mode, cluster mode, or both modes (default).

The parameter is similar to the `-rbac` parameter.

```
$ python3 run_tests.py -k test_cdb -mode standalone
Collected tests [1]:
test_cdb_list_endpoints.tavern.yaml


test_cdb_list_endpoints.tavern.yaml - Standalone environment 
	 1 failed, 4 passed, 9 warnings


$ python3 run_tests.py -k test_cdb -mode standalon
usage: run_tests.py [options]
run_tests.py: error: argument -mode: invalid choice: 'standalon' (choose from 'both', 'standalone', 'cluster')


$ python3 run_tests.py -k test_cdb -mode cluster
Collected tests [1]:
test_cdb_list_endpoints.tavern.yaml


test_cdb_list_endpoints.tavern.yaml - Cluster environment 
...


$ python3 run_tests.py -k test_cdb -mode both
Collected tests [1]:
test_cdb_list_endpoints.tavern.yaml


test_cdb_list_endpoints.tavern.yaml - Standalone environment 
	 1 failed, 4 passed, 9 warnings

test_cdb_list_endpoints.tavern.yaml - Cluster environment 
	 1 failed, 4 passed, 9 warnings
```

2021-11-11 09:23 UTC, vicferpoy requested changes

2021-11-11 09:23 UTC, vicferpoy commented on api/test/integration/run_tests.py
>      parser.add_argument('-rbac', dest='rbac', default='both', choices=rbac_choices,
```suggestion
    parser.add_argument('-b', '--rbac', dest='rbac', default='both', choices=rbac_choices,
```

2021-11-11 09:23 UTC, vicferpoy commented on api/test/integration/run_tests.py
> +    parser.add_argument('-mode', dest='mode', default='both', choices=mode_choices,
```suggestion
    parser.add_argument('-m', '--mode', dest='mode', default='both', choices=mode_choices,
```

2021-11-16 09:50 UTC, mcarmona99 commented on api/test/integration/run_tests.py
>      parser.add_argument('-rbac', dest='rbac', default='both', choices=rbac_choices,
Done

2021-11-16 09:50 UTC, mcarmona99 commented on api/test/integration/run_tests.py
> +    parser.add_argument('-mode', dest='mode', default='both', choices=mode_choices,
Done

2021-11-16 10:15 UTC, mcarmona99 commented
## PR update

Script output with the new flags:

```
$ python3 run_tests.py -k cdb --mode=cluster -b no
Collected tests [1]:
test_cdb_list_endpoints.tavern.yaml


test_cdb_list_endpoints.tavern.yaml - Cluster environment 
	 1 failed, 4 deselected, 9 warnings
```

```
$ python3 run_tests.py -k overview --rbac=no
Collected tests [1]:
test_overview_endpoints.tavern.yaml


test_overview_endpoints.tavern.yaml - Standalone environment 
	 1 passed, 5 warnings

test_overview_endpoints.tavern.yaml - Cluster environment 
	 1 passed, 5 warnings
```

```
$ python3 run_tests.py -k overview -m standalone
Collected tests [3]:
test_overview_endpoints.tavern.yaml, test_rbac_black_overview_endpoints.tavern.yaml, test_rbac_white_overview_endpoints.tavern.yaml


test_overview_endpoints.tavern.yaml - Standalone environment 
	 1 passed, 5 warnings

test_rbac_black_overview_endpoints.tavern.yaml 
	 1 passed, 3 warnings

test_rbac_white_overview_endpoints.tavern.yaml 
	 1 passed, 3 warnings
```

2021-11-16 11:53 UTC, vicferpoy approved these changes
LGTM

2021-12-10 14:38 UTC, vicferpoy requested changes

2021-12-10 14:38 UTC, vicferpoy commented on api/test/integration/run_tests.py
> +    os.makedirs(os.path.join(TESTS_PATH, RESULTS_FOLDER, 'html_reports'), exist_ok=True)
```suggestion
    os.makedirs(os.path.join(TESTS_PATH, RESULTS_FOLDER, 'html_reports'), exist_ok=True)
```

2021-12-10 14:38 UTC, vicferpoy commented on api/test/integration/run_tests.py
> +    parser.add_argument('-b', '--rbac', dest='rbac', default='both', choices=rbac_choices,
```suggestion
    parser.add_argument('-R', '--rbac', dest='rbac', default='both', choices=rbac_choices,
```

2021-12-10 14:39 UTC, vicferpoy approved these changes
LGTM

2021-12-13 10:34 UTC, davidjiglesias approved these changes

2021-12-13 10:34 UTC, merged