Fix random values at cluster zip filenames to be cryptographically secure
wazuh/wazuh pull request #10710
Opened 2021-11-02 20:24 UTC by Kondent

|Related issue|
|---|
| This issue closes #10154 |

## Description
> With the test created in the issue [wazuh/wazuh-qa#1615](https://github.com/wazuh/wazuh-qa/issues/1615), some possible code flaws were found by Bandit.
> In this issue we specify flaws when using pseudo-random generators.

This PR aims to generate more randomness (or entropy) to the creation of random numbers that are being used at zip filenames during the integrity check between master and workers.
Although this zipped information is not that sensitive, In my opinion applying this patch is a good practice.

With this modification, I switched from `random()` to `uuid4()` which is a function of `uuid` library. More precisely I'm using `uuid4().hex` to generate random alphanumeric values.

Inside it, `uuid` uses `os.urandom` to generate randomness. This package can safely be called cryptographically secure.

Finally, the chance of two uuid4 values collide its not zero but it's close enough since we have 2^128 possible combination of values.

Regards,
Alexis.

---

## Zip filename sample:
`Schema: <node_name>-<timestamp>-<random_value>.zip`
**Before**: cd8c48262c1b-1635884495.0066996-**3726800461941797**.zip
**After**: cd8c48262c1b-1635884268.383864-**69cc7608abab4516909136faa05a0f5b**.zip

## Code Analysis Scan
```
↪ ~/Documents/work/issues/wazuh/10154 ⨘ cat before/known_flaws_framework.json | grep 'B311' -C 12
        },
        {
            "code": "     failed_files = list()\n     zip_file_path = path.join(common.wazuh_path, 'queue', 'cluster', name, f'{name}-{time()}-{str(random())[2:]}.zip')\n     if not path.exists(path.dirname(zip_file_path)):\n",
            "filename": "framework/wazuh/core/cluster/cluster.py",
            "issue_confidence": "HIGH",
            "issue_severity": "LOW",
            "issue_text": "Standard pseudo-random generators are not suitable for security/cryptographic purposes.",
            "line_number": 306,
            "line_range": [
                306
            ],
            "more_info": "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b311-random",
            "test_id": "B311",
            "test_name": "blacklist"
        }
    ]
}
↪ ~/Documents/work/issues/wazuh/10154 ⨘ cat after/known_flaws_framework.json | grep 'B311' -C 12
↪ ~/Documents/work/issues/wazuh/10154 ⨘ 
```

## UNIT TEST - FRAMEWORK
<details>
    <summary>Click to expand</summary>

```
↪ ~/git/wazuh/api ⊶ fix/10154-pseudo-random ⨘ cd ~/git/wazuh/framework && python3 -m pytest -x wazuh --disable-warnings
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.4.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/kondent/git/wazuh/framework
plugins: asyncio-0.15.1, cov-2.12.0
collected 1650 items                                                                                                                                                                         

wazuh/core/cluster/dapi/tests/test_dapi.py .........................                                                                                                                   [  1%]
wazuh/core/cluster/tests/test_cluster.py ...................                                                                                                                           [  2%]
wazuh/core/cluster/tests/test_common.py .......                                                                                                                                        [  3%]
wazuh/core/cluster/tests/test_control.py .....                                                                                                                                         [  3%]
wazuh/core/cluster/tests/test_local_client.py .                                                                                                                                        [  3%]
wazuh/core/cluster/tests/test_utils.py .......                                                                                                                                         [  3%]
wazuh/core/cluster/tests/test_worker.py .......                                                                                                                                        [  4%]
wazuh/core/tests/test_active_response.py ..............                                                                                                                                [  5%]
wazuh/core/tests/test_agent.py ....................................................................................................................................................... [ 14%]
...............                                                                                                                                                                        [ 15%]
wazuh/core/tests/test_cdb_list.py ......................................                                                                                                               [ 17%]
wazuh/core/tests/test_common.py .......                                                                                                                                                [ 17%]
wazuh/core/tests/test_configuration.py ....................................                                                                                                            [ 20%]
wazuh/core/tests/test_database.py .............                                                                                                                                        [ 20%]
wazuh/core/tests/test_decoder.py ................                                                                                                                                      [ 21%]
wazuh/core/tests/test_exception.py ...                                                                                                                                                 [ 22%]
wazuh/core/tests/test_input_validator.py ...                                                                                                                                           [ 22%]
wazuh/core/tests/test_logtest.py ..                                                                                                                                                    [ 22%]
wazuh/core/tests/test_manager.py ...............                                                                                                                                       [ 23%]
wazuh/core/tests/test_mitre.py .............                                                                                                                                           [ 24%]
wazuh/core/tests/test_pyDaemonModule.py .....                                                                                                                                          [ 24%]
wazuh/core/tests/test_results.py ........................................                                                                                                              [ 26%]
wazuh/core/tests/test_rootcheck.py .............                                                                                                                                       [ 27%]
wazuh/core/tests/test_rule.py ......................                                                                                                                                   [ 28%]
wazuh/core/tests/test_sca.py ............                                                                                                                                              [ 29%]
wazuh/core/tests/test_security.py ............                                                                                                                                [...]

2021-11-08 09:38 UTC, mcarmona99 requested changes
Why are you using `uuid4`?

It would be great if we had a comparison between the options given by the `uuid` library to generate universally unique identifiers: `uuid1`, `uuid3`, `uuid4` and `uuid5`.

2021-11-08 13:06 UTC, mcarmona99 approved these changes

2021-12-16 19:17 UTC, Kondent commented
## Update
* Wazuh QA PR: https://github.com/wazuh/wazuh-qa/pull/2352.

2021-12-30 12:21 UTC, davidjiglesias approved these changes

2021-12-30 12:21 UTC, merged