Improve CloudWatch Logs integration to handle ThrottlingExceptions and EndpointConnectionErrors
wazuh/wazuh pull request #10794
Opened 2021-11-10 12:25 UTC by CarlosRS9

|Related issue|
|---|
|#10754|

## Description

This PR updates the CloudWatch Log integration to be able to handle the `ThrottlingException` and `EndpointConnectionError` that may be raised by boto3 when AWS  is receiving too many requests from internal or external sources.

The module itself was not able to trigger the `ThrottlingException` as it is not fast enought to perform 10 requests per second, which is the quota for AWS CloudWatch. However, it needs to handle these exception to avoid crashing on loaded environments.

The solution is to catch the exception and retry the request again. It is difficult to generate more than 10 requests per second, so the probability of a second collision is quite remote. However, we have set a limit of 10 attempts to ensure that we do not fall into an infinite loop. If the limit is reached the execution will be aborted.

The module will show a warning error in the `ossec.log` if one or more `ThrottlingExceptions` were present during the execution.

## Manual testing

To be able to replicate the issue we created a custom script that sends request to AWS, so more that 10 requests per second were made. Having both this custom script and the Wazuh AWS module at the same time resulted in the expected `ThrottlingException` being raised. Our module handled this exception properly after the modifications.

Here is the example output when after 10 attempts the `ThrottlingException` was still present:
```
DEBUG: Getting CloudWatch logs from log stream "test_empty_logstream_17" in log group "framework-test-apache" using token "None", start_time "1636502400000" and end_time "None"
DEBUG: WARNING: The "get_log_events" request was denied due to request throttling. Attempting again.
DEBUG: WARNING: The "get_log_events" request was denied due to request throttling. Attempting again.
DEBUG: WARNING: The "get_log_events" request was denied due to request throttling. Attempting again.
DEBUG: WARNING: The "get_log_events" request was denied due to request throttling. Attempting again.
DEBUG: WARNING: The "get_log_events" request was denied due to request throttling. Attempting again.
DEBUG: WARNING: The "get_log_events" request was denied due to request throttling. Attempting again.
DEBUG: WARNING: The "get_log_events" request was denied due to request throttling. Attempting again.
DEBUG: WARNING: The "get_log_events" request was denied due to request throttling. Attempting again.
DEBUG: WARNING: The "get_log_events" request was denied due to request throttling. Attempting again.
DEBUG: WARNING: The "get_log_events" request was denied due to request throttling. Attempting again.
DEBUG: ERROR: The "get_log_events" request was denied due to request throttling. No more attempts allowed.
DEBUG: committing changes and closing the DB
```

Here is an example of a regular execution with a single `ThrottlingException` present:
```
DEBUG: Getting CloudWatch logs from log stream "test_empty_logstream_17" in log group "framework-test-apache" using token "None", start_time "1636502400000" and end_time "None"
DEBUG: WARNING: The "get_log_events" request was denied due to request throttling. Attempting again.
DEBUG: Saving data for log group "framework-test-apache" and log stream "test_empty_logstream_17".
DEBUG: The saved values are "{'token': 'f/36496186245198646477605549684830727907706970143704711167/s', 'start_time': 1636502400000, 'end_time': 1636502400000}"
```
During the second attempt the request was accepted and the log was processed as expected. No missing logs.

2021-11-10 15:23 UTC, noise-kngdm submitted a review, later dismissed
LGTM!

2021-11-11 10:49 UTC, davidjiglesias requested changes
Fix while loop and retries structure

2021-11-11 15:48 UTC, noise-kngdm approved these changes
LGTM!

2021-11-11 16:47 UTC, davidjiglesias approved these changes

2021-11-11 16:47 UTC, merged