Fix server access date parsing
wazuh/wazuh pull request #10811
Opened 2021-11-11 20:01 UTC by noise-kngdm

|Related issue|
|---|
|Closes #10810 |

## Description
In this PR we fix the way dates are parsed in the Server Access module, adding also information about the hour, minute and second of the last parsed log, which wasn't present yet.

## Tests performed:
#### Server Access
<details><summary>Last key = None, only logs = None</summary>
<p>
It only process todays logs, as expected.  

```
root@5ce46a6348a7:/var/ossec/wodles/aws# ./aws-s3 -b wazuh-aws-wodle-access -t server_access -d2 
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Table does not exist; create
DEBUG: +++ Marker: 2021-11-11
DEBUG: ++ Found new log: 2021-11-11-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping file with another prefix: test_empty/
DEBUG: ++ Skipping file with another prefix: test_prefix/
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-12-25-F92E1554CC549BEE
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-13-06-338835093EADA3C1
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-14-05-B61AAAC9147C7F9F
...
...
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-13-06-338835093EADA3C1
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-14-05-B61AAAC9147C7F9F
DEBUG: +++ DB Maintenance
DEBUG: +++ DB Maintenance
```
</p>

</details>

<details><summary>Last key = None, only logs set</summary>
<p>
It process all logs between the specified date and today.  

```
root@5ce46a6348a7:/var/ossec/wodles/aws# ./aws-s3 -b wazuh-aws-wodle-access -t server_access
 -d2  -s 2021-oct-20
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Table does not exist; create
DEBUG: +++ Marker: 2021-10-20
DEBUG: ++ Found new log: 2021-10-20-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Found new log: 2021-10-28-09-14-58-BB4F6867C1A7DDD7
DEBUG: ++ Found new log: 2021-11-09-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Found new log: 2021-11-11-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping file with another prefix: test_empty/
DEBUG: ++ Skipping file with another prefix: test_prefix/
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-12-25-F92E1554CC549BEE
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-13-06-338835093EADA3C1
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-14-05-B61AAAC9147C7F9F
...
...
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-13-06-338835093EADA3C1
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-14-05-B61AAAC9147C7F9F
DEBUG: +++ DB Maintenance
DEBUG: +++ DB Maintenance
```
</p>

</details>

<details><summary>Last key earlier in the past than only logs</summary>
<p>
It uses the date passed as only logs as marker instead of the last key, as expected.  

```
root@5ce46a6348a7:/var/ossec/wodles/aws# ./aws-s3 -b wazuh-aws-wodle-access -t server_access -d2  -s 2021-nov-11
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Marker: 2021-11-11
DEBUG: ++ Found new log: 2021-11-11-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping file with another prefix: test_empty/
DEBUG: ++ Skipping file with another prefix: test_prefix/
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-12-25-F92E1554CC549BEE
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-13-06-338835093EADA3C1
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-14-05-B61AAAC9147C7F9F
...
...
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-12-25-F92E1554CC549BEE
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-13-06-338835093EADA3C1
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-14-05-B61AAAC9147C7F9F
DEBUG: +++ DB Maintenance
DEBUG: +++ DB Maintenance
```
</p>

</details>

<details><summary>Last key set, only logs = None</summary>
<p>
It only collects todays' logs. This is currently being fixed in #9993.  

```
root@5ce46a6348a7:/var/ossec/wodles/aws# ./aws-s3 -b wazuh-aws-wodle-access -t server_access -d2     
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Marker: 2021-11-11
DEBUG: ++ Found new log: 2021-11-11-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping file with another prefix: test_empty/
DEBUG: ++ Skipping file with another prefix: test_prefix/
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-12-25-F92E1554CC549BEE
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-13-06-338835093EADA3C1
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-14-05-B61AAAC9147C7F9F
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-14-48-5273CCCAE2158DCE
...
...
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-12-25-F92E1554CC549BEE
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-13-06-338835093EADA3C1
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-14-05-B61AAAC9147C7F9F
DEBUG: +++ DB Maintenance
DEBUG: +++ DB Maintenance
```
</p>

</details>

<details><summary>Last key later in time than only logs</summary>
<p>
It uses the only_logs value as marker (this is being fixed for #9993) and collects all logs after that one, but only process the unprocessed ones, so there's no problem with this use-case.  

```
root@5ce46a6348a7:/var/ossec/wodles/aws# ./aws-s3 -b wazuh-aws-wodle-access -t server_access -d2  -s 2021-oct-10;
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Marker: 2021-10-10
DEBUG: ++ Skipping previously processed file: 2021-10-18-09-11-26-B9F9F891E8AAEB13
DEBUG: ++ Skipping previously processed file: 2021-10-18-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping previously processed file: 2021-10-19-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping previously processed file: 2021-10-20-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping previously processed file: 2021-10-28-09-14-58-BB4F6867C1A7DDD7
DEBUG: ++ Found new log: 2021-11-09-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Found new log: 2021-11-11-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping file with another prefix: test_empty/
DEBUG: ++ Skipping file with another prefix: test_prefix/
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-12-25-F92E1554CC549BEE
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-13-06-338835093EADA3C1
DEBUG: ++ Skipping file too old to process: test_prefix/2021-04-29-09-14-05-B61AAAC9147C7F9F
...
...
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-12-25-F92E1554CC549BEE
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-13-06-338835093EADA3C1
DEBUG: ++ Skipping file too old to process: test_prefix/test_subfolder/2021-04-29-09-14-05-B61AAAC9147C7F9F
DEBUG: +++ DB Maintenance
DEBUG: +++ DB Maintenance
```
</p>

</details>

2021-11-12 09:23 UTC, CarlosRS9 submitted a review, later dismissed

2021-11-12 13:02 UTC, CarlosRS9 requested changes

2021-11-12 13:02 UTC, CarlosRS9 commented on wodles/aws/aws_s3.py
> +                        debug(f"+++ WARNING: The format of the {bucket_file['Key']} filename isn't correct, skipping.", 1)
```suggestion
                        debug(f"+++ WARNING: The format of the {bucket_file['Key']} filename is not valid, skipping it.", 1)
```

2021-11-12 13:33 UTC, CarlosRS9 approved these changes

2021-11-15 09:17 UTC, davidjiglesias approved these changes

2021-11-15 09:17 UTC, merged