New fim sync options for fim/dbsync implementation
wazuh/wazuh pull request #10882
Opened 2021-11-17 10:14 UTC by JoseAntonioMHerrera

… for the old ones

|Related issue|
|---|
|#10224|

## Description

Added new db_entry_limit block to replace the old file_limit from ossec.conf and warn about the deprecated option.

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
- [X] Source installation

- Memory tests for Linux
  - [X] Valgrind (memcheck and descriptor leaks check)

2021-11-19 09:53 UTC, antoniomanuelfr approved these changes
LGTM

2021-11-19 09:57 UTC, antoniomanuelfr requested changes
In my previous review, I forgot to check the configuration on-demand. 

You will need to add these changes to the on-demand configuration in order to be able to get these new options using the API query.

Other than that, the PR looks good to me

2022-01-18 15:08 UTC, FrancoRivero approved these changes

2022-01-18 15:37 UTC, chemamartinez commented on src/config/syscheck-config.h
> +    int db_entry_file_limit;                           /* maximun number of files to monitor */
`maximun` -> `maximum`

2022-01-18 15:37 UTC, chemamartinez commented on src/config/syscheck-config.h
> +    int db_entry_registry_limit;                       /* maximun number of registries to monitor */
`maximun` -> `maximum`

2022-01-19 09:43 UTC, jotacarma90 commented on src/config/syscheck-config.h
> +    int db_entry_file_limit;                           /* maximun number of files to monitor */
Done

2022-01-19 09:43 UTC, jotacarma90 commented on src/config/syscheck-config.h
> +    int db_entry_registry_limit;                       /* maximun number of registries to monitor */
Done

2022-01-19 09:46 UTC, merged