Add multiprocessing to the cluster `extra-valid` sync task
wazuh/wazuh pull request #10920
Opened 2021-11-22 13:43 UTC by Selutario

|Related issue|
|---|
| Closes #10912 |

## Description

This PR adds multiprocessing to the extra-valid sync task in the master node. As a consequence, the `await asyncio.sleep(0)` function is not needed anymore, which should boost the performance of the extra-valid processing task as well as to other tasks in the `clusterd` process.

What is being achieved in this PR is:
1. Extra-valid files can be processed in a child `clusterd` process of the master node, so the parent process doesn't need to waste time with this task.
2. If there is more than one free process in the pool, extra-valid files from coming from different worker nodes can be updated in parallel.

It is important to note that now there are 3 (heavy) tasks being run in the process pool, so its size should be updated in consequence, if needed, to achieve a better performance:
- Local integrity
- Agent-info sync (sending chunks of data to wazuh-db)
- Extra-valid files processing.

2021-11-22 14:38 UTC, AdriiiPRodri approved these changes
LGTM!

2021-11-24 08:31 UTC, AdriiiPRodri requested changes

2021-11-24 08:31 UTC, AdriiiPRodri commented on framework/wazuh/core/utils.py
> +from signal import signal, alarm, SIGALRM
Remove unused import

2021-11-24 08:40 UTC, AdriiiPRodri approved these changes

2021-11-24 12:23 UTC, davidjiglesias approved these changes

2021-11-24 12:23 UTC, merged