Fix non sorted ids in API response
wazuh/wazuh pull request #11010
Opened 2021-11-25 18:50 UTC by Kondent

|Related issue|
|---|
|This PR closes #10733 |

## Description
After reviewing this situation in more depth I noticed there are a few options to pick between. For example, doing this default sort at `expose_resources` in `decorators.py`.

https://github.com/wazuh/wazuh/blob/a8122d460d3eb8165a4cd90c58ae28fd9e39bc11/framework/wazuh/rbac/decorators.py#L399-L404

More precisely, It could be sorted at `kwargs[target_param] = list(allow[res_id])`. [_This is well-explained at the related issue._](https://github.com/wazuh/wazuh/issues/10593#issuecomment-960624241)

As we discussed with the team, sorting a list is not the expected behaviour of this decorator. Instead, it should be done inside the SDK corresponding method.

I added a fix just for `affected_items` since I checked that `failed_items` are already sorted.

Finally, if the Cluster is enabled or `affected_items` are already sorted, this will be a little bit redundant but practically no overhead will be added since `sort()` uses `Timsort` which runs in linear time for those cases.

Regards,
Alexis

## Related Integration Tests:
```s
test_active_response_endpoints.tavern.yaml:
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.0.0, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/inttest-env/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.5', 'Platform': 'Linux-5.11.0-40-generic-x86_64-with-glibc2.31', 'Packages': {'pytest': '5.0.0', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.11.0', 'tavern': '1.2.2'}}
rootdir: /home/kondent/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, metadata-1.11.0, tavern-1.2.2
collected 2 items                                                                                                                                                                            

test_active_response_endpoints.tavern.yaml::PUT /active-response/{:agent_id} PASSED                                                                                                    [ 50%]
test_active_response_endpoints.tavern.yaml::PUT /active-response PASSED                                                                                                                [100%]

=========================================================================== 2 passed, 1 warnings in 111.43 seconds ===========================================================================

test_rbac_black_active_response_endpoints.tavern.yaml:
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.0.0, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/inttest-env/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.5', 'Platform': 'Linux-5.11.0-40-generic-x86_64-with-glibc2.31', 'Packages': {'pytest': '5.0.0', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.11.0', 'tavern': '1.2.2'}}
rootdir: /home/kondent/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, metadata-1.11.0, tavern-1.2.2
collected 2 items                                                                                                                                                                            

test_rbac_black_active_response_endpoints.tavern.yaml::PUT ACTIVE-RESPONSE OVER A LIST OF AGENTS PASSED                                                                                [ 50%]
test_rbac_black_active_response_endpoints.tavern.yaml::PUT /active-response PASSED                                                                                                     [100%]

=========================================================================== 2 passed, 1 warnings in 111.61 seconds ===========================================================================

test_rbac_white_active_response_endpoints.tavern.yaml:
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.0.0, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/inttest-env/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.5', 'Platform': 'Linux-5.11.0-40-generic-x86_64-with-glibc2.31', 'Packages': {'pytest': '5.0.0', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.11.0', 'tavern': '1.2.2'}}
rootdir: /home/kondent/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, metadata-1.11.0, tavern-1.2.2
collected 2 items                                                                                                                                                                            

test_rbac_white_active_response_endpoints.tavern.yaml::PUT ACTIVE-RESPONSE OVER A LIST OF AGENTS PASSED                                                                                [ 50%]
test_rbac_white_active_response_endpoints.tavern.yaml::PUT /active-response PASSED                                                                                                     [100%]

=========================================================================== 2 passed, 1 warnings in 110.57 seconds ===========================================================================
```

2021-12-03 13:08 UTC, mcarmona99 requested changes
Review get_agents_keys function in wazuh/agent.py as sort may not be done here.
In truth this is not totally necessary because we will always receive only 1 agent in the agents_list parameter of get_agents_keys, but in order to maintain the consistency, we should also sort the response here.

This is also related to the framework independence of other modules.

<details>

<summary>get_agents_keys</summary>

```
@expose_resources(actions=["agent:read"], resources=["agent:id:{agent_list}"],
                  post_proc_kwargs={'exclude_codes': [1701]})
def get_agents_keys(agent_list=None):
    """Get the key of existing agents.

    :param agent_list: List of agents ID's.
    :return: AffectedItemsWazuhResult.
    """
    result = AffectedItemsWazuhResult(all_msg='Obtained keys for all selected agents',
                                      some_msg='Some agent keys were not obtained',
                                      none_msg='No agent keys were obtained'
                                      )
    system_agents = get_agents_info()
    for agent_id in agent_list:
        try:
            if agent_id not in system_agents:
                raise WazuhResourceNotFound(1701)
            result.affected_items.append({'id': agent_id, 'key': Agent(agent_id).get_key()})
        except WazuhException as e:
            result.add_failed_item(id_=agent_id, error=e)
    result.total_affected_items = len(result.affected_items)

    return result
```

</details>

The same is happening for the get_agents_sync_group function.
Same for function get_last_scan in rootcheck.py.
The sort in the run function from rootcheck.py may not be needed as there is a WazuhDBQueryAgents call.

Also, change the outdated functions docstrings to Numpy Doc.
The remove_user_role function of security.py has a wrong description, review it in this PR since it is a minor change that can be included here, in my opinion.

2021-12-06 15:48 UTC, Kondent commented
## Agent:
`get_agents_keys`: this method is able to handle just one agent ID if it's called from the Wazuh API endpoint.
But, reviewing this is more depth, its output must be sorted since it can be called from the framework, with a full agent list.

`get_agents_sync_group`: same as above, it can be called directly from our framework.

## Rootcheck:
`get_last_scan`: at this method I think it's not necessary to sort since its forced to pick the first one on the list and won't be using the entire list even if its called from the framework.
```py
    result.affected_items.append(last_scan(agent_list[0]))
    result.total_affected_items = len(result.affected_items)
```

`run`: I reviewed this and there's no need to do a sort since `WazuhDBQueryAgents` is being called.

## Security:
Fixed doc string from `remove_user_role`.

## Other:
I reviewed a few modules to check their docstring and it seems like there are several methods that have it wrong formatted.
I think this should be handled in another issue.

2021-12-09 14:27 UTC, mcarmona99 approved these changes
LGTM

2021-12-10 09:36 UTC, davidjiglesias approved these changes

2021-12-10 09:36 UTC, davidjiglesias approved these changes

2021-12-10 09:37 UTC, merged