Rework of PRs #10025 and #10046 -  Rules and Decoders for ESET Remote Administrator
wazuh/wazuh pull request #11013
Opened 2021-11-25 19:34 UTC by xrisbarney

|Related issue|
|---|
|#10970 |

## Description

This PR aims to resolve issues detected under #10025 and #10046 PRs. Closes #10970 

## Checks and changes 

### Syntax

- [ ] 1.a
- [ ] 1.b
- [ ] 1.c
- [ ] 1.d
- [ ] 1.e
- [ ] 1.f

### Grammar

- [ ] 2.a
- [ ] 2.b
- [ ] 2.c
- [ ] 2.d

### Semantic

- [ ] 3.a
- [ ] 3.b
- [ ] 3.c
     - [ ] 3.c1
     - [ ] 3.c2
     - [ ] 3.c3
     - [ ] 3.c4
- [ ] 3.d

### Unit testing

- [ ] 4.a
- [ ] 4.b
- [ ] 4.c
- [ ] 4.d
- [ ] 4.e
- [ ] 4.f

### E2E testing

- [ ] 5.a
- [ ] 5.b
- [ ] 5.c

### Elasticsearch Template

- [ ] 6.a
- [ ] 6.b
- [ ] 6.c
- [ ] 6.d

### Stoppers

- [ ] 7.a
- [ ] 7.b
- [ ] 7.c
- [ ] 7.d

### Others

- [ ] 8.a
- [ ] 8.b
- [ ] 8.c
- [ ] 8.d
- [ ] 8.e
- [ ] 8.f
- [ ] 8.g
- [ ] 8.h
- [ ] 8.i
- [ ] 8.j
- [ ] 8.k

2021-11-26 09:47 UTC, jcruzlp requested changes

2021-11-26 09:47 UTC, jcruzlp commented on ruleset/decoders/0575-eset-remote_decoders.xml
> +  This program is a free software; you can redistribute it and/or modify it under the terms of GPLv2.
New copyright block is this one:
```xml
<!--
  Copyright (C) 2015-2021, Wazuh Inc.
-->
```

2021-11-26 09:47 UTC, jcruzlp commented on ruleset/decoders/0575-eset-remote_decoders.xml
> +-->
Comment's can't have `-`, check 8c

2021-11-26 09:47 UTC, jcruzlp commented on ruleset/rules/0925-eset-remote_rules.xml
> +-->
Ditto

2021-11-26 09:47 UTC, jcruzlp commented on ruleset/rules/0925-eset-remote_rules.xml
> +    <description>Eset console logs.</description>
It should be ESET: <info>

2021-11-26 10:22 UTC, xrisbarney commented on ruleset/rules/0925-eset-remote_rules.xml
> +    <description>Eset console logs.</description>
Fixed, thanks.

2021-11-26 10:23 UTC, xrisbarney commented on ruleset/rules/0925-eset-remote_rules.xml
> +-->
Resolved.

2021-11-30 09:14 UTC, 72nomada requested changes
In parent decoder force to ensure only ESETSerer is consider

2021-11-30 09:14 UTC, 72nomada commented on ruleset/decoders/0575-eset-remote_decoders.xml
> +  May  6 10:59:37 XXXXX ERAServer[5032]: {"event_type":"Audit_Event","ipv4":"XXX.XXX.XXX.XXX","hostname":"XXXXX","source_uuid":"9416183d-3XX3-4776-9783-9532a3a027bb","occured":"06-May-2021 09:59:37",
indent

2021-11-30 09:14 UTC, 72nomada commented on ruleset/decoders/0575-eset-remote_decoders.xml
>    <program_name>ERAServer</program_name>
make program_name restricted as possible: 

`^ERAServer$`

2021-12-01 08:25 UTC, jcruzlp approved these changes
LGTM!

2021-12-01 09:23 UTC, 72nomada approved these changes
LGTM

2021-12-01 09:45 UTC, Spades0 commented
LGTM

2021-12-07 00:56 UTC, fabamatic approved these changes
LGTM

2021-12-07 00:56 UTC, fabamatic commented on ruleset/decoders/0575-eset-remote_decoders.xml
> +  <program_name>^ERAServer$</program_name>
Are you sure about this change?

2021-12-07 00:56 UTC, fabamatic commented on ruleset/decoders/0575-eset-remote_decoders.xml
> +  <program_name>^ERAServer$</program_name>
I mean, no version number or anything like that can come appended to program name?

2021-12-15 17:17 UTC, JcabreraC commented
# Test output
`# python2 runtests.py `
```bash

- [ File = ./tests/apparmor.ini ] ---------
.....

- [ File = ./tests/ossec.ini ] ---------
.....

- [ File = ./tests/mailscanner.ini ] ---------
.

- [ File = ./tests/vsftpd.ini ] ---------
....

- [ File = ./tests/gitlab.ini ] ---------
.........................

- [ File = ./tests/aws_s3_access.ini ] ---------
.......

- [ File = ./tests/opensmtpd.ini ] ---------
.......

- [ File = ./tests/paloalto.ini ] ---------
................

- [ File = ./tests/nextcloud.ini ] ---------
.......

- [ File = ./tests/nginx.ini ] ---------
............

- [ File = ./tests/netscreen.ini ] ---------
....

- [ File = ./tests/auditd.ini ] ---------
...

- [ File = ./tests/cisco_ftd.ini ] ---------
..........................................

- [ File = ./tests/kernel_usb.ini ] ---------
......

- [ File = ./tests/openldap.ini ] ---------
.........

- [ File = ./tests/huawei_usg.ini ] ---------
...

- [ File = ./tests/api.ini ] ---------
............................

- [ File = ./tests/doas.ini ] ---------
....

- [ File = ./tests/cpanel.ini ] ---------
.......

- [ File = ./tests/office365.ini ] ---------
................................................................................................................................

- [ File = ./tests/postfix.ini ] ---------
..

- [ File = ./tests/firewalld.ini ] ---------
..

- [ File = ./tests/rsh.ini ] ---------
..

- [ File = ./tests/exchange.ini ] ---------
..

- [ File = ./tests/sudo.ini ] ---------
........

- [ File = ./tests/arbor.ini ] ---------
..

- [ File = ./tests/sophos-utm-firewall.ini ] ---------
......

- [ File = ./tests/icinga.ini ] ---------
....

- [ File = ./tests/exim.ini ] ---------
.......

- [ File = ./tests/pam.ini ] ---------
.....

- [ File = ./tests/named.ini ] ---------
.....

- [ File = ./tests/oscap.ini ] ---------
................................

- [ File = ./tests/SonicWall.ini ] ---------
........

- [ File = ./tests/proftpd.ini ] ---------
.......

- [ File = ./tests/sysmon.ini ] ---------
...

- [ File = ./tests/fortiauth.ini ] ---------
....

- [ File = ./tests/modsecurity.ini ] ---------
......

- [ File = ./tests/f5_big_ip.ini ] ---------
...........................................

- [ File = ./tests/cimserver.ini ] ---------
..

- [ File = ./tests/iptables.ini ] ---------
........

- [ File = ./tests/syslog.ini ] ---------
......

- [ File = ./tests/junos.ini ] ---------
...

- [ File = ./tests/cloudlfare-waf.ini ] ---------
.............

- [ File = ./tests/trendmicro-cloud-one.ini ] ---------
.................

- [ File = ./tests/mcafee_epo.ini ] ---------
.

- [ File = ./tests/web_appsec.ini ] ---------
...............................

- [ File = ./tests/sophos.ini ] ---------
........

- [ File = ./tests/dovecot.ini ] ---------
...............

- [ File = ./tests/web_rules.ini ] ---------
..........

- [ File = ./tests/github.ini ] ---------
....................................................................................................................................................................................................................................................................................................................................

- [ File = ./tests/owlh.ini ] ---------
....

- [ File = ./tests/cisco_asa.ini ] ---------
........................................................................................

- [ File = ./tests/su.ini ] ---------
.....

- [ File = ./tests/gcp.ini ] ---------
...........

- [ File = ./tests/sshd.ini ] ---------
...........................................

- [ File = ./tests/panda_paps.ini ] ---------
........

- [ File = ./tests/freepbx.ini ] ---------
......

- [ File = ./tests/fireeye.ini ] ---------
...

- [ File = ./tests/cisco_ios.ini ] ---------
.................

- [ File = ./tests/pfsense.ini ] ---------
..

- [ File = ./tests/cylance.ini ] ---------
.......

- [ File = ./tests/dropbear.ini ] ---------
...

- [ File = ./tests/pix.ini ] ---------
......................

- [ File = ./tests/squid_rules.ini ] ---------
..

- [ File = ./tests/samba.ini ] ---------
....

- [ File = ./tests/sophos_fw.ini ] ---------
..........

- [ File = ./tests/audit_recon.ini ] ---------
..

- [ File = ./tests/audit_scp.ini ] ---------
.

- [ File = ./tests/glpi.ini ] ---------
...

- [ File = ./tests/apache.ini ] ---------
..................

- [ File = ./tests/eset.ini ] ---------
........

- [ File = ./tests/checkpoint_smart1.ini ] ---------
..................

- [ File = ./tests/fortigate.ini ] ---------
........................................

- [ File = ./tests/unbound.ini ] ---------


- [ File = ./tests/audit_lateral.ini ] ---------
......

- [ File = ./tests/openvpn_ldap.ini ] ---------
..

- [ File = ./tests/systemd.ini ] ---------
..

- [ File = ./tests/vuln_detector.ini ] ---------
..
```

2021-12-17 10:40 UTC, JcabreraC approved these changes
LGTM !

2021-12-21 11:58 UTC, merged