Improve remoted guess logic
wazuh/wazuh pull request #11491
Opened 2021-12-23 18:45 UTC by MiguelazoDS

|Related issue|
|---|
|#11446|

## Description

This PR makes the remote guess logic to use the new implementation in #11006. 

## Dod

Force to not found the group for agent.
![2](https://user-images.githubusercontent.com/13010397/147280140-8215486e-750b-4345-ad58-03f843eff00d.png)
Group couldn't not be guessed, so a `default` group is assigned. 
![7](https://user-images.githubusercontent.com/13010397/147280149-dd1bacb3-9f8f-47c4-bfa1-c7f62fb11f52.png)
During the remoted guessing step information is stored in the database.
![4](https://user-images.githubusercontent.com/13010397/147280563-65cae8d8-0054-4b4e-bccf-ffdd94ae935d.png)
The guessed information is not stored in the database as this is not empty.
![8](https://user-images.githubusercontent.com/13010397/147280152-3a412432-8102-428d-9b9c-31e349aed291.png)
Group information in agent database.
![9](https://user-images.githubusercontent.com/13010397/147280153-398f5171-5d71-4b98-aec5-8ad9112c4969.png)
Scan-build report.
![10](https://user-images.githubusercontent.com/13010397/147280156-b5f1ff06-d129-45ef-9796-741562067073.png)

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
- [X] Source installation
- [X] Review logs syntax and correct language

- Memory tests for Linux
  - [X] Scan-build report

2022-01-03 18:24 UTC, MiguelazoDS commented
## Guess logic

Force to not find the group for an agent.
![image](https://user-images.githubusercontent.com/13010397/147964057-2601a563-be20-47e8-94f3-a8f89be4e8c9.png)
The group couldn't be guessed, so the `group` variable is assigned with `default` value. 
![7](https://user-images.githubusercontent.com/13010397/147280149-dd1bacb3-9f8f-47c4-bfa1-c7f62fb11f52.png)
Before attempting to store the information in `group` variable. New group information is written in the database.
![4](https://user-images.githubusercontent.com/13010397/147280563-65cae8d8-0054-4b4e-bccf-ffdd94ae935d.png)
The information is not stored in the database as this is not empty.
![image](https://user-images.githubusercontent.com/13010397/147965288-e71266c0-83c4-4822-b8c6-812661d3b3e5.png)

2022-01-03 19:48 UTC, MiguelazoDS commented
## Authd 

Groups A,B created
![image](https://user-images.githubusercontent.com/13010397/147972689-323d4bcf-67ed-489d-81e0-3a7745b5c573.png)
Regitering agent with `agent-auth`
![image](https://user-images.githubusercontent.com/13010397/147972970-b3d54b0c-8879-4394-8900-6e56389cbf9a.png)
![image](https://user-images.githubusercontent.com/13010397/147973029-46b182a1-7aee-4547-ad43-e47490e7e3a2.png)
Belongs table for new agent 4
![image](https://user-images.githubusercontent.com/13010397/147973156-456695df-d388-416b-86c9-5094cef5e071.png)
Agent table for new agent 4
![image](https://user-images.githubusercontent.com/13010397/147973245-99837180-1f61-40b6-919b-b172acc08e63.png)

2022-01-03 22:36 UTC, MiguelazoDS commented
## Shared download

Information obtained from `files.yml`
![image](https://user-images.githubusercontent.com/13010397/147987526-70b27e93-dea7-40a2-8d44-fedb84f1db5e.png)
Groups created
![image](https://user-images.githubusercontent.com/13010397/147987684-edf5a39a-ae58-45bb-a8d0-25b469ddd8f0.png)
Belongs table updated for agent 3
![image](https://user-images.githubusercontent.com/13010397/147987712-805e83bc-4f9e-46bf-8a21-a58aadeb8f5d.png)
Agent table updated for agent 3
![image](https://user-images.githubusercontent.com/13010397/147987802-9d30a762-0afe-489b-bcc6-255477ac9842.png)

2022-01-05 16:04 UTC, palaciosjeremias requested changes
LGTM Just minor observations.

2022-01-05 16:56 UTC, MiguelazoDS commented on src/wazuh_db/wdb.h
> +#define WDB_GROUP_MODE_EMPTY_ONLY "empty_only"
Added

2022-01-05 16:56 UTC, MiguelazoDS commented on src/os_auth/main-server.c
> +                                             NULL)) {
Thanks, fixed.

2022-01-06 01:05 UTC, palaciosjeremias approved these changes
LGTM.
For this Code Review the following aspects were considered:
- Correct sockets usage
- Functionality
- Every legacy code is removed.

2022-01-06 20:32 UTC, DProvinciani approved these changes
Looks good!

2022-01-06 20:32 UTC, merged