add windows process start_time
wazuh/wazuh pull request #11640
Opened 2021-12-31 03:23 UTC by LubinLew

|Related issue|
|---|
|-|

## Description

add windows process start_time

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [x] Windows
  - [ ] MAC OS X
- [x] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [x] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-01-04 01:37 UTC, jnasselle requested changes
Hi @LubinLew,

Thanks again for your contributions!Amazing job! Current PR LGTM, but the branch was created from 4.3 branch and trying to be merged to master. This should be changed and created from master.

Regards,
Nico

2022-01-04 02:07 UTC, LubinLew commented
Hi @jnasselle ,

I Merged master into this PR branch, Can this meet the requirements?
I used the master branch at first, but there will be sqlite3 link errors, so I used 4.3 branch.

2022-01-04 06:39 UTC, Dwordcito commented
@LubinLew 
if you run (from the src folder) `rm -rf external/* && make deps TARGET=agent && make TARGET=agent` does the problem persist?
between different versions of wazuh the external dependencies vary, which can cause a link problem.

2022-01-04 07:00 UTC, LubinLew commented
@Dwordcito 

It works after cleaning the external dependencies.

Thanks.

2022-01-06 23:38 UTC, jnasselle commented
## End-to-end testing :green_circle: 
![kibana](https://user-images.githubusercontent.com/1791430/148467631-db639e58-3e2c-4046-9eaf-8f5018e268d6.PNG)
![conversion](https://user-images.githubusercontent.com/1791430/148467633-0dcd9445-4f97-48ef-a1e3-cd7a5816157c.PNG)
![processexplorer](https://user-images.githubusercontent.com/1791430/148467634-2d8859e7-bd24-48a8-aff1-eafc80441c07.PNG)

2022-01-07 14:04 UTC, jnasselle approved these changes

2022-01-13 15:33 UTC, RamiroRD commented on src/data_provider/src/sysInfoWin.cpp
> +            constexpr auto WINDOWS_UNIX_EPOCH_DIFF_SECONDS { 11644473600ULL };
Maybe we could leave a comment explaining where this was taken from

2022-01-13 20:53 UTC, HanesSciarrone approved these changes

2022-01-14 01:32 UTC, jnasselle approved these changes

2022-01-14 02:52 UTC, HanesSciarrone approved these changes

2022-01-18 14:46 UTC, Dwordcito approved these changes

2022-01-22 05:23 UTC, merged