Added log messages, hide wazuh-db configuration
wazuh/wazuh pull request #11778
Opened 2022-01-11 23:01 UTC by MiguelazoDS

|Related issue|
|---|
|#11777|

## Description

This PR adds some log messages and makes the wazuh-DB configuration hidden.

## Dod

Starting thread log

![1](https://user-images.githubusercontent.com/13010397/149034789-c4a0d46b-68e2-4176-86e9-4b1a745bd8ea.png)

Database backup creation log.

![2](https://user-images.githubusercontent.com/13010397/149034792-d2d26e78-d5b9-4ec5-b722-a097779f413e.png)

Database backup deletion log.
![3](https://user-images.githubusercontent.com/13010397/149034795-c95d20f2-4729-4f34-93a4-d0df8098e12e.png)

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
- [X] Source installation
- [X] Source upgrade

2022-01-12 15:24 UTC, DProvinciani approved these changes
Looks good!

2022-01-13 16:04 UTC, DProvinciani requested changes
Just a minor comment to improve the logs.

2022-01-13 16:04 UTC, DProvinciani commented on src/wazuh_db/wdb_parser.c
> +            merror("Creating Global DB snapshot by request failed: %s", output);
I would say `... snapshot on demand failed ...`

2022-01-13 17:47 UTC, MiguelazoDS commented on src/wazuh_db/wdb_parser.c
> +            merror("Creating Global DB snapshot by request failed: %s", output);
Changed!

2022-01-13 17:50 UTC, DProvinciani approved these changes
Looks good!

2022-01-13 17:50 UTC, merged