Handle PID files for child processes on Wazuh API and cluster
wazuh/wazuh pull request #11799
Opened 2022-01-13 11:48 UTC by vicferpoy

|Related issue|
|---|
|closes #11606 |

## Description

In addition to the original issue, a few related bugs have been fixed. Now, the Wazuh API and cluster will handle the PID files for their child processes.

No matter the use case, all processes will end gracefully and the PID files will be deleted. Only a kill signal will prevent the files from being deleted, but a mechanism to delete them once the service starts again has been added.

Wazuh API

```shellsession
-rw-r-----. 1 wazuh wazuh    5 Jan 13 11:05 wazuh-apid-1871.pid
-rw-r-----. 1 wazuh wazuh    5 Jan 13 11:06 wazuh-apid_auth-2089.pid
-rw-r-----. 1 wazuh wazuh    5 Jan 13 11:06 wazuh-apid_exec-2086.pid
```

Wazuh Cluster (depending on the number of child processes)

```shellsesion
-rw-r-----. 1 wazuh wazuh    5 Jan 13 11:06 wazuh-clusterd-2296.pid
-rw-r-----. 1 wazuh wazuh    5 Jan 13 11:06 wazuh-clusterd_child_0-2299.pid
-rw-r-----. 1 wazuh wazuh    5 Jan 13 11:06 wazuh-clusterd_child_1-2302.pid
```

## Tests performed

### Manual tests

- Foreground

```shellsession
root@wazuh-master:/# /var/ossec/bin/wazuh-apid -f
Starting API in foreground
2022/01/13 11:24:25 INFO: Listening on 0.0.0.0:55000..
======== Running on https://0.0.0.0:55000 ========
(Press CTRL+C to quit)

root@wazuh-master:/# ps -edf ww | grep api
root        3182    1655  0 11:24 pts/1    S+     0:00 /bin/sh /var/ossec/bin/wazuh-apid -f
wazuh       3187    3182 19 11:24 pts/1    Sl+    0:07 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py -f
wazuh       3188    3187  0 11:24 pts/1    S+     0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py -f
wazuh       3191    3187  0 11:24 pts/1    S+     0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py -f

root@wazuh-master:/# ll /var/ossec/var/run/ | grep api
-rw-r-----. 1 wazuh wazuh   5 Jan 13 11:24 wazuh-apid-3187.pid
-rw-r-----. 1 wazuh wazuh   5 Jan 13 11:24 wazuh-apid_auth-3191.pid
-rw-r-----. 1 wazuh wazuh   5 Jan 13 11:24 wazuh-apid_exec-3188.pid
```

After pressing `CTRL+C`.

```shellsession
root@wazuh-master:/# ll /var/ossec/var/run/ | grep api
root@wazuh-master:/#

root@wazuh-master:/# ps -edf ww | grep api
root        3205    2213  0 11:26 pts/3    S+     0:00 grep --color=auto api
root@wazuh-master:/#
```

- Background

```shellsession
root@wazuh-master:/# ps -edf ww | grep api
wazuh       3262       1 45 11:26 ?        Sl     0:06 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh       3352    3262  0 11:26 ?        S      0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh       3355    3262  0 11:26 ?        S      0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py

root@wazuh-master:/# ll /var/ossec/var/run/ | grep api
-rw-r-----. 1 wazuh wazuh    5 Jan 13 11:26 wazuh-apid-3262.pid
-rw-r-----. 1 wazuh wazuh    5 Jan 13 11:26 wazuh-apid_auth-3355.pid
-rw-r-----. 1 wazuh wazuh    5 Jan 13 11:26 wazuh-apid_exec-3352.pid
```

After killing the main process (trying to kill a child process without `kill -9` will not do anything).

```shellsession
root@wazuh-master:/# kill 3262

root@wazuh-master:/# ps -edf ww | grep api
root        4405    2213  0 11:28 pts/3    S+     0:00 grep --color=auto api

root@wazuh-master:/# ll /var/ossec/var/run/ | grep api
root@wazuh-master:/# 

```

- Using `kill -9` on either mode

```shellsession
root@wazuh-master:/# ps -edf ww | grep api
wazuh       9961       1  9 11:42 ?        Sl     0:06 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh      10030    9961  0 11:42 ?        S      0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh      10033    9961  0 11:42 ?        S      0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py

root@wazuh-master:/# ll /var/ossec/var/run/ | grep api
-rw-r-----. 1 wazuh wazuh    5 Jan 13 11:42 wazuh-apid-9961.pid
-rw-r-----. 1 wazuh wazuh    6 Jan 13 11:42 wazuh-apid_auth-10033.pid
-rw-r-----. 1 wazuh wazuh    6 Jan 13 11:42 wazuh-apid_exec-10030.pid

```

Killing one of the processes with `kill -9`.

```shellsession
root@wazuh-master:/# kill -9 9961

root@wazuh-master:/# ps -edf ww | grep api
wazuh      10030       1  0 11:42 ?        S      0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh      10033       1  0 11:42 ?        S      0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py

root@wazuh-master:/# ll /var/ossec/var/run/ | grep api
-rw-r-----. 1 wazuh wazuh    5 Jan 13 11:42 wazuh-apid-9961.pid
-rw-r-----. 1 wazuh wazuh    6 Jan 13 11:42 wazuh-apid_auth-10033.pid
-rw-r-----. 1 wazuh wazuh    6 Jan 13 11:42 wazuh-apid_exec-10030.pid
```

After restarting the service, everything will be restored.

```shellsession
root@wazuh-master:/# service wazuh-manager restart
wazuh-clusterd not running...
wazuh-modulesd not running...
wazuh-monitord not running...
wazuh-logcollector not running...
wazuh-remoted not running...
wazuh-syscheckd not running...
wazuh-analysisd not running...
wazuh-maild not running...
wazuh-execd not running...
wazuh-db not running...
wazuh-authd not running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid not running...
Wazuh v4.3.0 Stopped
2022/01/13 11:46:00 wazuh-db[12665] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/01/13 11:46:00 wazuh-db[12665] main.c:101 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/01/13 11:46:00 wazuh-remoted[12670] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/01/13 11:46:00 wazuh-remoted[12670] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/01/13 11:46:00 wazuh-remoted[12670] main.c:148 at main(): DEBUG: This is not a worker
Starting Wazuh v4.3.0...
wazuh-apid: Process 9961 not used by Wazuh, removing...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/01/13 11:46:02 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
2022/01/13 11:46:03 wazuh-db[12749] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/01/13 11:46:03 wazuh-db[12749] main.c:101 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
2022/01/13 11:46:07 wazuh-remoted[12906] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/01/13 11:46:07 wazuh-remoted[12906] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/01/13 11:46:07 wazuh-remoted[12906] main.c:148 at main(): DEBUG: This is not a worker
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Started wazuh-clusterd...
Completed.

root@wazuh-master:/# ps -edf ww | grep api
wazuh      12696       1 12 11:46 ?        Sl     0:06 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh      12765   12696  0 11:46 ?        S      0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh      12768   12696  0 11:46 ?        S      0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py

root@wazuh-master:/# ll /var/ossec/var/run/ | grep api
-rw-r-----. 1 wazuh wazuh    6 Jan 13 11:46 wazuh-apid-12696.pid
-rw-r-----. 1 wazuh wazuh    6 Jan 13 11:46 wazuh-apid_auth-12768.pid
-rw-r-----. 1 wazuh wazuh    6 Jan 13 11:46 wazuh-apid_exec-12765.pid
```

Regards,
Víctor

2022-01-13 16:49 UTC, AdriiiPRodri requested changes

2022-01-13 16:49 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/utils.py
> +    # Prevent race conditions
Improve description of the race condition

2022-01-14 14:20 UTC, AdriiiPRodri approved these changes

2022-01-14 14:37 UTC, davidjiglesias requested changes

2022-01-14 14:37 UTC, davidjiglesias commented on framework/wazuh/core/cluster/utils.py
> +    # Add a delay to force each child process create its own PID file and prevent multiple calls
```suggestion
    # Add a delay to force each child process to create its own PID file, preventing multiple calls
```

2022-01-14 16:57 UTC, merged