Add necessary changes on FIMDB
wazuh/wazuh pull request #11878
Opened 2022-01-20 17:30 UTC by FrancoRivero

|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

### Description

While I developed component tests to db.cpp interface, found some issues and necessary changes to implement those tests. This pull-request fix problems found in that development. These changes are:
- Change `getInstance` by `instance` to accomplish with [coding style](https://github.com/wazuh/wazuh/wiki/Coding-style-guide-%28C-plus-plus%29)
- #11844
- #11805
- #11846

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Unit tests passed
- [x] Review logs syntax and correct language

- Memory tests for Linux
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [x] cppcheck (static code analysis)
  - [x] Coverage (unit tests coverage code)
  
![image](https://user-images.githubusercontent.com/11745030/150452724-a1cc719e-3ddb-40ee-bc27-eb8c5dda8d07.png)

  - [x] Sformat (code style)

![image](https://user-images.githubusercontent.com/11745030/150452639-dc69d2f2-0d0e-4f78-a10e-491db26504c5.png)

Closes #11847
Closes #11805
Closes #11844
Closes #11846

2022-01-20 22:06 UTC, Dwordcito requested changes

2022-01-20 22:06 UTC, Dwordcito commented on src/syscheckd/src/db/src/fimDB.cpp
> +        m_dbsyncHandler->teardown();
```suggestion
        m_rsyncHandler.reset(nullptr);
        m_dbsyncHandler.reset(nullptr);
```

2022-01-21 02:07 UTC, FrancoRivero commented on src/syscheckd/src/db/src/fimDB.cpp
> +        m_dbsyncHandler->teardown();
Done!

2022-01-21 02:07 UTC, FrancoRivero commented on src/syscheckd/src/db/CMakeLists.txt
> +                           ${CMAKE_SOURCE_DIR}/src/db/src/dbFileItem.cpp
Done!

2022-01-21 16:12 UTC, chemamartinez approved these changes

2022-01-22 03:21 UTC, Dwordcito approved these changes

2022-01-22 03:21 UTC, merged