Unit tests - Adding unit tests to sha256_op and strarr_size
wazuh/wazuh pull request #11880
Opened 2022-01-20 19:07 UTC by san1526

|Related issue|
|---|
|#11754|

## Description
Adding unit testing to the sha256_op (similar to existing testing for other checksums) and strarr_size in string_op

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux

- Memory tests for Linux
  - [x] Scan-build report
  - [x] AddressSanitizer

- [x] Added unit tests (for new features)

2022-01-20 19:11 UTC, san1526 commented
![scanbuild](https://user-images.githubusercontent.com/25422834/150406108-558bc38f-bdf1-42ec-a65e-13591ff8ae7e.png)
![sha256tests](https://user-images.githubusercontent.com/25422834/150406122-6e2e2ad1-6a75-4eb8-a1b6-1866c5f91c9d.png)
![stringtests](https://user-images.githubusercontent.com/25422834/150406132-035e9cbf-9916-40ca-b0dd-30746a1ff745.png)

2022-01-21 18:20 UTC, pereyra-m requested changes
GJ!

We only need to change the way some tests are proposed.

2022-01-21 18:20 UTC, pereyra-m commented on src/unit_tests/shared/test_string_op.c
> +
We could add here the `/* Tests strarray_size */` comment

2022-01-21 18:20 UTC, pereyra-m commented on src/unit_tests/shared/test_string_op.c
> +void test_strarray_size_null() {
We could add here the `/* Tests strarray_size */` comment

2022-01-21 18:20 UTC, pereyra-m commented on src/unit_tests/os_crypto/sha256/test_sha256_op.c
> +void test_sha256_file() {
Here, we need to wrap all the necessary methods to make  `OS_SHA256_File()` thinks it's accessing a real file.
We shouldn't create a temporary file.

2022-01-21 18:20 UTC, pereyra-m commented on src/unit_tests/os_crypto/sha256/test_sha256_op.c
> +void test_sha256_file_fail() {
Same comment about wrapping as before.

2022-01-21 20:06 UTC, pereyra-m approved these changes
LGTM!
Good job fixing the other tests.

2022-01-25 03:32 UTC, DProvinciani approved these changes
Looks good!

2022-01-25 03:32 UTC, merged