Add Testtool for FIMDB features
wazuh/wazuh pull request #11907
Opened 2022-01-24 05:18 UTC by Dwordcito

|Related issue|
|---|
|Closes #10226 |

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-01-26 12:26 UTC, FrancoRivero commented on src/syscheckd/src/db/testtool/factoryAction.h
> +#include <iostream>
This header can be deleted

2022-01-26 12:49 UTC, FrancoRivero commented on src/syscheckd/src/db/testtool/main.cpp
> +#include <stdio.h>
This header can be deleted

2022-01-26 13:00 UTC, FrancoRivero commented on src/syscheckd/src/db/testtool/main.cpp
> +                //DB::stopIntegrity();
Here we can add a call to "DB::teardown()" in order to close correctly the database and synchronization

2022-01-26 13:20 UTC, FrancoRivero commented on src/syscheckd/src/db/testtool/main.cpp
> +                //DB::stopIntegrity();
Here we can add a call to "DB::instance().teardown()" in order to close correctly the database and synchronization

2022-01-26 13:47 UTC, FrancoRivero commented on src/syscheckd/src/db/testtool/main.cpp
> +#include "fimDB.hpp"
This header can be deleted

2022-01-31 14:43 UTC, FrancoRivero approved these changes

2022-02-04 11:34 UTC, antoniomanuelfr approved these changes

2022-02-04 11:41 UTC, jotacarma90 approved these changes
LGTM

2022-02-07 16:21 UTC, chemamartinez approved these changes

2022-02-07 16:44 UTC, FrancoRivero requested changes

2022-02-07 16:44 UTC, FrancoRivero commented on src/syscheckd/src/db/testtool/action.h
> +            count = DB::instance().countFiles(filterType);
This has changed in 9103, and the way to call it is : `count = DB::instance().countEntries(FIMDB_FILE_TABLE_NAME, COUNT_SELECT_TYPE::COUNT_ALL);`
After this change the filterType variable will be useless

2022-02-08 18:40 UTC, FrancoRivero approved these changes

2022-02-09 01:51 UTC, merged