Make agent_groups distributed
wazuh/wazuh pull request #12090
Opened 2022-02-03 15:31 UTC by yanazaeva

|Related issue|
|---|
|#11789|

## Description

This closes #11789. In this pull request, we made the `agent_groups` binary distributed, meaning that it could be executed from not only the master but the workers too. The master will be in charge of creating, assigning and removing all the groups, and then sending this information to the workers.

2022-02-08 14:00 UTC, Selutario requested changes

2022-02-08 14:00 UTC, Selutario commented on framework/scripts/agent_groups.py
> +    """
```suggestion
    """Send the command to the specified function.

    If local_master is True, the request type must be local_master (upgrade_result).

    Parameters
    ----------
    function : Callable
        Upgrade function.
    command : dict
        Arguments for the specified function.
    local_master : bool
        True for get the upgrade results, False for send upgrade command.

    Returns
    -------
    result : AffectedItemsWazuhResult
        Distributed API request result.
    """
```

2022-02-09 11:32 UTC, Selutario requested changes
Rebase with the epic branch when possible.

2022-02-09 12:35 UTC, Selutario requested changes

2022-02-09 12:35 UTC, Selutario commented on framework/scripts/agent_upgrade.py
> +            raise
Add a blank line at the end
```suggestion
            raise

```

2022-02-09 12:35 UTC, Selutario commented on framework/scripts/agent_groups.py
> +    agent_id: str
Remember to leave a space after the variable names in the docstrings
```suggestion
    agent_id : str
```

2022-02-09 12:53 UTC, Selutario approved these changes

2022-02-10 11:43 UTC, davidjiglesias requested changes
Fix conflicts

2022-02-21 11:07 UTC, davidjiglesias commented on framework/scripts/agent_groups.py
> +def send_command(function, command, local_master=True):
Function is duplicated with that in agent_upgrade.py

2022-02-21 11:09 UTC, davidjiglesias commented on framework/scripts/agent_groups.py
> +def send_command(function, command, local_master=True):
We should add it to utils.py or dapi.py

2022-02-23 12:05 UTC, davidjiglesias approved these changes

2022-02-23 12:51 UTC, merged