Fix Windows graceful shutdown
wazuh/wazuh pull request #12170
Opened 2022-02-10 16:05 UTC by antoniomanuelfr

|Related issue|
|---|
|#12091|

## Description

This PR aims to fix the graceful shutdown problem in Windows

Closes #12091 

## Tests
To test the behavior, the following changes have been performed:
- Disable all the modules except for FIM
- Disable FIM
- Disable FIM DB Synchronization

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [X] Source installation
- [X] Source upgrade

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory

2022-02-21 00:51 UTC, FrancoRivero approved these changes

2022-02-21 02:09 UTC, FrancoRivero requested changes
Review Cmocka unit tests! there are some tests which is failing

2022-02-22 17:13 UTC, FrancoRivero approved these changes
LGTM

2022-02-23 12:58 UTC, chemamartinez approved these changes

2022-02-23 15:11 UTC, merged