Refactor `core/common.py` module
wazuh/wazuh pull request #12390
Opened 2022-02-21 18:15 UTC by Kondent

|Related issue|
|---|
| This PR closes #10711 |

## Description
Under this development I refactored our common.py module.
What I did here:
* Changed variable names to suffice the `PEP8` formatting of constants.
* Removed unused variables.
* Fixed all involved Wazuh modules.
* Added a better organization layout for all variables, constants and methods.

## Schema
```
━ Common.py
    ┣━ Functions
    ┣━ Context variables 
    ┣━ Wazuh constants and variables
    ┃   ┣━ Commands
    ┃   ┣━ Date format
    ┃   ┣━ Extensions
    ┃   ┣━ Metadata 
    ┃   ┣━ Size and limits
    ┃   ┗━ Version
    ┗━ Wazuh path
        ┣━ Config
        ┣━ Misc
        ┣━ Sockets
        ┗━ Ruleset
```

In future developments, any variable / constant / function added to this file should use the section of the schema depending on its type. If there's no related section, a new one must be created following the current design. 

## Unit tests - Framework
<details>

<summary>Click to expand</summary>

```s
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.4.3, py-1.11.0, pluggy-0.13.1
rootdir: /home/kondent/git/wazuh/framework
plugins: html-2.1.1, asyncio-0.15.1, metadata-1.11.0, aiohttp-0.3.0, trio-0.7.0, cov-2.10.1
collected 1838 items                                                                                                                                                                         

wazuh/core/cluster/dapi/tests/test_dapi.py ..............................                                                                                                              [  1%]
wazuh/core/cluster/tests/test_client.py ................                                                                                                                               [  2%]
wazuh/core/cluster/tests/test_cluster.py .............................                                                                                                                 [  4%]
wazuh/core/cluster/tests/test_common.py ............................................................                                                                                   [  7%]
wazuh/core/cluster/tests/test_control.py .....                                                                                                                                         [  7%]
wazuh/core/cluster/tests/test_local_client.py .............                                                                                                                            [  8%]
wazuh/core/cluster/tests/test_local_server.py .......................                                                                                                                  [  9%]
wazuh/core/cluster/tests/test_master.py ..........................................                                                                                                     [ 11%]
wazuh/core/cluster/tests/test_server.py ...................                                                                                                                            [ 12%]
wazuh/core/cluster/tests/test_utils.py .......                                                                                                                                         [ 13%]
wazuh/core/cluster/tests/test_worker.py ...............................                                                                                                                [ 14%]
wazuh/core/tests/test_active_response.py ..............                                                                                                                                [ 15%]
wazuh/core/tests/test_agent.py ..............................................................................................................................................          [ 23%]
wazuh/core/tests/test_cdb_list.py ......................................                                                                                                               [ 25%]
wazuh/core/tests/test_common.py .......                                                                                                                                                [ 25%]
wazuh/core/tests/test_configuration.py ....................................                                                                                                            [ 27%]
wazuh/core/tests/test_database.py .............                                                                                                                                        [ 28%]
wazuh/core/tests/test_decoder.py ................                                                                                                                                      [ 29%]
wazuh/core/tests/test_exception.py ...                                                                                                                                                 [ 29%]
wazuh/core/tests/test_input_validator.py ...                                                                                                                                           [ 29%]
wazuh/core/tests/test_logtest.py ..                                                                                                                                                    [ 29%]
wazuh/core/tests/test_manager.py ...............                                                                                                                                       [ 30%]
wazuh/core/tests/test_mitre.py .............                                                                                                                                           [ 31%]
wazuh/core/tests/test_pyDaemonModule.py .....                                                                                                                                          [ 31%]
wazuh/core/tests/test_results.py ........................................                                                                                                              [ 33%]
wazuh/core/tests/test_rootcheck.py .............                                                                                                                                       [ 34%]
wazuh/core/tests/test_rule.py ......................                                                                                                                                   [ 35%]
wazuh/core/tests/test_sca.py ............                                                                                                                                              [ 36%]
wazuh/core/tests/test_security.py ............                                                                                                                                         [ 37%]
wazuh/core/tests/test_stats.py ............                                                                                                                                            [ 37%]
wazuh/core/tests/test_syscheck.py .......                                                                                                                                              [ 38%]
wazuh/core/tests/test_syscollector.py ...                                                                                                                                              [ 38%]
wazuh/core/tests/test_task.py ........                                                                                                                                                 [ 38%]
wazuh/core/tests/test_utils.py ...................................................................................................................... [...]

2022-02-25 09:54 UTC, vicferpoy requested changes

2022-02-25 09:54 UTC, vicferpoy commented on framework/wazuh/core/cdb_list.py
> +    return [str(next(Path(root_directory).rglob(file), path.join(common.USER_LISTS_PATH, file))) for file in filenames_list]
Check PEP8.

2022-02-25 09:54 UTC, vicferpoy commented on framework/wazuh/rule.py
> +def get_rules_files(status=None, relative_dirname=None, filename=None, offset=0, limit=common.DATABASE_LIMIT, sort_by=None,
Check PEP8.

2022-02-25 09:54 UTC, vicferpoy commented on framework/wazuh/core/cluster/worker.py
> +                                                                                                   common.WAZUH_PATH).encode())
Check PEP8.

2022-02-25 09:54 UTC, vicferpoy commented on framework/wazuh/core/exception.py
> +from wazuh.core.common import MAX_SOCKET_BUFFER_SIZE, WAZUH_VERSION as wazuh_full_version, AGENT_NAME_LEN_LIMIT
Constant variable imported as non-constant: `wazuh_full_version`

2022-02-25 09:54 UTC, vicferpoy commented on framework/wazuh/core/configuration.py
> +                                                                      '{0}.{1}'.format(high_name, low_name))
Use f-strings instead. Review the whole module please.

2022-03-01 08:00 UTC, vicferpoy approved these changes
LGTM

2022-03-01 10:29 UTC, davidjiglesias approved these changes

2022-03-01 10:29 UTC, merged