Fix warnings in read_nmapg.c file
wazuh/wazuh pull request #12418
Opened 2022-02-23 15:19 UTC by HanesSciarrone

|Related issue|
|---|
|#12100|

## Description

Hi Team

This PR aims to resolve the warnings when compiling the Wazuh agent project in read_nmapg.c. . The output of the compilation after the changes was:

## Compilation using GCC 9.3

<details>
<summary>Wazuh Agent</summary>

```
    CC logcollector/read_audit.o
    CC logcollector/read_multiline_regex.o
In file included from /usr/include/string.h:495,
                 from ./headers/shared.h:67,
                 from logcollector/read_audit.c:10:
In function ‘strncpy’,
    inlined from ‘audit_send_msg’ at logcollector/read_audit.c:31:13:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
logcollector/read_audit.c: In function ‘audit_send_msg’:
logcollector/read_audit.c:25:13: note: length computed here
   25 |         z = strlen(cache[i]);
      |             ^~~~~~~~~~~~~~~~
    CC logcollector/read_nmapg.o
    CC logcollector/read_command.o
    CC logcollector/read_mysql_log.o
    CC logcollector/read_ucs2_be.o
    CC logcollector/read_multiline.o
In file included from /usr/include/string.h:495,
                 from ./headers/shared.h:67,
                 from logcollector/read_multiline.c:11:
In function ‘strncpy’,
    inlined from ‘read_multiline’ at logcollector/read_multiline.c:96:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ output may be truncated copying between 0 and 65534 bytes from a string of length 65536 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC logcollector/macos_log.o

```
</details>

## Compilation using GCC 10.2.1

<details>
<summary>Wazuh Agent</summary>

```
   CC logcollector/read_multiline.o
    CC logcollector/read_multiline_regex.o
logcollector/read_mssql_log.c: In function ‘read_mssql_log’:
logcollector/read_mssql_log.c:117:17: warning: ‘strncpy’ output may be truncated copying between 2 and 65536 bytes from a string of length 65536 [-Wstringop-truncation]
  117 |                 strncpy(buffer, str, str_len + 2);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
logcollector/read_mssql_log.c:108:17: warning: ‘strncpy’ output may be truncated copying between 2 and 65536 bytes from a string of length 65536 [-Wstringop-truncation]
  108 |                 strncpy(buffer, str, str_len + 2);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
logcollector/read_multiline.c: In function ‘read_multiline’:
logcollector/read_multiline.c:96:9: warning: ‘strncpy’ output may be truncated copying between 0 and 65534 bytes from a string of length 65536 [-Wstringop-truncation]
   96 |         strncpy(buffer + buffer_size, str, OS_MAXSTR - buffer_size - 2);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC logcollector/read_mysql_log.o
    CC logcollector/read_nmapg.o
    CC logcollector/read_ossecalert.o
    CC logcollector/read_postgresql_log.o
logcollector/read_mysql_log.c: In function ‘read_mysql_log’:
logcollector/read_mysql_log.c:105:56: warning: ‘%s’ directive output may be truncated writing up to 65521 bytes into a region of size between 65489 and 65524 [-Wformat-truncation=]
  105 |             snprintf(buffer, OS_MAXSTR, "MySQL log: %s %s",
      |                                                        ^~
logcollector/read_mysql_log.c:105:13: note: ‘snprintf’ output between 13 and 65569 bytes into a destination of size 65536
  105 |             snprintf(buffer, OS_MAXSTR, "MySQL log: %s %s",
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  106 |                      __mysql_last_time, p);
      |                      ~~~~~~~~~~~~~~~~~~~~~
logcollector/read_mysql_log.c:158:55: warning: ‘%s’ directive output may be truncated writing up to 65504 bytes into a region of size between 65489 and 65524 [-Wformat-truncation=]
  158 |            snprintf(buffer, OS_MAXSTR, "MySQL log: %s %s",
      |                                                       ^~

```
</details>

- Compilation without warnings in every supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [x] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-02-23 20:37 UTC, RamiroRD requested changes

2022-02-23 20:37 UTC, RamiroRD commented on src/logcollector/read_nmapg.c
> +    char str[OS_MAXSTR - OS_LOG_HEADER];
Why the `- OS_LOG_HEADER`? Can't we use an intermediate macro with a descriptive name instead?

2022-02-23 20:37 UTC, RamiroRD commented on src/logcollector/read_nmapg.c
> +    str[OS_MAXSTR - OS_LOG_HEADER -1] = '\0';
Same as first comment.

2022-02-23 20:37 UTC, RamiroRD commented on src/logcollector/read_nmapg.c
> +        bytes_written = snprintf(final_msg, OS_MAXSTR - OS_LOG_HEADER, "Host: %s, open ports:",
Use sizeof instead of duplicating addition logic

2022-02-23 20:37 UTC, RamiroRD commented on src/logcollector/read_nmapg.c
> +        if (bytes_written < OS_MAXSTR - OS_LOG_HEADER) {
2x ditto

2022-02-24 12:10 UTC, RamiroRD commented on src/logcollector/read_nmapg.c
> +    char str[OS_MAXSTR - OS_LOG_HEADER];
Got it. In that case I think we should define a new macro for this value (`OS_MAXSTR - OS_LOG_HEADER`) something like
```
#define OS_MAX_LOG (OS_MAXSTR - OS_LOG_HEADER)
```
What do you think?

2022-02-24 12:18 UTC, RamiroRD commented on src/logcollector/read_nmapg.c
> +    char buffer[sizeof(port) + sizeof(proto) + 4];
Got it, thanks

2022-03-08 03:23 UTC, Dwordcito requested changes

2022-03-08 03:23 UTC, Dwordcito commented on src/logcollector/read_nmapg.c
> +        if (bytes_written < (int)sizeof(final_msg)) {
snprintf could return < 0 values. Catch it.

2022-03-08 19:58 UTC, RamiroRD commented on src/logcollector/read_nmapg.c
> +    str[sizeof(str) -1] = '\0';
```suggestion
    str[sizeof(str) - 1] = '\0';
```

2022-03-09 03:52 UTC, Dwordcito approved these changes

2022-03-09 04:25 UTC, Dwordcito approved these changes

2022-03-09 12:00 UTC, RamiroRD approved these changes

2022-03-09 12:29 UTC, RamiroRD requested changes
Minor formatting issues

2022-03-09 12:29 UTC, RamiroRD commented on src/logcollector/read_nmapg.c
> +        else if ((size_t)bytes_written < sizeof(final_msg)) {
```suggestion
        } else if ((size_t)bytes_written < sizeof(final_msg)) {
```

2022-03-09 12:29 UTC, RamiroRD commented on src/logcollector/read_nmapg.c
> +        else {
```suggestion
        } else {
```

2022-03-09 19:11 UTC, RamiroRD approved these changes

2022-03-10 18:04 UTC, HanesSciarrone commented on src/logcollector/read_nmapg.c
> +    char buffer[sizeof(port) + sizeof(proto) + 4] = {0};
Hi @jnasselle 

I really don't know why port and proto buffers have 17 characters in length.

2022-03-10 18:33 UTC, jnasselle commented on src/logcollector/read_nmapg.c
> +    char buffer[sizeof(port) + sizeof(proto) + sizeof(PORT_PROTO)] = {0};
sizeof(PORT_PROTO) will also contain string function formatters.

2022-03-11 14:22 UTC, jnasselle approved these changes

2022-03-11 14:22 UTC, merged