Fix warnings in read_postgresql_log.c file
wazuh/wazuh pull request #12422
Opened 2022-02-23 18:34 UTC by HanesSciarrone

|Related issue|
|---|
|#12100|

## Description

Hi Team

This PR aims to resolve the warnings when compiling the Wazuh agent project in read_nmapg.c. . The output of the compilation after the changes was:

## Compilation using GCC 9.3

<details>
<summary>Wazuh Agent</summary>

```
    CC analysisd/logmsg.o
addagent/validate.c: In function ‘OS_AddNewAgent’:
addagent/validate.c:49:27: warning: ‘%03d’ directive output may be truncated writing between 3 and 11 bytes into a region of size 9 [-Wformat-truncation=]
   49 |         snprintf(_id, 9, "%03d", ++keys->id_counter);
      |                           ^~~~
addagent/validate.c:49:26: note: directive argument in the range [-2147483647, 2147483647]
   49 |         snprintf(_id, 9, "%03d", ++keys->id_counter);
      |                          ^~~~~~
In file included from /usr/include/stdio.h:867,
                 from ./headers/shared.h:64,
                 from addagent/manage_agents.h:14,
                 from addagent/validate.c:12:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 4 and 12 bytes into a destination of size 9
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC os_auth/main-client.o
    CC logcollector/read_ossecalert.o
    CC logcollector/state.o
    CC logcollector/config.o
    CC logcollector/logcollector.o
    CC logcollector/read_djb_multilog.o
    CC logcollector/read_postgresql_log.o
    CC logcollector/read_ucs2_le.o
    CC logcollector/read_mssql_log.o
In file included from /usr/include/string.h:495,
                 from ./headers/shared.h:67,
                 from logcollector/read_mssql_log.c:13:
In function ‘strncpy’,
    inlined from ‘read_mssql_log’ at logcollector/read_mssql_log.c:117:17:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin___strncpy_chk’ output may be truncated copying between 2 and 65536 bytes from a string of length 65536 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘read_mssql_log’ at logcollector/read_mssql_log.c:108:17:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin___strncpy_chk’ output may be truncated copying between 2 and 65536 bytes from a string of length 65536 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC logcollector/read_win_el.o
    CC logcollector/lccom.o
    CC logcollector/read_macos.o
    CC logcollector/read_json.o

```

</details>

## Compilation using GCC 10.2.1

<details>
<summary>Wazuh Agent</summary>

```
    CC logcollector/read_mysql_log.o
logcollector/read_multiline.c: In function ‘read_multiline’:
logcollector/read_multiline.c:96:9: warning: ‘strncpy’ output may be truncated copying between 0 and 65534 bytes from a string of length 65536 [-Wstringop-truncation]
   96 |         strncpy(buffer + buffer_size, str, OS_MAXSTR - buffer_size - 2);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC logcollector/read_nmapg.o
    CC logcollector/read_ossecalert.o
    CC logcollector/read_postgresql_log.o
logcollector/read_mysql_log.c: In function ‘read_mysql_log’:
logcollector/read_mysql_log.c:105:56: warning: ‘%s’ directive output may be truncated writing up to 65521 bytes into a region of size between 65489 and 65524 [-Wformat-truncation=]
  105 |             snprintf(buffer, OS_MAXSTR, "MySQL log: %s %s",
      |                                                        ^~
logcollector/read_mysql_log.c:105:13: note: ‘snprintf’ output between 13 and 65569 bytes into a destination of size 65536
  105 |             snprintf(buffer, OS_MAXSTR, "MySQL log: %s %s",
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  106 |                      __mysql_last_time, p);
      |                      ~~~~~~~~~~~~~~~~~~~~~
logcollector/read_mysql_log.c:158:55: warning: ‘%s’ directive output may be truncated writing up to 65504 bytes into a region of size between 65489 and 65524 [-Wformat-truncation=]
  158 |            snprintf(buffer, OS_MAXSTR, "MySQL log: %s %s",
      |                                                       ^~
logcollector/read_mysql_log.c:158:12: note: ‘snprintf’ output between 13 and 65552 bytes into a destination of size 65536
  158 |            snprintf(buffer, OS_MAXSTR, "MySQL log: %s %s",
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  159 |                     __mysql_last_time, p);
      |                     ~~~~~~~~~~~~~~~~~~~~~
logcollector/read_mysql_log.c:206:54: warning: ‘%s’ directive output may be truncated writing up to 65509 bytes into a region of size between 65489 and 65524 [-Wformat-truncation=]
  206 |           snprintf(buffer, OS_MAXSTR, "MySQL log: %s %s",
      |                                                      ^~
logcollector/read_mysql_log.c:206:11: note: ‘snprintf’ output between 13 and 65557 bytes into a destination of size 65536
  206 |           snprintf(buffer, OS_MAXSTR, "MySQL log: %s %s",
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  207 |                    __mysql_last_time, p);
      |                    ~~~~~~~~~~~~~~~~~~~~~
logcollector/read_nmapg.c: In function ‘read_nmapg’:
logcollector/read_nmapg.c:222:49: warning: ‘, open ports:’ directive output may be truncated writing 13 bytes into a region of size between 0 and 65530 [-Wformat-truncation=]
  222 |         snprintf(final_msg, OS_MAXSTR, "Host: %s, open ports:",
      |                                                 ^~~~~~~~~~~~~
logcollector/read_nmapg.c:222:9: note: ‘snprintf’ output between 20 and 65550 bytes into a destination of size 65536
  222 |         snprintf(final_msg, OS_MAXSTR, "Host: %s, open ports:",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  223 |                  ip);
      |                  ~~~
logcollector/read_nmapg.c:246:13: warning: ‘strncat’ output may be truncated copying between 27 and 65533 bytes from a string of length 65536 [-Wstringop-truncation]
  246 |             strncat(final_msg, buffer, final_msg_s);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC logcollector/read_snortfull.o
    CC logcollector/read_syslog.o

```

</details>

- Compilation without warnings in every supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [x] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-02-23 20:38 UTC, RamiroRD requested changes

2022-02-23 20:38 UTC, RamiroRD commented on src/logcollector/read_postgresql_log.c
> +    char str[OS_MAXSTR - OS_LOG_HEADER];
Same as in other related PRs. :)

2022-02-23 20:38 UTC, RamiroRD commented on src/logcollector/read_postgresql_log.c
> +    buffer[OS_MAXSTR - OS_LOG_HEADER - 1] = '\0';
Why the `- 1` here?

2022-02-23 20:38 UTC, RamiroRD commented on src/logcollector/read_postgresql_log.c
> +                snprintf(buffer, OS_MAXSTR - OS_LOG_HEADER, "%s", str);
Use sizeof.

2022-02-23 20:38 UTC, RamiroRD commented on src/logcollector/read_postgresql_log.c
> +                snprintf(buffer, OS_MAXSTR - OS_LOG_HEADER, "%s", str);
Ditto.

2022-02-23 20:38 UTC, RamiroRD commented on src/logcollector/read_postgresql_log.c
> +            if (sizeof(buffer) - buffer_len > str_len) {
Why is the 256 missing here?

2022-02-23 22:11 UTC, HanesSciarrone commented on src/logcollector/read_postgresql_log.c
> +    char str[OS_MAXSTR - OS_LOG_HEADER];
Same answer :smile:

2022-02-23 22:11 UTC, HanesSciarrone commented on src/logcollector/read_postgresql_log.c
> +            if (sizeof(buffer) - buffer_len > str_len) {
Same answer and other PR :smile:

2022-02-24 13:14 UTC, RamiroRD approved these changes

2022-03-08 03:44 UTC, Dwordcito commented on src/logcollector/read_postgresql_log.c
>      buffer[0] = '\0';
use curly initialization.

2022-03-08 03:44 UTC, Dwordcito commented on src/logcollector/read_postgresql_log.c
> +    str[sizeof(str) - 1] = '\0';
Curly initialization please.

2022-03-08 19:56 UTC, RamiroRD approved these changes

2022-03-09 03:53 UTC, Dwordcito approved these changes

2022-03-10 17:16 UTC, jnasselle approved these changes

2022-03-10 17:17 UTC, merged