Refactor FIMDB
wazuh/wazuh pull request #12427
Opened 2022-02-23 19:52 UTC by FrancoRivero

|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

### Description
Add some changes to db.cpp and FIMDB class in order to avoid to compile  used the same files for Windows, Linux and other operating systems. It implies:

- [x] Modify initialization on FIMDB to select a different initialization for Windows without using WIN32 flag
- [x] Modify synchronization on FIMDB to select a different way for Windows without using WIN32 flag
- [x] Modify Cmake to avoid select the operating system
- [x] Modify test tool with the new implementation
- [x] Modify unit tests for FIMDB
- [x] Modify component tests in db.cpp 
- [x] Modify CMocka unit tests

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Unit tests passed
- [x] Review logs syntax and correct language

- Memory tests for Linux
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [x] cppcheck (static code analysis)
  - [x] Coverage (unit tests coverage code)
  - [x] Sformat (code style)
  - [x] Scan build
 
Closes #11950

2022-02-24 16:51 UTC, jotacarma90 requested changes

2022-02-24 16:59 UTC, jotacarma90 approved these changes
LGTM

2022-02-25 09:24 UTC, antoniomanuelfr approved these changes

2022-02-25 09:48 UTC, chemamartinez approved these changes

2022-02-26 06:04 UTC, Dwordcito requested changes

2022-02-26 06:04 UTC, Dwordcito commented on src/syscheckd/src/db/src/fimDB.cpp
> +    FIMDBCreator<OS_TYPE>::setLimits(m_dbsyncHandler, fileLimit, registryLimit);
```suggestion
    std::shared_lock<std::shared_timed_mutex> lock(m_handlersMutex);
    FIMDBCreator<OS_TYPE>::setLimits(m_dbsyncHandler, fileLimit, registryLimit);
```

2022-02-26 07:01 UTC, merged