Fix warnings in check_rc_sys.c file
wazuh/wazuh pull request #12434
Opened 2022-02-24 00:52 UTC by HanesSciarrone

|Related issue|
|---|
|#12100|

## Description

Hi Team

This PR aims to resolve the warnings when compiling the Wazuh agent project in check_rc_sys.c. . The output of the compilation after the changes was:

## Compilation using GCC 9.3

<details>
<summary>Wazuh Agent</summary>

```
    CC rootcheck/check_rc_if.o
    CC rootcheck/check_open_ports.o
In file included from /usr/include/string.h:495,
                 from ./headers/shared.h:67,
                 from rootcheck/check_rc_if.c:12:
In function ‘strncpy’,
    inlined from ‘check_rc_if’ at rootcheck/check_rc_if.c:87:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ output may be truncated copying 16 bytes from a string of length 639 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC rootcheck/os_string.o
    CC rootcheck/win-common.o
    CC rootcheck/check_rc_readproc.o
    CC rootcheck/check_rc_dev.o
    CC rootcheck/check_rc_sys.o
rootcheck/check_rc_dev.c: In function ‘read_dev_dir’:
rootcheck/check_rc_dev.c:41:47: warning: ‘%s’ directive output may be truncated writing up to 4097 bytes into a region of size 1018 [-Wformat-truncation=]
   41 |         snprintf(op_msg, OS_SIZE_1024, "File '%s' present on /dev."
      |                                               ^~
......
  140 |         read_dev_file(f_name);
      |                       ~~~~~~                   
In file included from /usr/include/stdio.h:867,
                 from ./headers/shared.h:64,
                 from rootcheck/check_rc_dev.c:12:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 47 and 4144 bytes into a destination of size 1024
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC rootcheck/run_rk_check.o
    CC rootcheck/check_rc_policy.o
    CC rootcheck/check_rc_pids.o
    CC rootcheck/check_rc_trojans.o
    CC os_execd/exec.o
    CC os_execd/config.o
In file included from /usr/include/string.h:495,
                 from ./headers/shared.h:67,
                 from os_execd/exec.c:11:
In function ‘strncpy’,
    inlined from ‘ReadExecConfig’ at os_execd/exec.c:72:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ output may be truncated copying 256 bytes from a string of length 65536 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

</details>

## Compilation using GCC 10.2.1

<details>
<summary>Wazuh Agent</summary>

```
    CC rootcheck/check_rc_files.o
    CC rootcheck/check_rc_if.o
    CC rootcheck/check_rc_pids.o
rootcheck/check_rc_if.c: In function ‘check_rc_if’:
rootcheck/check_rc_if.c:87:9: warning: ‘strncpy’ output may be truncated copying 16 bytes from a string of length 639 [-Wstringop-truncation]
   87 |         strncpy(_ifr.ifr_name, _ir->ifr_name, sizeof(_ifr.ifr_name));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rootcheck/check_rc_files.c: In function ‘check_rc_files’:
rootcheck/check_rc_files.c:171:52: warning: ‘%s’ directive output may be truncated writing up to 1024 bytes into a region of size 1023 [-Wformat-truncation=]
  171 |             snprintf(file_path, OS_SIZE_1024, "%s%c%s", basedir, PATH_SEP, file);
      |                                                    ^~
rootcheck/check_rc_files.c:171:13: note: ‘snprintf’ output 2 or more bytes (assuming 1026) into a destination of size 1024
  171 |             snprintf(file_path, OS_SIZE_1024, "%s%c%s", basedir, PATH_SEP, file);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rootcheck/check_rc_files.c:169:50: warning: ‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]
  169 |             snprintf(file_path, OS_SIZE_1024, "%s", file);
      |                                                  ^
rootcheck/check_rc_files.c:169:13: note: ‘snprintf’ output between 1 and 1025 bytes into a destination of size 1024
  169 |             snprintf(file_path, OS_SIZE_1024, "%s", file);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC rootcheck/check_rc_policy.o
    CC rootcheck/check_rc_ports.o
    CC rootcheck/check_rc_readproc.o
    CC rootcheck/check_rc_sys.o
    CC rootcheck/check_rc_trojans.o
    CC rootcheck/common.o
    CC rootcheck/common_rcl.o
    CC rootcheck/config.o
    CC rootcheck/os_string.o
    CC rootcheck/rootcheck.o
In file included from ./headers/shared.h:220,
                 from rootcheck/common.c:11:
rootcheck/common.c: In function ‘is_file’:
./headers/debug_op.h:46:32: warning: argument 6 null where non-null expected [-Wnonnull]
   46 | #define mterror(tag, msg, ...) _mterror(tag, __FILE__, __LINE__, __func__, msg, ##__VA_ARGS__)
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rootcheck/common.c:454:9: note: in expansion of macro ‘mterror’
  454 |         mterror(ARGV0, "RK: Invalid file name: %s!", file_name);
      |         ^~~~~~~
In file included from ./headers/shared.h:220,

```

</details>

- Compilation without warnings in every supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [x] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-02-25 12:39 UTC, jnasselle requested changes
The next comment also applies to this PR https://github.com/wazuh/wazuh/pull/12435#discussion_r814725534

2022-03-08 04:30 UTC, Dwordcito commented on src/rootcheck/check_rc_dev.c
> +            _dev_errors++;
is this change correct ?

2022-03-08 14:47 UTC, jnasselle commented on src/rootcheck/check_rc_sys.c
> +        int size = snprintf(NULL, 0, op_msg_fmt, (int)strlen(file_name), file_name);
```suggestion
        const int size = snprintf(NULL, 0, op_msg_fmt, (int)strlen(file_name), file_name);
```

2022-03-08 14:49 UTC, jnasselle commented on src/rootcheck/check_rc_sys.c
> +            int size = 0;
```suggestion
```

2022-03-08 14:50 UTC, jnasselle commented on src/rootcheck/check_rc_sys.c
> +                else {
```suggestion
                } else {
```

2022-03-08 14:51 UTC, jnasselle commented on src/rootcheck/check_rc_sys.c
> +                        else {
```suggestion
                        } else {
```

2022-03-08 20:20 UTC, RamiroRD approved these changes

2022-03-08 22:10 UTC, RamiroRD requested changes

2022-03-08 22:10 UTC, RamiroRD commented on src/rootcheck/check_rc_dev.c
> +            }
` } else { `

2022-03-09 04:06 UTC, Dwordcito approved these changes

2022-03-09 12:37 UTC, RamiroRD approved these changes

2022-03-09 15:07 UTC, jnasselle approved these changes

2022-03-09 15:07 UTC, merged