Fix active configuration error handling
wazuh/wazuh pull request #12450
Opened 2022-02-24 19:40 UTC by Kondent

|Related issue|
|---|
| This PR closes #10775 |

## Description

The following error was found when trying to make a request to `GET /cluster/{node_id}/configuration/{component}/{configuration}` with a valid but non configured component.

* Before: `GET /cluster/master-node/configuration/mail/global`.
```json
{
  "title": "Wazuh Internal Error",
  "detail": "Error connecting with socket",
  "dapi_errors": {
    "master-node": {
      "error": "Error connecting with socket",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 1121
}
```

* After: `GET /cluster/master-node/configuration/mail/global`.
```json
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 1,
    "failed_items": [
      {
        "error": {
          "code": 1121,
          "message": "Error connecting with socket: please verify that the component 'mail' is properly configured"
        },
        "id": [
          "master-node"
        ]
      }
    ]
  },
  "message": "Could not read active configuration in specified node",
  "error": 1
}
```
---

However, if the component is configured but the socket is malfunctioning, we'll be getting the `WazuhInternal` error as it should be.
`GET /cluster/master-node/configuration/syscheck/syscheck`
```
--- Socket file with wrong ownership ---
root@f1656202220d:/var/ossec/queue/sockets# ll syscheck 
srw-rw---- 1 root root 0 Feb 24 17:46 syscheck=
```
```json
{
  "title": "Wazuh Internal Error",
  "detail": "Error connecting with socket",
  "dapi_errors": {
    "wd_master_1": {
      "error": "Error connecting with socket",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 1121
}
```

2022-02-25 10:16 UTC, vicferpoy requested changes
Awful unit tests for the related function exceptions (overall, not yours). Please consider unifying them following our standards.

2022-02-25 10:16 UTC, vicferpoy commented on framework/wazuh/core/configuration.py
> +    """Get active configuration in a specific node.
```suggestion
    """Get an agent's component active configuration.
```

2022-02-25 10:16 UTC, vicferpoy commented on framework/wazuh/core/configuration.py
> +        If the reply from the node contains an error.
It is great that you added this. However, this section lacks detail. A good example: https://github.com/wazuh/wazuh/blob/edcfe6179fe86af0cb003cf9a1ef21b4e8a6480d/framework/wazuh/agent.py#L197-L204

2022-03-01 08:16 UTC, vicferpoy approved these changes
LGTM

2022-03-01 10:22 UTC, davidjiglesias approved these changes

2022-03-01 10:22 UTC, merged