Improve Google Cloud integration's error handling
wazuh/wazuh pull request #12647
Opened 2022-03-09 15:13 UTC by noise-kngdm

|Related issue|
|---|
|Closes #12140|

## Description
In this PR we rework the way the GCP module handles errors and exceptions. We add the `wodles/gcloud/exceptions.py` file, which enclose the information about all the errors the module might raise. All the exceptions are now being explicitely captured by the logger that is configured to set a different logging level depending on the severity of the error. Exceptions that are unhandled will be registered with the full exception trace to help debugging them. 

Along with this error handling system, we start handling errors that could be raised when specifying invalid credentials, bucket names and subscription and project names to make it easier for the user to use the module.

Because of the tests, we found out that the Access Logs integrations could be executed specifying '' as the bucket name, which made the module perform an incorrect API call to the GCP platform. We fixed that problem for this issue too by ensuring that the bucket name is of str type and that it evaluates to True, which means is not an empty string.

## Tests performed
All the tests passed without any further problems.

### Unit tests
We added unit tests to check that the changes that doesn't depend on the GCP API work as expected. All of them pass

```
(wazuh-unit) ➜  gcloud git:(feature/12140-improve-gcp-error-handling) ✗ pytest
==================================== test session starts ====================================
platform linux -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-0.13.1
rootdir: /home/gonzz/git/wazuh/wodles/gcloud
plugins: asyncio-0.15.1
collected 17 items                                                                          

tests/test_access_logs.py .                                                           [  5%]
tests/test_bucket.py ...                                                              [ 23%]
tests/test_gcloud.py .....                                                            [ 52%]
tests/test_integration.py .....                                                       [ 82%]
tests/test_subscriber.py ...                                                          [100%]

===================================== warnings summary ======================================
../../../../venv/wazuh-unit/lib/python3.10/site-packages/google/pubsub_v1/services/publisher/client.py:17
  /home/gonzz/venv/wazuh-unit/lib/python3.10/site-packages/google/pubsub_v1/services/publisher/client.py:17: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils import util

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================== 17 passed, 1 warning in 0.04s ===============================
```

### Test Access Logs

<details><summary>Tests output</summary>

```
root@97cff1b2dfb7:/# /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket  -c /var/ossec/wodles/gcloud/credentials.json -l 1 -o 2021-jan-01 -T access_logs
gcloud_wodle - INFO - Processing test_1_new.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 1", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_22.txt
gcloud_wodle - INFO - Processing test_2_new.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 2", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_3.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 3", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_3_new.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 3", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_4.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 4", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_5.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 5", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_6.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 6", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Updating previously processed files.
gcloud_wodle - INFO - Received 7 messages
root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket  -c /var/ossec/wodles/gcloud/credentials.json -l 1 -o 2021-jan-01 -T access_log 
gcloud_wodle - ERROR - An exception happened while running the wodle: Unsupported gcloud integration type: "access_log". The supported types are ('pubsub', 'access_logs')
Traceback (most recent call last):
  File "/var/ossec/wodles/gcloud/gcloud.py", line 89, in <module>
    raise exceptions.GCloudIntegrationTypeError(arguments.integration_type)
exceptions.GCloudIntegrationTypeError: Unsupported gcloud integration type: "access_log". The supported types are ('pubsub', 'access_logs')
root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket  -c /var/ossec/wodles/gcloud/credentials.json -l 2 -o 2021-jan-01 -T access_log
gcloud_wodle - ERROR - An exception happened while running the wodle: Unsupported gcloud integration type: "access_log". The supported types are ('pubsub', 'access_logs')
root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket  -c /var/ossec/wodles/gcloud/credentials.json -l 2 -o 2021-9jan-01 -T access_logs
usage: usage: gcloud.py [options]
gcloud.py: error: argument -o/--only_logs_after: Argument not a valid date in format YYYY-MMM-DD: '2021-9jan-01'.
root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -b framework-test-bucketo  -c /var/ossec/wodles/gcloud/credentials.json -l 2 -o 2021-jan-01 -T access_logs
gcloud_wodle - ERROR - An exception happened while running the wodle: The bucket 'framework-test-bucketo' does not exist
```

</details>

### Test Pub/Sub
<details><summary>Test output</summary>

```
root@97cff1b2dfb7:/# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 1 -s test_gcloud_blog -p wazuh-dev-123456 -c /var/ossec/wodles/gcloud/credentials.json  
gcloud_wodle - DEBUG - Setting 1 thread to pull 100 messages in total
gcloud_wodle - INFO - Received and acknowledged 0 messages
root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 2 -s wazuh-audit-log -p wazuh-dev-123456 -c /var/ossec/wodles/gcloud/credentials.json -m 10
gcloud_wodle - ERROR - An exception happened while running the wodle: The 'wazuh-audit-log' project ID is incorrect or the user does not have permissions to access to it
root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 2 -s wazuh-audit-logs -p wazuh-dev-123456 -c /var/ossec/wodles/gcloud/credentials.json -m 10
gcloud_wodle - INFO - Received and acknowledged 10 messages
root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 2 -s wazuh-audit-logs -p wazuh-dev-123456 -c /var/ossec/wodles/gcloud/credentials.json -m 10 -t 99999
gcloud_wodle - WARNING - Reached maximum number of threads. Truncating to 80.
gcloud_wodle - INFO - Received and acknowledged 10 messages
root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 2 -s wazuh-audit-logs -p wazuh-dev-123456 -c /var/ossec/wodles/gcloud/credentials.json -m 10 -t -99999
gcloud_wodle - ERROR - An exception happened while running the wodle: The minimum number of threads is 1. Please check your configuration.
root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 2 -s wazuh-audit-logs -p wazuh-dev-1234568 -c /var/ossec/wodles/gcloud/credentials.json -m 10     
gcloud_wodle - ERROR - An exception happened while running the wodle: The 'wazuh-dev-1234568 [...]

2022-03-10 12:30 UTC, CarlosRS9 requested changes
I think we should use an approach similar to the one used in exception handling in the Framework. Instead of defining so many separate classes in `exceptions.py` we should have only 2 or 3 and use a dictionary with the relevant information, simplifying the design of the classes.

2022-03-14 16:02 UTC, noise-kngdm commented
## Update
I modified the design of the exceptions as requested. Since the changes affected almost everything I had done, I performed the tests again.

## Tests performed
All the tests passed without any further problems.

### Unit tests
We added unit tests to check that the changes that doesn't depend on the GCP API work as expected. All of them passed.

```
(wazuh-unit) ➜  gcloud git:(feature/12140-improve-gcp-error-handling) ✗ pytest
==================================== test session starts ====================================
platform linux -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-0.13.1
rootdir: /home/gonzz/git/wazuh/wodles/gcloud
plugins: asyncio-0.15.1
collected 17 items                                                                          

tests/test_access_logs.py .                                                           [  5%]
tests/test_bucket.py ...                                                              [ 23%]
tests/test_gcloud.py .....                                                            [ 52%]
tests/test_integration.py .....                                                       [ 82%]
tests/test_subscriber.py ...                                                          [100%]

===================================== warnings summary ======================================
../../../../venv/wazuh-unit/lib/python3.10/site-packages/google/pubsub_v1/services/publisher/client.py:17
  /home/gonzz/venv/wazuh-unit/lib/python3.10/site-packages/google/pubsub_v1/services/publisher/client.py:17: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils import util

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================== 17 passed, 1 warning in 0.04s ===============================
```

### Test Access Logs

<details><summary>Tests output</summary>

```
root@97cff1b2dfb7:/# /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket  -c /var/ossec/wodles/gcloud/credentials.json -l 1 -o 2021-jan-01 -T access_logs
gcloud_wodle - INFO - Processing test_1_new.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 1", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_22.txt
gcloud_wodle - INFO - Processing test_2_new.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 2", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_3.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 3", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_3_new.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 3", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_4.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 4", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_5.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 5", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_6.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 6", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Updating previously processed files.
gcloud_wodle - INFO - Received 7 messages

root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket  -c /var/ossec/wodles/gcloud/credentials.json -l 1 -o 2021-jan-01 -T access_log 
gcloud_wodle - ERROR - An exception happened while running the wodle: GCloudIntegrationTypeError: Unsupported gcloud integration type: "access_log".The supported types are ('pubsub', 'access_logs')
Traceback (most recent call last):
  File "/var/ossec/wodles/gcloud/gcloud.py", line 92, in main
    raise exceptions.GCloudError(3, integration_type=arguments.integration_type)
exceptions.GCloudError: GCloudIntegrationTypeError: Unsupported gcloud integration type: "access_log".The supported types are ('pubsub', 'access_logs')

root@4926b5380b7e:/var/ossec/wodles/gcloud# /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket  -c /var/ossec/wodles/gcloud/credentials.json -l 3 -o 2021-jan-01 -T access_log 
gcloud_wodle - ERROR - An exception happened while running the wodle: GCloudIntegrationTypeError: Unsupported gcloud integration type: "access_log".The supported types are ('pubsub', 'access_logs')

root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket  -c /var/ossec/wodles/gcloud/credentials.json -l 2 -o 2021-9jan-01 -T access_logs
usage: usage: gcloud.py [options]
gcloud.py: error: argument -o/--only_logs_after: Argument not a valid date in format YYYY-MMM-DD: '2021-9jan-01'.

root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -b framework-test-bucketo  -c /var/ossec/wodles/gcloud/credentials.json -l 2 -o 2021-jan-01 -T access_logs
gcloud_wodle - ERROR - An exception happened while running the wodle: GCloudBucketNotFound: The bucket 'framework-test-bucketo' does not exist
```

</details>



### Test Pub/Sub
<details><summary>Test output</summary>

```
root@97cff1b2dfb7:/# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 1 -s test_gcloud_blog -p wazuh-dev-123456 -c /var/ossec/wodles/gcloud/credentials.json  
gcloud_wodle - DEBUG - Setting 1 thread to pull 100 messages in total
...
gcloud_wodle - INFO - Received and acknowledged 100 messages

root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 2 -s wazuh-audit-log -p wazuh-dev-123456 -c /var/ossec/wodles/gcloud/credentials.json -m 10
gcloud_wodle - ERROR - An exception happened while running the wodle: GCloudPubSubProjectError: The 'wazuh-audit-log' project ID is incorrect or the user does not have permissions to access to it

root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 2 -s wazuh-audit-logs -p wazuh-dev-123456 -c /var/ossec/wodles/gcloud/credentials.json -m 10
gcloud_wodle - INFO - Received and acknowledged 10 messages

root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 2 -s wazuh-audit-logs -p wazuh-dev-123456 -c /var/ossec/wodles/gcloud/credentials.json -m 10 -t 99999
gcloud_wodle - WARNING - Reached maximum number of threads. Truncating to 80.
gcloud_wodle - INFO - Received and acknowledged 10 messages

root@4926b5380b7e:/var/ossec/wodles/gcloud# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 2 -s wazuh-audit-logs -p wazuh-dev-123456 -c /var/ossec/wodles/gcloud/credentials.json -m 10 -t -99999
gcloud_wodle - ERROR - An exception happened while running the wodle: GCloudPubSubNumThreadsError: The minimum number of threads is 1. Please check your configuration.

root@4926b5380b7e:/var/ossec/wodles/gcloud# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 2 -s wazuh-audit-logs -p wazuh-dev-1234568 -c /var/ossec/wodles/gcloud/credentials.json -m 10
gcloud_wodle - ERROR - An exception happened while running the wodle: GCloudPubSubSubscriptionError: The 'wazuh-dev-1234568' subscription is incorrect or the user credentials are not valid

root@d3599e41fbc1:/# /var/ossec/wodles/gcloud/gcloud -T pubsub -l 1 -s wazuh-audit-logs -p wazuh-dev-1234568 -c /var/ossec/wodles/gcloud/credentials.json -m 10 
gcloud_wodle - DEBUG - Setting 1 thread to pull 10 messages in total
gcloud_wodle - ERROR - An exception happened while running the wodle: GCloudPubSubSubscriptionError: The 'wazuh-dev-1234568' subscription is incorrect or the user credentials are not valid
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
    return callable_(* [...]

2022-03-15 10:07 UTC, CarlosRS9 requested changes

2022-03-15 10:07 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_integration.py
> +    (OSError, exceptions.GCloudInternalError, 801)
```suggestion
    (ConnectionRefusedError, exceptions.WazuhIntegrationInternalError, 1),
    (OSError, exceptions.WazuhIntegrationInternalError, 2)
```

2022-03-15 10:07 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_integration.py
> +        expected_exception: exceptions.GCloudException,
```suggestion
        expected_exception: exceptions.WazuhIntegrationException,
```

2022-03-15 10:07 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_integration.py
> +    expected_exception : exceptions.GCloudException
```suggestion
    expected_exception : exceptions.WazuhIntegrationException
```

2022-03-15 10:07 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_subscriber.py
> +                         exception: exceptions.GCloudException,
```suggestion
                         exception: exceptions.WazuhIntegrationException,
```

2022-03-15 10:07 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_subscriber.py
> +    exception : exceptions.GCloudException
```suggestion
    exception : exceptions.WazuhIntegrationException
```

2022-03-15 10:07 UTC, CarlosRS9 commented on wodles/gcloud/buckets/bucket.py
> +        GCloudError
```suggestion
        exceptions.GCloudError
```

2022-03-15 10:07 UTC, CarlosRS9 commented on wodles/gcloud/buckets/bucket.py
> +        GCloudError
```suggestion
        exceptions.GCloudError
```

2022-03-15 16:16 UTC, CarlosRS9 approved these changes
LGTM!

2022-03-17 10:09 UTC, merged