Avoid loading wevtapi.dll on Windows XP.
wazuh/wazuh pull request #12756
Opened 2022-03-17 09:48 UTC by antoniomanuelfr

|Related issue|
|---|
|12718|

## Description
This PR aims to fix the start on Windows without Event Channel support. The problem was that due to the changes in the syscheck building system,  we were adding always the wevtapi.dll, even when the OS doesn't support Event channel. 

I have tested the behavior on Windows XP

Closes #12718 

## Logs/Alerts example

![image](https://user-images.githubusercontent.com/22987701/158782598-6fa02cfa-ffe6-43b0-859e-2f9139b64814.png)

## Tests

- Compilation without warnings in every supported platform
  - [X] Windows
- [X] Source installation
- [X] Source upgrade

- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

2022-03-17 10:35 UTC, jotacarma90 approved these changes
LGTM
Just a unit test in Windows is failing

2022-03-17 11:23 UTC, FrancoRivero requested changes
CMocka tests is failing could you check them?

2022-03-18 11:01 UTC, chemamartinez approved these changes

2022-03-18 11:40 UTC, FrancoRivero approved these changes

2022-03-18 16:08 UTC, merged