[Agent-groups] Change the logger tag when processing agent-groups DB
wazuh/wazuh pull request #12766
Opened 2022-03-17 16:18 UTC by AdriiiPRodri

|Related issue|
|---|
|#12762|

## Description

This PR closes #12762. In this PR we have changed the tag for the loggers when processing the whole database. This change is motivated by the independence of the agent-groups tasks.

```
============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.9.5, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /mnt/c/Users/adr_i/git/wazuh/framework
plugins: asyncio-0.15.1, trio-0.7.0, cov-2.12.0, metadata-1.11.0, tavern-1.19.0, testinfra-6.4.0, html-3.1.1, aiohttp-0.3.0
collected 281 items

framework/wazuh/core/cluster/tests/test_client.py ................                                                                                                                                         [  5%]
framework/wazuh/core/cluster/tests/test_cluster.py ..................................                                                                                                                      [ 17%]
framework/wazuh/core/cluster/tests/test_common.py .............................................................................                                                                            [ 45%]
framework/wazuh/core/cluster/tests/test_control.py .....                                                                                                                                                   [ 46%]
framework/wazuh/core/cluster/tests/test_local_client.py .............                                                                                                                                      [ 51%]
framework/wazuh/core/cluster/tests/test_local_server.py .......................                                                                                                                            [ 59%]
framework/wazuh/core/cluster/tests/test_master.py .................................................                                                                                                        [ 77%]
framework/wazuh/core/cluster/tests/test_server.py ...................                                                                                                                                      [ 83%]
framework/wazuh/core/cluster/tests/test_utils.py ...........                                                                                                                                               [ 87%]
framework/wazuh/core/cluster/tests/test_worker.py ..................................                                                                                                                       [100%]

======================================================================================= 281 passed, 24 warnings in 29.37s ========================================================================================
```

2022-03-18 15:06 UTC, yanazaeva requested changes
GJ, but some changes are required.

2022-03-18 15:06 UTC, yanazaeva commented on framework/wazuh/core/cluster/worker.py
> +    """TODO
```suggestion
    """
```

2022-03-18 15:06 UTC, yanazaeva commented on framework/wazuh/core/cluster/worker.py
> +    """TODO
```suggestion
    """
```

2022-03-21 08:04 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/cluster.py
> -    def check_if_file_correspond_to_agent():
Right, everything related to extra-valid has been kept in the code, but this function refers to the agent-groups files, these have been completely removed and are not expected to return in the future.

2022-03-21 08:06 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/cluster.py
> +    #     extra_valid_function()
Consider this as a placeholder in case we activate extra-valid again in the future, so we know we can introduce some extra procedure at this point.

2022-03-21 08:43 UTC, yanazaeva approved these changes
LGTM

2022-03-21 11:41 UTC, davidjiglesias approved these changes

2022-03-21 11:41 UTC, merged