Fix the residual child process removal
wazuh/wazuh pull request #12808
Opened 2022-03-22 09:55 UTC by yanazaeva

|Related issue|
|---|
|#12783|

## Description

This closes #12783. The aim of this issue is to change how residual child processes are being deleted before new processes are started. This is done to avoid a scenario where 'zombie' children are still active meanwhile the father was unexpectedly terminated.

2022-03-22 10:43 UTC, AdriiiPRodri requested changes
After killing the main API process and the Cluster, when the service is restarted this error is displayed:
```
Starting Wazuh v4.4.0...
Traceback (most recent call last):
  File "/var/ossec/api/scripts/wazuh-apid.py", line 299, in <module>
    utils.clean_pid_files(API_MAIN_PROCESS)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/utils.py", line 58, in clean_pid_files
    os.kill(int(match.group(1)), signal.SIGKILL)
AttributeError: 'function' object has no attribute 'SIGKILL'
wazuh-apid did not start correctly.
```

2022-03-22 10:43 UTC, AdriiiPRodri commented on framework/wazuh/core/utils.py
> +                print(f"{daemon}: Residual child process {match.group(1)} was terminated.")
```suggestion
                print(f"{daemon}: Orphan process {match.group(1)} was terminated.")
```

2022-03-22 11:55 UTC, yanazaeva commented
## Update

After applying the changes requested by @AdriiiPRodri:
```
root@8781e8716174:/# ps -edf | grep clusterd
wazuh      13119       1  0 20:00 ?        00:00:05 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh      13227   13119  0 20:00 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh      13230   13119  0 20:00 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root       13576    1195  0 20:51 pts/0    00:00:00 grep --color=auto clusterd
root@8781e8716174:/# kill -9 13119
root@8781e8716174:/# ps -edf | grep clusterd
wazuh      13227       1  0 20:00 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh      13230       1  0 20:00 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root       13578    1195  0 20:51 pts/0    00:00:00 grep --color=auto clusterd
root@8781e8716174:/# service wazuh-manager status
wazuh-clusterd: Process 13119 not used by Wazuh, removing...
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
root@8781e8716174:/# service wazuh-manager restart
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.4.0 Stopped
2022/03/22 11:52:03 wazuh-db[13788] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/03/22 11:52:03 wazuh-db[13788] main.c:100 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/03/22 11:52:03 wazuh-remoted[13793] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/03/22 11:52:03 wazuh-remoted[13793] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/03/22 11:52:03 wazuh-remoted[13793] main.c:148 at main(): DEBUG: This is not a worker
Starting Wazuh v4.4.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/03/22 11:52:04 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
2022/03/22 11:52:04 wazuh-authd[13856] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/03/22 11:52:04 wazuh-authd[13856] config.c:20 at authd_read_config(): DEBUG: Reading configuration 'etc/ossec.conf'
2022/03/22 11:52:04 wazuh-authd[13856] main-server.c:372 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-authd...
2022/03/22 11:52:05 wazuh-db[13872] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/03/22 11:52:05 wazuh-db[13872] main.c:100 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
2022/03/22 11:52:08 wazuh-remoted[14034] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/03/22 11:52:08 wazuh-remoted[14034] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/03/22 11:52:08 wazuh-remoted[14034] main.c:148 at main(): DEBUG: This is not a worker
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
wazuh-clusterd: Orphan child process 13230 was terminated.
wazuh-clusterd: Orphan child process 13227 was terminated.
Started wazuh-clusterd...
Completed.
root@8781e8716174:/# ps -edf | grep clusterd
wazuh      14491       1  0 20:52 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh      14685   14491  0 20:52 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh      14688   14491  0 20:52 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root       14954    1195  0 20:53 pts/0    00:00:00 grep --color=auto clusterd
root@8781e8716174:/# ls -la /var/ossec/var/run/ | grep cluster
-rw-r----- 1 wazuh wazuh    6 Mar 22 20:52 wazuh-clusterd-14491.pid
-rw-r----- 1 wazuh wazuh    6 Mar 22 20:52 wazuh-clusterd_child_0-14685.pid
-rw-r----- 1 wazuh wazuh    6 Mar 22 20:52 wazuh-clusterd_child_1-14688.pid
```

2022-03-22 12:03 UTC, AdriiiPRodri approved these changes

2022-03-23 10:23 UTC, davidjiglesias reviewed
Rebase to 4.3

2022-03-23 11:21 UTC, yanazaeva commented
## Update 

<details>
<summary>Check functioning after rebase</summary>

```
root@ff2f1da61ac6:/# service wazuh-manager status
wazuh-clusterd is running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
root@ff2f1da61ac6:/# ps -edf | grep cluster
wazuh       2271       1  0 20:18 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh       2301    2271  0 20:18 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh       2304    2271  0 20:18 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root        2607    1179  0 20:18 pts/0    00:00:00 grep --color=auto cluster
root@ff2f1da61ac6:/# kill -9 2271
root@ff2f1da61ac6:/# ps -edf | grep cluster
wazuh       2301       1  0 20:18 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh       2304       1  0 20:18 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root        2610    1179  0 20:19 pts/0    00:00:00 grep --color=auto cluster
root@ff2f1da61ac6:/# ls -la /var/ossec/var/run/
total 80
drwxrwx--- 1 root  wazuh 4096 Mar 23 20:19 .
drwxr-x--- 1 root  wazuh 4096 Mar 23 20:18 ..
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:18 wazuh-analysisd-1520.pid
-rw-r----- 1 wazuh wazuh 2531 Mar 23 20:19 wazuh-analysisd.state
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:18 wazuh-apid-1425.pid
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:18 wazuh-apid_auth-1497.pid
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:18 wazuh-apid_exec-1494.pid
-rw-r----- 1 root  wazuh    5 Mar 23 20:18 wazuh-authd-1464.pid
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:18 wazuh-clusterd-2271.pid
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:18 wazuh-clusterd_child_0-2301.pid
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:18 wazuh-clusterd_child_1-2304.pid
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:18 wazuh-db-1480.pid
-rw-r----- 1 root  wazuh    5 Mar 23 20:18 wazuh-execd-1509.pid
-rw-r----- 1 root  wazuh    5 Mar 23 20:18 wazuh-logcollector-1723.pid
-rw-r----- 1 root  wazuh    5 Mar 23 20:18 wazuh-modulesd-1791.pid
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:18 wazuh-monitord-1741.pid
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:18 wazuh-remoted-1652.pid
-rw-r--r-- 1 wazuh wazuh  511 Mar 23 20:19 wazuh-remoted.state
-rw-r----- 1 root  wazuh    5 Mar 23 20:18 wazuh-syscheckd-1617.pid
root@ff2f1da61ac6:/# service wazuh-manager restart
wazuh-clusterd: Process 2271 not used by Wazuh, removing...
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.3.0 Stopped
2022/03/23 11:19:36 wazuh-db[2767] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/03/23 11:19:36 wazuh-db[2767] main.c:101 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/03/23 11:19:36 wazuh-remoted[2772] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/03/23 11:19:36 wazuh-remoted[2772] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/03/23 11:19:36 wazuh-remoted[2772] main.c:148 at main(): DEBUG: This is not a worker
Starting Wazuh v4.3.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/03/23 11:19:37 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
2022/03/23 11:19:37 wazuh-authd[2835] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/03/23 11:19:37 wazuh-authd[2835] config.c:20 at authd_read_config(): DEBUG: Reading configuration 'etc/ossec.conf'
2022/03/23 11:19:37 wazuh-authd[2835] main-server.c:372 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-authd...
2022/03/23 11:19:38 wazuh-db[2851] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/03/23 11:19:38 wazuh-db[2851] main.c:101 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
2022/03/23 11:19:41 wazuh-remoted[3019] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/03/23 11:19:41 wazuh-remoted[3019] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/03/23 11:19:41 wazuh-remoted[3019] main.c:148 at main(): DEBUG: This is not a worker
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
wazuh-clusterd: Orphan child process 2301 was terminated.
wazuh-clusterd: Orphan child process 2304 was terminated.
Started wazuh-clusterd...
Completed.
root@ff2f1da61ac6:/# ps -edf | grep cluster
wazuh       3662       1  2 20:19 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh       3670    3662  0 20:19 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh       3673    3662  0 20:19 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root        3887    1179  0 20:19 pts/0    00:00:00 grep --color=auto cluster
root@ff2f1da61ac6:/# ls -la /var/ossec/var/run/ | grep cluster
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:19 wazuh-clusterd-3662.pid
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:19 wazuh-clusterd_child_0-3670.pid
-rw-r----- 1 wazuh wazuh    5 Mar 23 20:19 wazuh-clusterd_child_1-3673.pid
```

</details>

2022-03-24 10:39 UTC, davidjiglesias approved these changes

2022-03-24 11:08 UTC, merged