Escape value name properly in state message.
wazuh/wazuh pull request #12881
Opened 2022-03-28 10:26 UTC by antoniomanuelfr

|Related issue|
|---|
|#12845|

## Description
Hi team!

This PR aims to properly escape the value name field in order to avoid the problem described in #12845 
Closes #12845  
## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
  - [X] Windows
  - [ ] MAC OS X
- [X] Source installation
- [X] Source upgrade
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory

2022-03-28 12:54 UTC, Dwordcito commented on src/syscheckd/src/db/src/db.cpp
> +                            std::string value_name = keyValue.second;
use camelCase, auto, and brace initialization!

2022-03-28 12:55 UTC, Dwordcito requested changes
looks good, few suggestions.

2022-03-28 14:46 UTC, FrancoRivero approved these changes
LGTM

2022-03-28 15:04 UTC, MarcelKemp approved these changes

2022-03-28 15:08 UTC, chemamartinez approved these changes

2022-03-29 02:16 UTC, Dwordcito approved these changes

2022-03-29 06:38 UTC, merged