Add check to test tool outputs
wazuh/wazuh pull request #12894
Opened 2022-03-28 23:24 UTC by FrancoRivero

…ainable

|Related issue|
|---|
||

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-04-07 09:59 UTC, antoniomanuelfr approved these changes

2022-04-07 15:02 UTC, FrancoRivero commented
![image](https://user-images.githubusercontent.com/11745030/162230217-b7961f5b-5a52-4889-a03e-0b1db43fb587.png)
These are the changes named in the last commit

2022-04-11 09:38 UTC, MarcelKemp approved these changes

2022-04-11 12:57 UTC, chemamartinez requested changes

2022-04-12 14:26 UTC, chemamartinez approved these changes

2022-04-18 08:35 UTC, antoniomanuelfr approved these changes

2022-04-21 15:23 UTC, jotacarma90 approved these changes
LGTM

2022-05-17 09:36 UTC, jotacarma90 approved these changes
Reviewed and tested!
LGTM

2022-05-17 10:13 UTC, chemamartinez approved these changes

2022-05-24 04:30 UTC, Dwordcito reviewed
Please remove the line breaks.
![image](https://user-images.githubusercontent.com/14300208/169949002-dd328117-8736-4c4c-baad-aa9edc06ea36.png)

2022-05-24 04:30 UTC, Dwordcito commented on src/Readme.md
> +| `-rc`, `--readytoreviewandclean` | Run all the quality checks needed to create a PR and clean results. Example: `python3 build.py -r <data_provider\|shared_modules/dbsync\|shared_modules/rsync\|sha
Use Single letter arguments.

https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

2022-05-24 04:30 UTC, Dwordcito commented on src/build.py
> +    parser.add_argument("-rc", "--readytoreviewandclean",
ditto

2022-05-31 11:11 UTC, jnasselle approved these changes

2022-06-01 09:11 UTC, merged