Change wazuh-logtest and wazuh-clusterd script names
wazuh/wazuh pull request #12926
Opened 2022-03-30 15:15 UTC by AdriiiPRodri

|Related issue|
|---|
|#12912|

## Description

This PR closes #12912. In this PR we have modified the names of the `wazuh-logtest` and `wazuh-clusterd` scripts. As indicated in the issue, these scripts did not follow the Python standard. For the user nothing has changed as the binary names remain the same:

```
root@wazuh-master:/var/ossec# tree bin
bin
|-- __init__
|-- agent_control
|-- agent_groups
|-- agent_upgrade
|-- clear_stats
|-- cluster_control
|-- manage_agents
|-- verify-agent-conf
|-- wazuh-agentlessd
|-- wazuh-analysisd
|-- wazuh-apid
|-- wazuh-authd
|-- wazuh-clusterd <-----
|-- wazuh-control
|-- wazuh-csyslogd
|-- wazuh-db
|-- wazuh-dbd
|-- wazuh-execd
|-- wazuh-integratord
|-- wazuh-logcollector
|-- wazuh-logtest <-----
|-- wazuh-logtest-legacy
|-- wazuh-maild
|-- wazuh-modulesd
|-- wazuh-monitord
|-- wazuh-regex
|-- wazuh-remoted
|-- wazuh-reportd
`-- wazuh-syscheckd
```

```
root@wazuh-master:/var/ossec# tree framework/scripts/
framework/scripts/
|-- __init__.py
|-- agent_groups.py
|-- agent_upgrade.py
|-- cluster_control.py
|-- wazuh_clusterd.py
`-- wazuh_logtest.py
```

2022-03-30 16:49 UTC, yanazaeva commented
While testing I obtain the following error:
```
yanazaeva@pop-os:~/wd-ar$ docker ps
CONTAINER ID   IMAGE        COMMAND                  CREATED          STATUS          PORTS                                           NAMES
e04ab6fbebfa   wd-manager   "/scripts/entrypoint…"   46 seconds ago   Up 45 seconds                                                   wd-ar_worker_1
3e25906ac11c   wd-manager   "/scripts/entrypoint…"   46 seconds ago   Up 45 seconds                                                   wd-ar_worker_2
6886e569e536   wd-nginx     "/scripts/entrypoint…"   46 seconds ago   Up 45 seconds   80/tcp                                          wd-ar_nginx_1
7a046c4df19b   wd-manager   "/scripts/entrypoint…"   47 seconds ago   Up 46 seconds   0.0.0.0:55555->55000/tcp, :::55555->55000/tcp   wd-ar_manager_1
yanazaeva@pop-os:~/wd-ar$ docker exec -it wd-ar_manager_1 bash
root@7a046c4df19b:/# /var/ossec/bin/wazuh-logtest
/var/ossec/framework/python/bin/python3: can't open file '/var/ossec/framework/scripts/wazuh-logtest.py': [Errno 2] No such file or directory
root@7a046c4df19b:/# 
root@7a046c4df19b:/# 
root@7a046c4df19b:/# /var/ossec/bin/cluster_control -l
ERROR: Cluster is not running.
root@7a046c4df19b:/# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd not running...
wazuh-monitord not running...
wazuh-logcollector not running...
wazuh-remoted not running...
wazuh-syscheckd not running...
wazuh-analysisd not running...
wazuh-maild not running...
wazuh-execd not running...
wazuh-db not running...
wazuh-authd not running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid not running...
root@7a046c4df19b:/# /var/ossec/bin/wazuh-control info  
WAZUH_VERSION="v4.4.0"
WAZUH_REVISION="40400"
WAZUH_TYPE="server"
root@7a046c4df19b:/# service wazuh-manager start
2022/03/30 16:43:26 wazuh-db[148] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/03/30 16:43:26 wazuh-db[148] main.c:100 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/03/30 16:43:26 wazuh-remoted[153] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/03/30 16:43:26 wazuh-remoted[153] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/03/30 16:43:26 wazuh-remoted[153] main.c:148 at main(): DEBUG: This is not a worker
/var/ossec/framework/python/bin/python3: can't open file '/var/ossec/framework/scripts/wazuh-clusterd.py': [Errno 2] No such file or directory
wazuh-clusterd: Configuration error. Exiting
```

2022-03-30 16:51 UTC, yanazaeva requested changes
GJ, but I face some problems

2022-03-31 08:54 UTC, yanazaeva commented
These problems were due to an incorrect mapping.

2022-03-31 10:15 UTC, davidjiglesias approved these changes

2022-03-31 10:15 UTC, merged