Accepts MacOS log_format conf linux/win
wazuh/wazuh pull request #13035
Opened 2022-04-04 16:31 UTC by juliancnn

|Related issue|
|---|
|Closes #12903|

## Description

Previously the configuration block of a localfile only supported `macos` log_format on a MacOS system.
This is a issue, since it is not recognized by linux, the manager detects that the next configuration block is invalid:

```
<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="activity,trace" level="info">process == "sshd" OR message CONTAINS "invalid"</query>
</localfile>
```

output:
```
# /var/ossec/bin/verify-agent-conf 

verify-agent-conf: Verifying [etc/shared/default/agent.conf]
2022/03/29 12:29:22 verify-agent-conf: ERROR: (1235): Invalid value for element 'log_format': macos.
2022/03/29 12:29:22 verify-agent-conf: ERROR: (1202): Configuration error at 'etc/shared/default/agent.conf'.
2022/03/29 12:29:22 verify-agent-conf: ERROR: (1207): Localfile remote configuration in 'etc/shared/default/agent.conf' is corrupted
```
To solve this, the same approach was taken as with evenchannel or eventlog, the configuration is accepted but ignored in its operation.

As with eventchannel, it will be accepted in the configuration and will be returned by the API.

Linux Agent config:
```
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/kern.log</location>
  </localfile>

<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="activity,trace" level="info">process == "sshd" OR message CONTAINS "invalid"</query>
</localfile>
<localfile>
    <location>Microsoft-Windows-PrintService/Operational</location>
    <log_format>eventchannel</log_format>
</localfile>
```
API response:
```json
go run /_shared/go_scripts/wazuh_sock.go -f /var/ossec/queue/sockets/logcollector -m "getconfig localfile"
Response: ok {
    "localfile": [
        {
            "file": "/var/log/kern.log",
            "logformat": "syslog",
            "ignore_binaries": "no",
            "only-future-events": "yes",
            "target": [
                "agent"
            ]
        },
        {
            "logformat": "eventchannel",
            "ignore_binaries": "no",
            "only-future-events": "yes",
            "target": [
                "agent"
            ],
            "reconnect_time": 5
        },
        {
            "logformat": "macos",
            "query": {
                "value": "process == \"sshd\" OR message CONTAINS \"invalid\"",
                "level": "info",
                "type": [
                    "activity",
                    "trace"
                ]
            },
            "ignore_binaries": "no",
            "only-future-events": "yes",
            "target": [
                "agent"
            ]
        }
    ]
}
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [x] Source installation
- [ ] Package installation
- [x] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [x] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [x] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-04-06 15:34 UTC, JcabreraC approved these changes
LGTM !

2022-04-06 15:56 UTC, juliancnn commented
LGTM! :rocket: :rocket: :rocket:

2022-04-06 17:48 UTC, vikman90 requested changes
GJ @juliancnn!

In addition to the suggestion above, I wonder if we should let every platform accept the configuration. I mean remove the `#ifdef` guard at _localfile-config.c_ so that every version of the agent applies the `localfile` stanza and log that the log format will be discarded (except on macOS, of course).

2022-04-06 17:48 UTC, vikman90 commented on src/error_messages/information_messages.h
> +#define LOGCOLLECTOR_ONLY_MACOS             "(9201): 'macos' log_format is only supported in macOS."
```suggestion
#define LOGCOLLECTOR_ONLY_MACOS             "(9201): 'macos' log format is only supported on macOS."
```

2022-04-06 18:54 UTC, juliancnn commented
> GJ @juliancnn!
> 
> In addition to the suggestion below, I wonder if we should let every platform accept the configuration. I mean remove the `#ifdef` guard at _localfile-config.c_ so that every version of the agent applies the `localfile` stanza and log that the log format will be discarded (except on macOS, of course).

Thank you vik!

The mesagges "(9201): 'macos' log format is only supported on macOS" message is logged by all non-MacOS platforms and is defined in the `else` here:

https://github.com/wazuh/wazuh/blob/455dd82625e735e47fe2cd7e59bbac42253d85aa/src/logcollector/logcollector.c#L352-L370

2022-04-07 09:08 UTC, vikman90 approved these changes

2022-04-07 09:09 UTC, merged