Refactor sync_integrity in master.py
wazuh/wazuh pull request #13065
Opened 2022-04-06 08:29 UTC by Selutario

|Related issue|
|---|
| Closes #12673 |

## Description

This PR refactors the `sync_integrity` method of the `MasterHandler` class, in `master.py`. This is intended to achieve these three things:
- Unify duplicate code in worker and master.
- Reduce the size of sync_integrity.
- Make it easier to understand.

Due to the large size of `sync_integrity`, it has been split into two new methods:
- **integrity_check:** It takes care of waiting for the zip to arrive from a worker, decompressing it and comparing the checksums.
- **integrity_sync:** t is responsible for compressing and sending the files and notifying the worker to process them. Most of the logic for this method has been moved to a new class in `common.py` named `SyncFiles`.

SyncFiles, in `common.py`, now bundles what was previously done to send files from master and worker. I've also made minor improvements to other functions like compare_files.

## Tests
### Unit tests
I have updated all the unit tests and added new ones. The coverage of the common.py and master.py modules, the most affected, has remained the same:
```
----------- coverage: platform linux, python 3.9.5-final-0 -----------
Name                                                      Stmts   Miss  Cover
-----------------------------------------------------------------------------
framework/wazuh/core/cluster/client.py                      146      0   100%
framework/wazuh/core/cluster/cluster.py                     279      1    99%
framework/wazuh/core/cluster/common.py                      515      1    99%
framework/wazuh/core/cluster/control.py                      69      1    99%
framework/wazuh/core/cluster/local_client.py                 95      0   100%
framework/wazuh/core/cluster/local_server.py                147      0   100%
framework/wazuh/core/cluster/master.py                      386      0   100%
framework/wazuh/core/cluster/server.py                      148      0   100%
framework/wazuh/core/cluster/utils.py                       141     10    93%
framework/wazuh/core/cluster/worker.py                      277      0   100%

2022-04-08 08:32 UTC, AdriiiPRodri requested changes

2022-04-08 08:32 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/common.py
> +            raise exc
```suggestion
        except Exception as e:
            # Notify the sending node to stop its task.
            exc = exception.WazuhClusterError(3039)
            await self.send_request(command=b'cancel_task',
                                    data=task_id.encode() + b' ' + json.dumps(exc, cls=WazuhJSONEncoder).encode())
            raise exc from e
```

2022-05-12 07:54 UTC, Selutario commented
## Tests result

I have run related system tests after solving conflicts and this is the result:

| | | | | | |
|--|--|--|--|--|--|
| **Test name** | **Pass** | **XFail/Skip** | **Fail** | **Issues Ref.** | **Status** |
| test_cluster/test_agent_files_deletion/test_agent_files_deletion.py | 1 | 0 | 0 |  | :green_circle: |
| test_cluster/test_agent_info_sync/test_agent_info_sync.py | 2 | 0 | 0 |  | :green_circle: |
| test_cluster/test_integrity_sync/test_integrity_sync.py | 4 | 0 | 0 |  | :green_circle: |

[Report](https://github.com/wazuh/wazuh/files/8676060/report.zip)

2022-05-17 08:03 UTC, AdriiiPRodri approved these changes

2022-05-19 10:32 UTC, davidjiglesias approved these changes

2022-05-19 10:32 UTC, merged