Change the hashing algorithm
wazuh/wazuh pull request #13079
Opened 2022-04-07 16:54 UTC by yanazaeva

|Related issue|
|---|
|#10915|

## Description

This closes #10915. The aim of this pull is to modify the hashing algorithm from MD5 to BLAKE2, as the latter is safer and quicker.

2022-04-12 09:03 UTC, AdriiiPRodri requested changes

2022-04-12 10:34 UTC, AdriiiPRodri requested changes

2022-04-12 10:34 UTC, AdriiiPRodri commented on framework/wazuh/core/utils.py
> +import logging
```suggestion
```

2022-04-12 10:37 UTC, AdriiiPRodri approved these changes

2022-04-20 08:05 UTC, davidjiglesias requested changes
Add changes to documentation

2022-04-20 10:27 UTC, davidjiglesias approved these changes

2022-04-20 10:27 UTC, merged