Add broadcasting system for the cluster
wazuh/wazuh pull request #13124
Opened 2022-04-13 13:12 UTC by Selutario

|Related issue|
|---|
| Closes #12912 |

## Description

This PR adds a new broadcasting system for the master node of the Wazuh cluster, as requested at #12912. 

To do this, an asynchronous queue is created for each AbstractServerHandler (there is one for each connected client), to which the functions to be executed are added. Thus, the functions will be executed as soon as the AbstractServerHandler in the most resource-efficient way possible.

![schema_1](https://user-images.githubusercontent.com/23361101/162743472-c5963435-aded-4a82-a556-8240ba7a599b.png)

## Broadcast methods
This broadcasting system adds three new methods to make use of it. They are defined inside the [AbstractServer class](https://github.com/wazuh/wazuh/blob/5ce9cd8e2ab79e147cfbeb33d911668a6be83903/framework/wazuh/core/cluster/server.py#L245-L248). Therefore, they can be used there or in any inheriting class (such as `Master` or `LocalServer`):
- <b>broadcast(f, *args, **kwargs):</b>  Run a function in all server handlers. There is one server handler for each connected client. Nothing is returned and it is not possible to check if the function was run in every server handler or the result.
- <b>broadcast_add(f, *args, **kwargs):</b> It works as the method above (broadcast) but it does return an identifier (`broadcast_id`). When this function is used, the result of each server handler is stored and it can be queried with its `broadcast_id`.
- <b>broadcast_pop(broadcast_id):</b> Receive `broadcast_id` as a parameter. It returns False if the request has not yet been run in all expected server handlers. Otherwise, a dict with the response for each one is returned (or True if the `broadcast_id` is unknown).

## Usage example

An example of use could be this development of agent-groups (#10771). Until now, due to the lack of a broadcasting method, a function was called from which each MasterHandler obtained the info:
https://github.com/wazuh/wazuh/blob/813c85f70612bfbbdba340d90c003408763fb65c/framework/wazuh/core/cluster/master.py#L1194-L1206

Now, it could just call `broadcast()`, specifying a reference to the `MasterHandler.send_agent_groups_information` method and the info as a keyword:
```PYTHON
        while True:
            try:
                before = perf_counter()
                sync_object.logger.info("Starting.")

                if len(self.clients.keys()) > 0:
                    if info := await sync_object.retrieve_information():
                        self.broadcast(MasterHandler.send_agent_groups_information, info)
                    after = perf_counter()
                    logger.info(f"Finished in {(after - before):.3f}s.")
                elif len(self.clients.keys()) == 0:
                    logger.info("No clients connected. Skipping.")
            except Exception as e:
                sync_object.logger.error(f"Error getting agent-groups from WDB: {e}")
```

There is no way to verify if the function has been run in all MasterHandlers. If that is required, `broadcast_add()` and `broadcast_pop()` could be used instead. `broadcast_pop` would return False until all handlers run the function:
```PYTHON
        bc_sent = False
        while True:
            try:
                before = perf_counter()
                sync_object.logger.info("Starting.")

                bc_sent = self.broadcast_pop(bc_id)
                if bc_sent and len(self.clients.keys()) > 0:
                    if info := await sync_object.retrieve_information():
                        bc_id = self.broadcast_add(MasterHandler.send_agent_groups_information, info)
                    after = perf_counter()
                    logger.info(f"Finished in {(after - before):.3f}s.")
                elif len(self.clients.keys()) == 0:
                    logger.info("No clients connected. Skipping.")
            except Exception as e:
                sync_object.logger.error(f"Error getting agent-groups from WDB: {e}")
```

2022-04-25 07:58 UTC, AdriiiPRodri requested changes

2022-04-25 07:58 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/server.py
>                  self.logger.error("Error during handshake with incoming connection.", exc_info=False)
```suggestion
        elif exc is None:
            self.logger.error("Error during handshake with incoming connection.", exc_info=False)

        else:
            self.logger.error(f"Error during handshake with incoming connection: {exc}. \n"
                              f"{''.join(traceback.format_tb(exc.__traceback__))}", exc_info=False)
```

2022-04-25 07:58 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/server.py
> +                pass
```suggestion
            with contextlib.suppress(KeyError):
                self.server.broadcast_results[q_item['broadcast_id']][self.name] = result
```

2022-04-25 07:58 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/server.py
> +
```suggestion
```

2022-04-25 07:58 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/server.py
> +                    self.broadcast_results[broadcast_id][name] = NO_RESULT
```suggestion
                    self.broadcast_results[broadcast_id][name] = AbstractServer.NO_RESULT
```

Add No_RESULT to AbstractServer as class variable

2022-04-25 07:58 UTC, AdriiiPRodri commented on framework/wazuh/core/cluster/server.py
> +            if name in self.clients and result == NO_RESULT:
```suggestion
            if name in self.clients and result == AbstractServer.NO_RESULT:
```

2022-05-05 15:33 UTC, AdriiiPRodri approved these changes

2022-05-20 07:26 UTC, davidjiglesias approved these changes

2022-05-20 07:27 UTC, merged