Sort `PUT /agents/upgrade`, `PUT /agents/upgrade_custom` and `GET /agents/upgrade_result` responses
wazuh/wazuh pull request #13178
Opened 2022-04-20 08:52 UTC by mcarmona99

|Related issue|
|---|
|#13069|

This pull request closes #13069.

With this PR, we ensure that all the responses of endpoints `PUT /agents/upgrade`, `PUT /agents/upgrade_custom` and `GET /agents/upgrade_result` are sorted by the `agent` key. This sorting was needed due to the fact that the response obtained from the socket was not always sorted, as the petitions were not responded sequentially.

As we can see in https://github.com/wazuh/wazuh/issues/13069#issuecomment-1102856916, times are slightly higher, but this little difference will not truly affect the endpoint performance.

No changes are needed on the API integration tests as the test cases failing are now always expected to pass.

### Test results

```
test_agent_PUT_endpoints.tavern.yaml - Cluster environment 
	 10 passed, 11 warnings

test_agent_GET_endpoints.tavern.yaml - Cluster environment 
	 92 passed, 93 warnings
```

2022-04-21 07:24 UTC, vicferpoy requested changes
Given those agent numbers, performance is significantly worse. Try using `itemgetter` instead of `lambda` and compare results, please.

2022-04-21 08:23 UTC, mcarmona99 commented
> Given those agent numbers, performance is significantly worse. Try using `itemgetter` instead of `lambda` and compare results, please.

After this change was requested, I made a test to see which one of these three versions is faster. (The first one is the fastest, but the others should be considered as an approach for this issue)

- `sorted(agents_list)`, with `agents_list` being a list of integers
- `agents_list.sort(lambda)`, with `agents_list` being a list of dictionaries
- `agents_list.sort(itemgetter)`, with `agents_list` being a list of dictionaries

<details>

<summary>scratch.py</summary>


```python
import random
import time
import operator

# 15,000,000 agents test
# Using an unordered list as it is the worst case possible

agents_list = list(range(1, 15000000))
random.shuffle(agents_list)

# Test 1, current code: sorted(agents_list), with agents_list being a list of integers

start = time.perf_counter()
result1 = sorted(agents_list)
print(time.perf_counter() - start)

# Test 2: agents_list.sort(lambda), with agents_list being a list of dictionaries

result2 = []
for agent in agents_list:
    result2.append({'agent': agent, 'task_id': agent})

start = time.perf_counter()
result2.sort(key=lambda x: x['agent'])
print(time.perf_counter() - start)

# Test 3: agents_list.sort(itemgetter), with agents_list being a list of dictionaries

result3 = []
for agent in agents_list:
    result3.append({'agent': agent, 'task_id': agent})

start = time.perf_counter()
result3.sort(key=operator.itemgetter('agent'))
print(time.perf_counter() - start)
```

</details>


An output given by this scratch is the following:

```
8.043813375999889
12.138777932000266
11.669286784000178
```

The `itemgetter` version is slightly faster. Therefore, we will use this solution instead of the one using `lambda`.

Also see the following image, ref: https://stackoverflow.com/questions/17243620/operator-itemgetter-or-lambda [Accessed 21 April 2022]

![image](https://user-images.githubusercontent.com/57481331/164412488-1800defd-8136-4227-ab8a-c5a20d8413fe.png)

2022-04-22 08:59 UTC, mcarmona99 commented
Blocked by https://github.com/wazuh/wazuh/pull/13201

2022-04-29 11:07 UTC, vicferpoy approved these changes
LGTM

2022-05-09 06:50 UTC, davidjiglesias approved these changes

2022-05-09 06:50 UTC, merged