Engine - Processing logic
wazuh/wazuh pull request #13211
Opened 2022-04-22 13:17 UTC by JcabreraC

|Related issue|
|---|
|#12633|

We need to align the semantics defined in our design document with the software we've created. Also, this software must be able to fit in the place of analysisd. Because of that, we've identified some friction points which we must address in order to operate within the rest of the Wazuh platform.

### Processing logic

Each graph node and each set of operations should behave as stated in the functional document. We need to implement some
logical combinations at the graph and operation levels. At least we need an exclusive or (XOR) ideally with a sorted list by the number of times an option has been selected.

We can implement this without own code, instead of using RXCPP primitives or combinators.

2022-04-27 10:51 UTC, Hamza1-coder commented
I am new here any issue for me ?

2022-04-28 23:24 UTC, juliancnn approved these changes
LGTM :rocket:

2022-04-29 12:53 UTC, juliancnn commented
## Acceptance test

With the acceptance tests, can be seen that there is no significant impact of EPS. Engine continues to respond in the same way.

|EPS | Debug | Release
|----|----|----|
|Master|788201|3937131|
|PR|739544|3912738|

![image](https://user-images.githubusercontent.com/1891958/165945537-f789e0ca-1da2-49ce-9acd-f47029d6c55f.png)


[assets_db](https://github.com/wazuh/wazuh/files/8590845/assets_db.zip)
[RAW Results](https://github.com/wazuh/wazuh/files/8590878/RAW.Results.txt)

2022-04-29 20:07 UTC, nmkoremblum requested changes

2022-04-29 20:07 UTC, nmkoremblum commented on src/engine/source/builder/builderTypes.hpp
>  #include "connectable.hpp"
```suggestion
#include "baseTypes.hpp"
#include "connectable.hpp"

#include <rxcpp/rx.hpp>
```

2022-05-02 13:36 UTC, juliancnn commented on src/engine/source/base/baseTypes.hpp
> +    using Lifter = std::function<Observable(Observable)>;
We will not use `using json::Document` in a header file

2022-05-02 13:36 UTC, juliancnn commented on src/engine/source/base/eventHandler.hpp
> +#include <json.hpp>
for internal libraries we use <>

2022-05-02 13:39 UTC, juliancnn commented on src/engine/source/base/eventHandler.hpp
> +    bool is_decoded; ///< True if it reached the end of the decoding stage
:+1:

2022-05-02 13:42 UTC, juliancnn commented on src/engine/source/builder/builderTypes.hpp
>  #include "connectable.hpp"
Should be:
```cpp
#include <rxcpp/rx.hpp>

#include <baseTypes.hpp>

#include "connectable.hpp"
```

2022-05-02 15:05 UTC, nmkoremblum approved these changes
LGTM :)

2022-05-02 15:05 UTC, merged