Dev 13037 hlp Refinements
wazuh/wazuh pull request #13233
Opened 2022-04-25 18:16 UTC by san1526

|Related issue|
|---|
|#13037|

## Description
- Added boolean parser
- Added 'to end of line' parser
- Added number parser (long and float)
- Changed ParseResult to be of type std::any
- Updated bench and UTs
- Added a function to configure hlp mappings
- Reworked the catalog to be simpler

2022-04-26 15:48 UTC, palaciosjeremias approved these changes
LGTM

2022-04-28 17:47 UTC, juliancnn approved these changes
LGTM

2022-04-29 12:32 UTC, JcabreraC approved these changes
LGTM !

2022-04-29 13:48 UTC, nmkoremblum requested changes

2022-04-29 13:48 UTC, nmkoremblum commented on src/engine/source/hlp/include/hlp/hlp.hpp
> +#include <any>
```suggestion
#define _HLP_H

#include <any>
```

2022-04-29 13:48 UTC, nmkoremblum commented on src/engine/source/hlp/src/hlp.cpp
>  #include <profile/profile.hpp>
```suggestion
#include "hlpDetails.hpp"
#include "logQLParser.hpp"
#include "specificParsers.hpp"

#include <hlp/hlp.hpp>
#include <logging/logging.hpp>
#include <profile/profile.hpp>
#include <rapidjson/document.h>
```

2022-04-29 13:48 UTC, nmkoremblum commented on src/engine/source/hlp/src/specificParsers.cpp
> +#include <profile/profile.hpp>
```suggestion
#include "date/date.h"
#include "hlpDetails.hpp"
#include "specificParsers.hpp"
#include "tld.hpp"

#include <profile/profile.hpp>
#include <rapidjson/stringbuffer.h>
#include <rapidjson/writer.h>
```

2022-04-29 13:48 UTC, nmkoremblum commented on src/engine/test/source/hlp/hlp_test.cpp
>  #include "gtest/gtest.h"
```suggestion
#include <gtest/gtest.h>
```

2022-04-29 17:37 UTC, juliancnn approved these changes

2022-04-29 17:37 UTC, juliancnn commented on src/engine/source/builder/builders/stageParse.cpp
> +        doc->set(path, {nullptr, doc->getAllocator()});
```suggestion
        json::Value val;
        val.SetNull();
        doc->set(path, val);
```

2022-04-29 21:12 UTC, LucioDonda commented on src/engine/source/builder/builders/stageParse.cpp
> +        doc->set(path, {nullptr, doc->getAllocator()});
done!

2022-04-29 21:12 UTC, LucioDonda commented on src/engine/test/source/hlp/hlp_test.cpp
>  #include "gtest/gtest.h"
done!

2022-04-29 21:12 UTC, LucioDonda commented on src/engine/source/hlp/src/specificParsers.cpp
> +#include <profile/profile.hpp>
done!

2022-04-29 21:12 UTC, LucioDonda commented on src/engine/source/hlp/src/hlp.cpp
>  #include <profile/profile.hpp>
done!

2022-04-29 21:12 UTC, LucioDonda commented on src/engine/source/hlp/include/hlp/hlp.hpp
> +#include <any>
done!

2022-04-29 21:20 UTC, LucioDonda commented
UT ok:
![Screenshot from 2022-04-29 18-17-28](https://user-images.githubusercontent.com/95248059/166070474-227a168d-5f79-48e2-948c-e16ac6dc1ab5.png)

Benchmark:
![Screenshot from 2022-04-29 18-15-57](https://user-images.githubusercontent.com/95248059/166070511-1dd1be69-f5a9-443a-9204-d88b8557305a.png)

Benchmark_tool for engine:
![Screenshot from 2022-04-29 18-13-15](https://user-images.githubusercontent.com/95248059/166070553-7f71634b-ea8d-424c-835a-fc7b2093e84f.png)

Pending modification of not found parser, this should return error notifying user

2022-05-02 20:54 UTC, nmkoremblum approved these changes
LGTM :)

2022-05-02 21:03 UTC, juliancnn approved these changes
LGTM! :rocket: 
For next iteration:
- Move error msg on build asset steps
- Add catalog test
- Remove cli tools HLP
- Add tracer

2022-05-02 21:04 UTC, merged