Fix Winagent symbol stripping silent failure
wazuh/wazuh pull request #13269
Opened 2022-04-28 19:49 UTC by RamiroRD

|Related issue|
|---|
|#13255|

## Description

This PR fixes an issue where the symbol stripping process would fail without making the whole invocation to `make` fail. 
It does this by implementing the following logic:
If WIN_STRIP_TOOL_PATH is set, it checks whether cv2pdb.exe exists and wine is installed. If any of these last two conditions are not met, it causes the whole `make` invocation to fail.
If WIN_STRIP_TOOL_PATH is not set, then it 

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-04-28 20:51 UTC, HanesSciarrone requested changes

2022-04-28 20:51 UTC, HanesSciarrone commented on src/Makefile
> +		if test -d "${WIN_STRIP_TOOL_PATH}" -a -f "${WIN_STRIP_TOOL_PATH}/cv2pdb.exe" && command -v wine > /dev/null 2>&1; then \
I think that the use of `-a` and `-f` in the `if` condition is redundant

> [ -a FILE ]  - True if FILE exists.
> [ -f FILE ]  - True if FILE exists and is a regular file.

Flags `-f` is enough

2022-04-28 21:29 UTC, HanesSciarrone commented on src/Makefile
> +		if test -d "${WIN_STRIP_TOOL_PATH}" -a -f "${WIN_STRIP_TOOL_PATH}/cv2pdb.exe" && command -v wine > /dev/null 2>&1; then \
With the `test` command the meaning of the `-a` flag is different. Please @RamiroRD discard this change request.

2022-04-28 21:29 UTC, HanesSciarrone approved these changes

2022-04-29 12:31 UTC, jnasselle commented on src/Makefile
> +			return 1; \
My bad. && should be used to conditionally execute false

2022-04-29 12:57 UTC, jnasselle commented
### No WIN_STRIP_TOOL_PATH. Fallback stripping should be executed
`make TARGET=winagent -j4`
```sh
make[1]: Leaving directory '/root/repos/wazuh/src'
cd win32/ && ./unix2dos.pl ossec.conf > default-ossec.conf
cd win32/ && ./unix2dos.pl help.txt > help_win.txt
cd win32/ && ./unix2dos.pl ../../etc/internal_options.conf > internal_options.conf
cd win32/ && ./unix2dos.pl ../../etc/local_internal_options-win.conf > default-local_internal_options.conf
cd win32/ && ./unix2dos.pl ../../LICENSE > LICENSE.txt
cd win32/ && ./unix2dos.pl ../VERSION > VERSION
cd win32/ && ./unix2dos.pl ../REVISION > REVISION
cd win32/ && makensis wazuh-installer.nsi
Processing config: /etc/nsisconf.nsh
Processing script file: "wazuh-installer.nsi" (UTF8)

Processed 1 file, writing output (x86-ansi):
warning 7998: ANSI targets are deprecated

Output: "wazuh-agent-4.4.0.exe"
Install: 6 pages (384 bytes), 3 sections (12360 bytes), 1166 instructions (32648 bytes), 407 strings (33462 bytes), 1 language table (346 bytes).
Uninstall: 4 pages (320 bytes), 1 section (4120 bytes), 520 instructions (14560 bytes), 233 strings (4161 bytes), 1 language table (290 bytes).

Using zlib compression.

EXE header size:               97280 / 78336 bytes
Install code:                  16885 / 70448 bytes
Install data:                5690526 / 15603340 bytes
Uninstall code+data:           42039 / 56939 bytes
CRC (0x71FD6142):                  4 / 4 bytes

Total size:                  5846734 / 15809067 bytes (36.9%)

1 warning:
  7998: ANSI targets are deprecated
make settings
make[1]: Entering directory '/root/repos/wazuh/src'

General settings:
    TARGET:                  winagent
    V:                       
    DEBUG:                   
    DEBUGAD                  
    INSTALLDIR:              
    BUILD_VERSION            
    DATABASE:                
    ONEWAY:                  no
    CLEANFULL:               no
    RESOURCES_URL:           https://packages.wazuh.com/deps/16-9913
    EXTERNAL_SRC_ONLY:       
User settings:
    WAZUH_GROUP:             wazuh
    WAZUH_USER:              wazuh
USE settings:
    USE_ZEROMQ:              no
    USE_GEOIP:               no
    USE_PRELUDE:             no
    USE_INOTIFY:             no
    USE_BIG_ENDIAN:          no
    USE_SELINUX:             no
    USE_AUDIT:               no
    DISABLE_SYSC:            no
    DISABLE_CISCAT:          no
    DISABLE_STRIP_SYMBOLS:   no
Mysql settings:
    includes:                
    libs:                    
Pgsql settings:
    includes:                
    libs:                    
Defines:
    -DOSSECHIDS -DUSER="wazuh" -DGROUPGLOBAL="wazuh" -DENABLE_SYSC -DENABLE_CISCAT
Compiler:
    CFLAGS                   -pthread -g -DNDEBUG -O2 -DOSSECHIDS -DUSER="wazuh" -DGROUPGLOBAL="wazuh" -DENABLE_SYSC -DENABLE_CISCAT -pipe -Wall -Wextra -std=gnu99 -I./ -I./headers/ -Iexternal/openssl/include -Iexternal/cJSON/ -Iexternal/libyaml/include -Iexternal/curl/include -Iexternal/msgpack/include -Iexternal/bzip2/ -Ishared_modules/common -Ishared_modules/dbsync/include -Ishared_modules/rsync/include -Iwazuh_modules/syscollector/include  -Idata_provider/include  -Iexternal/libpcre2/include -Iexternal/rpm//builddir/output/include 
    LDFLAGS                  -pthread -O2 -Lshared_modules/dbsync/build/bin -Lshared_modules/rsync/build/bin  -Lwazuh_modules/syscollector/build/bin -Ldata_provider/build/bin
    LIBS                     
    CC                       gcc
    MAKE                     make
make[1]: Leaving directory '/root/repos/wazuh/src'

Done building winagent
```
```sh
# ls -l symbols
total 0
# i686-w64-mingw32-objdump -h libwazuhext.dll | grep -q ".debug_info"
# echo $?                                                                                                                                                                   1 ↵
1
```
### Invalid path
`make TARGET=winagent -j4  WIN_STRIP_TOOL_PATH=/root/thispathdoesnotexist`
```sh
make[1]: Entering directory '/root/repos/wazuh/src'
Error during debug symbols stripping: cv2pdb.exe or wine were not found.
make[1]: *** [Makefile:825: strip] Error 1
make[1]: Leaving directory '/root/repos/wazuh/src'
make: *** [Makefile:853: winagent] Error 2
```
### Path exist, cv2pdb.exe not
`mv /root/wintools/cv2pdb.exe /root/wintools/cv2pdb.exe.bak ; make TARGET=winagent -j4  WIN_STRIP_TOOL_PATH=/root/wintools`
```sh
make[1]: Entering directory '/root/repos/wazuh/src'
Error during debug symbols stripping: cv2pdb.exe or wine were not found.
make[1]: *** [Makefile:825: strip] Error 1
make[1]: Leaving directory '/root/repos/wazuh/src'
make: *** [Makefile:853: winagent] Error 2
```
### Path exist, cv2pdb.exe also, wine does not
`mv /usr/bin/wine /usr/bin/wine.bak ; make TARGET=winagent -j4  WIN_STRIP_TOOL_PATH=/root/wintools`
```sh
make[1]: Entering directory '/root/repos/wazuh/src'
Error during debug symbols stripping: cv2pdb.exe or wine were not found.
make[1]: *** [Makefile:825: strip] Error 1
make[1]: Leaving directory '/root/repos/wazuh/src'
make: *** [Makefile:853: winagent] Error 2
```
### Tools are ok! 
`mv /usr/bin/wine /usr/bin/wine.bak ; make TARGET=winagent -j4  WIN_STRIP_TOOL_PATH=/root/wintools`
```sh
make[1]: Leaving directory '/root/repos/wazuh/src'
make[1]: Entering directory '/root/repos/wazuh/src'
make[1]: Leaving directory '/root/repos/wazuh/src'
cd win32/ && ./unix2dos.pl ossec.conf > default-ossec.conf
cd win32/ && ./unix2dos.pl help.txt > help_win.txt
cd win32/ && ./unix2dos.pl ../../etc/internal_options.conf > internal_options.conf
cd win32/ && ./unix2dos.pl ../../etc/local_internal_options-win.conf > default-local_internal_options.conf
cd win32/ && ./unix2dos.pl ../../LICENSE > LICENSE.txt
cd win32/ && ./unix2dos.pl ../VERSION > VERSION
cd win32/ && ./unix2dos.pl ../REVISION > REVISION
cd win32/ && makensis wazuh-installer.nsi
Processing config: /etc/nsisconf.nsh
Processing script file: "wazuh-installer.nsi" (UTF8)

Processed 1 file, writing output (x86-ansi):
warning 7998: ANSI targets are deprecated

Output: "/root/repos/wazuh/src/win32/wazuh-agent-4.4.0.exe"
Install: 6 pages (384 bytes), 3 sections (12360 bytes), 1166 instructions (32648 bytes), 407 strings (33462 bytes), 1 language table (346 bytes).
Uninstall: 4 pages (320 bytes), 1 section (4120 bytes), 520 instructions (14560 bytes), 233 strings (4161 bytes), 1 language table (290 bytes).

Using zlib compression.

EXE header size:               97280 / 78336 bytes
Install code:                  16885 / 70448 bytes
Install data:                5650334 / 15461148 bytes
Uninstall code+data:           42039 / 56939 bytes
CRC (0x3EDE4A5F):                  4 / 4 bytes

Total size:                  5806542 / 15666875 bytes (37.0%)

1 warning:
  7998: ANSI targets are deprecated
make settings
make[1]: Entering directory '/root/repos/wazuh/src'

General settings:
    TARGET:                  winagent
    V:                       
    DEBUG:                   
    DEBUGAD                  
    INSTALLDIR:              
    BUILD_VERSION            
    DATABASE:                
    ONEWAY:                  no
    CLEANFULL:               no
    RESOURCES_URL:           https://packages.wazuh.com/deps/16-9913
    EXTERNAL_SRC_ONLY:       
User settings:
    WAZUH_GROUP:             wazuh
    WAZUH_USER:              wazuh
USE settings:
    USE_ZEROMQ:              no
    USE_GEOIP:               no
    USE_PRELUDE:             no
    USE_INOTIFY:             no
    USE_BIG_ENDIAN:          no
    USE_SELINUX:             no
    USE_AUDIT:               no
    DISABLE_SYSC:            no
    DISABLE_CISCAT:          no
    DISABLE_STRIP_SYMBOLS:   no
Mysql settings:
    includes:                
    libs:                    
Pgsql settings:
    includes:                
    libs:                    
Defines:
    -DOSSECHIDS -DUSER="wazuh" -DGROUPGLOBAL="wazuh" -DENABLE_SYSC -DENABLE_CISCAT
Compiler:
    CFLAGS                   -pthread -g -DNDEBUG -O2 -DOSSECHIDS -DUSER="wazuh" -DGROUPGLOBAL="wazuh" -DE [...]

2022-04-29 12:58 UTC, jnasselle approved these changes

2022-04-29 13:04 UTC, HanesSciarrone approved these changes

2022-04-30 02:09 UTC, Dwordcito commented
Without WIN_STRIP_TOOL_PATH
```
cp /usr/i686-w64-mingw32/lib/libwinpthread-1.dll win32/libwinpthread-1.dll
make win32/wazuh-agent.exe win32/wazuh-agent-eventchannel.exe win32/manage_agents.exe win32/setup-windows.exe win32/setup-syscheck.exe win32/setup-iis.exe win32/os_win32ui.exe win32/agent-auth.exe win32/syscollector CFLAGS="-DCLIENT -D_POSIX_C_SOURCE -DWIN32 -DPSAPI_VERSION=1" LIBS="-lwsock32 -lwevtapi -lshlwapi -lcomctl32 -ladvapi32 -lkernel32 -lpsapi -lgdi32 -liphlpapi -lws2_32 -lcrypt32"
make[1]: Entering directory '/home/dwordcito/Development/wazuh/src'
    [34;1mCC[0m [37;1mwin32/version-app.o[0m
    [34;1mCC[0m [37;1mwin32/icon.o[0m
    [34mCC[0m [33mwin32/win_agent.o[0m
    [34mCC[0m [33mwin32/win_service.o[0m
    [34mCC[0m [33mwin32/win_utils.o[0m
    [34mCC[0m [33msyscheckd/db/schema_fim_db.o[0m
    [34mCC[0m [33msyscheckd/config.o[0m
    [34mCC[0m [33msyscheckd/create_db.o[0m
    [34mCC[0m [33msyscheckd/fim_diff_changes.o[0m
    [34mCC[0m [33msyscheckd/fim_sync.o[0m
    [34mCC[0m [33msyscheckd/main.o[0m
    [34mCC[0m [33msyscheckd/run_check.o[0m
    [34mCC[0m [33msyscheckd/run_realtime.o[0m
    [34mCC[0m [33msyscheckd/syscheck.o[0m
    [34mCC[0m [33msyscheckd/syscom.o[0m
    [34mCC[0m [33msyscheckd/db/fim_db.o[0m
    [34mCC[0m [33msyscheckd/db/fim_db_registries.o[0m
    [34mCC[0m [33msyscheckd/db/fim_db_files.o[0m
    [34mCC[0m [33msyscheckd/whodata/audit_healthcheck.o[0m
    [34mCC[0m [33msyscheckd/whodata/audit_parse.o[0m
    [34mCC[0m [33msyscheckd/whodata/audit_rule_handling.o[0m
    [34mCC[0m [33msyscheckd/whodata/syscheck_audit.o[0m
    [34mCC[0m [33msyscheckd/whodata/win_whodata.o[0m
    [34mCC[0m [33msyscheckd/registry/events.o[0m
    [34mCC[0m [33msyscheckd/registry/registry.o[0m
    [34mCC[0m [33mrootcheck/check_open_ports.o[0m
    [34mCC[0m [33mrootcheck/check_rc_dev.o[0m
    [34mCC[0m [33mrootcheck/check_rc_files.o[0m
    [34mCC[0m [33mrootcheck/check_rc_if.o[0m
    [34mCC[0m [33mrootcheck/check_rc_pids.o[0m
    [34mCC[0m [33mrootcheck/check_rc_policy.o[0m
    [34mCC[0m [33mrootcheck/check_rc_ports.o[0m
    [34mCC[0m [33mrootcheck/check_rc_readproc.o[0m
    [34mCC[0m [33mrootcheck/check_rc_sys.o[0m
    [34mCC[0m [33mrootcheck/check_rc_trojans.o[0m
    [34mCC[0m [33mrootcheck/common.o[0m
    [34mCC[0m [33mrootcheck/common_rcl.o[0m
    [34mCC[0m [33mrootcheck/config.o[0m
    [34mCC[0m [33mrootcheck/os_string.o[0m
    [34mCC[0m [33mrootcheck/rootcheck.o[0m
    [34mCC[0m [33mrootcheck/rootcheck-config.o[0m
    [34mCC[0m [33mrootcheck/run_rk_check.o[0m
    [34mCC[0m [33mrootcheck/unix-process.o[0m
    [34mCC[0m [33mrootcheck/win-common.o[0m
    [34mCC[0m [33mrootcheck/win-process.o[0m
    [34mCC[0m [33mclient-agent/agcom.o[0m
    [34mCC[0m [33mclient-agent/buffer.o[0m
    [34mCC[0m [33mclient-agent/config.o[0m
    [34mCC[0m [33mclient-agent/notify.o[0m
    [34mCC[0m [33mclient-agent/receiver.o[0m
    [34mCC[0m [33mclient-agent/receiver-win.o[0m
    [34mCC[0m [33mclient-agent/request.o[0m
    [34mCC[0m [33mclient-agent/restart_agent.o[0m
    [34mCC[0m [33mclient-agent/rotate_log.o[0m
    [34mCC[0m [33mclient-agent/sendmsg.o[0m
    [34mCC[0m [33mclient-agent/start_agent.o[0m
    [34mCC[0m [33mclient-agent/state.o[0m
    [34mCC[0m [33mlogcollector/config.o[0m
    [34mCC[0m [33mlogcollector/lccom.o[0m
    [34mCC[0m [33mlogcollector/logcollector.o[0m
    [34mCC[0m [33mlogcollector/macos_log.o[0m
    [34mCC[0m [33mlogcollector/read_audit.o[0m
    [34mCC[0m [33mlogcollector/read_command.o[0m
    [34mCC[0m [33mlogcollector/read_djb_multilog.o[0m
    [34mCC[0m [33mlogcollector/read_fullcommand.o[0m
    [34mCC[0m [33mlogcollector/read_json.o[0m
    [34mCC[0m [33mlogcollector/read_macos.o[0m
    [34mCC[0m [33mlogcollector/read_mssql_log.o[0m
    [34mCC[0m [33mlogcollector/read_multiline.o[0m
    [34mCC[0m [33mlogcollector/read_multiline_regex.o[0m
    [34mCC[0m [33mlogcollector/read_mysql_log.o[0m
    [34mCC[0m [33mlogcollector/read_nmapg.o[0m
    [34mCC[0m [33mlogcollector/read_ossecalert.o[0m
    [34mCC[0m [33mlogcollector/read_postgresql_log.o[0m
    [34mCC[0m [33mlogcollector/read_snortfull.o[0m
    [34mCC[0m [33mlogcollector/read_syslog.o[0m
    [34mCC[0m [33mlogcollector/read_ucs2_be.o[0m
    [34mCC[0m [33mlogcollector/read_ucs2_le.o[0m
    [34mCC[0m [33mlogcollector/read_win_el.o[0m
    [34mCC[0m [33mlogcollector/read_win_event_channel.o[0m
    [34mCC[0m [33mlogcollector/state.o[0m
    [34mCC[0m [33mos_execd/config.o[0m
    [34mCC[0m [33mos_execd/exec.o[0m
    [34mCC[0m [33mos_execd/execd.o[0m
    [34mCC[0m [33mos_execd/wcom.o[0m
    [34mCC[0m [33mos_execd/win_execd.o[0m
    [34mCC[0m [33mactive-response/active_responses.o[0m
    [34mCC[0m [33mmonitord/rotate_log.o[0m
    [34mCC[0m [33mmonitord/compress_log.o[0m
    [34mCC[0m [33mconfig/active-response.o[0m
    [34mCC[0m [33mconfig/agentlessd-config.o[0m
    [34mCC[0m [33mconfig/alerts-config.o[0m
    [34mCC[0m [33mconfig/authd-config.o[0m
    [34mCC[0m [33mconfig/buffer-config.o[0m
    [34mCC[0m [33mconfig/client-config.o[0m
    [34mCC[0m [33mconfig/cluster-config.o[0m
    [34mCC[0m [33mconfig/config.o[0m
    [34mCC[0m [33mconfig/csyslogd-config.o[0m
    [34mCC[0m [33mconfig/dbd-config.o[0m
    [34mCC[0m [33mconfig/email-alerts-config.o[0m
    [34mCC[0m [33mconfig/global-config.o[0m
    [34mCC[0m [33mconfig/integrator-config.o[0m
    [34mCC[0m [33mconfig/labels-config.o[0m
    [34mCC[0m [33mconfig/localfile-config.o[0m
    [34mCC[0m [33mconfig/logtest-config.o[0m
    [34mCC[0m [33mconfig/remote-config.o[0m
    [34mCC[0m [33mconfig/reports-config.o[0m
    [34mCC[0m [33mconfig/rootcheck-config.o[0m
    [34mCC[0m [33mconfig/rules-config.o[0m
    [34mCC[0m [33mconfig/socket-config.o[0m
    [34mCC[0m [33mconfig/syscheck-config.o[0m
    [34mCC[0m [33mconfig/wmodules-agent-upgrade.o[0m
    [34mCC[0m [33mconfig/wmodules-aws.o[0m
    [34mCC[0m [33mconfig/wmodules-azure.o[0m
    [34mCC[0m [33mconfig/wmodules-ciscat.o[0m
    [34mCC[0m [33mconfig/wmodules-command.o[0m
    [34mCC[0m [33mconfig/wmodules-config.o[0m
    [34mCC[0m [33mconfig/wmodules-docker.o[0m
    [34mCC[0m [33mconfig/wmodules-fluent.o[0m
    [34mCC[0m [33mconfig/wmodules-gcp.o[0m
    [34mCC[0m [33mconfig/wmodules-github.o[0m
    [34mCC[0m [33mconfig/wmodules-key-request.o[0m
    [34mCC[0m [33mconfig/wmodules-office365.o[0m
    [34mCC[0m [33mconfig/wmodules-oscap.o[0m
    [34mCC[0m [33mconfig/wmodules-osquery-monitor.o[0m
    [34mCC[0m [33mconfig/wmodules-sca.o[0m
    [34mCC[0m [33mconfig/wmodules_syscollector.o[0m
    [34mCC[0m [33mconfig/wmodules-task-manager.o[0m
    [34mCC[0m [33mconfig/wmodules-vuln-detector.o[0m
    [34mCC[0m [33mwazuh_modules/wm_aws.o[0m
    [34mCC[0m [33mwazuh_modules/wm_azure.o[0m
    [34mCC[0m [33mwazuh_modules/wm_ciscat.o[0m
    [34mCC[0m [33mwazuh_modules/wmcom.o[0m
    [34mCC[0m [33mwazuh_modules/wm_command.o[0m
    [34mCC[0m [33mwazuh_modules/wm_control.o[0m
    [34mCC[0m [33mwazuh_modules/wm_database.o[0m
    [34mCC[0m [33mwazuh_modules/wm_docker.o[0m
    [34mCC[0m [33mwazuh_modules/wm_download.o[0m
    [34mCC[0m [33mwazuh_modules/wm_exec.o[0m
    [34mCC[0m [33mwazuh_modules/wm_fluent.o[0m
    [34mCC[0m [33mwazuh_modules/wm_gcp.o[0m
    [34mCC[0m [33mwazuh_modules/wm_github.o[0m
    [34mCC[0m [33mwazuh_modules/wm_keyrequest.o[0m
    [34mCC[0m [33mwazuh_modules/wmodules.o[0m
    [34mCC[0m [33mwazuh_modules/wm_office365.o[0m
    [34mCC[0m [33mwazuh_modules/wm_oscap.o[0m
    [34mCC[0m [33mwazuh_modules/wm_osquery_monitor.o [...]

2022-04-30 02:11 UTC, Dwordcito approved these changes
Based on functional test, I will approve this PR.

2022-04-30 02:11 UTC, merged