Review and update Gcloud unit tests
wazuh/wazuh pull request #13573
Opened 2022-05-24 11:30 UTC by CarlosRS9

|Related issue|
|---|
| #13389 |

# Description
In #13389 we have reviewed, updated, replaced existing unit tests for our gcloud module while adding new ones to expand code coverage up to 99%. This is the actual coverage using the new unit tests:

```
---------- coverage: platform linux, python 3.10.4-final-0 -----------
Name                               Stmts   Miss  Cover   Missing
----------------------------------------------------------------
gcloud/buckets/access_logs.py         16      0   100%
gcloud/buckets/bucket.py             128      2    98%   26-27
gcloud/exceptions.py                  23      0   100%
gcloud/gcloud.py                      68      1    99%   111
gcloud/integration.py                 36      1    97%   38
gcloud/pubsub/subscriber.py           60      2    97%   21-22
gcloud/tests/test_bucket.py          225      0   100%
gcloud/tests/test_gcloud.py           35      0   100%
gcloud/tests/test_integration.py      53      0   100%
gcloud/tests/test_subscriber.py       73      0   100%
gcloud/tests/test_tools.py            34      0   100%
gcloud/tools.py                       41      0   100%
----------------------------------------------------------------
TOTAL                                792      6    99%

```

To achieve this it was necessary to replace existing unit tests and create them from start. However, it has not been possible to create a `tools.py` auxiliary module for the unit tests due to the problem of the wodle folder not being an installable python package. Once #12874 is addressed, it will be possible to do so, further optimising the design of these unit tests.

The extensive code review has resulted in several optimizations, changes and removal of some parts of the code. Because of that, manual testing was necessary to ensure everything still works as expected.

2022-05-30 08:34 UTC, mcarmona99 requested changes

2022-05-30 08:34 UTC, mcarmona99 commented on wodles/gcloud/tests/test_integration.py
> +    msg = integration.format_msg(json.dumps(test_message))
Why does test_message need to be dumped to JSON?

2022-05-30 08:34 UTC, mcarmona99 commented on wodles/gcloud/tests/test_integration.py
> +])
`expected_exception` needed?

2022-05-30 08:34 UTC, mcarmona99 commented on wodles/gcloud/tests/test_integration.py
> +    (OSError, exceptions.WazuhIntegrationInternalError, 3)
No need to parametrize

Edit: if you leave the parameters for future new values, also leave docstring

2022-05-30 13:44 UTC, CarlosRS9 commented on wodles/gcloud/gcloud.py
> +        logging_func('An exception happened while running the wodle: {gcloud_exception}', exc_info=log_level == 1)
You are right, after the change this is no longer an f-string. This has been fixed.

2022-05-30 13:47 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_bucket.py
>  from buckets.bucket import WazuhGCloudBucket
These imports are already optimized. Is there anything that is missing or needs to be changed?

2022-05-30 13:48 UTC, CarlosRS9 commented on wodles/gcloud/tests/data/access_logs.log
> +Field_1_value,Field 2_value,Field-3_value,Field4_value
done

2022-05-30 13:49 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_bucket.py
> +test_table_name = "test_bucket"
done

2022-05-30 13:54 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_bucket.py
> +])
No, they are no longer needed. Those were remnants from the previous tests. We will remove them.

2022-05-30 14:01 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_bucket.py
> +])
The bucket name is required for the test, but this can easily be replaced by a variable in a similar way to how we work with TEST_TABLE_NAME.

2022-05-30 14:11 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_bucket.py
> +@pytest.mark.parametrize('project_id, prefix, processed_files', [("project_123", "", ["test_blob_1", "test_blob_2"])])
You are right again. Fixed.

2022-05-30 14:11 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_bucket.py
> +def test_WazuhGCloudBucket_check_permissions(mock_client, google_exception, expected_exception, errcode):
This parameter is no longer needed

2022-05-30 14:20 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_bucket.py
> +    bucket = WazuhGCloudBucket(**get_wodle_config(delete_file=delete_file))
done

2022-05-30 15:11 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_integration.py
> +    assert msg_json['gcp'] == test_message
suggestion accepted

2022-05-30 15:16 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_integration.py
> +    mock_socket.return_value.send.assert_called()
agreed

2022-05-30 15:19 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_subscriber.py
> +@pytest.mark.parametrize('max_messages', [100])
fixed

2022-05-30 15:20 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_tools.py
> +@pytest.mark.parametrize('args', [['main', '--integration_type', 'any', '--credentials_file', 'any']])
fixed

2022-05-30 15:31 UTC, CarlosRS9 commented on wodles/gcloud/tests/test_bucket.py
>  from buckets.bucket import WazuhGCloudBucket
done

2022-06-21 07:37 UTC, mcarmona99 approved these changes
LGTM

2022-07-05 08:10 UTC, davidjiglesias approved these changes

2022-07-05 08:10 UTC, merged