Adding new features to runtest.py
wazuh/wazuh pull request #13597
Opened 2022-05-26 22:25 UTC by fabamatic

|Related issue|
|---|
|#13555|

## Description

New features added to runtest.py:
* Windows event channel testing
* Better reporting capabilities

## Tests

|Component |  Tested  |  Total   | Coverage |
| -------- | -------- | -------- | -------- |
|  Rules   |   1171   |   4247   |  27.57%  |
| Decoders |    75    |   165    |  45.45%  |

|          File           |  Passed  |  Failed  |  Status  |
|        --------         | -------- | -------- | -------- |
|./tests/proftpd.ini      |    7     |    0     |   ✅    |
|./tests/exim.ini         |    7     |    0     |   ✅    |
|./tests/squid_rules.ini  |    2     |    0     |   ✅    |
|./tests/sysmon_eid_3.ini |    10    |    0     |   ✅    |
|./tests/checkpoint_smart1.ini|    18    |    0     |   ✅    |
|./tests/iptables.ini     |    8     |    0     |   ✅    |
|./tests/sysmon_eid_10.ini|    4     |    0     |   ✅    |
|./tests/SonicWall.ini    |    11    |    0     |   ✅    |
|./tests/panda_paps.ini   |    8     |    0     |   ✅    |
|./tests/fortiauth.ini    |    4     |    0     |   ✅    |
|./tests/openldap.ini     |    9     |    0     |   ✅    |
|./tests/f5_big_ip.ini    |    48    |    0     |   ✅    |
|./tests/sophos.ini       |    8     |    0     |   ✅    |
|./tests/opensmtpd.ini    |    7     |    0     |   ✅    |
|./tests/netscreen.ini    |    4     |    0     |   ✅    |
|./tests/rsh.ini          |    2     |    0     |   ✅    |
|./tests/arbor.ini        |    2     |    0     |   ✅    |
|./tests/web_rules.ini    |    10    |    0     |   ✅    |
|./tests/exchange.ini     |    2     |    0     |   ✅    |
|./tests/vuln_detector.ini|    2     |    0     |   ✅    |
|./tests/sysmon_eid_7.ini |    6     |    0     |   ✅    |
|./tests/cpanel.ini       |    7     |    0     |   ✅    |
|./tests/apparmor.ini     |    5     |    0     |   ✅    |
|./tests/pam.ini          |    5     |    0     |   ✅    |
|./tests/apache.ini       |    12    |    0     |   ✅    |
|./tests/fireeye.ini      |    3     |    0     |   ✅    |
|./tests/sysmon.ini       |    3     |    0     |   ✅    |
|./tests/dovecot.ini      |    15    |    0     |   ✅    |
|./tests/nginx.ini        |    12    |    0     |   ✅    |
|./tests/nextcloud.ini    |    8     |    0     |   ✅    |
|./tests/unbound.ini      |    0     |    0     |   ✅    |
|./tests/paloalto.ini     |    16    |    0     |   ✅    |
|./tests/sysmon_eid_13.ini|    7     |    0     |   ✅    |
|./tests/ossec.ini        |    5     |    0     |   ✅    |
|./tests/cisco_ftd.ini    |    42    |    0     |   ✅    |
|./tests/sysmon_eid_1.ini |    59    |    0     |   ✅    |
|./tests/github.ini       |   324    |    0     |   ✅    |
|./tests/fortimail.ini    |    6     |    0     |   ✅    |
|./tests/named.ini        |    5     |    0     |   ✅    |
|./tests/powershell.ini   |    32    |    0     |   ✅    |
|./tests/openvpn_ldap.ini |    2     |    0     |   ✅    |
|./tests/sysmon_eid_8.ini |    4     |    0     |   ✅    |
|./tests/cloudflare-waf.ini|    13    |    0     |   ✅    |
|./tests/huawei_usg.ini   |    3     |    0     |   ✅    |
|./tests/eset.ini         |    8     |    0     |   ✅    |
|./tests/gcp.ini          |    31    |    0     |   ✅    |
|./tests/samba.ini        |    4     |    0     |   ✅    |
|./tests/pfsense.ini      |    2     |    0     |   ✅    |
|./tests/cisco_asa.ini    |    88    |    0     |   ✅    |
|./tests/systemd.ini      |    2     |    0     |   ✅    |
|./tests/web_appsec.ini   |    31    |    0     |   ✅    |
|./tests/sysmon_eid_11.ini|    28    |    0     |   ✅    |
|./tests/cisco_ios.ini    |    17    |    0     |   ✅    |
|./tests/pix.ini          |    22    |    0     |   ✅    |
|./tests/php.ini          |    2     |    0     |   ✅    |
|./tests/office365.ini    |   128    |    0     |   ✅    |
|./tests/fortigate.ini    |    45    |    0     |   ✅    |
|./tests/audit_scp.ini    |    8     |    0     |   ✅    |
|./tests/win_application.ini|    0     |    0     |   ✅    |
|./tests/fortiddos.ini    |    1     |    0     |   ✅    |
|./tests/cimserver.ini    |    2     |    0     |   ✅    |
|./tests/freepbx.ini      |    6     |    0     |   ✅    |
|./tests/sshd.ini         |    47    |    0     |   ✅    |
|./tests/win_event_channel.ini|    8     |    0     |   ✅    |
|./tests/gitlab.ini       |    27    |    0     |   ✅    |
|./tests/glpi.ini         |    3     |    0     |   ✅    |
|./tests/api.ini          |    20    |    0     |   ✅    |
|./tests/dropbear.ini     |    3     |    0     |   ✅    |
|./tests/firewalld.ini    |    2     |    0     |   ✅    |
|./tests/mailscanner.ini  |    1     |    0     |   ✅    |
|./tests/owlh.ini         |    4     |    0     |   ✅    |
|./tests/sysmon_eid_20.ini|    2     |    0     |   ✅    |
|./tests/oscap.ini        |    32    |    0     |   ✅    |
|./tests/mcafee_epo.ini   |    1     |    0     |   ✅    |
|./tests/doas.ini         |    4     |    0     |   ✅    |
|./tests/junos.ini        |    3     |    0     |   ✅    |
|./tests/sudo.ini         |    8     |    0     |   ✅    |
|./tests/syslog.ini       |    6     |    0     |   ✅    |
|./tests/sophos_fw.ini    |    10    |    0     |   ✅    |
|./tests/vsftpd.ini       |    4     |    0     |   ✅    |
|./tests/postfix.ini      |    2     |    0     |   ✅    |
|./tests/modsecurity.ini  |    6     |    0     |   ✅    |
|./tests/su.ini           |    5     |    0     |   ✅    |
|./tests/kernel_usb.ini   |    6     |    0     |   ✅    |
|./tests/aws_s3_access.ini|    10    |    0     |   ✅    |
|./tests/auditd.ini       |    31    |    0     |   ✅    |

2022-06-08 14:11 UTC, jmv74211 requested changes

2022-06-08 14:11 UTC, jmv74211 commented on ruleset/testing/runtests.py
>                  print("")
?

2022-06-08 14:11 UTC, jmv74211 commented on ruleset/testing/runtests.py
> +    print("")
?

2022-06-08 14:11 UTC, jmv74211 commented on ruleset/testing/runtests.py
> +            disable_win_eventlog_tests()
Bad indentation

2022-06-08 14:13 UTC, jmv74211 reviewed
Review of the format and structure of the code.

Main problems encountered:

- `snake_case` format is not used in `coverage.py`
- Inconsistency of styles between different files
- Sometimes descriptive variable names are not used.
- Undocumented code and methods. Difficult to maintain code.
- Linter reports many formatting errors:
  - `coverage.py`

    ```
    coverage.py:16:1: E302 expected 2 blank lines, found 1
    coverage.py:39:1: E302 expected 2 blank lines, found 1
    coverage.py:69:41: E231 missing whitespace after ','
    coverage.py:70:32: E201 whitespace after '('
    coverage.py:70:99: E202 whitespace before ')'
    coverage.py:74:1: E302 expected 2 blank lines, found 1
    coverage.py:105:44: E231 missing whitespace after ','
    coverage.py:135:1: E305 expected 2 blank lines after class or function definition, found 1
    coverage.py:147:1: W391 blank line at end of file
    ```

  - `runtests.py`

    ```
    runtests.py:39:5: E722 do not use bare 'except'
    runtests.py:51:1: E302 expected 2 blank lines, found 1
    runtests.py:58:80: E231 missing whitespace after ','
    runtests.py:59:39: E203 whitespace before ','
    runtests.py:63:83: E231 missing whitespace after ','
    runtests.py:64:39: E203 whitespace before ','
    runtests.py:66:1: E302 expected 2 blank lines, found 1
    runtests.py:72:80: E231 missing whitespace after ','
    runtests.py:77:83: E231 missing whitespace after ','
    runtests.py:80:1: E302 expected 2 blank lines, found 1
    runtests.py:84:1: E302 expected 2 blank lines, found 1
    runtests.py:88:1: E302 expected 2 blank lines, found 1
    runtests.py:93:41: E231 missing whitespace after ','
    runtests.py:97:1: E302 expected 2 blank lines, found 1
    runtests.py:101:41: E231 missing whitespace after ','
    runtests.py:103:39: E231 missing whitespace after ','
    runtests.py:107:1: E302 expected 2 blank lines, found 1
    runtests.py:108:36: E203 whitespace before ':'
    runtests.py:109:21: E127 continuation line over-indented for visual indent
    runtests.py:109:36: E203 whitespace before ':'
    runtests.py:110:39: E203 whitespace before ':'
    runtests.py:111:30: E203 whitespace before ':'
    runtests.py:112:32: E203 whitespace before ':'
    runtests.py:120:91: E231 missing whitespace after ','
    runtests.py:123:63: E231 missing whitespace after ','
    runtests.py:124:121: E501 line too long (174 > 120 characters)
    runtests.py:124:166: E231 missing whitespace after ','
    runtests.py:135:1: E302 expected 2 blank lines, found 1
    runtests.py:193:56: E231 missing whitespace after ':'
    runtests.py:193:68: E231 missing whitespace after ':'
    runtests.py:212:97: E231 missing whitespace after ','
    runtests.py:212:119: E225 missing whitespace around operator
    runtests.py:212:121: E501 line too long (121 > 120 characters)
    runtests.py:236:121: E501 line too long (155 > 120 characters)
    runtests.py:238:121: E501 line too long (136 > 120 characters)
    runtests.py:240:121: E501 line too long (151 > 120 characters)
    runtests.py:244:34: E225 missing whitespace around operator
    runtests.py:245:41: E231 missing whitespace after ','
    runtests.py:245:52: E231 missing whitespace after ','
    runtests.py:246:47: E231 missing whitespace after ','
    runtests.py:246:56: E231 missing whitespace after ','
    runtests.py:256:1: E305 expected 2 blank lines after class or function definition, found 1
    runtests.py:265:121: E501 line too long (129 > 120 characters)
    runtests.py:291:13: E117 over-indented
    ```

2022-06-08 16:21 UTC, fabamatic commented on ruleset/testing/coverage.py
> +    parser.add_argument("tests_path", help="path were ini test files are located")
Will remove main method as it's not being used by any scripts

2022-06-08 16:26 UTC, fabamatic commented on ruleset/testing/runtests.py
> +from coverage import getParentDecoderNames
Done

2022-06-08 16:54 UTC, fabamatic commented on ruleset/testing/runtests.py
> +            failed_test["description"] = ""
done

2022-06-08 16:59 UTC, fabamatic commented on ruleset/testing/runtests.py
> +        did_pass = "failed"
changed variable name to test_status

2022-06-08 17:00 UTC, fabamatic commented on ruleset/testing/runtests.py
> +                self._execution_data[aFile] = {"passed":0, "failed":0}
Legacy varable name, should be something like "hopefully_a_ini_file", will change to "a_ini_file"

2022-06-08 17:07 UTC, fabamatic commented on ruleset/testing/runtests.py
> +            disable_win_eventlog_tests()
Corrected

2022-06-08 17:07 UTC, fabamatic commented on ruleset/testing/runtests.py
> +    print("")
change to print("\n")

2022-06-09 16:05 UTC, jmv74211 approved these changes

2022-06-09 17:24 UTC, 72nomada approved these changes

2022-06-17 07:48 UTC, merged