Show package installation time when DateInstall field doesn't appear …
wazuh/wazuh pull request #13672
Opened 2022-06-02 13:36 UTC by HanesSciarrone

…on the Regisrty.

|Related issue|
|---|
|#10703|

## Description

This PR aims to get the packages installation time when the packages registry queried doesn't have the DataInstall field. Currently 

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [x] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [x] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-06-02 17:43 UTC, jnasselle commented on src/shared_modules/utils/registryHelper.h
> +                FILETIME lastWirteTime { };
Fix typo 
```suggestion
                FILETIME lastModificationTime { };
```

2022-06-02 17:43 UTC, jnasselle commented on src/shared_modules/utils/registryHelper.h
> +                        value << std::setfill('0') << std::setw(2) << userTime.wSecond;
There's no WAPI function to do this?

2022-06-09 13:12 UTC, jnasselle commented on src/shared_modules/utils/windowsHelper.h
> +    static std::string buildTimestamp(const unsigned long long time)
What if we change `unsigned long long` to `ULONGLONG`?

2022-06-09 13:16 UTC, jnasselle commented on src/shared_modules/utils/registryHelper.h
> +                    fileTime = fileTime << sizeof(lastModificationTime.dwHighDateTime)*8 | lastModificationTime.dwLowDateTime;
Change approach to the one suggested Microsoft https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-filetime
```
It is not recommended that you add and subtract values from the FILETIME structure to obtain relative times. Instead, you should copy the low- and high-order parts of the file time to a [ULARGE_INTEGER](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-ularge_integer-r1) structure, perform 64-bit arithmetic on the QuadPart member, and copy the LowPart and HighPart members into the FILETIME structure.
```
For example, this is used here 
https://github.com/wazuh/wazuh/blob/3d9e9ac429d439d48506e684eadebd8909727413/src/data_provider/src/sysInfoWin.cpp#L140-L155

2022-06-13 13:02 UTC, jnasselle submitted a review, later dismissed
GJ @HanesSciarrone !

Please, create an issue to standardize time specs like
- TIme format
- Timezone used (UTC proposed)

2022-06-14 01:31 UTC, Dwordcito requested changes

2022-06-14 01:31 UTC, Dwordcito commented on src/shared_modules/utils/windowsHelper.h
> +        return ret;
```suggestion
        char formatString[20] = {0};

        std::strftime(formatString, sizeof(formatString), "%Y/%m/%d %H:%M:%S", std::localtime(&epochTIme));
        return formatString;
```

2022-06-14 01:31 UTC, Dwordcito commented on src/shared_modules/utils/registryHelper.h
> +                std::string ret { };
std::string don't need initialization, the constructor during instantiation does.

2022-06-15 13:18 UTC, HanesSciarrone commented
> GJ @HanesSciarrone !
> 
> Please, create an issue to standardize time specs like
> 
>     * TIme format
> 
>     * Timezone used (UTC proposed)

@jnasselle I created the issue #13884

2022-06-24 02:12 UTC, jnasselle approved these changes

2022-06-29 06:03 UTC, Dwordcito approved these changes

2022-06-29 13:14 UTC, jnasselle submitted a review, later dismissed

2022-08-04 22:23 UTC, MiguelazoDS commented
# Update 04/08/22

## Running tests after rebase 

![image](https://user-images.githubusercontent.com/13010397/182946097-40d553b4-8963-49c9-8b2b-dec63442c022.png)

## Behavior Windows 11 where the language was changed with 7zip and Telegram desktop

![image](https://user-images.githubusercontent.com/13010397/182948135-61af38ea-e68a-4484-b00c-0b421b1aca81.png)

Restoring language to English

![image](https://user-images.githubusercontent.com/13010397/182948644-8ec997e5-5d1b-4a25-8905-0a58af4207a2.png)

Multiple packages in Spanish appear without installation date, also Telegram Desktop application from the Microsoft store no longer displays the installation time.

![image](https://user-images.githubusercontent.com/13010397/182949285-eeece74f-3bf4-4211-adf6-b075c3f9ce1a.png)

## Behaviour on fresh Windows 10 installation with 7zip and Telegram desktop

![image](https://user-images.githubusercontent.com/13010397/182948182-6c992f18-4471-428a-aaa4-f003eec31cc4.png)

There's no package with null or empty installation time information and the Telegram desktop displays correctly the date 

![image](https://user-images.githubusercontent.com/13010397/182949759-c40579c4-b298-4abd-a60e-362f4cbaff30.png)
![image](https://user-images.githubusercontent.com/13010397/182949932-fcef9e53-fd1a-4c3f-b394-70d42390a7dd.png)

2022-08-05 18:53 UTC, closed without merging