Additional Telegram Integrations
wazuh/wazuh pull request #13810
Opened 2022-06-10 08:20 UTC by vncloudsco

In the process we built Telegram Integrations we decided to contribute it to the community. You can refer to it for telegram message notifications

2022-06-16 10:47 UTC, santiagz commented
agree with the author, this feature would be very useful

2022-07-19 07:28 UTC, chemamartinez commented on integrations/telegram
> +BLACK_LIST= ["sca","vulnerability-detector"]
This `BLACK_LIST` and `BLACK_RULE` should not be added to the final version of the script. This is customization for a particular use case but in the default one, it should be tuned with the available filters in the integrations defined [here](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/integration.html#options).

2022-07-19 07:35 UTC, chemamartinez commented on integrations/telegram
> +text = """*Wazuh-OSSEC: (%s) %s -> %s*
Please replace `Wazuh-OSSEC` with just `Wazuh` in the alert title.

2022-07-19 07:55 UTC, vncloudsco commented
@chemamartinez  Thank you for your review I have changed the information. Please review again!

2022-07-19 08:03 UTC, vncloudsco commented
I update more pictures of this script when it is actually run, i am using it with naxsi firewall log
![image](https://user-images.githubusercontent.com/41409442/179699039-7bda3ae1-4a88-4b72-aed1-401786deba4a.png)

2022-07-20 11:59 UTC, chemamartinez commented
Hi @vncloudsco,

Thanks for the additions. We are still missing to include the installation of the script along with the other ones deployed. This should be done here:
https://github.com/wazuh/wazuh/blob/master/src/init/inst-functions.sh#L994-L997

Regards.

2022-07-21 02:43 UTC, vncloudsco commented
Hi@chemamartinez 
I have resolved all of your suggestions!

2022-08-09 11:28 UTC, chemamartinez requested changes

2022-08-09 11:28 UTC, chemamartinez commented on src/os_integrator/integrator.c
> +                merror("Unable to enable integration for: '%s'. Missing ID chat.", integrator_config[s]->name);
```suggestion
                merror("Unable to enable integration for: '%s'. Missing Telegram Chat ID.", integrator_config[s]->name);
```

2022-08-09 11:39 UTC, chemamartinez commented
Hi @vncloudsco,

Thank you again for your contribution and your help.

I have been testing the integration more in-depth and I have noticed new changes that are required to make it work.

### Add a generic wrapper for the integration script

As you can see in these lines https://github.com/vncloudsco/wazuh/blob/master/src/init/inst-functions.sh#L1115-L1117, in `src/init/inst-functions.sh`, it is needed to add a new line to create a wrapper for the Telegram script. You can add a line as follows:
```
${INSTALL} -m 0750 -o root -g ${WAZUH_GROUP} ../framework/wrappers/generic_wrapper.sh ${INSTALLD
IR}/integrations/telegram
```

### Several changes are required in the Telegram script

Once reviewed the script deeper and tested it, some changes are required:
- Cleaning the script of residual comments
- `/var/ossec` is hardcoded as the installation path, which is not allowed since the manager can be installed in a different location
- Some imports are not available by default, so we can avoid using some modules to simplify the script and the needed dependencies. Here you can see some errors related to that dependencies:
```
2022/08/09 09:29:58 wazuh-integratord: ERROR: Unable to run integration for telegram -> integrations
2022/08/09 09:29:58 wazuh-integratord: ERROR: While running telegram -> integrations. Output: ModuleNotFoundError: No module named 'urllib2'
2022/08/09 10:47:48 wazuh-integratord: ERROR: While running telegram -> integrations. Output: NameError: name 'reload' is not defined
2022/08/09 10:49:14 wazuh-integratord: ERROR: While running telegram -> integrations. Output: AttributeError: module 'sys' has no attribute 'setdefaultencoding'
```
- The script doesn't follow the Wazuh standard in several ways.

To solve all these requirements, I have developed a new script that solve them. Here you can see how it looks like:

```python
#!/usr/bin/env python
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

import sys
import json
import requests
import os
import time

try:
    import requests
    from requests.auth import HTTPBasicAuth
except Exception as e:
    print("No module 'requests' found. Install: pip install requests")
    sys.exit(1)


# ossec.conf configuration:
#  <integration>
#      <name>telegram</name>
#      <hook_url>{ Chat ID of Telegram Group, Channel or Personal}</hook_url>
#      <api_key>{Token Bot Telegram}</api_key>
#      <alert_format>json</alert_format>
#  </integration>

# Global vars

debug_enabled = False
pwd = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
json_alert = {}
now = time.strftime("%a %b %d %H:%M:%S %Z %Y")

# Set paths
log_file = '{0}/logs/integrations.log'.format(pwd)

def main(args):
    debug("# Starting")

    # Read args
    alert_file_location = args[1]
    token = args[2]
    chat_id = args[3]

    debug("# Telegram token")
    debug(token)

    debug("# Telegram Chat ID")
    debug(chat_id)

    debug("# File location")
    debug(alert_file_location)

    # Load alert. Parse JSON object.
    with open(alert_file_location) as alert_file:
        json_alert = json.load(alert_file)
    debug("# Processing alert")
    debug(json_alert)

    debug("# Generating message")
    msg = generate_msg(json_alert, chat_id)
    debug(msg)

    debug("# Sending message")
    send_msg(token, msg)


def debug(msg):
    if debug_enabled:
        msg = "{0}: {1}\n".format(now, msg)
        print(msg)
        f = open(log_file, "a")
        f.write(msg)
        f.close()


def generate_msg(alert_json, chat_id):
    # Get alert information
    title = alert_json['rule']['description'] if 'description' in alert_json['rule'] else ''
    description = alert_json['full_log'] if 'full_log' in alert_json else ''
    description.replace("\\n", "\n")
    alert_level = alert_json['rule']['level'] if 'level' in alert_json['rule'] else ''
    groups = ', '.join(alert_json['rule']['groups']) if 'groups' in alert_json['rule'] else ''
    rule_id = alert_json['rule']['id'] if 'rule' in alert_json else ''
    agent_name = alert_json['agent']['name'] if 'name' in alert_json['agent'] else ''
    agent_id = alert_json['agent']['id'] if 'id' in alert_json['agent'] else ''

    # Format message with markdown
    msg_content = f'*{title}*\n\n'
    msg_content += f'_{description}_\n'
    msg_content += f'*Groups:* {groups}\n' if len(groups) > 0 else ''
    msg_content += f'*Rule:* {rule_id} (Level {alert_level})\n'
    msg_content += f'*Agent:* {agent_name} ({agent_id})\n' if len(agent_name) > 0 else ''

    msg_data = {}
    msg_data['chat_id'] = chat_id
    msg_data['text'] = msg_content
    msg_data['parse_mode'] = 'markdown'

    return json.dumps(msg_data)


def send_msg(token, msg):
    url = "https://api.telegram.org/bot" + token + "/sendMessage"
    headers = {
        'Content-Type': 'application/json',
    }
    try:
        res = requests.post(url, headers=headers, data=msg)
        debug(res)
    except Exception as e:
        print( 'Exception >> ' + type(e).__name__ )
        return 'Internal error sending msg to Telegram.'


if __name__ == "__main__":
    try:
        # Read arguments
        bad_arguments = False
        if len(sys.argv) >= 4:
            msg = '{0} {1} {2} {3} {4}'.format(
                now,
                sys.argv[1],
                sys.argv[2],
                sys.argv[3],
                sys.argv[4] if len(sys.argv) > 4 else '',
            )
            debug_enabled = (len(sys.argv) > 4 and sys.argv[4] == 'debug')
        else:
            msg = '{0} Wrong arguments'.format(now)
            bad_arguments = True

        # Logging the call
        f = open(log_file, 'a')
        f.write(msg + '\n')
        f.close()

        if bad_arguments:
            debug("# Exiting: Bad arguments.")
            sys.exit(1)

        # Main function
        main(sys.argv)

    except Exception as e:
        debug(str(e))
        raise
```

I have also tested it with success, now the alerts have the following appearance:
<img width="432" alt="image" src="https://user-images.githubusercontent.com/29475387/183638005-b10e09f2-0076-47e1-add7-072bdff086e7.png">

Regarding the mentioned above, could you please replace the uploaded script with this new one?

### A small correction in an error message

I have add a suggestion here: https://github.com/wazuh/wazuh/pull/13810#discussion_r941223498

Once solved all these suggestions, the pull request should be ready to be merged.

Thank you again!

2022-08-16 05:06 UTC, vncloudsco commented
Dear: @chemamartinez 
I have updated the source code, please check again, I agree that the source code will only run with python 3.x

2022-08-16 11:27 UTC, chemamartinez approved these changes
LGTM!

2022-08-16 11:29 UTC, chemamartinez commented
Hi again @vncloudsco,

Thanks for adding the requested changes. It is now approved by my side.

We are still missing the review of @davidjiglesias or anyone from the @wazuh/framework team who are our "python" experts.

Once it is approved by them, it will be merged.

Thanks again for your contribution and the help during the process!

2024-01-17 10:49 UTC, vncloudsco commented
who anyone considered this feature? @chemamartinez Can it be integrated?

2024-01-17 14:31 UTC, chemamartinez commented
cc: @vikman90 @davidjiglesias

2025-02-19 19:17 UTC, closed without merging