Fix Apple Silicon architecture retrieving
wazuh/wazuh pull request #13835
Opened 2022-06-11 03:39 UTC by jnasselle

|Related issue|
|---|
| #12341 |

## Description

This PR aims to detect when macOS Wazuh agent is running on Apple Silicon devices, showing them with proper architecture (arm64)

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-06-13 13:42 UTC, HanesSciarrone commented on src/data_provider/src/sysInfoMac.cpp
> +        retVal = 1 == isTranslated;
It would be better to use a `consexpr` to know the meaning of this number.

2022-06-13 20:41 UTC, Dwordcito requested changes

2022-06-13 20:41 UTC, Dwordcito commented on src/data_provider/src/sysInfoMac.cpp
> +        }
```suggestion
        if (errno != ENOENT)
        {
            throw std::system_error
            {
                ret,
                std::system_category(),
                "Error reading rosetta status."
            };
        }
```

2022-06-13 20:41 UTC, Dwordcito commented on src/data_provider/src/sysInfoMac.cpp
> +    size_t len{sizeof(isTranslated)};
```suggestion
    auto retVal {false};
    auto isTranslated{0};
    auto len{sizeof(isTranslated)};
```

2022-06-13 20:41 UTC, Dwordcito commented on src/data_provider/src/sysInfoMac.cpp
> +    const auto ret{sysctlbyname("sysctl.proc_translated", &isTranslated, &len, NULL, 0)};
add comment for `sysctl.proc_translated`  definition

2022-06-13 20:41 UTC, Dwordcito commented on src/data_provider/src/sysInfoMac.cpp
> +    const auto ret{sysctlbyname("sysctl.proc_translated", &isTranslated, &len, NULL, 0)};
use another name for ret, to be more descriptive compared to retVal

2022-06-15 13:40 UTC, HanesSciarrone submitted a review, later dismissed

2022-06-16 17:47 UTC, Dwordcito approved these changes

2022-08-26 14:37 UTC, jmv74211 commented
## QA review

- **Type**: Manual testing.
- **Status**: Pending to approve  🟡  
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3009
- **Comments**: Everything seems to work properly, but this PR has red Jenkins checks. It will be approved when all checks are passed.

2022-09-12 12:33 UTC, Dwordcito approved these changes

2022-10-14 04:17 UTC, Dwordcito approved these changes

2022-10-17 13:49 UTC, merged