13756 create SCA for RHEL9
wazuh/wazuh pull request #13843
Opened 2022-06-13 08:40 UTC by 72nomada

|Related issue|
|---|
|close #13756|

- [ ] Create SCA RHEL9 file based on CIS RHEL8 v2.0.0 
- [ ] SCA checks tested and verified
- [ ] SCA coverages updated
- [ ] Update the templates on etc/templates/config/ for the default SCA file on RHEL family 
- [ ] Create the template file for RHEL9 and update the root checks for the agent and the manager
- [ ] Issue for Wazuh-packages team to create SPECS as needed.

2022-06-16 13:59 UTC, thetredev commented
I tried to load https://github.com/wazuh/wazuh/blob/f1e4579f7c074ffa1e0b70480bef1464ac7cfc7f/ruleset/sca/rhel/9/cis_rhel9_linux.yml on `AlmaLinux 9.0` and it failed, because the ID `28062` existed twice with the same checks. ID `28115` had an empty entry (lone `-`) and ID `28117` existed twice, but they were two completely different checks. I incremented them from the second `28117` onwards. This is the diff:
```diff
--- cis_rhel9_linux.yml	2022-06-16 15:53:12.896754043 +0200
+++ cis_rhel9_linux_updated.yml	2022-06-16 15:53:35.656925153 +0200
@@ -28,6 +28,7 @@
     - "f:/etc/redhat-release -> r:^Oracle && r:release 9"
     - "f:/etc/redhat-release -> r:^Better && r:release 9"
     - "f:/etc/redhat-release -> r:^OpenVZ && r:release 9"
+    - "f:/etc/redhat-release -> r:^AlmaLinux && r:release 9.0"
 
 variables:
   $sshd_file: /etc/ssh/sshd_config
@@ -1197,22 +1198,6 @@
     rules:
       - "c:rpm -q chrony -> r:^chrony-"
 
-  # 2.1.2 Ensure chrony is configured (Automated)
-  - id: 28062
-    title: "Ensure chrony is configured"
-    description: "chrony is a daemon which implements the Network Time Protocol (NTP) and is designed to synchronize system clocks across a variety of systems and use a source that is highly accurate. More information on chrony can be found at http://chrony.tuxfamily.org/. chrony can be configured to be a client and/or a server."
-    rationale: "If chrony is in use on the system proper configuration is vital to ensuring time synchronization is working properly."
-    remediation: "On physical systems or virtual systems where host based time synchronization is not available install chrony: # dnf install chrony  On virtual systems where host based time synchronization is available consult your virtualization software documentation and verify that host based synchronization is in use."
-    compliance:
-      - cis: ["2.2.2.1"]
-      - cis_csc: ["6.1"]
-      - pci_dss: ["10.4"]
-      - nist_800_53: ["AU.8"]
-      - tsc: ["CC6.1", "CC6.8", "CC7.2", "CC7.3", "CC7.4"]
-    condition: all
-    rules:
-      - "c:rpm -q chrony -> r:^chrony-"
-
   ###############################################
   # 2.2 Remove Legacy Services
   ###############################################
@@ -2219,7 +2204,6 @@
       - "c:rpm -q nftables -> r:^package nftables is not installed"
       - "c:rpm -q iptables -> r:iptables-"
       - "c:rpm -q iptables-services -> r:iptables-services-"
-      -
 
   ############################################################
   # 3.4.3.2 Configure IPv4 iptables.
@@ -2269,7 +2253,7 @@
   ############################################################
 
   # 3.4.3.3.1 Ensure IPv6 loopback traffic is configured.
-  - id: 28117
+  - id: 28118
     title: "Ensure IPv6 loopback traffic is configured."
     description: "Configure the loopback interface to accept traffic. Configure all other interfaces to deny traffic tothe loopback network (::1)."
     rationale: "Loopback traffic is generated between processes on machine and is typically critical to operation of the system. The loopback interface is the only place that loopback network (::1) traffic should be seen, all other interfaces should ignore traffic on this network as an anti-spoofing measure"
@@ -2289,7 +2273,7 @@
   # 3.4.3.3.3 Ensure ip6tables firewall rules exist for all open ports - Not implemented, requires manual operation.
 
   # 3.4.3.3.4 Ensure ip6tables default deny firewall policy.
-  - id: 28118
+  - id: 28119
     title: "Ensure ip6tables default deny firewall policy."
     description: "A default deny all policy on connections ensures that any unconfigured network usage will be rejected."
     rationale: "With a default accept policy the firewall will accept any packet that is not configured to be denied. It is easier to white list acceptable usage than to black list unacceptable usage."
@@ -2308,7 +2292,7 @@
   # 3.4.3.3.5 Ensure ip6tables rules are saved - Not implemented, requires manual operation.
 
   # 3.4.3.3.6 Ensure ip6tables is enabled and running
-  - id: 28119
+  - id: 28120
     title: "Ensure ip6tables is enabled and running."
     description: "ip6tables.service is a utility for configuring and maintaining ip6tables."
     rationale: "ip6tables.service will load the iptables rules saved in the file /etc/sysconfig/ip6tables at boot, otherwise the ip6tables rules will be cleared during a re-boot of the system."
@@ -2334,7 +2318,7 @@
   ############################################################
 
   # 4.1.1.1 Ensure auditd is installed (Automated).
-  - id: 28120
+  - id: 28121
     title: "Ensure auditd is installed."
     description: "auditd is the userspace component to the Linux Auditing System. It's responsible for writing audit records to the disk."
     rationale: "The capturing of system events provides system administrators with information to allow them to determine if unauthorized access to their system is occurring."
@@ -2349,7 +2333,7 @@
       - "c:rpm -q audit -> r:^audit-"
 
   # 4.1.1.2 Ensure auditd service is enabled and running.
-  - id: 28121
+  - id: 28122
     title: "Ensure auditd service is enabled and running."
     description: "Turn on the auditd daemon to record system events."
     rationale: "The capturing of system events provides system administrators with information to allow them to determine if unauthorized access to their system is occurring."
@@ -2365,7 +2349,7 @@
       - "c:systemctl status auditd -> r:active && r:running"
 
   # 4.1.1.3 Ensure auditing for processes that start prior to auditd is enabled.
-  - id: 28122
+  - id: 28123
     title: "Ensure auditing for processes that start prior to auditd is enabled."
     description: "Configure grub so that processes that are capable of being audited can be audited even if they start up prior to auditd startup."
     rationale: "Audit events need to be captured on processes that start up prior to auditd, so that potential malicious activity cannot go undetected. Note: This recommendation is designed around the grub2 bootloader, if LILO or another bootloader is in use in your environment enact equivalent settings."
@@ -2388,7 +2372,7 @@
   ############################################################
 
   # 4.1.2.1 Ensure audit log storage size is configured.
-  - id: 28123
+  - id: 28124
     title: "Ensure audit log storage size is configured."
     description: "Configure the maximum size of the audit log file. Once the log reaches the maximum size, it will be rotated and a new log file will be started."
     rationale: "It is important that an appropriate size is determined for log files so that they do not impact the system and audit data is not lost."
@@ -2402,7 +2386,7 @@
       - 'f:/etc/audit/auditd.conf -> r:^max_log_file\s*=\s*\d+'
 
   # 4.1.2.2 Ensure audit logs are not automatically deleted.
-  - id: 28124
+  - id: 28125
     title: "Ensure audit logs are not automatically deleted."
     description: "The max_log_file_action setting determines how to handle the audit log file reaching the max file size. A value of keep_logs will rotate the logs but never delete old logs."
     rationale: "In high security contexts, the benefits of maintaining a long audit history exceed the cost of storing the audit history."
@@ -2416,7 +2400,7 @@
       - 'f:/etc/audit/auditd.conf -> r:^\s*max_log_file_action\s*=\s*keep_logs'
 
   # 4.1.2.3 Ensure system is disabled when audit logs are full.
-  - id: 28125
+  - id: 28126
     title: "Ensure system is disabled when audit logs are full."
     description: "The auditd daemon can be configured to halt the system when the audit logs are full."
     rationale: "In high security contexts, the risk of detecting unauthorized access or nonrepudiation exceeds the benefit of the system's availability."
@@ -2436,7 +2420,7 @@
   #############################################
 
   # 4.1.3.1 Ensure changes to system administration scope (sudoers) is collected (Automated)
-  - id: 28126
+  - id: 28127
     title: [...]

2022-06-22 17:19 UTC, 72nomada commented
@thetredev solved

2022-07-19 10:49 UTC, mcarmona99 requested changes

2022-07-19 10:49 UTC, mcarmona99 commented on etc/templates/config/rhel/9/sca.files
> +rhel/9/cis_rhel9_linux.yml
Add a new line to follow the POSIX standard.

2022-07-19 11:02 UTC, mcarmona99 approved these changes
LGTM

2022-08-05 15:31 UTC, s-ocando approved these changes
LGTM

2022-08-10 07:07 UTC, davidjiglesias approved these changes

2022-08-10 07:07 UTC, merged