Remove standalone references from API integration tests files
wazuh/wazuh pull request #13925
Opened 2022-06-20 16:03 UTC by vicferpoy

|Related issue|
|---|
|closes #13764 |

## Description

This PR removes every reference to the standalone AIT from the code, tools and documentation.

## Tests performed

WIP

Regards,
Víctor

2022-06-27 08:26 UTC, mcarmona99 requested changes
After the changes, `import subprocess` is not necessary in `api/test/integration/env/tools/healthcheck_utils.py` 

Also, in that same file, the `CHECK_CLUSTERD_DAEMON` variable is not needed.

Review `test_agent_GET_endpoints.tavern.yaml`

2022-06-27 08:26 UTC, mcarmona99 commented on api/test/integration/run_tests.py
> +            f'{test.rsplit(".")[0]}' f'{iteration if iteration != 1 else ""}'
This can be written in one line.

2022-06-27 08:26 UTC, mcarmona99 commented on api/test/integration/run_tests.py
> +            print(f"{file}")
No need to use f-string
```suggestion
            print(file)
```

2022-06-27 08:26 UTC, mcarmona99 commented on api/test/integration/run_tests.py
>          with open(os.path.join(RESULTS_FOLDER, test_name), 'w') as f:
Review this block, `pytest_mark` is never used.

The `run_test` function was created to make the code clearer after the addition of the standalone mode. We could consider avoiding this function now. Have a look at the changes done on https://github.com/wazuh/wazuh/pull/12360.

2022-07-04 07:21 UTC, mcarmona99 approved these changes
LGTM

2022-07-12 07:21 UTC, davidjiglesias approved these changes

2022-07-12 07:22 UTC, merged