Added thread_pool setting to FIM DB, to control number of thread in RSync
wazuh/wazuh pull request #14065
Opened 2022-06-28 11:13 UTC by jotacarma90

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/14056|

## Description
Hello team, this PR implements the new setting related to RSync, it is called thread_pool, it indicates the number of threads that RSync can use to perform FIM sync.
We have also modified the unit tests necessary for the correct testing and verification.

## Configuration options

```xml
  <syscheck>
   
   [...]
   
   <synchronization>
      <enabled>yes</enabled>
      <interval>5m</interval>
      <thread_pool>1</thread_pool>
      <max_eps>10</max_eps>
    </synchronization>
  </syscheck>
```

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
- [ ] Source installation
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
- Memory tests for Windows
  - [ ] Scan-build report

- [ ] Configuration on demand reports new parameters

2022-07-25 09:29 UTC, antoniomanuelfr requested changes

2022-07-25 09:29 UTC, antoniomanuelfr commented on src/unit_tests/Testing/Temporary/LastTest.log
> +Start testing: Jul 20 15:02 CEST
Remove the file

2022-07-25 09:29 UTC, antoniomanuelfr commented on src/unit_tests/Testing/Temporary/CTestCostData.txt
> +---
Remove the file

2022-07-27 13:16 UTC, jotacarma90 commented on src/unit_tests/Testing/Temporary/LastTest.log
> +Start testing: Jul 20 15:02 CEST
Done

2022-07-27 13:17 UTC, jotacarma90 commented on src/unit_tests/Testing/Temporary/CTestCostData.txt
> +---
Done

2022-08-05 10:28 UTC, chemamartinez requested changes

2022-08-05 10:28 UTC, chemamartinez commented on src/syscheckd/src/db/include/db.h
> + * @param sync_queue_size Number to define the size of the queue to be synchronized.
`sync_thread_pool` is not in this parameters list

2022-08-05 10:28 UTC, chemamartinez commented on src/unit_tests/Testing/Temporary/CTestCostData.txt
> +---
This file is still uploaded

2022-08-05 10:28 UTC, chemamartinez commented on src/unit_tests/Testing/Temporary/LastTest.log
> +Start testing: Jul 20 15:02 CEST
Remove this file as well

2022-08-08 10:48 UTC, chemamartinez approved these changes

2022-08-08 11:07 UTC, antoniomanuelfr approved these changes

2022-08-10 15:43 UTC, FrancoRivero approved these changes
LGTM

2022-08-11 17:07 UTC, FrancoRivero commented
Should these settings be in the default configuration?

2022-11-15 18:09 UTC, chemamartinez requested changes

2022-11-15 18:09 UTC, chemamartinez commented on src/unit_tests/Testing/Temporary/CTestCostData.txt
> +---
This is still needed to be removed.

2022-11-16 07:37 UTC, merged