Add new API protection settings to block uploading global limits
wazuh/wazuh pull request #14119
Opened 2022-07-04 13:38 UTC by vicferpoy

|Related issue|
|---|
|closes #13572 |

## Description

This PR includes new API settings for the global limits and refactors the former settings block to wrap everything in a more understandable configuration block. 

## Configuration options

The new API configuration block is the following (default values were also modified):

```yaml
# Uploadable Wazuh configuration sections
upload_configuration:
  remote_commands:
    localfile:
      allow: yes
      exceptions: []
    wodle_command:
      allow: yes
       exceptions: []
  limits:
    eps:
      allow: yes
```

## Examples

Trying to upload a configuration with the following block while having the EPS limits not allowed:

```xml
    <limits>
      <eps>
        <maximum>500</maximum>
      </eps>
    </limits>
  </global>
```

Response:

```json
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 1,
    "failed_items": [
      {
        "error": {
          "code": 1127,
          "message": "Forbidden section detected: global > limits > eps",
          "remediation": "To solve this issue, please enable the section in the API settings: https://documentation.wazuh.com/4.5/user-manual/api/configuration.html"
        },
        "id": [
          "master-node"
        ]
      }
    ]
  },
  "message": "Could not update configuration in specified node",
  "error": 1
}
```

## Tests performed
### Unit tests

```
============================================================================================================ test session starts ============================================================================================================
platform linux -- Python 3.9.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/vicferpoy/Desktop/Git/wazuh/framework
plugins: testinfra-5.0.0, metadata-1.11.0, cov-2.12.0, asyncio-0.18.3, aiohttp-0.3.0, html-3.1.1
asyncio: mode=legacy
collected 1968 items                                                                                                                                                                                                                        

scripts/tests/test_agent_groups.py ..............                                                                                                                                                                                     [  0%]
scripts/tests/test_agent_upgrade.py ...............                                                                                                                                                                                   [  1%]
scripts/tests/test_cluster_control.py ......                                                                                                                                                                                          [  1%]
scripts/tests/test_wazuh_clusterd.py .......                                                                                                                                                                                          [  2%]
scripts/tests/test_wazuh_logtest.py ......................                                                                                                                                                                            [  3%]
wazuh/core/cluster/dapi/tests/test_dapi.py ................................                                                                                                                                                           [  4%]
wazuh/core/cluster/tests/test_client.py ................                                                                                                                                                                              [  5%]
wazuh/core/cluster/tests/test_cluster.py ..................................                                                                                                                                                           [  7%]
wazuh/core/cluster/tests/test_common.py .............................................................................                                                                                                                 [ 11%]
wazuh/core/cluster/tests/test_control.py .....                                                                                                                                                                                        [ 11%]
wazuh/core/cluster/tests/test_local_client.py .............                                                                                                                                                                           [ 12%]
wazuh/core/cluster/tests/test_local_server.py .......................                                                                                                                                                                 [ 13%]
wazuh/core/cluster/tests/test_master.py .................................................                                                                                                                                             [ 15%]
wazuh/core/cluster/tests/test_server.py ...................                                                                                                                                                                           [ 16%]
wazuh/core/cluster/tests/test_utils.py ...........                                                                                                                                                                                    [ 17%]
wazuh/core/cluster/tests/test_worker.py .....................................                                                                                                                                                         [ 19%]
wazuh/core/tests/test_active_response.py ..............                                                                                                                                                                               [ 20%]
wazuh/core/tests/test_agent.py ................................................................................................................................................                                                       [ 27%]
wazuh/core/tests/test_cdb_list.py ......................................                                                                                                                                                              [ 29%]
wazuh/core/tests/test_common.py .......                                                                                                                                                                                               [ 29%]
wazuh/core/tests/test_configuration.py ....................................                                                                                                                                                           [ 31%]
wazuh/core/tests/test_database.py .............                                                                                                                                                                                       [ 32%]
wazuh/core/tests/test_decoder.py ................                                                                                                                                                                                     [ 32%]
wazuh/core/tests/test_exception.py ...                                                                                                                                                                                                [ 33%]
wazuh/core/tests/test_input_validator.py ...                                                                                                                        [...]

2022-07-07 07:38 UTC, mcarmona99 approved these changes
LGTM

2022-07-07 08:59 UTC, davidjiglesias requested changes
Remove

2022-07-07 09:00 UTC, davidjiglesias approved these changes

2022-07-07 09:00 UTC, merged

2023-01-26 15:19 UTC, sultanovich commented
hello @vicferpoy , we see that although the code is fine in the [comment in the example code section](https://github.com/wazuh/wazuh/pull/14119#issue-1293190942 ) there is an extra space in the `exceptions` line of the `wodle_command`. 

```yaml
    wodle_command:
      allow: yes
       exceptions: []
```

is it possible to update it in case someone copies the example code from there?


Thanks,