Delete message controller from 9103-replace-fim-db-dbsync
wazuh/wazuh pull request #14248
Opened 2022-07-14 17:45 UTC by FrancoRivero

|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

|Related issue|
|---|
|Closes #14133|
### Description
Hello team, this pull-request is to remove the message controller as a feature of DBSync in order to have compatibility with master and have less merge conflicts.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Unit tests passed
- [x] Review logs syntax and correct language

- Memory tests for Linux
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [x] cppcheck (static code analysis)
  - [x] Coverage (unit tests coverage code)
  - [x] Sformat (code style)
  - [x] Scan build

2022-07-19 16:03 UTC, jotacarma90 approved these changes
LGTM

2022-07-19 23:47 UTC, Dwordcito requested changes

2022-07-19 23:47 UTC, Dwordcito commented on src/shared_modules/rsync/include/rsync.hpp
> -        RegisterConfiguration & minimalSyncIntervalTime(const uint32_t intervalTime);
Remove, line 346

StartSyncConfiguration & syncOnDemand(const bool syncOnDemand);

2022-07-19 23:47 UTC, Dwordcito commented on src/shared_modules/rsync/src/rsync.cpp
> +    };
Remove this.
```suggestion
```

2022-07-19 23:47 UTC, Dwordcito commented on src/shared_modules/rsync/src/rsync.cpp
> -RegisterConfiguration& RegisterConfiguration::minimalSyncIntervalTime(const uint32_t parameter)
remove 364-368 syncOnDemand

2022-07-20 08:00 UTC, antoniomanuelfr approved these changes

2022-07-21 11:57 UTC, chemamartinez approved these changes
LGTM

2022-07-21 13:35 UTC, merged