13522 engine sca decoder
wazuh/wazuh pull request #14291
Opened 2022-07-17 16:10 UTC by LucioDonda

|Related issue|
|---|
|#13522|

## Description

- [ ] Code analysis
- [ ] SCA Event analysis 
- [ ] Code translation from C to C++
- [ ] Improvements of some JSON documents proccesing
- [ ] Unit Tests

2022-07-19 20:52 UTC, LucioDonda commented
Pending Test skipped `0handleCheckResultNotFoundEvent` : alone it works but when it get's executed executed with handleCheckResult it hangs all the proccess.

Also I'm uploading some logs in order to check and test:
[logsAndAlerts.zip](https://github.com/wazuh/wazuh/files/9144644/logsAndAlerts.zip)

2022-08-19 02:16 UTC, nmkoremblum requested changes

2022-08-19 14:26 UTC, juliancnn approved these changes

2022-08-19 19:36 UTC, nmkoremblum approved these changes
LGTM

2022-08-19 19:37 UTC, merged