Engine FIM decoder
wazuh/wazuh pull request #14451
Opened 2022-07-29 05:21 UTC by nmkoremblum

|Related issue|
|---|
|#13524|

## Description

As requested on Issue #13524, a way of decoding FIM events must be added to the engine. This would require creating its YAML-formatted decoder and complementary helper functions if needed.

2022-08-02 11:58 UTC, LucioDonda approved these changes
LGTM

2022-08-08 18:22 UTC, juliancnn approved these changes
LGTM!

2022-08-09 08:28 UTC, JavierBejMen requested changes

2022-08-09 08:28 UTC, JavierBejMen commented on src/engine/source/builder/builders/opBuilderHelperFilter.cpp
> +}
We should give a concise error trace of why it failed:

```c++
if (!event->exists(targetField)
{ // Error, target field not found
...
}
```
This applies to all added helpers

2022-08-11 12:33 UTC, JcabreraC approved these changes
LGTM !

2022-08-18 19:58 UTC, merged