Improve location message colons parsing
wazuh/wazuh pull request #14706
Opened 2022-08-22 13:31 UTC by cborla

|Related issue|
|---|
||

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-08-30 18:12 UTC, TomasTurina requested changes

2022-08-30 18:12 UTC, TomasTurina commented on src/analysisd/cleanevent.c
> +    char * msg_cpy;
```suggestion
    char *msg_cpy;
```

2022-08-31 14:04 UTC, cborla commented on src/shared/string_op.c
> +        if (*str_cpy == scape) {
Added `(*str_cpy != '\0')` control, and dst_size buffer to avoid buffer overflow.

2022-08-31 14:05 UTC, cborla commented on src/analysisd/cleanevent.c
> +    char * msg_cpy;
👍🏻

2022-08-31 14:05 UTC, cborla commented on src/shared/string_op.c
> +    while(*str_cpy != '\0') {
👍🏻

2022-08-31 14:05 UTC, cborla commented on src/shared/string_op.c
> +    while(*str_cpy != '\0') {
👍🏻

2022-08-31 14:05 UTC, cborla commented on src/analysisd/cleanevent.c
> +    char loc_buff[OS_BUFFER_SIZE + 1] = {0};
👍🏻

2022-08-31 14:05 UTC, cborla commented on src/shared/mq_op.c
> +    char loc_buff[OS_BUFFER_SIZE + 1] = {0};
👍🏻

2022-08-31 20:24 UTC, TomasTurina requested changes

2022-08-31 20:24 UTC, TomasTurina commented on src/headers/string_op.h
> + * Returns the size of the dststr if success, or 0 if fail.
Why don't -1 on failure?

2022-08-31 20:24 UTC, TomasTurina commented on src/headers/string_op.h
>   * Returns pointer to dststr if success, or NULL if fail.
Update comment.

2022-08-31 20:24 UTC, TomasTurina commented on src/shared/string_op.c
> +        if (*str_cpy == scape) {
What if the string ends with a `\`? for example, `test\`?

What do you think about this code?

```c
    unsigned int a = 0;
    while (*str_cpy != '\0' && a < dst_size -1) {
        if (*str_cpy == scape && *(str_cpy + 1) != '\0') {
            str_cpy++;
        }
        dststr[a++] = *str_cpy++;
    }
    dststr[a] = '\0';
```

2022-08-31 20:52 UTC, cborla commented on src/shared/string_op.c
> +        if (*str_cpy == scape) {
Regarding first question, if string ends with a `\`, test cases are:

```c
void test_wstr_unescape_one_scape(void ** state) {

    char dststr[OS_BUFFER_SIZE];

    unsigned int ret = wstr_unescape(dststr, sizeof(dststr), "\\", '\\');
    assert_string_equal(dststr, "");
    assert_int_equal(ret, 0);
}

void test_wstr_unescape_end_scape(void ** state) {

    char dststr[OS_BUFFER_SIZE];

    unsigned int ret = wstr_unescape(dststr, sizeof(dststr), "test \\a b\\", '\\');
    assert_string_equal(dststr, "test a b");
    assert_int_equal(ret, 8);
}
```
Where a unique character string with `\` returns zero as a size, and a `\'0'` in the destination buffer.
And second test, unescape ```test \a b\``` to ```test a b```,

2022-08-31 23:13 UTC, cborla commented on src/shared/string_op.c
> +        if (*str_cpy == scape) {
The problem with the proposed code is it leave the ``\`` at the end of the string. two test fails.
Proposed code:
```c
    unsigned int a = 0;
    while (*str_cpy != '\0' && a < dst_size -1) {
        if (*str_cpy == scape && *(str_cpy + 1) != '\0') {
            str_cpy++;
        }
        dststr[a++] = *str_cpy++;
    }
    dststr[a] = '\0';
```

First test:
```c
void test_wstr_unescape_one_scape(void ** state) {
    char dststr[OS_BUFFER_SIZE];
    unsigned int ret = wstr_unescape(dststr, sizeof(dststr), "\\", '\\');
    assert_string_equal(dststr, "");
    assert_int_equal(ret, 0);
}
```
result:
```
[ RUN      ] test_wstr_unescape_one_scape
[  ERROR   ] --- "\" != ""
[   LINE   ] --- /wazuh/src/unit_tests/shared/test_string_op.c:922: error: Failure!
[  FAILED  ] test_wstr_unescape_one_scape
```

Second test:
```c
void test_wstr_unescape_end_scape(void ** state) {
    char dststr[OS_BUFFER_SIZE];
    unsigned int ret = wstr_unescape(dststr, sizeof(dststr), "test \\a b\\", '\\');
    assert_string_equal(dststr, "test a b");
    assert_int_equal(ret, 8);
}
```
result:
```
[ RUN      ] test_wstr_unescape_end_scape
[  ERROR   ] --- "test a b\" != "test a b"
[   LINE   ] --- /wazuh/src/unit_tests/shared/test_string_op.c:931: error: Failure!
[  FAILED  ] test_wstr_unescape_end_scape
```
An option to cover that case and improve the current version is following propose.
```c
    unsigned int a = 0;
    while (*str_cpy != '\0' && a < dst_size -1) {
        if (*str_cpy == scape) {
            str_cpy++;
        }
        if (*str_cpy == '\0') {
            break;
        }
        dststr[a++] = *str_cpy++;
    }
    dststr[a] = '\0';
```

2022-09-02 00:53 UTC, TomasTurina approved these changes

2022-09-07 14:56 UTC, TomasTurina approved these changes

2022-09-08 21:23 UTC, TomasTurina requested changes
You need to apply these changes also for Windows agents.

2022-09-12 18:21 UTC, TomasTurina approved these changes

2022-09-15 12:19 UTC, jmv74211 commented
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3244
- **Comments**:  Everything seems to be working properly, but a few things to keep in mind:
  - The known issue raised in test cases for manager v4.4 with agent 4.3 is an incompatibility issue that can be fixed upgrading the agent to v4.4
  - Some problems were reported in this issue https://github.com/wazuh/wazuh/issues/14886 related to the one fixed in this PR, but with the logcollector commands.

2022-09-22 01:55 UTC, TomasTurina approved these changes
LGTM!

2022-09-30 06:57 UTC, vikman90 approved these changes

2022-09-30 06:57 UTC, merged