Engine AWS CloudTrail and S3 assets
wazuh/wazuh pull request #14714
Opened 2022-08-22 20:40 UTC by nmkoremblum

|Related issues|
|---|
|#14671, #14670|

As described in issues #14671 and #14670, it is required to create assets to process `AWS` events. In this case, for `CloudTrail` and `S3` events.

To do so, we need to create a decoder that generates an ECS-compliant events, and rules to alert about possible security threats.

We need to use:

- high-level parser
- logical expressions
- function helpers
- mapping new fields
- kvdb

All the assets will become part of a single environment that will receive logs and generate the corresponding events.

2022-08-28 22:16 UTC, juliancnn commented on src/engine/test/assets/schemas/wazuh-logql-types.json
> +    "log.syslog": "json",
:eyes:

2022-08-29 16:53 UTC, juliancnn commented on src/engine/test/assets/decoders/aws_cloudtrail.yml
> +      _json: +delete_field
This is not necessary since fields beginning with `_` will be automatically deleted at the end of the event processing.

2022-08-29 16:53 UTC, juliancnn commented on src/engine/test/assets/decoders/aws_s3.yml
> +      _json: +delete_field
This is not necessary since fields beginning with `_` will be automatically deleted at the end of the event processing.

2022-08-30 19:02 UTC, LucioDonda commented on src/engine/test/assets/decoders/aws-cloudtrail.yml
> +      aws.cloudtrail.recipient_account_id: $_json.aws.recipientAccountId
When a field is in a different type than expected the assignment is also done, should this be that way? shouldn't we check also data types?

2022-08-30 19:47 UTC, LucioDonda submitted a review, later dismissed
lgtm

2022-08-31 20:27 UTC, juliancnn requested changes

2022-08-31 20:27 UTC, juliancnn commented on src/engine/test/assets/decoders/json.yml
> +  - event.original: +r_match/^{.+}$
Avoid using a regex, it is almost as likely to have a key at the beginning as the one at the end, you can check only the key at the beginning is `+s_start/{`

2022-08-31 20:27 UTC, juliancnn commented on src/engine/test/assets/schemas/wazuh-logql-types.json
> +  "aws.s3access.bucket": "keyword",
This is ordered in reverse, `bucket` < `bucket_owner`

2022-08-31 20:27 UTC, juliancnn commented on src/engine/test/assets/schemas/custom-ecs-field.json
> +    "aws.s3access.bucket": {
This is ordered in reverse, `bucket` < `bucket_owner`

2022-09-01 13:07 UTC, JavierBejMen approved these changes
LGTM

2022-09-01 15:36 UTC, JcabreraC approved these changes
LGTM !

2022-09-01 15:37 UTC, merged