Make cluster wait for agent-info data from wdb asynchronously
wazuh/wazuh pull request #14791
Opened 2022-09-02 11:57 UTC by Selutario

|Related issue|
|---|
| Closes #14765 |

## Description

This PR adds a new async version (`AsyncWazuhDBConnection`) of the [WazuhDBConnection](https://github.com/wazuh/wazuh/blob/bc39d6791fad8e629fbe8b8ef2e9713bca0affba/framework/wazuh/core/wdb.py#L19-L22) class used to send and retrieve information from `wazuh-db`. 

This class lets the cluster request agent-info data and do other tasks (like answering distributed API requests) while waiting for `wazuh-db` response to be ready. This greatly improves cluster performance in environments where the database is very busy.

## Logs/Alerts example

### Sync requests to wdb
This is how the cluster behaves when wazuh-db is slow to respond (in this case, 20 seconds). As can be seen, there has been no log between `10:47:10` and `10:47:30`, which means that the cluster has been blocked and all tasks have been delayed:
```
2022/09/01 10:47:10 INFO: [Worker worker1] [Agent-info sync] Starting.
2022/09/01 10:47:30 DEBUG: [Worker worker1] [Agent-info sync] Obtained 20 chunks of data in 20.248s.
2022/09/01 10:47:30 DEBUG: [Worker worker1] [Main] Command received: 'b'dapi''
2022/09/01 10:47:30 DEBUG: [Worker worker1] [D API] Received request: b'master*527235 {"f": {"__callable__": {"__name__": "get_api_config", "__module__": "wazuh.manager", "__qualname__": "get_api_config", "__type__": "function"}}, "f_kwargs": {}, "request_type": "distributed_master", "wait_for_complete": true, "from_cluster": true, "is_async": false, "local_client_arg": null, "basic_services": ["wazuh-modulesd", "wazuh-analysisd", "wazuh-execd", "wazuh-db", "wazuh-remoted"], "rbac_permissions": {"agent:create": {"*:*:*": "allow"}, "group:create": {"*:*:*": "allow"}, "agent:read": {"agent:id:*": "allow", "agent:group:*": "allow"}, "agent:delete": {"agent:id:*": "allow", "agent:group:*": "allow"}, "agent:modify_group": {"agent:id:*": "allow", "agent:group:*": "allow"}, "agent:reconnect": {"agent:id:*": "allow", "agent:group:*": "allow"}, "agent:restart": {"agent:id:*": "allow", "agent:group:*": "allow"}, "agent:upgrade": {"agent:id:*": "allow", "agent:group:*": "allow"}, "group:read": {"group:id:*": "allow"}, "group:delete": {"group:id:*": "allow"}, "group:update_config": {"group:id:*": "allow"}, "group:modify_assignments": {"group:id:*": "allow"}, "active-response:command": {"agent:id:*": "allow"}, "security:create": {"*:*:*": "allow"}, "security:create_user": {"*:*:*": "allow"}, "security:read_config": {"*:*:*": "allow"}, "security:update_config": {"*:*:*": "allow"}, "security:revoke": {"*:*:*": "allow"}, "security:edit_run_as": {"*:*:*": "allow"}, "security:read": {"role:id:*": "allow", "policy:id:*": "allow", "user:id:*": "allow", "rule:id:*": "allow"}, "security:update": {"role:id:*": "allow", "policy:id:*": "allow", "user:id:*": "allow", "rule:id:*": "allow"}, "security:delete": {"role:id:*": "allow", "policy:id:*": "allow", "user:id:*": "allow", "rule:id:*": "allow"}, "cluster:status": {"*:*:*": "allow"}, "manager:read": {"*:*:*": "allow"}, "manager:read_api_config": {"*:*:*": "allow"}, "manager:update_config": {"*:*:*": "allow"}, "manager:restart": {"*:*:*": "allow"}, "cluster:read_api_config": {"node:id:*": "allow"}, "cluster:read": {"node:id:*": "allow"}, "cluster:restart": {"node:id:*": "allow"}, "cluster:update_config": {"node:id:*": "allow"}, "ciscat:read": {"agent:id:*": "allow"}, "decoders:read": {"decoder:file:*": "allow"}, "decoders:delete": {"decoder:file:*": "allow"}, "decoders:update": {"*:*:*": "allow"}, "lists:read": {"list:file:*": "allow"}, "lists:delete": {"list:file:*": "allow"}, "lists:update": {"*:*:*": "allow"}, "rootcheck:clear": {"agent:id:*": "allow"}, "rootcheck:read": {"agent:id:*": "allow"}, "rootcheck:run": {"agent:id:*": "allow"}, "rules:read": {"rule:file:*": "allow"}, "rules:delete": {"rule:file:*": "allow"}, "rules:update": {"*:*:*": "allow"}, "mitre:read": {"*:*:*": "allow"}, "sca:read": {"agent:id:*": "allow"}, "syscheck:clear": {"agent:id:*": "allow"}, "syscheck:read": {"agent:id:*": "allow"}, "syscheck:run": {"agent:id:*": "allow"}, "syscollector:read": {"agent:id:*": "allow"}, "logtest:run": {"*:*:*": "allow"}, "task:status": {"*:*:*": "allow"}, "vulnerability:read": {"agent:id:*": "allow"}, "rbac_mode": "white"}, "current_user": "", "broadcasting": false, "nodes": ["master-node", "worker1"], "api_timeout": 10}'
2022/09/01 10:47:30 INFO: [Worker worker1] [D API] Receiving request: get_api_config from master (527235)
2022/09/01 10:47:30 DEBUG: [Worker worker1] [D API] Receiving parameters {}
2022/09/01 10:47:30 DEBUG: [Worker worker1] [D API] Starting to execute request locally
2022/09/01 10:47:30 DEBUG: [Worker worker1] [D API] Finished executing request locally
2022/09/01 10:47:30 DEBUG: [Worker worker1] [D API] Time calculating request result: 0.032s
2022/09/01 10:47:30 DEBUG: [Worker worker1] [Integrity check] Permission to synchronize granted.
2022/09/01 10:47:30 INFO: [Worker worker1] [Integrity check] Starting.
2022/09/01 10:47:30 DEBUG: [Worker worker1] [Integrity check] Compressing 'files_metadata.json' of 36 files.
2022/09/01 10:47:30 DEBUG: [Worker worker1] [Integrity check] Sending zip file to master.
2022/09/01 10:47:30 DEBUG: [Worker worker1] [Agent-info sync] All chunks sent.
2022/09/01 10:47:30 DEBUG: [Worker worker1] [Integrity check] Zip file sent to master.
2022/09/01 10:47:30 DEBUG: [Worker worker1] [Main] Command received: 'b'syn_m_c_ok''
2022/09/01 10:47:30 INFO: [Worker worker1] [Integrity check] Finished in 0.068s. Sync not required.
2022/09/01 10:47:30 DEBUG: [Worker worker1] [Main] Command received: 'b'syn_m_a_e''
2022/09/01 10:47:30 INFO: [Worker worker1] [Agent-info sync] Finished in 20.462s (20 chunks updated).
```
Any API calls that have to be distributed to the affected node are also delayed, as in this case `GET /cluster/api/config`, which has taken 17 seconds to complete:
```
2022/09/01 10:47:30 INFO: wazuh 192.168.16.1 "GET /cluster/api/config" with parameters {"wait_for_complete": "true", "nodes_list": "worker1"} and body {} done in 17.185s: 200
```

### Async requests to wdb
Now, as the requests are async, other tasks are performed in the meantime even if `wazuh-db` is still taking 20 seconds to return a response (which occurred at `11:02:13`):
```
2022/09/01 11:01:53 INFO: [Worker worker1] [Agent-info sync] Starting.
2022/09/01 11:01:57 DEBUG: [Worker worker1] [Main] Command received: 'b'dapi''
2022/09/01 11:01:57 DEBUG: [Worker worker1] [D API] Received request: b'master*807364 {"f": {"__callable__": {"__name__": "get_api_config", "__module__": "wazuh.manager", "__qualname__": "get_api_config", "__type__": "function"}}, "f_kwargs": {}, "request_type": "distributed_master", "wait_for_complete": true, "from_cluster": true, "is_async": false, "local_client_arg": null, "basic_services": ["wazuh-modulesd", "wazuh-analysisd", "wazuh-execd", "wazuh-db", "wazuh-remoted"], "rbac_permissions": {"agent:create": {"*:*:*": "allow"}, "group:create": {"*:*:*": "allow"}, "agent:read": {"agent:id:*": "allow", "agent:group:*": "allow"}, "agent:delete": {"agent:id:*": "allow", "agent:group:*": "allow"}, "agent:modify_group": {"agent:id:*": "allow", "agent:group:*": "allow"}, "agent:reconnect": {"agent:id:*": "allow", "agent:group:*": "allow"}, "agent:restart": {"agent:id:*": "allow", "agent:group:*": "allow"}, "agent:upgrade": {"agent:id:*": "allow", "agent:group:*": "allow"}, "group:read": {"group:id:*": "allow"}, "group:delete": {"group:id:*": "allow"}, "group:update_config": {"group:id:*": "allow"}, "group:modify_assignments": {"group:id:*": "allow"}, "active-response:command": {"agent:id:*": "allow"}, "security:create": {"*:*:*": "allow"}, "security:create_user": {"*:*:*": "allow"}, "security:read_config": {"*:*:*": "allow"}, "security:update_config": {"*:*:*": "allow"}, "security:revoke": {"*:*:*": "allow"}, "security:edit_run_as": {"*:*:*": "allow"}, "security:read": {"role:id:*": "allow", "policy:id:*": "allow", "user:id:*": "allow", "rule:id:*": "allow"}, "security:update": {" [...]

2022-09-05 08:14 UTC, AdriiiPRodri approved these changes

2022-09-06 06:53 UTC, davidjiglesias requested changes

2022-09-06 06:53 UTC, davidjiglesias commented on framework/wazuh/core/wdb.py
> +    Represents an async connection to the wdb socket.
```suggestion
    Represent an async connection to the wdb socket.
```

2022-09-07 10:15 UTC, davidjiglesias approved these changes

2022-09-12 10:18 UTC, Selutario commented
Will be done in 4.4:

- https://github.com/wazuh/wazuh/pull/14843

2022-09-12 10:22 UTC, closed without merging