Add  an alert when active response can be triggered
wazuh/wazuh pull request #14804
Opened 2022-09-05 15:44 UTC by thejbte

|Related issues|Manual Testing|
|---|---|
|https://github.com/wazuh/wazuh/issues/14504||

## Description
This PR solves the issue https://github.com/wazuh/wazuh/issues/14504, the proposed solution was to generate an alert when the firewall is disabled, it is verified if the firewall is down and if so, it is written in the active response log in order to be able to generate the alert. A rule (658) for active response is also added.

## Configuration options
Agent ossec.conf :
```xml
  <localfile>
    <location>active-response\active-responses.log</location>
    <log_format>syslog</log_format>
  </localfile>
```
### Configuration option for test
Agent ossec.conf :
```xml
  <localfile>
    <location>C:\Users\vagrant\Documents\test.txt</location>
    <log_format>syslog</log_format>
  </localfile>
```
Manager ossec.conf:
```xml
  <active-response>
    <command>netsh</command>
    <location>local</location>
    <rules_id>5716</rules_id>
    <timeout>60</timeout>
  </active-response>
```
### Option test

1. Set configuration option for test

2. For trigger active response put  next sentece in `test.txt` 
```txt
Dec 10 01:02:02 host sshd[1234]: Failed none for root from <IP_TO_BLOCK> port 1066 ssh2
```

## Logs/Alerts example

1. only public profile disabled

```vim
Rule: 658 (level 5) -> 'Active response: Firewall is disabled , status: inactive, profile: FIREWALL_PUBLIC'
2022/09/05 15:16:31 active-response/bin/netsh.exe: {"message":"Firewall is disabled","profile":"FIREWALL_PUBLIC","status":"inactive"}
message: Firewall is disabled
```

2. all profiles disabled 

```vim
Rule: 658 (level 5) -> 'Active response: Firewall is disabled , status: inactive, profile: FIREWALL_DOMAIN'
2022/09/05 15:17:57 active-response/bin/netsh.exe: {"message":"Firewall is disabled","profile":"FIREWALL_DOMAIN","status":"inactive"}
message: Firewall is disabled
Rule: 658 (level 5) -> 'Active response: Firewall is disabled , status: inactive, profile: FIREWALL_PRIVATE'
2022/09/05 15:17:57 active-response/bin/netsh.exe: {"message":"Firewall is disabled","profile":"FIREWALL_PRIVATE","status":"inactive"}
message: Firewall is disabled
Rule: 658 (level 5) -> 'Active response: Firewall is disabled , status: inactive, profile: FIREWALL_PUBLIC'
2022/09/05 15:17:57 active-response/bin/netsh.exe: {"message":"Firewall is disabled","profile":"FIREWALL_PUBLIC","status":"inactive"}
message: Firewall is disabled

```

## Tests

- Compilation without warnings in every supported platform
  - [x] Windows
- [x] Source installation
- [ ] Package installation
- [x] Source upgrade
- [ ] Package upgrade
- [x] Review logs syntax and correct language
- [x] QA templates contemplate the added capabilities

- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-09-08 20:37 UTC, TomasTurina approved these changes

2022-10-19 16:23 UTC, TomasTurina requested changes

2022-10-19 16:23 UTC, TomasTurina commented on src/Makefile
> +win32/netsh.exe: ${WAZUH_LIB} ${WAZUHEXT_LIB} active-response/utilities.o active-response/active_responses.o
Why do you add two `netsh.exe` in the Makefile and not just one?

2022-10-19 16:23 UTC, TomasTurina commented on src/active-response/utilities.h
> +#ifndef _UTILITIES_H_
Don't create this file. We have already `src/active-response/active_responses.h` for common functions.

2022-10-19 16:23 UTC, TomasTurina commented on src/active-response/utilities.c
> +
Don't create this file. We have already `src/active-response/active_responses.c` for common functions.

2022-10-19 16:23 UTC, TomasTurina commented on src/active-response/utilities.c
> +void getStatusFirewallProfile(const char * output_buf, firewallData_t *firewallData){
Move this function to `src/active-response/netsh.c`

2022-10-19 16:23 UTC, TomasTurina commented on src/active-response/utilities.h
> +void getFirewallProfile(const char * output_buf, firewallData_t *firewallData);
Move this function to `src/active-response/netsh.c`

2022-10-19 16:23 UTC, TomasTurina commented on src/active-response/utilities.h
> +#define FIREWALL_PROFILES_MAX (3) /*!< Maximun number of profiles*/
Move this define to `src/active-response/netsh.c`

2022-10-19 16:23 UTC, TomasTurina commented on src/active-response/utilities.c
> +char* splitStrFromCharDelimiter(const char * output_buf, const char delimiter, char * strBefore, char *strAfter){
Move this function to `src/active-response/active_responses.c`

2022-10-19 16:23 UTC, TomasTurina commented on src/active-response/utilities.c
> +int isEnabledFromPattern(const char * output_buf, const char * str_pattern_1, const char * str_pattern_2){
Move this function to `src/active-response/active_responses.c`

2022-10-19 16:23 UTC, TomasTurina commented on src/active-response/utilities.c
> +int isEnabledFromPattern(const char * output_buf, const char * str_pattern_1, const char * str_pattern_2){
Use the function from the macOS PR: https://github.com/wazuh/wazuh/pull/14962/files#diff-8c46d6aa3fa2cb1de063c4b912f020b5f74722352fc96e486815b088f4d88474R241 that is already reviewed and approved

2022-10-19 16:23 UTC, TomasTurina commented on src/active-response/utilities.c
> +int isEnabledFromPattern(const char * output_buf, const char * str_pattern_1, const char * str_pattern_2){
You will have to delete it from the `src/active-response/firewalls/pf.c` file in the macOS PR later and use the one from `src/active-response/active_responses.c`

2022-10-20 13:58 UTC, TomasTurina requested changes
Also, delete all blanck space such as: 
![image](https://user-images.githubusercontent.com/11877311/196969004-dcc4b6db-fc13-42ac-ad03-17566222cec7.png)
I use the extension trailing spaces in VSCode to localize and delete automatically them.

2022-10-20 13:58 UTC, TomasTurina commented on src/active-response/active_responses.c
> +        pos = strchr(output_buf, delimiter);
Check if `pos` is valid.

2022-10-20 13:58 UTC, TomasTurina commented on src/active-response/active_responses.c
> +    return  retVal;
```suggestion
    return retVal;
```

2022-10-20 13:58 UTC, TomasTurina commented on src/Makefile
> +
Remove.

2022-10-20 13:58 UTC, TomasTurina commented on src/active-response/netsh.c
> +/**
Move the description to the declaration of the function.

2022-10-20 13:58 UTC, TomasTurina commented on src/active-response/netsh.c
> +    char *exec_args_show_profile[6] = { REG, "query", pathFirewallProfilesReg, "/v", "EnableFirewall", NULL};
```suggestion
    char *exec_args_show_profile[6] = { REG, "query", pathFirewallProfilesReg, "/v", "EnableFirewall", NULL };
```

2022-10-20 13:58 UTC, TomasTurina commented on src/active-response/netsh.c
> +    const char *firewallProfileStr[FIREWALL_PROFILES_MAX + 1] = {"FIREWALL_DOMAIN", "FIREWALL_PRIVATE", "FIREWALL_PUBLIC", "FIREWALL_DEFAULT" };
```suggestion
    const char *firewallProfileStr[FIREWALL_PROFILES_MAX + 1] = { "FIREWALL_DOMAIN", "FIREWALL_PRIVATE", "FIREWALL_PUBLIC", "FIREWALL_DEFAULT" };
```

2022-10-20 13:58 UTC, TomasTurina commented on src/active-response/netsh.c
> +    for ( int i = 0; i < FIREWALL_PROFILES_MAX; i++) {
```suggestion
    for (int i = 0; i < FIREWALL_PROFILES_MAX; i++) {
```

2022-10-20 13:58 UTC, TomasTurina commented on src/active-response/netsh.c
> +        if (exec_args_show_profile[2] != NULL) {
Is this check really necessary?

2022-10-20 13:58 UTC, TomasTurina commented on src/active-response/netsh.c
> +    if( output_buf != NULL){
```suggestion
    if (output_buf != NULL) {
```

2022-10-20 13:58 UTC, TomasTurina commented on src/active-response/netsh.c
> +                }else {
```suggestion
                } else {
```

2022-10-20 13:58 UTC, TomasTurina commented on src/active-response/netsh.c
> +    cJSON *input_json;
I think you don't need this. Free the JSON here https://github.com/wazuh/wazuh/pull/14804/files#diff-20cc756527cbb2a9d85240db689dd920417d7d2c629041e7f6c9e05ddfe0778aR120

2022-10-20 13:58 UTC, TomasTurina commented on src/active-response/netsh.c
> +    char **argv;
You are using only argv[0], I think this parameter can be a char*

2022-10-20 13:58 UTC, TomasTurina commented on src/active-response/netsh.c
> +        if (action == ADD_COMMAND){
```suggestion
        if (action == ADD_COMMAND) {
```

2022-10-20 14:06 UTC, TomasTurina requested changes

2022-10-20 14:06 UTC, TomasTurina commented on src/active-response/netsh.c
> +typedef struct {
I think this struct is not necessary. You can create `log_msg` locally inside the function `getAllProfilesStatus`. Only send argv[0] as parameter of `getAllProfilesStatus`.

2022-10-21 01:53 UTC, TomasTurina submitted a review, later dismissed

2022-12-05 15:21 UTC, QU3B1M commented
# Testing results


## Upgrade

<details><summary>Upgrade process</summary>

- Upgrade wazuh-manager 
    ```log
    dpkg -i wazuh-manager_4.5.0-3295.d21faf3_amd64.deb

    (Reading database ... 82195 files and directories currently installed.)
    Preparing to unpack .../wazuh-manager_4.5.0-3295.d21faf3_amd64.deb ...
    Unpacking wazuh-manager (4.5.0-3295.d21faf3) over (4.3.10-1) ...
    Setting up wazuh-manager (4.5.0-3295.d21faf3) ...
    Processing triggers for systemd (245.4-4ubuntu3.17) ...
    ```
- Upgrade wazuh-agent (windows server 2022)

</details>


<details><summary>IP drops correctly when firewall is up, otherwise an alert is raised - Windows Server 2022 :green_circle:</summary>

  - <details><summary>Configurations</summary>

    - `wazuh-agent` config:
        ```xml
        <localfile>
          <location>C:\test.txt</location>
          <log_format>syslog</log_format>
        </localfile>  
        ```
    - `wazuh-manager` config:
        ```xml
        <active-response>
          <command>netsh</command>
          <location>local</location>
          <rules_id>5716</rules_id>
          <timeout>60</timeout>
        </active-response>
        ```

    </details>

  - <details><summary>All firewall profiles activated :green_circle:</summary>

    1. Setup configurations in `wazuh-manager` and `wazuh-agent`
    2. Ensure all the firewall profiles are activated
        ```bash
        netsh advfirewall set allprofiles state on

        Ok.
        ```
    3. From an `attacker` machine ping the `windows agent` to verify the connection between systems
        ```log
        ping 192.168.56.13

        PING 192.168.56.13 (192.168.56.13) 56(84) bytes of data.
        64 bytes from 192.168.56.13: icmp_seq=1 ttl=128 time=0.415 ms
        64 bytes from 192.168.56.13: icmp_seq=2 ttl=128 time=0.484 ms
        ^C
        --- 192.168.56.13 ping statistics ---
        2 packets transmitted, 2 received, 0% packet loss, time 1009ms
        rtt min/avg/max/mdev = 0.415/0.449/0.484/0.034 ms
        ```
    4. Inside the file `test.txt` enter a log to trigger `active response` to block the attacker's IP 
        ```log
        Dec 10 01:02:02 host sshd[1234]: Failed none for root from 192.168.56.11 port 1066 ssh2
        ```
    5. Check the firewall rule is generated
        ```bash
        netsh advfirewall firewall show rule name="WAZUH ACTIVE RESPONSE BLOCKED IP"
        ```
        ```
        Rule Name:                            WAZUH ACTIVE RESPONSE BLOCKED IP
        ----------------------------------------------------------------------
        Enabled:                              Yes
        Direction:                            In
        Profiles:                             Domain,Private,Public
        Grouping:
        LocalIP:                              Any
        RemoteIP:                             192.168.56.11/32
        Protocol:                             Any
        Edge traversal:                       No
        Action:                               Block
        Ok.                
        ```
    6. Check the attacker's IP is dropped
        ```log
        ping 192.168.56.13

        PING 192.168.56.13 (192.168.56.13) 56(84) bytes of data.
        ^C
        --- 192.168.56.13 ping statistics ---
        19 packets transmitted, 0 received, 100% packet loss, time 18432ms
        ```
    7. Check the `Active response may not have an effect` alert is not generated
        ```bash
        grep "Active response may not have an effect" /var/ossec/logs/alerts/alerts.log
        ```

    </details>

- <details><summary>Firewall public profile deactivated :green_circle:</summary>

    1. Setup configurations in `wazuh-manager` and `wazuh-agent`
    2. Deactivate the `Public` firewall profile
        ```bash
        netsh advfirewall set Public state off

        Ok.
        ```
    3. From an `attacker` machine ping the `windows agent` to verify the connection between systems
        ```log
        ping 192.168.56.13

        PING 192.168.56.13 (192.168.56.13) 56(84) bytes of data.
        64 bytes from 192.168.56.13: icmp_seq=1 ttl=128 time=0.415 ms
        64 bytes from 192.168.56.13: icmp_seq=2 ttl=128 time=0.484 ms
        ^C
        --- 192.168.56.13 ping statistics ---
        2 packets transmitted, 2 received, 0% packet loss, time 1009ms
        rtt min/avg/max/mdev = 0.415/0.449/0.484/0.034 ms
        ```
    4. Inside the file `test.txt` enter a log to trigger `active response` to block the attacker's IP 
        ```log
        Dec 10 01:02:02 host sshd[1234]: Failed none for root from 192.168.56.11 port 1066 ssh2
        ```
    5. Check the firewall rule is generated
        ```bash
        netsh advfirewall firewall show rule name="WAZUH ACTIVE RESPONSE BLOCKED IP"
        ```
        ```
        Rule Name:                            WAZUH ACTIVE RESPONSE BLOCKED IP
        ----------------------------------------------------------------------
        Enabled:                              Yes
        Direction:                            In
        Profiles:                             Domain,Private,Public
        Grouping:
        LocalIP:                              Any
        RemoteIP:                             192.168.56.11/32
        Protocol:                             Any
        Edge traversal:                       No
        Action:                               Block
        Ok.                
        ```
    6. Check the attacker's IP is not dropped
        ```log
        ping 192.168.56.13

        PING 192.168.56.13 (192.168.56.13) 56(84) bytes of data.
        64 bytes from 192.168.56.13: icmp_seq=1 ttl=128 time=0.605 ms
        64 bytes from 192.168.56.13: icmp_seq=2 ttl=128 time=0.588 ms
        64 bytes from 192.168.56.13: icmp_seq=3 ttl=128 time=0.377 ms
        ^C
        --- 192.168.56.13 ping statistics ---
        3 packets transmitted, 3 received, 0% packet loss, time 2053ms
        rtt min/avg/max/mdev = 0.377/0.523/0.605/0.103 ms
        ```
    7. Check the `Active response may not have an effect` alert is generated correctly
        ```JSON
        grep "Active response may not have an effect" /var/ossec/logs/alerts/alerts.log

        {
          "timestamp": "2022-12-02T19:24:38.551+0000",
          "rule": {
            "level": 5,
            "description": "Active response related to netsh has been activated, but may not have an effect because the firewall is inactive",
            "id": "658",
            "firedtimes": 1,
            "mail": false,
            "groups": ["ossec", "active_response"],
            "pci_dss": ["11.4"],
            "gdpr": ["IV_35.7.d"],
            "nist_800_53": ["SI.4"],
            "tsc": ["CC6.1", "CC6.8", "CC7.2", "CC7.3", "CC7.4"]
          },
          "agent": {
            "id": "002",
            "name": "windows2022",
            "ip": "FE80:0000:0000:0000:70F3:F655:A546:B0A3"
          },
          "manager": { "name": "manager" },
          "id": "1670009078.1753087",
          "full_log": "2022/12/02 19:24:38 active-response/bin/netsh.exe: {\"message\":\"Active response may not have an effect\",\"firewall\":{\"profile1\":\"FIREWALL_DOMAIN\",\"status1\":\"active\",\"profile2\":\"FIREWALL_PRIVATE\",\"status2\":\"active\",\"profile3\":\"FIREWALL_PUBLIC\",\"status3\":\"inactive\"},\"status\":\"inactive\",\"script\":\"netsh\"}",
          "decoder": { "parent": "ar_log_json", "name": "ar_log_json" },
          "data": {
            "status": "inactive",
            "message": "Active response may not have an effect",
            "firewall": {
              "profile1": "FIREWALL_DOMAIN",
              "status1": "active",
              "profile2": "FIREWALL_PRIVATE",
              "status2": "active",
              "profile3": "FIREWALL_PUBLIC",
              "status3": "inactive"
            },
            "script": "netsh"
          },
          "location": "active-response\\active-responses.log"
        }
        ```

  </details>

- [...]

2022-12-10 03:42 UTC, thejbte commented
Fixed the error in the previous versions of Windows where the 3 firewall profiles do not exist, for example, in some Windows like XP there is only the private profile and when this happened, the json was created wrong.

Evidence of possible combinations is attached when there is no some profile (2^3 -1) , its tested in Windows 10 and Windows XP SP1.
<details><summary>screenshots </summary>

![Screenshot from 2022-12-09 19-54-38](https://user-images.githubusercontent.com/17997755/206827261-611892d1-873d-43ea-b9a2-0e8896d3c68b.png)
![Screenshot from 2022-12-09 20-58-01](https://user-images.githubusercontent.com/17997755/206827271-d3bc5035-3956-4dd1-b66d-00c8f0344c78.png)
![Screenshot from 2022-12-09 21-11-26](https://user-images.githubusercontent.com/17997755/206827319-f2f1360b-f617-4240-a3e2-9f79cd03f26d.png)
![Screenshot from 2022-12-09 21-11-55](https://user-images.githubusercontent.com/17997755/206827321-5bf92d92-e5d0-41ad-91ab-f36d68786eef.png)
![Screenshot from 2022-12-09 22-38-05](https://user-images.githubusercontent.com/17997755/206827323-93e7e6c3-055d-4826-8fc8-c214166c489f.png)

</details>

2022-12-12 13:46 UTC, cborla approved these changes
LGTM

2022-12-29 19:23 UTC, TomasTurina approved these changes

2022-12-29 19:34 UTC, damarisg commented
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3295
- **Comments**:  https://github.com/wazuh/wazuh-qa/issues/3295#issuecomment-1251065650

2022-12-29 20:18 UTC, merged