Add the initial configuration of wazuh_table and pf to the .conf file…
wazuh/wazuh pull request #14962
Opened 2022-09-17 21:04 UTC by thejbte

|Related issues|Manual Testing|
|---|---|
|https://github.com/wazuh/wazuh/issues/14073|[#3301](https://github.com/wazuh/wazuh-qa/issues/3301)|

## Description
This PR solves the issue https://github.com/wazuh/wazuh/issues/14073, the proposed solution was that when a **wazuh_fwtable** does not exist, it is created , the configurations are added to the `pf.conf` and `rc.conf` files and `pf` rules are reload. Also added an alert when the firewall is disabled, it is verified if the firewall is down and if so, it is written in the active response log in order to be able to generate the alert, for this the rule (658) is used.

## Configuration options
Agent ossec.conf :
```xml
<ossec_config>
  <localfile>
    <location>active-response\active-responses.log</location>
    <log_format>syslog</log_format>
  </localfile>
</ossec_config>
```
### Configuration option for test
Agent ossec.conf :
```xml
<ossec_config>
  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/apache2/access_log</location>
  </localfile>
</ossec_config>
```
Manager ossec.conf:
```xml
<ossec_config>
   <active-response>
     <command>firewall-drop</command>
     <location>local</location>
     <rules_id>100100</rules_id>
     <timeout>60</timeout>
   </active-response>
 </ossec_config>
```

```xml
<ossec_config>
      <ruleset>
          
          <decoder_dir>ruleset/decoders</decoder_dir>
          <rule_dir>ruleset/rules</rule_dir>
          <rule_exclude>0215-policy_rules.xml</rule_exclude>
          <list>etc/lists/audit-keys</list>
         <list>etc/lists/blacklist-alienvault</list>
          
          <decoder_dir>etc/decoders</decoder_dir>
          <rule_dir>etc/rules</rule_dir>
      </ruleset>

      <active-response>
          <command>firewall-drop</command>
          <location>local</location>
          <rules_id>100100</rules_id>
          <timeout>60</timeout>
      </active-response>
</ossec_config>
```
### Option test
1. Set configuration option for test
2. Configure Blocking a malicious actor PoC [(Link)](https://documentation.wazuh.com/current/proof-of-concept-guide/block-malicious-actor-ip-reputation.html)
3. Generate the alert
4. Try to access the agent from ssh when it has generated an alert blocking a malicious actor, so that it verifies that the firewall has its IP blocked

<details><summary><b>Vagrantfile Mac OS (optional)</summary>
<p>

#### Steps:
1. vagrant up
2. if has error, disable usb  3.0 and set to 1.0
3. VBoxManage modifyvm "mojave_instance_bck" --cpu-profile "Intel Core i7-6700K"
4. vagrant up

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "danimaetrix/macOS-mojave"
  config.vm.box_version = "1.0"
  config.vm.network "private_network", ip: "192.168.56.80"
   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.name = "mojave_instance_bck"
     # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
   end
 end
```
</p>
</details>

## Logs/Alerts example

#### Alert when firewall is disabled
```vim
{"timestamp":"2022-09-17T15:16:16.526-0500","rule":{"level":5,"description":"Active response: Firewall is disabled, status: inactive, profile: undefined","id":"658","firedtimes":1,"mail":false,"groups":["ossec","active_response"],"pci_dss":["11.4"],"gdpr":["IV_35.7.d"],"nist_800_53":["SI.4"],"tsc":["CC6.1","CC6.8","CC7.2","CC7.3","CC7.4"]},"agent":{"id":"006","name":"Vagrants-MacBook-Pro-Bck.local","ip":"FE80:0000:0000:0000:1876:67B9:B5D4:0765"},"manager":{"name":"thejbte-ASUS-TUF-A15"},"id":"1663445776.1452698","full_log":"2022/09/17 15:16:16 active-response/bin/firewall-drop: {\"message\":\"Firewall is disabled\",\"profile\":\"undefined\",\"status\":\"inactive\"}","decoder":{"name":"ar_log_json"},"data":{"status":"inactive","message":"Firewall is disabled","profile":"undefined"},"location":"/Library/Ossec/logs/active-responses.log"}
```
#### Alert when blocking a malicious actor 
```vim
{"timestamp":"2022-09-17T14:20:08.552-0500","rule":{"level":10,"description":"IP address found in AlienVault reputation database.","id":"100100","firedtimes":4,"mail":false,"groups":["attack"]},"agent":{"id":"006","name":"Vagrants-MacBook-Pro-Bck.local","ip":"FE80:0000:0000:0000:1876:67B9:B5D4:0765"},"manager":{"name":"thejbte-ASUS-TUF-A15"},"id":"1663442408.1315007","full_log":"192.168.56.66 - - [17/Sep/2022:14:20:06 -0500] \"GET / HTTP/1.1\" 304 -","decoder":{"name":"web-accesslog"},"data":{"protocol":"GET","srcip":"192.168.56.66","id":"304","url":"/"},"location":"/var/log/apache2/access_log"}

{"timestamp":"2022-09-17T14:20:08.605-0500","rule":{"level":3,"description":"Host Blocked by firewall-drop Active Response","id":"651","firedtimes":18,"mail":false,"groups":["ossec","active_response"],"pci_dss":["11.4"],"gpg13":["4.13"],"gdpr":["IV_35.7.d"],"nist_800_53":["SI.4"],"tsc":["CC6.1","CC6.8","CC7.2","CC7.3","CC7.4"]},"agent":{"id":"006","name":"Vagrants-MacBook-Pro-Bck.local","ip":"FE80:0000:0000:0000:1876:67B9:B5D4:0765"},"manager":{"name":"thejbte-ASUS-TUF-A15"},"id":"1663442408.1315307","full_log":"2022/09/17 14:20:08 active-response/bin/firewall-drop: {\"version\":1,\"origin\":{\"name\":\"node01\",\"module\":\"wazuh-execd\"},\"command\":\"add\",\"parameters\":{\"extra_args\":[],\"alert\":{\"timestamp\":\"2022-09-17T14:20:08.552-0500\",\"rule\":{\"level\":10,\"description\":\"IP address found in AlienVault reputation database.\",\"id\":\"100100\",\"firedtimes\":4,\"mail\":false,\"groups\":[\"attack\"]},\"agent\":{\"id\":\"006\",\"name\":\"Vagrants-MacBook-Pro-Bck.local\",\"ip\":\"FE80:0000:0000:0000:1876:67B9:B5D4:0765\"},\"manager\":{\"name\":\"thejbte-ASUS-TUF-A15\"},\"id\":\"1663442408.1315007\",\"full_log\":\"192.168.56.66 - - [17/Sep/2022:14:20:06 -0500] \\\"GET / HTTP/1.1\\\" 304 -\",\"decoder\":{\"name\":\"web-accesslog\"},\"data\":{\"protocol\":\"GET\",\"srcip\":\"192.168.56.66\",\"id\":\"304\",\"url\":\"/\"},\"location\":\"/var/log/apache2/access_log\"},\"program\":\"active-response/bin/firewall-drop\"}}","decoder":{"name":"ar_log_json"},"data":{"version":"1","origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"timestamp":"2022-09-17T14:20:08.552-0500","rule":{"level":"10","description":"IP address found in AlienVault reputation database.","id":"100100","firedtimes":"4","mail":"false","groups":["attack"]},"agent":{"id":"006","name":"Vagrants-MacBook-Pro-Bck.local","ip":"FE80:0000:0000:0000:1876:67B9:B5D4:0765"},"manager":{"name":"thejbte-ASUS-TUF-A15"},"id":"1663442408.1315007","full_log":"192.168.56.66 - - [17/Sep/2022:14:20:06 -0500] \"GET / HTTP/1.1\" 304 -","decoder":{"name":"web-accesslog"},"data":{"protocol":"GET","srcip":"192.168.56.66","id":"304","url":"/"},"location":"/var/log/apache2/access_log"},"program":"active-response/bin/firewall-drop"}},"location":"/Library/Ossec/logs/active-responses.log"}
```
#### Alert when unblocking a malicious actor 
```vim
{"timestamp":"2022-09-17T14:21:10.695-0500","rule":{"level":3,"description":"Host Unblocked by firewall-drop Active Response","id":"652","firedtimes":5,"mail":false,"groups":["ossec","active_response"],"pci_dss":["11.4"],"gpg13":["4.13"],"gdpr":["IV_35.7.d"],"nist_800_53":["SI.4"],"tsc":["CC6.1","CC6.8","CC7.2","CC7.3","CC7.4"]},"agent":{"id":"006","name":"Vagrants-MacBook-Pro-Bck.local","ip":"FE80:0000:0000:0000:1876:67B9:B5D4:0765"},"manager":{"name":"thejbte-ASUS-TUF-A15"},"id":"1663442470.1317518","full_log":"2022/09/17 14:21:09 active-response/bin/firewall-drop: {\"version\":1,\"origin\":{\"name\":\"node01\",\"module\":\"wazuh-execd\"},\"command\":\"delete\",\"parameters\":{\"extra_args\":[],\"alert\":{\"timestamp\":\"2022-09-17T14:20:08.552-0500\",\"rule\":{\"level\":10,\"description\":\"IP address found in AlienVault reputation database.\",\"id\":\"100100\",\"firedtimes\":4,\"mail\":false,\"groups\":[\"attack\"]},\"agent\":{\"id\":\"006\",\"name\":\"Vagrants-MacBook-Pro-Bck.local\",\"ip\":\"FE80:0000:0000:0000:1876:67B9 [...]

2022-09-19 17:40 UTC, TomasTurina requested changes

2022-09-19 17:40 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> + }
Always add a new line at the end of the file.

2022-09-19 17:40 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +    	    fprintf(fp, "%s\n", cmd);
```suggestion
            fprintf(fp, "%s\n", cmd);
```

2022-09-19 17:40 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +	        retVal = 1;
```suggestion
            retVal = 1;
```

2022-09-19 17:40 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +    if ( str_pattern_1 != NULL) {
```suggestion
    if (str_pattern_1 != NULL) {
```

2022-09-19 17:40 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +    if ( pos != NULL) {
```suggestion
    if (pos != NULL) {
```

2022-09-19 17:40 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +            if (pos && sscanf(pos, buffer /*"%*s %7s"*/, state) == 1 ) {
```suggestion
            if (pos && sscanf(pos, buffer /*"%*s %7s"*/, state) == 1) {
```

2022-09-19 17:40 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +            snprintf(buffer, OS_MAXSTR -1 , "%%*s %%%lds",strlen(str_pattern_2));
```suggestion
            snprintf(buffer, OS_MAXSTR -1 , "%%*s %%%lds", strlen(str_pattern_2));
```

2022-09-19 17:40 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +
Remove blank space

2022-09-19 17:40 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +                int retVal = 0;
You are not using this result anywhere.

2022-09-19 17:40 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +                if (exec_cmd4[0] && strcmp(exec_cmd4[0], PFCTL) == 0) {
When will this code executed? At this point, `exec_cmd4` will always be NULL.

2022-09-19 17:40 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +                if (exec_cmd5[0] && strcmp(exec_cmd5[0], PFCTL) == 0) {
Same here.

2022-09-19 17:40 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +            if ( 0 == isFirstEntryEnabledFirewall || (0 == isEnabledFirewallPrevious && 1 == isEnabledFirewall)){
I think these static variables won't persist between script executions.

2022-09-28 22:27 UTC, TomasTurina requested changes

2022-09-28 22:27 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +                (void)write_cmd_to_file(RCCONF, "pf_enable=\"YES\"" "\n" "pf_rules=\"/etc/pf.conf\"" "\n" "pflog_enable=\"YES\"" "\n" "pflog_logfile=\"/var/log/pflog\"");
Why don't you verify the return value?

2022-09-28 22:27 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +                (void)write_cmd_to_file(PFCTL_RULES, log_msg);
Why don't you verify the return value?

2022-09-28 22:27 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +                (void)write_cmd_to_file(RCCONF, "pf_enable=\"YES\"" "\n" "pf_rules=\"/etc/pf.conf\"" "\n" "pflog_enable=\"YES\"" "\n" "pflog_logfile=\"/var/log/pflog\"");
`"pf_enable=\"YES\"\npf_rules=\"/etc/pf.conf\"\npflog_enable=\"YES\"\npflog_logfile=\"/var/log/pflog\""`

2022-09-28 22:27 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +                    wfd = wpopenv(PFCTL, exec_cmd4, W_BIND_STDOUT);
Maybe `LAUNCHCTL`? Will this work in FreeBSD and OpenBSD?

2022-09-28 22:27 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
>                  return OS_SUCCESS;
Table is created but AR is not executed.

2022-09-28 22:27 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +                if (( 0 == isEnabledFirewall)) {
```suggestion
                if (0 == isEnabledFirewall) {
```

2022-09-28 22:27 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> + * @example retVal = isEnabledFromPattern(output_buf, "Status: ", "Enabled");
This example is confusing and English should be improved.

2022-09-28 22:27 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +            snprintf(buffer, OS_MAXSTR -1 , "%%*s %%%lds",strlen(str_pattern_2));
```suggestion
            snprintf(buffer, OS_MAXSTR -1 , "%%*s %%%lds", strlen(str_pattern_2));
```

2022-09-28 22:27 UTC, TomasTurina commented on src/active-response/firewalls/pf.c
> +            if (pos && sscanf(pos, buffer /*"%*s %7s"*/, state) == 1) {
Why do you check `pos` not null again?

2022-10-14 18:07 UTC, TomasTurina approved these changes

2022-10-18 13:31 UTC, TomasTurina submitted a review, later dismissed

2023-01-02 21:43 UTC, TomasTurina approved these changes

2023-02-10 15:01 UTC, TomasTurina approved these changes

2023-03-01 15:32 UTC, damarisg commented
## QA review
- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3330
- **Comments**:  https://github.com/wazuh/wazuh-qa/issues/3330#issuecomment-1450333730

2023-03-01 16:42 UTC, merged