Take *region* from *.aws/config* file for AWS cloudwatch
wazuh/wazuh pull request #14993
Opened 2022-09-22 18:51 UTC by nico-stefani

|Related issue|
|---|
|#12937|

## Description

This PR closes #12937. Take account of `region` field configured in `~/.aws/config` for a profile and use to filter cloudwatch log groups.

## Tests

### Unittest

```bash
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.9.9, pytest-5.4.3, py-1.11.0, pluggy-0.13.1
rootdir: /home/nstefani/git/wazuh
plugins: tavern-1.2.2, aiohttp-0.3.0, trio-0.7.0, cov-3.0.0, html-2.1.1, asyncio-0.15.1, metadata-2.0.1
collected 38 items

wodles/aws/tests/test_aws.py ......................................                                                                                                                                           [100%]

================================================================================================ 38 passed in 0.25s =================================================================================================
```

### Manual

Having the `region` configured in `~/.aws/config`, I ran the next tests:

```
[dev]
region = us-east-1
```

**Execute the module with `-r` option**
The region should be taken from the parameters

```bash

```

**Execute the module without specify the `-r` option**
The `region` should be taken from `~/.aws/config` file

```bash

```

**Execute the module with none of the above**
Remove the `~/.aws/config` file and don't use the `-r` option, the module should use the default regions.

**Execute the module specifying a different profile**
Using a different profile that hasn't configured a `region`, the module should use the default regions.

2022-09-22 22:33 UTC, nico-stefani commented
# Issue Update

**Execute the module with `-r` option** :green_circle:

The region should be taken from the parameters

<details><summary>Command Output</summary>

    root@wazuh:/# /var/ossec/wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile dev --aws_log_groups /aws/ecr/image-scan-findings/framework-test-ecr-repository -s 2022-SEP-19 -r us-east-2 -d2
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-2" region.
    DEBUG: Found configuration for connection retries in /root/.aws/config
    DEBUG: only logs: 1663545600000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "/aws/ecr/image-scan-findings/framework-test-ecr-repository" log group
    DEBUG: Found "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Getting data from DB for log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository" using token "None", start_time "1663545600000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "{     "name": "CVE-2021-33910",     "description": "basic/unit-name.c in systemd prior to 246.15, 247.8, 248.5, and 249.1 has a Memory Allocation with an Excessive Size Value (involving strdupa and alloca for a pathname controlled by a local attacker) that results in an operating system crash.",     "uri": "http://people.ubuntu.com/~ubuntu-security/cve/CVE-2021-33910",     "severity": "HIGH",     "attributes": [         {             "key": "package_version",             "value": "245.4-4ubuntu3.4"         },         {             "key": "package_name",             "value": "systemd"         },         {             "key": "CVSS2_VECTOR",             "value": "AV:L/AC:L/Au:N/C:N/I:N/A:C"         },         {             "key": "CVSS2_SCORE",             "value": "4.9"         }     ] }"
    DEBUG: Getting CloudWatch logs from log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository" using token "f/37105595840638286068215413387279960156045623484288925696/s", start_time "1663545600000" and end_time "None"
    DEBUG: Saving data for log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository" and log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z".
    DEBUG: The saved values are "{'token': 'f/37105595840649436438803180316044876835276859734463840255/s', 'start_time': 1663545600000, 'end_time': 1663872463019}"
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "/aws/ecr/image-scan-findings/framework-test-ecr-repository" log group
    DEBUG: Found "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: committing changes and closing the DB

</details>

*Conclusion*

The module works fine, only gets logs from region `us-east-2`.

2022-09-22 22:34 UTC, nico-stefani commented
# Issue Update

**Execute the module without specify the `-r` option**

The `region` should be taken from `~/.aws/config` file

<details><summary>Command Output</summary>

    root@wazuh:/# /var/ossec/wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile dev --aws_log_groups /aws/ecr/image-scan-findings/framework-test-ecr-repository -s 2022-SEP-19 -d2
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Found configuration for connection retries in /root/.aws/config
    DEBUG: only logs: 1663545600000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "/aws/ecr/image-scan-findings/framework-test-ecr-repository" log group
    DEBUG: Found "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-last_test-c27a0d7ce038dad9c9e6e4f4bdbfbbf4974319e0a923b9d7860918b7457516f3-2022-09-19T12-30-25Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-latest-326fe221243c22c432750dfc87af36eb835e4d3701424bdbdec0877b33e21837-2022-09-13T14-23-44Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-latest-863b02afb833d7171281191321adfa65140455c95c17a3259d00747282fc56df-2022-09-19T11-49-40Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-latest-e8ebc87a5d521420f3276c05e87742bd3567898f273d199253c2b9cb645d47b9-2022-09-08T18-26-50Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-last_test-c27a0d7ce038dad9c9e6e4f4bdbfbbf4974319e0a923b9d7860918b7457516f3-2022-09-19T12-30-25Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-latest-326fe221243c22c432750dfc87af36eb835e4d3701424bdbdec0877b33e21837-2022-09-13T14-23-44Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-latest-863b02afb833d7171281191321adfa65140455c95c17a3259d00747282fc56df-2022-09-19T11-49-40Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-latest-e8ebc87a5d521420f3276c05e87742bd3567898f273d199253c2b9cb645d47b9-2022-09-08T18-26-50Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-last_test-c27a0d7ce038dad9c9e6e4f4bdbfbbf4974319e0a923b9d7860918b7457516f3-2022-09-19T12-30-25Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-latest-326fe221243c22c432750dfc87af36eb835e4d3701424bdbdec0877b33e21837-2022-09-13T14-23-44Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-latest-863b02afb833d7171281191321adfa65140455c95c17a3259d00747282fc56df-2022-09-19T11-49-40Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-latest-e8ebc87a5d521420f3276c05e87742bd3567898f273d199253c2b9cb645d47b9-2022-09-08T18-26-50Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-last_test-c27a0d7ce038dad9c9e6e4f4bdbfbbf4974319e0a923b9d7860918b7457516f3-2022-09-19T12-30-25Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-latest-326fe221243c22c432750dfc87af36eb835e4d3701424bdbdec0877b33e21837-2022-09-13T14-23-44Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-latest-863b02afb833d7171281191321adfa65140455c95c17a3259d00747282fc56df-2022-09-19T11-49-40Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-latest-e8ebc87a5d521420f3276c05e87742bd3567898f273d199253c2b9cb645d47b9-2022-09-08T18-26-50Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Getting data from DB for log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository" using token "None", start_time "1663545600000" and end_time "None"
    DEBUG: Saving data for log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository" and log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z".
    DEBUG: The saved values are "{'token': 'f/37098306551747894964959186686873945526709611589135204351/s', 'start_time': 1663545600000, 'end_time': 1663545600000}"
    DEBUG: Getting data from DB for log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository" using token "None", start_time "1663545600000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "{"name": "CVE-2021-33910", "description": "basic/unit-name.c in systemd prior to 246.15, 247.8, 248.5, and 249.1 has a Memory Allocation with an Excessive Size Value (involving strdupa and alloca for a pathname controlled by a local attacker) that results in an operating system crash.", "uri": "http://people.ubuntu.com/~ubuntu-security/cve/CVE-2021-33910", "severity": "HIGH", "attributes": [{"key": "package_version", "value": "245.4-4ubuntu3.4"}, {"key": "package_name", "value": "systemd"}, {"key": "CVSS2_VECTOR", "value": "AV:L/AC:L/Au:N/C:N/I:N/A:C"}, {"key": "CVSS2_SCOR [...]

2022-09-22 22:35 UTC, nico-stefani commented
**Execute the module with none of the above** :green_circle:

Remove the `~/.aws/config` file and don't use the `-r` option, the module should use the default regions.

<details><summary>Command Output</summary>

    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Warning: No regions were specified, trying to get events from all regions
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: only logs: 1663545600000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "/aws/ecr/image-scan-findings/framework-test-ecr-repository" log group
    DEBUG: Found "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-last_test-c27a0d7ce038dad9c9e6e4f4bdbfbbf4974319e0a923b9d7860918b7457516f3-2022-09-19T12-30-25Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-latest-326fe221243c22c432750dfc87af36eb835e4d3701424bdbdec0877b33e21837-2022-09-13T14-23-44Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-latest-863b02afb833d7171281191321adfa65140455c95c17a3259d00747282fc56df-2022-09-19T11-49-40Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-latest-e8ebc87a5d521420f3276c05e87742bd3567898f273d199253c2b9cb645d47b9-2022-09-08T18-26-50Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-last_test-c27a0d7ce038dad9c9e6e4f4bdbfbbf4974319e0a923b9d7860918b7457516f3-2022-09-19T12-30-25Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-latest-326fe221243c22c432750dfc87af36eb835e4d3701424bdbdec0877b33e21837-2022-09-13T14-23-44Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-latest-863b02afb833d7171281191321adfa65140455c95c17a3259d00747282fc56df-2022-09-19T11-49-40Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-latest-e8ebc87a5d521420f3276c05e87742bd3567898f273d199253c2b9cb645d47b9-2022-09-08T18-26-50Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-last_test-c27a0d7ce038dad9c9e6e4f4bdbfbbf4974319e0a923b9d7860918b7457516f3-2022-09-19T12-30-25Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-latest-326fe221243c22c432750dfc87af36eb835e4d3701424bdbdec0877b33e21837-2022-09-13T14-23-44Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-latest-863b02afb833d7171281191321adfa65140455c95c17a3259d00747282fc56df-2022-09-19T11-49-40Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-latest-e8ebc87a5d521420f3276c05e87742bd3567898f273d199253c2b9cb645d47b9-2022-09-08T18-26-50Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-last_test-c27a0d7ce038dad9c9e6e4f4bdbfbbf4974319e0a923b9d7860918b7457516f3-2022-09-19T12-30-25Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-latest-326fe221243c22c432750dfc87af36eb835e4d3701424bdbdec0877b33e21837-2022-09-13T14-23-44Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-latest-863b02afb833d7171281191321adfa65140455c95c17a3259d00747282fc56df-2022-09-19T11-49-40Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-latest-e8ebc87a5d521420f3276c05e87742bd3567898f273d199253c2b9cb645d47b9-2022-09-08T18-26-50Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Getting data from DB for log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository" using token "None", start_time "1663545600000" and end_time "None"
    DEBUG: Saving data for log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository" and log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z".
    DEBUG: The saved values are "{'token': 'f/37098306551747894964959186686873945526709611589135204351/s', 'start_time': 1663545600000, 'end_time': 1663545600000}"
    DEBUG: Getting data from DB for log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository" using token "None", start_time "1663545600000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "{"name": "CVE-2021-33910", "description": "basic/unit-name.c in systemd prior to 246.15, 247.8, 248.5, and 249.1 has a Memory Allocation with an Excessive Size Value (involving strdupa and alloca for a pathname controlled by a local attacker) that results in an operating system crash.", "uri": "http://people.ubuntu.com/~ubuntu-security/cve/CVE-2021-33910", "severity": "HIGH", "attributes": [{"key": "package_version", "value": "245.4-4ubuntu3.4"}, {"key": "package_name", "value": "systemd"}, {"key": "CVSS2_VECTOR", "value": "AV:L/AC:L/Au:N/C:N/I:N/A:C"}, {"key": "CVSS2_SCORE", "value": "4.9"}]}"
    DEBUG: Getting [...]

2022-09-22 22:36 UTC, nico-stefani commented
# Issue Update

**Execute the module specifying a different profile** :green_circle:

Using a different profile that hasn't configured a `region`, the module should use the default regions.

<details><summary>Command Output</summary>

    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Warning: No regions were specified, trying to get events from all regions
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Found configuration for connection retries in /root/.aws/config
    DEBUG: only logs: 1663545600000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "/aws/ecr/image-scan-findings/framework-test-ecr-repository" log group
    DEBUG: Found "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-last_test-c27a0d7ce038dad9c9e6e4f4bdbfbbf4974319e0a923b9d7860918b7457516f3-2022-09-19T12-30-25Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-latest-326fe221243c22c432750dfc87af36eb835e4d3701424bdbdec0877b33e21837-2022-09-13T14-23-44Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-latest-863b02afb833d7171281191321adfa65140455c95c17a3259d00747282fc56df-2022-09-19T11-49-40Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-latest-e8ebc87a5d521420f3276c05e87742bd3567898f273d199253c2b9cb645d47b9-2022-09-08T18-26-50Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "INFORMATIONAL-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-last_test-c27a0d7ce038dad9c9e6e4f4bdbfbbf4974319e0a923b9d7860918b7457516f3-2022-09-19T12-30-25Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-latest-326fe221243c22c432750dfc87af36eb835e4d3701424bdbdec0877b33e21837-2022-09-13T14-23-44Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-latest-863b02afb833d7171281191321adfa65140455c95c17a3259d00747282fc56df-2022-09-19T11-49-40Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-latest-e8ebc87a5d521420f3276c05e87742bd3567898f273d199253c2b9cb645d47b9-2022-09-08T18-26-50Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "LOW-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-last_test-c27a0d7ce038dad9c9e6e4f4bdbfbbf4974319e0a923b9d7860918b7457516f3-2022-09-19T12-30-25Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-latest-326fe221243c22c432750dfc87af36eb835e4d3701424bdbdec0877b33e21837-2022-09-13T14-23-44Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-latest-863b02afb833d7171281191321adfa65140455c95c17a3259d00747282fc56df-2022-09-19T11-49-40Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-latest-e8ebc87a5d521420f3276c05e87742bd3567898f273d199253c2b9cb645d47b9-2022-09-08T18-26-50Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "MEDIUM-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-last_test-c27a0d7ce038dad9c9e6e4f4bdbfbbf4974319e0a923b9d7860918b7457516f3-2022-09-19T12-30-25Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-latest-326fe221243c22c432750dfc87af36eb835e4d3701424bdbdec0877b33e21837-2022-09-13T14-23-44Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-latest-863b02afb833d7171281191321adfa65140455c95c17a3259d00747282fc56df-2022-09-19T11-49-40Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-latest-e8ebc87a5d521420f3276c05e87742bd3567898f273d199253c2b9cb645d47b9-2022-09-08T18-26-50Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Found "SUMMARY-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" log stream in /aws/ecr/image-scan-findings/framework-test-ecr-repository
    DEBUG: Getting data from DB for log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository" using token "None", start_time "1663545600000" and end_time "None"
    DEBUG: Saving data for log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository" and log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2021-11-02T10-20-28Z".
    DEBUG: The saved values are "{'token': 'f/37098306551747894964959186686873945526709611589135204351/s', 'start_time': 1663545600000, 'end_time': 1663545600000}"
    DEBUG: Getting data from DB for log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "HIGH-ubuntu-test-e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c-2022-09-19T12-25-49Z" in log group "/aws/ecr/image-scan-findings/framework-test-ecr-repository" using token "None", start_time "1663545600000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "{"name": "CVE-2021-33910", "description": "basic/unit-name.c in systemd prior to 246.15, 247.8, 248.5, and 249.1 has a Memory Allocation with an Excessive Size Value (involving strdupa and alloca for a pathname controlled by a local attacker) that results in an operating system crash.", "uri": "http://people.ubuntu.com/~ubuntu-security/cve/CVE-2021-33910", "severity": "HIGH", "attributes": [{"key": "package_version", "value": "245.4-4ubuntu3.4"}, {"key": "package_name", "value": "systemd"}, {"key": "CVSS2_VECTOR", "value": "AV:L/AC:L/Au:N/C:N/I:N/A:C"}, {"key": "CVSS2_SCORE", "value": "4.9"}]}"
    DEBUG: [...]

2022-09-26 09:23 UTC, CarlosRS9 requested changes
When the AWS Profile is not specified by the user the module should try to read the `[default]` configuration

2022-09-26 14:20 UTC, CarlosRS9 approved these changes

2022-09-28 09:44 UTC, davidjiglesias approved these changes

2022-09-28 09:44 UTC, merged