Ubuntu Linux 20.04 rework
wazuh/wazuh pull request #15070
Opened 2022-10-04 17:17 UTC by 72nomada

|Related issue|
|---|
|#14690|

This PR will rebuild the current Ubuntu Linux 20.04 policy using the  CIS Ubuntu Linux 20.04 LTS Benchmark v1.1.0 - 03-31-2021

2022-10-04 17:29 UTC, 72nomada commented
Items ready for team review: 

| Id | Title | Team Review status |
|---|---|---|
| 1 | Initial Setup ||
| 1.1 | Filesystem Configuration  ||
| 1.1.1 | Disable unused filesystems ||
| 1.1.1.1 | Ensure mounting of cramfs filesystems is disabled (Automated)  ||
| 1.1.1.2 | Ensure mounting of freevxfs filesystems is disabled (Automated)  ||
| 1.1.1.3 | Ensure mounting of jffs2 filesystems is disabled (Automated) ||
| 1.1.1.4 | Ensure mounting of hfs filesystems is disabled (Automated)  ||
| 1.1.1.5 | Ensure mounting of hfsplus filesystems is disabled (Automated) ||
| 1.1.1.6 | Ensure mounting of squashfs filesystems is disabled (Manual)  ||
| 1.1.1.7 | Ensure mounting of udf filesystems is disabled (Automated) ||
| 1.1.2 | Ensure /tmp is configured (Automated)  ||
| 1.1.3 | Ensure nodev option set on /tmp partition (Automated)  ||
| 1.1.4 | Ensure nosuid option set on /tmp partition (Automated)  ||
| 1.1.5 | Ensure noexec option set on /tmp partition (Automated)  ||
| 1.1.6 | Ensure /dev/shm is configured (Automated)  ||
| 1.1.7 | Ensure nodev option set on /dev/shm partition (Automated)  ||
| 1.1.8 | Ensure nosuid option set on /dev/shm partition (Automated)  ||
| 1.1.9 | Ensure noexec option set on /dev/shm partition (Automated) ||
| 1.1.10 | Ensure separate partition exists for /var (Automated)  ||
| 1.1.11 | Ensure separate partition exists for /var/tmp (Automated)||
| 1.1.12 | Ensure /var/tmp partition includes the nodev option (Automated)  ||
| 1.1.13 | Ensure /var/tmp partition includes the nosuid option (Automated)  ||
| 1.1.14 | Ensure /var/tmp partition includes the noexec option (Automated)||
| 1.1.15 | Ensure separate partition exists for /var/log (Automated)||

2022-10-05 19:24 UTC, fabamatic submitted a review, later dismissed

2022-10-05 19:24 UTC, fabamatic commented on ruleset/sca/ubuntu/cis_ubuntu20-04.yml
> +  - id: 19021
Repeated id with 1.1.17

2022-10-05 19:25 UTC, 72nomada commented on ruleset/sca/ubuntu/cis_ubuntu20-04.yml
> +      - "c:modprobe -n -v cramfs -> r:^install /bin/true|^install /bin/false"
Both true and false are valid options

2022-10-05 19:50 UTC, fabamatic commented on ruleset/sca/ubuntu/cis_ubuntu20-04.yml
>      condition: all
Condition may be any instead of all?

2022-10-05 19:50 UTC, fabamatic commented on ruleset/sca/ubuntu/cis_ubuntu20-04.yml
>      condition: all
Condition may be any instead of all?

2022-10-12 17:31 UTC, 72nomada commented
|Check ID | Check Name | implemented | Ready for review |
|---|---|---|---|---|
|1.2 | Configure Software Updates  | ⚫  | |  
|1.2.1 | Ensure package manager repositories are configured (Manual)  | 🔴  |Not implemented |  
|1.2.2 | Ensure GPG keys are configured (Manual)  | 🔴  | Not implemented |  
|1.3 | Filesystem Integrity Checking | ⚫   | |  
|1.3.1 | Ensure AIDE is installed (Automated)  | 🟢  | |  
|1.3.2 | Ensure filesystem integrity is regularly checked (Automated)  |  | |  
|1.4 | Secure Boot Settings  |  | |  
|1.4.1 | Ensure permissions on bootloader config are not overridden (Automated) |  | |  
|1.4.2 | Ensure bootloader password is set (Automated) |  | |  
|1.4.3 | Ensure permissions on bootloader config are configured (Automated) |  | |  
|1.4.4 | Ensure authentication required for single user mode (Automated)  |  | |  
|1.5 | Additional Process Hardening  |  | |  
|1.5.1 | Ensure XD/NX support is enabled (Manual) |  | |  
|1.5.2 | Ensure address space layout randomization (ASLR) is enabled (Automated)  |  | |  
|1.5.3 | Ensure prelink is not installed (Automated) |  | |  
|1.5.4 | Ensure core dumps are restricted (Automated) |  | |

2022-10-20 11:40 UTC, jmv74211 commented
## QA report

The corresponding checks between 1 and 1.9 have been tested and approved (after making the modifications requested in the review).

- https://github.com/wazuh/wazuh-qa/issues/3431
- https://github.com/wazuh/wazuh-qa/issues/3432
- https://github.com/wazuh/wazuh-qa/issues/3433

The rest of the checks will be reviewed as they are implemented, with an estimated date of October 28th.

2022-10-24 21:19 UTC, fabamatic commented on ruleset/sca/ubuntu/cis_ubuntu20-04.yml
>      com
Shouldn't it be:
`f:/boot/grub/grub.cfg -> r:^\s*linux && r:audit=1'` ?

2022-10-27 09:22 UTC, jmv74211 commented
## QA report

The corresponding checks between 3.5 and 4.4 have been tested and approved (after making the modifications requested in the review).

- https://github.com/wazuh/wazuh-qa/issues/3436
- https://github.com/wazuh/wazuh-qa/issues/3438

2022-10-28 09:05 UTC, jmv74211 commented
## QA report

The corresponding checks between 5 to 5.3.22 have been tested and approved (after making the modifications requested in the review).

- https://github.com/wazuh/wazuh-qa/issues/3439

2022-11-02 17:37 UTC, fabamatic requested changes

2022-11-03 11:53 UTC, jmv74211 commented
## QA report

The [Ubuntu Linux 20.04 SCA Policy rework end to end test](https://github.com/wazuh/wazuh-qa/issues/3520) has passed successfully.

2022-11-09 11:34 UTC, jmv74211 approved these changes
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3391
- **Comments**:  https://github.com/wazuh/wazuh-qa/issues/3391#issuecomment-1308615655

2022-11-09 11:34 UTC, merged