Fix vulnerability API integration tests' healthcheck
wazuh/wazuh pull request #15194
Opened 2022-10-19 11:48 UTC by mcarmona99

|Related issue|
|---|
| https://github.com/wazuh/wazuh/issues/15192 |

## Description

This PR closes #15192 

In this pull request, I have updated the vulnerability API integration test health check.

Now the containers are healthy before the 20 minutes mentioned in the related issue as the health check is working properly.

```
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS                   PORTS                                           NAMES
bcb8efe2b962   integration_test_wazuh-agent_old   "/scripts/entrypoint…"   6 minutes ago   Up 6 minutes (healthy)                                                   env_wazuh-agent8_1
0d06cdfadc1f   integration_test_wazuh-agent_old   "/scripts/entrypoint…"   6 minutes ago   Up 6 minutes (healthy)                                                   env_wazuh-agent7_1
fcb231483c5c   integration_test_wazuh-agent_old   "/scripts/entrypoint…"   6 minutes ago   Up 6 minutes (healthy)                                                   env_wazuh-agent6_1
4151ac2f82d5   integration_test_wazuh-agent_old   "/scripts/entrypoint…"   6 minutes ago   Up 6 minutes (healthy)                                                   env_wazuh-agent5_1
20703837cab6   integration_test_wazuh-agent       "/scripts/entrypoint…"   6 minutes ago   Up 6 minutes (healthy)                                                   env_wazuh-agent4_1
7be80a974562   integration_test_wazuh-agent       "/scripts/entrypoint…"   6 minutes ago   Up 6 minutes (healthy)                                                   env_wazuh-agent3_1
942947d0abdf   integration_test_wazuh-agent       "/scripts/entrypoint…"   6 minutes ago   Up 6 minutes (healthy)                                                   env_wazuh-agent2_1
90a021531ea9   integration_test_wazuh-agent       "/scripts/entrypoint…"   6 minutes ago   Up 6 minutes (healthy)                                                   env_wazuh-agent1_1
1e02fec25841   integration_test_nginx-lb          "/scripts/entrypoint…"   6 minutes ago   Up 6 minutes             80/tcp                                          env_nginx-lb_1
7d734701ab8b   integration_test_wazuh-manager     "/scripts/entrypoint…"   6 minutes ago   Up 6 minutes (healthy)   0.0.0.0:55000->55000/tcp, :::55000->55000/tcp   env_wazuh-master_1
0a00cf468e47   integration_test_wazuh-manager     "/scripts/entrypoint…"   6 minutes ago   Up 6 minutes (healthy)                                                   env_wazuh-worker1_1
9223eac02a80   integration_test_wazuh-manager     "/scripts/entrypoint…"   6 minutes ago   Up 6 minutes (healthy)                                                   env_wazuh-worker2_1
```
                                                                                                       
                     
```                                                                                  
$ python3 run_tests.py -l test_vuln -m cluster
Collected tests [1]:
test_vulnerability_endpoints.tavern.yaml

test_vulnerability_endpoints.tavern.yaml - Cluster environment 
	 3 passed, 4 warnings
```

2022-10-24 08:49 UTC, vicferpoy requested changes

2022-10-24 08:49 UTC, vicferpoy commented on api/test/integration/env/configurations/vulnerability/manager/healthcheck/healthcheck.py
> +from healthcheck_utils import BASE_URL, check, get_login_header, get_manager_health_base, get_response, LOGIN_URL
About the constants, does this mean that it was broken? I don't see changes on any other module and you are importing a "different" object.

2022-10-24 08:49 UTC, vicferpoy commented on api/test/integration/env/configurations/vulnerability/manager/healthcheck/healthcheck.py
> +        response = get_response('GET', f'{BASE_URL}/agents?select=id,manager&status={status}',
Be consistent with quotation, please. Also, remember to use double quotation marks on f-strings.

2022-10-25 09:00 UTC, davidjiglesias approved these changes

2022-10-25 09:01 UTC, vicferpoy approved these changes
LGTM

2022-10-25 09:01 UTC, merged