Fix analysisd segfault fired by regex capture group
wazuh/wazuh pull request #15190
Opened 2022-10-18 23:11 UTC by cborla

|Related issue|Manual Testing|
|---|---|
|[Segmentation fault in Analysisd #14923](https://github.com/wazuh/wazuh/issues/14923#event-7602313521)|https://github.com/wazuh/wazuh-qa/issues/3427|

## Description
The goal of this PR is avoid analysisd segfault, it occurs under very specific conditions, it requires revert pcre2 capture groups vector increase, and replace the capture group counting by `regex_match->sub_strings` array, to keep OS_IsValidIP function validating any IPv4 or IPv6 with or without prefix or netmask.

- [x] Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Package installation

- Memory tests for Linux
  - [x] Valgrind (memcheck and descriptor leaks check)

2022-10-19 16:00 UTC, TomasTurina requested changes
What about the regex in `OS_GetIPv4FromIPv6`?

2022-10-20 13:18 UTC, TomasTurina commented on src/shared/validate_op.c
> +                    for (unsigned int a = 0; regex_match->sub_strings[a] != NULL; a++, sub_strings_num++);
```suggestion
                    for (sub_strings_num = 0; regex_match->sub_strings[sub_strings_num] != NULL; sub_strings_num++);
```

2022-10-20 14:08 UTC, TomasTurina approved these changes

2022-10-20 14:10 UTC, TomasTurina approved these changes
LGTM!

2022-10-20 18:16 UTC, juliancnn requested changes

2022-10-20 18:16 UTC, juliancnn commented on src/shared/validate_op.c
>      }
Maybe: 
```cpp
OSRegex_free_regex_matching(regex_match);
os_free(regex_match)
```
Or change regex_match to the stack and not the heap, and:
```cpp
OSRegex_free_regex_matching(&regex_match);
```

2022-10-20 21:07 UTC, jnasselle approved these changes

2022-10-21 08:01 UTC, juliancnn approved these changes
LGTM!

2022-10-28 15:30 UTC, jmv74211 approved these changes
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3427
- **Comments**:  https://github.com/wazuh/wazuh-qa/issues/3427#issuecomment-1294757248

2022-10-28 18:00 UTC, merged