Disables Restart Manager and closes GUI in Wazuh Agent MSI installation and upgrade
wazuh/wazuh pull request #15207
Opened 2022-10-21 11:34 UTC by verdx

|Related issue|
|---|
|https://github.com/wazuh/wazuh-packages/issues/1485|

## Description

This PR modifies the MSI Installer creator `wazuh-installer.wsx`. It disables the use of the Restart Manager when open applications are in conflict with the installation and it closes the Wazuh Agent GUI if the message urging the user to close it is ignored, solving the problem explained in issue https://github.com/wazuh/wazuh-packages/issues/1485.

## Logs/Alerts example

Logs can be found in the issue.

## Tests

All tests can be found in the issue.

2022-10-24 16:34 UTC, alberpilot requested changes
Minor changes. Additionally, please add tests for Windows server 2012R2 and Windows XP.

2022-10-24 16:34 UTC, alberpilot commented on src/win32/wazuh-installer.wxs
> +        <!-- Close the Wazuh Agent GUI -->
```suggestion
        <!-- Close the Wazuh agent GUI -->

```

2022-10-25 08:42 UTC, verdx commented
> Minor changes. Additionally, please add tests for Windows server 2012R2 and Windows XP.

New tests:
- Windows Server 2012 R2
 - [ ] Fresh installation
 - [ ] Upgrade without open GUI
 - [ ] Upgrade with open GUI
 - Windows XP
 - [ ] Fresh installation
 - [ ] Upgrade without open GUI
 - [ ] Upgrade with open GUI

2022-10-25 10:34 UTC, verdx commented
All tests have been repeated, as the first ones weren't done on the final branch, which had an error, but in the testing one that was erased.

More investigation has been done on removing the usage of the Restart Manager. Based primarily on these links:
- https://learn.microsoft.com/en-us/windows/win32/rstmgr/restart-manager-portal
- https://learn.microsoft.com/en-us/windows/win32/rstmgr/about-restart-manager
- https://learn.microsoft.com/en-us/windows/win32/rstmgr/using-restart-manager
Here we can see the Restart Manager detects apps, services and file usages that are changed in the installation or could somewhat prove conflictful. This is done automatically, but it doesn't change anything to doing it manually. In our case, we close manually both the service and the GUI, the only possible apps that could create a conflict.
No problem arising from disabling the Restart Manager has been found after searching on webs such as StackOverflow.

2022-10-27 08:15 UTC, alberpilot approved these changes

2022-10-27 08:19 UTC, DFolchA approved these changes
lgtm

2022-11-11 10:50 UTC, jmv74211 approved these changes
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3512
- **Comments**:  https://github.com/wazuh/wazuh-qa/issues/3512#issuecomment-1311529231

2022-11-11 11:58 UTC, merged