Check if the password is empty
wazuh/wazuh pull request #15709
Opened 2022-12-16 19:40 UTC by JoseMiguelGD

|Related issue|Manual Testing|
|---|---|
|https://github.com/wazuh/wazuh/issues/15230||

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2022-12-22 15:33 UTC, TomasTurina approved these changes

2022-12-22 17:27 UTC, thejbte submitted a review, later dismissed

2022-12-22 17:49 UTC, TomasTurina submitted a review, later dismissed

2022-12-23 15:27 UTC, TomasTurina requested changes

2022-12-23 15:27 UTC, TomasTurina commented on src/os_auth/main-server.c
> +            fseek(fp, 0, SEEK_END);
I'm not sure that doing this will allow later to read correctly this file. Please retest and try to find a different solution.

2022-12-29 13:45 UTC, TomasTurina submitted a review, later dismissed

2023-01-02 21:55 UTC, TomasTurina approved these changes

2023-03-02 16:24 UTC, damarisg approved these changes

2023-03-02 17:46 UTC, merged