Fix Rootcheck scan trying to read deleted files
wazuh/wazuh pull request #15719
Opened 2022-12-19 21:49 UTC by mateocervilla

|Related issue|
|---|
|Closes #8309|

## Description

This PR aims to fix a Rootcheck scan issue that occurs because before unmerging the merged.mg file, the files in the shared folder are removed and during that time, rootcheck might try to read them.

### Previous behavior

The client-agent receiver deletes all files in shared folder, then unmerges the merged.mg and creates the new files.

### Proposed behavior

The client-agent receiver unmerges the merged.mg and creates the new files with temp names, then renames these files with their original names and add them to the exclude list. After this, all files in the shared folder that are not in the exclude list are deleted.

## Tests

### 🟢 Create heavy files on the manager that are not on the agent and vice versa

2023-01-18 17:58 UTC, MarcelKemp requested changes

2023-01-18 17:58 UTC, MarcelKemp commented on src/client-agent/receiver.c
> +                                }
To improve these lines of code, let's use the `w_FreeArray` macro with the `IGNORE_LIST` array:
- `w_FreeArray(IGNORE_LIST);`

2023-01-20 12:36 UTC, MarcelKemp submitted a review, later dismissed

2023-01-20 23:08 UTC, MarcelKemp approved these changes

2023-02-07 10:25 UTC, jmv74211 approved these changes
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3694
- **Comments**:  https://github.com/wazuh/wazuh-qa/issues/3694#issuecomment-1419407718

2023-02-07 10:29 UTC, MarcelKemp approved these changes

2023-02-07 14:51 UTC, MarcelKemp approved these changes

2023-02-14 14:50 UTC, vikman90 submitted a review, later dismissed

2023-04-14 11:42 UTC, MarcelKemp approved these changes

2023-04-14 14:45 UTC, merged