Wildcard support in Windows registers
wazuh/wazuh pull request #15852
Opened 2023-01-09 20:51 UTC by GabrielEValenzuela

|Related issue|
|---|
|Closes #14321|

This PR attempts to provide wildcard support for windows logs, when adding any directory to FIM monitoring.

### Previous behavior

Previously, this option was not possible

### Proposed behavior

By parsing the path composition provided in the `osse.conf` file, the different parts of the path are split using the two wildcard options `*` or `?` as delimiters.
Subsequently, the Windows API is used, where the records of a root key and a sub key (possibly null) are listed and the new complete paths are assembled, which will then be monitored by FIM. It's important to clarify that this solution is **case sensitive.**

## Tests

### 🟢 Combine three possibles cases
#### Configuration

```xml
<windows_registry arch="both">HKEY_LOCAL_MACHINE\*\De?</windows_registry>
<windows_registry arch="both">HKEY_LOCAL_MACHINE\*\DE?</windows_registry>
<windows_registry arch="both">HKEY_CURRENT_USER\Software\*</windows_registry>
<windows_registry arch="both">HKEY_CURRENT_CONFIG\So?</windows_registry>
```

<details><summary><h5>🟢 Start agent with new feature</h5></summary>

```
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_LOCAL_MACHINE\*\De?' to 'HKEY_LOCAL_MACHINE\BCD00000000\Description' to monitor FIM events.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_LOCAL_MACHINE\*\De?' to 'HKEY_LOCAL_MACHINE\SYSTEM\MountedDevices' to monitor FIM events.
2023/01/09 13:29:04 wazuh-agent[12660] logcollector.c:222 at LogCollectorStart(): INFO: Windows version is 6.0 or newer. (Microsoft Windows 10 Pro [Ver: 10.0.19044.2364] - Wazuh v4.5.0).
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:637 at read_reg(): DEBUG: (6372): Wildcard configuration successfully completed.
2023/01/09 13:29:04 wazuh-agent[12660] logcollector.c:237 at LogCollectorStart(): DEBUG: Entering LogCollectorStart().
2023/01/09 13:29:04 wazuh-agent[12660] logcollector.c:279 at LogCollectorStart(): INFO: (1951): Analyzing event log: 'Application'.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:623 at read_reg(): DEBUG: (6370): Starting configuration for Windows registry wildcards.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_LOCAL_MACHINE\*\DE?' to 'HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION' to monitor FIM events.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_LOCAL_MACHINE\*\DE?' to 'HKEY_LOCAL_MACHINE\HARDWARE\DEVICEMAP' to monitor FIM events.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:637 at read_reg(): DEBUG: (6372): Wildcard configuration successfully completed.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:623 at read_reg(): DEBUG: (6370): Starting configuration for Windows registry wildcards.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_CURRENT_USER\Software\*' to 'HKEY_CURRENT_USER\Software\Console' to monitor FIM events.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_CURRENT_USER\Software\*' to 'HKEY_CURRENT_USER\Software\Control Panel' to monitor FIM events.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_CURRENT_USER\Software\*' to 'HKEY_CURRENT_USER\Software\Environment' to monitor FIM events.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_CURRENT_USER\Software\*' to 'HKEY_CURRENT_USER\Software\EUDC' to monitor FIM events.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_CURRENT_USER\Software\*' to 'HKEY_CURRENT_USER\Software\Keyboard Layout' to monitor FIM events.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_CURRENT_USER\Software\*' to 'HKEY_CURRENT_USER\Software\Printers' to monitor FIM events.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_CURRENT_USER\Software\*' to 'HKEY_CURRENT_USER\Software\Software' to monitor FIM events.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_CURRENT_USER\Software\*' to 'HKEY_CURRENT_USER\Software\System' to monitor FIM events.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:637 at read_reg(): DEBUG: (6372): Wildcard configuration successfully completed.
2023/01/09 13:29:04 sca[12660] wm_sca.c:151 at wm_sca_main(): INFO: Module started.
2023/01/09 13:29:04 wazuh-modulesd:agent-upgrade[12660] wm_agent_upgrade_agent.c:96 at wm_agent_upgrade_start_agent_module(): INFO: (8153): Module Agent Upgrade started.
2023/01/09 13:29:04 wazuh-agent[12660] notify.c:135 at run_notify(): DEBUG: Sending agent notification.
2023/01/09 13:29:04 sca[12660] wm_sca.c:158 at wm_sca_main(): INFO: No policies defined. Exiting.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:623 at read_reg(): DEBUG: (6370): Starting configuration for Windows registry wildcards.
2023/01/09 13:29:04 wazuh-agent[12660] syscheck-config.c:625 at read_reg(): DEBUG: (6371): Expanding entry 'HKEY_CURRENT_CONFIG\So?' to 'HKEY_CURRENT_CONFIG\Software' to monitor FIM events.
```
</details>
<details><summary><h5>🟢 Add new registry</h5></summary>

```
2023/01/09 14:47:46 wazuh-agent[9580] run_check.c:127 at send_syscheck_msg(): DEBUG: (6321): Sending FIM event: {"type":"event","data":{"path":"HKEY_CURRENT_CONFIG\\Software\\NEW_KEY","version":2,"mode":"scheduled","type":"added","arch":"[x64]","timestamp":1673297266,"attributes":{"type":"registry_key","perm":{"S-1-5-32-545":{"name":"Usuarios","allowed":["read_control","read_data","read_ea","write_ea"]},"S-1-5-32-544":{"name":"Administradores","allowed":["delete","read_control","write_dac","write_owner","read_data","write_data","append_data","read_ea","write_ea","execute"]},"S-1-5-18":{"name":"SYSTEM","allowed":["delete","read_control","write_dac","write_owner","read_data","write_data","append_data","read_ea","write_ea","execute"]},"S-1-3-0":{"name":"CREATOR OWNER","allowed":["delete","read_control","write_dac","write_owner","read_data","write_data","append_data","read_ea","write_ea","execute"]},"S-1-15-2-1":{"name":"ALL APPLICATION PACKAGES","allowed":["read_control","read_data","read_ea","write_ea"]},"S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681":{"allowed":["read_control","read_data","read_ea","write_ea"]}},"uid":"S-1-5-32-544","user_name":"Administradores","gid":"S-1-5-21-2535345508-762786813-1329944505-513","group_name":"Ninguno","mtime":1673297255,"checksum":"a2bdd12a4d134836bd767f83345275399ce2bc2c"}}}
2023/01/09 14:47:46 wazuh-agent[9580] run_check.c:127 at send_syscheck_msg(): DEBUG: (6321): Sending FIM event: {"type":"event","data":{"path":"HKEY_CURRENT_CONFIG\\Software\\NEW_KEY","version":2,"mode":"scheduled","type":"added","arch":"[x64]","value_name":"NEW_VALUE","timestamp":1673297266,"attributes":{"type":"registry_value","value_type":"REG_BINARY","size":0,"hash_md5":"d41d8cd98f00b204e9800998ecf8427e","hash_sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","hash_sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","checksum":"38fdd1d295687fa298dbda6732232ee58c309cb4"}}}
2023/01/09 14:47:48 wazuh-agent[9580] run_check.c:127 at send_syscheck_msg(): DEBUG: (6321): Sending FIM event: {"type":"event","data":{"path":"HKEY_CURRENT_CONFIG\\Software\\NEW_KEY","version":2,"mode":"scheduled","type":"added","arch":"[x32]","timestamp":1673297268,"attributes":{"type":"registry_key","perm":{"S-1-5-32-545":{"name":"Usuarios","allowed":["read_control","read_data","read_ea","write_ea"]},"S-1-5-32-544":{"name":"Administradores","al [...]

2023-02-09 17:31 UTC, GabrielEValenzuela commented on src/config/syscheck-config.c
>              //free(paths);
To delete

2023-02-09 17:31 UTC, GabrielEValenzuela commented on src/config/syscheck-config.c
> -                mdebug2(FIM_WILDCARDS_ADD_REGISTER, entry[i], *paths);
To kept in mdebug2

2023-02-09 17:32 UTC, GabrielEValenzuela commented on src/shared/syscheck_op.c
> +        //Usar strtok_r
To delete

2023-02-09 17:33 UTC, GabrielEValenzuela commented on src/shared/syscheck_op.c
> +
To delete

2023-03-13 22:05 UTC, lsayanes commented on src/shared/syscheck_op.c
> +    }
wrong indentation

2023-03-13 22:05 UTC, lsayanes commented on src/shared/syscheck_op.c
> +                    int path_length             = strlen(full_path);
extra space

2023-06-14 15:05 UTC, MarcelKemp commented on src/shared/syscheck_op.c
> +    if (path_len) {
```suggestion
    if (path_len > 0) {
```

2023-06-16 00:15 UTC, GabrielEValenzuela commented on src/shared/syscheck_op.c
> +    }
Nice idea !

2023-06-19 17:54 UTC, MarcelKemp submitted a review, later dismissed
LGTM!

2023-07-03 10:01 UTC, vikman90 requested changes
@GabrielEValenzuela @MarcelKemp I've found the following defect in the code:

```
** CID 321729:    (RESOURCE_LEAK)
/config/syscheck-config.c: 639 in read_reg()
/config/syscheck-config.c: 653 in read_reg()


________________________________________________________________________________________________________
*** CID 321729:    (RESOURCE_LEAK)
/config/syscheck-config.c: 639 in read_reg()
633                         dump_syscheck_registry(syscheck, *paths_wildcard, opts, restrict_key, restrict_value, recursion_level, tag, ARCH_32BIT, tmp_diff_size);
634                     } else {
635                         dump_syscheck_registry(syscheck, *paths_wildcard, opts, restrict_key, restrict_value, recursion_level, tag, arch, tmp_diff_size);
636                     }
637                     paths_wildcard++;
638                 }
>>>     CID 321729:    (RESOURCE_LEAK)
>>>     Overwriting "paths_wildcard" in "paths_wildcard = start_vector" leaks the storage that "paths_wildcard" points to.
639                 paths_wildcard = start_vector;
640                 free_strarray(paths_wildcard);
641                 mdebug1(FIM_WILDCARDS_REGISTERS_FINALIZE);
642             } else {
643                 /* Add new entry */
644                 if (arch == ARCH_BOTH) {
/config/syscheck-config.c: 653 in read_reg()
647                 } else {
648                     dump_syscheck_registry(syscheck, tmp_entry, opts, restrict_key, restrict_value, recursion_level, tag, arch, tmp_diff_size);
649                 }
650             }
651             /* Next entry */
652             free(entry[i]);
>>>     CID 321729:    (RESOURCE_LEAK)
>>>     Variable "paths_wildcard" going out of scope leaks the storage it points to.
653         }
654         free(entry);
655     
656         retval = 1;
657     clean_reg:
658         os_free(tag);
```

Please review it and fix that if applicable.
Cheers!

2023-07-13 11:52 UTC, MarcelKemp approved these changes

2023-07-17 11:11 UTC, vikman90 approved these changes

2023-07-18 08:55 UTC, merged