15851 engine sophos decoder firewall
wazuh/wazuh pull request #16047
Opened 2023-01-30 21:53 UTC by NahuFigueroa97

|Related issue|
|---|
|#15851|

## Description

With the aim of expanding the coverage of the decoders, this PR adds a decoder for Sophos/Ldp.

## Configuration options

Validate the new decoder:
- ./build/main catalog validate decoder/sophos-ldp/0 < /home/vagrant/engine/wazuh/src/engine/ruleset/decoders/sophos/ldp.yml

Create decoder:
- ./build/main  catalog create decoder < /home/vagrant/engine/wazuh/src/engine/ruleset/decoders/sophos/ldp.yml

Update environment
- ./build/main catalog update environment/wazuh/0 < /home/vagrant/engine/wazuh/src/engine/ruleset/environments/wazuh-environment.yml

Test new decoder
- ./build/main test -q 1

## Logs/Alerts example

- <30>device="SFW" date=2020-05-18 time=14:38:55 timezone="CEST" device_name="XG230" device_id=1234567890123456 log_id=020804407002 log_type="IDP" log_component="Signatures" log_subtype="Drop" priority=Warning idp_policy_id=7 fw_rule_id=23 user_name="" signature_id=1616 signature_msg="PROTOCOL-DNS named version attempt" classification="Attempted Information Leak" rule_priority=1 src_ip=89.160.20.156 src_country_code=CHN dst_ip=67.43.156.12 dst_country_code=R1 protocol="UDP" src_port=58914 dst_port=53 platform="BSD,Linux,Mac,Other,Solaris,Unix,Windows" category="protocol-dns" target="Server"
## Tests

Event:
- <30>device="SFW" date=2020-05-18 time=14:38:55 timezone="CEST" device_name="XG230" device_id=1234567890123456 log_id=020804407002 log_type="IDP" log_component="Signatures" log_subtype="Drop" priority=Warning idp_policy_id=7 fw_rule_id=23 user_name="" signature_id=1616 signature_msg="PROTOCOL-DNS named version attempt" classification="Attempted Information Leak" rule_priority=1 src_ip=89.160.20.156 src_country_code=CHN dst_ip=67.43.156.12 dst_country_code=R1 protocol="UDP" src_port=58914 dst_port=53 platform="BSD,Linux,Mac,Other,Solaris,Unix,Windows" category="protocol-dns" target="Server"

Output:
```
{
    "wazuh": {
        "queue": 49,
        "origin": "/dev/stdin"
    },
    "event": {
        "original": "<30>device=\"SFW\" date=2020-05-18 time=14:38:55 timezone=\"CEST\" device_name=\"XG230\" device_id=1234567890123456 log_id=020804407002 log_type=\"IDP\" log_component=\"Signatures\" log_subtype=\"Drop\" priority=Warning idp_policy_id=7 fw_rule_id=23 user_name=\"\" signature_id=1616 signature_msg=\"PROTOCOL-DNS named version attempt\" classification=\"Attempted Information Leak\" rule_priority=1 src_ip=89.160.20.156 src_country_code=CHN dst_ip=67.43.156.12 dst_country_code=R1 protocol=\"UDP\" src_port=58914 dst_port=53 platform=\"BSD,Linux,Mac,Other,Solaris,Unix,Windows\" category=\"protocol-dns\" target=\"Server\"",
        "action": "Drop",
        "code": 20804407002,
        "dataset": "sophos.xg",
        "kind": "event",
        "module": "sophos",
        "outcome": "success",
        "severity": 4,
        "timezone": "CEST"
    },
    "destination": {
        "ip": "67.43.156.12",
        "port": 53
    },
    "fileset": {
        "name": "xg"
    },
    "input": {
        "type": "log"
    },
    "log": {
        "level": "Warning"
    },
    "network": {
        "transport": "udp"
    },
    "observer": {
        "product": "XG",
        "serial_number": 1234567890123456,
        "type": "firewall",
        "vendor": "Sophos"
    },
    "related": {
        "ip": [
            "89.160.20.156",
            "67.43.156.12"
        ]
    },
    "rule": {
        "category": "Attempted Information Leak"
    },
    "service": {
        "type": "sophos"
    },
    "sophos": {
        "xg": {
            "category": "protocol-dns",
            "device": "SFW",
            "device_name": "XG230",
            "dst_country_code": "R1",
            "fw_rule_id": 23,
            "idp_policy_id": 7,
            "log_component": "Signatures",
            "log_id": 20804407002,
            "log_subtype": "Drop",
            "log_type": "IDP",
            "platform": "BSD,Linux,Mac,Other,Solaris,Unix,Windows",
            "priority": "Warning",
            "rule_priority": 1,
            "src_country_code": "CHN",
            "target": "Server"
        }
    },
    "source": {
        "ip": "89.160.20.156",
        "port": 58914
    },
    "tags": [
        "forwarded",
        "preserve_original_even",
        "sophos-xg"
    ],
    "\\@timestamp": "2020-05-18T14:38:55"
}

```

2023-01-31 11:32 UTC, JorgeMarinoDev requested changes
Good job here.
Based on already approved decoders I noticed it's a good idea to improve readability in these cases where lots of conditions are checked consecutively.

2023-01-31 11:32 UTC, JorgeMarinoDev commented on src/engine/ruleset/decoders/sophos/firewall.yml
> +      - event.severity: 6
Please add an empty newline after each check-map section to improve readability of the conditions.

2023-02-02 12:16 UTC, soynof commented on src/engine/ruleset/decoders/sophos/firewall.yml
> +  author:
Improve (documentation): add compatibility version

2023-02-02 12:17 UTC, soynof commented on src/engine/ruleset/decoders/sophos/firewall.yml
> +    - event.original: \<<~log.head_message>><~log.payload_messge>
Improve (design): if it's possible, use only one temporal variable like ~tmp

2023-02-02 20:14 UTC, merged