Add sophos/cfilter decoder
wazuh/wazuh pull request #16060
Opened 2023-02-01 04:40 UTC by NahuFigueroa97

|Related issue|
|---|
|#15851|

## Description

With the aim of expanding the coverage of the decoders, this PR adds a decoder for Sophos/Firewall.

## Configuration options

Validate the new decoder:
- ./build/main catalog validate decoder/sophos-ldp/0 < /home/vagrant/engine/wazuh/src/engine/ruleset/decoders/sophos/firewall.yml

Create decoder:
- ./build/main  catalog create decoder < /home/vagrant/engine/wazuh/src/engine/ruleset/decoders/sophos/firewall.yml

Update environment
- ./build/main catalog update environment/wazuh/0 < /home/vagrant/engine/wazuh/src/engine/ruleset/environments/wazuh-environment.yml

Test new decoder
- ./build/main test -q 1

## Logs/Alerts example

- <30>device="SFW" date=2020-05-18 time=14:38:37 timezone="CEST" device_name="XG230" device_id=1234567890123456 log_id=010101600001 log_type="Firewall" log_component="Firewall Rule" log_subtype="Allowed" status="Allow" priority=Information duration=11 fw_rule_id=21 policy_type=1 user_name="" user_gp="" iap=0 ips_policy_id=0 appfilter_policy_id=0 application="HTTP" application_risk=1 application_technology="Browser Based" application_category="General Internet" in_interface="Port1" out_interface="Port2" src_mac=00:00:00:00:00:00 src_ip=1.128.3.4 src_country_code=R1 dst_ip=91.228.167.86 dst_country_code=SVK protocol="TCP" src_port=62841 dst_port=80 sent_pkts=6  recv_pkts=5 sent_bytes=459 recv_bytes=606 tran_src_ip=213.167.51.66 tran_src_port=0 tran_dst_ip="" tran_dst_port=0 srczonetype="LAN" srczone="LAN" dstzonetype="WAN" dstzone="WAN" dir_disp="" connevent="Stop" connid="1617925280" vconnid="" hb_health="No Heartbeat" message="" appresolvedby="Signature" app_is_cloud=0

## Tests

Event:
- <30>device="SFW" date=2020-05-18 time=14:38:37 timezone="CEST" device_name="XG230" device_id=1234567890123456 log_id=010101600001 log_type="Firewall" log_component="Firewall Rule" log_subtype="Allowed" status="Allow" priority=Information duration=11 fw_rule_id=21 policy_type=1 user_name="" user_gp="" iap=0 ips_policy_id=0 appfilter_policy_id=0 application="HTTP" application_risk=1 application_technology="Browser Based" application_category="General Internet" in_interface="Port1" out_interface="Port2" src_mac=00:00:00:00:00:00 src_ip=1.128.3.4 src_country_code=R1 dst_ip=91.228.167.86 dst_country_code=SVK protocol="TCP" src_port=62841 dst_port=80 sent_pkts=6  recv_pkts=5 sent_bytes=459 recv_bytes=606 tran_src_ip=213.167.51.66 tran_src_port=0 tran_dst_ip="" tran_dst_port=0 srczonetype="LAN" srczone="LAN" dstzonetype="WAN" dstzone="WAN" dir_disp="" connevent="Stop" connid="1617925280" vconnid="" hb_health="No Heartbeat" message="" appresolvedby="Signature" app_is_cloud=0

Output:
```
{
    "wazuh": {
        "queue": 49,

2023-02-01 17:10 UTC, JorgeMarinoDev requested changes
Looks good to me. A few readability improvements can be made and check the url parsing section.

2023-02-01 17:10 UTC, JorgeMarinoDev commented on src/engine/ruleset/decoders/sophos/cfilter.yml
> +      - event.severity: 6
Move event severity mapping to the end in a new section with proper comment.

2023-02-01 17:10 UTC, JorgeMarinoDev commented on src/engine/ruleset/decoders/sophos/cfilter.yml
> +      - url.extension: $~tmp.extension
Same discussion about url parsing.
https://github.com/wazuh/wazuh/pull/16063#discussion_r1093496001

2023-02-01 17:10 UTC, JorgeMarinoDev commented on src/engine/ruleset/decoders/sophos/cfilter.yml
> +      - user_agent.original: $~tmp.user_agent
Same comment as here.
https://github.com/wazuh/wazuh/pull/16063#discussion_r1093502976

2023-02-02 11:58 UTC, soynof commented on src/engine/ruleset/decoders/sophos/cfilter.yml
> +  description: Decoder for sophos logs
Improve (Documentation): add compatibility version

2023-02-02 11:59 UTC, soynof commented on src/engine/ruleset/decoders/sophos/cfilter.yml
> +    - event.original: \<<~log.head_message>><~log.payload_message>
Improve (Design): if is possible use only one temporal variable, like ~tmp

2023-02-02 12:00 UTC, soynof commented on src/engine/ruleset/decoders/sophos/cfilter.yml
> +  - check:
Improve (Design): check is not necessary

2023-02-02 20:29 UTC, merged