15485 expand helper function coverage
wazuh/wazuh pull request #16094
Opened 2023-02-06 12:49 UTC by LucioDonda

|Related issue|
|---|
|#15485|

## Description
This PR implements a new function :
- **+s_contains**: It is necessary to be able to check if a string contains a substring.
Adds some corrections to other HF already implemented:
- **+i_calc/operator/param1/../paramN**: Now it should operate on the target field N parameters, which can be values or references.
- **OperationBuilder** : Fix in order to avoid unnecessary unescape characters.

## Tasks
- [ ] Implement `+s_contains`
> - [ ] Unit Tests (different inputs (reference, values, emptiness, types, nested objects) 
> - [ ] Development

- [ ] Modify `+i_calc`
> - [ ] Unit Tests changes, improvements
> - [ ] Development

- [ ] Fix OperationBuilder issue extracting split arguments (should unescape when necessary)

- [ ] Update Documentation
- [ ] QA validate

2023-02-23 12:28 UTC, LucioDonda commented on src/engine/source/builder/builders/opBuilderHelperFilter.cpp
> -    auto regex_ptr {std::make_shared<RE2>(parameters[0].m_value, RE2::Quiet)};
Altough `at()` y slower than the `[]` operator we can catch the exception thrown by it if it's out of bounds. Besides that, it was part of the comments/corrections we received in this [PR](https://github.com/wazuh/wazuh/pull/15970/files) and I thought it was a more C++ approach to apply from now on.

2023-02-23 13:09 UTC, LucioDonda commented on src/engine/source/base/utils/stringUtils.cpp
> +std::vector<std::string> splitEscaped(std::string_view input, const char& splitChar, const char& escape)
great, indeed it's a better approach, I'll modify it!

2023-02-24 10:42 UTC, JavierBejMen commented on src/engine/source/base/utils/stringUtils.cpp
> +std::vector<std::string> splitEscaped(std::string_view input, const char& splitChar, const char& escape)
When processing the las char, a separator is allowed also, indicating the las parameter is empty. We must handle this too

2023-02-24 10:42 UTC, JavierBejMen commented on src/engine/source/base/utils/stringUtils.cpp
> +std::vector<std::string> splitEscaped(std::string_view input, const char& splitChar, const char& escape)
Also a test for this case must exists

2023-02-24 10:57 UTC, LucioDonda commented on src/engine/source/base/utils/stringUtils.cpp
> +std::vector<std::string> splitEscaped(std::string_view input, const char& splitChar, const char& escape)
It is tested in:
```
TEST(splitEscaped, SuccessEmptyFields)
{
    std::string input = R"(+123456/ABC\/DE\/12/test/!//)";
    std::vector<std::string> expected = {"+123456", R"(ABC/DE/12)", "test", "!", ""};
```
If the last char is a separator is the ending of a segment, if empty then before of that the empty string was appended, if not then we added it to the last segment

2023-02-24 13:01 UTC, juliancnn requested changes

2023-02-24 13:01 UTC, juliancnn commented on src/engine/source/builder/builders/opBuilderHelperMap.cpp
> +                    throw std::runtime_error(
Add the `e.whats()` to the msg

2023-02-24 17:25 UTC, LucioDonda commented on src/engine/source/base/utils/stringUtils.cpp
> +    splitted.push_back("");
done!

2023-02-24 17:25 UTC, LucioDonda commented on src/engine/source/base/utils/stringUtils.cpp
> +        auto thisChar = input.at(i);
right!

2023-02-24 17:25 UTC, LucioDonda commented on src/engine/source/base/utils/stringUtils.cpp
> +    return splitted;
yup, it could be managed inside the loop, I'll check!

2023-02-24 17:25 UTC, LucioDonda commented on src/engine/source/builder/builders/opBuilderHelperMap.cpp
> +                    throw std::runtime_error(
ok

2023-02-24 17:29 UTC, LucioDonda commented
The change in the empty parameters, assuming the last '/' as an additional empty parameter, impacted several helpers that weren't used that way.
eg `+s_eq//` was used to check if a string was empty. now it's `+s_eq/`
That's why now in the PR there are several modifications on the decoders.

2023-02-27 15:36 UTC, JavierBejMen approved these changes
LGTM

2023-02-28 13:10 UTC, juliancnn approved these changes
LGTM!

2023-03-01 14:59 UTC, JcabreraC approved these changes
LGTM !

2023-03-01 14:59 UTC, merged