Fixes to wazuh-db sync-agent-groups-get endpoint
wazuh/wazuh pull request #16202
Opened 2023-02-14 18:46 UTC by sdvendramini

|Related issues|
|---|
|https://github.com/wazuh/wazuh/issues/16188|
|https://github.com/wazuh/wazuh/issues/16190|
|https://github.com/wazuh/wazuh/issues/16196|

## Description

This changes where made to fix the above issues. They are related to ```sync-agent-groups-get``` wazuh-db endpoint and consist in:
- New function created to add global group hash to ```sync-agent-groups-get``` response. 
- The ```condition``` parameter of ```sync-agent-groups-get``` is optional now. 
- Fix to not set ```group_sync_status``` to ```synced``` status when the response is full.

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

2023-02-14 18:57 UTC, sdvendramini commented
- https://github.com/wazuh/wazuh/issues/16188

This fix was tested on master quering the first chunck of data from the ```sync-agent-groups-get```:
```
python3 wdb-query.py 'global sync-agent-groups-get {"condition": "sync_status", "set_synced": true, "get_global_hash": true}'
due [{"data":[{"id":1,"groups":["g0","g1","g2"]},...,{"id":1739,"groups":["g0","g1","g2"]}]}]
```

Then we check that the last agent of the chuck is marked as ```synced``` and the next one still is marked as ```synreq```:
```
python3 wdb-query.py 'global sql select group_sync_status from agent where id=1739'
[
    {
        "group_sync_status": "synced"
    }
]

python3 wdb-query.py 'global sql select group_sync_status from agent where id=1740'
[
    {
        "group_sync_status": "syncreq"
    }
]
```
Finally we query the second chunck of agents and groups and check again that agents returned are correct.
```
root@jellyfish:~/wazuh-tools/utils# python3 wdb-query.py 'global sync-agent-groups-get {"condition": "sync_status", "set_synced": true, "get_global_hash": true}'
due [{"data":[{"id":1740,"groups":["g0","g1","g2"]},...,{"id":3449,"groups":["g0","g1","g2"]}]}]
```
We can observer once again that the last agent of the query and the following are marked correctly:
```
python3 wdb-query.py 'global sql select group_sync_status from agent where id=3449'
[
    {
        "group_sync_status": "synced"
    }
]

python3 wdb-query.py 'global sql select group_sync_status from agent where id=3450'
[
    {
        "group_sync_status": "syncreq"
    }
]
```

2023-02-14 19:05 UTC, sdvendramini commented
- https://github.com/wazuh/wazuh/issues/16190

This fix was tested on worker. We can observe the following agents with theris groups:
```
python3 wdb-query.py 'global sql select id, "GROUP", group_hash from agent LIMIT 3'
[
    {
        "id": 0
    },
    {
        "id": 1,
        "group": "g0,g1,g2",
        "group_hash": "18832fd6"
    },
    {
        "id": 2,
        "group": "g0,g1,g2",
        "group_hash": "18832fd6"
    }
]
```

Then one of the groups is deleted:
```
root@focal:~# rm -r /var/ossec/etc/shared/g2

python3 wdb-query.py 'global sql select id, "GROUP", group_hash from agent LIMIT 3'
[
    {
        "id": 0
    },
    {
        "id": 1,
        "group": "g0,g1",
        "group_hash": "f37fe7e3"
    },
    {
        "id": 2,
        "group": "g0,g1",
        "group_hash": "f37fe7e3"
    }
]
```
After that we check if any agent is with ```group_sync_status="syncreq"```
```
python3 wdb-query.py 'global sql select count(id) from agent where id > 0 AND group_sync_status = "synreq"'
[
    {
        "count(id)": 0
    }
]

python3 wdb-query.py 'global sql select count(id) from agent where id > 0 AND group_sync_status = "synced"'
[
    {
        "count(id)": 25000
    }
]

```

Finally the master sync the agent group to the worker correctly:
```
python3 wdb-query.py 'global sql select id, "GROUP", group_hash from agent LIMIT 3'
[
    {
        "id": 0
    },
    {
        "id": 1,
        "group": "g0,g1,g2",
        "group_hash": "18832fd6"
    },
    {
        "id": 2,
        "group": "g0,g1,g2",
        "group_hash": "18832fd6"
    }
]

```

2023-02-14 20:44 UTC, sdvendramini commented
- https://github.com/wazuh/wazuh/issues/16196

This change was tested quering ```sync-agent-groups-get``` with differents paremeters:
```
python3 wdb-query.py 'global sync-agent-groups-get {"get_global_hash": true}'
[
    {
        "data": [],
        "hash": "1945e0d9718edae6897a8c8777ad805a4fe6c9cd"
    }
]
```

```
python3 wdb-query.py 'global sync-agent-groups-get {}'
[
    {
        "data": []
    }
]
```

```
python3 wdb-query.py 'global sql update agent set group_sync_status = "syncreq" where id = 3000'
[]

python3 wdb-query.py 'global sync-agent-groups-get {"condition": "sync_status", "get_global_hash": true}'
[
    {
        "data": [
            {
                "id": 3000,
                "groups": [
                    "g0",
                    "g1",
                    "g2"
                ]
            }
        ],
        "hash": "1945e0d9718edae6897a8c8777ad805a4fe6c9cd"
    }
]
```

```
python3 wdb-query.py 'global sql update agent set group_sync_status = "syncreq" where id = 3000'
[]

python3 wdb-query.py 'global sync-agent-groups-get {"get_global_hash": true}'
[
    {
        "data": [],
        "hash": "1945e0d9718edae6897a8c8777ad805a4fe6c9cd"
    }
]
```

2023-02-15 14:21 UTC, TomasTurina requested changes

2023-02-15 14:21 UTC, TomasTurina commented on src/wazuh_db/wdb_parser.c
> +            if (cJSON_IsString(j_sync_condition) && 0 == strcmp(j_sync_condition->valuestring, "sync_status")) {
```suggestion
            if (j_sync_condition && 0 == strcmp(j_sync_condition->valuestring, "sync_status")) {
```

2023-02-15 14:21 UTC, TomasTurina commented on src/wazuh_db/wdb_parser.c
> +            } else if (cJSON_IsString(j_sync_condition) && 0 == strcmp(j_sync_condition->valuestring, "all")) {
```suggestion
            } else if (j_sync_condition && 0 == strcmp(j_sync_condition->valuestring, "all")) {
```

2023-02-15 14:21 UTC, TomasTurina commented on src/wazuh_db/wdb.h
> +int wdb_global_add_global_group_hash_to_resposne(wdb_t *wdb, cJSON** response, size_t response_size);
```suggestion
int wdb_global_add_global_group_hash_to_response(wdb_t *wdb, cJSON** response, size_t response_size);
```

2023-02-15 14:21 UTC, TomasTurina commented on src/wazuh_db/wdb_global.c
>      if (!wdb->transaction && wdb_begin2(wdb) < 0) {
I think this if can be inside the if below:
```
if (condition != WDB_GROUP_NO_CONDITION) {
    if (!wdb->transaction && wdb_begin2(wdb) < 0) {
        mdebug1("Cannot begin transaction");
        return WDBC_ERROR;
    }
...
```

2023-02-15 14:21 UTC, TomasTurina commented on src/wazuh_db/wdb_global.c
> +    if (response == NULL || *response == NULL) {
```suggestion
    if (response == NULL || !cJSON_IsObject(*response)) {
```

2023-02-15 21:32 UTC, TomasTurina approved these changes

2023-02-16 16:31 UTC, TomasTurina requested changes

2023-02-16 16:31 UTC, TomasTurina commented on src/wazuh_db/wdb_global.c
> +                    WDBC_ERROR == wdb_global_recalculate_agent_groups_hash(wdb, agent_id->valueint, wconfig.is_worker?"synced":"syncreq")) {
Check also for standalone.

2023-02-16 20:31 UTC, TomasTurina submitted a review, later dismissed

2023-02-17 12:23 UTC, sdvendramini commented
## Valgrind
For this test, two manager (1 master and 1 worker) were configured, 25.000 agents were enrolled and finally 4 groups were created and assigned to all the agents. Then some groups folder were deleted to force the synchronization process.

### Valgrind Reports 

- Master node
```
==69078== 
==69078== FILE DESCRIPTORS: 4 open (3 std) at exit.
==69078== Open file descriptor 3: /dev/urandom
==69078==    at 0x52A16EB: open (open64.c:41)
==69078==    by 0x23F401: randombytes (randombytes.c:62)
==69078==    by 0x23F536: os_random (randombytes.c:88)
==69078==    by 0x2354A1: OSHash_Create (hash_op.c:54)
==69078==    by 0x11D7CD: main (main.c:128)
==69078== 
==69078== 
==69078== HEAP SUMMARY:
==69078==     in use at exit: 0 bytes in 0 blocks
==69078==   total heap usage: 6,234,762 allocs, 6,234,762 frees, 496,521,914 bytes allocated
==69078== 
==69078== All heap blocks were freed -- no leaks are possible
==69078== 
==69078== For lists of detected and suppressed errors, rerun with: -s
==69078== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
==69078== could not unlink /tmp/vgdb-pipe-from-vgdb-to-69078-by-root-on-???
==69078== could not unlink /tmp/vgdb-pipe-to-vgdb-from-69078-by-root-on-???
==69078== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-69078-by-root-on-???
```
- Worker node
```
==151736== 
==151736== FILE DESCRIPTORS: 5 open at exit.
==151736== Open AF_UNIX socket 5: queue/db/wdb
==151736==    at 0x51964FF: accept (accept.c:26)
==151736==    by 0x11E239: run_dealer (main.c:310)
==151736==    by 0x518B608: start_thread (pthread_create.c:477)
==151736==    by 0x52C5132: clone (clone.S:95)
==151736== 
==151736== Open file descriptor 3: /dev/urandom
==151736==    at 0x5196ABB: open (open64.c:48)
==151736==    by 0x23D36E: randombytes (randombytes.c:62)
==151736==    by 0x23D497: os_random (randombytes.c:88)
==151736==    by 0x2341AF: OSHash_Create (hash_op.c:54)
==151736==    by 0x11D76A: main (main.c:128)
==151736== 
==151736== Open file descriptor 2: /dev/pts/1
==151736==    <inherited from parent>
==151736== 
==151736== Open file descriptor 1: /dev/pts/1
==151736==    <inherited from parent>
==151736== 
==151736== Open file descriptor 0: /dev/pts/1
==151736==    <inherited from parent>
==151736== 
==151736== 
==151736== HEAP SUMMARY:
==151736==     in use at exit: 0 bytes in 0 blocks
==151736==   total heap usage: 22,884,884 allocs, 22,884,884 frees, 16,484,860,200 bytes allocated
==151736== 
==151736== All heap blocks were freed -- no leaks are possible
==151736== 
==151736== For lists of detected and suppressed errors, rerun with: -s
==151736== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
==151736== could not unlink /tmp/vgdb-pipe-from-vgdb-to-151736-by-root-on-???
==151736== could not unlink /tmp/vgdb-pipe-to-vgdb-from-151736-by-root-on-???
==151736== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-151736-by-root-on-???
```

2023-02-22 15:14 UTC, TomasTurina approved these changes

2023-02-22 16:42 UTC, TomasTurina approved these changes

2023-02-22 16:43 UTC, merged