Remove agent-group relationship check from `DELETE /groups`
wazuh/wazuh pull request #16231
Opened 2023-02-16 15:22 UTC by vicferpoy

|Related issue|
|---|
|closes #16191 |

## Description

This PR removes the agent-group relationship check before trying to delete an agent group, leaving that to `wazuh-db`. This improves the endpoint performance vastly.

In addition, since that check has been removed, that endpoint's response has changed too:

```json
{
  "data": {
    "affected_items": [
      "testing"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected groups were deleted",
  "error": 0
}
```

In the exact same situation (50k agents, 5 assigned groups, 1 deleted group), request time has changed from more than 4 minutes to `37ms`.

## Tests

### Unit tests

```
==================================================================================================================================================== test session starts =====================================================================================================================================================
platform linux -- Python 3.9.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/vicferpoy/Desktop/Git/wazuh/framework
plugins: testinfra-5.0.0, metadata-1.11.0, cov-2.12.0, asyncio-0.18.3, aiohttp-0.3.0, html-3.1.1, trio-0.7.0
asyncio: mode=legacy
collected 2047 items                                                                                                                                                                                                                                                                                                         

framework/scripts/tests/test_agent_groups.py ..............                                                                                                                                                                                                                                                            [  0%]
framework/scripts/tests/test_agent_upgrade.py ...............                                                                                                                                                                                                                                                          [  1%]
framework/scripts/tests/test_cluster_control.py ......                                                                                                                                                                                                                                                                 [  1%]
framework/scripts/tests/test_wazuh_clusterd.py .......                                                                                                                                                                                                                                                                 [  2%]
framework/scripts/tests/test_wazuh_logtest.py ......................                                                                                                                                                                                                                                                   [  3%]
framework/wazuh/core/cluster/dapi/tests/test_dapi.py ................................                                                                                                                                                                                                                                  [  4%]
framework/wazuh/core/cluster/tests/test_client.py ................                                                                                                                                                                                                                                                     [  5%]
framework/wazuh/core/cluster/tests/test_cluster.py ...................................                                                                                                                                                                                                                                 [  7%]
framework/wazuh/core/cluster/tests/test_common.py ...........................................................................                                                                                                                                                                                          [ 10%]
framework/wazuh/core/cluster/tests/test_control.py ......                                                                                                                                                                                                                                                              [ 11%]
framework/wazuh/core/cluster/tests/test_local_client.py .............                                                                                                                                                                                                                                                  [ 11%]
framework/wazuh/core/cluster/tests/test_local_server.py ........................                                                                                                                                                                                                                                       [ 12%]
framework/wazuh/core/cluster/tests/test_master.py .............................................                                                                                                                                                                                                                        [ 15%]
framework/wazuh/core/cluster/tests/test_server.py ...................                                                                                                                                                                                                                                                  [ 16%]
framework/wazuh/core/cluster/tests/test_utils.py ...........                                                                                                                                                                                                                                                           [ 16%]
framework/wazuh/core/cluster/tests/test_worker.py ....................................                                                                                                                                                                                                                                 [ 18%]
framework/wazuh/core/tests/test_active_response.py ..............                                                                                                                                                                                                                                                      [ 19%]
framework/wazuh/core/tests/test_agent.py ................................................................................................................................................                                                                                                                              [ 26%]
framework/wazuh/core/tests/test_cdb_list.py ......................................                                                                                                                                                                                                                                     [ 27%]
framework/wazuh/core/tests/test_common.py .......                                                                                                                                                                                                                                                                      [ 28%]
framework/wazuh/core/tests/test_config [...]

2023-02-21 11:26 UTC, Selutario approved these changes

2023-02-21 11:52 UTC, davidjiglesias requested changes

2023-02-21 11:52 UTC, davidjiglesias commented on api/api/spec/spec.yaml
> +          description: "List of removed groups"
```suggestion
          description: "List of removed groups, agents belonging exclusively to the removed groups will be reassigned to group default"
```

2023-02-24 10:49 UTC, davidjiglesias approved these changes

2023-02-24 10:50 UTC, merged