Add new command to get active cluster.json configuration
wazuh/wazuh pull request #16264
Opened 2023-02-22 16:04 UTC by Selutario

|Related issue|
|---|
| Closes #14983 |

## Description

This PR adds a new cluster command, `get_cl_conf`, to obtain the active `cluster.json` configuration of the node where it is run. As this file is not intended to be modified by users, no API endpoint is required. In fact, although a CLI option (`-c`, `--cluster-config`) has been added to `/var/ossec/bin/cluster_control`, it is not shown in the CLI help:
```
# /var/ossec/bin/cluster_control   
usage: cluster_control.py [-h] [-d] [-fn [FILTER_NODE ...]] [-fs [FILTER_STATUS ...]] [-a | -l | -i [HEALTH] | -u]

optional arguments:
  -h, --help            show this help message and exit
  -d, --debug           Enable debug mode
  -fn [FILTER_NODE ...], --filter-node [FILTER_NODE ...]
                        Filter by node name
  -fs [FILTER_STATUS ...], --filter-agent-status [FILTER_STATUS ...]
                        Filter by agent status
  -a, --list-agents     List agents
  -l, --list-nodes      List nodes
  -i [HEALTH], --health [HEALTH]
                        Show cluster health
  -u, --usage           Show usage
```

## Logs/Alerts example

```JSON
root@wazuh-master:/# /var/ossec/bin/cluster_control -c 
{
    "files": {
        "etc/": {
            "permissions": 416,
            "source": "master",
            "files": [
                "client.keys"
            ],
            "recursive": false,
            "restart": false,
            "remove_subdirs_if_empty": false,
            "extra_valid": false,
            "description": "client keys file database"
        },
        "etc/shared/": {
            "permissions": 432,
            "source": "master",
            "files": [
                "all"
            ],
            "recursive": true,
            "restart": false,
            "remove_subdirs_if_empty": true,
            "extra_valid": false,
            "description": "shared configuration files"
        },
        "var/multigroups/": {
            "permissions": 432,
            "source": "master",
            "files": [
                "merged.mg"
            ],
            "recursive": true,
            "restart": false,
            "remove_subdirs_if_empty": true,
            "extra_valid": false,
            "description": "shared configuration files"
        },
        "etc/rules/": {
            "permissions": 432,
            "source": "master",
            "files": [
                "all"
            ],
            "recursive": true,
            "restart": true,
            "remove_subdirs_if_empty": false,
            "extra_valid": false,
            "description": "user rules"
        },
        "etc/decoders/": {
            "permissions": 432,
            "source": "master",
            "files": [
                "all"
            ],
            "recursive": true,
            "restart": true,
            "remove_subdirs_if_empty": false,
            "extra_valid": false,
            "description": "user decoders"
        },
        "etc/lists/": {
            "permissions": 432,
            "source": "master",
            "files": [
                "all"
            ],
            "recursive": true,
            "restart": true,
            "remove_subdirs_if_empty": false,
            "extra_valid": false,
            "description": "user CDB lists"
        },
        "excluded_files": [
            "ar.conf",
            "ossec.conf"
        ],
        "excluded_extensions": [
            "~",
            ".tmp",
            ".lock",
            ".swp"
        ]
    },
    "intervals": {
        "worker": {
            "sync_integrity": 9,
            "sync_agent_info": 10,
            "sync_agent_groups": 30,
            "timeout_agent_groups": 40,
            "keep_alive": 60,
            "connection_retry": 10,
            "max_failed_keepalive_attempts": 2,
            "agent_groups_mismatch_limit": 10
        },
        "master": {
            "process_pool_size": 2,
            "sync_agent_groups": 10,
            "timeout_extra_valid": 40,
            "recalculate_integrity": 8,
            "timeout_agent_info": 40,
            "agent_group_start_delay": 30,
            "check_worker_lastkeepalive": 60,
            "max_allowed_time_without_keepalive": 120,
            "max_locked_integrity_time": 1000
        },
        "communication": {
            "timeout_cluster_request": 20,
            "timeout_dapi_request": 200,
            "timeout_receiving_file": 120,
            "max_zip_size": 1073741824,
            "min_zip_size": 31457280,
            "compress_level": 1,
            "zip_limit_tolerance": 0.2
        }
    },
    "distributed_api": {
        "enabled": true
    }
}
```

## Tests

```
$ PYTHONPATH=/home/selu/Git/wazuh/api:/home/selu/Git/wazuh/framework python3 -m pytest framework -x --disable-warnings
============================================================================================ test session starts ============================================================================================
platform linux -- Python 3.9.16, pytest-7.0.1, pluggy-0.13.1
rootdir: /home/selu/Git/wazuh/framework
plugins: anyio-3.6.2, asyncio-0.18.1, aiohttp-1.0.4, cov-4.0.0
asyncio: mode=auto
collected 2099 items                                                                                                                                                                                        

framework/scripts/tests/test_agent_groups.py ..............                                                                                                                                           [  0%]
framework/scripts/tests/test_agent_upgrade.py ..............                                                                                                                                          [  1%]
framework/scripts/tests/test_cluster_control.py .......                                                                                                                                               [  1%]
framework/scripts/tests/test_rbac_control.py .........                                                                                                                                                [  2%]
framework/scripts/tests/test_wazuh_clusterd.py .......                                                                                                                                                [  2%]
framework/scripts/tests/test_wazuh_logtest.py ......................                                                                                                                                  [  3%]
framework/wazuh/core/cluster/dapi/tests/test_dapi.py ................................                                                                                                                 [  5%]
framework/wazuh/core/cluster/tests/test_client.py ................                                                                                                                                    [  5%]
framework/wazuh/core/cluster/tests/test_cluster.py ...................................                                                                                                                [  7%]
framework/wazuh/core/cluster/tests/test_common.py ..................................................................................                                                                  [ 11%]
framework/wazuh/core/cluster/tests/test_control.py .........                                                                                                                                          [ 11%]
framework/wazuh/core/cluster/tests/test_local_client.py ..............                                                                                                                                [ 12%]
framework/wazuh/core/cluster/tests/test_local_server.py .........................                                                                [...]

2023-03-01 14:30 UTC, nico-stefani submitted a review, later dismissed
LGTM!

2023-03-08 11:10 UTC, davidjiglesias requested changes
Also add the active configuration in the cluster.log at start, in INFO mode and in json format.

2023-03-08 11:10 UTC, davidjiglesias commented on framework/scripts/cluster_control.py
> +    exclusive.add_argument('-c', '--cluster-conf', action='store_true', help=argparse.SUPPRESS)
-c could be a bit confusing honestly. I think something like rc (read config) makes more sense. C or c is sometimes used to provide config, not only reading it.

2023-03-08 11:10 UTC, davidjiglesias commented on framework/wazuh/core/cluster/control.py
> +        Dictionary with results
```suggestion
        Dictionary with results.
```

2023-11-07 07:33 UTC, closed without merging