Fix/16032 variable use ruleset
wazuh/wazuh pull request #16310
Opened 2023-03-01 19:32 UTC by mateojames

|Related issue|
|---|
|#16032|

## Description

Using the following configuration on _/var/ossec/etc/rules/local_rules.xml_:

```
<var name="LEVEL">0</var>
<var name="ID">100001</var>

<group name="local,syslog,sshd,">
  <rule id="$ID" level="$LEVEL">
    <if_sid>5716</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>sshd: authentication failed from IP 1.1.1.1.</description>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>

</group>
```
and by consulting the API endpoint GET /rules we get the following response:

```
{
    "data": {
        "affected_items": [
            {
                "filename": "local_rules.xml",
                "relative_dirname": "etc/rules",
                "id": 100001,
                "level": 0,
                "status": "enabled",
                "details": {
                    "if_sid": "5716",
                    "srcip": "1.1.1.1"
                },
                "pci_dss": [
                    "10.2.4",
                    "10.2.5"
                ],
                "gpg13": [],
                "gdpr": [],
                "hipaa": [],
                "nist_800_53": [],
                "tsc": [],
                "mitre": [],
                "groups": [
                    "authentication_failed",
                    "local",
                    "syslog",
                    "sshd"
                ],
                "description": "sshd: authentication failed from IP 1.1.1.1."
            }
        ],
        "total_affected_items": 1,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "All selected rules were returned",
    "error": 0
}
```

confirming the ID and Level were replaced correctly by their variable values.
A issue for the documentation will be created in order to specify variables must be defined at root level, nos inside any tag.

## Tests

### Unit Tests 🟢 
```
============================= test session starts ==============================
platform linux -- Python 3.9.16, pytest-7.0.1, pluggy-0.13.1
rootdir: /home/testuser/git/wazuh/framework
plugins: cov-3.0.0, aiohttp-1.0.4, trio-0.7.0, anyio-3.6.2, metadata-2.0.2, html-3.0.0, asyncio-0.18.1
asyncio: mode=auto
collected 2094 items

framework/scripts/tests/test_agent_groups.py ..............              [  0%]
framework/scripts/tests/test_agent_upgrade.py ..............             [  1%]
framework/scripts/tests/test_cluster_control.py ......                   [  1%]
framework/scripts/tests/test_rbac_control.py .........                   [  2%]
framework/scripts/tests/test_wazuh_clusterd.py .......                   [  2%]
framework/scripts/tests/test_wazuh_logtest.py ......................     [  3%]
framework/wazuh/core/cluster/dapi/tests/test_dapi.py ................... [  4%]
.............                                                            [  4%]
framework/wazuh/core/cluster/tests/test_client.py ................       [  5%]
framework/wazuh/core/cluster/tests/test_cluster.py ..................... [  6%]
..............                                                           [  7%]
framework/wazuh/core/cluster/tests/test_common.py ...................... [  8%]
............................................................             [ 11%]
framework/wazuh/core/cluster/tests/test_control.py ......                [ 11%]
framework/wazuh/core/cluster/tests/test_local_client.py ..............   [ 12%]
framework/wazuh/core/cluster/tests/test_local_server.py ................ [ 13%]
........                                                                 [ 13%]
framework/wazuh/core/cluster/tests/test_master.py ...................... [ 14%]
..........................                                               [ 15%]
framework/wazuh/core/cluster/tests/test_server.py ...................... [ 16%]
.......                                                                  [ 17%]
framework/wazuh/core/cluster/tests/test_utils.py ...........             [ 17%]
framework/wazuh/core/cluster/tests/test_worker.py ...................... [ 18%]
............                                                             [ 19%]
framework/wazuh/core/tests/test_active_response.py ..............        [ 19%]
framework/wazuh/core/tests/test_agent.py ............................... [ 21%]
........................................................................ [ 24%]
............................................                             [ 26%]
framework/wazuh/core/tests/test_cdb_list.py ............................ [ 28%]
..........                                                               [ 28%]
framework/wazuh/core/tests/test_common.py .........                      [ 29%]
framework/wazuh/core/tests/test_configuration.py ....................... [ 30%]
................................................                         [ 32%]
framework/wazuh/core/tests/test_database.py .............                [ 33%]
framework/wazuh/core/tests/test_decoder.py ................              [ 33%]
framework/wazuh/core/tests/test_exception.py ...                         [ 34%]
framework/wazuh/core/tests/test_input_validator.py ...                   [ 34%]
framework/wazuh/core/tests/test_logtest.py ..                            [ 34%]
framework/wazuh/core/tests/test_manager.py ................              [ 35%]
framework/wazuh/core/tests/test_mitre.py .............                   [ 35%]
framework/wazuh/core/tests/test_pyDaemonModule.py .....                  [ 35%]
framework/wazuh/core/tests/test_results.py ............................. [ 37%]
...........                                                              [ 37%]
framework/wazuh/core/tests/test_rootcheck.py .............               [ 38%]
framework/wazuh/core/tests/test_rule.py ......................           [ 39%]
framework/wazuh/core/tests/test_sca.py ........................          [ 40%]
framework/wazuh/core/tests/test_security.py .............                [ 41%]
framework/wazuh/core/tests/test_stats.py .................               [ 42%]
framework/wazuh/core/tests/test_syscheck.py .......                      [ 42%]
framework/wazuh/core/tests/test_syscollector.py ...                      [ 42%]
framework/wazuh/core/tests/test_task.py ........                         [ 42%]
framework/wazuh/core/tests/test_utils.py ............................... [ 44%]
........................................................................ [ 47%]
........................................................................ [ 51%]
...................................................................      [ 54%]
framework/wazuh/core/tests/test_vulnerability.py ..                      [ 54%]
framework/wazuh/core/tests/test_wazuh_queue.py ....................      [ 55%]
framework/wazuh/core/tests/test_wazuh_socket.py ....................     [ 56%]
framework/wazuh/core/tests/test_wdb.py ...............................   [ 58%]
framework/wazuh/core/tests/test_wlogging.py ............                 [ 58%]
framework/wazuh/rbac/tests/test_auth_context.py ..                       [ 58%]
framework/wazuh/rbac/tests/test_decorators.py .......................... [ 59%]
........................................................................ [ 63%]
...........                                                              [ 63%]
framework/wazuh/rbac/tests/test_default_configuration.py ............... [ 64%]
.........................................                                [ 66%]
framework/wazuh/rbac/tests/test_orm.py ................................. [ 68%]
................................                                         [ 69%]
framework/wazuh/rbac/tests/test_preprocessor.py ...........              [ 70%]
framework/wazuh/tests/test_active_response.py ............               [ 70%]
framework/wazuh/tests/test_agent.py .................................... [ 72%]
........................................................................ [ 75%] [...]

2023-03-06 11:39 UTC, Selutario approved these changes

2023-03-06 11:44 UTC, Selutario requested changes

2023-03-06 11:44 UTC, Selutario commented on framework/wazuh/core/rule.py
> +                        #Replace values of id and level if variables exist
```suggestion
                        # Replace values of id and level if variables exist
```

2023-03-06 11:44 UTC, Selutario commented on framework/wazuh/core/rule.py
> +            name = "$"+vari.attrib.get('name')
```suggestion
            name = "$" + vari.attrib.get('name')
```

2023-03-07 13:19 UTC, Selutario approved these changes

2023-04-14 14:16 UTC, davidjiglesias approved these changes

2023-04-14 14:16 UTC, merged