16031 engine metrics module implementation
wazuh/wazuh pull request #16339
Opened 2023-03-07 14:30 UTC by NahuFigueroa97

|Related issue|
|---|
||

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2023-03-09 18:51 UTC, soynof commented on src/engine/source/api/include/api/metrics/commands.hpp
> +api::CommandFn metricsDumpCmd();
Add function descripción

2023-03-09 18:52 UTC, soynof commented on src/engine/source/api/include/api/metrics/commands.hpp
> +api::CommandFn metricsGetCmd();
Add function descripción

2023-03-09 18:52 UTC, NahuFigueroa97 commented on src/engine/source/api/include/api/metrics/commands.hpp
> +api::CommandFn metricsDumpCmd();
Severe - Documentation : add documentation to methods

2023-03-09 18:52 UTC, soynof commented on src/engine/source/api/include/api/metrics/commands.hpp
> +api::CommandFn metricsEnableCmd();
Add function descripción

2023-03-09 18:52 UTC, soynof commented on src/engine/source/api/include/api/metrics/commands.hpp
> +api::CommandFn metricsListCmd();
Add function descripción

2023-03-09 18:52 UTC, soynof commented on src/engine/source/api/include/api/metrics/commands.hpp
> +api::CommandFn metricsTestCmd();
Add function descripción

2023-03-09 18:53 UTC, JorgeMarinoDev commented on src/engine/source/api/include/api/metrics/commands.hpp
> +void registerAllCmds(std::shared_ptr<api::Registry> registry);
Add missing documentation for Cmd()s

2023-03-09 18:53 UTC, NahuFigueroa97 commented on src/engine/source/metrics/include/metrics.hpp
> +     */
severe - documentation: Fix documentation in all methods

2023-03-09 18:55 UTC, soynof commented on src/engine/source/api/src/metrics/commands.cpp
> +        auto name = params.getString("/nameInstrument");
Rename "/nameInstrument" to "/instrumentName"

2023-03-09 18:56 UTC, NahuFigueroa97 commented on src/engine/source/metrics/include/chainOfResponsibility.hpp
> +    std::shared_ptr<AbstractHandler> next() const
improve - desing: this method is unsed

2023-03-09 18:56 UTC, soynof commented on src/engine/source/cmds/include/cmds/metrics.hpp
> +std::string commandName(const std::string& command);
Add function description

2023-03-09 18:59 UTC, NahuFigueroa97 commented on src/engine/source/metrics/include/dataHubExporter.hpp
> +#endif // __JSON_EXPORTER_H
Add new line

2023-03-09 19:01 UTC, NahuFigueroa97 commented on src/engine/source/metrics/include/exporterHandler.hpp
> +     * @brief Trigger for the normalization process on the metrics context.
improve - documentation: this isn't a normalizacion process

2023-03-09 19:01 UTC, NahuFigueroa97 commented on src/engine/source/metrics/include/exporterHandler.hpp
> +     * @brief
improve - documentation: add documentation

2023-03-09 19:03 UTC, NahuFigueroa97 commented on src/engine/source/metrics/include/providerHandler.hpp
> +#ifndef _PROVIDER_HANDLER_HPP
improve - documentation: same to exporter

2023-03-09 19:03 UTC, NahuFigueroa97 commented on src/engine/source/metrics/include/readerHandler.hpp
> +#ifndef _READER_HANDLER_HPP
improve - documentation: same to exporter

2023-03-09 19:07 UTC, NahuFigueroa97 commented on src/engine/source/metrics/include/metricsContext.hpp
> +enum class ProviderTypes
improve -  naming: it is SignalsTypes

2023-03-09 19:07 UTC, NahuFigueroa97 commented on src/engine/source/metrics/include/processorHandler.hpp
> +#ifndef _PROCESSOR_HANDLER_HPP
improve - documentation: same to exporter

2023-03-09 19:07 UTC, NahuFigueroa97 commented on src/engine/source/cmds/src/catalog.cpp
> +#include "metrics.hpp"
delete this

2023-03-09 19:41 UTC, cborla commented on src/engine/source/cmds/src/catalog.cpp
> +#include "metrics.hpp"
I believe that the library should not be included here.

2023-03-09 19:53 UTC, JorgeMarinoDev requested changes

2023-03-09 19:53 UTC, JorgeMarinoDev commented on src/engine/source/api/src/metrics/commands.cpp
> +        auto result = Metrics::instance().getListInstruments();
typo:   getListInstruments  -> getInstrumentsList

2023-03-09 19:53 UTC, JorgeMarinoDev commented on src/engine/source/cmds/src/start.cpp
> +        Metrics::instance().initMetrics("engine-metrics", "/var/ossec/engine/store/metrics/config/0");
Add TODO: Resolve fullpath accordingly.

2023-03-09 19:53 UTC, JorgeMarinoDev commented on src/engine/source/metrics/CMakeLists.txt
> +#    DOWNLOAD_ONLY
Remove Commented line.

2023-03-09 19:53 UTC, JorgeMarinoDev commented on src/engine/source/metrics/CMakeLists.txt
> +        "WITH_ZIPKIN ON"
Add TODO: Add build option and link zipkin to it. Define OT modules policy.

2023-03-09 19:53 UTC, JorgeMarinoDev commented on src/engine/source/metrics/CMakeLists.txt
> +${FETCHCONTENT_BASE_DIR}/opentelemetry-src/exporters/zipkin/include
same here . zipkin,

2023-03-09 19:53 UTC, JorgeMarinoDev commented on src/engine/source/metrics/include/dataHubExporter.hpp
> +#endif // __JSON_EXPORTER_H
+1

2023-03-09 19:53 UTC, JorgeMarinoDev commented on src/engine/source/metrics/include/dataHubInterface.hpp
> +#endif // _DATA_HUB_INTERFACE_H
add new line

2023-03-09 19:53 UTC, JorgeMarinoDev commented on src/engine/source/metrics/include/metrics.hpp
> +    std::unordered_map<std::string, bool> controller;
m_controller . severe. set descriptive name to the map.

2023-03-09 19:53 UTC, JorgeMarinoDev commented on src/engine/source/metrics/include/metricsContext.hpp
> +    std::chrono::milliseconds export_timeout_millis;
add TODO: Write proper doc to these members.

2023-03-09 19:54 UTC, JorgeMarinoDev commented
Also please sign the unsigned commits. @NahuFigueroa97 
https://github.com/wazuh/wazuh/pull/16339/commits/e8c22e0177992d2db5f93858c78ec02564b8c7e6
https://github.com/wazuh/wazuh/pull/16339/commits/22c178d5fb81f8f3be8162594ead907a2ad2d351

2023-03-09 21:51 UTC, cborla approved these changes
LGTM!

2023-03-09 21:51 UTC, soynof approved these changes

2023-03-10 14:48 UTC, JorgeMarinoDev approved these changes
LGTM

2023-03-10 14:49 UTC, merged