Add schema fields to Sonicwall decoder
wazuh/wazuh pull request #16409
Opened 2023-03-16 21:18 UTC by soynof

|Related Issue|
|---|
| #16406|

## Description

With the aim of expanding the coverage of the decoders, this PR adds the schema fields to Sonicwall decoder.

2023-03-16 21:21 UTC, cborla approved these changes
lgtm

2023-03-21 15:57 UTC, JorgeMarinoDev approved these changes
LGTM

2023-03-23 15:32 UTC, nmkoremblum requested changes
I am still receiving the following error:
```
Failed to read entry /root/repos/engine/src/engine/ruleset/decoders/sonicwall/sonicwall-firewall-generated.yml: An error occurred while trying to validate "decoder/sonicwall-firewall-generated/0": Parse stage: Building asset "decoder/sonicwall-firewall-generated/0" failed: Error building parser "logpar": An error occurred while parsing a log: Field 'observer.egress.interface.name' not found in schema
```

2023-03-23 18:04 UTC, nmkoremblum requested changes

2023-03-23 18:04 UTC, nmkoremblum commented on src/engine/ruleset/environments/wazuh-environment.yml
> +  - output/file-output/0
Please fix the newline at the end

2023-03-24 12:18 UTC, JcabreraC approved these changes
LGTM !

2023-03-24 12:19 UTC, merged