Validated the region passed before instantiating the service class
wazuh/wazuh pull request #16463
Opened 2023-03-20 20:07 UTC by nico-stefani

|Related issue|
|---|
| #16301 |

## Description

This PR closes #16301. Adds validation for the region passed to the service classes, in order to prevent requesting inexistent endpoints.

## Tests

```python
root@ubuntu-jammy:/home/vagrant/qa/tests/integration/test_aws# pytest -k 'cloudwatchlogs or inspector' --disable-warnings --tb=line --tier 0 test_regions.py
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/vagrant/qa/tests/integration, configfile: pytest.ini
plugins: metadata-2.0.2, html-3.1.1, testinfra-5.0.0
collected 24 items / 18 deselected / 6 selected

test_regions.py ......                                                                                                                                                                                        [100%]

============================================================================= 6 passed, 18 deselected, 2 warnings in 132.06s (0:02:12) ==============================================================================
```

2023-03-27 14:02 UTC, fdalmaup requested changes
Adding to the suggested change in the code, why does the module continue with its execution and not exit when an invalid region is passed? Wouldn't be better if the module shows an error and exits to alert the user of the wrong configuration?

2023-03-28 12:01 UTC, nico-stefani commented
> Adding to the suggested change in the code, why does the module continue with its execution and not exit when an invalid region is passed? Wouldn't be better if the module shows an error and exits to alert the user of the wrong configuration?

I chose this behavior because the module can receive multiple regions for one execution. Then if one valid and one invalid region are passed, the execution can process the valid one.

2023-03-29 12:54 UTC, nico-stefani commented on wodles/aws/aws_s3.py
> +                    debug(f"+++ WARNING: The region '{region}' is not a valid one.", 1)
As we discuss, the best solution, for now, is to raise an exception and quit the execution.  Until we have #16301.
I will do the changes.

2023-03-29 15:08 UTC, fdalmaup approved these changes
LGTM!

2023-04-14 07:55 UTC, merged