Refactor default_config method to take into account user config found in .aws/config file
wazuh/wazuh pull request #16531
Opened 2023-03-29 19:50 UTC by EduLeon12

|Related issue|
|---|
|Closes #14978|

## Description

The default_config was not taken into consideration that the _.aws/config_ file could not have the necessary retries parameters to avoid a throttling error a solution was made to not only look for the retry parameter but also all primary botocore parameters and set them into a botocore Config object.

More information on the solution is described here:
- #14978 

## Logs/Alerts example

Until now it was assumed that the retries parameter 

Now after running the module it will always check for the retries parameters on the config file if the file exists:

- No Retry Parameters
```
root@wazuh-master:/# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-kms -t custom -p dev -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: No retries configuration found in profile config generating default configuration for retries: mode standard - max_attempts 10
DEBUG: Created Config object using profile: dev parameters
DEBUG: +++ Marker: 2023/03/29
```
 
- With retry parameters

```
root@wazuh-master:/# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-kms -t custom -p dev -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Created Config object using profile: dev parameters
DEBUG: +++ Marker: 2023/03/29
DEBUG: +++ DB Maintenance
```

## Tests

Some scenarios were tested to ensure the module was functioning properly
Ex:

- No regions matching

```
root@wazuh-master:/# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-kms -t custom -r us-west-1 -p dev -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Region passed as parameter does not match region found in dev config file
```

- Api unit test:

```
(ut-3.9-venv) eduardoleon@pop-os:~/git/wazuh$ PYTHONPATH=/home/eduardoleon/git/wazuh/api:/home/eduardoleon/git/wazuh/framework python3 -m pytest api/api --disable-warnings
========================================== test session starts ===========================================
platform linux -- Python 3.9.9, pytest-7.0.1, pluggy-0.13.1
rootdir: /home/eduardoleon/git/wazuh/api
plugins: asyncio-0.18.1, aiohttp-1.0.4, trio-0.7.0, cov-3.0.0, anyio-3.6.2, metadata-2.0.2, html-3.0.0
asyncio: mode=auto
collected 544 items                                                                                      

api/api/controllers/test/test_active_response_controller.py .                                      [  0%]
api/api/controllers/test/test_agent_controller.py ...........................................      [  8%]
api/api/controllers/test/test_cdb_list_controller.py ......                                        [  9%]
api/api/controllers/test/test_ciscat_controller.py .                                               [  9%]
api/api/controllers/test/test_cluster_controller.py ........................                       [ 13%]
api/api/controllers/test/test_decoder_controller.py .......                                        [ 15%]
api/api/controllers/test/test_default_controller.py .                                              [ 15%]
api/api/controllers/test/test_experimental_controller.py ...............                           [ 18%]
api/api/controllers/test/test_manager_controller.py ..................                             [ 21%]
api/api/controllers/test/test_mitre_controller.py .......                                          [ 22%]
api/api/controllers/test/test_overview_controller.py .                                             [ 22%]
api/api/controllers/test/test_rootcheck_controller.py ....                                         [ 23%]
api/api/controllers/test/test_rule_controller.py ........                                          [ 25%]
api/api/controllers/test/test_sca_controller.py ..                                                 [ 25%]
api/api/controllers/test/test_security_controller.py ............................................. [ 33%]
......                                                                                             [ 34%]
api/api/controllers/test/test_syscheck_controller.py ....                                          [ 35%]
api/api/controllers/test/test_syscollector_controller.py .........                                 [ 37%]
api/api/controllers/test/test_task_controller.py .                                                 [ 37%]
api/api/controllers/test/test_vulnerability_controller.py ....                                     [ 38%]
api/api/models/test/test_model.py ...........................                                      [ 43%]
api/api/test/test_alogging.py ..................                                                   [ 46%]
api/api/test/test_authentication.py ...........                                                    [ 48%]
api/api/test/test_configuration.py ............................................                    [ 56%]
api/api/test/test_encoder.py ...                                                                   [ 56%]
api/api/test/test_middlewares.py ............                                                      [ 59%]
api/api/test/test_uri_parser.py ...                                                                [ 59%]
api/api/test/test_util.py ..............................................                           [ 68%]
api/api/test/test_validator.py ................................................................... [ 80%]
.................................................................................................. [ 98%]
........                                                                                           [100%]

==================================== 544 passed, 15 warnings in 2.23s ====================================
```

2023-03-30 13:55 UTC, nico-stefani requested changes

2023-03-30 13:55 UTC, nico-stefani commented on wodles/aws/aws_s3.py
> +                print('Invalid key, value found in config '.format(e))
Maybe?

```suggestion
                print('Invalid key or value found in config '.format(e))
```

2023-03-30 14:37 UTC, nico-stefani commented on wodles/aws/aws_s3.py
> +                    sys.exit(20)
As we discuss, it needed to remove this condition.

2023-03-31 12:58 UTC, nico-stefani requested changes

2023-03-31 12:58 UTC, nico-stefani commented on wodles/aws/aws_s3.py
> +#   20 - Matching regions error
This error code isn't longer used.

2023-03-31 12:58 UTC, nico-stefani commented on wodles/aws/aws_s3.py
> +        }
Still are typos of `s2` in this block

2023-03-31 12:58 UTC, nico-stefani commented on wodles/aws/aws_s3.py
> +                        f"retries: mode: {retries['mode']} - max_attempts: {retries['max_attempts']}",
```suggestion
                        "No retries configuration found in profile config. Generating default configuration for: "
                        f"retries: mode: {retries['mode']} - max_attempts: {retries['max_attempts']}",
```

2023-03-31 12:58 UTC, nico-stefani commented on wodles/aws/aws_s3.py
> +    def default_config(profile: str):
```suggestion
    def default_config(profile: str) -> dict:
```

2023-03-31 19:53 UTC, nico-stefani requested changes

2023-03-31 19:53 UTC, nico-stefani commented on wodles/aws/aws_s3.py
> +            profile_config = {option: aws_config.get(profile, option) for option in aws_config.options(profile)}
You must handle the error raised when the provided profile not exits.

```
root@9ab624e54776:/var/ossec# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-kms -t custom -p default -d2 --region us-east-1
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Error: No section: 'default'
Unknown error: No section: 'default'
Traceback (most recent call last):
  File "/var/ossec/wodles/aws/aws-s3.py", line 3833, in <module>
    main(sys.argv[1:])
  File "/var/ossec/wodles/aws/aws-s3.py", line 3759, in main
    bucket = bucket_type(reparse=options.reparse, access_key=options.access_key,
  File "/var/ossec/wodles/aws/aws-s3.py", line 2130, in __init__
    AWSBucket.__init__(self, **kwargs)
  File "/var/ossec/wodles/aws/aws-s3.py", line 682, in __init__
    WazuhIntegration.__init__(self, access_key=access_key,
  File "/var/ossec/wodles/aws/aws-s3.py", line 235, in __init__
    self.connection_config = self.default_config(profile=aws_profile)
  File "/var/ossec/wodles/aws/aws-s3.py", line 336, in default_config
    profile_config = {option: aws_config.get(profile, option) for option in aws_config.options(profile)}
  File "/var/ossec/framework/python/lib/python3.9/configparser.py", line 675, in options
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'default'
```

2023-04-03 12:39 UTC, nico-stefani submitted a review, later dismissed
LGTM!

2023-04-20 14:56 UTC, nico-stefani submitted a review, later dismissed

2023-04-26 16:30 UTC, nico-stefani submitted a review, later dismissed

2023-05-30 10:22 UTC, davidjiglesias requested changes

2023-05-30 10:22 UTC, davidjiglesias commented on wodles/aws/aws_s3.py
> +    """Creates a botocore.config.Config object with the specified profile and profile_config.
```suggestion
    """Create a botocore.config.Config object with the specified profile and profile_config.
```

2023-05-30 10:22 UTC, davidjiglesias commented on wodles/aws/aws_s3.py
> +    set into the boto_config
```suggestion
    set into the boto_config.
```

2023-05-30 10:22 UTC, davidjiglesias commented on wodles/aws/aws_s3.py
> +        """Sets the parameters found in user config file as a default configuration for client.
```suggestion
        """Set the parameters found in user config file as a default configuration for client.
```

2023-05-30 10:22 UTC, davidjiglesias commented on wodles/aws/aws_s3.py
> +        profile and retries parameters are set to avoid a throttling exception
```suggestion
        profile and retries parameters are set to avoid a throttling exception.
```

2023-05-30 10:22 UTC, davidjiglesias commented on wodles/aws/aws_s3.py
> +                Aws profile configuration to use
```suggestion
                Aws profile configuration to use.
```

2023-05-30 10:22 UTC, davidjiglesias commented on wodles/aws/aws_s3.py
> +            Configuration dictionary
```suggestion
            Configuration dictionary.
```

2023-05-30 10:22 UTC, davidjiglesias commented on wodles/aws/aws_s3.py
> +            KeyError when there is no region in user config file
```suggestion
            KeyError when there is no region in user config file.
```

2023-05-30 10:22 UTC, davidjiglesias commented on wodles/aws/aws_s3.py
> +            ValueError when there is an error parsing config file
```suggestion
            ValueError when there is an error parsing config file.
```

2023-05-30 10:22 UTC, davidjiglesias commented on wodles/aws/aws_s3.py
> +            configparser error when given profile does not exist in user config file
```suggestion
            configparser error when given profile does not exist in user config file.
```

2023-05-30 10:24 UTC, davidjiglesias requested changes
We need Integration tests to validate this change.

2023-06-27 10:21 UTC, Selutario commented
@EduLeon12, open a new issue to add Unit tests for these changes. The new issue should be blocked by:
- https://github.com/wazuh/wazuh/issues/13388

2023-06-29 12:22 UTC, Selutario approved these changes

2023-06-29 12:40 UTC, merged