16677 improve logical expression
wazuh/wazuh pull request #16863
Opened 2023-04-25 00:38 UTC by NahuFigueroa97

2023-04-26 04:10 UTC, JorgeMarinoDev commented on src/engine/test/source/builder/builders/stageBuilderCheck_test.cpp
> +                                    "Check stage: The \">=\" operator only allows operate with numbers or string")));
Are we sure Check stage all cases in Testing::values map to the same fmt string "`Check stage: The \">=\" operator only allows operate with numbers or string""`

2023-04-26 08:17 UTC, JavierBejMen requested changes

2023-04-26 08:17 UTC, JavierBejMen commented on src/engine/source/builder/builders/stageBuilderCheck.cpp
>              value = term.substr(0, pos1) + term.substr(pos2);
We don't set valueJson when is a helper function, this results in the operation builder generating a function to check if the field is null and not the desired function. Add tests for this use case and fix the implementation.

2023-04-26 17:18 UTC, JorgeMarinoDev commented on src/engine/test/source/builder/builders/stageBuilderCheck_test.cpp
> +                                    "Check stage: The \">=\" operator only allows operate with numbers or string")));
Disregard. Clear now.

2023-04-26 17:19 UTC, JorgeMarinoDev approved these changes
LGTM

2023-04-26 20:07 UTC, cborla approved these changes
LGTM

2023-04-28 15:17 UTC, juliancnn approved these changes
LGTM!

2023-05-02 12:40 UTC, merged