Handle case where the "date_start" is a str
wazuh/wazuh pull request #16986
Opened 2023-05-02 18:25 UTC by RamosFe

|Related issue|
|---|
| [#16981](https://github.com/wazuh/wazuh/issues/16981) |

## Description

All the status properties inside the `MasterHandler` are saved as a `String` containing the date of the event.
Example:
https://github.com/wazuh/wazuh/blob/13228ade7786495fd6d75f34775efcfc30eeee64/framework/wazuh/core/cluster/master.py#L693-L696

The data from `send_full_agent_groups_status` and `sync_agent_info_status` is used in the `process_request` method as a `start_date`, so it needs to be converted to a `date` type. The following code was added to use a type guard in case the value is an `String` and convert it to the desired `date` type:

https://github.com/wazuh/wazuh/blob/13228ade7786495fd6d75f34775efcfc30eeee64/framework/wazuh/core/cluster/master.py#L262-L277

2023-05-04 07:44 UTC, Selutario requested changes

2023-05-04 07:44 UTC, Selutario commented on framework/wazuh/core/cluster/master.py
> +            start_time = self.send_agent_groups_status['date_start']
```suggestion
            start_time = self.send_full_agent_groups_status['date_start']
```

2023-05-04 14:04 UTC, Selutario approved these changes

2023-05-09 08:56 UTC, davidjiglesias approved these changes

2023-05-09 08:56 UTC, merged