Replace agents group column with the belongs relationship table
wazuh/wazuh pull request #17127
Opened 2023-05-15 17:52 UTC by GGP1

|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/16285 |

## Description

Replaced the `group` column from `agents` table with the agent-group links stored in the `belongs` table. The code now refers to group names instead of group IDs.

## Tests

I ran the tests locally and all of them passed, except for the ones mentioned in https://github.com/wazuh/wazuh/issues/16918. So it's expected that some checks will fail.

2023-09-22 16:21 UTC, GGP1 commented on api/test/integration/test_agent_GET_endpoints.tavern.yaml
> +          total_affected_items: 1
This was a bug actually, we returned one element but a `total_affected_items` of `2`

2023-09-26 16:17 UTC, nico-stefani approved these changes
LGTM

2023-09-27 15:48 UTC, Selutario requested changes

2023-09-27 18:24 UTC, GGP1 commented on framework/wazuh/core/agent.py
> +            self.request[field_filter] = f"%{q_filter['value']}%"
001 -> default, default2
002 -> default
003 -> default2

<details><summary><code>/agents?q=group=default&select=id,group</code></summary>

```json
{
    "data": {
        "affected_items": [
            {
                "group": [
                    "default",
                    "default2"
                ],
                "id": "001"
            },
            {
                "group": [
                    "default"
                ],
                "id": "002"
            }
        ],
        "total_affected_items": 2,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "All selected agents information was returned",
    "error": 0
}
```

</details>

<details><summary><code>/agents?q=group~default&select=id,group</code></summary>

```json
{
    "data": {
        "affected_items": [
            {
                "group": [
                    "default",
                    "default2"
                ],
                "id": "001"
            },
            {
                "group": [
                    "default"
                ],
                "id": "002"
            },
            {
                "group": [
                    "default2"
                ],
                "id": "003"
            }
        ],
        "total_affected_items": 3,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "All selected agents information was returned",
    "error": 0
}
```

</details>

<details><summary><code>/agents?q=group~default2&select=id,group</code></summary>

```json
{
    "data": {
        "affected_items": [
            {
                "group": [
                    "default",
                    "default2"
                ],
                "id": "001"
            },
            {
                "group": [
                    "default2"
                ],
                "id": "003"
            }
        ],
        "total_affected_items": 2,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "All selected agents information was returned",
    "error": 0
}
```

</details>

<details><summary><code>/agents?q=group!=default&select=id,group</code></summary>

```json
{
    "data": {
        "affected_items": [
            {
                "group": [
                    "default2"
                ],
                "id": "003"
            }
        ],
        "total_affected_items": 1,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "All selected agents information was returned",
    "error": 0
}
```

</details>

2023-09-28 11:00 UTC, Selutario approved these changes

2023-09-28 11:00 UTC, merged