Add engine schema validation
wazuh/wazuh pull request #17134
Opened 2023-05-16 10:14 UTC by JavierBejMen

|Related issue|
|---|
| Closes #16856 |

The solution presented in this PR moves forward regarding the integrity of the indexer and improves user feedback on schema-related errors.

Here is a brief overview of the changes implemented:

Schema Management Module: A foundational module has been added to manage the schema. This module is the bedrock for the new schema verification feature and forms the basis for the subsequent improvements.

Schema Loading and Verification: Schema loading from JSON descriptions has been implemented, alongside schema verification on basic operations. This ensures that any interactions with the schema are validated against the definitions, enhancing data integrity and reducing the risk of errors.

Field Naming Validation: Naming validation has been added. This addition will further safeguard against potential inconsistencies or errors in the schema, ensuring that field naming adheres strictly to the schema definition.

Updated Ruleset and Tooling: Finally, the ruleset and tooling have been updated to work seamlessly with the new schema verification feature.

2023-05-17 16:39 UTC, LucioDonda requested changes

2023-05-17 16:39 UTC, LucioDonda commented on src/engine/test/source/schemf/CMakeLists.txt
> +# gtest_discover_tests(field_test)
shouldn't this be uncommented?

2023-05-18 14:41 UTC, JavierBejMen commented on src/engine/source/builder/builders/operationBuilder.cpp
> +    std::string operationName;
Initialization of the variables needs to be safe guarded for exceptions, to make it const requires excessive boilerplate

2023-05-18 14:42 UTC, JavierBejMen commented on src/engine/test/source/schemf/CMakeLists.txt
> +# gtest_discover_tests(field_test)
My mistake, done.

2023-05-18 18:19 UTC, LucioDonda approved these changes
LGTM!

2023-05-18 20:06 UTC, nbertoldo approved these changes
LGTM!

2023-05-19 10:32 UTC, JcabreraC approved these changes
LGTM !

2023-05-19 10:40 UTC, merged