Vulnerability Detector W10 & W11
wazuh/wazuh pull request #17178
Opened 2023-05-19 17:37 UTC by lsayanes

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/15160|

## Description

The issue originates from the change in the **CPE** format that has been applied in **NVD**, as previously the **Windows 11** CPE was:  

- [cpe:2.3-o:microsoft:windows_11:21h2:::::::*](https://nvd.nist.gov/products/cpe/detail/46138D1E-853D-4899-9D8F-E1B0E8D484D0?namingFormat=2.3&orderBy=CPEURI&keyword=cpe%3A2.3%3Ao%3Amicrosoft%3Awindows_11%3A-%3A*%3A*%3A*%3A*%3A*%3A*%3A*&status=FINAL%2CDEPRECATED)

**This has been deprecated and the format is:**

- [cpe:2.3-o:microsoft:windows_11_21h2:-::::::x64](https://nvd.nist.gov/products/cpe/detail/E4604687-B03E-478C-B119-226D2BF51448?namingFormat=2.3&orderBy=CPEURI&keyword=cpe%3A2.3%3Ao%3Amicrosoft%3Awindows_11_22h2%3A-%3A*%3A*%3A*%3A*%3A*%3A*%3A*&status=FINAL%2CDEPRECATED)

This resulted in a mismatch with the corresponding vulnerability and therefore it was not reported.
Examples:

> Old CPE: https://nvd.nist.gov/vuln/detail/CVE-2022-44698#vulnConfigurationsArea
> New CPE: https://nvd.nist.gov/vuln/detail/CVE-2023-28250#vulnConfigurationsArea

The "_product_name_" build chain for **Windows 10** and **Windows 11** has been updated adding the `wm_vuldet_build_product_name` function, with it the CVE structure is generated for each agent, 
the rest was to update the code to detect well the vulnerabilities of the systems:

```
W11 21H2 & W11 22H2
W10 22H2 & W10 1809 
```
Among the most important changes we have **removed** the if in which it entered when the generated CPE had a valid version and then it would scan all the vulnerabilities that did not have version (`-`) in the CPE or the version was generic (`*`) in order not to cause false positives, in the function `wm_vuldet_get_vuln_vulnvd_cpe`:

```
            // For a WIN10 O.S product with a valid product version, discard those
            // CPE's that matched using '-' or '*'.
            if (agent_cpe->part && (agent_cpe->part[0] == 'o') && cpe_version &&
                agent_cpe->vendor && strcmp(cpe_version, agent_cpe->version) &&
                (agent->dist_ver == FEED_W10 || agent->dist_ver == FEED_W11) {
                continue;
            }
```

The following CPEs were discarded so as not to generate false positives:

- o:microsoft:windows_10:*
- o:microsoft:windows_10:-

Accepting only:

- o:microsoft:windows_10:<version>

Now it is not necessary, because the `CPE` product already includes the version, so we can accept all 3 CPEs:

- microsoft:windows_10_<version>:os_version
- microsoft:windows_10_<version>:*
- microsoft:windows_10_<version>:-

An example of this issue [here](https://wazuh-team.slack.com/archives/C04FFKZ0ABS/p1684255745980979?thread_ts=1683559264.197009&cid=C04FFKZ0ABS)
 

## Logs/Alerts example
`Windows 11 22h2 patched`
```
[...]
2023/05/17 19:00:45 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector.c:2804 at wm_vuldet_check_agent_vulnerabilities(): DEBUG: (5438): A full scan will be run on agent '004'
2023/05/17 19:00:45 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector.c:5682 at wm_vuldet_collect_agent_software(): DEBUG: (5437): Collecting agent '004' software.
2023/05/17 19:00:45 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector.c:6974 at wm_vuldet_insert_agent_data(): DEBUG: (5446): The CPE 'o:microsoft:windows_11_22h2:10.0.22621.1702::::::x64:' from the agent '004' was indexed.
2023/05/17 19:00:45 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector_nvd.c:3272 at wm_vuldet_add_dic_cpe(): DEBUG: (5446): The CPE 'a:wazuh:wazuh:4.4.1::::::x86:' from the agent '004' was indexed.
2023/05/17 19:00:45 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector.c:2827 at wm_vuldet_check_agent_vulnerabilities(): INFO: (5450): Analyzing agent '004' vulnerabilities.
2023/05/17 19:00:45 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector_nvd.c:1859 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5451): Analyzing NVD vulnerabilities for agent '004'
2023/05/17 19:00:45 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector_nvd.c:1871 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'find NVD' vulnerabilities in agent '004'
2023/05/17 19:00:45 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector_nvd.c:1873 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5466): Sending vulnerabilities report for agent '004'
2023/05/17 19:00:45 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector_nvd.c:1883 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'report' vulnerabilities in agent '004'
2023/05/17 19:00:45 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector.c:2846 at wm_vuldet_check_agent_vulnerabilities(): INFO: (5471): Finished vulnerability assessment for agent '004'
2023/05/17 19:00:45 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector.c:2847 at wm_vuldet_check_agent_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'scan' vulnerabilities in agent '004'
```

`Windows 11 21h2 patched`
```
[...]
2023/05/17 19:00:46 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector.c:2799 at wm_vuldet_check_agent_vulnerabilities(): DEBUG: (5491): A baseline scan will be run on agent '006'
2023/05/17 19:00:46 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector.c:5682 at wm_vuldet_collect_agent_software(): DEBUG: (5437): Collecting agent '006' software.
2023/05/17 19:00:46 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector.c:6974 at wm_vuldet_insert_agent_data(): DEBUG: (5446): The CPE 'o:microsoft:windows_11_21h2:10.0.22000.318::::::x64:' from the agent '006' was indexed.
2023/05/17 19:00:46 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector_nvd.c:3272 at wm_vuldet_add_dic_cpe(): DEBUG: (5446): The CPE 'a:wazuh:wazuh:4.4.1::::::x86:' from the agent '006' was indexed.
2023/05/17 19:00:46 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector.c:2827 at wm_vuldet_check_agent_vulnerabilities(): INFO: (5450): Analyzing agent '006' vulnerabilities.
2023/05/17 19:00:46 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector_nvd.c:1859 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5451): Analyzing NVD vulnerabilities for agent '006'
2023/05/17 19:00:46 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector_nvd.c:1871 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'find NVD' vulnerabilities in agent '006'
2023/05/17 19:00:46 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector_nvd.c:1873 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5466): Sending vulnerabilities report for agent '006'
2023/05/17 19:00:46 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector_nvd.c:1883 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'report' vulnerabilities in agent '006'
2023/05/17 19:00:46 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector.c:2846 at wm_vuldet_check_agent_vulnerabilities(): INFO: (5471): Finished vulnerability assessment for agent '006'
2023/05/17 19:00:46 wazuh-modulesd:vulnerability-detector[225176] wm_vuln_detector.c:2847 at wm_vuldet_check_agent_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'scan' vulnerabilities in agent '006'

```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
 [...]

2023-05-19 19:13 UTC, mateocervilla commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
> +
```suggestion
```

2023-05-19 19:32 UTC, mateocervilla requested changes
Unnecessary use of a `pr_name` variable

2023-05-19 19:32 UTC, mateocervilla commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
> +    char *pr_name = NULL;
```suggestion
```

2023-05-19 19:32 UTC, mateocervilla commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
> +            win_pr = pr_name;
```suggestion
            win_pr = wm_vuldet_build_product_name(FEED_W10 == agent->dist_ver ? PR_WIN10 : PR_WIN11, ver_aux);
```

2023-05-19 19:32 UTC, mateocervilla commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
> +
```suggestion
```

2023-05-19 19:37 UTC, mateocervilla commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
> +
```suggestion
```

2023-05-19 20:23 UTC, lsayanes commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
> +
done

2023-05-19 20:23 UTC, lsayanes commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
> +
done

2023-05-19 23:08 UTC, mateocervilla approved these changes

2023-05-22 12:39 UTC, MarcelKemp commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c
> +                    if (agent_cpe->part && (agent_cpe->part[0] == 'o') &&
Include a comment explaining why this condition is added.
A possible example: 
```c
// For W10 and W11, we bypass the versioning check on OS vulnerabilities, with the NVD to be scanned by the MSU.
```

2023-05-22 12:43 UTC, MarcelKemp commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
> +char *wm_vuldet_build_product_name(const char *pr, const char *ver) {
Add the function definition, together with its Doxygen documentation, please.

2023-05-22 12:57 UTC, MarcelKemp commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c
> +STATIC char *wm_vuldet_generate_msu_request(cpe *s_cpe, vu_feed dist_ver, char *win_version);
```suggestion

/**
 * @brief Generates the vulnerability request to the MSU DB, in order to check the corresponding hotfixes.
 * @param s_cpe CPE generated for the Windows agent.
 * @param dist_ver Version of the Windows distribution used in the agent.
 * @param win_version Display version of Windows agent (1909, 21H2, 22H2, etc).
 * @return Request to check the MSU DB.
 */
STATIC char *wm_vuldet_generate_msu_request(cpe *s_cpe, vu_feed dist_ver, char *win_version);
```

2023-06-02 06:30 UTC, merged