Feature/15994 api get decoder rule file with relative path
wazuh/wazuh pull request #17206
Opened 2023-05-23 13:17 UTC by mhamra

|Related issue|
|---|
|[#15994](https://github.com/wazuh/wazuh/issues/15994)|

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

2023-06-28 15:10 UTC, RamosFe approved these changes
All tests passed! LGTM 🥇 

> Passed to `on-hold` because the checks don't pass.

2023-07-10 08:30 UTC, Selutario requested changes

2023-07-11 13:18 UTC, mhamra commented on framework/wazuh/decoder.py
> +def get_decoder_file(filename: str, raw: bool = False, default_ruleset: bool = True) -> Union[str, AffectedItemsWazuhResult]:
Fixed in recent commit

2023-07-13 01:12 UTC, mhamra commented
### UPDATE

git rebase 4.6.0 done

2023-07-13 18:34 UTC, mhamra commented on framework/wazuh/decoder.py
> +                                  relative_dirname=relative_dirname).affected_items
- Changed in recent commit
https://github.com/wazuh/wazuh/blob/f217ffa4e64c5cbe731fd8d46619b914304e4abe/framework/wazuh/decoder.py#L203-L207
- Added new test case; see line 141
https://github.com/wazuh/wazuh/blob/f217ffa4e64c5cbe731fd8d46619b914304e4abe/framework/wazuh/tests/test_decoder.py#L135-L146

2023-07-13 18:35 UTC, mhamra commented on api/api/controllers/decoder_controller.py
> +        relative directory where the decoder is located. Default None.
Fixed in the last pushed commit. Thanks, @Selutario

2023-07-13 18:35 UTC, mhamra commented on framework/wazuh/decoder.py
> +        relative directory where de decoder is found. Default None.
Fixed in the last pushed commit. Thanks, @Selutario

2023-07-13 18:39 UTC, mhamra commented on framework/wazuh/decoder.py
> +from os.path import join, exists, commonpath, basename, relpath, normpath
Fixed in the last pushed commit. Thanks, @Selutario!

2023-07-13 18:39 UTC, mhamra commented on framework/wazuh/rule.py
> +from os.path import exists, join, abspath, commonpath, basename, relpath, normpath
Fixed in the last pushed commit. Thanks, @Selutario!

2023-07-13 18:42 UTC, mhamra commented on framework/wazuh/rule.py
> +                                  relative_dirname=relative_dirname).affected_items
- Fixed in the last pushed commit, but I implemented the fix differently.
https://github.com/wazuh/wazuh/blob/f217ffa4e64c5cbe731fd8d46619b914304e4abe/framework/wazuh/rule.py#L331-L335
- Added new test case; see line 242
https://github.com/wazuh/wazuh/blob/f217ffa4e64c5cbe731fd8d46619b914304e4abe/framework/wazuh/tests/test_rule.py#L237-L246

Thanks for the observation @Selutario!

2023-07-13 18:43 UTC, mhamra commented on framework/wazuh/rule.py
> +        # relative path length
Fixed in the last pushed commit. Thanks, @Selutario!

2023-07-14 09:13 UTC, Selutario approved these changes

2023-07-14 09:14 UTC, merged