Engine | Suricata integration
wazuh/wazuh pull request #17226
Opened 2023-05-24 15:49 UTC by 72nomada

|Related issue|
|---|
||

Suricata integration.

2023-05-25 09:36 UTC, JcabreraC requested changes

2023-05-25 09:36 UTC, JcabreraC commented on src/engine/ruleset/integrations/suricata/agent/deb/ossec.conf
> +  </ossec_config>
```suggestion
<ossec_config>
  <localfile>
    <!-- Edit location to appropriate path if needed -->
    <location>/var/log/suricata/eve.json</location>
    <log_format>json</log_format>
  </localfile>
</ossec_config>

<!--
<ossec_config>
  <localfile>
    <!-- Edit location to appropriate path if needed -->
    <location>/var/log/suricata/eve.json</location>
    <log_format>json</log_format>
    <label key="event.module">suricata</label>
  </localfile>
</ossec_config>
-->
```

2023-05-25 09:36 UTC, JcabreraC commented on src/engine/ruleset/integrations/suricata/agent/rpm/ossec.conf
> +  </ossec_config>
```suggestion
<ossec_config>
  <localfile>
    <!-- Edit location to appropriate path if needed -->
    <location>/var/log/suricata/eve.json</location>
    <log_format>json</log_format>
  </localfile>
</ossec_config>

<!--
<ossec_config>
  <localfile>
    <!-- Edit location to appropriate path if needed -->
    <location>/var/log/suricata/eve.json</location>
    <log_format>json</log_format>
    <label key="event.module">suricata</label>
  </localfile>
</ossec_config>
-->
```

2023-05-25 09:36 UTC, JcabreraC commented on src/engine/ruleset/integrations/suricata/agent/windows/ossec.conf
> +  </ossec_config>
```suggestion
<ossec_config>
  <localfile>
    <!-- Edit location to appropriate path if needed -->
  <location>WINDOWS_PATH\eve.json</location>
  <log_format>json</log_format>
  </localfile>
</ossec_config>

<ossec_config>
  <localfile>
    <!-- Edit location to appropriate path if needed -->
    <location>WINDOWS_PATH\eve.json</location>
    <log_format>json</log_format>
    <label key="event.module">suricata</label>
  </localfile>
</ossec_config>
-->
```

2023-05-25 09:36 UTC, JcabreraC commented on src/engine/ruleset/integrations/suricata/decoders/suricata.yml
> +  - ~json.flow_id: +exists
```suggestion
check:
  - ~json.event_type: +exists
  - ~json.flow_id: +exists
#TODO: Once the events arrive tagged, uncomment these lines below and remove the above `event.original`
# - event.module: suricata
```

2023-05-26 14:31 UTC, JcabreraC approved these changes
LGTM !

2023-05-26 14:57 UTC, JavierBejMen approved these changes
LGTM

2023-05-26 15:00 UTC, JcabreraC approved these changes

2023-05-26 15:59 UTC, merged