Enable alert forwarding for Analysisd for all version
wazuh/wazuh pull request #17306
Opened 2023-05-30 10:04 UTC by GabrielEValenzuela

|Related issue|
|---|
| #16351  |

This PR aims to add a new feature within the Analysisd module which is the possibility to forward alerts coming from the module in a JSON format to a socket where it will communicate with the [Fluentd](https://www.fluentd.org/) software.
While this feature is intended for AIX, it can be easily exported to other operating systems.

## Description of the new feature

Based on the implementation made for [logcollector](https://documentation.wazuh.com/current/user-manual/capabilities/fluent-forwarder.html), which can be summarized by the following sequence diagram:

### Sequence diagram logcollector and fluentd
<details><summary>Figure</summary>

![image](https://user-images.githubusercontent.com/27935340/233223486-f42db949-74e1-491a-a949-ff003cb3ad08.png)

</details>

We proceeded to generalize the structure containing the information relevant to the configuration defined for the `socket`, in such a way that this structure could be used for both `logcollector` and `analysisd`. 

```c
typedef struct _socket_fw {
    char *name;
    char *location;
    int mode;
    char *prefix;
    int socket;
    time_t last_attempt;
} socket_forwarder; //Struct defined in shared.h, shared for both logcollector and analysisd
```

Once this was done, since the function in charge of reading this configuration from `ossec.conf` was designed to work with logcollector and lacked the _open/closed principle_, a new definition of the type of socket to be read was added as well as a function capable of reading the structure from analysisd. 
Both functions replicate its logic in several aspects, but work with a different data type.

```c
#define CLGCSOCKET    010000000 //Redefinition.
#define CANDSOCKET    020000000 //New definition.
#define CLOGTEST      040000000 //Redifinition due new change.
```

Once this is done, for analysisd configuration, unlike the already established [localfile](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html), the socket targets are added inside the global section of the configuration, so this structure now contains the data needed to store these targets, as well as the logic needed to read them from `ossec.conf`.

```c
    /* Vector of targets forwarder */
    char** forwarders_list;

    /* Vector of socket configuration from ossec.conf <socket/> */
    socket_forwarder *socket_list;
```

Finally, similar to the function in charge of reading the configuration socket, a new function `SendJSONtoSCK` was added that shares a similar logic, but receives as argument the event that it then transforms into a JSON format string.
Unlike the "slibing" function, it does not retry to send the message if the socket is not available.

```c
/**
 * Sends a JSON message to a socket. If the socket has not been created yet it will be created based on
 * the target information. If a message fails to be sent the method will not try to send it again until *sock_fail_time* has passed
 * @param new_event Event structure with the information.
 * @return
 * UNIX ->  1 message was discarded
 * UNIX -> -1 invalid protocol or cannot create socket
 * UNIX ->  0 message was sent
 * WIN32 -> -1 invalid target
 * WIN32 -> 0 valid target
 * Notes: (UNIX) If the message is not sent because the socket is busy, the return code will be 0
 */
int SendJSONtoSCK(Eventinfo *new_event);
```

All this description can be summarized by the following sequence diagram:

### Example of configuration

<details open><summary>ossec.conf</summary>

```xml
<global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>no</email_notification>
    <smtp_server>smtp.example.wazuh.com</smtp_server>
    <email_from>wazuh@example.wazuh.com</email_from>
    <email_to>recipient@example.wazuh.com</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>10m</agents_disconnection_time>
    <forward_to>fluentd</forward_to> 
  </global>

 
  <fluent-forward>
	<enabled>yes</enabled>
	<tag>debug.test</tag>
	<socket_path>/var/ossec/var/run/fluent.sock</socket_path>
	<address>localhost</address>
	<port>24224</port>
  </fluent-forward>

  <socket>
	<name>fluentd</name> 
	<location>var/run/fluent.sock</location>  
	<mode>udp</mode>
  </socket>
```
</details>

### Sequence diagram analysisd and fluentd

<details><summary>Figure</summary>

![image](https://user-images.githubusercontent.com/27935340/233223711-0c241f72-5d77-4909-bfbc-08a433c144d8.png)

</details>

### Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [x] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [x] Added unit tests (for new features)
- [ ] Stress test for affected components

2023-06-19 17:55 UTC, MarcelKemp requested changes

2023-06-19 17:55 UTC, MarcelKemp commented on src/config/socket-config.c
> +int Read_LogCollecSocket(XML_NODE node, __attribute__((unused)) void *d1, void *d2) {
Did you mean this?
```suggestion
int Read_LogCollecSocket(XML_NODE node, void *d1, __attribute__((unused)) void *d2) {
```

2023-06-19 18:16 UTC, GabrielEValenzuela commented on src/config/socket-config.c
> +int Read_LogCollecSocket(XML_NODE node, __attribute__((unused)) void *d1, void *d2) {
Thanks ! You have right !

2023-06-20 18:24 UTC, MarcelKemp approved these changes

2023-10-09 12:26 UTC, tdrauncieal commented
leave a test results:
![2023-10-07_09-18](https://github.com/wazuh/wazuh/assets/93778492/57bbc094-d6fa-4eab-b756-1c26bb25c460)

2023-10-09 12:27 UTC, tdrauncieal approved these changes

2023-10-26 14:18 UTC, MarcelKemp approved these changes

2023-10-26 23:03 UTC, merged