Prevent invalid free of stack memory at osquery integration module
wazuh/wazuh pull request #17463
Opened 2023-06-07 16:27 UTC by vikman90

|Related issue|
|---|
|Closes #17440|

This PR aims to fix a bug that mishandles logging data from osquery.

There is a 4 KB buffer allocated in the thread's stack that receives each log from the osquery output. The log parser may call `wm_osquery_already_running()` to match a message like:

> osqueryd (1000) is already running

This function should return a heap-allocated string containing either the process PID, `"unknown"`, or a null pointer (if the message did not match the pattern). However, a recent change let the function return the source string itself. As the caller assumes that the returned string is independent and heap-allocated, it tries to free it after, causing an invalid free hazard.

## Proposed fix

Let `wm_osquery_already_running()` return `NULL` if the input string matches no pattern.

2023-06-08 18:28 UTC, thejbte requested changes

2023-06-08 18:28 UTC, thejbte commented on src/wazuh_modules/wm_osquery_monitor.c
>          }
This will work.
```suggestion
        } else {
            text = NULL;
        }
```

2023-06-08 18:28 UTC, thejbte commented on src/wazuh_modules/wm_osquery_monitor.c
> +    return NULL;
```suggestion
    return text;
```

2023-06-09 15:26 UTC, thejbte submitted a review, later dismissed

2023-06-26 05:38 UTC, Dwordcito commented
@vikman90 is this PR blocked by this another one https://github.com/wazuh/wazuh/pull/17636 ? we may be deadlocked.

2023-06-27 14:29 UTC, merged