Fixed heap memory increase
wazuh/wazuh pull request #17577
Opened 2023-06-14 01:12 UTC by cborla

|Related issue|
|---|
|#17575|

## Description
An increase in the use of memory by the Engine without any justification has been detected, the objective of this Issue is to investigate the cause of this and propose a possible solution.

## DoD
 - [x] Reproduce the memory leak in local, testing it in main branch #11334 . 
 - [x] Memory leak analysis.
 - [x] Porpose a code fix.
 - [x] Check that all test run on green.

2023-06-14 01:21 UTC, cborla commented
## Reproduce the memory leak
In this case the memory usage is increased by rapidjson.
- Branch: [11334-dev-new-wazuh-engine](https://github.com/wazuh/wazuh/tree/11334-dev-new-wazuh-engine)

![11334_leak](https://github.com/wazuh/wazuh/assets/41765669/009d61df-c996-4a41-b53d-f9c3733845a1)

2023-06-14 01:23 UTC, cborla commented
## Tets with proposed fix.
In this case, an increase in memory is observed due to rapidjson.
- Branch: [17575-engine-metrics-memory-leak](https://github.com/wazuh/wazuh/tree/17575-engine-metrics-memory-leak)

![11334_no_leak](https://github.com/wazuh/wazuh/assets/41765669/20130ba6-d178-4d0f-b207-d0728c4257e7)

2023-06-14 09:59 UTC, JorgeMarinoDev commented on src/engine/source/metrics/src/dataHub.cpp
> +    m_resources.insert(std::make_pair(scope, object));
Please check if we do need both lines (erase and insert). Try without erase.

2023-06-14 13:34 UTC, JorgeMarinoDev commented on src/engine/source/metrics/src/dataHub.cpp
> +    m_resources.insert(std::make_pair(scope, object));
[] operator from std::map triggers this leak.

2023-06-14 13:35 UTC, JorgeMarinoDev approved these changes
LGTM now. Thank you.

2023-06-15 12:47 UTC, nmkoremblum approved these changes

2023-06-29 14:22 UTC, nmkoremblum requested changes

2023-06-29 14:22 UTC, nmkoremblum commented on src/engine/source/server/src/endpoints/unixStream.cpp
> +            } else  if (client->closing())
Please, fix style here

2023-06-29 15:24 UTC, JorgeMarinoDev commented on src/engine/source/cmds/src/start.cpp
> +    cmd::details::StackExecutor exitHanlder {};
small fix typo exitHanlder  to exitHandler

2023-06-29 15:26 UTC, JorgeMarinoDev approved these changes
LGTM. Just small typo suggested change.

2023-06-29 15:57 UTC, nmkoremblum approved these changes
LGTM

2023-06-29 16:08 UTC, LucioDonda approved these changes
Minor changes in comments but it LGTM!

2023-06-29 17:29 UTC, merged