Refactor the AWS module and add its Unit Tests
wazuh/wazuh pull request #17623
Opened 2023-06-21 15:42 UTC by fdalmaup

|Related issue|
|---|
| #13388 |

> @CarlosRS9 initially developed this issue.

## Description

In https://github.com/wazuh/wazuh/issues/13388, we have refactored the AWS module, making it simpler to maintain and extend. The new structure of the AWS integration is below:

```
├── aws_s3.py
├── aws_tools.py
├── wazuh_integration.py
├── buckets_s3/
│   ├── aws_bucket.py
│   ├── cloudtrail.py
│   ├── config.py
│   ├── guardduty.py
│   ├── load_balancers.py
│   ├── server_access.py
│   ├── umbrella.py
│   ├── vpcflow.py
│   └── waf.py
├── services/
│   ├── aws_service.py
│   ├── cloudwatchlogs.py
│   └── inspector.py
├── subscribers/
│   ├── sl_subscriber_bucket.py
│   ├── sqs_queue.py
└── tests/
    ├── aws_utils.py
    ├── conftest.py
    ├── data/
    │       ...
    ├── test_aws_bucket.py
    ├── test_aws_s3.py
    ├── test_aws_service.py
    ├── test_cloudtrail.py
    ├── test_cloudwatchlogs.py
    ├── test_config.py
    ├── test_guardduty.py
    ├── test_inspector.py
    ├── test_load_balancers.py
    ├── test_server_access.py
    ├── test_sl_subscriber_bucket.py
    ├── test_sqs_queue.py
    ├── test_tools.py
    ├── test_umbrella.py
    ├── test_vpcflow.py
    ├── test_waf.py
    └── test_wazuh_integration.py
```

Also, we have reviewed, updated, and replaced existing unit tests for the module while adding new ones to expand code coverage up to 95%. This is the actual coverage using the new unit tests:
```
---------- coverage: platform linux, python 3.9.17-final-0 -----------
Name                                  Stmts   Miss  Cover   Missing
-------------------------------------------------------------------
__init__.py                               0      0   100%
aws_s3.py                                81     14    83%   48-49, 113, 155, 161-170
aws_tools.py                            102      2    98%   31-32
buckets_s3/__init__.py                   10      0   100%
buckets_s3/aws_bucket.py                478     26    95%   574, 591-596, 601-602, 605, 630, 635, 656, 695, 712, 895-904, 972-973
buckets_s3/cloudtrail.py                 26      3    88%   35-38
buckets_s3/config.py                     91      7    92%   51, 148, 165, 174, 185-186, 195
buckets_s3/guardduty.py                  64      1    98%   35
buckets_s3/load_balancers.py             69      0   100%
buckets_s3/server_access.py             135     13    90%   25, 42, 49-52, 88, 92, 155-156, 171, 174-175, 179-180
buckets_s3/umbrella.py                   22      0   100%
buckets_s3/vpcflow.py                   103     11    89%   7-9, 155, 169-177, 197, 238-239
buckets_s3/waf.py                        38      0   100%
services/__init__.py                      4      0   100%
services/aws_service.py                  44      0   100%
services/cloudwatchlogs.py              171      1    99%   456
services/inspector.py                    48      4    92%   83-90, 114
subscribers/__init__.py                   3      0   100%
subscribers/sl_subscriber_bucket.py      35      3    91%   8-10
subscribers/sqs_queue.py                 63      4    94%   64-66, 127
wazuh_integration.py                    165      3    98%   7-9
-------------------------------------------------------------------
TOTAL                                  1752     92    95%
```

It was necessary to replace existing unit tests and create them from the start to achieve this. 

The extensive code review has resulted in several optimizations, changes, and removal of some parts of the code. Because of that, integration tests and manual testing were necessary to ensure everything worked as expected.

<details><summary>AWS integration tests</summary>

    /wazuh-qa/tests/integration/test_aws# pytest -vvx .
    ====================================================================== test session starts ======================================================================
    platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0 -- /usr/bin/python3
    cachedir: .pytest_cache
    metadata: {'Python': '3.10.6', 'Platform': 'Linux-5.19.0-1025-aws-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.1.2', 'pluggy': '1.0.0'}, 'Plugins': {'testinfra': '5.0.0', 'html': '3.1.1', 'metadata': '3.0.0'}}
    rootdir: /wazuh-qa/tests/integration, configfile: pytest.ini
    plugins: testinfra-5.0.0, html-3.1.1, metadata-3.0.0
    collected 195 items                                                                                                                                             
    
    test_basic.py::test_bucket_defaults[cloudtrail_defaults] PASSED                                                                                           [  0%]
    test_basic.py::test_bucket_defaults[vpc_defaults] PASSED                                                                                                  [  1%]
    test_basic.py::test_bucket_defaults[config_defaults] PASSED                                                                                               [  1%]
    test_basic.py::test_bucket_defaults[alb_defaults] PASSED                                                                                                  [  2%]
    test_basic.py::test_bucket_defaults[clb_defaults] PASSED                                                                                                  [  2%]
    test_basic.py::test_bucket_defaults[nlb_defaults] PASSED                                                                                                  [  3%]
    test_basic.py::test_bucket_defaults[kms_defaults] PASSED                                                                                                  [  3%]
    test_basic.py::test_bucket_defaults[macie_defaults] PASSED                                                                                                [  4%]
    test_basic.py::test_bucket_defaults[trusted_advisor_defaults] PASSED                                                                                      [  4%]
    test_basic.py::test_bucket_defaults[guardduty_defaults] PASSED                                                                                            [  5%]
    test_basic.py::test_bucket_defaults[native_guardduty_defaults] PASSED                                                                                     [  5%]
    test_basic.py::test_bucket_defaults[waf_defaults] PASSED                                                                                                  [  6%]
    test_basic.py::test_bucket_defaults[server_access_defaults] PASSED                                                                                        [  6%]
    test_basic.py::test_bucket_defaults[cisco_umbrella_defaults] PASSED                                                                                       [  7%]
    test_basic.py::test_service_defaults[cloudwatchlogs_defaults] PASSED                                                                                      [  7%]
    test_basic.py::test_inspector_defaults[inspector_defaults] PASSED                                                                                         [  8%]
    test_discard_regex.py::test_discard_regex[cloudtrail_discard_regex] PASSED                                                                                [  8%]
    test_discard_regex.py::test_discard_regex[vpc_discard_regex] PASSED                                                                                       [  9%]
    test_discard_regex.py::test_discard_regex[config_discard_regex] PASSED                                                                                    [  9%]
    test_discard_regex.py::test_discard_regex[alb_discard_regex] PASSED                                                                                       [ 10%]
    test_discard_regex.py::test_discard_regex[clb_discard_regex] PASSED                                                                                       [ 10%]
    test_discard_regex.py::test_discar [...]

2023-07-06 16:02 UTC, nico-stefani commented on wodles/aws/tests/test_config.py
> +@pytest.mark.parametrize('iam_profile', ['iamInstanceProfileName', {}])
If possible, group these `parametrize` decorators.

2023-07-06 16:03 UTC, nico-stefani commented on wodles/aws/tests/test_inspector.py
> +@pytest.mark.parametrize('only_logs_after', [utils.TEST_ONLY_LOGS_AFTER, None])
Same comment about `parametrize` decorators.

2023-07-06 16:04 UTC, nico-stefani commented on wodles/aws/tests/test_server_access.py
> +@pytest.mark.parametrize('same_prefix_result', [True, False])
Same comment about `parametrize` decorators.

2023-07-06 16:07 UTC, nico-stefani commented on wodles/aws/tests/test_vpcflow.py
> +@pytest.mark.parametrize('profile', [None, utils.TEST_AWS_PROFILE])
Same comment about `parametrize` decorators.

2023-07-06 16:07 UTC, nico-stefani commented on wodles/aws/tests/test_vpcflow.py
> +@pytest.mark.parametrize('regions', [[utils.TEST_REGION], None])
Same here

2023-07-06 16:08 UTC, nico-stefani commented on wodles/aws/tests/test_vpcflow.py
> +@pytest.mark.parametrize('region', [utils.TEST_REGION, "invalid_region"])
And here

2023-07-06 16:08 UTC, nico-stefani commented on wodles/aws/tests/test_wazuh_integration.py
> +@pytest.mark.parametrize('service_name', ["cloudTrail", "cloudwatchlogs"])
Same comment about `parametrize` decorators.

2023-07-06 19:02 UTC, fdalmaup commented on wodles/aws/tests/test_aws_s3.py
> +])
Added a validation for the subscriber type in `aws-s3.py` and the corresponding test.

2023-07-06 19:08 UTC, fdalmaup commented on wodles/aws/tests/test_cloudwatchlogs.py
> +                                            'end_time': TEST_END_TIME - 1}])
If the variables are united in a single `parametrize`, every possible combination of each one should be declared. Having the separated `parametrize` decorators generates a cartesian product of all the parameters.

2023-07-06 20:01 UTC, nico-stefani approved these changes
LGTM!

2023-07-10 15:46 UTC, Selutario requested changes
Add copyright note to all new tests and modules:

```
# Copyright (C) 2015, Wazuh Inc.
# Created by Wazuh, Inc. <info@wazuh.com>.
# This program is free software; you can redistribute it and/or modify it under the terms of GPLv2
```

2023-07-10 15:46 UTC, Selutario commented on wodles/aws/tests/test_server_access.py
> +    assert marker == f"{instance.prefix}{test_only_logs_after[0:4]}-{test_only_logs_after[4:6]}-{test_only_logs_after[6:8]}"
Some lines exceed 120 characters, which is the value most of our API and framework files take:
![image](https://github.com/wazuh/wazuh/assets/23361101/b2388387-511c-49df-bdc1-2bf5c48f4b06)

2023-07-10 15:46 UTC, Selutario commented on wodles/aws/tests/test_umbrella.py
> +    assert marker == f"{instance.prefix}{test_only_logs_after[0:4]}-{test_only_logs_after[4:6]}-{test_only_logs_after[6:8]}"
Too long line

2023-07-10 15:46 UTC, Selutario commented on wodles/aws/tests/test_vpcflow.py
> +    expected_vpc_prefix = utils.TEST_FULL_PREFIX + TEST_DATE + '/' + utils.TEST_ACCOUNT_ID + '_vpcflowlogs_' + utils.TEST_REGION + '_' + TEST_FLOW_LOG_ID
Too long line

2023-07-10 15:46 UTC, Selutario commented on wodles/aws/tests/test_wazuh_integration.py
> +    assert instance.db_cursor.execute(instance.sql_find_table, {'name': METADATA_TABLE_NAME}).fetchone()[0]
Missing new line at the end of the file.
```suggestion
    assert instance.db_cursor.execute(instance.sql_find_table, {'name': METADATA_TABLE_NAME}).fetchone()[0]

```

2023-07-10 15:46 UTC, Selutario commented on wodles/aws/wazuh_integration.py
> +                f"Generating default configuration for retries: mode {args['config'].retries['mode']} - max_attempts {args['config'].retries['max_attempts']}",
Too long line, fix this everywhere you find it (when using a shorter line it's possible).

2023-07-11 14:02 UTC, fdalmaup commented
On Hold until the latest changes of the code are merged into the master branch to apply them for a last review.

2023-08-23 13:07 UTC, fdalmaup commented on wodles/aws/pytest.ini
Done

2023-08-23 15:43 UTC, nico-stefani approved these changes
LGTM! The failed check isn't related to the changes.

2023-08-24 10:16 UTC, Selutario approved these changes

2023-08-24 10:19 UTC, merged