Engine - Wazuh dashboard integration
wazuh/wazuh pull request #17633
Opened 2023-06-22 20:32 UTC by nbertoldo

|Related issue|
|---|
|#17582|

## Description
This integration must be able to process different types of events generated on the [Wazuh Dashboard](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/index.html#wazuh-dashboard).

## Task List:
- [ ] Obtain a list and a pre-analysis of the possible event types with the default configuration.
- [ ] Create a decoder to extract the useful fields of each event type.
- [ ] Analysis of fields that can be obtained but there is no clear destination in the ECS.
- [ ] Analysis of fields that cannot be extracted (parse). 
- [ ] Generate end to end events and check filbeat logs to rule out errors
- [ ] Add test and expected for all event types

2023-06-27 16:14 UTC, nbertoldo commented on src/engine/ruleset/integrations/wazuh-dashboard/README.md
I agree. Done

2023-06-27 19:21 UTC, juliancnn requested changes

2023-06-27 20:44 UTC, nbertoldo commented on src/engine/source/hlp/src/syntax.hpp
>      };
Done

2023-06-27 20:58 UTC, LucioDonda approved these changes
LGTM!

2023-06-29 04:50 UTC, juliancnn approved these changes
LGTM!

2023-06-29 14:18 UTC, JcabreraC approved these changes
LGTM !

2023-06-29 14:18 UTC, merged