17580 aws integration update
wazuh/wazuh pull request #17648
Opened 2023-06-23 20:56 UTC by LucioDonda

|Related issue|
|---|
|#17580|

## Description

This PR aims to modify ¿the 3 integrations of AWS already available for the engine usage in order to use only ECS fields.
Due to the previous implementation of AWS ELB it will be replaced by one that make use of the wodle.

Configuration block:
```

<ossec_config>

  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>yes</skip_on_error>
    <bucket type="server_access">
        <aws_profile>default</aws_profile>
    </bucket>
    <bucket type="alb">
        <name>wazuh-aws-wodle</name>
        <path>ALB</path>
        <aws_profile>default</aws_profile>
    </bucket>
    <bucket type="clb">
      <name>wazuh-aws-wodle</name>
      <path>CLB</path>
      <aws_profile>default</aws_profile>
    </bucket>
    <bucket type="nlb">
      <name>wazuh-aws-wodle</name>
      <path>NLB</path>
      <aws_profile>default</aws_profile>
    </bucket>
    <bucket type="cloudtrail">
      <name>wazuh-cloudtrail</name>
      <aws_profile>default</aws_profile>
    </bucket>
  </wodle>

  
    <location>[AWS ELB log path]</location>
    <log_format>json</log_format>
    <label key="event.module">aws</label>
    <label key="event.dataset">aws.elb</label>
  </localfile>

</ossec_config>
```

Event types:
[S3 server access](https://documentation.wazuh.com/current/amazon/services/supported-services/server-access.html#amazon-server-access)
[Cloudtrail](https://documentation.wazuh.com/current/amazon/services/supported-services/cloudtrail.html#amazon-cloudtrail)
ELB
-   [ALB](https://documentation.wazuh.com/current/amazon/services/supported-services/elastic-load-balancing/alb.html#amazon-alb) 
-   [CLB](https://documentation.wazuh.com/current/amazon/services/supported-services/elastic-load-balancing/clb.html#amazon-clb)
-   [NLB](https://documentation.wazuh.com/current/amazon/services/supported-services/elastic-load-balancing/nlb.html#amazon-nlb)

2023-06-29 15:41 UTC, nbertoldo requested changes

2023-06-29 19:12 UTC, nbertoldo approved these changes
LGTM!

2023-07-03 21:00 UTC, juliancnn approved these changes

2023-07-04 06:53 UTC, JavierBejMen approved these changes
LGTM

2023-07-04 12:49 UTC, JcabreraC approved these changes
LGTM !

2023-07-04 12:49 UTC, merged