Feature/maximum buffer length reached error with get stats api
wazuh/wazuh pull request #17669
Opened 2023-06-27 15:36 UTC by thejbte

|Related issue|Manual Testing|
|---|---|
|https://github.com/wazuh/wazuh/issues/16379||

## Description
This PR  solves the issue https://github.com/wazuh/wazuh/issues/16379, the proposed solution was  split the json file into 64k json blocks.
from the api you must send "getstate next" when you want to request the next page, when you want to only request the first page you must send "getstate", the response is a json formed by `{"error":0,"remaining":false,"json_updated":false,"data":{` where remaining indicates if there are pending pages, json_updated indicates if json file is updated automatically, this variable could be used to know if it starts from first page.

12. open console and send the next command

## Configuration options
Manager:
1. Request stats
 ```
curl -k -X GET "https://192.168.1.18:55000/agents/009/stats/logcollector?pretty=true" -H "Authorization: Bearer $(curl -u wazuh:wazuh -k -X GET "https://192.168.1.18:55000/security/user/authenticate?raw=true")"
 ```

Agent:
1. Monitoring folder where there are many files 
```
  <localfile>
    <log_format>syslog</log_format>
    <location>/root/logs/*</location>
  </localfile>
```
2. Change if necessary
`logcollector.max_files=1000` , `logcollector.rlimit_nofile=1100` and `agent.debug=2`

3. Check logs `tail -f /var/ossec/logs/ossec.log | grep '{"error"'`

## Logs/Alerts example

## Tests

 

- Compilation without warnings in every supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer

2023-06-27 15:39 UTC, thejbte commented
Example of statistics.

<details><summary>first page</summary>

  ```json
{"error":0,"remaining":true ,"json_updated":true ,"data":{"global":{"start":"2023-06-27 14:43:15","end":"2023-06-27 14:50:15","files":[{"location":"last -n 20","events":2,"bytes":1462,"targets":[{"name":"agent","drops":0}]},{"location":"/root/logs/my-log-for-any-thing-example-982.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-945.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-92.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-908.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-880.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-843.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-806.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-779.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-741.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-704.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-677.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-602.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-575.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-55.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-538.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-500.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-473.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-436.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-371.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-334.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-3.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-232.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-18.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-168.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-130.log","events":0,"bytes":0,"targets":[]},{"location":"/var/log/dpkg.log","events":0,"bytes":0,"targets":[{"name":"agent","drops":0}]},{"location":"/root/logs/my-log-for-any-thing-example-973.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-936.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-871.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-834.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-83.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-732.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-668.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-630.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-566.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-529.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-464.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-46.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-427.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-362.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-325.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-298.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-260.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-223.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-196.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-159.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-121.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-1234567-689.log","events":0,"bytes":0,"targets":[{"name":"agent","drops":0}]},{"location":"/root/logs/my-log-for-any-thing-example-964.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-927.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-862.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-825.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-798.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-760.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-74.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-723.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-696.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-659.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-621.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-594.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-557.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-492.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-455.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-418.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-390.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-37.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-353.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-316.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-289.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-251.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-214.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-187.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-112.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-992.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-955.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-918.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-890.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-853.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my-log-for-any-thing-example-816.log","events":0,"bytes":0,"targets":[]},{"location":"/root/logs/my [...]

2023-06-27 16:07 UTC, thejbte commented
@wazuh/framework

From Framework they must modify the code and send us `getstate next` when they want to request the next page, when they want to only request the first page they must send `getstate`.

The response is a json formed by `{"error":0,"remaining":false,"json_updated":false,"data":{` where `remaining` indicates if there are pending pages, `json_updated` indicates if json file is updated automatically, this variable could be used to know if it starts from first page.

see issue here  https://github.com/wazuh/wazuh/issues/17671

2023-07-10 20:07 UTC, TomasTurina requested changes

2023-07-10 20:07 UTC, TomasTurina commented on src/logcollector/lccom.c
> +                        mwarn("global no found\r\n");
```suggestion
                        mwarn("'global' tag no found in logcollector JSON stats.");
```

2023-07-10 20:07 UTC, TomasTurina commented on src/logcollector/lccom.c
> +
Remove empty lines.

2023-07-10 20:07 UTC, TomasTurina commented on src/logcollector/lccom.c
> +            if ( counter < OS_MAXSTR - SIZE_1KB) {
```suggestion
            if (counter < OS_MAXSTR - SIZE_1KB) {
```

2023-07-11 19:54 UTC, thejbte commented on src/logcollector/lccom.c
> +        replaceBoolToStr(*output, "\"remaining\":", strlen(*output) >= OS_MAXSTR - (2*SIZE_1KB));
It should be like this, becuase the last block could be lower than 64k and should be false.
first '*output' point to the global json without split and second one '*output' point to the block of length <= 64k, where 2*SIZE_1KB is for left free space to headers.

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +bool getObjectIndexFromJsonStats(char *outjson_aux, size_t *ptrs, uint16_t *amountObj );
```suggestion
bool getObjectIndexFromJsonStats(char *outjson_aux, size_t *ptrs, uint16_t *amountObj);
```

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +bool getObjectIndexFromJsonStats(char *outjson_aux, size_t *ptrs, uint16_t *amountObj ) {
```suggestion
bool getObjectIndexFromJsonStats(char *outjson_aux, size_t *ptrs, uint16_t *amountObj) {
```

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +        outjson_aux = outjson_aux + LEN_LOCATION ;
```suggestion
        outjson_aux = outjson_aux + LEN_LOCATION;
```

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +                if (counter == 0 ) {
```suggestion
                if (counter == 0) {
```

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +        memcpy(strJson, bufferTmp, OS_MAXSTR);
```suggestion
        memcpy(strJson, bufferTmp, OS_MAXSTR - 1);
```

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +#define SIZE_1KB            (1024)  /*!< size of 1KB*/
Not necessary. Use `OS_SIZE_1024` from `src/headers/defs.h`.

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +            strncpy(output, outjson + ptrs[initialIndex] - ptrs[0], ptrs[currentIndex-1] - ptrs[initialIndex-1] + strlen(outjson + ptrs[currentIndex-1] -ptrs[0]));
```suggestion
            strncpy(output, outjson + ptrs[initialIndex] - ptrs[0], ptrs[currentIndex-1] - ptrs[initialIndex-1] + strlen(outjson + ptrs[currentIndex-1] - ptrs[0]));
```

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +    isReadyIndex = getObjectIndexFromJsonStats (*output, ptrs, &i);
```suggestion
    isReadyIndex = getObjectIndexFromJsonStats(*output, ptrs, &i);
```

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +        apiLatestIndex = checkJson64k (*output, apiLatestIndex, i, ptrs, buffer, &counter);
```suggestion
        apiLatestIndex = checkJson64k(*output, apiLatestIndex, i, ptrs, buffer, &counter);
```

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +        addStartandEndTagsToJsonStrBlock (buffer, headerGlobal, headerInterval, headerData,
```suggestion
        addStartandEndTagsToJsonStrBlock(buffer, headerGlobal, headerInterval, headerData,
```

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +        os_strdup (buffer, *output);
```suggestion
        os_strdup(buffer, *output);
```

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +                    find intervals,files y greather than 64k
```suggestion
                    find intervals,files and greather than 64k
```

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +                    find intervals,files y lower than 64k, it closes self
```suggestion
                    find intervals,files and lower than 64k, it closes self
```

2023-07-12 18:22 UTC, TomasTurina commented on src/logcollector/lccom.c
> +                intervals,files not found y greather than 64k
```suggestion
                intervals,files not found and greather than 64k
```

2023-07-12 18:25 UTC, TomasTurina commented on src/logcollector/lccom.c
> +        memcpy(bufferTmp + lenHeaderData + lenHeader, strJson, OS_MAXSTR - lenHeaderData - lenHeader);
```suggestion
        memcpy(bufferTmp + lenHeaderData + lenHeader, strJson, OS_MAXSTR - lenHeaderData - lenHeader - 1);
```

2023-08-22 20:11 UTC, TomasTurina approved these changes

2023-12-14 17:46 UTC, thejbte commented
I tested after merge and it's working fine.
this is the output: [out1.log](https://github.com/wazuh/wazuh/files/13676515/out1.log)

2023-12-15 14:58 UTC, TomasTurina approved these changes

2023-12-15 15:18 UTC, TomasTurina approved these changes

2023-12-15 16:11 UTC, Selutario approved these changes
LGTM. This failing wodle [check](https://github.com/wazuh/wazuh/actions/runs/7223847171/job/19683875270?pr=17669) is unrelated to the changes and should be fixed in the next `4.8.0 -> 4.8.1` merge.

2023-12-15 18:04 UTC, merged