Engine - Changed int to accept 64 bits
wazuh/wazuh pull request #17738
Opened 2023-07-03 20:54 UTC by LucioDonda

|Related issue|
|---|
||

## Description

This PR aims to update the default integer to 64 bits, avoiding the overflow on several cases.

## Tasks
- []  Update all helpers using int to int64, getting values from reference or arguments.
- []  Update helpers to use this format also
- []  Improve or update documentation of modified helpers

2023-07-05 15:19 UTC, JavierBejMen approved these changes
LGTM

2023-10-31 14:35 UTC, LucioDonda commented on src/engine/source/builder/helperParser.hpp
> +    bool isValueIntiger = expressionToken.value.isInt() || expressionToken.value.isInt64();
Rename to `isValueInteger`

2023-11-01 16:44 UTC, soynof requested changes

2023-11-01 16:44 UTC, soynof commented on src/engine/test/source/json/json_test.cpp
> +                         ::testing::Values(0, 1, 2, 3, static_cast<int64_t>(std::numeric_limits<int32_t>::max()) + 10));
Add test with std::numeric_limits<int32_t>::min() -10, for example.

2023-11-03 12:23 UTC, juliancnn commented on src/engine/source/builder/helperParser.hpp
> +    bool isValueIntiger = expressionToken.value.isInt() || expressionToken.value.isInt64();
done

2023-11-03 14:18 UTC, NahuFigueroa97 approved these changes
LGTM!

2023-11-03 15:07 UTC, JavierBejMen approved these changes
LGTM

2023-11-06 13:28 UTC, soynof approved these changes
LGTM!

2023-11-07 10:11 UTC, JcabreraC approved these changes
LGTM !

2023-11-07 10:11 UTC, merged