Add native Maltiverse integration
wazuh/wazuh pull request #17782
Opened 2023-07-07 10:26 UTC by dgilm

|Related issue|
|#17752|
|#17753|

## Description

This PR adds the Maltiverse native integration to Wazuh.

### What is Maltiverse?
Maltiverse works as a broker for Threat intelligence sources that are
aggregated from more than a hundred different Public, Private and Community
sources. Once the data is ingested, the IoC Scoring Algorithm applies a
qualitative classification to the IoC that changes. Finally this data can
be queried in a Threat Intelligence feed that can be delivered to your
Firewalls, SOAR, SIEM, EDR or any other technology.

More info at: https://whatis.maltiverse.com

### What does this integration?
This integration enrichs any alert generated by Wazuh via the Maltiverse API,
inserting new fields in case of match and following the threat taxonomy of the
ECS standard (Elastic Common Squema).

https://www.elastic.co/guide/en/ecs/current/ecs-threat.html

Ipv4, Domain names, Urls and MD5/SHA1 checksums are checked in Maltiverse
platform in order to enrich the original alert with threat Intel information

## Configuration options

1. Move this file ``maltiverse.py`` to ``/var/ossec/integrations/custom-maltiverse.py``
   and make sure the file has the right perms:
   ```
   chmod +x /var/ossec/integrations/custom-maltiverse.py
   chown root.wazuh /var/ossec/integrations/custom-maltiverse.py
    ```

2. Add this to the ossec.conf file, inside <ossec_config></ossec_config> block:
```
<integration>
     <name>custom-maltiverse</name>
     <hook_url>https://api.maltiverse.com</hook_url>
     <api_key><YOUR_MALTIVERSE_AUTH_TOKEN></api_key>
     <alert_format>json</alert_format>
</integration>
```
3. Restart Wazuh Manager

## Logs/Alerts example

Threat taxonomy of the ECS standard (Elastic Common Squema) is followed: https://www.elastic.co/guide/en/ecs/current/ecs-threat.html

```
      "threat": {
        "indicator": {
          "reference": "https://maltiverse.com/ip/212.192.241.132",
          "first_seen": "2021-12-30 00:58:57",
          "last_seen": "2023-07-05 13:59:09",
          "provider": "Emerging Threats, Maltiverse, Blocklist.de, FireHOL",
          "confidence": "Medium",
          "name": "212.192.241.132",
          "description": "Scanning IPs, ET COMPROMISED Known Compromised or Hostile Host Traffic TCP, HTTP Attacker, Bruteforce login attacker, Proxy, ET COMPROMISED Known Compromised or Hostile Host Traffic UDP",
          "sightings": "6",
          "type": "ip",
          "modified_at": "2023-07-05 13:59:09"
        }
      }
```

Also, full response of Maltiverse api is included in `data->maltiverse->source`

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2023-07-07 15:36 UTC, fdalmaup requested changes
Other general suggestions:
- I have tested the integration and works fine but test output should be added here or in the development issue.
- We should change the target branch to the epic branch [17752-maltiverse-integration](https://github.com/wazuh/wazuh/tree/17752-maltiverse-integration).

2023-07-07 15:36 UTC, fdalmaup commented on ruleset/rules/0995-maltiverse_rules.xml
> +    <rule id="99500" level="0">
```suggestion
    <rule id="99500" level="10">
```
We should define a base level, e.g. 10, for the rule to trigger alerts when Maltiverse returns aggregated information.

2023-07-14 19:58 UTC, fdalmaup requested changes

2023-07-14 19:58 UTC, fdalmaup commented on integrations/maltiverse.py
> +      response is also included.
```suggestion
    alert_id: in
        The generated alert ID.
    ioc_dict: dict 
        Raw information returned by Maltiverse API.
    ioc_name: str
        The representative name of the indicator.
    ioc_ref: Optional[str] 
        An indicator reference used to build a reference URL.
        ioc_name is used by default if ioc_ref is not set.
    include_full_source: Optional[bool] 
        If True (default), the complete API response is also included.
```

2023-07-17 12:09 UTC, fdalmaup approved these changes
LGTM!

2023-07-17 15:50 UTC, Selutario approved these changes
LGTM

2023-07-17 15:50 UTC, merged