Create SCA Policy for Rocky Linux 8
wazuh/wazuh pull request #17784
Opened 2023-07-07 11:27 UTC by jk-olaoluwa

| Component | Action type           | Main Issue 
| --- | --- | ---
| SCA       | Create |  #14358 

|Related issue|
|---|
|https://github.com/wazuh/wazuh/pull/16880|

## Main tasks

- [x] Use the latest CIS benchmark PDF - CIS Rocky Linux 8 Benchmark v1.0.0
- [x] Verify IDs numbers.
- [x] Verify texts are correct: Title, Description, Rationale and Remediation.
- [x] Verify Compliance: CIS, CIS_CSC.
- [x] Verify condition and rules:
  - [x] To Pass.
  - [x] To Fail.

  
### Issue QA:
- TBD

## PR Tests
### Syntax and semantic

- [ ] a) ID of each policy must be contiguous.
- [ ] b) The order and format set in [Documentation](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html) must be respected.
- [ ] c) YML must be valid to avoid errors.

### Content

- [ ] a) Compare each check with its analog from CIS Benchmark.
- [ ] b) Try maintaining each rule as similar as possible with the `Audit` section from the CIS check.
- [ ] c) Check that the commands provide the expected output.
- [ ] d) When a failure is discovered, check similar policies to avoid repetition of the issue.

### Unit testing

- [ ] a) Output from `ossec.log` after the SCA scan and a raw output of the result of the checks.
<details><summary>Tests results</summary>
<p>

#### Analysisd (server or local)
analysisd.debug=2

#### Auth daemon debug (server)
authd.debug=0

#### Exec daemon debug (server, local, or Unix agent)
execd.debug=0

#### Monitor daemon debug (server, local, or Unix agent)
monitord.debug=0

#### Log collector (server, local or Unix agent)
logcollector.debug=0

#### Integrator daemon debug (server, local, or Unix agent)
integrator.debug=0

#### Unix agentd
agent.debug=2

</p>
</details>

### Deployment

- [ ] a) If the policy it's new, it must be added to the `sca.files` templates.
- [ ] b) If the OS has many supported SCA policies, a policy must be set as the default policy. ([as example](https://github.com/wazuh/wazuh/blob/master/etc/templates/config/centos/sca.files))

### Documentation

- [ ] a) Ensure documentation SCA list includes the created or updated SCA.

# Checks
| Check Id and Name                                                                                                                | Status | Ready for QA    |
| -------------------------------------------------------------------------------------------------------------------------------- | ------ | --------------- |
|                                                                                                                                  |        |                 |
| 1 Initial setup                                                                      |        |                 |
| 1.1 Filesystem Configuration                                                                      |        |                 |
| 1.1.1 Disable unused filesystems                                                                      |        |                 |
||||
| 1.1.1.1 Ensure mounting of cramfs filesystems is disabled. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.1.2 Ensure mounting of squashfs filesystems is disabled. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.1.3 Ensure mounting of udf filesystems is disabled. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.2.1 Ensure /tmp is a separate partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.2.2 Ensure nodev option set on /tmp partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.2.3 Ensure noexec option set on /tmp partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.2.4 Ensure nosuid option set on /tmp partition. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.1.3 Configure /var                                                                      |        |                 |
||||
| 1.1.3.1 Ensure separate partition exists for /var. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.3.2 Ensure nodev option set on /var partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.3.3 Ensure noexec option set on /var partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.3.4 Ensure nosuid option set on /var partition. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.1.4 Configure /var/tmp                                                                      |        |                 |
||||
| 1.1.4.1 Ensure separate partition exists for /var/tmp. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.4.2 Ensure noexec option set on /var/tmp partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.4.3 Ensure nosuid option set on /var/tmp partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.4.4 Ensure nodev option set on /var/tmp partition. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.1.5 Configure /var/log                                                                      |        |                 |
||||
| 1.1.5.1 Ensure separate partition exists for /var/log. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.5.2 Ensure nodev option set on /var/log partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.5.3 Ensure noexec option set on /var/log partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.5.4 Ensure nosuid option set on /var/log partition. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.1.6 Configure /var/log/audit                                                                      |        |                 |
||||
| 1.1.6.1 Ensure separate partition exists for /var/log/audit. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.6.2 Ensure noexec option set on /var/log/audit partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.6.3 Ensure nodev option set on /var/log/audit partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.6.4 Ensure nosuid option set on /var/log/audit partition. (Automated)                                                                    | 🟢      | 🟢               |
||||
| 1.1.7 Configure /home                                                                      |        |                 |
||||
| 1.1.7.1 Ensure separate partition exists for /home. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.7.2 Ensure nodev option set on /home partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.7.3 Ensure nosuid option set on /home partition. (Automated)                                                                    | 🟢      | 🟢               |
| 1.1.7.4 Ensure us [...]

2023-07-16 19:00 UTC, 72nomada approved these changes
LGTM

2023-07-18 08:10 UTC, DFolchA reviewed
The directory names do not conform with the information retrieved by `dist-detect.sh`:
```
[root@rockylinux8 vagrant]# bash dist-detect.sh 
DIST_NAME=rocky
DIST_VER=8
DIST_SUBVER=8
```

2023-07-18 14:19 UTC, DFolchA requested changes

2023-07-18 16:02 UTC, DFolchA requested changes
The new files must be added to `sca.manager.files`

2023-09-15 09:19 UTC, ooniagbi approved these changes
LGTM!

2023-09-15 10:03 UTC, DFolchA approved these changes

2023-09-15 10:15 UTC, merged

2024-01-09 20:27 UTC, breisig commented
Is there going to be one for Rocky Linux 9?