SCA Rocky Linux 9
wazuh/wazuh pull request #17810
Opened 2023-07-08 03:01 UTC by Johnng007

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/16618|

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2023-07-16 19:13 UTC, 72nomada approved these changes
LGTM

2023-07-18 08:10 UTC, DFolchA reviewed
The directory names do not conform with the information retrieved by `dist-detect.sh`:
```
[root@rockylinux9 vagrant]# bash dist-detect.sh 
DIST_NAME=rocky
DIST_VER=9
DIST_SUBVER=2
```

2023-07-18 14:19 UTC, DFolchA commented on etc/templates/config/rocky/9/sca.files
> +rockylinux/cis_rocky_linux_9.yml
This path is incorrect after the last changes.

2023-07-18 16:02 UTC, DFolchA requested changes
The new files must be added to `sca.manager.files`

2024-01-12 15:27 UTC, ooniagbi approved these changes
LGTM!

2024-01-12 15:31 UTC, ooniagbi approved these changes
LGTM!

2024-01-12 15:32 UTC, merged