Engine - Adapt decoders
wazuh/wazuh pull request #18025
Opened 2023-07-24 16:15 UTC by nmkoremblum

|Related issue|
|---|
|#17988|

#description

This pull request addresses the changes required in #17988 due to the new syntax implemented for decoders in issue #17980. With the recent update, it is needed to adapt the existing decoders to align with the new format for improved functionality and efficiency.

**Decoders/Integrations to Update**:

- [x] Syslog
- [x] System
- [x] Apache
- [x] Suricata
- [x] Wazuh-core

**Proposed Changes**:

1. Replacing Temporal Fields with Variables:
   - Replace occurrences of `~tmp.name` with appropriate variables using the `_name` format.

2. Revise Helper Function Format:
   - Revise the format of the `helper function` to adhere to standard programming language conventions:
   ```scss
   function_name(param1, param2, ..., paramN)
   
3. Introducing the Usage of the '$' Symbol for Event Field References:
   - Introduce the usage of the $ symbol to reference event fields during the check stage, similar to mapping or function helper calls.

2023-07-25 17:15 UTC, juliancnn commented on src/engine/ruleset/integrations/apache-http/decoders/apache-access.yml
> +      - tls.version: _tls-1
```suggestion
      - tls.version: $_tls-1
```

2023-07-25 19:10 UTC, cborla requested changes

2023-07-25 21:40 UTC, juliancnn requested changes

2023-07-26 01:04 UTC, cborla approved these changes
LGTM

2023-07-26 01:07 UTC, merged