Engine - KVDB - Prefix Search
wazuh/wazuh pull request #18293
Opened 2023-08-07 15:47 UTC by soynof

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## Description

Enable usage of RocksDB's Prefix Search feature to drive a secondary index for keys in a single KVDB (Column Family). 
This way we could have grouped keys under certain prefix inside the same KVDB.
 
## DoD
 - [x] Unit test.
 - [ ] Update the design document.
 - [ ] Update the user manual.
 - [ ] Memory Leak analysis.

2023-08-08 19:07 UTC, juliancnn requested changes

2023-08-08 19:07 UTC, juliancnn commented on src/engine/source/proto/src/kvdb.proto
> +/******************** Operation with a DB ********************/
```suggestion
```

2023-08-09 13:51 UTC, juliancnn approved these changes
LGTM!

2023-08-10 14:45 UTC, NahuFigueroa97 commented on src/engine/source/api/src/kvdb/handlers.cpp
>              return ::api::adapter::genericError<ResponseType>("The Database already exists.");
improve - desing: 
```
return ::api::adapter::genericError<ResponseType>(fmt::format("The KVDB '{}' does not exist.", eRequest.name()));
```

2023-08-10 14:45 UTC, NahuFigueroa97 commented on src/engine/source/api/src/kvdb/handlers.cpp
>                  fmt::format("The KVDB '{}' does not exist.", eRequest.name()));
improve-desing: This message is repited in each handler, put this as constexpr

2023-08-10 14:45 UTC, NahuFigueroa97 commented on src/engine/test/source/api/kvdb/kvdb_api_test.cpp
> +TEST_F(KVDBApiTest, dbSearchNameArrayNotString)
nitpick - desing: should you use TEST_P() to avoid duclicated code

2023-08-10 20:01 UTC, NahuFigueroa97 approved these changes
LGTM!

2023-08-17 10:27 UTC, JavierBejMen approved these changes
LGTM

2023-08-17 11:48 UTC, JcabreraC approved these changes
LGTM !

2023-08-17 11:48 UTC, merged