Delete deprecated endpoints lists
wazuh/wazuh pull request #18330
Opened 2023-08-10 13:13 UTC by mhamra

|Related issue|
|---|
|#17068|

## Description

Delete deprecated endpoints lists.

2023-08-30 17:20 UTC, nico-stefani requested changes
Please check:
* The PR should be pointing to `11334-dev-new-wazuh-engine`
* The API IT that were failed
* Resolve the conflicts

2023-08-30 17:20 UTC, nico-stefani commented on framework/wazuh/rbac/decorators.py
> +        #     return expand_lists()
Why not just remove the condition?

2023-09-21 18:28 UTC, mhamra commented on framework/wazuh/rbac/decorators.py
> +        #     return expand_lists()
Removed!

2023-11-02 13:39 UTC, nico-stefani requested changes
The PR should point to the new engine epic `11334-dev-new-wazuh-engine`. Also, fix the conflicts, please.

2023-11-06 16:08 UTC, nico-stefani requested changes

2023-11-06 16:08 UTC, nico-stefani commented on framework/wazuh/core/common.py
> +# USER_LISTS_PATH = os.path.join(WAZUH_PATH, 'etc', 'lists')
```suggestion
```

2023-11-06 16:08 UTC, nico-stefani commented on framework/wazuh/rbac/decorators.py
> +from wazuh.core.utils import expand_rules, expand_decoders #, expand_lists
```suggestion
from wazuh.core.utils import expand_rules, expand_decoders 
```

2023-11-10 12:50 UTC, nico-stefani submitted a review, later dismissed
LGTM

2024-09-10 13:39 UTC, closed without merging