Migrate AWS wazuh-qa integration tests to wazuh core repository
wazuh/wazuh pull request #18508
Opened 2023-08-18 16:24 UTC by EduLeon12

|Related issue|
|---|
|Closes #17788|

## Description

As part of #17427, This PR tends to migrate AWS QA Integration tests to wazuh core repository. 

## Configuration options

## Logs/Alerts example

Log history can be found [here](https://github.com/wazuh/wazuh/issues/17788#issuecomment-1674971694). 

## Tests

Run of the full test suite: 

```
root@wazuh-master:/wazuh/tests/integration# pytest -x test_aws/ --disable-warnings
==================================== test session starts ====================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.2.0
rootdir: /wazuh/tests/integration, configfile: pytest.ini
plugins: testinfra-5.0.0, metadata-3.0.0, html-3.1.1
collected 195 items

test_aws/test_basic.py ................                                               [  8%]
test_aws/test_discard_regex.py ..............                                         [ 15%]
test_aws/test_log_groups.py ..                                                        [ 16%]
test_aws/test_only_logs_after.py .............................................x.      [ 40%]
test_aws/test_parser.py ..........................                                    [ 53%]
test_aws/test_path.py ..........................................                      [ 75%]
test_aws/test_path_suffix.py .........                                                [ 80%]
test_aws/test_regions.py ........................                                     [ 92%]
test_aws/test_remove_from_bucket.py ...sss.........                                   [100%]

============ 191 passed, 3 skipped, 1 xfailed, 7 warnings in 3723.08s (1:02:03) =============
```

2023-08-22 18:44 UTC, nico-stefani requested changes

2023-08-25 11:27 UTC, EduLeon12 commented on tests/integration/conftest.py
> +        file_to_monitor = WAZUH_LOG_PATH
As explained in [this comment](https://github.com/wazuh/wazuh/issues/17788#issuecomment-1673636630), the scope of this issue is to migrate the tests without making major enhancement changes. However, this proposal should be taken into consideration for https://github.com/wazuh/wazuh/issues/18355.

2023-09-21 12:16 UTC, nico-stefani requested changes

2023-09-21 12:16 UTC, nico-stefani commented on tests/integration/test_aws/utils.py
Please, remove this file if don't we use it.

2023-09-22 17:50 UTC, EduLeon12 commented on tests/integration/test_aws/utils.py
My mistake, It is meant to be used in next step, but got caught on this branch, 
Done.

2023-09-26 18:55 UTC, nico-stefani approved these changes
LGMT

2023-10-02 10:36 UTC, Selutario approved these changes
This will be better reviewed in the epic PR, once the refactor is carried out.

2023-10-02 10:37 UTC, merged