Add support for Amazon Linux 2023 in Vulnerability Detector
wazuh/wazuh pull request #18570
Opened 2023-08-24 03:25 UTC by Leoquicenoz

|Related issue|
|---|
|[#18526](https://github.com/wazuh/wazuh/issues/18526)|

## Description

The purpose of this PR is to add support for Amazon Linux 2023 in the vulnerability detector module.

First, we generate our own feed in `JSON` format and upload it to the following links (from where we download it): 
[Amazon Linux 2023 feed](https://feed.wazuh.com/vulnerability-detector/ALAS/2023/alas2023.json.gz) and [Amazon Linux 2023 metadata](https://feed.wazuh.com/vulnerability-detector/ALAS/2023/alas2023.meta)

The vulnerabilities are then parsed and inserted into the database.

And finally, when an Amazon Linux 2023 agent is detected, then if the configuration is well set, it scans the agent and reports the vulnerabilities it contains.

## Configuration options

The Vulnerability Detector configuration has been extended to support the added OS (AL2023):
```xml
<vulnerability-detector>
    ...
    
    <provider name="alas">
      <enabled>yes</enabled>
      <os>amazon-linux</os>
      <os>amazon-linux-2</os>
      <os>amazon-linux-2023</os>
      <update_interval>1h</update_interval>
    </provider>
    ...
</vulnerability-detector>
```

2023-09-07 13:13 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/vulnerability_detector/test_wm_vuln_detector.c
> +
```suggestion
```

2023-09-07 13:14 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/vulnerability_detector/test_wm_vuln_detector.c
> +    int dist_ver_ref[] = {FEED_ALAS1, FEED_ALAS2, FEED_ALAS2022, FEED_ALAS2023};
```suggestion
    int dist_ver_ref[] = {FEED_ALAS1, FEED_ALAS2, FEED_ALAS2022, FEED_ALAfgjfgj23};
```

2023-09-07 13:15 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/vulnerability_detector/test_wm_vuln_detector.c
> +
```suggestion
```

2023-09-07 13:16 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/vulnerability_detector/test_wm_vuln_detector.c
> +
```suggestion
```

2023-09-20 14:31 UTC, MarcelKemp requested changes
We will avoid adding the changelog line, as this will be done in a separate issue.

2023-09-20 17:21 UTC, MarcelKemp approved these changes

2023-09-21 13:29 UTC, merged