Engine addpolicy api
wazuh/wazuh pull request #18709
Opened 2023-08-29 13:49 UTC by juliancnn

|Related issue|
|---|
|#18524|

## Description

This PR adds a new endpoind to manage the policies, these will stop being an asset in the catalog to become an internal construction, managed externally through the api, allowing to create policies and modify them by api.
A hash is also added to be able to know if the api that is currently running is the same as the one we have in memory.

## Examples

2023-09-11 17:16 UTC, NahuFigueroa97 requested changes
Very good work! Just one thing, the integration tests fail because in the given steps API of the router the policy is being created using the catalog, this changes in the current PR. They should generate the .proto of the policy for python and create the policy with the policy API.

```
# First Scenario
@given('I am authenticated with the router API "{name}"')
def step_impl(context, name: str):
    get_catalog = catalog_pb2.ResourceGet_Request()
    get_catalog.name = "policy"
    get_catalog.format = "yaml"
    context.result = API_CATALOG.send_command("resource", "get", MessageToDict(get_catalog))
```

2023-09-11 19:17 UTC, soynof requested changes

2023-09-11 19:17 UTC, soynof commented on src/engine/source/cmds/include/cmds/policy.hpp
> +void runAddPolicy(std::shared_ptr<apiclnt::Client> client, const std::string& policyName);
Please, add documentation.

2023-09-12 13:36 UTC, juliancnn commented on src/engine/source/router/src/policyManager.cpp
> +    return it->second[0].hash();
The hash is a mandatory requirement to raise a policy, seen from the policy manager's point of view, we return nullopt if the policy is not hashed (line 214 or the hash inside the optional).

2023-09-12 13:39 UTC, juliancnn commented on src/engine/source/router/src/router.cpp
> +            const auto& hash = m_policyManager->getPolicyHash(policyName).value_or("");
This validation must be done here and not inside the policy manager, the policy manager must return null to indicate that the policy does not exist. This is just a double check.

2023-09-12 13:41 UTC, juliancnn commented on src/engine/source/api/include/api/test/handlers.hpp
> +// TODO: CHECK IF THIS METODO EXIST!
yes

2023-09-12 16:18 UTC, NahuFigueroa97 approved these changes
LGTM!

2023-09-14 10:36 UTC, JcabreraC approved these changes
LGTM !

2023-09-14 10:37 UTC, merged