Fix issue with parameter in test_rootcheck_endpoints.tavern.yaml
wazuh/wazuh pull request #18707
Opened 2023-08-29 13:26 UTC by javiersanchz

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/18045|

## Description

The `cis` parameter has been removed from the tests related to `GET /rootcheck/001` to avoid validation. When the related integration tests are executed, they pass successfully, as shown below.

## Tests

### test_rootcheck_endpoints.tavern.yaml

```
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.2.0 -- /home/wazuh/venv/api-it/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.9.16', 'Platform': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.2.0'}, 'Plugins': {'metadata': '3.0.0', 'aiohttp': '1.0.4', 'html': '2.1.1', 'trio': '0.7.0', 'asyncio': '0.18.1', 'tavern': '1.23.5'}}
rootdir: /home/wazuh/Git/wazuh/api/test/integration
configfile: pytest.ini
plugins: metadata-3.0.0, aiohttp-1.0.4, html-2.1.1, trio-0.7.0, asyncio-0.18.1, tavern-1.23.5
asyncio: mode=auto
collected 4 items                                                                                                                                                                                         

test_rootcheck_endpoints.tavern.yaml::GET /rootcheck/001 PASSED                                                                                                                                     [ 25%]
test_rootcheck_endpoints.tavern.yaml::GET /rootcheck/001/last_scan PASSED                                                                                                                           [ 50%]
test_rootcheck_endpoints.tavern.yaml::PUT /rootcheck PASSED                                                                                                                                         [ 75%]
test_rootcheck_endpoints.tavern.yaml::DELETE /rootcheck/{agent_id} PASSED                                                                                                                           [100%]
```

### test_rbac_white_rootcheck_endpoints.tavern.yaml

```
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.2.0 -- /home/wazuh/venv/api-it/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.9.16', 'Platform': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.2.0'}, 'Plugins': {'metadata': '3.0.0', 'aiohttp': '1.0.4', 'html': '2.1.1', 'trio': '0.7.0', 'asyncio': '0.18.1', 'tavern': '1.23.5'}}
rootdir: /home/wazuh/Git/wazuh/api/test/integration
configfile: pytest.ini
plugins: metadata-3.0.0, aiohttp-1.0.4, html-2.1.1, trio-0.7.0, asyncio-0.18.1, tavern-1.23.5
asyncio: mode=auto
collected 4 items                                                                                                                                                                                         

test_rbac_white_rootcheck_endpoints.tavern.yaml::GET /rootcheck PASSED                                                                                                                              [ 25%]
test_rbac_white_rootcheck_endpoints.tavern.yaml::GET /rootcheck/{agent_id}/last_scan PASSED                                                                                                         [ 50%]
test_rbac_white_rootcheck_endpoints.tavern.yaml::PUT /rootcheck PASSED                                                                                                                              [ 75%]
test_rbac_white_rootcheck_endpoints.tavern.yaml::DELETE /rootcheck/{agent_id} PASSED                                                                                                                [100%]
```

### test_rbac_black_rootcheck_endpoints.tavern.yaml

```
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.2.0 -- /home/wazuh/venv/api-it/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.9.16', 'Platform': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.2.0'}, 'Plugins': {'metadata': '3.0.0', 'aiohttp': '1.0.4', 'html': '2.1.1', 'trio': '0.7.0', 'asyncio': '0.18.1', 'tavern': '1.23.5'}}
rootdir: /home/wazuh/Git/wazuh/api/test/integration
configfile: pytest.ini
plugins: metadata-3.0.0, aiohttp-1.0.4, html-2.1.1, trio-0.7.0, asyncio-0.18.1, tavern-1.23.5
asyncio: mode=auto
collected 4 items                                                                                                                                                                                         

test_rbac_black_rootcheck_endpoints.tavern.yaml::GET /rootcheck PASSED                                                                                                                              [ 25%]
test_rbac_black_rootcheck_endpoints.tavern.yaml::DELETE /rootcheck/{agent_id} PASSED                                                                                                                [ 50%]
test_rbac_black_rootcheck_endpoints.tavern.yaml::GET /rootcheck/{agent_id}/last_scan PASSED                                                                                                         [ 75%]
test_rbac_black_rootcheck_endpoints.tavern.yaml::PUT /rootcheck PASSED                                                                                                                              [100%]
```

2023-08-31 17:56 UTC, GGP1 requested changes
The `cis` field may be null and therefore not be part of the response, so the changes look good to me. However, I'm curious about what caused the test to start failing if it was working as expected previously even when validating that field.

Please rebase the branch to `4.5.3` (it won't be part of `4.5.2` as explained [here](https://github.com/wazuh/wazuh/issues/18045#issuecomment-1682199337)), it will also re-run the API integration test that failed.

2023-09-01 12:59 UTC, javiersanchz commented
Rebase branch to `4.5.3 `done

2023-10-05 09:41 UTC, javiersanchz commented
## Update

In the context of Rootcheck scanning, the `cis` field in the results is not mandatory and will only contain information if a specific string `("{CIS: ")` is found in the `log` field of the scanning event. This means that not all Rootcheck scan results will have information in the `cis` column, and its absence does not indicate an error in the system. Some test cases failed because they expected the `cis` field to be present in all results, but the logic for extracting `cis` from the `log` field dictates that this field can be empty if the specific string is not found

As mentioned in this thread: https://wazuh-team.slack.com/archives/C038AR25C8N/p1690300139692849?thread_ts=1690298215.090539&cid=C038AR25C8N

2023-10-05 13:18 UTC, GGP1 approved these changes
LGTM!

2023-10-09 15:34 UTC, Selutario requested changes
The changes LGTM, but this is now out of time to be included in 4.5.3. Please, rebase to 4.7.1 @javiersanchz

2023-10-18 09:37 UTC, Selutario requested changes
Some failing [checks](https://github.com/wazuh/wazuh/pull/18707/checks?check_run_id=17788261489) to review

2023-11-08 17:03 UTC, Selutario approved these changes

2023-11-08 17:04 UTC, merged