Refactor API logging mechanism to avoid loggers' race condition
wazuh/wazuh pull request #18733
Opened 2023-08-30 20:39 UTC by fdalmaup

|Related issue|
|---|
| #18456 |

## Description

Closes #18456. It modifies the mechanism used by the three API loggers (`connexion.aiohttp_app`, `connexion.apis.aiohttp_api`, `wazuh-api`) defined in `wazuh-apid.py` to log into `api.log` and how the API process rotates its logs to avoid race conditions between the loggers.

## API and Framework Unit Tests

<details><summary>API</summary>

    ====================================================================== test session starts ======================================================================
    platform linux -- Python 3.9.18, pytest-7.0.1, pluggy-0.13.1
    rootdir: /home/fdalmau/git/wazuh/api
    plugins: cov-3.0.0, aiohttp-1.0.4, trio-0.7.0, anyio-3.6.2, metadata-2.0.2, html-3.0.0, asyncio-0.18.1
    asyncio: mode=auto
    collected 540 items                                                                                                                                             
    
    api/api/controllers/test/test_active_response_controller.py .                                                                                             [  0%]
    api/api/controllers/test/test_agent_controller.py ............................................                                                            [  8%]
    api/api/controllers/test/test_cdb_list_controller.py ......                                                                                               [  9%]
    api/api/controllers/test/test_ciscat_controller.py .                                                                                                      [  9%]
    api/api/controllers/test/test_cluster_controller.py ........................                                                                              [ 14%]
    api/api/controllers/test/test_decoder_controller.py .......                                                                                               [ 15%]
    api/api/controllers/test/test_default_controller.py .                                                                                                     [ 15%]
    api/api/controllers/test/test_experimental_controller.py ...............                                                                                  [ 18%]
    api/api/controllers/test/test_manager_controller.py ..................                                                                                    [ 21%]
    api/api/controllers/test/test_mitre_controller.py .......                                                                                                 [ 22%]
    api/api/controllers/test/test_overview_controller.py .                                                                                                    [ 23%]
    api/api/controllers/test/test_rootcheck_controller.py ....                                                                                                [ 23%]
    api/api/controllers/test/test_rule_controller.py ........                                                                                                 [ 25%]
    api/api/controllers/test/test_sca_controller.py ..                                                                                                        [ 25%]
    api/api/controllers/test/test_security_controller.py ...................................................                                                  [ 35%]
    api/api/controllers/test/test_syscheck_controller.py ....                                                                                                 [ 35%]
    api/api/controllers/test/test_syscollector_controller.py .........                                                                                        [ 37%]
    api/api/controllers/test/test_task_controller.py .                                                                                                        [ 37%]
    api/api/controllers/test/test_vulnerability_controller.py ....                                                                                            [ 38%]
    api/api/models/test/test_model.py ...........................                                                                                             [ 43%]
    api/api/test/test_alogging.py ..................                                                                                                          [ 46%]
    api/api/test/test_authentication.py ...........                                                                                                           [ 48%]
    api/api/test/test_configuration.py ..........................................                                                                             [ 56%]
    api/api/test/test_encoder.py ...                                                                                                                          [ 57%]
    api/api/test/test_middlewares.py ............                                                                                                             [ 59%]
    api/api/test/test_uri_parser.py ...                                                                                                                       [ 60%]
    api/api/test/test_util.py ........................................                                                                                        [ 67%]
    api/api/test/test_validator.py .......................................................................................................................... [ 90%]
    ......................................................                                                                                                    [100%]
    
    =============================================================== 540 passed, 18 warnings in 4.06s ================================================================

</details>
<details><summary>Framework</summary>

    ====================================================================== test session starts ======================================================================
    platform linux -- Python 3.9.18, pytest-7.0.1, pluggy-0.13.1
    rootdir: /home/fdalmau/git/wazuh/framework
    plugins: cov-3.0.0, aiohttp-1.0.4, trio-0.7.0, anyio-3.6.2, metadata-2.0.2, html-3.0.0, asyncio-0.18.1
    asyncio: mode=auto
    collected 2053 items                                                                                                                                            
    
    framework/scripts/tests/test_agent_groups.py ..............                                                                                               [  0%]
    framework/scripts/tests/test_agent_upgrade.py ...............                                                                                             [  1%]
    framework/scripts/tests/test_cluster_control.py ......                                                                                                    [  1%]
    framework/scripts/tests/test_wazuh_clusterd.py .......                                                                                                    [  2%]
    framework/scripts/tests/test_wazuh_logtest.py ......................                                                                                      [  3%]
    framework/wazuh/core/cluster/dapi/tests/test_dapi.py ................................                                                                     [  4%]
    framework/wazuh/core/cluster/tests/test_client.py ................                                                                                        [  5%]
    framework/wazuh/core/cluster/tests/test_cluster.py ...................................                                                                    [  7%]
    framework/wazuh/core/cluster/tests/test_common.py ...........................................................................  [...]

2023-09-01 18:45 UTC, GGP1 requested changes

2023-09-01 18:45 UTC, GGP1 commented on api/api/alogging.py
> +    def setup_logger(self, custom_handler: logging.Handler = None):
Add `custom_handler` parameter type hint

2023-09-01 18:45 UTC, GGP1 commented on framework/wazuh/core/wlogging.py
> +from multiprocessing import Queue
Remove unused import

2023-09-04 13:29 UTC, GGP1 approved these changes
LGTM

2023-09-15 09:38 UTC, Selutario approved these changes

2023-09-15 09:38 UTC, merged