18523 engine filter test output by namespaces
wazuh/wazuh pull request #18758
Opened 2023-09-01 17:05 UTC by NahuFigueroa97

|Related issue|
|---|
|#18523|

## Description

2023-09-07 12:02 UTC, soynof commented on src/engine/source/api/include/api/test/handlers.hpp
> +                     const std::shared_ptr<store::IStore>& store);
Please, check documentation.

2023-09-07 15:25 UTC, juliancnn requested changes

2023-09-07 15:25 UTC, juliancnn commented on src/engine/source/proto/src/test.proto
> +    repeated string namespaceid = 7;       // Namespaces where are the assets to test
```suggestion
    repeated string namespaces = 7;       // Namespaces where are the assets to test
```

2023-09-07 19:39 UTC, soynof commented on src/engine/source/router/include/router/policyManager.hpp
> +     * @param assets Vector of asset names to subscribe to.
Check parameters order

2023-09-07 19:39 UTC, soynof commented on src/engine/source/router/include/router/router.hpp
> +     * @param assets Vector of asset names to subscribe to.
Check parameters order

2023-09-08 04:41 UTC, juliancnn approved these changes
LGTM!

2023-09-08 07:00 UTC, JavierBejMen approved these changes
LGTM

2023-09-08 09:35 UTC, JcabreraC commented on src/engine/source/router/include/router/router.hpp
> +     * @param assets Vector of asset names to subscribe to.
done

2023-09-08 09:35 UTC, JcabreraC commented on src/engine/source/router/include/router/policyManager.hpp
> +     * @param assets Vector of asset names to subscribe to.
Done

2023-09-08 09:52 UTC, JcabreraC approved these changes
LGTM !

2023-09-08 09:52 UTC, merged