Filter logs files by `flowlog id` in AWS Wodle
wazuh/wazuh pull request #19002
Opened 2023-09-13 15:36 UTC by nico-stefani

|Related issue|
|---|
| #18901 |

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2023-09-13 17:44 UTC, GGP1 requested changes
Re-run failed [check](https://github.com/wazuh/wazuh/pull/19002/checks?check_run_id=16762368105)

2023-09-13 17:44 UTC, GGP1 commented on wodles/aws/aws_s3.py
> +    def _filter_bucket_files(self, bucket_files, **kwargs):
Add docstring and `bucket_files` type hint

2023-09-13 17:44 UTC, GGP1 commented on wodles/aws/aws_s3.py
> +    def _filter_bucket_files(self, bucket_files, **kwargs):
Add docstring and `bucket_files` type hint

2023-09-14 13:03 UTC, GGP1 approved these changes
LGTM!

2023-09-19 09:03 UTC, Selutario approved these changes

2023-09-19 09:03 UTC, merged