Multiple tenants in ms-graph
wazuh/wazuh pull request #19064
Opened 2023-09-20 01:08 UTC by lsayanes

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/18202|

## Description

This PR adds multi-tenant capability to the **ms-graph** module.
For this, the `auth_config` member of the wm_ms_graph structure was converted into an array: 

```
typedef struct wm_ms_graph {
	bool enabled;
	bool only_future_events;
	ssize_t curl_max_size;
	bool run_on_start;
	char* version;
	sched_scan_config scan_config;
	wm_ms_graph_auth **auth_config;
	wm_ms_graph_resource* resources;
	unsigned int num_resources;
	wm_ms_graph_state_t state;
} wm_ms_graph;
```
and the functions of the ms-graph module were adapted.

## Configuration options

The following configuration has been used to test the new feature:
```
<ms-graph>
    <enabled>yes</enabled>
    <only_future_events>no</only_future_events>
    <curl_max_size>10M</curl_max_size>
    <run_on_start>no</run_on_start>
    <interval>1m</interval>
    <version>v1.0</version>
    <api_auth>
      <tenant_id>tenant_1</tenant_id>
      <client_id>client_1</client_id>
      <secret_value>secret_1</secret_value>
      <api_type>global</api_type>
    </api_auth>
    <api_auth>
      <tenant_id>tenant_2</tenant_id>
      <client_id>client_2</client_id>
      <secret_value>secret_2</secret_value>
      <api_type>global</api_type>
    </api_auth>
    <api_auth>
      <tenant_id>tenant_3</tenant_id>
      <client_id>client_3</client_id>
      <secret_value>secret_3</secret_value>
      <api_type>global</api_type>
    </api_auth>
    <resource>
      <name>auditLogs</name>
      <relationship>signIns</relationship>
    </resource>
</ms-graph>
```

## Test Logs

**tenant_1:**
```
Mock responses for 5 url patterns loaded from /Users/lsayanes/Code/m365-developer-proxy-main/m365-developer-proxy/bin/Debug/net7.0/responses.json
Listening on 0.0.0.0:8000...
  WARNING: Configure your operating system to use this proxy's port and address
Press CTRL+C to stop the Microsoft 365 Developer Proxy

 request     POST http://login.microsoftonline.com/tenant_1/oauth2/v2.0/token
    mock   ╭ 200 http://login.microsoftonline.com/*/oauth2/v2.0/token
           ╰ POST http://login.microsoftonline.com/tenant_1/oauth2/v2.0/token
 request     GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
    mock   ╭ 403 http://*/*/*/*$filter=createdDateTime+gt+*
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
 request     GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
 warning   ╭ Another request to /v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z intercepted within 5 seconds.
           │ Last intercepted at 9/18/2023 4:04:18 PM.
           │ Consider using cache to avoid calling the API too often.
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
    mock   ╭ 403 http://*/*/*/*$filter=createdDateTime+gt+*
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
 request     GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T19:00:49Z
    mock   ╭ 403 http://*/*/*/*$filter=createdDateTime+gt+*
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T19:00:49Z
```
**tenant_2:**
```
 request     POST http://login.microsoftonline.com/tenant_2/oauth2/v2.0/token
    mock   ╭ 200 http://login.microsoftonline.com/*/oauth2/v2.0/token
           ╰ POST http://login.microsoftonline.com/tenant_2/oauth2/v2.0/token
 request     GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
 warning   ╭ Another request to /v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z intercepted within 5 seconds.
           │ Last intercepted at 9/18/2023 4:04:18 PM.
           │ Consider using cache to avoid calling the API too often.
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
    mock   ╭ 403 http://*/*/*/*$filter=createdDateTime+gt+*
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
 request     GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
 warning   ╭ Another request to /v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z intercepted within 5 seconds.
           │ Last intercepted at 9/18/2023 4:04:18 PM.
           │ Consider using cache to avoid calling the API too often.
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
    mock   ╭ 403 http://*/*/*/*$filter=createdDateTime+gt+*
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
 request     GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T19:00:49Z
 warning   ╭ Another request to /v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T19:00:49Z intercepted within 5 seconds.
           │ Last intercepted at 9/18/2023 4:04:18 PM.
           │ Consider using cache to avoid calling the API too often.
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T19:00:49Z
    mock   ╭ 403 http://*/*/*/*$filter=createdDateTime+gt+*
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T19:00:49Z
```
**tenant_3:**
```
 request     POST http://login.microsoftonline.com/tenant_3/oauth2/v2.0/token
    mock   ╭ 200 http://login.microsoftonline.com/*/oauth2/v2.0/token
           ╰ POST http://login.microsoftonline.com/tenant_3/oauth2/v2.0/token
 request     GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
 warning   ╭ Another request to /v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z intercepted within 5 seconds.
           │ Last intercepted at 9/18/2023 4:04:18 PM.
           │ Consider using cache to avoid calling the API too often.
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
    mock   ╭ 403 http://*/*/*/*$filter=createdDateTime+gt+*
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
 request     GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
 warning   ╭ Another request to /v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z intercepted within 5 seconds.
           │ Last intercepted at 9/18/2023 4:04:18 PM.
           │ Consider using cache to avoid calling the API too often.
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
    mock   ╭ 403 http://*/*/*/*$filter=createdDateTime+gt+*
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T18:55:45Z
 request     GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T19:00:49Z
 warning   ╭ Another request to /v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T19:00:49Z intercepted within 5 seconds.
           │ Last intercepted at 9/18/2023 4:04:18 PM.
           │ Consider using cache to avoid calling the API too often.
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T19:00:49Z
    mock   ╭ 403 http://*/*/*/*$filter=createdDateTime+gt+*
           ╰ GET http://graph.microsoft.com/v1.0/auditLogs/signIns?$filter=createdDateTime+gt+2023-09-18T19:00:49Z
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [ ] Windows
  -  [...]

2023-09-25 18:34 UTC, mateocervilla requested changes

2023-09-25 18:34 UTC, mateocervilla commented on src/config/wmodules-ms-graph.c
> +	int e;
Unused variable?
```suggestion
```

2023-09-25 18:34 UTC, mateocervilla commented on src/config/wmodules-ms-graph.c
> +	wm_ms_graph_auth *it;
```suggestion
	wm_ms_graph_auth *it;
```

2023-09-25 18:34 UTC, mateocervilla commented on src/config/wmodules-ms-graph.c
> +
```suggestion
```

2023-09-25 18:34 UTC, mateocervilla commented on src/config/wmodules-ms-graph.c
> +			for (int j = 0; children[j]; j++) {
```suggestion
			for (int j = 0; children[j]; j++) {
```

2023-09-25 18:34 UTC, mateocervilla commented on src/config/wmodules-ms-graph.c
> +
```suggestion

```

2023-09-25 18:34 UTC, mateocervilla commented on src/config/wmodules-ms-graph.c
> +
```suggestion
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
```suggestion
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +
```suggestion
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +
```suggestion
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +
```suggestion
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +
```suggestion

```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +
```suggestion

```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +
```suggestion

```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    wm_ms_graph* module_data = (wm_ms_graph *)*state;
```suggestion
    wm_ms_graph* module_data = (wm_ms_graph *)*state;
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +
```suggestion

    wm_ms_graph_scan_relationships(module_data, initial);

```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +
```suggestion

```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
```suggestion

```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
```suggestion

```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```suggestion
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config);
    os_calloc(1, sizeof(wm_ms_graph_auth), module_data->auth_config[0]);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +
```suggestion

```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +
```suggestion

```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +    const struct CMUnitTest tests_without_startup[] = {
```suggestion
    const struct CMUnitTest tests_without_startup[] = {
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +
```suggestion
```

2023-09-25 18:34 UTC, mateocervilla commented on src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c
> +
```suggestion
    result = cmocka_run_group_tests(tests_without_startup, NULL, NULL);
    result += cmocka_run_group_tests(tests_with_startup, NULL, NULL);
```

2023-09-25 18:34 UTC, mateocervilla commented on src/wazuh_modules/wm_ms_graph.c
> +
```suggestion

```

2023-09-25 18:34 UTC, mateocervilla commented on src/wazuh_modules/wm_ms_graph.c
> +
```suggestion

```

2023-09-25 18:34 UTC, mateocervilla commented on src/wazuh_modules/wm_ms_graph.c
> +
```suggestion
    for (e = 0; ms_graph->auth_config && ms_graph->auth_config[e]; e++) {
        it = ms_graph->auth_config[e];

```

2023-09-25 18:54 UTC, lsayanes commented
Code style resolved

2023-09-25 19:01 UTC, lsayanes commented
Due to the **[issue](https://github.com/wazuh/wazuh/issues/18785)** in master installation checks will fail
![Captura de pantalla 2023-09-25 a la(s) 15 57 54](https://github.com/wazuh/wazuh/assets/68856625/d89b2635-7f0a-47ad-b83c-d97229cca614)

2023-10-26 16:05 UTC, MarcelKemp requested changes

2023-10-31 17:05 UTC, MarcelKemp approved these changes

2023-11-02 12:09 UTC, MarcelKemp requested changes
The compilation of the UTs for Windows has failed:
- https://github.com/wazuh/wazuh/pull/19064/checks?check_run_id=18236425135
```
[ 12%] Built target MS_GRAPH_O
[ 13%] Building C object wazuh_modules/ms_graph/CMakeFiles/test_wm_ms_graph.dir/test_wm_ms_graph.c.obj
In file included from /tmp/build/wazuh/src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c:16:
/tmp/build/wazuh/src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c: In function 'test_wm_ms_graph_get_access_token_success':
/tmp/build/wazuh/src/unit_tests/wazuh_modules/ms_graph/test_wm_ms_graph.c:1893:46: error: request for member 'token_expiration_time' in something not a structure or union
 1893 |     assert_int_equal(module_data->auth_config.token_expiration_time, 123);
      |                                              ^
make[2]: *** [wazuh_modules/ms_graph/CMakeFiles/test_wm_ms_graph.dir/build.make:77: wazuh_modules/ms_graph/CMakeFiles/test_wm_ms_graph.dir/test_wm_ms_graph.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:789: wazuh_modules/ms_graph/CMakeFiles/test_wm_ms_graph.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
```
Please fix it.

2023-11-07 10:55 UTC, MarcelKemp approved these changes

2023-11-08 12:12 UTC, mateocervilla approved these changes

2023-11-08 12:25 UTC, merged