UTF8 exec command on windows agent
wazuh/wazuh pull request #19146
Opened 2023-09-22 18:27 UTC by tdrauncieal

|Related issue|
|---|
|#18743|

## Description
Following the recommendations proposed in the issue and after making the necessary changes to allow this call to be transformed into UTF-8, the problem is considered solved.

## Tests
This output shows how using the same scenario it is now possible to correctly run these `Utilisation_Memoire` commands that make use of accented characters

<details><summary>Details</summary>
<p>

```shell

2023/09/20 23:14:41 wazuh-modulesd:command[4164] wm_command.c:187 at wm_command_main(): DEBUG: Sleeping until: 2023/09/20 23:15:40
PS C:\Program Files\ossec-agent> Get-Content -Tail 100 -Wait .\ossec.log | Select-String command

2023/09/20 23:15:40 wazuh-modulesd:command[4164] wm_command.c:192 at wm_command_main(): INFO: Starting command 'Utilisation_Memoire'.
2023/09/20 23:15:40 wazuh-modulesd:command[4164] wm_command.c:192 at wm_command_main(): INFO: Starting command 'Utilisation_CPU'.
2023/09/20 23:15:40 wazuh-agent[4164] wm_exec.c:123 at wm_exec(): DEBUG: UTF-8 command: Powershell -c "@{ winCounter = (Get-Counter
'\mémoire\mégaoctets disponibles').CounterSamples[0] } | ConvertTo-Json -compress"
2023/09/20 23:15:40 wazuh-agent[4164] wm_exec.c:123 at wm_exec(): DEBUG: UTF-8 command: Powershell -c "@{ winCounter = (Get-Counter
'\processeur(_total)\% temps processeur').CounterSamples[0] } | ConvertTo-Json -compress"
2023/09/20 23:15:51 wazuh-modulesd:command[3524] wm_command.c:151 at wm_command_main(): INFO: Module command:Utilisation_Disque started
2023/09/20 23:15:51 wazuh-modulesd:command[3524] wm_command.c:151 at wm_command_main(): INFO: Module command:Utilisation_Memoire started
2023/09/20 23:15:51 wazuh-modulesd:command[3524] wm_command.c:151 at wm_command_main(): INFO: Module command:Utilisation_CPU started
2023/09/20 23:15:51 wazuh-modulesd:command[3524] wm_command.c:192 at wm_command_main(): INFO: Starting command 'Utilisation_Disque'.
2023/09/20 23:15:51 wazuh-modulesd:command[3524] wm_command.c:192 at wm_command_main(): INFO: Starting command 'Utilisation_Memoire'.
2023/09/20 23:15:51 wazuh-modulesd:command[3524] wm_command.c:192 at wm_command_main(): INFO: Starting command 'Utilisation_CPU'.
2023/09/20 23:15:51 wazuh-agent[3524] wm_exec.c:123 at wm_exec(): DEBUG: UTF-8 command: Powershell -c "@{ winCounter = (Get-Counter
-Counter '\disque logique(C:)\% d''espace libre').CounterSamples[0]} | ConvertTo-Json -compress"
2023/09/20 23:15:51 wazuh-agent[3524] wm_exec.c:123 at wm_exec(): DEBUG: UTF-8 command: Powershell -c "@{ winCounter = (Get-Counter
'\processeur(_total)\% temps processeur').CounterSamples[0] } | ConvertTo-Json -compress"
2023/09/20 23:15:51 wazuh-agent[3524] wm_exec.c:123 at wm_exec(): DEBUG: UTF-8 command: Powershell -c "@{ winCounter = (Get-Counter
'\mémoire\mégaoctets disponibles').CounterSamples[0] } | ConvertTo-Json -compress"
2023/09/20 23:15:52 rootcheck[3524] common_rcl.c:412 at rkcl_get_entry(): DEBUG: Checking registry:
'HKEY_CLASSES_ROOT\aim\shell\open\command'.
2023/09/20 23:15:52 wazuh-agent[3524] create_db.c:1669 at fim_check_restrict(): DEBUG: (6203): Ignoring entry
'c:\windows\system32\command.com' due to restriction 'winrm.vbs$'
2023/09/20 23:15:52 wazuh-agent[3524] create_db.c:1669 at fim_check_restrict(): DEBUG: (6203): Ignoring entry
'c:\windows\system32\dmcommandlineutils.dll' due to restriction 'winrm.vbs$'
2023/09/20 23:15:53 wazuh-agent[3524] create_db.c:1669 at fim_check_restrict(): DEBUG: (6203): Ignoring entry
'c:\windows\system32\provisioningcommandscsp.dll' due to restriction 'winrm.vbs$'
2023/09/20 23:15:53 wazuh-modulesd:command[3524] wm_command.c:231 at wm_command_main(): DEBUG: Command 'Utilisation_Disque' finished.
2023/09/20 23:15:53 wazuh-modulesd:command[3524] wm_command.c:231 at wm_command_main(): DEBUG: Command 'Utilisation_CPU' finished.
2023/09/20 23:15:53 wazuh-modulesd:command[3524] wm_command.c:231 at wm_command_main(): DEBUG: Command 'Utilisation_Memoire' finished.
2023/09/20 23:15:53 wazuh-modulesd:command[3524] wm_command.c:187 at wm_command_main(): DEBUG: Sleeping until: 2023/09/20 23:25:51
2023/09/20 23:15:53 wazuh-modulesd:command[3524] wm_command.c:187 at wm_command_main(): DEBUG: Sleeping until: 2023/09/20 23:16:51
2023/09/20 23:15:53 wazuh-modulesd:command[3524] wm_command.c:187 at wm_command_main(): DEBUG: Sleeping until: 2023/09/20 23:16:51
2023/09/20 23:16:51 wazuh-modulesd:command[3524] wm_command.c:192 at wm_command_main(): INFO: Starting command 'Utilisation_CPU'.
2023/09/20 23:16:51 wazuh-modulesd:command[3524] wm_command.c:192 at wm_command_main(): INFO: Starting command 'Utilisation_Memoire'.
2023/09/20 23:16:51 wazuh-agent[3524] wm_exec.c:123 at wm_exec(): DEBUG: UTF-8 command: Powershell -c "@{ winCounter = (Get-Counter
'\mémoire\mégaoctets disponibles').CounterSamples[0] } | ConvertTo-Json -compress"
2023/09/20 23:16:51 wazuh-agent[3524] wm_exec.c:123 at wm_exec(): DEBUG: UTF-8 command: Powershell -c "@{ winCounter = (Get-Counter
'\processeur(_total)\% temps processeur').CounterSamples[0] } | ConvertTo-Json -compress"
2023/09/20 23:16:53 wazuh-modulesd:command[3524] wm_command.c:231 at wm_command_main(): DEBUG: Command 'Utilisation_CPU' finished.
2023/09/20 23:16:53 wazuh-modulesd:command[3524] wm_command.c:187 at wm_command_main(): DEBUG: Sleeping until: 2023/09/20 23:17:51
2023/09/20 23:16:53 wazuh-modulesd:command[3524] wm_command.c:231 at wm_command_main(): DEBUG: Command 'Utilisation_Memoire' finished.
2023/09/20 23:16:53 wazuh-modulesd:command[3524] wm_command.c:187 at wm_command_main(): DEBUG: Sleeping until: 2023/09/20 23:17:51

``` 

</p>
</details> 

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [X] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [X] Package installation
- [ ] Source upgrade
- [X] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

2023-11-16 17:06 UTC, MarcelKemp requested changes

2023-11-16 17:20 UTC, tdrauncieal commented on src/wazuh_modules/wm_exec.c
> +    free(wcommand);
I change also `os_calloc() `call

2023-11-16 17:21 UTC, tdrauncieal commented on src/wazuh_modules/wm_exec.c
> +    if (!CreateProcessW(NULL, wcommand, NULL, NULL, TRUE, dwCreationFlags, NULL, NULL, &sinfo, &pinfo)) {
done!

2023-11-17 18:00 UTC, MarcelKemp approved these changes

2023-11-23 15:31 UTC, merged