Syscollector IT migration
wazuh/wazuh pull request #19324
Opened 2023-09-28 23:22 UTC by mateocervilla

|Related issue|
|---|
|#19086|

## Description

This PR includes all the necessary changes to move the syscollector integration tests from wazuh-qa to this repository. Those tests will use a new structure that is being developed here (https://github.com/wazuh/qa-integration-framework/pull/40).

2023-10-11 12:15 UTC, tdrauncieal commented
test evidence.
![image](https://github.com/wazuh/wazuh/assets/93778492/5dc15caf-d4bf-406f-a4d6-8693a1f49e4d)

2023-10-11 12:16 UTC, tdrauncieal submitted a review, later dismissed

2023-10-13 23:24 UTC, Leoquicenoz submitted a review, later dismissed
LGTM!!

2023-10-25 17:59 UTC, TomasTurina requested changes
Missing `__init__.py` file inside `tests/integration/test_syscollector`.

Also, probably you'll need to rebase this branch.

2023-10-25 17:59 UTC, TomasTurina commented on tests/integration/test_syscollector/data/configuration/configuration_syscollector.yaml
Folder name should be `configuration_templates`.

2023-10-25 17:59 UTC, TomasTurina commented on tests/integration/test_syscollector/test_syscollector_configuration.py
> +TEST_DATA_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'data')
Use `Path` instead of `os.path`:
```
from pathlib import Path
```

2023-10-25 18:19 UTC, TomasTurina requested changes
Also, remember to add the GitHub workflow to execute this tests in each PR.

Check any other suite already migrated, for example:
```
.github/workflows/integration-tests-github-tier-0-1-lin.yml
.github/workflows/integration-tests-github-tier-0-1-win.yml
```

2023-11-29 15:23 UTC, TomasTurina commented on .github/workflows/integration-tests-syscollector-tier-0-1-lin.yml
> +      # Build wazuh server for linux.
I think it's better to use wazuh agent since this module will not be part of the server in the future.

2023-11-29 15:23 UTC, TomasTurina commented on tests/integration/test_syscollector/test_syscollector_configuration.py
> +import os
Unused import.

2023-11-29 21:31 UTC, TomasTurina approved these changes

2023-11-29 21:32 UTC, merged