Engine - update windows powershell integration
wazuh/wazuh pull request #19474
Opened 2023-10-06 19:00 UTC by NahuFigueroa97

|Related issue|
|---|
|#19407|

## Description

The existing Powershell integration in Wazuh needs to be updated and enhanced. With the evolution of Wazuh and the introduction of new syntax and standards, it's crucial to ensure that the Powershell integration aligns with these changes and extracts relevant fields efficiently.

2023-10-10 14:13 UTC, soynof requested changes

2023-10-10 21:02 UTC, soynof requested changes

2023-10-10 21:02 UTC, soynof commented on src/engine/ruleset/integrations/windows/decoders/windows-powershell-operational.yml
> +check: $windows.System.Channel.#text == Microsoft-Windows-PowerShell/Operational
We should unify the way of checking this field. I think the most legible way is how it was added in the `Windows Powershell` decoder, like this:

```
check:
  - windows.System.Channel.#text: Microsoft-Windows-PowerShell/Operational
```

What do you think?

2023-10-11 04:50 UTC, NahuFigueroa97 commented
The values of system keywords and opcode were obtained from here https://github.com/nihon-tc/Rtest/blob/8246e4d21323802fb84c406edc1a005991304f5a/header/Microsoft%20SDKs/Windows/v7.0A/Include/winmeta.xml
Also, because the keywords values are 64 bits, the helper was updated with said change.

2023-10-11 10:32 UTC, JavierBejMen requested changes
The function was 32-bit because where used on 32-bit masks, please revert changes and make an additional function or template.

2023-10-11 11:22 UTC, soynof requested changes

2023-10-11 11:22 UTC, soynof commented on src/engine/source/builder/builders/opBuilderKVDB.cpp
> +std::function<std::optional<json::Json>(uint64_t pos)> getFnSearchMap(const json::Json& jMap)
Shouldn't we have both functions? one for 32 and one for 64 bits?

2023-10-11 11:22 UTC, soynof commented on src/engine/test/source/builder/builders/opBuilderKVDBDecodeBitmask_test.cpp
> +        BuildMapT(json::Json {R"( {"0" : "zero", "1" : "one", "64" : "sixty four", "65" : "sixty five"} )"}, false),
We should have coverage for 32 and 64 bit masks

2023-10-11 11:22 UTC, soynof commented on src/engine/test/source/builder/builders/opBuilderKVDBDecodeBitmask_test.cpp
> +        DecodeMaskT(R"("0x1FFFFFFFFFFFFFFFF")", {}, false),
ditto

2023-10-11 12:39 UTC, juliancnn requested changes

2023-10-11 12:39 UTC, juliancnn commented on src/engine/ruleset/integrations/windows/decoders/windows-powershell.yml
> +   - windows.logon.keywords: kvdb_decode_bitmask(windows_bitmask_tables, Keywords, $windows.System.Keywords.#text)
Should  check the special case wjhens Keywords, `$windows.System.Keywords.#text == 0x0`

2023-10-11 14:57 UTC, soynof approved these changes
LGTM!

2023-10-12 20:30 UTC, juliancnn approved these changes

2023-10-18 12:17 UTC, JcabreraC approved these changes
LGTM !

2023-10-18 12:44 UTC, merged