Add cloud logger to installation script
wazuh/wazuh pull request #19581
Opened 2023-10-10 20:37 UTC by EduLeon12

|Related issue|
|---|
|Closes #19575 |

## Description

As explained in #19575, Thie Pr tends to modify the installation script to include the cloud logger.

2023-10-12 12:38 UTC, GGP1 requested changes
The installation was successful and the cloud logger was found at `/var/ossec/wodles/shared/wazuh_cloud_logger.py`. Just suggested to align comments with commands.

2023-10-12 12:38 UTC, GGP1 commented on src/init/inst-functions.sh
> +    ${INSTALL} -d -m 0750 -o root -g ${WAZUH_GROUP} ${INSTALLDIR}/wodles/shared
```suggestion
    # Install the Wazuh cloud logger
    ${INSTALL} -d -m 0750 -o root -g ${WAZUH_GROUP} ${INSTALLDIR}/wodles/shared
```

2023-10-12 12:38 UTC, GGP1 commented on src/init/inst-functions.sh
> +    ${INSTALL} -d -m 0750 -o root -g ${WAZUH_GROUP} ${INSTALLDIR}/wodles/shared
```suggestion
    # Install the Wazuh cloud logger
    ${INSTALL} -d -m 0750 -o root -g ${WAZUH_GROUP} ${INSTALLDIR}/wodles/shared
```

2023-10-20 14:46 UTC, GGP1 approved these changes
LGTM

2023-10-25 08:19 UTC, Selutario approved these changes

2023-10-25 08:22 UTC, merged