Make get_daemons_stats_socket async
wazuh/wazuh pull request #19712
Opened 2023-10-18 02:01 UTC by mhamra

|Related issue|
|---|
|#19394|

## Description
Make the get_daemons_stats_socket function asynchronous

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2023-11-01 16:24 UTC, mhamra commented
### API INTEGRATION TEST FAILURES

After running the AIT in a local environment with branch master and enhancement/19394-async-daemons-stats, I've found no difference in the failures, concluding that the failures were not introduced by the changes made on this PR.



```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================================ short test summary info ============================================================================================
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::/cluster/local/config
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/healthcheck
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/ruleset/synchronization
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/local/info
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/nodes
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/nodes/{node_id}
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/status
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration/{component}/{configuration}
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/daemons/stats
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/api/config
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::PUT /cluster/restart
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/configuration
============================================================================ 19 failed, 25 passed, 22 warnings in 732.83s (0:12:12) =============================================================================
```

```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================================ short test summary info ============================================================================================
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::/cluster/local/config
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/healthcheck
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/ruleset/synchronization
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/local/info
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/nodes
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/nodes/{node_id}
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/status
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration/{component}/{configuration}
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/daemons/stats
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/api/config
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::PUT /cluster/restart
FAILED test_rbac_white_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/configuration
============================================================================ 19 failed, 25 passed, 22 warnings in 719.38s (0:11:59) =============================================================================
```
### COMPLETE LOG

[complete log.txt](https://github.com/wazuh/wazuh/files/13229274/complete.log.txt)

2023-11-01 22:24 UTC, mhamra commented
### UPDATE
All AITs passed OK in this [check](https://github.com/wazuh/wazuh/pull/19712/checks?check_run_id=18269348125).

2023-11-15 14:36 UTC, GGP1 requested changes

2023-11-15 14:36 UTC, GGP1 commented on framework/wazuh/core/wazuh_socket.py
> +    async def receive(self, header_format:str="<I", header_size:int=4) -> bytes:
```suggestion
    async def receive(self, header_format: str ="<I", header_size: int =4) -> bytes:
```

2023-11-15 14:36 UTC, GGP1 commented on framework/wazuh/stats.py
> +                await get_daemons_stats_socket(daemon_socket_mapping[daemon]))
```suggestion
            res = await get_daemons_stats_socket(daemon_socket_mapping[daemon])
            result.affected_items.append(res)
```

2023-11-15 14:36 UTC, GGP1 commented on framework/wazuh/core/wazuh_socket.py
> +    async def receive_json(self, header_format="<I", header_size=4) -> dict:
```suggestion
    async def receive_json(self, header_format: str ="<I", header_size: int =4) -> dict:
```

2023-11-16 10:55 UTC, GGP1 submitted a review, later dismissed
LGTM

2024-02-09 12:32 UTC, Selutario requested changes
Looks good! I also checked whether the cluster `sendsync` protocol keeps working as expected, and it does, although `await` should be removed here:
https://github.com/wazuh/wazuh/blob/ad3fb60669a65beb1e3b96229960b38c1271532a/framework/wazuh/core/wazuh_socket.py#L270

Only some minor changes were requested additionally. It will be necessary to rebase with the master branch.

2024-02-21 18:37 UTC, mhamra commented on framework/wazuh/core/wazuh_socket.py
> +    async def receive(self, header_format: str ="<I", header_size: int =4) -> bytes:
Change committed:

https://github.com/wazuh/wazuh/blob/67860bcbcbc24331f817037c9f4886e335cde97a/framework/wazuh/core/wazuh_socket.py#L167

2024-02-21 18:38 UTC, mhamra commented on framework/wazuh/core/wazuh_socket.py
> +    async def send(self, msg_bytes: str, header_format: str ="<I") -> bytes:
Changes committed:

https://github.com/wazuh/wazuh/blob/67860bcbcbc24331f817037c9f4886e335cde97a/framework/wazuh/core/wazuh_socket.py#L200

2024-02-21 18:38 UTC, mhamra commented on framework/wazuh/core/wazuh_socket.py
> +        Returns that message.
Change committed:

https://github.com/wazuh/wazuh/blob/67860bcbcbc24331f817037c9f4886e335cde97a/framework/wazuh/core/wazuh_socket.py#L201

2024-02-21 18:46 UTC, mhamra commented
### UPDATE
- The branch was rebased to master.
- All the requested changes are committed to the branch.

2024-02-22 17:27 UTC, Selutario requested changes
I'd like this to be released in [4.9.0](https://github.com/wazuh/wazuh/issues/19394#event-a40ed22e-1071-58fd-8add-c0072f67e319) so we can see the behavior in prod before refactoring all the framework. Since master is currently 5.0.0, could you rebase to 4.9.0 branch instead? Everything else looks good!

2024-02-27 17:22 UTC, Selutario approved these changes
I finally decided that it's okay to merge this in 5.0. The failing check is unrelated to these changes, and should be fixed once the changed applied here reach the master branch:
- https://github.com/wazuh/wazuh/issues/21822

2024-02-27 17:22 UTC, merged