Logtest IT migration
wazuh/wazuh pull request #19929
Opened 2023-10-28 16:36 UTC by lsayanes

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/19082|

## Description
This PR includes all the necessary changes to move logtest Integrations from wazuh-qa to wazuh repository. Those tests will use a new structure that is being developed here https://github.com/wazuh/qa-integration-framework/pull/47

## Test folders

- test_configuration
- test_invalid_rule_decoders_syntax
- test_invalid_socket_input
- test_invalid_token
- test_log_process_options
- test_remove_old_sessions
- test_remove_session
- test_rules_decoders_load
- test_ruleset_refresh

- Compilation without warnings in every supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] MAC OS X

2024-01-15 19:00 UTC, TomasTurina requested changes
Also rebase.

2024-02-08 11:52 UTC, mateocervilla commented on tests/integration/test_logtest/test_invalid_rule_decoders_syntax/conftest.py
> +    # restore previous configuration
I believe they made it this way to avoid conflicts with other tests

2024-02-08 11:52 UTC, mateocervilla commented on tests/integration/test_logtest/test_invalid_rule_decoders_syntax/conftest.py
> +    # remove configuration
Same here, I believe they made it this way to avoid conflicts with other tests

2024-02-15 19:58 UTC, TomasTurina commented on tests/integration/test_logtest/test_rules_decoders_load/conftest.py
> +    shutil.chown(CUSTOM_RULES_FILE, "wazuh", "wazuh")
```suggestion
        shutil.chown(CUSTOM_RULES_FILE, "wazuh", "wazuh")
```

2024-02-15 19:59 UTC, TomasTurina approved these changes

2024-02-15 20:58 UTC, MarcelKemp approved these changes

2024-02-16 13:42 UTC, merged