Feature/18725 update check service system
wazuh/wazuh pull request #19952
Opened 2023-10-30 16:00 UTC by nico-stefani

|Related issue|
|---|
|#18725|

## Description

This PR adds a new functionality to query the available Wazuh updates from the CTI service. Also, includes a new endpoint for retrieving this information. 

## Logs/Alerts example

2023-11-01 20:32 UTC, nico-stefani commented
I've created [feature/18725-update-check-service-system-bis](https://github.com/wazuh/wazuh/tree/feature/18725-update-check-service-system-bis) and cherry-picked eed98951c8f3459950c9ce8325b192b89d683a36 to execute the *Integration tests for API - Tier 0 and 1 / build (pull_request)* pipelines. 
[Here](https://github.com/wazuh/wazuh/actions/runs/6724448254/job/18276737763) are the results :green_circle:

2023-11-08 16:46 UTC, Selutario requested changes

2023-11-08 16:46 UTC, Selutario commented on api/api/signals.py
> +    return wazuh.__version__
These are no longer being used

2023-11-08 16:46 UTC, Selutario commented on api/api/signals.py
> +import ssl
```suggestion
```

2023-11-08 16:46 UTC, Selutario commented on api/api/signals.py
> +import certifi
```suggestion
```

2023-11-08 16:46 UTC, Selutario commented on api/api/signals.py
> +import wazuh
```suggestion
```

2023-11-08 16:46 UTC, Selutario commented on api/test/integration/test_manager_endpoints.tavern.yaml
> +  - name: Get available updates
```suggestion
  - name: Try to get available updates
```

2023-11-08 16:46 UTC, Selutario commented on api/test/integration/test_manager_endpoints.tavern.yaml
> +  - name: Get available updates with force option
```suggestion
  - name: Try to get available updates with force option
```

2023-11-09 11:24 UTC, Selutario approved these changes
LGTM. 

Failing checks are:
- **[Framework](https://github.com/wazuh/wazuh/pull/19952/checks?check_run_id=18494734783) and [API](https://github.com/wazuh/wazuh/pull/19952/checks?check_run_id=18518909484) unit tests:** Probably failed due to [changes in Jenkins](https://github.com/wazuh/wazuh-jenkins/pull/5268) in order to use Python 3.10. Should be fixed after rebasing with 4.8.0. The same tests were also run in Github Actions, where they passed successfully:
  - [Framework tests](https://github.com/wazuh/wazuh/actions/runs/6801939061)
  - [API tests](https://github.com/wazuh/wazuh/actions/runs/6801939083)
- **[Integration tests for API - Tier 0 and 1](https://github.com/wazuh/wazuh/actions/runs/6801939072):** The same tests passed successfully [here](https://github.com/wazuh/wazuh/pull/19952#issuecomment-1789633972) a week ago. The error does not seem related to the changes in this PR. 
  ```
  ValueError: Error when executing restart in daemon None. Exit status: 1
  ```
  In any case, please @nico-stefani open an issue to investigate it separately. 
- **[Build Linux x86_64/amd64 agent/manager](https://github.com/wazuh/wazuh/pull/19952/checks?check_run_id=18494182556):** The failures in those checks have nothing to do with the changes in this PR.
- **[Integration API endpoints test](https://github.com/wazuh/wazuh/pull/19952/checks?check_run_id=18495558248):** 
  - **test_agent_GET_endpoints:** Failed tests are related to [#20002](https://github.com/wazuh/wazuh/issues/20002), and maybe to [#20143](https://github.com/wazuh/wazuh/issues/20143). No changes were made in agent API endpoints.
  - **test_cluster_endpoints:** There were no changes in cluster API endpoints. The failed tests are related to [#20002](https://github.com/wazuh/wazuh/issues/20002) and [#18284](https://github.com/wazuh/wazuh/issues/18284).
  - **test_manager_endpoints:** There are failed tests after restarting Wazuh as a step of one of the Update check system tests. Restarting is taking more than 50s to complete, making it fail. Related to [#20143](https://github.com/wazuh/wazuh/issues/20143).

2023-11-09 12:11 UTC, merged