Modify and add python 3.10 unit test workflows to GitHub actions
wazuh/wazuh pull request #19965
Opened 2023-10-31 13:14 UTC by mhamra

|Related issue|
|---|
|#19949|

## Description

- Modify the API and framework unit test workflows to run with Python 3.10.
- Add new wodles and external integrations unit tests workflows.

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

2023-10-31 19:50 UTC, GGP1 requested changes

2023-10-31 19:50 UTC, GGP1 commented on .github/workflows/external-integrations-unit-tests.yml
> +name: EXTERNAL INTEGRATIONS unit tests
Just to be consistent with the naming of the rest of the workflows

```suggestion
name: External integrations unit tests
```

2023-10-31 19:50 UTC, GGP1 commented on .github/workflows/external-integrations-unit-tests.yml
> +      - name: Run EXTERNAL INTEGRATIONS tests
```suggestion
      - name: Run External integrations tests
```

or 

```suggestion
      - name: Run external integrations tests
```

2023-10-31 19:50 UTC, GGP1 commented on .github/workflows/wodles-unit-tests.yml
> +name: WODLES unit tests
```suggestion
name: Wodles unit tests
```

2023-10-31 19:50 UTC, GGP1 commented on .github/workflows/wodles-unit-tests.yml
> +      - name: Run WODLES tests
```suggestion
      - name: Run Wodles tests
```

2023-10-31 19:50 UTC, GGP1 commented on .github/workflows/external-integrations-unit-tests.yml
> +      - uses: actions/checkout@v3
We could take advantage of the fact that we are adding/updating all unit test workflows to update the version of this action to v4

```suggestion
      - uses: actions/checkout@v4
```

Same in the rest of the files

2023-11-01 12:34 UTC, GGP1 approved these changes
LGTM

2023-11-02 10:53 UTC, Selutario approved these changes

2023-11-02 10:54 UTC, merged