Added correct protobuf classes to api-communication
wazuh/wazuh pull request #20029
Opened 2023-11-03 10:21 UTC by JavierBejMen

|Related issue|
|---|
|#19998|

In this PR the Engine api-communication python library has been updated with protobuf classes for all endpoints as stub files. The current integration tests have been updated with the new interfaces.

2023-11-06 13:20 UTC, juliancnn approved these changes
LGTM!

2023-11-06 14:29 UTC, soynof requested changes

2023-11-06 14:39 UTC, soynof approved these changes
Great job! LGTM!

2023-11-06 15:16 UTC, NahuFigueroa97 approved these changes

2023-11-07 11:23 UTC, JcabreraC approved these changes
LGTM !

2023-11-07 13:29 UTC, merged