Add security analytics plugin
wazuh/wazuh pull request #20131
Opened 2023-11-08 08:18 UTC by JavierBejMen

|Related issue|
|---|
|#20090|

This PR adds the OpenSearch security analytics plugin installation on the Vagrant provision script. Also improves windows decoders integrity of the schema field mappings.

2023-11-08 14:45 UTC, soynof requested changes

2023-11-08 14:45 UTC, soynof commented on src/engine/ruleset/integrations/windows/decoders/windows-security.yml
> +      - user.domain: parse_fqdn($windows.EventData.TargetDomainName)
The `parse_fqdn($windows.EventData.TargetDomainName)` statement is used multiple times, would it be better to create a variable to assign it only once and execute the hf `parse_fqdn` only once? what do you think?

2023-11-09 13:24 UTC, soynof approved these changes
LGTM!

2023-11-09 17:39 UTC, juliancnn approved these changes
LGTM!

2023-11-10 13:05 UTC, JcabreraC approved these changes
LGTM !

2023-11-10 13:05 UTC, merged