Fix test_encrypt_by_method_aes fails on master
wazuh/wazuh pull request #20144
Opened 2023-11-08 15:06 UTC by diegodfrf

|Related issue|
|---|
|#20094|

## Description

2023-11-09 19:47 UTC, pereyra-m requested changes
Gj!

2023-11-09 19:47 UTC, pereyra-m commented on src/unit_tests/os_crypto/shared/test_msgs.c
Please, apply the initialization in all the tests

2023-11-10 00:37 UTC, pereyra-m commented on src/unit_tests/os_crypto/shared/test_msgs.c
Also, with an interactive rebase you can squash the commits of the PR and leave it more clean.

2023-11-10 13:19 UTC, pereyra-m approved these changes
LGTM!

2023-11-10 13:38 UTC, Dwordcito approved these changes

2023-11-10 13:38 UTC, merged