Modify server to allow responses to the client from modules
wazuh/wazuh pull request #20393
Opened 2023-11-23 15:42 UTC by NahuFigueroa97

|Related issue|
|---|
||

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2023-12-04 16:23 UTC, soynof requested changes

2023-12-04 16:23 UTC, soynof commented on src/engine/source/server/include/server/endpoints/unixStream.hpp
>       * @param message Message to be processed
Change param name to request

2023-12-05 12:46 UTC, juliancnn commented on src/engine/test/source/server/unixStream_test.cpp
> +    });
You must not mix the loop threads with the test threads, you cannot do a walk here.

2023-12-05 12:46 UTC, juliancnn commented on src/engine/test/source/server/unixStream_test.cpp
> +    EXPECT_EQ(numAsyncsOpen, 1);
```suggestion
    EXPECT_EQ(numAsyncsOpen, 0);
```

2023-12-05 12:46 UTC, juliancnn commented on src/engine/test/source/server/unixStream_test.cpp
> +    EXPECT_EQ(numAsyncsOpen, 1);
All handlers should be checked, not just the async ones.

2023-12-12 03:38 UTC, juliancnn approved these changes
LGTM!

2023-12-12 13:10 UTC, JcabreraC approved these changes
LGTM !

2023-12-12 13:10 UTC, merged