Fix AWS configuration profiles parsing
wazuh/wazuh pull request #20447
Opened 2023-11-27 19:09 UTC by GGP1

|Related issue|
|---|
| Closes #20352 |

## Description

Adds the `profile` prefix to the configuration profile specified through the command line.

### Logs

<details><summary>Credentials</summary>

```console
root@wazuh-master:/# cat /root/.aws/credentials
[dev]
aws_access_key_id=foo
aws_secret_access_key=bar
region=us-east-1
```

</details>

<details><summary>Configuration</summary>

With profile prefix

```console
root@wazuh-master:/# cat /root/.aws/config
[profile dev]
region=us-east-1
max_attempts=5
retry_mode=standard
dev.s3.max_concurrent_requests = 10
dev.s3.max_queue_size = 1000
dev.proxy.host = localhost
dev.proxy.port = 8080
signature_version = s3v4
```

Without profile prefix

```console
root@wazuh-master:/# cat /root/.aws/config
[dev]
region=us-east-1
max_attempts=5
retry_mode=standard
dev.s3.max_concurrent_requests = 10
dev.s3.max_queue_size = 1000
dev.proxy.host = localhost
dev.proxy.port = 8080
signature_version = s3v4
```

</details>

<details><summary>Execution before changes</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/wodles/aws/aws-s3.py --aws_profile dev -b wazuh-xxx-cloudtrail -t cloudtrail -d2
DEBUG: +++ Debug mode on - Level: 2
No profile named: 'dev' was found in the user config file
```

</details>

<details><summary>Execution after the changes</summary>

<details><summary>Profile [dev]</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/wodles/aws/aws_s3.py --aws_profile dev -b wazuh-xxx-cloudtrail -t cloudtrail -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Retries parameters found in user profile. Using profile 'dev' retries configuration
DEBUG: Created Config object using profile: 'dev' configuration
DEBUG: +++ Table does not exist; create
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
```

</details>

<details><summary>Profile [profile dev]</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/wodles/aws/aws_s3.py --aws_profile dev -b wazuh-xxx-cloudtrail -t cloudtrail -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Retries parameters found in user profile. Using profile 'profile dev' retries configuration
DEBUG: Created Config object using profile: 'profile dev' configuration
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
```

</details>

<details><summary>Profile [default] implicit</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/wodles/aws/aws_s3.py -b wazuh-xxx-cloudtrail -t cloudtrail -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Retries parameters found in user profile. Using profile 'default' retries configuration
DEBUG: Created Config object using profile: 'default' configuration
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
```

</details>

<details><summary>Profile [default] explicit</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/wodles/aws/aws_s3.py --aws_profile default -b wazuh-xxx-cloudtrail -t cloudtrail -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Retries parameters found in user profile. Using profile 'default' retries configuration
DEBUG: Created Config object using profile: 'default' configuration
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
```

</details>

<details><summary>Profile [profile default]</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/wodles/aws/aws_s3.py --aws_profile default -b wazuh-xxx-cloudtrail -t cloudtrail -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Retries parameters found in user profile. Using profile 'profile default' retries configuration
DEBUG: Created Config object using profile: 'profile default' configuration
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on xxx - us-west-1
DEBUG: +++ Marker: AWSLogs/xxx/CloudTrail/us-west-1/2023/11/30
DEBUG: +++ No logs to process in bucket: xxx/us-west-1
DEBUG: +++ DB Maintenance
```

</details>

```console
# S3 config
DEBUG: {'max_concurrent_requests': 10, 'max_queue_size': 1000, 'multipart_threshold': '8MB', 'multipart_chunksize': '8MB', 'max_bandwidth': None, 'use_accelerate_endpoint': False, 'addressing_style': 'auto'}

# Proxies config
DEBUG: {'host': 'localhost', 'port': 8080, 'username': None, 'password': None}
```

</details>

2023-11-29 18:56 UTC, EduLeon12 approved these changes
Taking into consideration this is a patch, I think the solution is correct and fulfills the scope of the issue. For that is approved.

However, after discussing with @GGP1 we concluded that a new issue should be created to address a change that can be done in the same conflictual method `set_profile_dict_config`. The reason to look for the profile name and compare it to the config file is not needed anymore. Therefore, it can be removed to allow a more concise AWS config file. 

The proposed issue is a breaking change and should be for a minor release. @Selutario

2023-11-29 19:23 UTC, EduLeon12 requested changes
Wodle fails when declaring the aws_profile as default.

```command
2023/11/29 19:21:42 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  No profile named: 'profile default' was found in the user config file

```
Change the wodle to check for this after removing the prefix.

2023-11-30 16:15 UTC, EduLeon12 approved these changes
Testing the changes the module worked as expected.

LGTM !!

<details> <summary> Test output </summary> 

```command
root@wazuh-master:/var/ossec# cat ~/.aws/config
[default]
region = us-east-1
output = json

[test_aws_profile]
region = us-east-1
output = json

[qa]
region = us-east-1
output = json

[profile test_profile]
region = us-east-1
output = json
test_profile.s3.max_concurrent_requests = 10
test_profile.s3.max_queue_size = 1000
test_profile.s3.multipart_threshold = 64MB
test_profile.s3.multipart_chunksize = 16MB
test_profile.s3.max_bandwidth = 50MB/s
test_profile.s3.use_accelerate_endpoint = false
test_profile.s3.addressing_style = virtual

test_profile.proxy.host = proxy.example.com
test_profile.proxy.port = 8080
test_profile.proxy.username = your-proxy-username
test_profile.proxy.password = your-proxy-password

test_profile.proxy.ca_bundle = /path/to/ca_bundle.pem
test_profile.proxy.client_cert = /path/to/client_cert.pem
test_profile.proxy.use_forwarding_for_https = true
signature_version = s3v4
max_attempts = 5
retry_mode = standard

[dev]
region = us-east-1
output = json

root@wazuh-master:/var/ossec# wodles/aws/aws-s3 --bucket wazuh-aws-wodle-cloudtrail --aws_profile test_profile --only_logs_after 2022-JAN-01 --type cloudtrail --debug 2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Retries parameters found in user profile. Using profile 'profile test_profile' retries configuration
DEBUG: Created Config object using profile: 'profile test_profile' configuration
DEBUG: +++ Working on ########## - us-west-1
DEBUG: +++ Marker: AWSLogs/##########/CloudTrail/us-west-1/2023/09/06/##########_CloudTrail_us-west-1_20230906T1755Z_2CqtXDyI0zFiYm1J.json
DEBUG: +++ No logs to process in bucket: ##########/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on ########## - us-west-1
DEBUG: +++ Marker: AWSLogs/##########/CloudTrail/us-west-1/2022/01/01
DEBUG: +++ No logs to process in bucket: ##########/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on ########## - us-west-1
DEBUG: +++ Marker: AWSLogs/##########/CloudTrail/us-west-1/2023/01/25/##########_CloudTrail_us-west-1_20211223T0000Z_HASDOtJxxxxxxxxx.json.gz
DEBUG: +++ No logs to process in bucket: ##########/us-west-1
DEBUG: +++ DB Maintenance
root@wazuh-master:/var/ossec# wodles/aws/aws-s3 --bucket wazuh-aws-wodle-cloudtrail --aws_profile dev --only_logs_after 2022-JAN-01 --type cloudtrail --debug 2           
DEBUG: +++ Debug mode on - Level: 2
No profile named: 'profile dev' was found in the user config file
root@wazuh-master:/var/ossec# wodles/aws/aws-s3 --bucket wazuh-aws-wodle-cloudtrail --aws_profile default --only_logs_after 2022-JAN-01 --type cloudtrail --debug 2       
DEBUG: +++ Debug mode on - Level: 2
DEBUG: No retries configuration found in profile config. Generating default configuration for retries: mode: standard - max_attempts: 10
DEBUG: Created Config object using profile: 'default' configuration
DEBUG: +++ Working on ########## - us-west-1
DEBUG: +++ Marker: AWSLogs/##########/CloudTrail/us-west-1/2023/09/06/##########_CloudTrail_us-west-1_20230906T1755Z_2CqtXDyI0zFiYm1J.json
DEBUG: +++ No logs to process in bucket: 166157441623/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on ########## - us-west-1
DEBUG: +++ Marker: AWSLogs/##########/CloudTrail/us-west-1/2022/01/01
DEBUG: +++ No logs to process in bucket: ##########/us-west-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on ########## - us-west-1
DEBUG: +++ Marker: AWSLogs/##########/CloudTrail/us-west-1/2023/01/25/##########_CloudTrail_us-west-1_20211223T0000Z_HASDOtJxxxxxxxxx.json.gz
DEBUG: +++ No logs to process in bucket: ##########/us-west-1
DEBUG: +++ DB Maintenance

```

</details>

2023-11-30 20:39 UTC, EduLeon12 approved these changes
LGTM!

2023-12-04 15:39 UTC, Selutario requested changes
Looks great @GGP1. I would merge this in 4.7.2 though.

2023-12-05 09:02 UTC, merged