Add additional check on XML parsing
wazuh/wazuh pull request #20448
Opened 2023-11-27 20:35 UTC by LucioDonda

|Related issue|
|---|
|#16386|

## Description

After merging this [PR](https://github.com/wazuh/wazuh/pull/16681) there where found that some of the windows events where not correctly handled. That turn into a revert of some changes in that merge. 
This PR tries to solve some of those issues without affecting any other process that make use of the XML parser. 

The easiest and cleaner approach we found was simply checking if the XML starts with '<' (passing all spaces and line jumps before it)

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
- [ ] Source installation
- [ ] Package installation
- [ ] Review logs syntax and correct language

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

2023-11-30 21:10 UTC, nbertoldo approved these changes
LGTM!

2023-12-11 15:42 UTC, LucioDonda commented
**Additional test:**

Fixed version running on ubuntu 20 as manager and windows 10 as agent.
On both cases the installation and the start of the service disn't generate any warning or error. That didn't happened on the enrollment process either.

Example of alert after login:

```
** Alert 1702306968.257562: - windows,windows_security,authentication_failed,gdpr_IV_32.2,gdpr_IV_35.7.d,gpg13_7.1,hipaa_164.312.b,nist_800_53_AC.7,nist_800_53_AU.14,pci_dss_10.2.4,pci_dss_10.2.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Dec 11 15:02:48 (vm-win10) any->EventChannel
Rule: 60122 (level 5) -> 'Logon failure - Unknown user or bad password.'
{"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-a5ba-3e3b0328c30d}","eventID":"4625","version":"0","level":"0","task":"12544","opcode":"0","keywords":"0x8010000000000000","systemTime":"2023-12-11T15:02:47.9920973Z","eventRecordID":"17301","processID":"708","threadID":"7876","channel":"Security","computer":"vm-win10","severityValue":"AUDIT_FAILURE","message":"\"An account failed to log on.\r\n\r\nSubject:\r\n\tSecurity ID:\t\tS-1-5-18\r\n\tAccount Name:\t\tVM-WIN10$\r\n\tAccount Domain:\t\tWORKGROUP\r\n\tLogon ID:\t\t0x3E7\r\n\r\nLogon Type:\t\t\t2\r\n\r\nAccount For Which Logon Failed:\r\n\tSecurity ID:\t\tS-1-0-0\r\n\tAccount Name:\t\tvagrant\r\n\tAccount Domain:\t\tVM-WIN10\r\n\r\nFailure Information:\r\n\tFailure Reason:\t\tUnknown user name or bad password.\r\n\tStatus:\t\t\t0xC000006D\r\n\tSub Status:\t\t0xC000006A\r\n\r\nProcess Information:\r\n\tCaller Process ID:\t0x2dc\r\n\tCaller Process Name:\tC:\\Windows\\System32\\svchost.exe\r\n\r\nNetwork Information:\r\n\tWorkstation Name:\tVM-WIN10\r\n\tSource Network Address:\t127.0.0.1\r\n\tSource Port:\t\t0\r\n\r\nDetailed Authentication Information:\r\n\tLogon Process:\t\tUser32 \r\n\tAuthentication Package:\tNegotiate\r\n\tTransited Services:\t-\r\n\tPackage Name (NTLM only):\t-\r\n\tKey Length:\t\t0\r\n\r\nThis event is generated when a logon request fails. It is generated on the computer where access was attempted.\r\n\r\nThe Subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.\r\n\r\nThe Logon Type field indicates the kind of logon that was requested. The most common types are 2 (interactive) and 3 (network).\r\n\r\nThe Process Information fields indicate which account and process on the system requested the logon.\r\n\r\nThe Network Information fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.\r\n\r\nThe authentication information fields provide detailed information about this specific logon request.\r\n\t- Transited services indicate which intermediate services have participated in this logon request.\r\n\t- Package name indicates which sub-protocol was used among the NTLM protocols.\r\n\t- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.\""},"eventdata":{"subjectUserSid":"S-1-5-18","subjectUserName":"VM-WIN10$","subjectDomainName":"WORKGROUP","subjectLogonId":"0x3e7","targetUserSid":"S-1-0-0","targetUserName":"vagrant","targetDomainName":"VM-WIN10","status":"0xc000006d","failureReason":"%%2313","subStatus":"0xc000006a","logonType":"2","logonProcessName":"User32","authenticationPackageName":"Negotiate","workstationName":"VM-WIN10","keyLength":"0","processId":"0x2dc","processName":"C:\\Windows\\System32\\svchost.exe","ipAddress":"127.0.0.1","ipPort":"0"}}}
win.system.providerName: Microsoft-Windows-Security-Auditing
win.system.providerGuid: {54849625-5478-4994-a5ba-3e3b0328c30d}
win.system.eventID: 4625
win.system.version: 0
win.system.level: 0
win.system.task: 12544
win.system.opcode: 0
win.system.keywords: 0x8010000000000000
win.system.systemTime: 2023-12-11T15:02:47.9920973Z
win.system.eventRecordID: 17301
win.system.processID: 708
win.system.threadID: 7876
win.system.channel: Security
win.system.computer: vm-win10
win.system.severityValue: AUDIT_FAILURE
win.system.message: "An account failed to log on.

Subject:
	Security ID:		S-1-5-18
	Account Name:		VM-WIN10$
	Account Domain:		WORKGROUP
	Logon ID:		0x3E7

Logon Type:			2

Account For Which Logon Failed:
	Security ID:		S-1-0-0
	Account Name:		vagrant
	Account Domain:		VM-WIN10

Failure Information:
	Failure Reason:		Unknown user name or bad password.
	Status:			0xC000006D
	Sub Status:		0xC000006A

Process Information:
	Caller Process ID:	0x2dc
	Caller Process Name:	C:\Windows\System32\svchost.exe

Network Information:
	Workstation Name:	VM-WIN10
	Source Network Address:	127.0.0.1
	Source Port:		0

Detailed Authentication Information:
	Logon Process:		User32 
	Authentication Package:	Negotiate
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0

This event is generated when a logon request fails. It is generated on the computer where access was attempted.

The Subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.

The Logon Type field indicates the kind of logon that was requested. The most common types are 2 (interactive) and 3 (network).

The Process Information fields indicate which account and process on the system requested the logon.

The Network Information fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.

The authentication information fields provide detailed information about this specific logon request.
	- Transited services indicate which intermediate services have participated in this logon request.
	- Package name indicates which sub-protocol was used among the NTLM protocols.
	- Key length indicates the length of the generated session key. This will be 0 if no session key was requested."
win.eventdata.subjectUserSid: S-1-5-18
win.eventdata.subjectUserName: VM-WIN10$
win.eventdata.subjectDomainName: WORKGROUP
win.eventdata.subjectLogonId: 0x3e7
win.eventdata.targetUserSid: S-1-0-0
win.eventdata.targetUserName: vagrant
win.eventdata.targetDomainName: VM-WIN10
win.eventdata.status: 0xc000006d
win.eventdata.failureReason: %%2313
win.eventdata.subStatus: 0xc000006a
win.eventdata.logonType: 2
win.eventdata.logonProcessName: User32
win.eventdata.authenticationPackageName: Negotiate
win.eventdata.workstationName: VM-WIN10
win.eventdata.keyLength: 0
win.eventdata.processId: 0x2dc
win.eventdata.processName: C:\Windows\System32\svchost.exe
win.eventdata.ipAddress: 127.0.0.1
win.eventdata.ipPort: 0
```

This proves that these alerts are being triggered by processing the XML events without any problem and that both `ossec.conf` are being read and used for a simple execution without problems.

2024-01-05 18:49 UTC, cborla approved these changes
LGTM!

2024-01-08 13:41 UTC, nmkoremblum requested changes

2024-01-08 13:41 UTC, nmkoremblum commented on src/os_xml/os_xml.c
> +    if(c == cmp) {
```suggestion
    if (c == cmp) {
```

2024-01-08 13:41 UTC, nmkoremblum commented on src/os_xml/os_xml.c
> +    else if(c != _R_CONFS) {
```suggestion
    else if (c != _R_CONFS) {
```

2024-01-08 13:41 UTC, nmkoremblum commented on src/os_xml/os_xml.c
> +        if(isspace(c)) {
```suggestion
        if (isspace(c)) {
```

2024-01-08 15:12 UTC, nmkoremblum submitted a review, later dismissed
LGTM

2024-04-23 20:01 UTC, cborla commented on src/os_xml/os_xml.c
> +
What if we include to validate the end of the file/string, containing the character '>'. 
Without trailing spaces and returning file position at the beginning of the file when validated by Ok. 

``` c
// Get the current position before checking '>'
long pos = ftell(_lxml->fp);

// validate that the file ends with '>'
fseek(_lxml->fp, -1, SEEK_END);
if (fgetc(_lxml->fp) != '>') {
    xml_error(_lxml, "XMLERR: Malformed XML does not end with '>'");
    fseek(_lxml->fp, pos, SEEK_SET); // Return to the position of '<'
    goto end;
}

// Set the current character back to '<'
fseek(_lxml->fp, pos, SEEK_SET);
c = _R_CONFS;
```

2024-04-25 13:55 UTC, vikman90 requested changes

2024-04-25 13:55 UTC, vikman90 commented on src/unit_tests/os_xml/test_os_xml.c
> +    create_xml_file("  <element-name>test</element-name>", data->xml_file_name, 256);
That's great! Please just add another test that checks leading newlines.

2024-04-26 18:27 UTC, cborla commented on src/os_xml/os_xml.c
> +
The xml parser already validate it.

2024-04-29 07:04 UTC, vikman90 commented
## Failing checks

### Scan build / scan-build-macos-agent

- https://github.com/wazuh/wazuh/issues/23176

### Testing DLL search order to prevent hijack / check_dll_on_windows

Ignoring it, it's a flaky-test.

2024-04-29 09:42 UTC, vikman90 approved these changes

2024-04-29 19:13 UTC, LucioDonda commented
# Testing

## Manager 

### Info

```console
root@kinetic:/var/ossec/bin# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"
PRETTY_NAME="Ubuntu 22.10"
NAME="Ubuntu"
VERSION_ID="22.10"
VERSION="22.10 (Kinetic Kudu)"
VERSION_CODENAME=kinetic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=kinetic
LOGO=ubuntu-logo
root@kinetic:/var/ossec/bin# ./wazuh-control info
WAZUH_VERSION="v4.9.0"
WAZUH_REVISION="40900"
WAZUH_TYPE="server"

```

### wazuh status
```
root@kinetic:/var/ossec/bin# systemctl status wazuh-manager.service 
● wazuh-manager.service - Wazuh manager
     Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; preset: enabled)
     Active: active (running) since Mon 2024-04-29 11:46:57 -03; 4h 14min ago
      Tasks: 201 (limit: 11783)
     Memory: 748.3M
        CPU: 1min 15.444s
     CGroup: /system.slice/wazuh-manager.service
             ├─14769 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─14808 /var/ossec/bin/wazuh-authd
             ├─14821 /var/ossec/bin/wazuh-db
             ├─14843 /var/ossec/bin/wazuh-execd
             ├─14854 /var/ossec/bin/wazuh-analysisd
             ├─14863 /var/ossec/bin/wazuh-syscheckd
             ├─14876 /var/ossec/bin/wazuh-remoted
             ├─14996 /var/ossec/bin/wazuh-logcollector
             ├─15012 /var/ossec/bin/wazuh-monitord
             ├─15015 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─15018 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─15021 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             └─15033 /var/ossec/bin/wazuh-modulesd

Apr 29 11:46:52 kinetic env[14713]: Started wazuh-analysisd...
Apr 29 11:46:52 kinetic env[14713]: Started wazuh-syscheckd...
Apr 29 11:46:53 kinetic env[14713]: Started wazuh-remoted...
Apr 29 11:46:53 kinetic env[14713]: Started wazuh-logcollector...
root@kinetic:/var/ossec/bin# ./wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...

```


### enrollment status

```console
root@kinetic:/var/ossec/bin# ./manage_agents -l

Available agents: 
   ID: 001, Name: jammy, IP: any

````

## Linux Agent

###  Info

```console
root@jammy:/home/vagrant#  cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
root@jammy:/var/ossec/bin# ./wazuh-control info
WAZUH_VERSION="v4.9.0"
WAZUH_REVISION="40900"
WAZUH_TYPE="agent"
````

###  status

```console
root@jammy:/var/ossec/bin# systemctl status wazuh-agent.service 
● wazuh-agent.service - Wazuh agent
     Loaded: loaded (/lib/systemd/system/wazuh-agent.service; disabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-04-29 17:50:30 UTC; 1h 22min ago
    Process: 59800 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
      Tasks: 38 (limit: 11792)
     Memory: 605.6M
        CPU: 22.772s
     CGroup: /system.slice/wazuh-agent.service
             ├─60463 /var/ossec/bin/wazuh-execd
             ├─60474 /var/ossec/bin/wazuh-agentd
             ├─60488 /var/ossec/bin/wazuh-syscheckd
             ├─60501 /var/ossec/bin/wazuh-logcollector
             └─60515 /var/ossec/bin/wazuh-modulesd

Apr 29 17:50:20 jammy systemd[1]: Starting Wazuh agent...
Apr 29 17:50:20 jammy env[59800]: Starting Wazuh v4.9.0...
Apr 29 17:50:20 jammy env[59800]: Started wazuh-execd...
Apr 29 17:50:23 jammy env[59800]: Started wazuh-agentd...
Apr 29 17:50:24 jammy env[59800]: Started wazuh-syscheckd...
Apr 29 17:50:27 jammy env[59800]: Started wazuh-logcollector...
Apr 29 17:50:28 jammy env[59800]: Started wazuh-modulesd...
Apr 29 17:50:30 jammy env[59800]: Completed.
Apr 29 17:50:30 jammy systemd[1]: Started Wazuh agent.
root@jammy:/var/ossec/bin# ./wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
root@jammy:/var/ossec/bin# cat /var/ossec/logs/ossec.log | grep "Valid key received" -C 5
2024/04/29 17:50:20 wazuh-agentd: INFO: Started (pid: 59830).
2024/04/29 17:50:20 wazuh-agentd: INFO: Requesting a key from server: 192.168.56.129
2024/04/29 17:50:20 wazuh-agentd: INFO: No authentication password provided
2024/04/29 17:50:20 wazuh-agentd: INFO: Using agent name as: jammy
2024/04/29 17:50:20 wazuh-agentd: INFO: Waiting for server reply
2024/04/29 17:50:20 wazuh-agentd: INFO: Valid key received
2024/04/29 17:50:20 wazuh-agentd: INFO: Waiting 20 seconds before server connection
2024/04/29 17:50:23 wazuh-syscheckd: INFO: Started (pid: 59843).
2024/04/29 17:50:23 wazuh-syscheckd: INFO: (6003): Monitoring path: '/bin', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2024/04/29 17:50:23 wazuh-syscheckd: INFO: (6003): Monitoring path: '/boot', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2024/04/29 17:50:23 wazuh-syscheckd: INFO: (6003): Monitoring path: '/etc', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.

````


###  Alerts on the manager

```console
root@kinetic:/var/ossec/bin# cat /var/ossec/logs/alerts/alerts.log | grep "(jammy)" | wc -l
195
````

Examples:

```console
** Alert 1714413085.54804: - ossec,pci_dss_10.6.1,gpg13_10.1,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,tsc_CC7.2,tsc_CC7.3,
2024 Apr 29 14:51:25 (jammy) any->wazuh-agent
Rule: 501 (level 3) -> 'New wazuh agent connected.'
ossec: Agent started: 'jammy->any'.

** Alert 1714413085.55069: - ossec,rootcheck,pci_dss_10.6.1,gdpr_IV_35.7.d,
2024 Apr 29 14:51:25 (jammy) any->rootcheck
Rule: 510 (level 7) -> 'Host-based anomaly detection event (rootcheck).'
Trojaned version of file '/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).
title: Trojaned version of file detected.
file: /bin/diff

** Alert 1714413085.55448: - ossec,rootcheck,pci_dss_10.6.1,gdpr_IV_35.7.d,
2024 Apr 29 14:51:25 (jammy) any->rootcheck
Rule: 510 (level 7) -> 'Host-based anomaly detection event (rootcheck).'
Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).
title: Trojaned version of file detected.
file: /usr/bin/diff

** Alert 1714413087.55835: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2024 Apr 29 14:51:27 (jammy) any->sca
Rule: 19007 (level 7) -> 'CIS Ubuntu Linux 22.04 LTS Benchmark v1.0.0.: Ensure /tmp is a separate partition.'
{"type":"check","id":1782925229,"policy":"CIS Ubuntu Linux 22.04 LTS Benchmark v1.0.0.","policy_id":"cis_ubuntu22-04","check":{"id":28500,"title":"Ensure /tmp is a separate partition.","description":"The /tmp directory is a world-writable directory  [...]

2024-04-30 08:01 UTC, merged