Adds validation to decoders and rules using logtest.
wazuh/wazuh pull request #20507
Opened 2023-11-28 19:40 UTC by RamosFe

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/17862|

## Description

Adds validation to PUT` /decoders/files/{filename} `and PUT `/rules/files/{filename}` for XML files using the logtest.

2023-12-01 14:08 UTC, GGP1 requested changes
Please upload the execution logs of the modified AITs once the changes are made, since they weren't ran in the checks.

2023-12-04 19:40 UTC, RamosFe commented on framework/wazuh/decoder.py
> +        validate_dummy_logtest()
Added cleanup for the cases when the rule/decoder has an invalid syntax:

https://github.com/wazuh/wazuh/blob/910d9ff8ce776638c0c899b643db1ee57b4c2bc5/framework/wazuh/rule.py#L494-L500

The `temp` idea was very good, but due to `delete_rule_file` and `delete_decoder_file` using `common.WAZUH_PATH` for searching the decoder/ruler I opted not to change the logic of the controller and add the respective cleanup if an exception is raised validating the XML.

2023-12-05 13:30 UTC, GGP1 requested changes
Uploading a new file works as expected, it fails and does not create it. However, updating an existing file does not return an error and changes its content.

### Uploading a new file

<details><summary>Request</summary>

`PUT /decoders/files/test_decoder.xml`

Body:

```xml
<!-- comment -->
```

</details>


<details><summary>Response</summary>

```json
{
    "data": {
        "affected_items": [],
        "total_affected_items": 0,
        "total_failed_items": 1,
        "failed_items": [
            {
                "error": {
                    "code": 1113,
                    "message": "XML syntax error",
                    "remediation": "Please, ensure file content has correct XML"
                },
                "id": [
                    "etc/decoders/test_decoder.xml"
                ]
            }
        ]
    },
    "message": "Could not upload decoder",
    "error": 1
}
```

</details>

<details><summary>Looking for the file in the manager</summary>

```console
root@wazuh-master:/# cat /var/ossec/etc/decoders/test_decoder.xml 
cat: /var/ossec/etc/decoders/test_decoder.xml: No such file or directory
```

</details>

### Updating an existing file

<details><summary>Request</summary>

`PUT /decoders/files/local_decoder.xml?overwrite=true`

Body:

```xml
<!-- comment -->
```

</details>


<details><summary>Response</summary>

```json
{
    "data": {
        "affected_items": [
            "etc/decoders/local_decoder.xml"
        ],
        "total_affected_items": 1,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "Decoder was successfully uploaded",
    "error": 0
}
```

</details>

<details><summary>File is updated</summary>

```console
root@wazuh-master:/# cat /var/ossec/etc/decoders/local_decoder.xml
<!-- comment -->
```

</details>

### Updating an existing file with a different body

<details><summary>Request</summary>

`PUT /decoders/files/local_decoder.xml?overwrite=true`

Body:

```xml
<?xml version="1.0" ?>
<metadata>
</metadata>
```

</details>


<details><summary>Response</summary>

It fails earlier, when executing `validate_wazuh_xml(content)`.

```json
{
    "data": {
        "affected_items": [],
        "total_affected_items": 0,
        "total_failed_items": 1,
        "failed_items": [
            {
                "error": {
                    "code": 1113,
                    "message": "XML syntax error",
                    "remediation": "Please, ensure file content has correct XML"
                },
                "id": [
                    "etc/decoders/local_decoder.xml"
                ]
            }
        ]
    },
    "message": "Could not upload decoder",
    "error": 1
}
```

</details>

<details><summary>File is not updated</summary>

```console
root@wazuh-master:/# cat /var/ossec/etc/decoders/local_decoder.xml
<!-- comment -->
```

</details>

2023-12-18 22:03 UTC, RamosFe commented
## Update

### Uploading a new file

<details><summary>Request</summary>

`PUT decoders/files/oops.xml?pretty=false&wait_for_complete=false&overwrite=false`

Body:

```xml
<!-- comment -->
```

</details>


<details><summary>Response</summary>

```json
{
    "data": {
        "affected_items": [],
        "total_affected_items": 0,
        "total_failed_items": 1,
        "failed_items": [
            {
                "error": {
                    "code": 1113,
                    "message": "XML syntax error",
                    "remediation": "Please, ensure file content has correct XML"
                },
                "id": [
                    "etc/decoders/oops.xml"
                ]
            }
        ]
    },
    "message": "Could not upload decoder",
    "error": 1
}
```

</details>

<details><summary>Looking for the file in the manager</summary>

```console
root@wazuh-master:/# cat /var/ossec/etc/decoders/test_decoder.xml 
cat: /var/ossec/etc/decoders/oops.xml: No such file or directory
```

</details>

### Updating a valid file

<details><summary>Request</summary>

`PUT decoders/files/valid.xml?pretty=false&wait_for_complete=false&overwrite=false`

Body:

```xml
<!-- Local Decoders -->

<!-- Modify it at your will. -->
<!-- Copyright (C) 2015, Wazuh Inc. -->

<!--
  - Allowed static fields:
  - location   - where the log came from (only on FTS)
  - srcuser    - extracts the source username
  - dstuser    - extracts the destination (target) username
  - user       - an alias to dstuser (only one of the two can be used)
  - srcip      - source ip
  - dstip      - dst ip
  - srcport    - source port
  - dstport    - destination port
  - protocol   - protocol
  - id         - event id
  - url        - url of the event
  - action     - event action (deny, drop, accept, etc)
  - status     - event status (success, failure, etc)
  - extra_data - Any extra data
-->

<decoder name="local_decoder_example">
    <program_name>local_decoder_example</program_name>
</decoder>
```

</details>


<details><summary>Response</summary>

```json
{
    "data": {
        "affected_items": [
            "etc/decoders/valid.xml"
        ],
        "total_affected_items": 1,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "Decoder was successfully uploaded",
    "error": 0
}
```

</details>

<details><summary>File is not updated</summary>

```console
root@wazuh-master:/var/ossec/framework/python/lib/python3.10/site-packages/wazuh# ls /var/ossec/etc/decoders/
local_decoder.xml  valid.xml
root@wazuh-master:/var/ossec/framework/python/lib/python3.10/site-packages/wazuh# cat /var/ossec/etc/decoders/valid.xml 
<!-- Local Decoders -->

<!-- Modify it at your will. -->
<!-- Copyright (C) 2015, Wazuh Inc. -->

<!--
  - Allowed static fields:
  - location   - where the log came from (only on FTS)
  - srcuser    - extracts the source username
  - dstuser    - extracts the destination (target) username
  - user       - an alias to dstuser (only one of the two can be used)
  - srcip      - source ip
  - dstip      - dst ip
  - srcport    - source port
  - dstport    - destination port
  - protocol   - protocol
  - id         - event id
  - url        - url of the event
  - action     - event action (deny, drop, accept, etc)
  - status     - event status (success, failure, etc)
  - extra_data - Any extra data
-->

<decoder name="local_decoder_example">
    <program_name>local_decoder_example</program_name>
</decoder>

```
</details>

### Updating an existing file

<details><summary>Request</summary>

`PUT decoders/files/valid.xml?pretty=false&wait_for_complete=false&overwrite=true`

Body:

```xml
<!-- comment -->
```

</details>


<details><summary>Response</summary>

```json
{
    "data": {
        "affected_items": [],
        "total_affected_items": 0,
        "total_failed_items": 1,
        "failed_items": [
            {
                "error": {
                    "code": 1113,
                    "message": "XML syntax error",
                    "remediation": "Please, ensure file content has correct XML"
                },
                "id": [
                    "etc/decoders/valid.xml"
                ]
            }
        ]
    },
    "message": "Could not upload decoder",
    "error": 1
}
```

</details>

<details><summary>File is not updated</summary>

```console
root@wazuh-master:/var/ossec/framework/python/lib/python3.10/site-packages/wazuh# ls /var/ossec/etc/decoders/
local_decoder.xml  valid.xml
root@wazuh-master:/var/ossec/framework/python/lib/python3.10/site-packages/wazuh# cat /var/ossec/etc/decoders/valid.xml 
<!-- Local Decoders -->

<!-- Modify it at your will. -->
<!-- Copyright (C) 2015, Wazuh Inc. -->

<!--
  - Allowed static fields:
  - location   - where the log came from (only on FTS)
  - srcuser    - extracts the source username
  - dstuser    - extracts the destination (target) username
  - user       - an alias to dstuser (only one of the two can be used)
  - srcip      - source ip
  - dstip      - dst ip
  - srcport    - source port
  - dstport    - destination port
  - protocol   - protocol
  - id         - event id
  - url        - url of the event
  - action     - event action (deny, drop, accept, etc)
  - status     - event status (success, failure, etc)
  - extra_data - Any extra data
-->

<decoder name="local_decoder_example">
    <program_name>local_decoder_example</program_name>
</decoder>

```

2023-12-20 12:03 UTC, GGP1 approved these changes
LGTM

> Failed checks are not related to the changes introduced.

2024-01-16 13:36 UTC, Selutario requested changes
GJ @RamosFe (and good in-depth functionality review @GGP1). I just requested some minor changes related to the docstring format:

2024-01-24 18:39 UTC, RamosFe commented
Changed base to `4.8.1`.

2024-01-26 19:10 UTC, RamosFe commented
The error in the test of `GET /cluster/configuration/validation` in the API Integration test is related to the changes made in the `PUT /rules/files/{filename}` endpoint.

The test  uploads a corrupted rule file:

```yml
  #### Upload corrupted rules file
  - name: Upload corrupted configuration
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/rules/files/new-rules_corrupted.xml"
      method: PUT
      data: "{corrupted_rules_file}"
      headers:
        Authorization: "Bearer {test_login_token}"
        content-type: application/octet-stream
    response:
      status_code: 200
    delay_after: !float "{cluster_sync_delay}"
 ```
 
 And then expects 3 failed items when validating the cluster configuration using `GET /cluster/configuration/validation`:
 
 ```yml
   - name: Request validation
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/cluster/configuration/validation"
      method: GET
      headers:
        Authorization: "Bearer {test_login_token}"
    response:
      status_code: 200
      json:
        error: 1
        data:
          failed_items:
            - error:
                code: 1908
              id:
                - 'master-node'
                - 'worker1'
                - 'worker2'
          total_affected_items: 0
          total_failed_items: 3
 ```
 
 The problem is that the corrupted rule is never updated, and that causes no error when calling `GET /cluster/configuration/validation`.

2024-01-29 17:20 UTC, Selutario approved these changes
LGTM

2024-01-29 17:20 UTC, merged