Fix Agent crash using the Forwarded Events from eventchannel configuration
wazuh/wazuh pull request #20511
Opened 2023-11-28 21:20 UTC by nbertoldo

|Related issue|
|---|
|Closes #20509|

## Description

There is a problem related to the event channel log format, where the agent collects and forwards events from other Windows machines, this event channel is called `Forwarded Events` and in Wazuh agent configuration it works with `ForwardedEvents`.
The same configuration in the same agent version on Windows 2022 OS fails, the agent service crashes a few seconds after starting, but, if the `ForwardedEvents` section is removed/commented, the agent starts without problems. 
The only difference is the Windows version.

Agent configurations 003 (working) and 008 (not working).
[ossec.conf.agents.zip](https://github.com/wazuh/external-devel-requests/files/12836331/ossec.conf.agents.zip)

```xml
<ossec_config>
  <localfile>
    <location>ForwardedEvents</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157]</query>
  </localfile>
</ossec_config>
```

Windows versions for each:
```
OS Version Windows Agent003
Microsoft Windows Server 2012 R2 Standard 6.3.9600
PS C:\Users\robert.lee> (Get-WmiObject -Class Win32_OperatingSystem).Version
6.3.9600

OS Version Windows Agent008
Microsoft Windows Server 2022 Datacenter 10.0.20348
PS C:\Users\robert.lee> (Get-WmiObject -Class Win32_OperatingSystem).Version
10.0.20348
```

Wazuh agents and manager version: 4.3.10

2023-11-29 13:11 UTC, nmkoremblum requested changes

2023-11-29 13:11 UTC, nmkoremblum commented on src/syscheckd/src/whodata/win_whodata.c
> +    err_msg[OS_SIZE_1024 - 1] = '\0';
I would recommend changing this in favor of:
```suggestion
    char err_msg[OS_SIZE_1024];
    memset(err_msg, 0, OS_SIZE_1024); // Set all elements to zero
```
I suggest changing it as well in other occurrences.

2023-11-29 13:11 UTC, nmkoremblum commented on src/logcollector/read_win_event_channel.c
> +    if ((buffer = calloc(++size, sizeof(wchar_t))) == NULL) {
To improve code readability I suggest changing this line as follows:
 ```suggestion
    // Buffer size is increased by one unit as `EvtFormatMessage` does not count the '\0'
    size += 1;
    if ((buffer = calloc(size, sizeof(wchar_t))) == NULL) {
```

2023-11-29 15:58 UTC, LucioDonda requested changes
minor changes regarding UTs

2023-11-29 15:58 UTC, LucioDonda commented on src/unit_tests/logcollector/test_read_win_event_channel.c
> +    char message[] = "Test_Message";
Some variables and values of each test are repeated, can this be unified into a common setup stage?

2023-11-29 21:09 UTC, LucioDonda submitted a review, later dismissed
LGTM!

2023-11-30 19:41 UTC, nmkoremblum submitted a review, later dismissed
LGTM

2023-11-30 21:24 UTC, cborla submitted a review, later dismissed
LGTM!

2023-12-01 19:05 UTC, closed without merging