Add configuration upload test
wazuh/wazuh pull request #20619
Opened 2023-12-04 15:58 UTC by GGP1

|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/20610 |

## Description

Adds a test that validates the successful upload of configuration files through the API.

2023-12-04 19:33 UTC, fdalmaup requested changes

2023-12-04 19:33 UTC, fdalmaup commented on tests/integration/test_api/test_config/test_upload_configuration/test_upload_configuration.py
> +    wazuh_min_version: 4.2.0
The limit configuration related to the EPS was added in #13608. The Wazuh minimum version should be changed since the base conf includes it.

2023-12-04 19:33 UTC, fdalmaup commented on tests/integration/test_api/test_config/test_upload_configuration/test_upload_configuration.py
> +brief: This tests checks that the configuration is set correctly in the manager via the API.
```suggestion
type: integration

brief: These tests check that the configuration is set correctly in the manager via the API.
```

2023-12-05 19:27 UTC, fdalmaup approved these changes
LGTM!

2023-12-11 12:56 UTC, Selutario approved these changes

2023-12-11 13:32 UTC, merged