Add support of raw message type parsing to class DatabaseFeedManagerMessageProcessor
wazuh/wazuh pull request #20647
Opened 2023-12-05 19:54 UTC by matias-braida

|Related issue|
|---|
|Closes #20615 |

## Description

This PR adds the capacity to dynamic JSON processing messages based on the value of the 'type' field. 
UTs were added and also database feed manager testtool was modified.

## Tests

![image](https://github.com/wazuh/wazuh/assets/101227434/583bf574-c63d-496f-987f-4976071505d8)

- Compilation without warnings in every supported platform
  - [ ] Linux
- [ ] Manual tests
- [ ] UTs running ok

2023-12-06 03:07 UTC, pereyra-m requested changes
Gj!

2023-12-06 03:07 UTC, pereyra-m commented on src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/eventDecoder.hpp
We should add tests for the new code in `src/wazuh_modules/vulnerability_scanner/tests/unit/eventDecoder_test.cpp`.

2023-12-06 17:42 UTC, matias-braida commented on src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/eventDecoder.hpp
> +        if ("raw_create" == data->resource.at("type"))
This behavior was modified. Now the EventDecoder is unchanged.

2023-12-06 17:43 UTC, matias-braida commented on src/wazuh_modules/vulnerability_scanner/testtool/databaseFeedManager/file_raw1.json
This is the real extract of a raw file.

2023-12-06 17:43 UTC, matias-braida commented on src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/eventDecoder.hpp
> +                data->cvesDatabase->delete_(data->resource.at("resource"));
This behavior was modified. Now the whole database is cleaned.

2023-12-07 01:30 UTC, pereyra-m approved these changes
LGTM!

2023-12-12 12:07 UTC, merged