Development of Interfaces, Mocks, and Unit Tests for Orchestrator and Related modules
wazuh/wazuh pull request #20882
Opened 2023-12-15 13:49 UTC by juliancnn

### Overview

This PR introduces a comprehensive update to the Wazuh Engine, focusing on the development of interfaces, mocks, and unit tests for the Orchestrator, Worker, Tester, and Router components. These enhancements aim to improve the modularity, testability, and overall robustness of these key components within the Wazuh Engine.

### Key Features

- **Interface Development**: Implemented well-defined interfaces for the Orchestrator, Worker, Tester, and Router classes, separating them into distinct interfaces and implementations.
- **Mock Creation**: Developed detailed mocks for these interfaces, facilitating effective unit testing and simulation of various conditions and scenarios.
- **Orchestrator Unit Testing**: Created a comprehensive suite of unit tests for the Orchestrator, covering all its methods and interactions with Worker, Tester, and Router.
- **Integration with Existing Tests**: Ensured that these new unit tests seamlessly integrate with the existing test suite of the Wazuh Engine.

### Implementation Details

- Designed interfaces that encapsulate the functionalities of the Orchestrator, Worker, Tester, and Router, enhancing the separation of concerns and modularity.
- The mocks accurately mimic the behavior of the actual classes, including handling various inputs and states, to ensure effective unit testing.
- The unit tests for the Orchestrator are extensive, covering a wide range of scenarios, including edge cases and error handling.
- Followed established coding standards and best practices for the Wazuh Engine project throughout the development process.

### Testing and Validation

- Conducted rigorous unit testing to validate the functionality and reliability of the new interfaces and mocks.
- Ensured that the new unit tests do not disrupt the existing test suite and complement the current testing strategy.

### Impact

- This PR significantly enhances the testing infrastructure for the Orchestrator, Worker, Tester, and Router components in the Wazuh Engine, ensuring robustness and reliability through well-structured interfaces, mocks, and unit tests.

2023-12-22 13:10 UTC, JcabreraC requested changes

2023-12-22 13:10 UTC, JcabreraC commented on src/engine/source/router/test/src/unit/mockTester.hpp
> +#endif // ROUTER_TEST_INTERNAL_MOCKS_TESTER_HPP
The line break at the end of the file is missing.

2023-12-22 13:10 UTC, JcabreraC commented on src/engine/source/router/test/src/unit/mockWorker.hpp
> +#endif // ROUTER_TEST_INTERNAL_MOCKS_WORKER_HPP
The line break at the end of the file is missing.

2023-12-22 13:10 UTC, JcabreraC commented on src/engine/source/router/test/src/unit/mockRouter.hpp
> +#endif // ROUTER_TEST_INTERNAL_MOCKS_ROUTER_HPP
The line break at the end of the file is missing.

2023-12-22 14:57 UTC, JavierBejMen approved these changes
LGTM

2023-12-22 16:00 UTC, soynof requested changes

2023-12-26 13:30 UTC, NahuFigueroa97 commented on src/engine/source/router/CMakeLists.txt
> +        builders # Todo delete after refactoring to builder
yes

2023-12-26 14:32 UTC, soynof approved these changes
LGTM!

2023-12-26 14:39 UTC, merged