Refactor Azure logs to use common cloud logger
wazuh/wazuh pull request #20979
Opened 2023-12-20 18:35 UTC by EduLeon12

|Related issue|
|---|
| Closes 16739|

## Description

## Configuration options

## Logs/Alerts example

## Tests

All test related to the wodle has been performed [here](https://github.com/wazuh/wazuh/issues/16739#issuecomment-1864846884).

```python
(unit-test) eduardoleon@pop-os:~/git/wazuh(16739-refactor-azure-logs)$ pytest wodles/
=========================== test session starts ===========================
platform linux -- Python 3.9.16, pytest-7.4.2, pluggy-0.13.1
rootdir: /home/eduardoleon/git/wazuh
plugins: anyio-3.6.2, aiohttp-1.0.4, trio-0.7.0, html-3.0.0, asyncio-0.18.1, cov-3.0.0, metadata-2.0.2
asyncio: mode=auto
collected 852 items

wodles/aws/tests/test_aws_bucket.py ............................... [  3%]
................................................................... [ 11%]
................................................................... [ 19%]
............................................                        [ 24%]
wodles/aws/tests/test_aws_s3.py ..................                  [ 26%]
wodles/aws/tests/test_aws_service.py ....                           [ 27%]
wodles/aws/tests/test_cloudtrail.py ..                              [ 27%]
wodles/aws/tests/test_cloudwatchlogs.py ........................... [ 30%]
..........................                                          [ 33%]
wodles/aws/tests/test_config.py ................................... [ 37%]
...........................................                         [ 42%]
wodles/aws/tests/test_guardduty.py .................                [ 44%]
wodles/aws/tests/test_inspector.py ......                           [ 45%]
wodles/aws/tests/test_load_balancers.py ............                [ 46%]
wodles/aws/tests/test_s3_log_handler.py ....                        [ 47%]
wodles/aws/tests/test_server_access.py ............................ [ 50%]
.....                                                               [ 51%]
wodles/aws/tests/test_sqs_queue.py .......                          [ 51%]
wodles/aws/tests/test_tools.py ...............................      [ 55%]
wodles/aws/tests/test_umbrella.py ......                            [ 56%]
wodles/aws/tests/test_vpcflow.py ............................       [ 59%]
wodles/aws/tests/test_waf.py .......                                [ 60%]
wodles/aws/tests/test_wazuh_integration.py ........................ [ 63%]
................................................................... [ 71%]
...........                                                         [ 72%]
wodles/azure/tests/test_azure.py .................................. [ 76%]
................................................................... [ 84%]
............                                                        [ 85%]
wodles/azure/tests/test_orm.py ...............................      [ 89%]
wodles/docker-listener/tests/test_docker_listener.py .............. [ 90%]
.....                                                               [ 91%]
wodles/gcloud/tests/test_bucket.py ................................ [ 95%]
.                                                                   [ 95%]
wodles/gcloud/tests/test_gcloud.py .........                        [ 96%]
wodles/gcloud/tests/test_integration.py ........                    [ 97%]
wodles/gcloud/tests/test_subscriber.py ..............               [ 99%]
wodles/gcloud/tests/test_tools.py ........                          [100%]

============================ warnings summary =============================
../../.pyenv/versions/3.9.16/envs/unit-test/lib/python3.9/site-packages/pytest_aiohttp/plugin.py:28
  /home/eduardoleon/.pyenv/versions/3.9.16/envs/unit-test/lib/python3.9/site-packages/pytest_aiohttp/plugin.py:28: DeprecationWarning: The 'asyncio_mode' is 'legacy', switching to 'auto' for the sake of pytest-aiohttp backward compatibility. Please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
    config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================== 852 passed, 1 warning in 3.08s ======================

```

2023-12-20 19:09 UTC, EduLeon12 commented
##  Check Update

The failure on the Unit test is expected since the `shared/` module that contains the logger has not been updated in the pipeline.

```command
```

2023-12-21 19:38 UTC, fdalmaup requested changes

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +            azure_logger.error(f"Error: The authentication file does not contains the expected '{fields[0]}' "
```suggestion
            azure_logger.error(f"Error: The authentication file does not contain the expected '{fields[0]}'."
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +        azure_logger.error("Error: The authentication file format is not valid. "
```suggestion
        azure_logger.error("Error: The authentication file format is not valid."
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +        azure_logger.debug(f"Attempting to update a {table.__tablename__} row object. "
```suggestion
        azure_logger.debug(f"Attempting to update a {table.__tablename__} row object."
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +        azure_logger.error(f"Error trying to obtain row object from '{orm.Graph.__tablename__}' using md5='{md5}': {e}")
```suggestion
        azure_logger.error(f"Error trying to obtain row object from '{orm.Graph.__tablename__}' using md5='{md5}': {e}.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +            azure_logger.info("Graph: There are no new results")
```suggestion
            azure_logger.info("Graph: There are no new results.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +            azure_logger.error(f"Error trying to obtain row object from '{orm.Storage.__tablename__}' using md5='{md5}': {e}")
```suggestion
            azure_logger.error(f"Error trying to obtain row object from '{orm.Storage.__tablename__}' using md5='{md5}': {e}.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +    azure_logger.info("Storage: End")
```suggestion
    azure_logger.info("Storage: End.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +        azure_logger.error(f"Error: An error occurred while trying to obtain the authentication token: {e}")
```suggestion
        azure_logger.error(f"Error: An error occurred while trying to obtain the authentication token: {e}.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +            azure_logger.error(f"ERROR: Error sending message to wazuh: {e}")
```suggestion
            azure_logger.error(f"ERROR: Error sending message to wazuh: {e}.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +            azure_logger.error(f"Error updating row object from {table.__tablename__}: {e}")
```suggestion
            azure_logger.error(f"Error updating row object from {table.__tablename__}: {e}.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +        azure_logger.error(f"Error inserting row object into {table.__tablename__}: {e}")
```suggestion
        azure_logger.error(f"Error inserting row object into {table.__tablename__}: {e}.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +        azure_logger.error(f"Log Analytics: {e}")
```suggestion
        azure_logger.error(f"Log Analytics: {e}.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +                           f"using md5='{md5}': {e}")
```suggestion
                           f"using md5='{md5}': {e}.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +    azure_logger.info(f"Log Analytics: The search starts for query: '{query}'")
```suggestion
    azure_logger.info(f"Log Analytics: The search starts for query: '{query}'.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +                azure_logger.info("Log Analytics: There are no new results")
```suggestion
                azure_logger.info("Log Analytics: There are no new results.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +                    azure_logger.error("Error: No TimeGenerated field was found")
```suggestion
                    azure_logger.error("Error: No TimeGenerated field was found.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +    azure_logger.info("Graph: Pagination starts")
```suggestion
    azure_logger.info("Graph: Pagination starts.")
```

2023-12-21 19:38 UTC, fdalmaup commented on wodles/azure/azure-logs.py
> +    azure_logger.info("Graph: End")
```suggestion
        azure_logger.error(f"Graph: {e}.")
    azure_logger.info("Graph: End.")
```

2023-12-22 13:12 UTC, fdalmaup approved these changes
LGTM!

2023-12-22 17:49 UTC, Selutario approved these changes

2023-12-22 17:49 UTC, merged