Fix GET /groups endpoint
wazuh/wazuh pull request #21181
Opened 2024-01-03 17:42 UTC by javiersanchz

|Related issue|
|---|
| #20942  |

## Description

 - This PR closes https://github.com/wazuh/wazuh/issues/20942.

 - It was added `limit` parameter, because the query was not using the parameter passed to it, causing the result to already be limited by taking the parameter when executing `process_array` .
 - The output of total_affected_items was also modified

 - The unit tests were successfully launched

## Logs/Alerts example

<details><summary>Limit & Offset</summary>

```console

root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -X GET -k "https://0.0.0.0:55000/groups?pretty=True&limit=600&offset=510"
{
   "data": {
      "affected_items": [
         {
            "name": "ZsNJY5Ka28Yg4",
            "count": 0,
            "mergedSum": "c9c08c92e3b62ae02963fd3ed502e203",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "ZSx41kJMJXSWu",
            "count": 0,
            "mergedSum": "7ab12208800fcd8c5101ba76135cfdd4",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "ZWeHZp2Znop1g",
            "count": 0,
            "mergedSum": "3ab7764935e717a2da19e04671d41b61",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "zyFhILLNxkv3u",
            "count": 0,
            "mergedSum": "0d59f0aa02898be4e2e65b228dce3e8c",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "ZYNNKQc1Ocdv3",
            "count": 0,
            "mergedSum": "c8965a6b2e1b242bfebdc7f33f6096d3",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "zzGAsXAVEz7ME",
            "count": 0,
            "mergedSum": "499fb8d8224071aef2d109902f8e21f5",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         }
      ],
      "total_affected_items": 516,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected groups information was returned",
   "error": 0

```
</details>

<details><summary>Limit</summary>

```console

root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -X GET -k "https://0.0.0.0:55000/groups?pretty=True&limit=600"
{
   "data": {
      "affected_items": [
         {
            "name": "083PmIBDNWewP",
            "count": 0,
            "mergedSum": "8ccfc6a77706ab701ad335cf952bdaad",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "0b1Q4KGTSWTkH",
            "count": 0,
            "mergedSum": "1120aeaf0691d997a9816a77e15fa76b",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "0b64Rdq9GA1oa",
            "count": 0,
            "mergedSum": "91bd44823da99f85345e095d039c264f",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "0DBMgDTbO5rSA",
            "count": 0,
            "mergedSum": "5ed62996a0e968e57a3a49007adef1d1",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "0fObLSQvrGEov",
            "count": 0,
            "mergedSum": "57a3a4de7f64636b58ad2e5e4ac6734a",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "0ISQ46ZqGhu8m",
            "count": 0,
            "mergedSum": "513544b7c1a0265a10168895d262b86a",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "0OmrRfrBSd27q",
            "count": 0,
            "mergedSum": "ac5a1104c97fc04399d0864f0700432e",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "0RZoGNWjNQSIf",
            "count": 0,
            "mergedSum": "1762cb84f1b3ea1b419bf4326bc11da7",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "1FFIPu8VXkePg",
            "count": 0,
            "mergedSum": "409de506b748a1077a9d3f50f8b07971",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         ...
          ],
      "total_affected_items": 516,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected groups information was returned",
   "error": 0
```
</details>

<details><summary>Offset = 500</summary>

```console

root@wazuh-master:/# TOKEN=$(curl -u wazuh:wazuh -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   398  100   398    0     0    815      0 --:--:-- --:--:-- --:--:--   817
root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -X GET -k "https://0.0.0.0:55000/groups?pretty=True&offset=500"
{
   "data": {
      "affected_items": [],
      "total_affected_items": 516,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected groups information was returned",
   "error": 0

```
</details>

<details><summary>Offset = 495</summary>

```console

root@wazuh-master:/# curl -H "Authorization: Bearer $TOKEN" -X GET -k "https://0.0.0.0:55000/groups?pretty=True&offset=495"
{
   "data": {
      "affected_items": [
         {
            "name": "ZRUHzW31oxleK",
            "count": 0,
            "mergedSum": "f868a068e41c2766f5f79698b7f6e375",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "ZsNJY5Ka28Yg4",
            "count": 0,
            "mergedSum": "c9c08c92e3b62ae02963fd3ed502e203",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "ZSx41kJMJXSWu",
            "count": 0,
            "mergedSum": "7ab12208800fcd8c5101ba76135cfdd4",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "ZWeHZp2Znop1g",
            "count": 0,
            "mergedSum": "3ab7764935e717a2da19e04671d41b61",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "name": "ZYNNKQc1Ocdv3",
            "count": 0,
            "mergedSum": "c8965a6b2e1b242bfebdc7f33f6096d3",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         }
      ],
      "total_affected_items": 516,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected groups information was returned",
   "error": 0

```
</details>

In the output of `offset = 500`, no items are displayed because the default limit is set to 500. If you add `limit = 600` as shown, the `affected_items` appear, just like when `offset = 495` shows the 5 `affected_items` up to 500 (by default if you don't add the `limit` parameter)

2024-01-03 19:39 UTC, nico-stefani approved these changes
LGTM

2024-01-11 13:55 UTC, Selutario requested changes
The limit is now working fine but `offset` is still wrong. The output should always include `limit` number of items (unless there are fewer elements to return), no matter the offset value. For example, if there are 1600 items, this is how limit + offset would work:
- `Limit 500, offset 0:` Returns items 0 to 499
- `Limit 500, offset 500:` Returns items 500 to 999
- `Limit 500, offset 1000:` Returns items 1000 to 1499
- `Limit 500, offset 1500:` Returns items 1500 to 1600 (since there are no more than 1600 items)

Thanks to the `offset`, a segment of data can be obtained without reading all the previous data, but this is not what happens right now according to the PR example:
```JSON
# curl -H "Authorization: Bearer $TOKEN" -X GET -k "https://0.0.0.0:55000/groups?pretty=True&offset=500"
{
   "data": {
      "affected_items": [],
      "total_affected_items": 516,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected groups information was returned",
   "error": 0
}
```

If there are 516 groups and offset 500 is applied, it should be printing the remaining 16 groups (from 500 to 515).

2024-01-11 13:55 UTC, Selutario commented on framework/wazuh/agent.py
> +        with WazuhDBQueryGroup(**rbac_filters, limit=limit) as group_query:
We need to send the offset parameter to the DB so it fetches the expected data:
```suggestion
        with WazuhDBQueryGroup(**rbac_filters, limit=limit, offset=offset) as group_query:
```

Also, remove `limit` and `offset` from process_array on line 630:
https://github.com/wazuh/wazuh/blob/958f6e2264d7e3dd5fdad67d3d73c24cf0743623/framework/wazuh/agent.py#L630

2024-01-11 17:07 UTC, javiersanchz commented
- The suggested changes were added, the functionality was verified, and the tests were executed

2024-01-24 12:08 UTC, Selutario approved these changes
LGTM. Now the full list of groups can be obtained. 

However, there will still be a bug when searching or applying any kind of filters, since they will apply only to a subset of groups. There is no proper way to fix the problem on the API side, so an issue was opened for the core team to include the hashes in global.db:
- https://github.com/wazuh/wazuh/issues/19010

2024-01-24 12:28 UTC, Selutario requested changes

2024-01-24 12:28 UTC, Selutario commented on framework/wazuh/agent.py
> +        result.total_affected_items = query_data['totalItems']
I just saw that there are some failing checks and it seems those are related with this line. If no filters are applied in the process_array, the number of total items should be `query_data['totalItems']` (all items in the DB). But if any filter is applied (for exmaple, `q=name=test_group_3`), the number of total_items should be 1.

This should do the trick, but review the unit and API tests to make sure it works as expected:
```suggestion
        result.total_affected_items = query_data['totalItems'] if limit == data['totalItems'] else data['totalItems']
```

2024-01-24 16:12 UTC, javiersanchz commented
**Requested changes were applied, and `unit tests` and `API tests` were reviewed**

<details>
<summary>Unit test</summary>

```console
(unittest-env) wazuh@javier:~/Git/wazuh$ PYTHONPATH=/home/wazuh/Git/wazuh/api:/home/wazuh/Git/wazuh/framework python3 -m pytest framework/wazuh/tests/test_agent.py -v
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.9.16, pytest-7.4.0, pluggy-0.13.1 -- /home/wazuh/venv/unittest-env/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.9.16', 'Platform': 'Linux-6.2.0-37-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.4.0', 'pluggy': '0.13.1'}, 'Plugins': {'aiohttp': '0.3.0', 'metadata': '3.0.0', 'html': '2.1.1', 'trio': '0.7.0', 'asyncio': '0.15.1'}}
rootdir: /home/wazuh/Git/wazuh/framework
configfile: pytest.ini
plugins: aiohttp-0.3.0, metadata-3.0.0, html-2.1.1, trio-0.7.0, asyncio-0.15.1
collected 122 items                                                                                                                                                                                        

framework/wazuh/tests/test_agent.py::test_agent_get_distinct_agents[fields0-expected_items0] PASSED                                                                                                  [  0%]
framework/wazuh/tests/test_agent.py::test_agent_get_distinct_agents[fields1-expected_items1] PASSED                                                                                                  [  1%]
framework/wazuh/tests/test_agent.py::test_agent_get_distinct_agents[fields2-expected_items2] PASSED                                                                                                  [  2%]
framework/wazuh/tests/test_agent.py::test_agent_get_distinct_agents[fields3-expected_items3] PASSED                                                                                                  [  3%]
framework/wazuh/tests/test_agent.py::test_agent_get_distinct_agents[fields4-expected_items4] PASSED                                                                                                  [  4%]
framework/wazuh/tests/test_agent.py::test_agent_sort_order[fields0-asc-expected_items0] PASSED                                                                                                       [  4%]
framework/wazuh/tests/test_agent.py::test_agent_sort_order[fields1-asc-expected_items1] PASSED                                                                                                       [  5%]
framework/wazuh/tests/test_agent.py::test_agent_sort_order[fields2-desc-expected_items2] PASSED                                                                                                      [  6%]
framework/wazuh/tests/test_agent.py::test_agent_get_agents_summary_status PASSED                                                                                                                     [  7%]
framework/wazuh/tests/test_agent.py::test_agent_get_agents_summary_os PASSED                                                                                                                         [  8%]
framework/wazuh/tests/test_agent.py::test_agent_reconnect_agents[agent_list0-expected_items0-None] PASSED                                                                                            [  9%]
framework/wazuh/tests/test_agent.py::test_agent_reconnect_agents[agent_list1-expected_items1-1703] PASSED                                                                                            [  9%]
framework/wazuh/tests/test_agent.py::test_agent_reconnect_agents[agent_list2-expected_items2-1701] PASSED                                                                                            [ 10%]
framework/wazuh/tests/test_agent.py::test_agent_restart_agents[agent_list0-expected_items0-None] PASSED                                                                                              [ 11%]
framework/wazuh/tests/test_agent.py::test_agent_restart_agents[agent_list1-expected_items1-1703] PASSED                                                                                              [ 12%]
framework/wazuh/tests/test_agent.py::test_agent_restart_agents[agent_list2-expected_items2-1701] PASSED                                                                                              [ 13%]
framework/wazuh/tests/test_agent.py::test_agent_restart_agents_by_node[agent_list0-expected_items0-1703] PASSED                                                                                      [ 13%]
framework/wazuh/tests/test_agent.py::test_agent_restart_agents_by_node[agent_list1-expected_items1-1701] PASSED                                                                                      [ 14%]
framework/wazuh/tests/test_agent.py::test_agent_get_agents[agent_list0-expected_items0] PASSED                                                                                                       [ 15%]
framework/wazuh/tests/test_agent.py::test_agent_get_agents[agent_list1-expected_items1] PASSED                                                                                                       [ 16%]
framework/wazuh/tests/test_agent.py::test_agent_get_agents_in_group[default-True-expected_agents0] PASSED                                                                                            [ 17%]
framework/wazuh/tests/test_agent.py::test_agent_get_agents_in_group[not_exists_group-False-None] PASSED                                                                                              [ 18%]
framework/wazuh/tests/test_agent.py::test_agent_get_agents_in_group_q_formats[default-(name~wazuh,status~active)-group=default;((name~wazuh,status~active))] PASSED                                  [ 18%]
framework/wazuh/tests/test_agent.py::test_agent_get_agents_in_group_q_formats[default-name~wazuh,status~active-group=default;(name~wazuh,status~active)] PASSED                                      [ 19%]
framework/wazuh/tests/test_agent.py::test_agent_get_agents_keys[agent_list0-expected_items0] PASSED                                                                                                  [ 20%]
framework/wazuh/tests/test_agent.py::test_agent_get_agents_keys[agent_list1-expected_items1] PASSED                                                                                                  [ 21%]
framework/wazuh/tests/test_agent.py::test_agent_delete_agents[agent_list0-filters0-None-None-expected_items0] PASSED                                                                                 [ 22%]
framework/wazuh/tests/test_agent.py::test_agent_delete_agents[agent_list1-filters1-None-1731-expected_items1] PASSED                                                                                 [ 22%]
framework/wazuh/tests/test_agent.py::test_agent_delete_agents[agent_list2-filters2-None-1731-expected_items2] PASSED                                                                                 [ 23%]
framework/wazuh/tests/test_agent.py::test_agent_delete_agents[agent_list3-filters3-None-1731-expected_items3] PASSED                                                                                 [ 24%]
framework/wazuh/tests/test_agent.py::test_agent_delete_agents[agent_list4-filters4-None-1731-expected_items4] PASSED                                                                                 [ 25%]
framework/wazuh/tests/test_agent.py::test_agent_delete_agents[agent_list5-filters5-None-1731-expected_items5] PASSED                                                                                 [ 26%]
framework/wazuh/tests/test_agent.py::test_agent_delete_agents[agent_list6-filters6-None-1731-expected_items6] PASSED                                                                                 [ 27%]
framework/wazuh/tests/test_age [...]

2024-01-25 15:41 UTC, Selutario approved these changes
LGTM

2024-01-25 15:42 UTC, merged