Fix/21290 vd not disabled master
wazuh/wazuh pull request #21644
Opened 2024-01-26 21:17 UTC by RamosFe

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/21290|

## Description

Disable the Vulnerability Detector for test cases where the manager `ossec.conf` is configured.

2024-01-30 14:00 UTC, fdalmaup requested changes
Changes look correct, nevertheless:
- There is a failing check that does not correlate with the modifications. We should leave a note stating its existence.
- The modified configurations are used in other test files that were not executed as part of the PR checks. These are: 
  - `test_manager_endpoints`
  - `test_rbac_black_cluster_endpoints`
  - `test_rbac_black_manager_endpoints`
  - `test_rbac_white_cluster_endpoints`
  - `test_rbac_white_manager_endpoints`
  - `test_rbac_white_all_endpoints`
 The execution should be attached in the PR or the issue as proof that it does not break said tests.

2024-02-01 14:15 UTC, RamosFe commented
<details>
  <summary>test_manager_endpoints</summary>
  
  ```
  (venv) federamos@pop-os:~/Documents/Wazuh/Repositories/wazuh/api/test/integration$ python3 -m pytest -v test_manager_endpoints.tavern.yaml
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.9.18, pytest-7.3.1, pluggy-1.4.0 -- /home/federamos/Documents/Wazuh/Repositories/wazuh/venv/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.9.18', 'Platform': 'Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.4.0'}, 'Plugins': {'asyncio': '0.18.1', 'trio': '0.7.0', 'html': '2.1.1', 'metadata': '3.0.0', 'tavern': '1.23.5', 'aiohttp': '1.0.4'}}
rootdir: /home/federamos/Documents/Wazuh/Repositories/wazuh/api/test/integration
configfile: pytest.ini
plugins: asyncio-0.18.1, trio-0.7.0, html-2.1.1, metadata-3.0.0, tavern-1.23.5, aiohttp-1.0.4
asyncio: mode=auto
collected 36 items                                                                                                                                                                                                                      

test_manager_endpoints.tavern.yaml::GET /manager/status PASSED                                                                                                                                                                    [  2%]
test_manager_endpoints.tavern.yaml::GET /manager/info PASSED                                                                                                                                                                      [  5%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[alerts] PASSED                                                                                                                                           [  8%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[auth] PASSED                                                                                                                                             [ 11%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[cis-cat] PASSED                                                                                                                                          [ 13%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[cluster] PASSED                                                                                                                                          [ 16%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[command] PASSED                                                                                                                                          [ 19%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[global] PASSED                                                                                                                                           [ 22%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[localfile] PASSED                                                                                                                                        [ 25%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[osquery] PASSED                                                                                                                                          [ 27%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[remote] PASSED                                                                                                                                           [ 30%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[rootcheck] PASSED                                                                                                                                        [ 33%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[ruleset] PASSED                                                                                                                                          [ 36%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[sca] PASSED                                                                                                                                              [ 38%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[syscheck] PASSED                                                                                                                                         [ 41%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[syscollector] PASSED                                                                                                                                     [ 44%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[vulnerability-detection] PASSED                                                                                                                          [ 47%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[indexer] PASSED                                                                                                                                          [ 50%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration PASSED                                                                                                                                                             [ 52%]
test_manager_endpoints.tavern.yaml::GET /manager/daemons/stats PASSED                                                                                                                                                             [ 55%]
test_manager_endpoints.tavern.yaml::GET /manager/stats PASSED                                                                                                                                                                     [ 58%]
test_manager_endpoints.tavern.yaml::GET /manager/stats/hourly PASSED                                                                                                                                                              [ 61%]
test_manager_endpoints.tavern.yaml::GET /manager/stats/weekly PASSED                                                                                                                                                              [ 63%]
test_manager_endpoints.tavern.yaml::GET /manager/stats/analysisd PASSED                                                                                                                                                           [ 66%]
test_manager_endpoints.tavern.yaml::GET /manager/stats/remoted PASSED                                                                                                                                                             [ 69%]
test_manager_endpoints.tavern.yaml::GET /manager/logs PASSED                                                                                                                                                                      [ 72%]
test_manager_endpoints.tavern.yaml::GET /manager/logs/summary PASSED                                                                                                                                                              [ 75%]
test_manager_endpoints.tavern.yaml::GET /manager/api/config PASSED                                                                                                                                                                [ 77%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration/validation (OK) PASSED                                                                      [...]

2024-02-01 20:06 UTC, fdalmaup approved these changes
LGTM!

2024-02-05 11:32 UTC, Selutario approved these changes
LGTM. The failing API IT tier 0 and 1 [check](https://github.com/wazuh/wazuh/actions/runs/7673549635) is known and has already been fixed in these issues, which are (still) not merged in 4.8.2:
- https://github.com/wazuh/wazuh/issues/21402
- https://github.com/wazuh/wazuh/issues/21401

2024-02-05 11:32 UTC, merged