Merge group files endpoints
wazuh/wazuh pull request #21653
Opened 2024-01-29 16:31 UTC by GGP1

|Related issue|
|---|
| Closes |

## Description

Merges the `/groups/:group_id/files/:file_name/json` and `/groups/:group_id/files/:file_name/xml` endpoints into a single one that takes the `return_format` parameter which defined whether the response content will be formatted in plain text or json.

## Logs/Alerts example

<details><summary>Get merged.mg in plain text</summary>

`GET /groups/default/files/merged.mg?return_format=plain`

```
#default
!228 ar.conf
restart-ossec0 - restart-ossec.sh - 0
restart-ossec0 - restart-ossec.cmd - 0
restart-wazuh0 - restart-ossec.sh - 0
restart-wazuh0 - restart-ossec.cmd - 0
restart-wazuh0 - restart-wazuh - 0
restart-wazuh0 - restart-wazuh.exe - 0
!76 agent.conf
<agent_config>

  

</agent_config>
!28411 cis_apache2224_rcl.txt
...
```

</details>

<details><summary>Get merged.mg in JSON</summary>

`GET /groups/default/files/merged.mg?return_format=json`

```json
{
    "data": {
        "vars": {
            "traceen": "/etc/apache2/apache2.conf,/etc/httpd/conf/httpd.conf,/etc/apache2/conf-enabled/security.conf;",
            "home_dirs": "/usr2/home/*,/home/*,/home,/*/home/*,/*/home,/;",
            "enviroment_files": "/*/home/*/\\.bashrc,/*/home/*/\\.profile,/*/home/*/\\.bash_profile,/home/*/\\.bashrc,/home/*/\\.profile,/home/*/\\.bash_profile;",
            "rc_dirs": "/etc/rc.d/rc2.d,/etc/rc.d/rc3.d,/etc/rc.d/rc4.d,/etc/rc.d/rc5.d;",
            "sshd_file": "/etc/ssh/sshd_config;",
            "web_dirs": "/var/www,/var/htdocs,/home/httpd,/usr/local/apache,/usr/local/apache2,/usr/local/www;"
        },
        "controls": [
            {},
            {
                "name": "CIS - Apache Configuration - 2.3: WebDAV Modules are enable",
                "cis": [],
                "pci": [],
                "condition": "any",
                "reference": "https://workbench.cisecurity.org/benchmarks/307, https://workbench.cisecurity.org/benchmarks/308",
                "checks": [
                    "d:$conf-dirs -> conf -> !r:^# && r:loadmodule\\sdav;",
                    "d:$conf-dirs -> load -> !r:^# && r:loadmodule\\sdav;",
                    "f:/etc/httpd/conf.d -> !r:^# && r:loadmodule\\sdav;",
                    "d:$mods-en -> dav.load;"
                ]
            },
...
```

</details>

<details><summary>Get file content using an invalid return_format</summary>

`GET /groups/default/files/merged.mg?return_format=xml`

```json
{
    "title": "Bad Request",
    "detail": "'xml' is not one of ['json', 'plain']. Failed validating 'enum' in schema: {'enum': ['json', 'plain'], 'type': 'string'}. On instance: 'xml'"
}
```

</details>

<details><summary>Get file content using a configuration type</summary>

`GET /groups/default/files/agent.conf?type=conf`

```json
{
    "data": {
        "total_affected_items": 1,
        "affected_items": [
            {
                "filters": {},
                "config": {}
            }
        ]
    },
    "error": 0
}
```

</details>

2024-01-31 06:34 UTC, EduLeon12 approved these changes
Great work @GGP1

 LGTM!,

My only question is if it would be better for readibility purposes to change the raw default value to a bool `False` instead of `None.

2024-01-31 12:05 UTC, GGP1 commented
> My only question is if it would be better for readibility purposes to change the raw default value to a bool `False` instead of `None.

I've seen both in the code, I don't think there's a standard but I agree that using `False` is slightly better so I modified it. Thanks!

2024-01-31 18:05 UTC, Selutario requested changes
Looks good! Just some minor changes were requested. Also, I found a strange behaviour. I guess this is expected, but I would like to confirm.

I tried creating a `test.json` file. When the content-type returned is `application/json`, it is seen this way:

> `curl -k -X GET "https://localhost:55000/groups/default/files/test.json?raw=true" -H  "Authorization: Bearer $TOKEN" -v`

![image](https://github.com/wazuh/wazuh/assets/23361101/93aba6d0-2979-4a54-810f-932d72dbc311)

However, this does not happen when xml content is returned as `application/xml`:
![image](https://github.com/wazuh/wazuh/assets/23361101/55889e65-65ef-49fa-9937-ad20504dc0e9)

Nor when the json file is returned as plain :thinking::
![image](https://github.com/wazuh/wazuh/assets/23361101/a143a2c4-09b7-45cf-8fec-43916371705d)

2024-01-31 18:05 UTC, Selutario commented on framework/wazuh/core/configuration.py
>      dict
```suggestion
    dict or str
```

2024-02-01 12:28 UTC, GGP1 commented
> Looks good! Just some minor changes were requested. Also, I found a strange behaviour. I guess this is expected, but I would like to confirm.
> 
> I tried creating a `test.json` file. When the content-type returned is `application/json`, it is seen this way:
> 
> > `curl -k -X GET "https://localhost:55000/groups/default/files/test.json?raw=true" -H  "Authorization: Bearer $TOKEN" -v`
> 
> ![image](https://private-user-images.githubusercontent.com/23361101/301261095-93aba6d0-2979-4a54-810f-932d72dbc311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODk5ODgsIm5iZiI6MTcwNjc4OTY4OCwicGF0aCI6Ii8yMzM2MTEwMS8zMDEyNjEwOTUtOTNhYmE2ZDAtMjk3OS00YTU0LTgxMGYtOTMyZDcyZGJjMzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEyMTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMDE0MjBhODc4NmFhNmJiZmYwZWExOGMzYjRjZTU1NGI1OTBiYjQzMDBmNmIxMWJjNmU1Yzc2NzQxMjliMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixDloTDndhdxFkqo1lu00Qq3_AWRbsj6MvxMOLD3w50)

This is expected, the content of the file is returned as a string, and if the Content-Type is `json` then it will be interpreted as a json string instead of an object. This is why new lines are present and the double quotes are escaped. The other content types do not behave the same because they don't need to escape or wrap anything (and thus the output makes it seem like the actual file content).

2024-02-01 12:31 UTC, GGP1 commented
> Looks good! Just some minor changes were requested. Also, I found a strange behaviour. I guess this is expected, but I would like to confirm.
> 
> I tried creating a `test.json` file. When the content-type returned is `application/json`, it is seen this way:
> 
> > `curl -k -X GET "https://localhost:55000/groups/default/files/test.json?raw=true" -H  "Authorization: Bearer $TOKEN" -v`
> 
> ![image](https://private-user-images.githubusercontent.com/23361101/301261095-93aba6d0-2979-4a54-810f-932d72dbc311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODk5ODgsIm5iZiI6MTcwNjc4OTY4OCwicGF0aCI6Ii8yMzM2MTEwMS8zMDEyNjEwOTUtOTNhYmE2ZDAtMjk3OS00YTU0LTgxMGYtOTMyZDcyZGJjMzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEyMTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMDE0MjBhODc4NmFhNmJiZmYwZWExOGMzYjRjZTU1NGI1OTBiYjQzMDBmNmIxMWJjNmU1Yzc2NzQxMjliMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixDloTDndhdxFkqo1lu00Qq3_AWRbsj6MvxMOLD3w50)

@Selutario This is expected, the content of the file is returned as a string, and if the Content-Type is `json` then it will be interpreted as a json string instead of an object.

In order to include all the content inside the string, new lines have to be literal and double quotes have to be escaped. The other content types do not behave the same because they don't need to escape or wrap anything (and thus the output is the actual file content).

2024-02-01 16:38 UTC, Selutario approved these changes
LGTM. I think we'll need to update the documentation too, at least the [RBAC reference](https://documentation.wazuh.com/current/user-manual/api/rbac/reference.html). 

Please, open a PR for this @GGP1

2024-02-01 16:39 UTC, merged