Add setup and teardown to scenaries for avoid dependence between them
wazuh/wazuh pull request #21813
Opened 2024-02-07 20:23 UTC by NahuFigueroa97

|Related issue|
|---|
|#21758|

## Description

2024-02-15 19:46 UTC, juliancnn requested changes

2024-02-15 19:46 UTC, juliancnn commented on src/engine/test/integration_tests/policy/steps/api_steps.py
> +    parse_response = ParseDict(response, expected_response_type)
Check `error`, this var handle the protocol error:

https://github.com/wazuh/wazuh/blob/aeac12615a30969ac9142da37e65ea2368b03435/src/engine/tools/api-communication/src/api_communication/client.py#L137-L139

2024-02-16 16:46 UTC, JavierBejMen approved these changes
LGTM!

2024-02-19 11:24 UTC, JavierBejMen approved these changes
LGTM

2024-02-19 11:39 UTC, JcabreraC approved these changes
LGTM !

2024-02-19 11:39 UTC, merged