Add aws_account_alias to aws_service
wazuh/wazuh pull request #21843
Opened 2024-02-09 12:00 UTC by javiersanchz

|Related issue|
|---|
| #15840  |

## Description

The `aws_account_alias` parameter was added to `aws_service` because it was not yet implemented in the code, but it was present in the documentation.

The changes were verified, modified accordingly, and `unit_tests` were run. Additionally, the documentation was reviewed to ensure it did not require any updates.

## Configuration options

Enabled `wazuh_modules.debug=2` and `/var/ossec/etc/ossec.conf`:

```console
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>1m</interval>
    <run_on_start>yes</run_on_start>
    
    <service type="cloudwatchlogs">a
      <aws_profile>default</aws_profile>
      <aws_log_groups>wazuh-cloudwatchlogs-integration-tests</aws_log_groups>
      <aws_account_alias>test-feature-15840</aws_account_alias>
      <regions>us-east-1</regions>
    </service>
  </wodle>
```

## Logs

```console
2024/02/09 12:43:23 wazuh-modulesd:aws-s3[19177] wm_aws.c:703 at wm_aws_run_service(): DEBUG: Service: cloudwatchlogs(test-feature-15840)  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: No retries configuration found in profile config. Generating default configuration for retries: mode: standard - max_attempts: 10
DEBUG: Created Config object using profile: 'default' configuration
DEBUG: only logs: None
DEBUG: Getting log streams for "wazuh-cloudwatchlogs-integration-tests" log group
DEBUG: Found "wazuh-cloudwatchlogs-integration-tests" log stream in wazuh-cloudwatchlogs-integration-tests
DEBUG: Getting data from DB for log stream "wazuh-cloudwatchlogs-integration-tests" in log group "wazuh-cloudwatchlogs-integration-tests"
DEBUG: Token: "f/38076214461433656xxxxxs", start_time: "1707350400000", end_time: "1707350400005"
DEBUG: Getting CloudWatch logs from log stream "wazuh-cloudwatchlogs-integration-tests" in log group "wazuh-cloudwatchlogs-integration-tests" using token "f/3807621446143xxxxx/s", start_time "1707350400006" and end_time "None"
DEBUG: +++ There are no new events in the "wazuh-cloudwatchlogs-integration-tests" group
DEBUG: Saving data for log group "wazuh-cloudwatchlogs-integration-tests" and log stream "wazuh-cloudwatchlogs-integration-tests".
DEBUG: The saved values are "{'token': 'f/38076214461433xxxxxxs', 'start_time': 1707350400000, 'end_time': 1707350400006}"
DEBUG: Some data already exists on DB for that key. Updating their values...
DEBUG: Purging the BD
DEBUG: Getting log streams for "wazuh-cloudwatchlogs-integration-tests" log group
DEBUG: Found "wazuh-cloudwatchlogs-integration-tests" log stream in wazuh-cloudwatchlogs-integration-tests
DEBUG: committing changes and closing the DB
2024/02/09 12:43:23 wazuh-modulesd:aws-s3[19177] wm_aws.c:80 at wm_aws_main(): DEBUG: Sleeping until: 2024/02/09
```
Service with the `account_alias` **test-feature-15840** in the `ossec.log` output: 

```
DEBUG: Service: cloudwatchlogs(test-feature-15840)
```

## Tests

<details>

<summary>Test_aws_service</summary>

```console
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-0.13.1 -- /home/wazuh/venv/unittest-env/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.9.16', 'Platform': 'Linux-6.2.0-37-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '3.0.0', 'aiohttp': '1.0.4', 'html': '2.1.1', 'trio': '0.7.0', 'asyncio': '0.18.1', 'tavern': '1.23.5'}}
rootdir: /home/wazuh/Git/wazuh/wodles/aws/tests
configfile: pytest.ini
plugins: metadata-3.0.0, aiohttp-1.0.4, html-2.1.1, trio-0.7.0, asyncio-0.18.1, tavern-1.23.5
asyncio: mode=auto
collected 7 items                                                                                                                                                                                          

wodles/aws/tests/test_aws_service.py::test_aws_service_initializes_properly PASSED                                                                                                                   [ 14%]
wodles/aws/tests/test_aws_service.py::test_aws_service_check_region PASSED                                                                                                                           [ 28%]
wodles/aws/tests/test_aws_service.py::test_aws_service_get_last_log_date PASSED                                                                                                                      [ 42%]
wodles/aws/tests/test_aws_service.py::test_aws_service_format_message PASSED                                                                                                                         [ 57%]
wodles/aws/tests/test_aws_service.py::test_aws_service_get_alert_msg[event0] PASSED                                                                                                                  [ 71%]
wodles/aws/tests/test_aws_service.py::test_aws_service_get_alert_msg[event1] PASSED                                                                                                                  [ 85%]
wodles/aws/tests/test_aws_service.py::test_aws_service_get_alert_msg[None] PASSED                                                                                                                    [100%]

============================================================================================ 7 passed in 0.20s =============================================================================================
```

</details>

<details>

<summary>Test_aws</summary>

```console
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-0.13.1
rootdir: /home/wazuh/Git/wazuh/wodles/aws/tests
configfile: pytest.ini
plugins: metadata-3.0.0, aiohttp-1.0.4, html-2.1.1, trio-0.7.0, asyncio-0.18.1, tavern-1.23.5
asyncio: mode=auto
collected 642 items                                                                                                                                                                                               

wodles/aws/tests/test_aws_bucket.py ....................................................................................................................................................................... [ 26%]
..........................................                                                                                                                                                                  [ 32%]
wodles/aws/tests/test_aws_s3.py ..................                                                                                                                                                          [ 35%]
wodles/aws/tests/test_aws_service.py .......                                                                                                                                                                [ 36%]
wodles/aws/tests/test_cloudtrail.py ..                                                                                                                                                                      [ 36%]
wodles/aws/tests/test_cloudwatchlogs.py .....................................................                                                                                                               [ 45%]
wodles/aws/tests/test_config.py ..............................................................................                                                                                              [ 57%]
wodles/aws/tests/test_guardduty.py .................                                                                                   [...]

2024-02-09 12:49 UTC, GGP1 requested changes

2024-02-14 12:32 UTC, GGP1 requested changes
The account alias options is being added to the AWS services classes, but I can't find any indication of whether it's being added to the logs like buckets do [here](https://github.com/wazuh/wazuh/blob/076d22b3e3f0f8bed7a5fbeef48cb5199adaed90/wodles/aws/buckets_s3/aws_bucket.py#L325-L329). Please upload evidence that the alias appears in the logs as well.

2024-03-08 12:58 UTC, GGP1 requested changes

2024-03-08 12:58 UTC, GGP1 commented on wodles/aws/services/cloudwatchlogs.py
> +                 iam_role_arn, only_logs_after, account_alias ,region, aws_log_groups,
```suggestion
                 iam_role_arn, only_logs_after, account_alias, region, aws_log_groups,
```

2024-03-08 12:58 UTC, GGP1 commented on wodles/aws/services/cloudwatchlogs.py
> +                                        only_logs_after=only_logs_after, account_alias=account_alias ,region=region,
```suggestion
                                        only_logs_after=only_logs_after, account_alias=account_alias, region=region, 
```

2024-03-08 12:58 UTC, GGP1 commented on wodles/aws/tests/aws_utils.py
> +                               only_logs_after: str = None, account_alias: str = None ,region: str = None, aws_log_groups: str = None,
```suggestion
                               only_logs_after: str = None, account_alias: str = None, region: str = None, aws_log_groups: str = None,
```

2024-03-11 12:23 UTC, GGP1 approved these changes
LGTM

2024-03-12 10:50 UTC, Selutario approved these changes
LGTM. The key point of the `aws_account_alias` is seeing the alias in the alerts to differentiate the origin account in the dashboard easily. However, after reading this you mentioned [here](https://github.com/wazuh/wazuh/issues/15840#issuecomment-1984089965), I do understand that this is not possible for both Cloudwatch and Inspector services. 

I'm merging it for now, but if this is confusing to users in the future, we may choose to remove it from the code again and also (especially) from the [Services documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#service-aws-account-alias).

2024-03-12 10:51 UTC, Selutario commented
The failing checks are unrelated to these changes.

2024-03-12 10:51 UTC, merged