Verify last_update_check response conditionally
wazuh/wazuh pull request #21928
Opened 2024-02-15 14:25 UTC by GGP1

|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/21822 |

## Description

Modifies the function used to validate last update check responses to consider failures because of the CTI service being unavailable for unreleased versions.

2024-02-15 21:30 UTC, EduLeon12 requested changes
Requested small changes for improved readability.

2024-02-15 21:30 UTC, EduLeon12 commented on api/test/integration/tavern_utils.py
> +    """Check that the update check response contains the fields expected and
```suggestion
    """Check that the update check response contains the expected fields, and verify if the 'last_available_*' dictionaries have the correct keys and values.
```
A small suggestion to improve the readability of the method docstring. 
Let me know what you think @GGP1.

2024-02-16 13:39 UTC, EduLeon12 approved these changes

2024-02-16 16:37 UTC, Selutario requested changes
Looks good! It seems that some of the `test_manager_endpoints` are failing though, could you check the reason?
- https://github.com/wazuh/wazuh/pull/21928/checks?check_run_id=21658376272

2024-02-16 17:12 UTC, GGP1 commented
> Looks good! It seems that some of the `test_manager_endpoints` are failing though, could you check the reason?
> 
> * https://github.com/wazuh/wazuh/pull/21928/checks?check_run_id=21658376272

The error shows `TLS/SSL connection has been closed`, that didn't happen when I executed them locally nor on the other runs though.

I've found a [question](https://stackoverflow.com/questions/75273639/caused-by-sslerrorsslzeroreturnerror6-tls-ssl-connection-has-been-closed-eo) in stackeroverflow and an [issue](https://github.com/googleapis/google-auth-library-python/issues/1356) describring this problem, but neither of them seem to be resolved. I think we should investigate it in a separate issue as it's not related to the changes introduced.

2024-02-16 17:28 UTC, Selutario approved these changes
Agree! Please, open it when possible. LGTM.

2024-02-16 17:29 UTC, merged