Integrate HAProxy Helper in the manager
wazuh/wazuh pull request #21947
Opened 2024-02-16 19:29 UTC by nico-stefani

|Related issue|
|---|
| #20938 |

## Description

This PR closes #20938. Integrates the code of the coordinator, apart from the now-called HAProxy Helper, into the Wazuh cluster.

```bash
root@wazuh-master:/var/ossec# framework/python/bin/python3 framework/scripts/wazuh_clusterd.py -f
2024/02/16 19:26:23 DEBUG: [Cluster] [Main] Removing '/var/ossec/queue/cluster/'.
2024/02/16 19:26:23 DEBUG: [Cluster] [Main] Removed '/var/ossec/queue/cluster/'.
wazuh-clusterd: Orphan child process 1269 was terminated.
wazuh-clusterd: Orphan child process 1412 was terminated.
wazuh-clusterd: Orphan child process 1409 was terminated.
Starting cluster in foreground (pid: 2513)
2024/02/16 19:26:23 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2024/02/16 19:26:23 DEBUG: [Local Server] [Keep alive] Calculating.
2024/02/16 19:26:23 DEBUG: [Local Server] [Keep alive] Calculated.
2024/02/16 19:26:23 INFO: [Master] [Main] Serving on ('0.0.0.0', 1516)
2024/02/16 19:26:23 DEBUG: [Master] [Keep alive] Calculating.
2024/02/16 19:26:23 DEBUG: [Master] [Keep alive] Calculated.
2024/02/16 19:26:23 INFO: [Master] [Local integrity] Starting.
2024/02/16 19:26:23 INFO: [Master] [Local agent-groups] Sleeping 30s before starting the agent-groups task, waiting for the workers connection.
2024/02/16 19:26:23 INFO: [Local Server] [HAPHelper Main] Proxy was initialized
2024/02/16 19:26:23 DEBUG2: [Local Server] [HAPHelper Proxy] Obtained proxy backends
2024/02/16 19:26:23 DEBUG2: [Local Server] [HAPHelper Proxy] Obtained proxy frontends
2024/02/16 19:26:23 INFO: [Local Server] [HAPHelper Main] Starting HAProxy Helper
2024/02/16 19:26:23 DEBUG2: [Local Server] [HAPHelper Proxy] Obtained proxy servers
2024/02/16 19:26:23 INFO: [Master] [Local integrity] Finished in 0.092s. Calculated metadata of 34 files.
2024/02/16 19:26:23 DEBUG: [Local 594943] [Main] Connection received in local server.
2024/02/16 19:26:23 DEBUG: [Client master-node] [HAPHelper DAPI] Receiving parameters {}
2024/02/16 19:26:23 DEBUG: [Local Client] [HAPHelper DAPI] Starting to execute request locally
2024/02/16 19:26:23 DEBUG: [Local 594943] [Main] Disconnected 594943.
2024/02/16 19:26:23 DEBUG: [Local 994704] [Main] Connection received in local server.
2024/02/16 19:26:23 DEBUG: [Local 994704] [Main] Disconnected 994704.
2024/02/16 19:26:23 DEBUG: [Local Client] [HAPHelper DAPI] Finished executing request locally
2024/02/16 19:26:23 DEBUG: [Local Client] [HAPHelper DAPI] Time calculating request result: 0.006s
2024/02/16 19:26:23 DEBUG2: [Local Client] [HAPHelper Proxy] Obtained proxy servers
2024/02/16 19:26:23 DEBUG2: [Local Client] [HAPHelper Proxy] Obtained server 'worker2' stats
2024/02/16 19:26:23 DEBUG2: [Local Client] [HAPHelper Main] Server 'worker2' has been disconnected for 43s
2024/02/16 19:26:23 INFO: [Local Client] [HAPHelper Main] Server 'worker2' has not been disconnected enough time to remove it
2024/02/16 19:26:23 INFO: [Local Client] [HAPHelper Main] Load balancer backend is up to date
2024/02/16 19:26:23 DEBUG2: [Local Client] [HAPHelper Proxy] Obtained server 'master-node' stats
2024/02/16 19:26:23 DEBUG2: [Local Client] [HAPHelper Proxy] Obtained server 'worker2' stats
2024/02/16 19:26:23 DEBUG: [Local Client] [HAPHelper Main] Checking for agent balance. Current connections distribution: {'master-node': 1, 'worker2': 1}
2024/02/16 19:26:23 DEBUG: [Local Client] [HAPHelper Main] Current balance is under tolerance
2024/02/16 19:26:23 DEBUG2: [Local Client] [HAPHelper Proxy] Obtained server 'master-node' stats
2024/02/16 19:26:23 DEBUG2: [Local Client] [HAPHelper Proxy] Obtained server 'worker2' stats
2024/02/16 19:26:23 DEBUG: [Local Client] [HAPHelper Main] Current backend stats: {'master-node': 1, 'worker2': 1}
2024/02/16 19:26:23 INFO: [Local Client] [HAPHelper Main] Load balancer backend is balanced
2024/02/16 19:26:23 DEBUG: [Local Client] [HAPHelper Main] Sleeping 60s...
```

2024-02-19 13:29 UTC, fdalmaup requested changes
We should add the corresponding docstrings to the added classes, methods, and functions.

The new `httpx` dependency will be added as part of the Connexion 3.0 upgrade epic in #20795. We should state this to avoid opening issues that may repeat tasks.

2024-02-19 13:29 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/hap_helper.py
> +    # TODO: This must be deprecated
Should this have the `@deprecated` decorator?

2024-02-19 13:29 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/hap_helper.py
> +    # TODO: This must be deprecated
Same as the previous comment.

2024-02-19 13:29 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/wazuh.py
> +class WazuhAPIMethod(Enum):
This class is no longer used since we are directly using the DAPI. It should be removed.

2024-02-19 20:47 UTC, nico-stefani commented on framework/wazuh/core/cluster/hap_helper/exception.py
Done in 3f29036b39c73a3da55bf6ce41964341542e2f74

2024-02-19 20:49 UTC, nico-stefani commented on framework/wazuh/core/cluster/hap_helper/hap_helper.py
> +    # TODO: This must be deprecated
Same for this

2024-02-19 20:54 UTC, nico-stefani commented
> We should add the corresponding docstrings to the added classes, methods, and functions.
> 
> The new `httpx` dependency will be added as part of the Connexion 3.0 upgrade epic in #20795. We should state this to avoid opening issues that may repeat tasks.

Added docstrings in 1f3b2aebaa7278ffbe2a0c2e8a6ad61415609a13. 
Please, disregard the methods with the TODO mark and all the functions in the `configurations.py` that will be removed in the future.

2024-02-20 14:39 UTC, fdalmaup requested changes

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +            Data to send within the request, by default None
```suggestion
        method : ProxyAPIMethod, optional
            Method to use, by default ProxyAPIMethod.GET.
        query_parameters : dict | None, optional
            Query parameters to send in the request, by default None.
        json_body : dict | None, optional
            Data to send within the request, by default None.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +            Load balancing algorithm to use, by default ProxyBalanceAlgorithm.LEAST_CONNECTIONS
```suggestion
        mode : CommunicationProtocol, optional
            Protocol to use, by default CommunicationProtocol.TCP.
        algorithm : ProxyBalanceAlgorithm, optional
            Load balancing algorithm to use, by default ProxyBalanceAlgorithm.LEAST_CONNECTIONS.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +            Communication protocol to use, by default CommunicationProtocol.TCP
```suggestion
            Communication protocol to use, by default CommunicationProtocol.TCP.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Returns the runtime information of the HAProxy instance.
```suggestion
        """Get the runtime information of the HAProxy instance.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Returns the configured backends.
```suggestion
        """Get the configured backends.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Returns the servers for the provided backend.
```suggestion
        """Get the servers for the provided backend.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Returns the configured logger.
```suggestion
        """Get the configured logger.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Returns the current HAProxy PID
```suggestion
        """Get the current HAProxy PID.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Returns current backends from the Proxy.
```suggestion
        """Get the current backends from the Proxy.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Checks if the provided backend exists.
```suggestion
        """Check if the provided backend exists.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Returns current frontends from the Proxy.
```suggestion
        """Get the current frontends from the Proxy.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Checks if the provided frontend exists.
```suggestion
        """Check if the provided frontend exists.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Adds new backend to the Proxy.
```suggestion
        """Add a new backend to the Proxy.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +            Load balancing algorithm to use, by default ProxyBalanceAlgorithm.LEAST_CONNECTIONS
```suggestion
            Communication protocol to use, by default CommunicationProtocol.TCP.
        algorithm : ProxyBalanceAlgorithm, optional
            Load balancing algorithm to use, by default ProxyBalanceAlgorithm.LEAST_CONNECTIONS.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Adds new frontend to the Proxy.
```suggestion
        """Add a new frontend to the Proxy.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +            Communication protocol to use, by default CommunicationProtocol.TCP
```suggestion
            Communication protocol to use, by default CommunicationProtocol.TCP.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Returns current backend servers from the Proxy.
```suggestion
        """Get the current backend servers from the Proxy.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Adds new Wazuh manager to the Proxy.
```suggestion
        """Add a new Wazuh manager to the Proxy.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Deletes the given Wazuh manager from the Proxy.
```suggestion
        """Delete the given Wazuh manager from the Proxy.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +            The server name to query
```suggestion
        """Get the statistics of the given server.

        Parameters
        ----------
        server_name : str
            The server name to query.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Checks if the server is in DRAIN state.
```suggestion
        """Check if the server is in DRAIN state.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +            Only include running servers, by default True
```suggestion
        """Get the statistics of the Wazuh backend.

        Parameters
        ----------
        only_actives : bool, optional
            Only include running servers, by default True.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/proxy.py
> +        """Returns the active connections of the Wazuh backend server.
```suggestion
        """Get the active connections of the Wazuh backend server.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/wazuh.py
> +    """Tools for handle Wazuh agents connections."""
```suggestion
    """Tools to handle Wazuh agents connections."""
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/wazuh.py
> +    """Class for call Wazuh DAPI functions."""
```suggestion
    """Class to call Wazuh DAPI functions."""
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/wazuh.py
> +        """Returns the configured logger.
```suggestion
        """Get the configured logger.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/wazuh.py
> +             Arguments to be passed to function `f`, by default None
```suggestion
             Arguments to be passed to function `f`, by default None.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/wazuh.py
> +            The agents to be re-connected, by default None
```suggestion
        """Make an API call to reconnect agents.

        Parameters
        ----------
        agent_list : list, optional
            The agents to be re-connected, by default None.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/cluster/hap_helper/wazuh.py
> +            Max number of agents to retrieve, by default None
```suggestion
            Max number of agents to retrieve, by default None.
```

2024-02-20 14:39 UTC, fdalmaup commented on framework/wazuh/core/exception.py
> +        3041: "Server status check timed out after adding new servers",
We could add a comment like the one below for `RBAC` to describe that this set of codes is for `HAProxy Helper` exceptions.

2024-02-21 12:24 UTC, fdalmaup approved these changes
LGTM!

2024-02-23 17:35 UTC, Selutario requested changes
This looks really good! There are parts that I have not yet been able to review in-depth, so I will only comment on a few things in this first review:

### Log tags

In the logs you showed in the [PR description](https://github.com/wazuh/wazuh/pull/21947#issue-2139288169), HAProxy is a subtag of other tasks (like Local Server, Local Client, etc.). In my opinion, in the future it would be easier to debug the logs if everything related to HAProxy helper appears with the tag `HAPHelper`, and what now accompanies `HAPHelper`, be the subtag (`DAPI`, `Main `, `Proxy`).

It would be something like this:
```LOG
root@wazuh-master:/var/ossec# framework/python/bin/python3 framework/scripts/wazuh_clusterd.py -f
2024/02/16 19:26:23 DEBUG: [Cluster] [Main] Removing '/var/ossec/queue/cluster/'.
2024/02/16 19:26:23 DEBUG: [Cluster] [Main] Removed '/var/ossec/queue/cluster/'.
wazuh-clusterd: Orphan child process 1269 was terminated.
wazuh-clusterd: Orphan child process 1412 was terminated.
wazuh-clusterd: Orphan child process 1409 was terminated.
Starting cluster in foreground (pid: 2513)
2024/02/16 19:26:23 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2024/02/16 19:26:23 DEBUG: [Local Server] [Keep alive] Calculating.
2024/02/16 19:26:23 DEBUG: [Local Server] [Keep alive] Calculated.
2024/02/16 19:26:23 INFO: [Master] [Main] Serving on ('0.0.0.0', 1516)
2024/02/16 19:26:23 DEBUG: [Master] [Keep alive] Calculating.
2024/02/16 19:26:23 DEBUG: [Master] [Keep alive] Calculated.
2024/02/16 19:26:23 INFO: [Master] [Local integrity] Starting.
2024/02/16 19:26:23 INFO: [Master] [Local agent-groups] Sleeping 30s before starting the agent-groups task, waiting for the workers connection.
2024/02/16 19:26:23 INFO: [HAPHelper] [Main] Proxy was initialized
2024/02/16 19:26:23 DEBUG2: [HAPHelper] [Proxy] Obtained proxy backends
2024/02/16 19:26:23 DEBUG2: [HAPHelper] [Proxy] Obtained proxy frontends
2024/02/16 19:26:23 INFO: [HAPHelper] [Main] Starting HAProxy Helper
2024/02/16 19:26:23 DEBUG2: [HAPHelper] [Proxy] Obtained proxy servers
2024/02/16 19:26:23 INFO: [Master] [Local integrity] Finished in 0.092s. Calculated metadata of 34 files.
2024/02/16 19:26:23 DEBUG: [Local 594943] [Main] Connection received in local server.
2024/02/16 19:26:23 DEBUG: [HAPHelper] [DAPI] Receiving parameters {}
2024/02/16 19:26:23 DEBUG: [HAPHelper] [DAPI] Starting to execute request locally
2024/02/16 19:26:23 DEBUG: [Local 594943] [Main] Disconnected 594943.
2024/02/16 19:26:23 DEBUG: [Local 994704] [Main] Connection received in local server.
2024/02/16 19:26:23 DEBUG: [Local 994704] [Main] Disconnected 994704.
2024/02/16 19:26:23 DEBUG: [HAPHelper] [DAPI] Finished executing request locally
2024/02/16 19:26:23 DEBUG: [HAPHelper] [DAPI] Time calculating request result: 0.006s
2024/02/16 19:26:23 DEBUG2: [HAPHelper] [Proxy] Obtained proxy servers
2024/02/16 19:26:23 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker2' stats
2024/02/16 19:26:23 DEBUG2: [HAPHelper] [Main] Server 'worker2' has been disconnected for 43s
2024/02/16 19:26:23 INFO: [HAPHelper] [Main] Server 'worker2' has not been disconnected enough time to remove it
2024/02/16 19:26:23 INFO: [HAPHelper] [Main] Load balancer backend is up to date
2024/02/16 19:26:23 DEBUG2: [HAPHelper] [Proxy] Obtained server 'master-node' stats
2024/02/16 19:26:23 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker2' stats
2024/02/16 19:26:23 DEBUG: [HAPHelper] [Main] Checking for agent balance. Current connections distribution: {'master-node': 1, 'worker2': 1}
2024/02/16 19:26:23 DEBUG: [HAPHelper] [Main] Current balance is under tolerance
2024/02/16 19:26:23 DEBUG2: [HAPHelper] [Proxy] Obtained server 'master-node' stats
2024/02/16 19:26:23 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker2' stats
2024/02/16 19:26:23 DEBUG: [HAPHelper] [Main] Current backend stats: {'master-node': 1, 'worker2': 1}
2024/02/16 19:26:23 INFO: [HAPHelper] [Main] Load balancer backend is balanced
2024/02/16 19:26:23 DEBUG: [HAPHelper] [Main] Sleeping 60s...
```

Setting tags and subtags is trickier than it may seem since there are many different contexts due to coroutines. I'm not even sure if it's possible to achieve what I'm proposing. In any case, what is your opinion on this? Would you change anything?

2024-02-27 20:10 UTC, nico-stefani commented
After doing the changes the HAProxy helper logs look like:

```
2024/02/27 19:49:08 DEBUG2: [HAPHelper] [Proxy] Obtained proxy servers
2024/02/27 19:49:08 DEBUG: [HAPHelper] [DAPI] Receiving parameters {}
2024/02/27 19:49:08 DEBUG2: [HAPHelper] [Proxy] Obtained proxy servers
2024/02/27 19:49:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker3' stats
2024/02/27 19:49:08 DEBUG2: [HAPHelper] [Main] Server 'worker3' has been disconnected for 2s
2024/02/27 19:49:08 INFO: [HAPHelper] [Main] Server 'worker3' has not been disconnected enough time to remove it
2024/02/27 19:49:08 INFO: [HAPHelper] [Main] Load balancer backend is up to date
2024/02/27 19:49:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'master-node' stats
2024/02/27 19:49:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker2' stats
2024/02/27 19:49:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker3' stats
2024/02/27 19:49:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker1' stats
2024/02/27 19:49:08 DEBUG: [HAPHelper] [Main] Checking for agent balance. Current connections distribution: {'master-node': 4, 'worker2': 4, 'worker1': 4}
2024/02/27 19:49:08 DEBUG: [HAPHelper] [Main] Current balance is under tolerance
2024/02/27 19:49:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'master-node' stats
2024/02/27 19:49:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker2' stats
2024/02/27 19:49:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker3' stats
2024/02/27 19:49:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker1' stats
2024/02/27 19:49:08 DEBUG: [HAPHelper] [Main] Current backend stats: {'master-node': 4, 'worker2': 4, 'worker1': 4}
2024/02/27 19:49:08 INFO: [HAPHelper] [Main] Load balancer backend is balanced
2024/02/27 19:49:08 DEBUG: [HAPHelper] [Main] Sleeping 60s...
2024/02/27 19:50:08 DEBUG2: [HAPHelper] [Proxy] Obtained proxy servers
2024/02/27 19:50:08 DEBUG: [HAPHelper] [DAPI] Receiving parameters {}
2024/02/27 19:50:08 DEBUG2: [HAPHelper] [Proxy] Obtained proxy servers
2024/02/27 19:50:08 INFO: [HAPHelper] [Main] Load balancer backend is up to date
2024/02/27 19:50:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'master-node' stats
2024/02/27 19:50:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker2' stats
2024/02/27 19:50:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker3' stats
2024/02/27 19:50:08 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker1' stats
2024/02/27 19:50:08 DEBUG: [HAPHelper] [Main] Checking for agent balance. Current connections distribution: {'master-node': 4, 'worker2': 4, 'worker3': 0, 'worker1': 4}
2024/02/27 19:50:08 INFO: [HAPHelper] [Main] Agent imbalance detected. Waiting for agent status sync...
2024/02/27 19:50:33 INFO: [HAPHelper] [Main] Attempting to balance agent connections
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Receiving parameters {'select': ['version'], 'sort': {'fields': ['version', 'id'], 'order': 'desc'}, 'filters': {'status': 'active', 'node_name': 'master-node'}, 'q': 'id!=000', 'limit': 1}
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Starting to execute request locally
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Finished executing request locally
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Time calculating request result: 0.005s
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Receiving parameters {'select': ['version'], 'sort': {'fields': ['version', 'id'], 'order': 'desc'}, 'filters': {'status': 'active', 'node_name': 'worker2'}, 'q': 'id!=000', 'limit': 1}
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Starting to execute request locally
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Finished executing request locally
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Time calculating request result: 0.005s
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Receiving parameters {'select': ['version'], 'sort': {'fields': ['version', 'id'], 'order': 'desc'}, 'filters': {'status': 'active', 'node_name': 'worker1'}, 'q': 'id!=000', 'limit': 1}
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Starting to execute request locally
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Finished executing request locally
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Time calculating request result: 0.005s
2024/02/27 19:50:33 INFO: [HAPHelper] [Main] Balancing 1 agents from 'master-node'
2024/02/27 19:50:33 DEBUG: [HAPHelper] [Main] Reconnecting agents
2024/02/27 19:50:33 DEBUG: [HAPHelper] [Main] Agent reconnection chunk size is set to 120. Total iterations: 1
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Receiving parameters {'agent_list': ['010']}
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Receiving parameters {'agent_list': ['010']}
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Starting to execute request locally
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Finished executing request locally
2024/02/27 19:50:33 DEBUG: [HAPHelper] [DAPI] Time calculating request result: 0.004s
2024/02/27 19:50:33 DEBUG: [HAPHelper] [Main] Delay between agent reconnections. Sleeping 5s...
2024/02/27 19:50:38 INFO: [HAPHelper] [Main] Balancing 1 agents from 'worker2'
2024/02/27 19:50:38 DEBUG: [HAPHelper] [Main] Reconnecting agents
2024/02/27 19:50:38 DEBUG: [HAPHelper] [Main] Agent reconnection chunk size is set to 120. Total iterations: 1
2024/02/27 19:50:38 DEBUG: [HAPHelper] [DAPI] Receiving parameters {'agent_list': ['013']}
2024/02/27 19:50:38 DEBUG: [HAPHelper] [Main] Delay between agent reconnections. Sleeping 5s...
2024/02/27 19:50:43 INFO: [HAPHelper] [Main] Balancing 1 agents from 'worker1'
2024/02/27 19:50:43 DEBUG: [HAPHelper] [Main] Reconnecting agents
2024/02/27 19:50:43 DEBUG: [HAPHelper] [Main] Agent reconnection chunk size is set to 120. Total iterations: 1
2024/02/27 19:50:43 DEBUG: [HAPHelper] [DAPI] Receiving parameters {'agent_list': ['012']}
2024/02/27 19:50:43 DEBUG: [HAPHelper] [Main] Delay between agent reconnections. Sleeping 5s...
2024/02/27 19:50:48 DEBUG: [HAPHelper] [Main] Sleeping 60s...
```

2024-03-01 12:10 UTC, Selutario requested changes
Rebasing with the current status of the epic branch will be required too.

2024-03-06 17:19 UTC, Selutario approved these changes
Looks good to me!

2024-03-06 17:19 UTC, merged