Add scenaries for Catalog and fix bugs
wazuh/wazuh pull request #22142
Opened 2024-02-26 16:55 UTC by NahuFigueroa97

|Related issue|
|---|
|#21986|

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2024-02-29 15:49 UTC, JavierBejMen requested changes

2024-02-29 15:49 UTC, JavierBejMen commented on src/engine/source/api/src/catalog/catalog.cpp
> +    return std::nullopt;
use base::noError() instead of optional details

2024-02-29 15:49 UTC, JavierBejMen commented on src/engine/source/api/test/src/unit/catalog/catalog_test.cpp
> +    if (isSuccess)
Why if it succeeded an error should be returned?

2024-03-01 14:21 UTC, juliancnn approved these changes
LGTM!

2024-03-04 09:43 UTC, JcabreraC approved these changes
LGTM !

2024-03-04 09:43 UTC, merged