Enhancement Parse Date for support format name
wazuh/wazuh pull request #22203
Opened 2024-02-28 15:22 UTC by NahuFigueroa97

|Related issue|
|---|
|#22143|

## Description

2024-03-05 14:54 UTC, juliancnn requested changes

2024-03-05 14:54 UTC, juliancnn commented on src/engine/source/cmds/src/start.cpp
> +
This block is part of the engine initialization, it should be inside the try, just before or inside the HLP initialization, and it should throw a runtime_exception describing the error without the return.

2024-03-05 14:54 UTC, juliancnn commented on src/engine/source/hlp/src/parsers/date.cpp
> +    {"UnixDate", "%a %b %d %T %Z %Y"},  // Mon Jan 2 15:04:05 MST 2006
Do not delete the `_`, this marks the optional., %d is the day of the month as a decimal number. The modified command %Nd where N is a positive decimal integer specifies the maximum number of characters to read. If not specified, the default is 2. Leading zeroes are permitted but not required.

2024-03-06 21:30 UTC, juliancnn approved these changes
LGTM!

2024-03-07 08:59 UTC, JcabreraC approved these changes
LGTM !

2024-03-07 08:59 UTC, merged