Remove uvicorn server header from response
wazuh/wazuh pull request #22373
Opened 2024-03-05 19:59 UTC by nico-stefani

|Related issue|
|---|
| #22329 |

## Description

This PR closes #22329. Removes the `server: uvicorn` header from response.

## Logs/Alerts example

### Before the change

```bash
curl -i --silent -u wazuh:wazuh -k -X GET "https://localhost:55050/security/user/authenticate?raw=true"
HTTP/1.1 200 OK
date: Tue, 05 Mar 2024 19:58:24 GMT
server: uvicorn
content-type: text/plain
deprecated: true
link: <https://documentation.wazuh.com/4.9.0/user-manual/api/reference.html#operation/api.controllers.security_controller.login_user>; rel="Deprecated"
content-length: 398
server: Wazuh
strict-transport-security: max-age=63072000; includeSubdomains
x-frame-options: deny
x-xss-protection: 0
x-content-type-options: nosniff
content-security-policy: none
referrer-policy: no-referrer, strict-origin-when-cross-origin
cache-control: no-store
```

### After the change

```bash
curl -i --silent -u wazuh:wazuh -k -X GET "https://localhost:55050/security/user/authenticate?raw=true"
HTTP/1.1 200 OK
date: Tue, 05 Mar 2024 19:49:56 GMT
content-type: text/plain
deprecated: true
link: <https://documentation.wazuh.com/4.9.0/user-manual/api/reference.html#operation/api.controllers.security_controller.login_user>; rel="Deprecated"
content-length: 398
server: Wazuh
strict-transport-security: max-age=63072000; includeSubdomains
x-frame-options: deny
x-xss-protection: 0
x-content-type-options: nosniff
content-security-policy: none
referrer-policy: no-referrer, strict-origin-when-cross-origin
cache-control: no-store
```

2024-03-05 20:11 UTC, nico-stefani commented
The integration tests are failing because we still don't have the CPython with the required dependencies.

2024-03-05 20:21 UTC, fdalmaup approved these changes
LGTM!

2024-03-08 11:51 UTC, Selutario approved these changes

2024-03-08 11:52 UTC, Selutario requested changes
It will be needed to resolve the conflict before merging.

2024-03-08 14:36 UTC, merged