22080 migrate and adapt the wazuh agent subsystem
wazuh/wazuh pull request #22396
Opened 2024-03-07 01:04 UTC by lchico

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/22080|

## Description
As the main task of this PR is to move all required components from the wazuh-package repository to be able to generate RPM, DEB, ZIP, and PKG packages for the agent, the following steps were taken:

- Moved the wazuh-agent specs from the wazuh-packages repository to the wazuh repository.
- Unified the build scripts for DEB and RPM packages.
  - Utilized a helper function to define specific behavior for the generation of each package.
- Also unified the generate_package.sh script.
  - Defined the following environment variables:
    + `BUILD_TARGET`
    + `ARCHITECTURE_TARGET`
    + `PACKAGE_FORMAT`
    + `INSTALLATION_PATH`
- Used the sources flag to specify that the specs and source code will be taken from the wazuh-local-src directory.
- Update the package name to adhere to [this naming convention](https://github.com/wazuh/wazuh/issues/21755#:~:text=As%20subsystem%20owners%2C%20teams%20must%20follow%20this%20naming%20convention%20for%20development%20package%20names%3A%20%3CSubsystemName%3E_%3CVersionNumber%3E%2D%3CRevision%3E_%7B%3COSName%3E%2D%3COSVersion%3E_%7D%3CArchitecture%3E_%3CGitReference%3E.%3CPackageType%3E.) for development package names:
```
 <SubsystemName>_<VersionNumber>-<Revision>_{<OSName>-<OSVersion>_}<Architecture>_<GitReference>.<PackageType>.
```

## Configuration options
To generate a DEB/RPM package for wazuh-agent:

```
git clone --branch 22080-migrate-and-adapt-the-wazuh-agent-subsystem https://github.com/wazuh/wazuh.git
cd wazuh/packages
./generate_package.sh -b 22080-migrate-and-adapt-the-wazuh-agent-subsystem -s /tmp -t agent -a [amd64/x86_64/i386/arm64] -r [revision] --package-format [deb/rpm] 
```

## Logs/Alerts example

# Deb
```
 ./generate_package.sh -b 22080-migrate-and-adapt-the-wazuh-agent-subsystem -s /tmp -t agent -a amd64 -r test --package-format deb 
 ./generate_package.sh -b 22080-migrate-and-adapt-the-wazuh-agent-subsystem -s /tmp -t agent -a amd64 -r test --package-format deb  --future
 ./generate_package.sh -b 22080-migrate-and-adapt-the-wazuh-agent-subsystem -s /tmp -t agent -a i386 -r test --package-format deb 
 ./generate_package.sh -b 22080-migrate-and-adapt-the-wazuh-agent-subsystem -s /tmp -t agent -a i386 -r test --package-format deb  --future
```

# RPM
```
 ./generate_package.sh -b 22080-migrate-and-adapt-the-wazuh-agent-subsystem -s /tmp -t agent -a x86_64 -r test --package-format rpm 
 ./generate_package.sh -b 22080-migrate-and-adapt-the-wazuh-agent-subsystem -s /tmp -t agent -a x86_64 -r test --package-format rpm --future
 ./generate_package.sh -b 22080-migrate-and-adapt-the-wazuh-agent-subsystem -s /tmp -t agent -a i386 -r test --package-format rpm 
 ./generate_package.sh -b 22080-migrate-and-adapt-the-wazuh-agent-subsystem -s /tmp -t agent -a i386 -r test --package-format rpm  --future
 ./generate_package.sh -b 22080-migrate-and-adapt-the-wazuh-agent-subsystem -s /tmp -t agent -a i386 -r test --package-format rpm  --legacy
 ./generate_package.sh -b 22080-migrate-and-adapt-the-wazuh-agent-subsystem -s /tmp -t agent -a i386 -r test --package-format rpm  --legacy --future
```

Packages generated locally, commit https://github.com/wazuh/wazuh/commit/c6e7702719404ac019e3d3d929f0367d600e4ebd

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2024-04-09 10:40 UTC, jotacarma90 requested changes

2024-04-09 10:40 UTC, jotacarma90 commented on .github/workflows/rtr_syscheck.yml
> -      - ".github/actions/**"
We should remove this changes, or at least improve the filtering of these workflows.

2024-04-09 10:40 UTC, jotacarma90 commented on packages/debs/SPECS/wazuh-agent/debian/conffiles
Is this file needed?

2024-04-09 10:40 UTC, jotacarma90 commented on packages/macos/entitlements.plist
> +</plist>
Add new line at the end of file

2024-04-09 10:40 UTC, jotacarma90 commented on packages/macos/generate_wazuh_packages.sh
> +INSTALLATION_PATH="/Library/Ossec"    # Installation path
```suggestion
INSTALLATION_PATH="/Library/Ossec"    # Installation path.
```

2024-04-09 10:40 UTC, jotacarma90 commented on packages/macos/generate_wazuh_packages.sh
> +VERSION=""                            # Default VERSION (branch/tag)
```suggestion
VERSION=""                            # Default VERSION (branch/tag).
```

2024-04-09 10:40 UTC, jotacarma90 commented on packages/macos/generate_wazuh_packages.sh
> +IS_STAGE="no"                         # Enables release package naming,
```suggestion
IS_STAGE="no"                         # Enables release package naming.
```

2024-04-09 10:40 UTC, jotacarma90 commented on packages/macos/package_files/preinstall.sh
> +dscl . create /Users/wazuh IsHidden 1
Add new line at the end of file

2024-04-09 10:40 UTC, jotacarma90 commented on packages/rpms/amd64/agent/CentOS-Base.repo
> +gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
New line

2024-04-09 10:40 UTC, jotacarma90 commented on packages/rpms/amd64/legacy/CentOS-Base.repo
> +gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5
New line

2024-04-09 10:40 UTC, jotacarma90 commented on packages/rpms/i386/agent/CentOS-Base.repo
> +gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
New line

2024-04-09 10:40 UTC, jotacarma90 commented on packages/rpms/i386/legacy/CentOS-Base.repo
> +gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5
New line

2024-04-09 13:21 UTC, lchico commented on packages/debs/SPECS/wazuh-agent/debian/conffiles
While not mandatory, using debian/conffiles is considered a good practice for Debian package development. It enhances user experience by providing control over configuration changes during package installation and upgrades.

2024-04-09 22:31 UTC, lchico commented
@jotacarma90 Thank you for your comments. All of them have been addressed. When you have a moment, PTAL. Thank you!

2024-04-11 11:38 UTC, mjcr99 requested changes
Amazing job @lchico! 
Just a comment, the upload images workflows should be discussed with the team.

2024-04-26 08:48 UTC, mjcr99 approved these changes
LGTM

2024-04-26 11:02 UTC, jotacarma90 approved these changes
LGTM

2024-04-26 12:19 UTC, MarcelKemp approved these changes
LGTM.

2024-04-26 12:20 UTC, merged