Updated README of the AITs with the new parameters
wazuh/wazuh pull request #22458
Opened 2024-03-12 11:32 UTC by javiersanchz

|Related issue|
|---|
| #21740  |

## Description

The parameters that were added in `conftest.py` were included in the AITs `README`.
Added parameters:
- `--disable-warnings`
- `--build-managers-only` --> https://github.com/wazuh/wazuh/pull/21924
- `--nobuild` --> https://github.com/wazuh/wazuh/pull/17750

2024-03-12 14:43 UTC, GGP1 approved these changes
LGTM

2024-03-15 12:06 UTC, Selutario requested changes
Looks good. Just a small typo:

2024-03-15 12:06 UTC, Selutario commented on api/test/integration/README.md
> +                  Recreates only the managers images once the AIT test environment is built.
```suggestion
                  Recreates only the managers' image once the AIT test environment is built.
```

2024-03-15 17:06 UTC, Selutario approved these changes

2024-03-15 17:06 UTC, merged