Make cluster commands asynchronous
wazuh/wazuh pull request #22640
Opened 2024-03-22 19:03 UTC by GGP1

|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/21862 |

## Description

Makes the  `Sendsync`, `Agent-info sync`, `Agent-groups recv`, `Agent-groups recv full` cluster commands asynchronous.

## Logs/Alerts example

Logs can be found [here](https://github.com/wazuh/wazuh/issues/21862#issuecomment-2013376134) and [here](https://github.com/wazuh/wazuh/issues/21862#issuecomment-2015514131).

2024-03-25 13:45 UTC, fdalmaup requested changes
Changes look good and the manual tests do not seem to have issues. Nevertheless, we should run [related system](https://github.com/wazuh/wazuh-qa/tree/master/tests/system/test_cluster) and [cluster performance](https://github.com/wazuh/wazuh-qa/tree/master/tests/performance/test_cluster) tests as part of the verification process.

2024-04-03 19:59 UTC, fdalmaup approved these changes
LGTM! The required tests were run [here](https://github.com/wazuh/wazuh/issues/21862#issuecomment-2034832186).

2024-04-04 10:21 UTC, Selutario commented
It has been decided not to publish a 4.8.2 patch for now. I'm moving this issue to on hold for it to be rebased to 4.9.0.

2024-04-05 12:05 UTC, Selutario requested changes
It seems we will need to update the cluster documentation too, now multiprocessing is used in less places:
- https://documentation.wazuh.com/current/development/wazuh-cluster.html#multiprocessing

2024-04-05 16:38 UTC, GGP1 commented on framework/wazuh/core/cluster/common.py
> +            result = await send_data_to_wdb(data, timeout, info_type)
I agree, since it will execute asynchronously from now on I think we can get rid of the timeout.

2024-04-08 09:41 UTC, Selutario approved these changes
LGTM, nice job @GGP1. These changes affect key parts of the cluster, we will have to pay special attention during the release testing to detect any strange behavior that we may be overlooking now.

2024-04-08 09:41 UTC, merged