Improving indexer connector log messages
wazuh/wazuh pull request #22682
Opened 2024-03-27 15:15 UTC by pereyra-m

|Related issue|
|---|
|Closes #22532|

## Description

This PR improves the messages shown to the user when the indexer connector finds an error.
Also, some callbacks were re-organized.

2024-03-27 17:08 UTC, sebasfalcone submitted a review, later dismissed
LGTM

2024-03-27 17:10 UTC, GabrielEValenzuela submitted a review, later dismissed
Great job Mati!

2024-03-28 04:29 UTC, pereyra-m commented
The failure of the test https://github.com/wazuh/wazuh/actions/runs/8454182489/job/23158814102?pr=22682 doesn't seem related to the changes in the PR

2024-03-30 19:24 UTC, Dwordcito requested changes

2024-03-30 19:24 UTC, Dwordcito commented on src/shared_modules/indexer_connector/src/indexerConnector.cpp
> +                            "Unable to initializing IndexerConnector for index '%s': %s. Retrying in %ld "
This message should not be perpetual (printed every 30 seconds non-stop).

At the Warning level, we should only print it once informing that we are going to retry continuously until successful (which has to print a non-technical log ex: Initialized with success.)

The perpetual message can be at the DEBUG level, in terms of analyzing the case.

2024-04-03 18:21 UTC, Dwordcito approved these changes

2024-04-03 18:22 UTC, merged