Migrate and adapt macos wazuh agent packages subsystem
wazuh/wazuh pull request #22707
Opened 2024-04-02 11:19 UTC by mjcr99

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/22080|

## Description
As the main task of this PR is to move all required components from the wazuh-package repository to be able to generate RPM, DEB, ZIP, and PKG packages for the agent, the following steps were taken:

- Moved the wazuh-agent specs from the wazuh-packages repository to the wazuh repository.
- Improved the generate_wazuh_package.sh script.
- Added workflow for Macos package generation. 
- Used the sources `branch` to specify that the specs and source code will be taken from the downloaded branch.
- 
- Update the package name to adhere to [this naming convention](https://github.com/wazuh/wazuh/issues/21755#:~:text=As%20subsystem%20owners%2C%20teams%20must%20follow%20this%20naming%20convention%20for%20development%20package%20names%3A%20%3CSubsystemName%3E_%3CVersionNumber%3E%2D%3CRevision%3E_%7B%3COSName%3E%2D%3COSVersion%3E_%7D%3CArchitecture%3E_%3CGitReference%3E.%3CPackageType%3E.) for development package names:
```
 <SubsystemName>_<VersionNumber>-<Revision>_{<OSName>-<OSVersion>_}<Architecture>_<GitReference>.<PackageType>.
```

## Generate package
To generate a DEB/RPM package for wazuh-agent:

```
git clone --branch 22080-migrate-and-adapt-macos-wazuh-agent-subsystem-1
https://github.com/wazuh/wazuh.git
cd wazuh/packages/macos

./generate_wazuh_package.sh -s /tmp  -a [arch] -r [revision]  
```

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [x] MAC OS X

2024-04-04 23:59 UTC, lchico approved these changes
I left some minor comments in the code. Feel free to ignore them.

2024-04-04 23:59 UTC, lchico commented on .github/workflows/packages-build-macos-agent.yml
> +        default: false
These lines can be safely removed as they are already set to false by default. Leaving a comment explaining this (as you've done) is sufficient.

2024-04-04 23:59 UTC, lchico commented on .github/workflows/packages-build-macos-agent.yml
> +          if [ $(sudo /Library/Ossec/bin/wazuh-control status | grep 'is running...' | wc -l) -gt "0" ];
```suggestion
          if [ $(sudo /Library/Ossec/bin/wazuh-control status | grep 'is running...' | wc -l) -gt 5 ];
```
So, we validate that all services are running:

```
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
```

2024-04-04 23:59 UTC, lchico commented on packages/macos/generate_wazuh_packages.sh
> +                | grep '"sha"' | head -n 1| cut -d '"' -f 4 | cut -c 1-11)"
Could you check if this works:
```suggestion
short_commit_hash=$(git rev-parse -C "${WAZUH_PATH}" --short HEAD)
```

2024-04-04 23:59 UTC, lchico commented on packages/macos/package_files/build.sh
> +DEBUG_ENABLED=$4
Could we just use DEBUG? It seems like it's always the same flag, and the current name is a bit confusing.

2024-04-05 00:35 UTC, lchico requested changes
Looks great! To improve validation, let's add checks for the CUSTOM_CODE_VOL path.

2024-04-05 00:39 UTC, lchico approved these changes

2024-04-05 12:12 UTC, MarcelKemp requested changes
GJ, just a few minor changes.

2024-04-05 12:12 UTC, MarcelKemp commented on .github/workflows/packages-build-macos-agent.yml
> +  Build-agent-linux-packages:
```suggestion
  build-agent-macos-packages:
```

2024-04-05 12:12 UTC, MarcelKemp commented on .github/workflows/packages-build-macos-agent.yml
> +name: Build Macos Wazuh Agent Packages - intel64|arm64
```suggestion
name: Build macOS Wazuh Agent Packages - intel64|arm64
```

2024-04-05 12:12 UTC, MarcelKemp commented on .github/workflows/packages-build-macos-agent.yml
> +    name: Build MacOS wazuh-agent on ${{ inputs.architecture }}
```suggestion
    name: Build macOS wazuh-agent on ${{ inputs.architecture }}
```

2024-04-05 12:18 UTC, jotacarma90 commented on .github/workflows/packages-build-macos-agent.yml
> +  Build-agent-linux-packages:
done

2024-04-05 12:18 UTC, jotacarma90 commented on .github/workflows/packages-build-macos-agent.yml
> +name: Build Macos Wazuh Agent Packages - intel64|arm64
done

2024-04-05 12:18 UTC, jotacarma90 commented on .github/workflows/packages-build-macos-agent.yml
> +  Build-agent-linux-packages:
done

2024-04-05 12:19 UTC, jotacarma90 commented on packages/macos/generate_wazuh_packages.sh
> +                | grep '"sha"' | head -n 1| cut -d '"' -f 4 | cut -c 1-11)"
done

2024-04-05 12:35 UTC, MarcelKemp approved these changes

2024-04-05 12:46 UTC, jotacarma90 commented
## Builds successfully with different params

🟢 https://github.com/wazuh/wazuh/actions/runs/8569902622
🟢 https://github.com/wazuh/wazuh/actions/runs/8569904263
🟢 https://github.com/wazuh/wazuh/actions/runs/8569907318

2024-04-05 14:13 UTC, merged