Change the default database synchronous configuration
wazuh/wazuh pull request #22774
Opened 2024-04-05 14:44 UTC by nmkoremblum

|Related issue|
|---|
|#22753|

## Description

Wazuh database synchronous mode has been changed to "1" (NORMAL) programmatically, as the configuration does not persist through sessions.

- Compilation without warnings in every supported platform
  - [X] Linux
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

2024-04-05 15:48 UTC, cborla commented on src/wazuh_db/wdb.c
> +    [WDB_STMT_PRAGMA_SYNCHRONOUS_1] = "PRAGMA synchronous = 1;",
We should keep the format similar to the other configurations, eliminating the spaces between the = and the value.
`[WDB_STMT_PRAGMA_SYNCHRONOUS_1] = "PRAGMA synchronous=1;",`

2024-04-05 15:49 UTC, cborla approved these changes
LGTM

2024-04-05 21:46 UTC, cborla commented
## Branches 4.8.0 vs 22753-change-db-synchronous-mode

### Branch  22753-change-db-synchronous-mode

``` console
wdb-query2.py global "sql PRAGMA synchronous"
[
    {
        "synchronous": 1
    }
]


cat /var/ossec/etc/client.keys | wc -l
50000

TOKEN=$(curl -u wazuh:wazuh -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")

curl -k -X POST "https://localhost:55000/groups" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d '{"group_id": "test_group10"}'

time curl -k -X PUT "https://localhost:55000/agents/group?wait_for_complete=true&group_id=test_group10" -H  "Authorization: Bearer $TOKEN"
{"data": {"affected_items": ["001",.... "50000", "50001"], "total_affected_items": 50001, "total_failed_items": 0, "failed_items": []}, "message": "All selected agents were assigned to test_group10", "error": 0}
real  7m49,405s
user  0m0,037s
sys 0m0,027s
```

### Branch 4.8.0

``` console
wdb-query2.py global "sql PRAGMA synchronous"
[
    {
        "synchronous": 2
    }
]


cat /var/ossec/etc/client.keys | wc -l
50000

TOKEN=$(curl -u wazuh:wazuh -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")

curl -k -X POST "https://localhost:55000/groups" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d '{"group_id": "test_group10"}'

time curl -k -X PUT "https://localhost:55000/agents/group?wait_for_complete=true&group_id=test_group10" -H  "Authorization: Bearer $TOKEN"
{"data": {"affected_items": ["001",.... "50000", "50001"], "total_affected_items": 50001, "total_failed_items": 0, "failed_items": []}, "message": "All selected agents were assigned to test_group10", "error": 0}
real  11m23,399s
user  0m0,028s
sys 0m0,049s
```

### Conclusion

| Branch | synchronous value | Time it takes to perform group assignment|
|-|-|-|
|[22753-change-db-synchronous-mode](https://github.com/wazuh/wazuh/tree/22753-change-db-synchronous-mode)| NORMAL (1) | 7m 49s |
|[4.8.0](https://github.com/wazuh/wazuh/tree/4.8.0)| FULL (2) | 11m 23s |

In this case the difference between versions was about 30% less time that `branch 22753-change-db-synchronous-mode` took than branch `4.8.0`.

2024-04-08 06:52 UTC, vikman90 requested changes

2024-04-09 01:04 UTC, cborla commented
## Time a version takes to perform group assignment (Vulnerability detector disabled)

### Branch  22753-change-db-synchronous-mode

Disabling vulnerability detection from ossec.conf

``` xml
<vulnerability-detection>
  <enabled>no</enabled>
```

#### Test:
``` console
wdb-query2.py global "sql PRAGMA synchronous"
[
    {
        "synchronous": 1
    }
]

cat /var/ossec/etc/client.keys | wc -l
50000

TOKEN=$(curl -u wazuh:wazuh -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")

curl -k -X POST "https://localhost:55000/groups" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d '{"group_id": "test_group3"}'

time curl -k -X PUT "https://localhost:55000/agents/group?wait_for_complete=true&group_id=test_group3" -H  "Authorization: Bearer $TOKEN"
{"data": {"affected_items": ["001",.... "50000", "50001"], "total_affected_items": 50001, "total_failed_items": 0, "failed_items": []}, "message": "All selected agents were assigned to test_group3", "error": 0}
real  5m13,638s
user  0m0,020s
sys 0m0,021s
```

### Branch v4.8.0-beta4

Disabling vulnerability detection from ossec.conf
``` xml
<vulnerability-detection>
  <enabled>no</enabled>
```

#### Test:
``` console
/var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.8.0"
WAZUH_REVISION="40806"
WAZUH_TYPE="server"

wdb-query2.py global "sql PRAGMA synchronous"
[
    {
        "synchronous": 2
    }
]

cat /var/ossec/etc/client.keys | wc -l
50000

TOKEN=$(curl -u wazuh:wazuh -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")

curl -k -X POST "https://localhost:55000/groups" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d '{"group_id": "test_group3"}'

time curl -k -X PUT "https://localhost:55000/agents/group?wait_for_complete=true&group_id=test_group3" -H  "Authorization: Bearer $TOKEN"
{"data": {"affected_items": ["001",.... "50000", "50001"], "total_affected_items": 50001, "total_failed_items": 0, "failed_items": []}, "message": "All selected agents were assigned to test_group3", "error": 0}
real  6m50,241s
user  0m0,020s
sys 0m0,025s
```

### Branch v4.8.0-beta5

Disabling vulnerability detection from ossec.conf

``` xml
<vulnerability-detection>
  <enabled>no</enabled>
```
#### Test:
``` console
/var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.8.0"
WAZUH_REVISION="40807"
WAZUH_TYPE="server"

wdb-query2.py global "sql PRAGMA synchronous"
[
    {
        "synchronous": 2
    }
]

cat /var/ossec/etc/client.keys | wc -l
50000

TOKEN=$(curl -u wazuh:wazuh -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")

curl -k -X POST "https://localhost:55000/groups" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d '{"group_id": "test_group3"}'

time curl -k -X PUT "https://localhost:55000/agents/group?wait_for_complete=true&group_id=test_group3" -H  "Authorization: Bearer $TOKEN"
{"data": {"affected_items": ["001",.... "50000", "50001"], "total_affected_items": 50001, "total_failed_items": 0, "failed_items": []}, "message": "All selected agents were assigned to test_group3", "error": 0}
real  6m38,176s
user  0m0,027s
sys 0m0,022s
```

### Conclusion

| Branch | synchronous value | Time it takes to perform group assignment|
|-|-|-|
|[22753-change-db-synchronous-mode](https://github.com/wazuh/wazuh/tree/22753-change-db-synchronous-mode)| NORMAL (1) | 5m 13s |
|v4.8.0-beta4| FULL (2) | 6m 50s |
|v4.8.0-beta5| FULL (2) | 6m 38s |

In this case the difference between versions was about 20% less time that `branch 22753-change-db-synchronous-mode` took than branch `v4.8.0-betaX`.

2024-04-09 09:31 UTC, vikman90 reviewed
## Tests

### 4.8.0 (unfixed)

|Query|Result|
|--|--|
|`global sql PRAGMA synchronous`|2|

### This branch (fixed)

|Query|Result|
|--|--|
|`global sql PRAGMA synchronous`|1|
|`agent 000 sql PRAGMA synchronous`|2|

2024-04-11 09:57 UTC, merged