Implementation of docker images update in packages building
wazuh/wazuh pull request #22907
Opened 2024-04-12 12:29 UTC by mjcr99

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/22868|

## Description

Hi team,

This PR establishes a standard procedure to upload and update the docker images used in the packages' building process via GHA. This includes:

- A new workflow `packages-retag-images.yml` will be triggered when a push event is detected in a new version branch or when the `src/VERSION` file content is updated. It will also be possible to call this workflow manually. This will retag all the docker images to let the new packages building workflows that may be launched from a new versioned branch, find the correct docker image, since this procedure depends, in most cases, on the `src/VERSION` file content.

- A new workflow `packages-upload-images.yml` will be dispatched and will rebuild the images if the Dockerfiles or the `helper_functions` files are modified.

## Tests
- This [workflow](https://github.com/wazuh/wazuh/actions/runs/8721641712/job/23925815271) has been launched to manually retag the image `pkg_deb_agent_builder_amd64`. [Here](https://github.com/wazuh/wazuh/pkgs/container/pkg_deb_agent_builder_amd64) it shows the retag is done successfully.

- This [workflow](https://github.com/wazuh/wazuh/actions/runs/8721748626/job/23926144727) has been launched to manually retaf the image `pkg_deb_agent_builder` which does not exist. The workflow shows a descriptive message, referring to the inexistence of this image.

2024-04-18 10:56 UTC, MarcelKemp requested changes
We will also have to take into account the changes in this other issue:
- https://github.com/wazuh/wazuh-agent-packages/issues/1

So that we can upload images from the other repository via the API.

2024-04-30 13:54 UTC, lchico requested changes
@mjcr99 , Looks great! I left some comments.

2024-04-30 13:54 UTC, lchico commented on .github/workflows/packages-upload-images.yml
> +              - packages/wpk/wpkpack.py
Why don't the next paths have single quotes? Maybe we should add them just to be consistent with the previous ones.

2024-04-30 13:54 UTC, lchico commented on .github/workflows/packages-upload-images.yml
> +              - packages/wpk/common/*
Should we use `**`?
`              - 'packages/wpk/common/**'`

2024-04-30 13:54 UTC, lchico commented on .github/workflows/packages-upload-images.yml
> +          elif [ "${{ inputs.docker_image_tag }}" == "developer" ]; then echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV;
Should we consider applying the same approach to the ref_name as [here](https://github.com/wazuh/wazuh/pull/22973):

```
         elif [ "${{ inputs.docker_image_tag }}" == "developer" ]; then echo "TAG=$(sed 's|[/\]|--|g' <<< ${{ github.ref_name }})" >> $GITHUB_ENV;
```

2024-04-30 13:54 UTC, lchico commented on .github/workflows/packages-upload-images.yml
> +          gh workflow run packages-upload-agent-images-amd.yml --repo wazuh/wazuh-agent-packages -r ${{ env.WAZUH_AGENT_PACKAGES_BRANCH }} -f docker_image_tag=${{ env.TAG }} -f system=deb -f architec
I'm not sure about this, but if a flag like *legacy* defaults to false and isn't required, is it still necessary to define it here? If not, I'd like to remove it.

2024-04-30 13:54 UTC, lchico commented on .github/workflows/packages-upload-images.yml
> +          gh workflow run packages-upload-agent-images-amd.yml --repo wazuh/wazuh-agent-packages -r ${{ env.WAZUH_AGENT_PACKAGES_BRANCH }} -f docker_image_tag=${{ env.TAG }} -f system=deb -f architec
Consider applying this approach to all cases.

2024-05-02 23:10 UTC, lchico approved these changes
GJ, @mjcr99. LGTM!

2024-05-03 11:05 UTC, MarcelKemp requested changes

2024-05-03 11:05 UTC, MarcelKemp commented on .github/workflows/packages-upload-images.yml
> +          echo "WAZUH_AGENT_PACKAGES_BRANCH=master" >> $GITHUB_ENV
We want the `wazuh_agent_packages` branch to be the same as the one used in `wazuh`. 
As the only branches that can trigger would be `master` and a versioned branch, we can tell it to always use the `ref_name`, as it should also be in the other repository.
```suggestion
          echo "WAZUH_AGENT_PACKAGES_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
```

2024-05-03 13:12 UTC, MarcelKemp approved these changes
GJ! LGTM.

2024-05-03 15:00 UTC, merged