Fix: remove permissions for Authenticated users
wazuh/wazuh pull request #23273
Opened 2024-05-05 00:45 UTC by lchico

|Related issue|
|---|
|https://github.com/wazuh/internal-devel-requests/issues/1091|

## Description
The objective is clearing the ACL and setting the explicit permissions that the agent's folder needs. However, after several attempts, I was able to remove explicit the permissions for Authenticated users (S-1-5-11).

Some of the tries were:
*         `setPermsInherit = "icacls """ & install_dir & """ /inheritancelevel:r /q"`
In this case, I was unable to set permissions for Administrators, System, and Users afterward.
*         `setPermsInherit = "icacls """ & install_dir & """ /reset /q"`
This resulted in the same issue as the previous attempt.
*         `setPermsInherit = "icacls """ & install_dir & """ /inheritancelevel:r /grant Administrators:F /grant System:F /q "`
This configuration did not remove inheritance at all. 

## Tests

|                                                  C:\Program Files (x86)\ossec-agent                                                  |                                                               C:\ossec                                                               |   |   |   |
|:------------------------------------------------------------------------------------------------------------------------------------:|:------------------------------------------------------------------------------------------------------------------------------------:|---|---|---|
| <img width="576" alt="ossec_default_path" src="https://github.com/wazuh/wazuh/assets/21695385/5f89e0b7-1ac9-43d9-916e-a7f179628564"> | <img width="576" alt="ossec_on_root_path" src="https://github.com/wazuh/wazuh/assets/21695385/679240ce-a279-4d77-b482-a64e65f9f39f"> |   |   |   |

**_So this PR removes permissions for Authenticated users._**

**Note:** The MSI generated on S3 bucket:  s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/wazuh-agent_4.9.0-lcwin_windows_1fcaa34.msi

- Compilation without warnings in every supported platform
  - [x] Windows
- [x] Package installation

2024-05-08 18:27 UTC, MarcelKemp submitted a review, later dismissed
LGTM!

2024-05-08 18:43 UTC, MarcelKemp commented
## Failing checks
- **_Integration tests for `<module>` on Windows - Tier 0 and 1_**

It seems that all ITs are failing due to reduced permissions, because the log monitor does not have access to the `ossec.log` file.

2024-05-09 01:08 UTC, lchico commented
> [](/apps/github-actions) ** Integration tests for enrollment on Windows - Tier 0 and 1 / run-test (pull_request) **



> access to the `ossec.log`
# Update 
By adding the (OI)(CI) flags, we can ensure that both new files and new subfolders inherit these permissions. This fix the access issue with the ossec.log file. Should we implement this change or implement a new change on the test side?

2024-05-09 10:09 UTC, MarcelKemp requested changes

2024-05-09 10:09 UTC, MarcelKemp commented on src/win32/InstallerScripts.vbs
> +        grantSystemPerm = "icacls """ & install_dir & """ /grant *S-1-5-18:(OI)(CI)F /t"
Ditto:
```suggestion
        grantSystemPerm = "icacls """ & install_dir & """ /grant *S-1-5-18:(OI)(CI)F"
```

2024-05-11 11:33 UTC, MarcelKemp approved these changes

2024-05-11 11:34 UTC, merged