Set file permissions
wazuh/wazuh pull request #23369
Opened 2024-05-09 20:05 UTC by aritosteles

|Related issue|
|---|
|#20727|

## Description
Modified InstallerScripts.vbs and wazuh-installer.wxs. 
Added a custom function that set file permissions.

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [x] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [x] Package installation
- [ ] Source upgrade
- [x] Package upgrade
- [x] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2024-05-10 12:57 UTC, tdrauncieal requested changes

2024-05-10 13:20 UTC, ncvicchi commented on src/win32/wazuh-installer.wxs
> +        <CustomAction Id="SetCustomActionDataValue2" Return="check" Property="SetPermissions" Value="&quot;[APPLICATIONFOLDER]&quot;" />
Reusing names as "SetCustomActionDataValue" to "SetCustomActionDataValue2" tends to ofuscate code in time and might grown badly. If this value is used exclusively with the setPermissions functionality I would use some name that would refer to it as "SetPermissionsCustomActionDataValue" or similar to enforce relationship

2024-05-10 13:31 UTC, Leoquicenoz requested changes

2024-05-10 13:31 UTC, Leoquicenoz commented on src/win32/wazuh-installer.wxs
> +            <Custom Action="SetCustomActionDataValue2" Before="InstallFinalize"/>
You could add the closing of the `<Custom Action></Custom>`, this would keep the same existing syntax.

2024-05-10 14:00 UTC, tdrauncieal approved these changes
LGTM.

2024-05-10 15:00 UTC, ncvicchi approved these changes
LGTM!

2024-05-10 15:18 UTC, Leoquicenoz approved these changes
LGTM!!

2024-05-14 02:01 UTC, Dwordcito commented
The failed checks are pre-existing and are due to the fact that 4.9.0 must be updated with the changes introduced in 4.8.0

2024-05-14 02:01 UTC, merged