Handle Generic Windows CPE for "Running On" Configurations
wazuh/wazuh pull request #23549
Opened 2024-05-21 19:21 UTC by GabrielEValenzuela

|Related issue|
|---|
| #23149|

# Objetive
This PR aims to enhance the vulnerability scanner by incorporating logic to accurately handle generic Windows CPEs, especially in "running on" configurations as specified by the NVD. The objective is to improve the scanner's ability to assess vulnerabilities more precisely in environments where specific version details are not available but a generic classification is.

### Changes Implemented
- **Enhanced Logic in `oscpe-global`**:
  - Added logic to handle the template of `oscpe-global.json` to facilitate reverse mapping from platform to vendor using `feed-global.json`.

- **Updates to `osDataCache.hpp`**:
  - Integrated support for new generic CPEs in the cache system to enhance matching capabilities.

- **New Functionality in `scanContext.hpp`**:
  - Implemented `buildCPENameForGenericOrRunning` to construct CPE names based on information received from syscollector messages.

- **Improvements in `packageScanner.hpp`**:
  - Enhanced log messages for better clarity and troubleshooting.
  - Added logic to handle comparisons involving generic CPEs, improving the accuracy of vulnerability assessments.

### Implementation Details
- Modified JSON parsing logic and data structures to support the inclusion of new generic CPEs.
- Updated schema definitions in `oscpe-global.json` to align with the enhanced functionality.
- Conducted extensive unit and integration testing to ensure accurate CPE generation and comparison under various scenarios.

### Testing
- Implemented automated tests to verify the correct functioning of the new logic across different modules (`osDataCache.hpp`, `scanContext.hpp`, and `packageScanner.hpp`).
- Performed regression testing to ensure that existing functionalities are not adversely affected by the new updates.
- Conducted manual testing with simulated syscollector messages to validate the effectiveness of CPE name construction.

### Additional Information
- Documentation has been updated to reflect the new capabilities and guide users on how to leverage the enhanced features effectively.

--------------------------

2024-05-22 13:12 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanContext.hpp
> +                vendorName = item[m_osData.platform];
```suggestion
                vendorName = item.at(m_osData.platform);
```

2024-05-22 23:13 UTC, GabrielEValenzuela commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/osDataCache.hpp
> +    std::string cpeGenericOrRunning; ///< CPE running or generic of the operating system.
Improved it!

2024-05-22 23:13 UTC, GabrielEValenzuela commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanContext.hpp
> +                vendorName = item[m_osData.platform];
Thanks!

2024-05-24 02:55 UTC, sebasfalcone reviewed
I will take from here @GabrielEValenzuela

2024-05-24 02:55 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanContext.hpp
> +        for (const auto& item : reverseVendorMaps[KEY_REVERSE_VENDOR])
Its preferable to produce an exception than a segfault:
```suggestion
        for (const auto& item : reverseVendorMaps.at(KEY_REVERSE_VENDOR))
```

2024-05-27 18:30 UTC, sebasfalcone commented
## Update
- The target branch changed from 4.8.0 to 4.9.0 
- Still waiting for 4.8.0 to be merged into 4.9.0

2024-06-01 16:58 UTC, sebasfalcone requested changes
Good work @GabrielEValenzuela!

Please add an efficacy test for this scenario

2024-06-06 18:20 UTC, GabrielEValenzuela commented
# Update

With local changes, test 🟢 

```bash
❯ python -m pytest  -xvv -k "run_process_and_monitor_log14"  wazuh_modules/vulnerability_scanner/qa
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.11.9, pytest-7.2.2, pluggy-1.5.0 -- /home/gvalenzuela/Documents/Work/wazuh/src/virtual_env/bin/python
cachedir: .pytest_cache
rootdir: /home/gvalenzuela/Documents/Work/wazuh/src
collected 19 items / 18 deselected / 1 selected

wazuh_modules/vulnerability_scanner/qa/test_efficacy_log.py::test_false_negatives[run_process_and_monitor_log14] PASSED                                                                [100%]

============================================================================== 1 passed, 18 deselected in 2.14s ==============================================================================
```

2024-06-07 14:25 UTC, sebasfalcone requested changes
Simple, yet effective!

Just one thing, add the documentation for the test 20 ([here is a template](https://github.com/wazuh/wazuh/blob/9721fbeabd6c1c3d2c7de8b14c1af45623302b4e/src/wazuh_modules/vulnerability_scanner/qa/test_data/001/Readme.md))

2024-06-11 19:12 UTC, GabrielEValenzuela commented
# Test case II

- After adding the content manually in the code, we run the QA tests again

```bash
❯ python -m pytest --log-cli-level=DEBUG --capture=tee-sys -xvv  wazuh_modules/vulnerability_scanner/qa/
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.11.9, pytest-7.2.2, pluggy-1.5.0 -- /home/gvalenzuela/Documents/Work/wazuh/src/virtual_env/bin/python
cachedir: .pytest_cache
rootdir: /home/gvalenzuela/Documents/Work/wazuh/src
collected 23 items
[...]
=============================================================================== 23 passed in 240.81s (0:04:00) ===============================================================================
```

2024-06-12 13:58 UTC, sebasfalcone approved these changes
Good work @GabrielEValenzuela!
- Tests 🟢 
- Code 🟢

2024-06-12 13:58 UTC, sebasfalcone commented
## Issue blocked
Awaiting for content to be updated in order for QA test to pass in GA

2024-06-13 19:37 UTC, sebasfalcone requested changes
Missing efficacy test for the case proposed on the issues:
- https://nvd.nist.gov/vuln/detail/CVE-2012-4142

2024-06-13 20:31 UTC, sebasfalcone approved these changes

2024-06-14 18:38 UTC, closed without merging