Add post action and re-scan after that update.
wazuh/wazuh pull request #23603
Opened 2024-05-23 18:15 UTC by Dwordcito

|Related issue|
|---|
|Close #23482 |

## Description

Add post action and no-index feature

2024-05-23 23:07 UTC, GabrielEValenzuela requested changes
One little comment!

2024-05-23 23:07 UTC, GabrielEValenzuela commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/agentReScanListException.hpp
> +
Documentation or function name should have more context

2024-05-24 01:17 UTC, sebasfalcone requested changes

2024-05-24 01:17 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/resultIndexer.hpp
> +                // This is useful for elements that needs the trigger of agent to be indexed.
+1: We will forget this

2024-05-24 01:17 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/resultIndexer.hpp
We have to replicate this on the [arrayResultIndex](https://github.com/wazuh/wazuh/blob/4.8.0/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/arrayResultIndexer.hpp)

2024-05-24 01:28 UTC, Dwordcito commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/resultIndexer.hpp
It is not necessary, because is only for re-scan triggers

2024-05-24 01:37 UTC, sebasfalcone reviewed
Minor comments

2024-05-24 01:37 UTC, sebasfalcone commented on src/shared_modules/utils/timeHelper.h
> +     */
Documentation unclear 😆

2024-05-24 01:37 UTC, sebasfalcone commented on src/shared_modules/indexer_connector/src/indexerConnector.cpp
> +                const bool shouldIndex = !parsedData.contains("no-index") || !parsedData.at("no-index").get<bool>();
Nitpick: We use a different logic in another file
```suggestion
                const bool shouldIndex = parsedData.contains("no-index") ? parsedData.at("no-index").get<bool>() : false;
```

2024-05-24 01:37 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanAgentList.hpp
> +            }
Why not?
```suggestion
            context->m_noIndex = noIndex;
```

2024-05-24 01:37 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanAgentList.hpp
> +            }
ditto
```suggestion
            context->m_noIndex = noIndex;
```

2024-05-24 03:55 UTC, sebasfalcone approved these changes
- Code 🟢 LGTM
  - One comment with no impact on the behaviour

2024-05-24 03:55 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOrchestrator.hpp
>                      m_eventDelayedDispatcher->clear(context->agentId());
Coverity may complain about "copy instead of move"

2024-05-24 03:55 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOrchestrator.hpp
>                      m_eventDelayedDispatcher->clear(context->agentId());
ditto

2024-05-24 04:36 UTC, GabrielEValenzuela approved these changes
Great work!

Code 🟢 
Testing 🟢 

During the test stage, we can see that after the content was successfully updated, all agents performed a re-scan.

2024-05-24 05:25 UTC, merged