Implementing version regex in translations
wazuh/wazuh pull request #23727
Opened 2024-05-28 15:18 UTC by pereyra-m

|Related issue|
|---|
|Closes #23518|

## Description

This PR adds the vendor and version regex validations when a package is scanned.

- UTs and QA tests were added.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] QA templates contemplate the added capabilities
- [x] Added unit tests (for new features)

2024-06-01 22:00 UTC, sebasfalcone reviewed
Great work @pereyra-m!


Partial review:
- Add the documentation for test-case 18

Testing pending

2024-06-03 15:53 UTC, sebasfalcone requested changes
Lets add the documentation for the 018 test

2024-06-04 15:23 UTC, pereyra-m commented on src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp
> +            translationQuery.versionRegex = std::move(versionRegex);
Thank you!
It's more readable now.

2024-06-11 12:07 UTC, sebasfalcone requested changes
Rebase needed

2024-06-12 04:02 UTC, Dwordcito approved these changes

2024-06-12 04:02 UTC, merged