Wazuh manager workflow: Improve installers' naming handling
wazuh/wazuh pull request #23780
Opened 2024-05-29 22:05 UTC by lchico

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/23777|

## Description

## Configuration options

## Logs/Alerts example

## Tests

2024-05-31 10:36 UTC, mjcr99 requested changes
GJ @lchico!

Could we consider adding a timeout for the job as it has been done for the agent workflow?

2024-06-01 13:51 UTC, lchico commented
> GJ @lchico!
> 
> Could we consider adding a timeout for the job as it has been done for the agent workflow?

This change has already been implemented. (See #23779)

2024-06-03 12:41 UTC, mjcr99 approved these changes

2024-06-03 14:42 UTC, MarcelKemp approved these changes

2024-06-03 14:43 UTC, merged