integratord - Remove sensitive information from log files
wazuh/wazuh pull request #23833
Opened 2024-05-31 22:08 UTC by Damian-Mangold

|Related issue|
|---|
|#23648|

## Description

## Tests

2024-06-01 01:31 UTC, Dwordcito requested changes

2024-06-01 01:31 UTC, Dwordcito commented on integrations/maltiverse.py
We need to add a conditional to avoid writing an empty line if len(args) >= 4

2024-06-01 01:31 UTC, Dwordcito commented on integrations/pagerduty.py
We need to add a conditional to avoid writing an empty line if len(args) >= 4

2024-06-01 01:31 UTC, Dwordcito commented on integrations/virustotal.py
We need to add a conditional to avoid writing an empty line if len(args) >= 4

2024-06-01 11:17 UTC, Damian-Mangold commented on integrations/maltiverse.py
Instead of adding a conditional I included the line break to the only possible message that can be printed in case len(args) < 4.
This is how the log looks now:
![image](https://github.com/wazuh/wazuh/assets/106940255/9b1cf8b4-57a6-4b17-af6e-e8ff0867be0f)

2024-06-01 11:18 UTC, Damian-Mangold commented on integrations/pagerduty.py
the same as [here](https://github.com/wazuh/wazuh/pull/23833#discussion_r1623204796)

2024-06-01 11:18 UTC, Damian-Mangold commented on integrations/virustotal.py
the same as [here](https://github.com/wazuh/wazuh/pull/23833#discussion_r1623204796)

2024-06-01 11:26 UTC, Damian-Mangold commented on integrations/maltiverse.py
Here I have simulated an error between two runs, you can see that the log is generated correctly, respecting the line breaks.
![image](https://github.com/wazuh/wazuh/assets/106940255/41204ca0-44c3-489d-ab13-4ecaee21c5ca)

2024-06-03 02:19 UTC, Dwordcito approved these changes

2024-06-03 02:19 UTC, merged