Ensure `queue` folder is removed when agent is uninstalled in `deb` systems
wazuh/wazuh pull request #23873
Opened 2024-06-04 10:52 UTC by mjcr99

|Related issue|
|---|
|https://github.com/wazuh/wazuh-packages/issues/2195|

## Description

This PR fixes the situation when the uninstall of a wazuh-agent does not completely remove the desired folders, specifically the `queue` folder.

## Testing

<details><summary> :green_circle: Testing the solution</summary>

Install wazuh-agent with new branch:

```console
root@agent1-ubu22:/home/vagrant# apt install /vagrant/wazuh-agent_4.9.0-0_amd64_0aa014f.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'wazuh-agent' instead of '/vagrant/wazuh-agent_4.9.0-0_amd64_0aa014f.deb'
The following NEW packages will be installed:
  wazuh-agent
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/10.7 MB of archives.
After this operation, 37.2 MB of additional disk space will be used.
Get:1 /vagrant/wazuh-agent_4.9.0-0_amd64_0aa014f.deb wazuh-agent amd64 4.9.0-0 [10.7 MB]
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package wazuh-agent.
(Reading database ... 71365 files and directories currently installed.)
Preparing to unpack .../wazuh-agent_4.9.0-0_amd64_0aa014f.deb ...
Unpacking wazuh-agent (4.9.0-0) ...
Setting up wazuh-agent (4.9.0-0) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Scanning processes...                                                                                                                   
Scanning linux images...                                                                                                                

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
```

Agent starts and try to connect to the manger:

```console
root@agent1-ubu22:/home/vagrant# cat /var/ossec/logs/ossec.log | grep "agentd"
2024/06/04 10:45:27 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2024/06/04 10:45:27 wazuh-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2024/06/04 10:45:27 wazuh-agentd: INFO: Version detected -> Linux |agent1-ubu22 |5.15.0-25-generic |#25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 |x86_64 [Ubuntu|ubuntu: 22.04 (Jammy Jellyfish)] - Wazuh v4.9.0
2024/06/04 10:45:27 wazuh-agentd: INFO: Started (pid: 2912).
2024/06/04 10:45:27 wazuh-agentd: INFO: Requesting a key from server: 11.11.11.11
2024/06/04 10:47:36 wazuh-agentd: ERROR: (1208): Unable to connect to enrollment service at '[11.11.11.11]:1515'
2024/06/04 10:47:41 wazuh-agentd: INFO: Requesting a key from server: 11.11.11.11
```

Agent is removed and residual files are checked:

```console
root@agent1-ubu22:/home/vagrant# apt remove wazuh-agent
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  wazuh-agent
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 37.2 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 71789 files and directories currently installed.)
Removing wazuh-agent (4.9.0-0) ...

root@agent1-ubu22:/home/vagrant# tree /var/ossec/
/var/ossec/
└── etc
    ├── client.keys.save
    ├── local_internal_options.conf.save
    ├── ossec.conf.save
    └── shared
        ├── cis_apache2224_rcl.txt.save
        ├── cis_debian_linux_rcl.txt.save
        ├── cis_mysql5-6_community_rcl.txt.save
        ├── cis_mysql5-6_enterprise_rcl.txt.save
        ├── cis_rhel5_linux_rcl.txt.save
        ├── cis_rhel6_linux_rcl.txt.save
        ├── cis_rhel7_linux_rcl.txt.save
        ├── cis_rhel_linux_rcl.txt.save
        ├── cis_sles11_linux_rcl.txt.save
        ├── cis_sles12_linux_rcl.txt.save
        ├── cis_win2012r2_domainL1_rcl.txt.save
        ├── cis_win2012r2_domainL2_rcl.txt.save
        ├── cis_win2012r2_memberL1_rcl.txt.save
        ├── cis_win2012r2_memberL2_rcl.txt.save
        ├── rootkit_files.txt.save
        ├── rootkit_trojans.txt.save
        ├── system_audit_rcl.txt.save
        ├── system_audit_ssh.txt.save
        ├── win_applications_rcl.txt.save
        ├── win_audit_rcl.txt.save
        └── win_malware_rcl.txt.save

2 directories, 24 files

```

</details>

2024-06-04 14:42 UTC, lchico approved these changes
LGTM!

2024-06-04 14:47 UTC, lchico commented
> LGTM!

Should we do some for the [manager](https://github.com/wazuh/wazuh/blob/4.9.0/packages/debs/SPECS/wazuh-agent/debian/postrm#L30)?

2024-06-04 15:07 UTC, lchico requested changes
Should we do the some for the [manager](https://github.com/wazuh/wazuh/blob/4.9.0/packages/debs/SPECS/wazuh-agent/debian/postrm#L30)?

2024-06-11 09:12 UTC, mjcr99 commented
Hi team, the PR has been updated to make the DEB and RPM packages consistent between each other regarding their behavior when uninstalling the package.

Now the remaining files for DEB manager after uninstalling are:

```
root@agent1-ubu22:/home/vagrant# apt remove wazuh-manager
....

root@agent1-ubu22:/home/vagrant# tree /var/ossec/
/var/ossec/
├── backup
│   └── db
│       └── global.db-backup-2024-06-11-09:09:27.gz
└── etc
    ├── client.keys.save
    ├── lists
    │   ├── amazon
    │   │   ├── aws-eventnames.cdb.save
    │   │   ├── aws-eventnames.save
    │   │   └── aws-sources.save
    │   ├── audit-keys.cdb.save
    │   ├── audit-keys.save
    │   ├── security-eventchannel.cdb.save
    │   └── security-eventchannel.save
    ├── local_internal_options.conf.save
    ├── ossec.conf.save
    ├── shared
    │   ├── ar.conf.save
    │   └── default
    │       └── merged.mg.save
    ├── sslmanager.cert.save
    └── sslmanager.key.save

7 directories, 15 files

```

Now the remaining files for RPM manager after uninstalling are:

```
[root@linux-rocky vagrant]# yum remove wazuh-manager
....


[root@linux-rocky vagrant]# tree /var/ossec/
/var/ossec/
├── backup
│   └── db
│       └── global.db-backup-2024-06-11-04:42:21.gz
└── etc
    ├── lists
    │   ├── amazon
    │   │   └── aws-eventnames.cdb
    │   ├── audit-keys.cdb
    │   └── security-eventchannel.cdb
    ├── ossec.conf.rpmsave
    ├── shared.save
    │   ├── ar.conf
    │   └── default
    │       └── merged.mg
    ├── sslmanager.cert.save
    └── sslmanager.key.save

7 directories, 9 files

```

2024-06-11 12:32 UTC, lchico approved these changes
GJ. LGTM. Maybe we could update the title and description.

2024-06-11 13:33 UTC, MarcelKemp approved these changes

2024-06-11 15:33 UTC, MarcelKemp commented
## Failing checks

### Unit tests: cmocka server
- https://github.com/wazuh/wazuh-jenkins/issues/6554

### Build Windows i386 agent package
- https://github.com/wazuh/wazuh/issues/23921

### Build Linux x86_64/arm64v8 manager rpm package
- Both are expected, because _wazuh-packages_ from `4.9.0` onwards are not being updated, causing these checks to fail due to lack of SPECS updates.

2024-06-11 15:33 UTC, merged