Fix `sts_client_profile` errors.
wazuh/wazuh pull request #24050
Opened 2024-06-11 19:59 UTC by RamosFe

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/23672|

## Description

Review and fix subscriber-type related classes in the AWS module.

2024-06-12 16:17 UTC, GGP1 requested changes
Changes LGTM, but there's an integration test case related to SQS queues that is [failing](https://github.com/wazuh/wazuh/actions/runs/9472259170/job/26099370778?pr=24050). It passed in master before, so we should fix it.

```console
assert log_monitor.callback_result is not None, ERROR_MESSAGE['failed_sqs_message_retrieval']
E       AssertionError: The AWS module did not retrieve the expected message from the SQS Queue
E       assert None is not None
E        +  where None = <wazuh_testing.tools.monitors.file_monitor.FileMonitor object at 0x7f3764c1b190>.callback_result
```

2024-07-10 12:11 UTC, GGP1 requested changes
There are some conflicts that should be resolved before merging, please make sure that the checks run after these changes.

2024-07-10 23:03 UTC, RamosFe commented
## Update

After fixing the merge conflicts and running again the [IT](https://github.com/wazuh/wazuh/actions/runs/9875706682/job/27273076544?pr=24050), no errors related to the changes made in the Issue were found.

2024-07-11 12:25 UTC, GGP1 approved these changes
LGTM

2024-07-12 12:02 UTC, fdalmaup requested changes

2024-07-12 13:29 UTC, RamosFe commented on wodles/aws/services/aws_service.py
> +    def __init__(self, reparse: bool, profile: str, iam_role_arn: str,service_name: str, only_logs_after: str,
Fixed in commit a7d2afc59558d1e6ff7e2111ebebb0bf3ca0bceb.

2024-07-15 09:33 UTC, fdalmaup approved these changes
LGTM

2024-07-16 18:14 UTC, RamosFe commented
## Update

Due to conflict errors when rebasing the branch in an attempt to `amend` the commits and sign them in the process, I finally squashed the commits and signed them. I will wait for the AWS Integration test results before sending it to review.

2024-07-17 08:13 UTC, merged