Add helper tools for integration development in the Engine
wazuh/wazuh pull request #24085
Opened 2024-06-13 12:33 UTC by JavierBejMen

|Related issue|
|---|
|#24046|

This PR adds the following helper python scripts:
- flatt output:
```
$ python3 tools/flatt_output.py -h
usage: flatt_output.py [-h] [-r ROOT] path pattern

Flattens the output json of a root field

positional arguments:
  path                  Path to the input directory
  pattern               Pattern for the output files

options:
  -h, --help            show this help message and exit
  -r ROOT, --root ROOT  Root field to flatten. Default fllattens all fields
```

- update expected:
```
$ python3 tools/update_expected.py -h
usage: update_expected.py [-h] [-o OUTPUT] [-b BINARY] environment path pattern test_integration test_integration_conf_file

Update expected results

positional arguments:
  environment           Environment folder where the test configuration is stored.
  path                  Path to the directory with input files
  pattern               Pattern for the input files
  test_integration      engine-test integration if any
  test_integration_conf_file
                        engine-test integration configuration file

options:
  -h, --help            show this help message and exit
  -o OUTPUT, --output OUTPUT
                        Path to the output file, default: /tmp/update_expected/
  -b BINARY, --binary BINARY
                        Specify the path to the engine binary
```

Also QoL changes on:
- src/engine/test/health_test/initialState.py
- src/engine/test/setupEnvironment.py
- src/engine/tools/compare_expected.py

2024-06-13 18:51 UTC, juliancnn requested changes
The file `src/engine/tools/flatt_output.py` should be renamed (double `t` in the name):
 `src/engine/tools/flat_output.py`  

On the other hand, it would be desirable to add execution permissions to the scripts:
```
chmod +x tools/flatt_output.py 
chmod +x tools/update_expected.py 
chmod +x tools/compare_expected.py 
```

2024-06-13 18:51 UTC, juliancnn commented on src/engine/tools/flatt_output.py
> +from pathlib import Path
```suggestion
#!/usr/bin/env python3

from pathlib import Path
```

2024-06-13 18:51 UTC, juliancnn commented on src/engine/tools/update_expected.py
> +from pathlib import Path
#!/usr/bin/env python3
```suggestion
#!/usr/bin/env python3

from pathlib import Path
```

2024-06-14 12:11 UTC, juliancnn approved these changes
LGTM!

2024-06-14 12:39 UTC, JcabreraC approved these changes
LGTM !

2024-06-14 12:39 UTC, merged