Capture agent scripts distributed exceptions
wazuh/wazuh pull request #24341
Opened 2024-06-27 15:32 UTC by GGP1

|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/23218 |

## Description

Captures the exceptions raised in distributed functions.

## Tests

<details><summary>Trying to upgrade a non existent agent</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/agent_upgrade.py -a 003 -f /wpk_file
Agents that cannot be upgraded:
  Agent 003 upgrade failed. Status: Error 1701 - Agent does not exist
```

</details>

<details><summary>Deleting the agent database</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/agent_upgrade.py -a 001 -f /wpk_file
Agents that cannot be upgraded:
  Agent 001 upgrade failed. Status: Error 1707 - Cannot send request, agent is not active
```

</details>

<details><summary>Forcing the mentioned exception</summary>

> The trace log is still shown as explained in https://github.com/wazuh/wazuh/issues/18560.

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/agent_upgrade.py -a 001 -f /wpk_file
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/dapi/dapi.py", line 239, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/decorators.py", line 494, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/agent.py", line 1139, in upgrade_agents
    raise WazuhInternalError(1816, 'Agent information not found in database')
wazuh.core.exception.WazuhInternalError: Error 1816 - Agent information not found in database
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/dapi/dapi.py", line 285, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
wazuh.core.exception.WazuhInternalError: Error 1816 - Agent information not found in database
Internal error: Error 1816 - Agent information not found in database
```

</details>

<details><summary>agent_groups execution to show that it's working</summary>

```console
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/agent_groups.py -l
Groups (1):
  default (0)
Unassigned agents: 0.
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/agent_groups.py -s -i 000
The agent 'wazuh-master' with ID '000' belongs to groups: Null
```

</details>

2024-06-28 10:05 UTC, javiersanchz requested changes
The changes made are good and the included tests fulfill the purpose of the issue.

Failed unit tests in the checks deployment need to be checked and fixed.

It also seems that the following checks got stuck at the beginning:

```
RTR scan-build test module agent
RTR scan-build test module server
```

Once the failed tests are analyzed and in case new changes are added to them, the RTR tests will be relaunched

2024-06-28 11:44 UTC, GGP1 commented
> Failed unit tests in the checks deployment need to be checked and fixed.

None of the unit tests are related to the changes introduced, the `Unit tests: framework` test from Jenkins is failing because of a `trio` dependency issue, but we no longer maintain those as they were replaced by Github actions (which were executed successfully).

2024-06-28 12:44 UTC, javiersanchz approved these changes
LGTM !

2024-07-01 08:13 UTC, Selutario approved these changes
LGTM

2024-07-01 08:13 UTC, merged