Merge 4.8.1 into 4.9.0
wazuh/wazuh pull request #24502
Opened 2024-07-08 15:39 UTC by sebasfalcone

|Related issue|
|---|
| #24415 |

2024-07-08 17:25 UTC, sebasfalcone commented
## Failing tests
- Framework tests are falling due to an update of one of the dependencies
  - Tracked by: https://github.com/wazuh/wazuh/issues/24506
  
- Vulnerability scanner QA test is failing due to a misalignment in the generated content
  - Tracked by: https://github.com/wazuh/intelligence-platform/issues/1619

2024-07-08 18:26 UTC, Damian-Mangold approved these changes

2024-07-09 08:25 UTC, Selutario requested changes

2024-07-09 08:25 UTC, Selutario commented on framework/requirements.txt
> +itsdangerous==2.0.0
```suggestion
```

I think this dep should not be included :thinking: It was removed in 4.9.0 when `connexion` was upgraded to 3.0.0:
- https://github.com/wazuh/wazuh/pull/23199/files#diff-ac0d503454a85f64c8021ded91db3e9afddcc51dd88864ca250ac0e199da797a 

Also, it is not being included in the deps 30 cpython:
![image](https://github.com/wazuh/wazuh/assets/23361101/bedbbc5d-6e38-471c-99bd-d127689df18c)

2024-07-09 08:42 UTC, Selutario approved these changes

2024-07-09 09:06 UTC, JcabreraC commented
- **macOS compilation tests / build-sonoma (pull_request)**
Expected, fixed in 4.9.0: https://github.com/wazuh/wazuh/pull/23927

2024-07-09 13:28 UTC, rauldpm commented
Service tests are using old packages due to the wazuh-packages migration to wazuh/wazuh, pending removal

2024-07-09 13:29 UTC, JcabreraC approved these changes

2024-07-09 13:29 UTC, merged