Hide undesired messages in the package generation script
wazuh/wazuh pull request #24724
Opened 2024-07-19 19:32 UTC by lchico

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/24676|

## Description

The script was displaying debug information for all commands, which resulted in excessive output, including when simply checking the help message. This information was more detailed than necessary and could obscure important details.

## Tests

- No verbose
![image](https://github.com/user-attachments/assets/92627850-8a95-4c3f-b42e-e9b64e1ef5e2)

- Verbose
![image](https://github.com/user-attachments/assets/5d21251a-8e50-4cb3-93fd-c8f103f2ad6a)

2024-07-19 19:34 UTC, lchico commented on packages/macos/generate_wazuh_packages.sh
> +set -e
For this script, we already have logic in place that allows setting the --verbose flag, which enables set -x.

2024-07-29 12:10 UTC, MarcelKemp approved these changes

2024-07-29 12:21 UTC, MarcelKemp requested changes
Could we apply the same changes to manager workflows?
- https://github.com/wazuh/wazuh-agent-packages/pull/66

2024-07-29 13:58 UTC, mjcr99 submitted a review, later dismissed
LGTM

2024-07-29 15:45 UTC, MarcelKemp approved these changes

2024-07-29 15:47 UTC, merged