Add Framework Engine API client
wazuh/wazuh pull request #25107
Opened 2024-08-08 18:46 UTC by GGP1

|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/24646 |

## Description

Adds the `Engine` class to communicate to the Engine API via HTTP over Unix sockets.

## Tests

<details><summary>Unit tests</summary>

```console
(venv) gasti@gasti:~/work/wazuh$ pytest framework/wazuh/core/engine --disable-warnings
============================================================== test session starts ===============================================================
platform linux -- Python 3.10.14, pytest-7.3.1, pluggy-1.5.0
rootdir: /home/gasti/work/wazuh/framework
configfile: pytest.ini
plugins: asyncio-0.18.1, tavern-1.23.5, html-2.1.1, metadata-3.1.1, cov-4.1.0, anyio-4.1.0, trio-0.8.0, aiohttp-1.0.4
asyncio: mode=auto
collected 10 items                                                                                                                               

framework/wazuh/core/engine/tests/test_base.py .                                                                                           [ 10%]
framework/wazuh/core/engine/tests/test_init.py .........                                                                                   [100%]

=============================================================== 10 passed in 0.28s ===============================================================
```

</details>

<details><summary>Test using the Docker API as the server</summary>

> The Engine API is still unavailable, so I tested the class against the Docker API which uses the same protocols.

```console
(venv) gasti@gasti:~/work/wazuh$ /home/gasti/work/wazuh/venv/bin/python3 -m asyncio
asyncio REPL 3.10.14 (main, May  3 2024, 08:57:23) [GCC 12.2.0] on linux
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> from wazuh.core.engine import Engine
>>> engine = Engine(socket_path='/var/run/docker.sock')
>>> response = await engine._client.get("http://docker/info")
>>> print(response)
<Response [200 OK]>
>>> print(response.json())
{'ID': '***', 'Containers': 0, 'ContainersRunning': 0, 'ContainersPaused': 0, 'ContainersStopped': 0, ...}
```

</details>

2024-08-08 18:54 UTC, GGP1 commented on framework/wazuh/core/engine/__init__.py
> +# TODO: use actual default path
I'm making a list with these TODOs so we can create a technical debt issue to solve them later

2024-08-13 18:18 UTC, RamosFe approved these changes
LGTM! 🚀

2024-08-14 09:47 UTC, fdalmaup requested changes

2024-08-14 09:47 UTC, fdalmaup commented on framework/wazuh/core/engine/tests/test_init.py
> +    """Check the correct initalization of the `Engine` class."""
```suggestion
    """Check the correct initialization of the `Engine` class."""
```

2024-08-14 09:47 UTC, fdalmaup commented on framework/wazuh/core/engine/tests/test_base.py
> +    """Check the correct initalization of the `BaseModule` class."""
```suggestion
    """Check the correct initialization of the `BaseModule` class."""
```

2024-08-14 09:47 UTC, fdalmaup commented on framework/wazuh/core/engine/tests/test_init.py
> +async def test_close():
```suggestion
async def test_engine_close():
```

2024-08-14 09:47 UTC, fdalmaup commented on framework/wazuh/core/engine/tests/test_init.py
> +    assert engine._client.is_closed == False
```suggestion
    assert not engine._client.is_closed
```

2024-08-14 09:47 UTC, fdalmaup commented on framework/wazuh/core/engine/tests/test_init.py
> +    assert engine._client.is_closed == True
```suggestion
        assert not engine._client.is_closed

    assert engine._client.is_closed
```

2024-08-15 10:19 UTC, fdalmaup approved these changes
LGTM

2024-08-15 10:19 UTC, merged