Add Agent comms API `POST /events/stateful` endpoint
wazuh/wazuh pull request #25206
Opened 2024-08-13 17:18 UTC by GGP1

|Related issue|
|---|
|Closes https://github.com/wazuh/wazuh/issues/24647|

## Description

Implements the Agent communications API `POST /events/stateful` endpoint.

## Tests

> [!Note]
> The response is just to showcase that the events are indexed, the batcher will return different results.

<details><summary>Indexing a single event</summary>

> The SCA event schema is not defined yet, I used the fields `key` and `value` to test the endpoint behavior.

```console
root@wazuh-master:/# curl -k -X POST -H "Content-Type: application/json" https://0.0.0.0:27000/api/v1/events/stateful -d '{"events": [{"key": "string", "value": 0}]}'
{"0":{"_index":"stateful-sca","_id":"wkJ6TJEBWYFJUvSw3N3V","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}}
```

</details>

<details><summary>Indexing multiple events</summary>

```console
root@wazuh-master:/# curl -k -X POST -H "Content-Type: application/json" https://0.0.0.0:27000/api/v1/events/stateful -d '{"events": [{"file": {"attributes": ["string"],"name": "string","path": "string","gid": 0,"group": "string","inode": "string","mtime": "2024-08-13T16:05:19.260Z","mode": "string","size": 0,"target_path": "string","type": "string","uid": 0,"owner": "string","hash": {"md5": "string","sha1": "string","sha256": "string"}},"registry": {"key": "string","value": "string"}},{"host": {"architecture": "string","hostname": "string","os": {"kernel": "string","full": "string","name": "string","platform": "string","version": "string","type": "string","family": "string"}},"process": {"hash": {"md5": "string"}},{"key": "string","value": 0},{"agent": {"build": {"original": "string"},"ephemeral_id": "string","id": "string","name": "string","type": "string","version": "string"},"host": {"architecture": "string","hostname": "string","os": {"kernel": "string","full": "string","name": "string","platform": "string","version": "string","type": "string","family": "string"}},"message": "string","package": {"architecture": "string","build_version": "string","checksum": "string","description": "string","install_scope": "string","installed": "2024-08-13T16:05:19.261Z","license": "string","name": "string","path": "string","reference": "string","size": 0,"type": "string","version": "string"},"tags": ["string"]}]}'
{
  "0":{"_index":"stateful-fim","_id":"w0J-TJEBWYFJUvSwtd0V","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1},
  "1":{"_index":"stateful-inventory","_id":"xEJ-TJEBWYFJUvSwtd2j","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1},
  "2":{"_index":"stateful-sca","_id":"xUJ-TJEBWYFJUvSwtd3O","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1},
  "3":{"_index":"stateful-vulnerability","_id":"xkJ-TJEBWYFJUvSwtt03","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}
}
```

</details>

<details><summary>Unit tests</summary>

```console
(venv) gasti@gasti:~/work/wazuh$ pytest apis/comms_api --disable-warnings
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.10.14, pytest-7.3.1, pluggy-1.5.0
rootdir: /home/gasti/work/wazuh/apis/comms_api
plugins: asyncio-0.18.1, tavern-1.23.5, html-2.1.1, metadata-3.1.1, cov-4.1.0, anyio-4.1.0, trio-0.8.0, aiohttp-1.0.4
asyncio: mode=auto
collected 39 items                                                                                                                  

apis/comms_api/authentication/test/test_authentication.py ......                                                                                                    [ 15%]
apis/comms_api/core/test/test_files.py ...                                                                                                                          [ 23%]
apis/comms_api/middlewares/test/test_logging.py ..                                                                                                                  [ 28%]
apis/comms_api/models/test/test_error.py ....                                                                                                                       [ 38%]
apis/comms_api/routers/test/test_authentication.py ....                                                                                                             [ 48%]
apis/comms_api/routers/test/test_events.py ..                                                                                                                       [ 53%]
apis/comms_api/routers/test/test_exceptions.py .....                                                                                                                [ 66%]
apis/comms_api/routers/test/test_files.py ........                                                                                                                  [ 87%]
apis/comms_api/routers/test/test_utils.py .....                                                                                                                     [100%]

===================================================================== 39 passed, 10 warnings in 1.49s =====================================================================
```

</details>

2024-08-16 13:26 UTC, GGP1 commented on apis/comms_api/core/files.py
This is supposed to be merged in master, since the `GET /files` PR was merged into the authentication one, and the latter was just merged in to master. But the `core/` folder does not appear in master, that's why it's present here

2024-08-16 17:00 UTC, nico-stefani commented on apis/comms_api/core/events.py
Missing UT for this module

2024-08-16 18:35 UTC, nico-stefani submitted a review, later dismissed
LGTM

2024-08-19 10:32 UTC, fdalmaup requested changes

2024-08-19 10:32 UTC, fdalmaup commented on apis/comms_api/routers/events.py
> +        response =  await post_stateful_events(events)
```suggestion
        response = await post_stateful_events(events)
```

2024-08-19 10:32 UTC, fdalmaup commented on apis/comms_api/core/events.py
> +       return await indexer_client.events.post(events)
```suggestion
        return await indexer_client.events.post(events)
```

2024-08-19 12:09 UTC, fdalmaup submitted a review, later dismissed
LGTM! GJ :rocket:

2024-08-19 12:28 UTC, fdalmaup approved these changes

2024-08-19 12:28 UTC, merged