Updates Engine to use new ruleset structure
wazuh/wazuh pull request #25298
Opened 2024-08-21 09:45 UTC by JavierBejMen

2024-08-30 14:35 UTC, juliancnn approved these changes
LGTM!

2024-09-02 13:10 UTC, NahuFigueroa97 approved these changes
LGTM!

2024-09-03 12:14 UTC, JcabreraC approved these changes
LGTM !

2024-09-09 21:59 UTC, Dwordcito requested changes
Minor things

2024-09-09 21:59 UTC, Dwordcito commented on src/engine/source/README.md
> +├── builder/
missing indexerconnector, vdscanner, feedmanager and apiserver, is it really necessary to have this? I don't think we will add many modules, but it is something easy to become obsolete and forget.

2024-09-09 21:59 UTC, Dwordcito commented on src/engine/source/README.md
> +            └── <component>_unit_test.cpp
```suggestion
            └── <class>_test.cpp
```

2024-09-10 08:24 UTC, JcabreraC commented
All checks are passed before the README is deleted:
![imagen](https://github.com/user-attachments/assets/eb1d67ca-7eab-492c-b432-7e64385887c2)

2024-09-10 11:53 UTC, JcabreraC approved these changes
LGTM !

2024-09-10 11:53 UTC, Dwordcito approved these changes

2024-09-10 11:53 UTC, merged