Upgrades Certifi and removes unused dependencies
wazuh/wazuh pull request #25324
Opened 2024-08-22 11:28 UTC by RamosFe

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/24568|

## Description
- Upgrade the certifi package to the version 2024.07.04 or higher.
 - Remove zipp and importlib-metadata dependencies.

2024-08-22 17:33 UTC, GGP1 approved these changes
LGTM

> Authd integration tests failed with the error `RuntimeError: The API was not started as expected.` but the changes introduced aren't related to it, the tests were executed successfully [here](https://github.com/wazuh/wazuh/issues/24568#issuecomment-2304723112).

2024-08-27 08:10 UTC, fdalmaup requested changes

2024-08-27 11:38 UTC, RamosFe commented on src/Makefile
> +DEPS_VERSION = 30-24568
Fixed in b15c553175aced7f9b37c1460462e32e4030426f.

2024-08-27 11:38 UTC, RamosFe commented on framework/requirements.txt
>  content_size_limit_asgi==0.1.5
Fixed in b15c553175aced7f9b37c1460462e32e4030426f.

2024-08-27 13:36 UTC, fdalmaup approved these changes
LGTM!

> [!NOTE]

2024-08-28 09:02 UTC, merged