Content Manager - Avoid error log when provider name is not found
wazuh/wazuh pull request #25641
Opened 2024-09-09 07:39 UTC by tsarquis88

|Related issue|
|---|
|#25575|

## Description

2024-09-09 15:05 UTC, matias-braida approved these changes
LGTM

2024-09-09 15:51 UTC, jftuduri submitted a review, later dismissed
LGTM

2024-09-09 16:22 UTC, Damian-Mangold approved these changes

2024-09-09 23:39 UTC, Dwordcito requested changes

2024-09-10 06:42 UTC, tsarquis88 commented on src/shared_modules/content_manager/src/contentModuleFacade.cpp
> +        logDebug1(WM_CONTENTUPDATER, "Couldn't start scheduled action: Provider '%s' not found.", name);
Fixed.

2024-09-10 06:42 UTC, tsarquis88 commented on src/shared_modules/content_manager/src/contentModuleFacade.cpp
> +    if (providerIt == m_providers.end())
Done.

2024-09-10 06:42 UTC, tsarquis88 commented on src/shared_modules/content_manager/src/contentModuleFacade.cpp
> +        logDebug1(WM_CONTENTUPDATER, "Couldn't start on-demand action: Provider '%s' not found.", name);
Done.

2024-09-10 06:42 UTC, tsarquis88 commented on src/shared_modules/content_manager/src/contentModuleFacade.cpp
> +        logDebug1(WM_CONTENTUPDATER, "Couldn't change scheduled interval: Provider '%s' not found.", name);
Done.

2024-09-10 13:40 UTC, Dwordcito approved these changes

2024-09-10 13:42 UTC, merged