Retrieve vulnerability description with ADPs' data
wazuh/wazuh pull request #25681
Opened 2024-09-11 00:28 UTC by pereyra-m

|Related issue|
|---|
|Closes #25481 |

## Description

This PR allows to select the source for the description data used to populate the vulnerability field.
First, it was required to store the missing descriptive information in the `queue/vd/feed` DB. Then, the `databaseFeedManager` was updated to build the final description considering the ADPs from the `shortName` and `subShortName`.

The corresponding UTs were added  to make sure the data was updated with the required keys, and then properly assembled in the get request. To maintain retro-compatibility, the NVD related entries weren't modified.

## Tests

It was confirmed that the final size of the DB is within the acceptable range. At the offset `123`, this the final size

```

```

Manual tests: WIP.

- Compilation without warnings in every supported platform
  - [ ] Linux
- [ ] Source installation

- [ ] Added unit tests (for new features)

2024-09-12 07:53 UTC, pereyra-m commented
## E2E test

I created an environment to test the new features developed.
The `wazuh-docker` repository was used to run a single-node v4.9.0 Wazuh stack.

These are the agents connected to the manager, all of them Docker images except by the Windows vagrant box

![2024-09-12_03-08](https://github.com/user-attachments/assets/96372eb1-57a3-4766-b264-b0d95b0b84a9)

Consider that:
- No vulnerabilities were found for the Fedora agent, because it hasn't a feed and the NVD doesn't match the package's name
- The Suse agent required to update the content. This is due to its platform (`opensuse-leap`). I manually added the entry, but this issue could require additional research.
- The Debian Buster agent didn't detect vulnerabilities, I had to use another Debian OS. This could be researched more in depth.
- The Oracle agent doesn't report vulnerabilities, even when I add the missing entry the content isn't available.

These are the results exported from each agent vulnerabilities inventory. I didn't consider the alerts because they aren't generated in all cases

[001_debian_4.9.0.csv](https://github.com/user-attachments/files/16974404/001_debian_4.9.0.csv)
[002_suse_4.9.0.csv](https://github.com/user-attachments/files/16974405/002_suse_4.9.0.csv)
[005_redhat_4.9.0.csv](https://github.com/user-attachments/files/16974406/005_redhat_4.9.0.csv)
[006_alas_4.9.0.csv](https://github.com/user-attachments/files/16974407/006_alas_4.9.0.csv)
[007_arch_4.9.0.csv](https://github.com/user-attachments/files/16974408/007_arch_4.9.0.csv)
[008_ubuntu_4.9.0.csv](https://github.com/user-attachments/files/16974409/008_ubuntu_4.9.0.csv)
[009_rocky_4.9.0.csv](https://github.com/user-attachments/files/16974410/009_rocky_4.9.0.csv)
[010_alma_4.9.0.csv](https://github.com/user-attachments/files/16974412/010_alma_4.9.0.csv)
[012_win_4.9.0.csv](https://github.com/user-attachments/files/16974413/012_win_4.9.0.csv)

This baseline was compared against the same setup except by the following changes:
- The development branch was compiled and the `libvulnerability_scanner.so` library was replaced
- The index template was replaced
- The vulnerabilities index was removed
- The folders `queue/vd` and `queue/vd_updater` were removed
- The content was generated against from the snapshot
- The missing feed entry for Suse was added
- The new `adp_descriptions` object was added.
- The mapping of the index was updated to add the new `source` and `under_evaluation` fields
- The module was disabled and enabled again

These are the new results

[001_debian_dev.csv](https://github.com/user-attachments/files/16975326/001_debian_dev.csv)
[002_suse_dev.csv](https://github.com/user-attachments/files/16975329/002_suse_dev.csv)
[005_redhat_dev.csv](https://github.com/user-attachments/files/16975330/005_redhat_dev.csv)
[006_alas_dev.csv](https://github.com/user-attachments/files/16975331/006_alas_dev.csv)
[007_arch_dev.csv](https://github.com/user-attachments/files/16975332/007_arch_dev.csv)
[008_ubuntu_dev.csv](https://github.com/user-attachments/files/16975333/008_ubuntu_dev.csv)
[009_rocky_dev.csv](https://github.com/user-attachments/files/16975334/009_rocky_dev.csv)
[010_alma_dev.csv](https://github.com/user-attachments/files/16975336/010_alma_dev.csv)
[012_win_dev.csv](https://github.com/user-attachments/files/16975337/012_win_dev.csv)

Some important details:
- I couldn't verify the `under_evaluation` field. It is always empty and it has a problem when I try to use it for sorting. It might be related to some missing changes for the Wazuh Indexer
- The field `source` is empty for Suse. It might be related to the manual changes in the content.

2024-09-12 14:59 UTC, MiguelazoDS commented
# Sanitized CSV files 

Updated CSV files without `vulnerability.description`  and `vulnerability.reference` fields to avoid breaking the parsing using a calc software and ease the analysis. 

[001_debian_dev.csv](https://github.com/user-attachments/files/16981450/001_debian_dev.csv)
[002_suse_dev.csv](https://github.com/user-attachments/files/16981451/002_suse_dev.csv)
[005_redhat_dev.csv](https://github.com/user-attachments/files/16981452/005_redhat_dev.csv)
[006_alas_dev.csv](https://github.com/user-attachments/files/16981453/006_alas_dev.csv)
[007_arch_dev.csv](https://github.com/user-attachments/files/16981455/007_arch_dev.csv)
[008_ubuntu_dev.csv](https://github.com/user-attachments/files/16981456/008_ubuntu_dev.csv)
[009_rocky_dev.csv](https://github.com/user-attachments/files/16981457/009_rocky_dev.csv)
[010_alma_dev.csv](https://github.com/user-attachments/files/16981458/010_alma_dev.csv)
[012_win_dev.csv](https://github.com/user-attachments/files/16981459/012_win_dev.csv)

2024-09-12 15:27 UTC, MiguelazoDS commented
# Debian :yellow_circle: 

## Missing fields :yellow_circle: 

The following CVEs do not have information about `vulnerability.scanner.source` and `vulnerability.under_evaluation` fields. 

| CVE ID |
|----------------|
|CVE-2021-22922|
|CVE-2021-22923|
|CVE-2021-3998|
|CVE-2022-27778|
|CVE-2022-27779|
|CVE-2022-27780|
|CVE-2022-30115|
|CVE-2022-35260|
|CVE-2022-42915|
|CVE-2022-42916|
|CVE-2022-43551|
|CVE-2023-23914|
|CVE-2023-23915|
|CVE-2023-27537|
|CVE-2023-28319|
|CVE-2023-28320|
|CVE-2023-38039|
|CVE-2023-4527|
|CVE-2023-46219|
|CVE-2023-4806|
|CVE-2023-4813|
|CVE-2023-6246|
|CVE-2023-6779|
|CVE-2023-6780|
|CVE-2024-2004|
|CVE-2024-2379|
|CVE-2024-7264|

Affected packages 

- libc-bin
- curl
- libc6
- libcurl4

## Vulnerability.scanner.source :green_circle: 

> [!NOTE]
> The rest of CVEs refer to the `Debian Security Tracker` vulnerability scanner source, which makes sense since none of the installed packages are npm or pypi format. 

## Vulnerability.under_evaluation :green_circle: 

| Under evaluation | Last modified |
|-----------------|-------|
|CVE-2023-45918 | 03/15/2024 |
|CVE-2023-50868 |06/10/2024 |
|CVE-2023-6237 | 06/10/2024 |
|CVE-2024-2511 | 05/03/2024 |
|CVE-2024-26458 | 05/14/2024 |
|CVE-2024-28757 | 05/01/2024 |
|CVE-2024-33599 | 07/22/2024 |
|CVE-2024-33600 | 07/22/2024 |
|CVE-2024-5642 | 07/28/2024 |
|CVE-2024-8088 | 09/04/2024 |

2024-09-12 15:31 UTC, MiguelazoDS commented
# Suse 

## Missing fields :yellow_circle: 

All the CVEs in the report do not have information about `vulnerability.scanner.source` and `vulnerability.under_evaluation` fields.

|CVE ID |
|---|
|CVE-2013-4235|
|CVE-2018-6798|
|CVE-2018-6913|
|CVE-2021-3521|
|CVE-2023-45918|
|CVE-2024-0727|
|CVE-2024-2004|
|CVE-2024-2398|
|CVE-2024-25062|
|CVE-2024-2511|
|CVE-2024-28085|
|CVE-2024-28182|
|CVE-2024-34397|
|CVE-2024-34459|
|CVE-2024-37370|
|CVE-2024-37371|
|CVE-2024-5535|
|CVE-2024-6197|
|CVE-2024-7264|

2024-09-12 15:57 UTC, MiguelazoDS commented
# RedHat :green_circle: 

## Missing fields :green_circle:  

>  [!NOTE] 
> No missing fields. 

## Vulnerability.scanner.source :green_circle: 

### RedHat CVE database 

| Affected packages |
|--|
|ca-certificates|
|curl-minimal|
|elfutils-default-yama-scope|
|elfutils-libelf|
|elfutils-libs|
|expat|
|file-libs|
|gawk|
|gdb-gdbserver|
|glib2|
|glibc|
|glibc-common|
|glibc-minimal-langpack|
|gnupg2|
|gnutls|
|krb5-libs|
|libarchive|
|libbpf|
|libcurl-minimal|
|libgcc|
|libgcrypt|
|libgomp|
|libnghttp2|
|libstdc++|
|libxml2|
|libyaml|
|libzstd|
|nano|
|ncurses-base|
|ncurses-libs|
|openldap|
|openssl|
|openssl-libs|
|pam|
|pcre2|
|pcre2-syntax|
|python3|
|python3-idna|
|python3-libs|
|python3-pip-wheel|
|python3-setuptools|
|python3-setuptools-wheel|
|python3-urllib3|
|sqlite-libs|
|systemd|
|systemd-libs|
|systemd-pam|
|systemd-rpm-macros|
|tar|
|tpm2-tss|
|vim-minimal|

> [!NOTE]
> Some packages are python modules but according to the naming they are managed by the oficial repository

### Open Source Vulnerabilities

|Affected packages|
|--|
|requests|
|setuptools|
|urllib3|
|urllib3|
|urllib3|
|idna|
|requests|

> [!NOTE]
> Unlike the previous packages these do not have the python3- prefix. 

## Vulnerability.under_evaluation :green_circle: 

|Under evaluation | NVD reference|
|--|--|
|CVE-2023-39804|https://nvd.nist.gov/vuln/detail/CVE-2023-39804|
|CVE-2023-43804|https://nvd.nist.gov/vuln/detail/CVE-2023-43804|
|CVE-2023-45803|https://nvd.nist.gov/vuln/detail/CVE-2023-45803|
|CVE-2023-45918|https://nvd.nist.gov/vuln/detail/CVE-2023-45918|
|CVE-2023-6237 |https://nvd.nist.gov/vuln/detail/CVE-2023-6237|
|CVE-2024-2511 |https://nvd.nist.gov/vuln/detail/CVE-2024-2511|
|CVE-2024-26458|https://nvd.nist.gov/vuln/detail/CVE-2024-26458|
|CVE-2024-26462|https://nvd.nist.gov/vuln/detail/CVE-2024-26462|
|CVE-2024-28757|https://nvd.nist.gov/vuln/detail/CVE-2024-28757|
|CVE-2024-33599|https://nvd.nist.gov/vuln/detail/CVE-2024-33599|
|CVE-2024-33600|https://nvd.nist.gov/vuln/detail/CVE-2024-33600|
|CVE-2024-34397|https://nvd.nist.gov/vuln/detail/CVE-2024-34397|
|CVE-2024-35195|https://nvd.nist.gov/vuln/detail/CVE-2024-35195|
|CVE-2024-3651 |https://nvd.nist.gov/vuln/detail/CVE-2024-3651|
|CVE-2024-37891|https://nvd.nist.gov/vuln/detail/CVE-2024-37891|
|CVE-2024-6345 |https://nvd.nist.gov/vuln/detail/CVE-2024-6345|
|CVE-2024-8088 |https://nvd.nist.gov/vuln/detail/CVE-2024-8088|

2024-09-12 17:48 UTC, MiguelazoDS commented
# Alas :green_circle: 

## Missing fields :green_circle: 

> [!NOTE]
> No missing fields.

## Vulnerability.scanner.source :green_circle: 

### Amazon Linux Security Center 

|Affected package|
|--|
|glib2
|glibc
|glibc-common
|libnghttp2
|nss-softokn
|nss-softokn-freebl

## Vulnerability.under_evaluation :green_circle: 

- CVE-2023-5388 
 - https://nvd.nist.gov/vuln/detail/CVE-2023-5388
 
 > [!NOTE]
 > At the moment of this analysis, the CVE is indeed under analysis.
 
## ADP information :green_circle: 

> [!NOTE]
> The only CVE without CVSS and severity information is the one under analysis. CVE-2023-5388

2024-09-12 17:59 UTC, MiguelazoDS commented
# Arch Linux :yellow_circle: 

## Missing fields :green_circle: 

> [!NOTE]
> No missing fields.

## Vulnerability.scanner.source  :green_circle: 

### Arch Linux Security Tracker

| Affected packages |
|--|
|python-django|

> [!NOTE]
> With the `python-` prefix we can see this is a official package

![image](https://github.com/user-attachments/assets/f9bc55db-0d20-416a-9b69-39c3aba5223b)

### Open Source Vulnerabilities

| Affected packages |
|--|
|Django|

> [!NOTE]
> Installed with pip

## Vulnerability.under_evaluation :yellow_circle: 

| Under evaluation | NVD reference |
|--|--|
|CVE-2023-36053| https://nvd.nist.gov/vuln/detail/CVE-2023-36053
|CVE-2022-41323| https://nvd.nist.gov/vuln/detail/CVE-2022-41323

> [!NOTE]
>  The CVEs have the state Modified 

![image](https://github.com/user-attachments/assets/10154867-968d-4c00-8488-c9f8358a584e)
![image](https://github.com/user-attachments/assets/17ce5ea2-8f1d-4762-8606-c19a2c3a6710)

> [!IMPORTANT]
> I wouldn't consider this as a under_evaluation, since I can see the information about CVSS and severity 

## ADP information :green_circle: 

> [!NOTE]
> All the CVEs do have information about CVSS and severity.

2024-09-12 18:28 UTC, MiguelazoDS commented
# Rocky Linux :green_circle: 

> [!NOTE]
> Only one CVE to analyze. The ADP information is present. 

## Vulnerability.scanner.source :green_circle: 

The vulnerability scanner source is OSV because the package is from pypi 

https://pypi.org/project/setuptools/

## Vulnerability.under_evaluation :green_circle: 

The CVE is under analysis:

![image](https://github.com/user-attachments/assets/b1563dda-8caa-431b-a642-8518678a4b75)
https://nvd.nist.gov/vuln/detail/CVE-2024-6345

2024-09-12 18:37 UTC, MiguelazoDS commented
# Alma Linux :yellow_circle: 

## Missing fields :green_circle: 

> [!NOTE]
> No missing fields. 

## Vulnerability.scanner.source :green_circle: 

### Alma Linux Security Oval 

|Affected packages |
|--|
| python3-setuptools-wheel
| krb5-libs
| platform-python-setuptools

### Open Source Vulnerabilities 

|Affected package 
|--
|setuptools

## Vulnerability.under_evaluation  :yellow_circle: 

| CVE ID | NVD reference |
|--|--|
|CVE-2024-6345|https://nvd.nist.gov/vuln/detail/CVE-2024-6345|

> [!NOTE]
> The CVE is under analysis, but we have discrepancies because the same CVE is evaluated by two different feeds

![image](https://github.com/user-attachments/assets/8b247ae7-27e6-4652-9080-46f944410743)

| Affected package | CVE ID | Vulnerability.scanner.source | Vulnerability.under_evaluation
|--|--|--|--
|python3-setuptools-wheel |  CVE-2024-6345 | Alma Linux Security Oval | 8.8 | 3 | High | false
|platform-python-setuptools |  CVE-2024-6345 | Alma Linux Security Oval | 8.8 | 3 | High | false
|setuptools | CVE-2024-6345 | Open Source Vulnerabilities | 8.8 | 3.1 | High | true


## ADP information :green_circle: 

> [!NOTE]
> All the CVEs do have information about CVSS and severity.

2024-09-12 18:42 UTC, MiguelazoDS commented
# Windows :green_circle: 

## Missing field  :green_circle: 

> [!NOTE]
> No missing fields. 

## Vulnerability.scanner.source :green_circle: 

> [!NOTE]
> All affected packages have as vulnerability source the National Vulnerability Database.

| Affected packages |
|--|
|Google Chrome
|Mozilla Firefox (x86 en-US)
|PuTTY release 0.80 (64-bit)
|Python 3.1.1 (64-bit)

## Vulnerability.under_evaluation :green_circle: 

> [!NOTE]
> There are no CVEs under evaluation. 

## ADP information :green_circle: 

> [!NOTE]
> All the CVEs do have information about CVSS and severity.

2024-09-12 20:30 UTC, sebasfalcone commented
## Analysis
The issue with the CVEs that are marked as under evaluation despite having descriptive information available is due to a bug in the `isUnderEvaluation` logic:
https://github.com/wazuh/wazuh/blob/6563d685794642f99fc536c842c5cda34882c07c/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/eventDetailsBuilder.hpp#L219-L224

The logic should be instead:
```C++
 const auto isUnderEvaluation = [&returnData]() 
 { 
     return Utils::floatToDoubleRound(returnData.data->scoreBase(), 2) == 0 || 
            returnData.data->scoreVersion()->str().empty() || 
            returnData.data->severity()->str().empty(); 
 }; 
```

2024-09-12 21:06 UTC, sebasfalcone approved these changes
LGTM!

The testing landed good results, the descriptive information is being obtained from the corresponding vendor or the NVD

The issue @MiguelazoDS found in regard of the under_analisis field was addressed in [this commit](https://github.com/wazuh/wazuh/pull/25681/commits/d0c0b8edcc78e3d62c1df3e93385669cda598ac5)

2024-09-12 21:08 UTC, sebasfalcone approved these changes
Style changes

2024-09-19 11:53 UTC, sebasfalcone requested changes
## Review
Compilation is failing in GA

2024-09-19 17:51 UTC, sebasfalcone submitted a review, later dismissed

2024-09-20 18:33 UTC, Dwordcito commented on src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp
>      void getVulnerabiltyDescriptiveInformation(const std::string_view cveId,
This interface is to search for specific values ​​from the family columns of descriptions, apply business logic as to whether one thing or the other should not be part of this library.  Here we only have to model and obtain information.

2024-09-20 18:43 UTC, Dwordcito commented on src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/updateCVEDescription.hpp
> +            auto descriptionArray = std::visit([](auto&& arg) { return arg->descriptions(); }, container);
"std::forward" is never called on this forwarding reference argument

2024-09-20 18:43 UTC, Dwordcito commented on src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/updateCVEDescription.hpp
> +            auto referencesArray = std::visit([](auto&& arg) { return arg->references(); }, container);
dito

2024-09-20 18:43 UTC, Dwordcito commented on src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/updateCVEDescription.hpp
> +            auto problemTypesArray = std::visit([](auto&& arg) { return arg->problemTypes(); }, container);
dito

2024-09-20 18:43 UTC, Dwordcito commented on src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/updateCVEDescription.hpp
> +            auto metricsArray = std::visit([](auto&& arg) { return arg->metrics(); }, container);
dito

2024-09-20 18:43 UTC, Dwordcito commented on src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/updateCVEDescription.hpp
> +                [](auto&& arg)
dito

2024-09-25 00:19 UTC, sebasfalcone submitted a review, later dismissed
## Functional tests
Testing wasn't successful, NVD description and CVSS scoring are used every time

2024-09-25 20:35 UTC, sebasfalcone commented
## Functional testing (local changes)
I've performed some changes and validated the results

### DB size
It went from 5.3GB to 5,8GB. This represents an increase of 9%

### Indexed results
```json
      {
        "_index": "wazuh-states-vulnerabilities-thinkpad-sebas",
        "_id": "001_5a4324d97b01ae617ce9d9a4a64210a15d27cafc_CVE-2022-1665",
        "_score": 1,
        "_source": {
          "agent": {
            "id": "001",
            "name": "centos8",
            "type": "Wazuh",
            "version": "v4.9.0"
          },
          "host": {
            "os": {
              "full": "CentOS Linux 8.5.2111",
              "kernel": "4.18.0-348.7.1.el8_5.x86_64",
              "name": "CentOS Linux",
              "platform": "centos",
              "type": "centos",
              "version": "8.5.2111"
            }
          },
          "package": {
            "architecture": "x86_64",
            "description": "The Linux kernel",
            "installed": "2023-11-01T20:38:26.000Z",
            "name": "kernel-core",
            "size": 70864903,
            "type": "rpm",
            "version": "4.18.0-348.7.1.el8_5"
          },
          "vulnerability": {
            "category": "Packages",
            "classification": "-",
            "description": "DOCUMENTATION: A flaw was found in the Linux kernel, where a set of pre-production kernel packages of Red Hat Enterprise Linux for IBM Power architecture were signed with Red Hat's production secure boot keys. This issue allows kernel versions targeted for testing to eventually boot in PowerPC environments with the Secure Boot feature enabled. An attacker needs high privilege to install the non-production kernel packages in the target machine and make it the default boot option on grub2.",
            "detected_at": "2024-09-25T20:17:52.698Z",
            "enumeration": "CVE",
            "id": "CVE-2022-1665",
            "published_at": "2022-06-21T15:15:08Z",
            "reference": "https://access.redhat.com/security/cve/CVE-2022-1665",
            "scanner": {
              "source": "Red Hat CVE Database",
              "vendor": "Wazuh"
            },
            "score": {
              "base": 8.2,
              "version": "3.1"
            },
            "severity": "High",
            "under_evaluation": false
          },
          "wazuh": {
            "cluster": {
              "name": "Thinkpad-Sebas"
            },
            "schema": {
              "version": "1.0.0"
            }
          }
        }
      }
```

If we verify the CVEs content in CTI:

### Description 🟢 
Matches RedHat's one

- RedHat description: 
  `DOCUMENTATION: A flaw was found in the Linux kernel, where a set of pre-production kernel..` 
- NVD description: 
  `A set of pre-production kernel packages of Red Hat Enterprise Linux for IBM Power architecture can be booted by..`

2024-09-26 23:47 UTC, MiguelazoDS commented
# Testing 

## Environment 

- Manager: Ubuntu Jammy (dev branch) 
- Agent: Centos 9 (v4.8.2) 

## Analysis 

- Raw vulnerabilities (+12k)
[vulnerabilities.tar.gz](https://github.com/user-attachments/files/17157121/vulnerabilities.tar.gz)

###  Vulnerability.source field :green_circle:
![image](https://github.com/user-attachments/assets/24a6d2eb-1953-49f3-8ad9-3c309cfe40ea)

#### Red Hat CVE Database 

```json
{"agent":{"id":"003","name":"centos9","type":"Wazuh","version":"v4.8.2"},"host":{"os":{"full":"CentOS Stream 9","kernel":"5.14.0-378.el9.x86_64","name":"CentOS Stream","platform":"centos","type":"centos","version":"9"}},"package":{"architecture":"x86_64","description":"The shared core libraries and support files for LibreOffice.","installed":"2024-07-03T18:50:49.000Z","name":"libreoffice-core","size":291179591,"type":"rpm","version":"1:7.1.8.1-13.el9"},"vulnerability":{"category":"Packages","classification":"-","description":"DOCUMENTATION: A improper certificate validation flaw was found in LibreOffice allowing an attacker to manipulate a digitally signed ODF document to appear that no alteration of the document occurred since the last signing and that the signature is valid.","detected_at":"2024-09-26T22:58:12.622Z","enumeration":"CVE","id":"CVE-2021-25636","published_at":"2022-02-24T15:15:21Z","reference":"https://access.redhat.com/security/cve/CVE-2021-25636","scanner":{"source":"Red Hat CVE Database","vendor":"Wazuh"},"score":{"base":6.2,"version":"3.1"},"severity":"Medium","under_evaluation":false},"wazuh":{"cluster":{"name":"jammy"},"schema":{"version":"1.0.0"}}}

{"agent":{"id":"003","name":"centos9","type":"Wazuh","version":"v4.8.2"},"host":{"os":{"full":"CentOS Stream 9","kernel":"5.14.0-378.el9.x86_64","name":"CentOS Stream","platform":"centos","type":"centos","version":"9"}},"package":{"architecture":"x86_64","description":"The shared core libraries and support files for LibreOffice.","installed":"2024-07-03T18:50:49.000Z","name":"libreoffice-core","size":291179591,"type":"rpm","version":"1:7.1.8.1-13.el9"},"vulnerability":{"category":"Packages","classification":"-","description":"DOCUMENTATION: An Improper Certificate Validation vulnerability was found in LibreOffice, where determining if a trusted author signed a macro was done by only matching the serial number and issuer string of the used certificate with that of a trusted certificate. This is not sufficient to verify that the macro was actually signed with the certificate. This flaw allows an adversary to create an arbitrary certificate with a serial number and an issuer string identical to a trusted certificate which LibreOffice would present as belonging to the trusted author, potentially leading to the user executing arbitrary code contained in the improperly trusted macros.","detected_at":"2024-09-26T22:58:12.621Z","enumeration":"CVE","id":"CVE-2022-26305","published_at":"2022-07-25T15:15:09Z","reference":"https://access.redhat.com/security/cve/CVE-2022-26305","scanner":{"source":"Red Hat CVE Database","vendor":"Wazuh"},"score":{"base":7.1,"version":"3.1"},"severity":"High","under_evaluation":false},"wazuh":{"cluster":{"name":"jammy"},"schema":{"version":"1.0.0"}}}

{"agent":{"id":"003","name":"centos9","type":"Wazuh","version":"v4.8.2"},"host":{"os":{"full":"CentOS Stream 9","kernel":"5.14.0-378.el9.x86_64","name":"CentOS Stream","platform":"centos","type":"centos","version":"9"}},"package":{"architecture":"x86_64","description":"The shared core libraries and support files for LibreOffice.","installed":"2024-07-03T18:50:49.000Z","name":"libreoffice-core","size":291179591,"type":"rpm","version":"1:7.1.8.1-13.el9"},"vulnerability":{"category":"Packages","classification":"-","description":"DOCUMENTATION: A flaw was found in LibreOffice, where the required initialization vector for encryption was always the same. Stored passwords are encrypted with a single master key provided by the user. This issue weakens the security of the encryption, making them vulnerable if an attacker has access to the user's configuration data.","detected_at":"2024-09-26T22:58:12.621Z","enumeration":"CVE","id":"CVE-2022-26306","published_at":"2022-07-25T15:15:09Z","reference":"https://access.redhat.com/security/cve/CVE-2022-26306","scanner":{"source":"Red Hat CVEDatabase","vendor":"Wazuh"},"score":{"base":7.5,"version":"3.1"},"severity":"High","under_evaluation":false},"wazuh":{"cluster":{"name":"jammy"},"schema":{"version":"1.0.0"}}}

{"agent":{"id":"003","name":"centos9","type":"Wazuh","version":"v4.8.2"},"host":{"os":{"full":"CentOS Stream 9","kernel":"5.14.0-378.el9.x86_64","name":"CentOS Stream","platform":"centos","type":"centos","version":"9"}},"package":{"architecture":"x86_64","description":"The shared core libraries and support files for LibreOffice.","installed":"2024-07-03T18:50:49.000Z","name":"libreoffice-core","size":291179591,"type":"rpm","version":"1:7.1.8.1-13.el9"},"vulnerability":{"category":"Packages","classification":"-","description":"DOCUMENTATION: A flaw was found in LibreOffice, where the master key was poorly encoded, resulting in weakening its entropy from 128 to 43 bits. This issue makes the stored passwords that are encrypted with a single master key provided by the user vulnerable to a brute force attack if an attacker has access to the user’s stored config.","detected_at":"2024-09-26T22:58:12.620Z","enumeration":"CVE","id":"CVE-2022-26307","published_at":"2022-07-25T15:15:09Z","reference":"https://access.redhat.com/security/cve/CVE-2022-26307","scanner":{"source":"Red Hat CVE Database","vendor":"Wazuh"},"score":{"base":8.8,"version":"3.1"},"severity":"High","under_evaluation":false},"wazuh":{"cluster":{"name":"jammy"},"schema":{"version":"1.0.0"}}}

{"agent":{"id":"003","name":"centos9","type":"Wazuh","version":"v4.8.2"},"host":{"os":{"full":"CentOS Stream 9","kernel":"5.14.0-378.el9.x86_64","name":"CentOS Stream","platform":"centos","type":"centos","version":"9"}},"package":{"architecture":"x86_64","description":"The shared core libraries and support files for LibreOffice.","installed":"2024-07-03T18:50:49.000Z","name":"libreoffice-core","size":291179591,"type":"rpm","version":"1:7.1.8.1-13.el9"},"vulnerability":{"category":"Packages","classification":"-","description":"DOCUMENTATION: A vulnerability was found in LibreOffice that affects the Office URI Schemes. These schemes enable browser integration of LibreOffice with the MS SharePoint server. In LibreOffice, the links using the scheme 'vnd.libreoffice.command' could be constructed to call internal macros with arbitrary arguments, which, when clicked, or activated by document events, could result in arbitrary script execution without warning. The attacker must trick the targeted individual into opening a malicious file to trigger the exploit.","detected_at":"2024-09-26T22:58:12.619Z","enumeration":"CVE","id":"CVE-2022-3140","published_at":"2022-10-11T21:15:16Z","reference":"https://access.redhat.com/security/cve/CVE-2022-3140","scanner":{"source":"Red Hat CVE Database","vendor":"Wazuh"},"score":{"base":5.3,"version":"3.1"},"severity":"Medium","under_evaluation":false},"wazuh":{"cluster":{"name":"jammy"},"schema":{"version":"1.0.0"}}}
```

#### Open Source Vulnerability

```json
{"agent":{"id":"003","name":"centos9","type":"Wazuh","version":"v4.8.2"},"host":{"os":{"full":"CentOS Stream 9","kernel":"5.14.0-378.el9.x86_64","name":"CentOS Stream","platform":"centos","type":"centos","version":"9"}},"package":{"name":"idna","path":"/usr/local/lib/python3.9/site-packages/idna-3.6.dist-info/METADATA","size":0,"type":"pypi","version":"3.6"},"vulnerability":{"category":"Packages","classification":"-","description":"### Impact A specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.  ### Patches The function has been refined to reject such strings without the associated resource consumption in version 3.7.  ### Workarounds Domain names cannot ex [...]

2024-09-27 00:16 UTC, MiguelazoDS commented
# Testing 

## Environment 

- Manager: Ubuntu Jammy (dev branch) 
- Agent: Debian Bookworm (v4.8.2) 

## Analysis 

- Raw vulnerabilities (+)

2024-09-27 01:25 UTC, sebasfalcone reviewed
# Functional testing

## Centos 8
### CVE-2024-26838

#### Indexer:
```json
      {
        "_index": "wazuh-states-vulnerabilities-thinkpad-sebas",
        "_id": "001_19925e120611a2d5c4acf440079c390dc0ada4b8_CVE-2024-26838",
        "_score": 1,
        "_source": {
          "agent": {
            "id": "001",
            "name": "centos8",
            "type": "Wazuh",
            "version": "v4.9.0"
          },
          "host": {
            "os": {
              "full": "CentOS Linux 8.5.2111",
              "kernel": "4.18.0-348.7.1.el8_5.x86_64",
              "name": "CentOS Linux",
              "platform": "centos",
              "type": "centos",
              "version": "8.5.2111"
            }
          },
          "package": {
            "architecture": "x86_64",
            "description": "Python bindings for apps which will manipulate perf events",
            "installed": "2023-11-01T20:38:57.000Z",
            "name": "python3-perf",
            "size": 372789,
            "type": "rpm",
            "version": "4.18.0-348.7.1.el8_5"
          },
          "vulnerability": {
            "category": "Packages",
            "classification": "-",
            "description": "DOCUMENTATION: The MITRE CVE dictionary describes this issue as: In the Linux kernel, the following vulnerability has been resolved:  RDMA/irdma: Fix KASAN issue with tasklet  KASAN testing revealed the following issue assocated with freeing an IRQ.  [50006.466686] Call Trace: [50006.466691]  <IRQ> [50006.489538]  dump_stack+0x5c/0x80 [50006.493475]  print_address_description.constprop.6+0x1a/0x150 [50006.499872]  ? irdma_sc_process_ceq+0x483/0x790 [irdma] [50006.505742]  ? irdma_sc_process_ceq+0x483/0x790 [irdma] [50006.511644]  kasan_report.cold.11+0x7f/0x118 [50006.516572]  ? irdma_sc_process_ceq+0x483/0x790 [irdma] [50006.522473]  irdma_sc_process_ceq+0x483/0x790 [irdma] [50006.528232]  irdma_process_ceq+0xb2/0x400 [irdma] [50006.533601]  ? irdma_hw_flush_wqes_callback+0x370/0x370 [irdma] [50006.540298]  irdma_ceq_dpc+0x44/0x100 [irdma] [50006.545306]  tasklet_action_common.isra.14+0x148/0x2c0 [50006.551096]  __do_softirq+0x1d0/0xaf8 [50006.555396]  irq_exit_rcu+0x219/0x260 [50006.559670]  irq_exit+0xa/0x20 [50006.563320]  smp_apic_timer_interrupt+0x1bf/0x690 [50006.568645]  apic_timer_interrupt+0xf/0x20 [50006.573341]  </IRQ>  The issue is that a tasklet could be pending on another core racing the delete of the irq.  Fix by insuring any scheduled tasklet is killed after deleting the irq.",
            "detected_at": "2024-09-27T01:18:30.316Z",
            "enumeration": "CVE",
            "id": "CVE-2024-26838",
            "published_at": "2024-04-17T10:15:09Z",
            "reference": "https://access.redhat.com/security/cve/CVE-2024-26838",
            "scanner": {
              "source": "Red Hat CVE Database",
              "vendor": "Wazuh"
            },
            "score": {
              "base": 4.4,
              "version": "3.1"
            },
            "severity": "Medium",
            "under_evaluation": false
          },
          "wazuh": {
            "cluster": {
              "name": "Thinkpad-Sebas"
            },
            "schema": {
              "version": "1.0.0"
            }
          }
        }
      }
```

#### Description 🟢 
- RedHat: **DOCUMENTATION: The MITRE CVE dictionary describes this issue as: In the Linux kernel, the following vulnerability**
- NVD: **In the Linux kernel, the following vulnerability has been resolved:  RDMA/irdma: Fix KASAN issue with tasklet**
  
#### CVSS 🟢 
- Redhat: 4.4
- NVD: 5.5

2024-09-27 01:39 UTC, sebasfalcone reviewed
# Functional testing
## Pypi
### 
#### Indexer
```json
      {
        "_index": "wazuh-states-vulnerabilities-thinkpad-sebas",
        "_id": "000_2f6e6738cd66732cba19df00662691fa0f272237_CVE-2024-34064",
        "_score": 5.4109426,
        "_source": {
          "agent": {
            "id": "000",
            "name": "Thinkpad-Sebas",
            "type": "Wazuh",
            "version": "v4.10.0"
          },
          "host": {
            "os": {
              "full": "Linux Mint 21.1 (Vera)",
              "kernel": "5.15.0-119-generic",
              "name": "Linux Mint",
              "platform": "linuxmint",
              "type": "linuxmint",
              "version": "21.1"
            }
          },
          "package": {
            "name": "Jinja2",
            "path": "/home/sebas/.local/lib/python3.10/site-packages/Jinja2-3.1.3.dist-info/METADATA",
            "size": 0,
            "type": "pypi",
            "version": "3.1.3"
          },
          "vulnerability": {
            "category": "Packages",
            "classification": "-",
            "description": "Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter",
            "detected_at": "2024-09-27T01:18:09.363Z",
            "enumeration": "CVE",
            "id": "CVE-2024-34064",
            "published_at": "2024-05-06T15:15:23Z",
            "reference": "https://github.com/pallets/jinja, https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb, https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj, https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/567XIGSZMABG6TSMYWD7MIYNJSUQQRUC, https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GCLF44KY43BSVMTE6S53B4V5WP3FRRSE, https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SSCBHIL6BYKR5NRCBXP4XMP2CEEKGFVS, https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZALNWE3TXPPHVPSI3AZ5CTMSTAVN5UMS, https://nvd.nist.gov/vuln/detail/CVE-2024-34064",
            "scanner": {
              "source": "Open Source Vulnerabilities",
              "vendor": "Wazuh"
            },
            "score": {
              "base": 5.4,
              "version": "3.1"
            },
            "severity": "Medium",
            "under_evaluation": false
          },
          "wazuh": {
            "cluster": {
              "name": "Thinkpad-Sebas"
            },
            "schema": {
              "version": "1.0.0"
            }
          }
        }
      }
```

#### Description 🟢 
- OSV: **Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter**
- NVD: **Jinja is an extensible templating engine. The `xmlattr` filter in affected version**

#### CVSS 🟢 
- OSV: **5.4**
- NVD: **5.4**

2024-09-27 16:08 UTC, sebasfalcone reviewed
# Functional testing
## CVE-2022-40023 - CVSS information not in ADP
This test verifies that the NVD information is used if the ADP doesn't have the corresponding information

#### Indexer 
```json
      {
        "_index": "wazuh-states-vulnerabilities-thinkpad-sebas",
        "_id": "000_f862ea4e955d202b0a5aa16e83d96e4ad9cdee09_CVE-2022-40023",
        "_score": 14.753093,
        "_source": {
          "agent": {
            "id": "000",
            "name": "Thinkpad-Sebas",
            "type": "Wazuh",
            "version": "v4.10.0"
          },
          "host": {
            "os": {
              "full": "Linux Mint 21.1 (Vera)",
              "kernel": "5.15.0-119-generic",
              "name": "Linux Mint",
              "platform": "linuxmint",
              "type": "linuxmint",
              "version": "21.1"
            }
          },
          "package": {
            "name": "Mako",
            "path": "/usr/lib/python3/dist-packages/Mako-1.1.3-py3.10.egg-info/PKG-INFO",
            "size": 0,
            "type": "pypi",
            "version": "1.1.3"
          },
          "vulnerability": {
            "category": "Packages",
            "classification": "CVSS",
            "description": "mako is vulnerable to Regular Expression Denial of Service",
            "detected_at": "2024-09-27T16:00:37.634Z",
            "enumeration": "CVE",
            "id": "CVE-2022-40023",
            "published_at": "2022-09-07T13:15:09Z",
            "reference": "https://github.com/advisories/GHSA-v973-fxgf-6xhp, https://github.com/pypa/advisory-database/tree/main/vulns/mako/PYSEC-2022-260.yaml, https://github.com/sqlalchemy/mako, https://github.com/sqlalchemy/mako/blob/c2f392e0be52dc67d1b9770ab8cce6a9c736d547/mako/ext/extract.py#L21, https://github.com/sqlalchemy/mako/commit/925760291d6efec64fda6e9dd1fd9cfbd5be068c, https://github.com/sqlalchemy/mako/issues/366, https://lists.debian.org/debian-lts-announce/2022/09/msg00026.html, https://nvd.nist.gov/vuln/detail/CVE-2022-40023, https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages, https://pyup.io/vulnerabilities/CVE-2022-40023/50870, https://pyup.io/vulnerabilities/CVE-2022-40023/50870/",
            "scanner": {
              "source": "Open Source Vulnerabilities",
              "vendor": "Wazuh"
            },
            "score": {
              "base": 7.5,
              "version": "3.1"
            },
            "severity": "High",
            "under_evaluation": false
          },
          "wazuh": {
            "cluster": {
              "name": "Thinkpad-Sebas"
            },
            "schema": {
              "version": "1.0.0"
            }
          }
        }
      }
```
#### Description 🟢 
- Pypi: **mako is vulnerable to Regular Expression Denial of Service**
- NVD: **Sqlalchemy mako before 1.2.2 is vulnerable to Regular expression Denial of Service when using the Lexer class to parse. This also affects babelplugin and linguaplugin.**

#### CVSS 🟢 
- Pypi: **null**
- NVD: **7.5**

2024-09-30 02:32 UTC, Dwordcito approved these changes

2024-09-30 02:33 UTC, merged