Fix Upgrading Windows agent via WPK
wazuh/wazuh pull request #25699
Opened 2024-09-12 01:22 UTC by cborla

|Related issue|
|---|
|Close #25086|

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [x] Windows
- [x] Package installation
- [x] Package upgrade

2024-09-12 02:00 UTC, cborla commented
# Testing case 1 
After executing the failure case 10 times continuously, the timeout error is not observed. 

``` shell
workspace/wpk-test# time /var/ossec/bin/agent_upgrade -a 003 -F -f /tmp/wazuh-agent.wpk 

Upgrading...

Upgraded agents:
	Agent 003 upgraded: Wazuh v4.9.0 -> Wazuh v4.9.0

real	2m15,315s
user	0m1,931s
sys	0m0,332s


workspace/wpk-test# time /var/ossec/bin/agent_upgrade -a 003 -F -f /tmp/wazuh-agent.wpk 

Upgrading...

Upgraded agents:
	Agent 003 upgraded: Wazuh v4.9.0 -> Wazuh v4.9.0

real	1m32,459s
user	0m1,642s
sys	0m0,267s


workspace/wpk-test# time /var/ossec/bin/agent_upgrade -a 003 -F -f /tmp/wazuh-agent.wpk 

Upgrading...

Upgraded agents:
	Agent 003 upgraded: Wazuh v4.9.0 -> Wazuh v4.9.0

real	1m29,384s
user	0m1,689s
sys	0m0,263s


workspace/wpk-test# time /var/ossec/bin/agent_upgrade -a 003 -F -f /tmp/wazuh-agent.wpk 

Upgrading...

Upgraded agents:
	Agent 003 upgraded: Wazuh v4.9.0 -> Wazuh v4.9.0

real	1m53,597s
user	0m1,751s
sys	0m0,303s


workspace/wpk-test# time /var/ossec/bin/agent_upgrade -a 003 -F -f /tmp/wazuh-agent.wpk 

Upgrading...

Upgraded agents:
	Agent 003 upgraded: Wazuh v4.9.0 -> Wazuh v4.9.0

real	1m38,528s
user	0m1,837s
sys	0m0,273s


workspace/wpk-test# time /var/ossec/bin/agent_upgrade -a 003 -F -f /tmp/wazuh-agent.wpk 

Upgrading...

Upgraded agents:
	Agent 003 upgraded: Wazuh v4.9.0 -> Wazuh v4.9.0

real	2m6,152s
user	0m2,188s
sys	0m0,363s
```

2024-09-12 06:42 UTC, vikman90 reviewed
@cborla The change makes sense. 

However, I have not been able to understand under what conditions the problem occurs. 

Please clarify in the main comment the exact cause of the problem, the motivation for proposing this solution, and the version of Windows you tested on. This will help us to understand the bug and to make related changes in the future.

Thank you!

2024-09-19 01:52 UTC, cborla commented
# Test case after the fix 🟢 

### Agent Windows version
``` 
Edition	Windows Server 2022 Standard Evaluation
Version	21H2
Installed on	‎6/‎10/‎2024
OS build	20348.2402
```
For this test, a custom wpk was generated, following the steps of the following [commentary ](https://github.com/wazuh/wazuh/issues/25086#issuecomment-2342505502)
[custom_wpk.zip](https://github.com/user-attachments/files/17052337/custom_wpk.zip)

### Test - Forcing upgrade from 4.9.0 to 4.9.0 (using a custom wpk) 🟢 
After executing the failure case several times continuously, the timeout error is not observed. 

``` shell
# time /var/ossec/bin/agent_upgrade -a 022 -F -f /tmp/wazuh-agent3.wpk 

Upgrading...

Upgraded agents:
	Agent 022 upgraded: Wazuh v4.9.0 -> Wazuh v4.9.0

real	1m8,069s
user	0m1,426s
sys	0m0,197s
```

Agent upgrade.log

```log
2024-09-18 22:18:43Z - Sysnative Powershell will be used to access the registry.
2024-09-18 22:18:47Z - Current version: v4.9.0.
2024-09-18 22:18:48Z - MSI new version: v4.9.0.
2024-09-18 22:18:48Z - Starting upgrade process.
2024-09-18 22:18:48Z - Reinstalling the same version.
2024-09-18 22:18:53Z - Waiting for the Wazuh-Agent installation to end.
2024-09-18 22:18:55Z - Waiting for the Wazuh-Agent installation to end.
2024-09-18 22:18:57Z - Waiting for the Wazuh-Agent installation to end.
2024-09-18 22:18:59Z - Waiting for the Wazuh-Agent installation to end.
2024-09-18 22:19:01Z - Waiting for the Wazuh-Agent installation to end.
2024-09-18 22:19:03Z - Starting Wazuh-Agent service.
2024-09-18 22:19:03Z - Installation finished.
2024-09-18 22:19:03Z - Process ID: 2292.
2024-09-18 22:19:13Z - Reading status file: status='connected'.
2024-09-18 22:19:13Z - Upgrade finished successfully.
2024-09-18 22:19:13Z - New version: v4.9.0.

```


<details><summary>installer.txt</summary>

```
=== Logging started: 9/18/2024  22:18:49 ===
Action start 22:18:49: INSTALL.
Action start 22:18:49: FindRelatedProducts.
Action ended 22:18:49: FindRelatedProducts. Return value 0.
Action start 22:18:49: CheckSvcRunning.
Action ended 22:18:49: CheckSvcRunning. Return value 0.
Action start 22:18:49: AppSearch.
Action ended 22:18:49: AppSearch. Return value 1.
Action start 22:18:49: ValidateProductID.	
Action ended 22:18:49: ValidateProductID. Return value 1.
Action start 22:18:49: CostInitialize.
Action ended 22:18:49: CostInitialize. Return value 1.
Action start 22:18:49: FileCost.
Action ended 22:18:49: FileCost. Return value 1.
Action start 22:18:49: WixSetDefaultPerUserFolder.
Action ended 22:18:49: WixSetDefaultPerUserFolder. Return value 1.
Action start 22:18:49: WixSetDefaultPerMachineFolder.
Action ended 22:18:49: WixSetDefaultPerMachineFolder. Return value 1.
Action start 22:18:49: CostFinalize.
Action ended 22:18:50: CostFinalize. Return value 1.
Action start 22:18:50: MigrateFeatureStates.
Action ended 22:18:50: MigrateFeatureStates. Return value 0.
Action start 22:18:50: InstallValidate.
Info 1603.The file C:\Program Files (x86)\ossec-agent\wazuh-agent.exe is being held in use by the following process: Name: wazuh-agent, Id: 1964, Window Title: '(not determined yet)'.  Close that application and retry.
Action ended 22:18:51: InstallValidate. Return value 1.
Action start 22:18:51: InstallInitialize.
Action ended 22:18:51: InstallInitialize. Return value 1.
Action start 22:18:51: RemoveExistingProducts.
Action ended 22:18:51: RemoveExistingProducts. Return value 0.
Action start 22:18:51: ProcessComponents.
Action ended 22:18:51: ProcessComponents. Return value 1.
Action start 22:18:51: UnpublishFeatures.
Action ended 22:18:51: UnpublishFeatures. Return value 1.
Action start 22:18:51: SchedSecureObjectsRollback.
SchedSecureObjectsRollback:  Entering SchedSecureObjectsRollback in C:\Windows\Installer\MSI2379.tmp, version 3.11.4516.0
Action start 22:18:51: ExecSecureObjectsRollback.
Action ended 22:18:51: ExecSecureObjectsRollback. Return value 1.
Action ended 22:18:51: SchedSecureObjectsRollback. Return value 1.
Action start 22:18:51: StopServices.
Action ended 22:18:51: StopServices. Return value 1.
Action start 22:18:51: DeleteServices.
Action ended 22:18:51: DeleteServices. Return value 1.
Action start 22:18:51: RemoveRegistryValues.
Action ended 22:18:51: RemoveRegistryValues. Return value 1.
Action start 22:18:51: RemoveShortcuts.
Action ended 22:18:51: RemoveShortcuts. Return value 1.
Action start 22:18:51: RemoveFiles.
Action ended 22:18:51: RemoveFiles. Return value 1.
Action start 22:18:51: WixSchedInternetShortcuts.
WixSchedInternetShortcuts:  Entering WixSchedInternetShortcuts in C:\Windows\Installer\MSI23B8.tmp, version 3.11.4516.0
WixSchedInternetShortcuts:  Adding folder 'ProgramMenuDir', component 'StartMenuShortcuts' to the CreateFolder table
Action ended 22:18:51: WixSchedInternetShortcuts. Return value 1.
Action start 22:18:51: RemoveFolders.
Action ended 22:18:51: RemoveFolders. Return value 1.
Action start 22:18:51: CreateFolders.
Action ended 22:18:51: CreateFolders. Return value 1.
Action start 22:18:51: InstallFiles.
Action ended 22:18:51: InstallFiles. Return value 1.
Action start 22:18:51: CreateShortcuts.
Action ended 22:18:51: CreateShortcuts. Return value 1.
Action start 22:18:51: WixRollbackInternetShortcuts.
Action ended 22:18:51: WixRollbackInternetShortcuts. Return value 1.
Action start 22:18:51: WixCreateInternetShortcuts.
Action ended 22:18:51: WixCreateInternetShortcuts. Return value 1.
Action start 22:18:51: WriteRegistryValues.
Action ended 22:18:51: WriteRegistryValues. Return value 1.
Action start 22:18:51: InstallServices.
Action ended 22:18:51: InstallServices. Return value 1.
Action start 22:18:51: SchedSecureObjects.
SchedSecureObjects:  Entering SchedSecureObjects in C:\Windows\Installer\MSI2475.tmp, version 3.11.4516.0
Action ended 22:18:51: SchedSecureObjects. Return value 1.
Action start 22:18:51: StartServices.
Action ended 22:18:51: StartServices. Return value 1.
Action start 22:18:51: RegisterUser.
Action ended 22:18:51: RegisterUser. Return value 0.
Action start 22:18:51: RegisterProduct.
Action ended 22:18:51: RegisterProduct. Return value 1.
Action start 22:18:51: PublishFeatures.
Action ended 22:18:51: PublishFeatures. Return value 1.
Action start 22:18:51: PublishProduct.
Action ended 22:18:51: PublishProduct. Return value 1.
Action start 22:18:51: CloseGUI.
Action ended 22:18:51: CloseGUI. Return value 1.
Action start 22:18:51: InstallFinalize.
WixCreateInternetShortcuts:  Entering WixCreateInternetShortcuts in C:\Windows\Installer\MSI2B8A.tmp, version 3.11.4516.0
WixCreateInternetShortcuts:  Creating IShellLinkW shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\OSSEC\Documentation.lnk' target 'https://documentation.wazuh.com'
Action ended 22:18:53: InstallFinalize. Return value 1.
Action ended 22:18:53: INSTALL. Return value 1.
Property(S): UpgradeCode = {F495AC57-7BDE-4C4B-92D8-DBE40A9AA5A0}
Property(S): MAJORVERSION = #10
Property(S): BUILDVERSION = 20348
Property(S): APPLICATIONFOLDER = C:\Program Files (x86)\ossec-agent\
Property(S): WAZUHINSTALLED = Wazuh
Property(S): BIN = C:\Program Files (x86)\ossec-agent\active-response\bin\
Property(S): ACTIVE_RESPONSE = C:\Program Files (x86)\ossec-agent\active-response\
Property(S): SHARED = C:\Program Files (x86)\ossec-agent\shared\
Property(S): SECURITY_CONFIGURATION_ASSESSMENT = C:\Program Files (x86)\ossec-agent\ruleset\sca\
Property(S): SYSCOLLECTOR = C:\Program Files (x86)\ossec-agent\queue\syscollector\
Property(S): ProgramMenuDir = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\OSSEC\
Property(S): TMP = C:\Program Files (x86)\ossec-agent\tmp\
Property(S): QUEUE = C:\Program Files (x86)\ossec-agent\queue\
Property(S): DIFF = C:\Program Files (x86)\ossec-agent\queue\diff\
Property(S): FIM = C:\Program Files (x86)\ossec-agent\queue\fim\
Property(S): FIM_DB = C:\Program Files (x86)\ossec-agent\queue\fim\db\
Property(S): SYSCOLLECTOR_DB = C:\Program Files (x86)\ossec-agent\queue\syscollector\db\
Property(S): LOGCOLLECTOR = C:\Progra [...]

2024-09-19 07:05 UTC, vikman90 requested changes
@cborla GJ on this PR. I like how you have managed to extract the product version from the MSI file.

I would like to find out how to avoid the loop that wait for the log file. Indeed, `msiexec` runs in background by default. However, I think we could wait for it with something like this:

```powershell
Start-Process -Wait msiexec.exe -ArgumentList '/a "$msiPath" /qn TARGETDIR=$env:TEMP /lv* msi_output.txt'
```

Let me know your thoughts about this.

2024-09-19 22:39 UTC, cborla commented
@vikman90 
The commands have been updated according to your suggestion, the PR is updated and ready for review.

I have also tested the status of the directory in the force of the same version, being that the new parameters are included, I took the status of the directory with version 4.9.0 before the upgrade, and then compared it with the status after the forced upgrade, without finding any problems.

The script used was.

```bash

param (
    [string]$Directory = "C:\Program Files (x86)\ossec-agent",
    [string]$OutputFile
)

function Export-DirectoryInfo {
    param (
        [string]$Dir,
        [string]$Output
    )

    # Obtenemos la información de los archivos
    Get-ChildItem -Recurse -Path $Dir | ForEach-Object {
        $acl = Get-Acl $_.FullName
        [PSCustomObject]@{
            Path = $_.FullName
            Permissions = $acl.Access | ForEach-Object {
                "$($_.IdentityReference) $($_.FileSystemRights) $($_.AccessControlType)"
            }
            Owner = $acl.Owner
            CreationTime = $_.CreationTime
            LastAccessTime = $_.LastAccessTime
            LastWriteTime = $_.LastWriteTime
            Size = if ($_.PSIsContainer) { "Directory" } else { $_.Length }
        }
    } | Export-Csv -Path $Output -NoTypeInformation
}

# Llamamos a la función para exportar la información del directorio
Export-DirectoryInfo -Dir $Directory -Output $OutputFile

Write-Host "Información del directorio exportada a $OutputFile"


```
The resulting files are:
- [backup_before_upgrade.csv](https://github.com/user-attachments/files/17067570/backup_before_upgrade.csv)
- [backup_after_upgrade.csv](https://github.com/user-attachments/files/17067571/backup_after_upgrade.csv)

2024-09-20 07:46 UTC, vikman90 approved these changes

2024-09-20 07:46 UTC, merged