Assign placeholder for missing field values in alerts
wazuh/wazuh pull request #25711
Opened 2024-09-13 20:18 UTC by GabrielEValenzuela

| Related issue |
| --- |
| #25484 |

# Description
This PR introduces logic to automatically assign a hyphen (`-`) as a placeholder for fields that lack values: `score.base`, `score.version`, `severity`, and `classification`. This update ensures consistent handling of empty or undefined fields across the system.

The field replacement is implemented according to the current index template used by alerts, and a unit test (UT) has been added to cover this new scenario.

2024-09-13 20:31 UTC, sebasfalcone requested changes

2024-09-13 20:31 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/eventPackageAlertDetailsBuilder.hpp
As seen here:
- https://github.com/wazuh/wazuh/blob/520e9611657f8da9b28ce6b91b1860d20d98fc82/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/eventDetailsBuilder.hpp#L218-L221

Some fields can be empty when we assign them

We should add a more generic logic. Maybe iterate the fields of the final array and fill the empty strings with the corresponding "-" or "-1"

2024-09-13 23:15 UTC, GabrielEValenzuela commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/eventPackageAlertDetailsBuilder.hpp
Nice idea, @sebasfalcone! 😊

I’ve created a helper function to handle the logic and applied it to the fields you mentioned. If you'd like me to add it to more fields or move the helper function to a different folder, just let me know!

Thanks for the suggestion! 🦾

2024-09-16 17:07 UTC, sebasfalcone reviewed
## Tests
I've added a CentOS 8 agent and checked the indexed vulnerabilities for this cases

```json
      {
        "_index": "wazuh-states-vulnerabilities-thinkpad-sebas",
        "_id": "001_55c76af225bcb6340ea4fd0ba8005e8c7284df69_CVE-2022-48648",
        "_score": 1,
        "_source": {
          "agent": {
            "id": "001",
            "name": "centos8",
            "type": "wazuh",
            "version": "v4.9.0"
          },
          "host": {
            "os": {
              "full": "CentOS Linux 8.5.2111",
              "kernel": "4.18.0-348.7.1.el8_5.x86_64",
              "name": "CentOS Linux",
              "platform": "centos",
              "type": "centos",
              "version": "8.5.2111"
            }
          },
          "package": {
            "architecture": "x86_64",
            "description": "The Linux kernel, based on version 4.18.0, heavily modified with backports",
            "installed": "2023-11-01T20:38:59.000Z",
            "name": "kernel",
            "size": 0,
            "type": "rpm",
            "version": "4.18.0-348.7.1.el8_5"
          },
          "vulnerability": {
            "category": "Packages",
            "classification": "-",
            "description": "In the Linux kernel, the following vulnerability has been resolved:  sfc: fix null pointer dereference in efx_hard_start_xmit  Trying to get the channel from the tx_queue variable here is wrong because we can only be here if tx_queue is NULL, so we shouldn't dereference it. As the above comment in the code says, this is very unlikely to happen, but it's wrong anyway so let's fix it.  I hit this issue because of a different bug that caused tx_queue to be NULL. If that happens, this is the error message that we get here:   BUG: unable to handle kernel NULL pointer dereference at 0000000000000020   [...]   RIP: 0010:efx_hard_start_xmit+0x153/0x170 [sfc]",
            "detected_at": "2024-09-16T16:37:02.580Z",
            "enumeration": "CVE",
            "id": "CVE-2022-48648",
            "published_at": "2024-04-28T13:15:07Z",
            "reference": "https://git.kernel.org/stable/c/0a242eb2913a4aa3d6fbdb86559f27628e9466f3, https://git.kernel.org/stable/c/8547c7bfc0617e7184e4da65b9b96681fcfe9998, https://git.kernel.org/stable/c/b3b41d4d95d3822b2e459ecbc80d030ea6aec5e7, https://git.kernel.org/stable/c/b3b952168ee1f220ba729fa100fd9d5aa752eb03",
            "scanner": {
              "vendor": "Wazuh"
            },
            "score": {
              "base": -1,
              "version": ""
            },
            "severity": "-",
            "under_evaluation": true
          },
          "wazuh": {
            "cluster": {
              "name": "Thinkpad-Sebas"
            },
            "schema": {
              "version": "1.0.0"
            }
          }
        }
      },
```

See that expected fields are filled with expected default values
```json
            "score": {
              "base": -1,
              "version": ""
            },
            "severity": "-",
            "under_evaluation": true
```

2024-09-16 17:07 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/fieldAlertHelper.hpp
> +        }
Can this be a static assert?

2024-09-17 00:08 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/fieldAlertHelper.hpp
> +     *  - If the value is an integral type, the field is populated only if the value is non-negative.
This is not implemented and it should

2024-09-17 00:20 UTC, GabrielEValenzuela commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/fieldAlertHelper.hpp
> +     *  - If the value is an integral type, the field is populated only if the value is non-negative.
Done!

2024-09-17 19:16 UTC, sebasfalcone requested changes

2024-09-17 19:16 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/cveSolvedAlertDetailsBuilder.hpp
> +                    json["vulnerability"]["rationale"] = "-";
Revert
```suggestion
```

2024-09-17 19:16 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/cveSolvedAlertDetailsBuilder.hpp
> +                    json["vulnerability"]["cwe_reference"] = "-";
Revert
```suggestion
```

2024-09-17 19:35 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/cveSolvedAlertDetailsBuilder.hpp
> +                                Utils::floatToDoubleRound(returnData.data->scoreBase(), 2));
This field is not in the ones requested

2024-09-17 19:35 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/eventPackageAlertDetailsBuilder.hpp
> +                            FieldAlertHelper::fillEmptyOrNegative(
Ditto

2024-09-18 01:48 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOsAlertDetailsBuilder.hpp
> +                                Utils::floatToDoubleRound(returnData.data->scoreBase(), 2));
```suggestion
                            Utils::floatToDoubleRound(returnData.data->scoreBase(), 2);
```

2024-09-18 01:50 UTC, sebasfalcone approved these changes
LGTM!

2024-09-18 02:48 UTC, Dwordcito approved these changes

2024-09-18 02:48 UTC, Dwordcito commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/fieldAlertHelper.hpp
> +#include "numericHelper.h"
unused

2024-09-18 02:48 UTC, Dwordcito commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/fieldAlertHelper.hpp
> +#include "numericHelper.h"
```suggestion
```

2024-09-18 03:29 UTC, merged