Fix compilation in HP-UX/AIX systems removing anti_tampering functionality
wazuh/wazuh pull request #25791
Opened 2024-09-19 12:57 UTC by jotacarma90

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/25789|

## Description
Removing getopt lib from HP-UX and AIX compilation.

# Testing
Tested basic antitampering functionality in Ubuntu, it worked without problems.

Using:
![image](https://github.com/user-attachments/assets/1605a228-c39f-4f40-8db3-f783eaf346a7)

Execution pipelines:
- HP-UX: https://ci.wazuh.info/job/Packages_builder_special/1088/🟢 
- AIX: https://ci.wazuh.info/job/Packages_builder_special/1087/🟢 
- Solaris 10: https://ci.wazuh.info/job/Packages_builder_solaris/31880/🟢 
- Solaris 11: https://ci.wazuh.info/job/Packages_builder_solaris/31881/🟢

2024-09-20 12:07 UTC, MarcelKemp approved these changes

2024-09-20 15:06 UTC, MarcelKemp requested changes
After performing a compilation test for a Solaris 10 agent, I have encountered the following error:
```
In file included from ./headers/shared.h:289:0,
                 from client-agent/buffer.c:13:
./headers/url.h:15:48: fatal error: ../external/curl/include/curl/curl.h: No such file or directory
compilation terminated.
In file included from ./headers/shared.h:289:0,
                 from client-agent/agcom.c:11:
./headers/url.h:15:48: fatal error: ../external/curl/include/curl/curl.h: No such file or directory
compilation terminated.
gmake[1]: *** [Makefile:2087: client-agent/buffer.o] Error 1
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: *** [Makefile:2087: client-agent/agcom.o] Error 1
In file included from ./headers/shared.h:289:0,
                 from client-agent/agentd.c:11:
./headers/url.h:15:48: fatal error: ../external/curl/include/curl/curl.h: No such file or directory
compilation terminated.
In file included from ./headers/shared.h:289:0,
                 from client-agent/config.c:11:
./headers/url.h:15:48: fatal error: ../external/curl/include/curl/curl.h: No such file or directory
compilation terminated.
gmake[1]: *** [Makefile:2087: client-agent/agentd.o] Error 1
gmake[1]: *** [Makefile:2087: client-agent/config.o] Error 1
gmake[1]: Leaving directory '/export/home/vagrant/wazuh/src'
gmake: *** [Makefile:859: agent] Error 2
```

We will check the bug and fix it.

2024-09-23 15:11 UTC, jotacarma90 commented
Added filter to remove anti_tampering from Solaris too.

2024-09-23 15:21 UTC, MarcelKemp approved these changes

2024-09-23 15:52 UTC, merged