Use a cluster by default
wazuh/wazuh pull request #25896
Opened 2024-09-23 15:43 UTC by GGP1

|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/25895 |

## Description

Introduces modifications to always use a cluster of nodes and to set the default bind address to `localhost` (previously `0.0.0.0`).

## Tests

WIP

2024-10-03 14:17 UTC, nico-stefani requested changes
GJ! Just a small thing to note

2024-10-03 15:20 UTC, nico-stefani submitted a review, later dismissed
LGTM

2024-10-04 15:06 UTC, fdalmaup requested changes

2024-10-04 15:06 UTC, fdalmaup commented on framework/wazuh/manager.py
We should analyze if the `manager:` related actions should be completely removed and how we will manage the permissions related to it.

2024-10-07 14:30 UTC, fdalmaup commented on framework/wazuh/rbac/default/policies.yaml
> -          - cluster:status
We should not remove this.

2024-10-09 13:34 UTC, fdalmaup approved these changes
LGTM! GJ :clap:

2024-10-09 13:34 UTC, merged