Add `POST /vulnerability/scan` endpoint
wazuh/wazuh pull request #26228
Opened 2024-10-08 18:17 UTC by GGP1

|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/25621 |

## Description

Adds the `POST /api/v1/vulnerability/scan` endpoint to the Communications API

## Tests

<details><summary>Vulnerable package found</summary>

```console
root@wazuh-master:/# curl -sSk -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -X POST --data '{
  "type": "packagelist",
  "agent": {
    "id": "001"
  },               
  "packages": [
    {          
      "architecture": "amd64",
      "checksum": "1e6ce14f97f57d1bbd46ff8e5d3e133171a1bbce",
      "description": "NSS",
      "format": "rpm",                                             
      "groups": "libs",
      "item_id": "ec465b7eb5fa011a336e95614072e4c7f1a65a53",
      "multiarch": "same",
      "name": "nss",                                              
      "priority": "optional",
      "scan_time": "2023/08/04 19:56:11",
      "size": 72,
      "source": "nss",
      "vendor": "Red Hat, Inc.",
      "version": "3.53.1-3.el7_9"
    }                                 
  ],                                   
  "hotfixes": [],
  "os": {
    "architecture": "x86_64",
    "checksum": "1691178971959743855",
    "hostname": "redhat",
    "codename": "7",
    "major_version": "7",
    "minor_version": "9",
    "name": "Redhat",
    "patch": "6",
    "platform": "rhel",
    "version": "7.9",
    "scan_time": "2023/08/04 19:56:11",
    "kernel_release": "5.4.0-155-generic",
    "kernel_name": "Linux",
    "kernel_version": "#172-Ubuntu SMP Fri Jul 7 16:10:02 UTC 2023"
  }                                       
}' https://0.0.0.0:27000/api/v1/vulnerability/scan | jq
{
  "vulnerabilities": [
    {
      "assigner": "mozilla",
      "category": "Packages",
      "classification": "CVSS",
      "condition": "Package default status",
      "cvss": {
        "cvss3": {
          "vector": {
            "attack_vector": "",
            "availability": "NONE",
            "confidentiality_impact": "LOW",
            "integrity_impact": "NONE",
            "privileges_required": "NONE",
            "scope": "UNCHANGED",
            "user_interaction": "REQUIRED"
          }
        }
      },
      "cwe_reference": "CWE-203",
      "description": "Multiple NSS NIST curves were susceptible to a side-channel attack known as \"Minerva\". This attack could potentially allow an attacker to recover the private key. This vulnerability affects Firefox < 121.",
      "detected_at": "2024-09-05T01:25:27.452Z",
      "enumeration": "CVE",
      "id": "CVE-2023-6135",
      "item_id": "CVE-2023-6135",
      "published_at": "2023-12-19",
      "score": "4.3",
      "severity": "Medium",
      "updated": "2024-01-07"
    }
  ]
}
```

</details>

<details><summary>No vulnerable packages found</summary>

```console
root@wazuh-master:/# curl -sSkv --header "Content-Type: application/json" -X POST --data '{"type": "packagelist", "packages": []}' https://0.0.0.0:27000/api/v1/vulnerability/scan
> POST /api/v1/vulnerability/scan HTTP/1.1
> Host: 0.0.0.0:27000
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 39
> 
< HTTP/1.1 200 OK
< date: Tue, 08 Oct 2024 17:50:06 GMT
< server: uvicorn
< content-length: 0
< server: Wazuh
< strict-transport-security: max-age=63072000; includeSubdomains
< x-frame-options: deny
< x-xss-protection: 0
< x-content-type-options: nosniff
< content-security-policy: none
< referrer-policy: no-referrer, strict-origin-when-cross-origin
< cache-control: no-store
< 
* Connection #0 to host 0.0.0.0 left intact
<Empty response>
```

</details>

<details><summary>Request missing a required field</summary>

```console
root@wazuh-master:/# curl -sSk -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -X POST --data '{
    "type": "fullscan",
    "agent":
    {          
        "id": "01915801-4b34-7131-9d88-ff06ff05aefd"
    },         
    "packages":
    [                         
        {                                                    
            "architecture": "amd64",
            "checksum": "1e6ce14f97f57d1bbd46ff8e5d3e133171a1bbce",
            "description": "NSS",
            "format": "rpm",
            "groups": "libs",
            "item_id": "ec465b7eb5fa011a336e95614072e4c7f1a65a53",
            "multiarch": "same",
            "name": "nss",
            "priority": "optional",
            "scan_time": "2023/08/04 19:56:11",
            "size": 72,
            "source": "nss",
            "vendor": "Red Hat, Inc.",
            "version": "3.53.1-3.el7_9"
        }
    ],
    "hotfixes":
    [],                               
    "os":                
    {               
        "architecture": "x86_64",
        "checksum": "1713967856394802400",
        "hostname": "DESKTOP-EQ4F57D",
        "major_version": "10",
        "minor_version": "0",
        "build": "19045.4291",
        "name": "Microsoft Windows 10 Pro",
        "display_version": "22H2",
        "platform": "windows",
        "version": "10.0.19045.4291",
        "scan_time": "2024/04/24 14:00:00"
    }
}' https://0.0.0.0:27000/api/v1/vulnerability/scan | jq
{
  "message": "('body', 'os', 'codename') field required",
  "code": 400
}
```

</details>

<details><summary>Engine client permission denied error</summary>

```console
root@wazuh-master:/# curl -sSk -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -X POST --data '{
  "type": "packagelist",
  "agent": {
    "id": "001"
  },               
  "packages": [
    {          
      "architecture": "amd64",
      "checksum": "1e6ce14f97f57d1bbd46ff8e5d3e133171a1bbce",
      "description": "NSS",
      "format": "rpm",                                             
      "groups": "libs",
      "item_id": "ec465b7eb5fa011a336e95614072e4c7f1a65a53",
      "multiarch": "same",
      "name": "nss",                                              
      "priority": "optional",
      "scan_time": "2023/08/04 19:56:11",
      "size": 72,
      "source": "nss",
      "vendor": "Red Hat, Inc.",
      "version": "3.53.1-3.el7_9"
    }
  ],                                   
  "hotfixes": [],
  "os": {
    "architecture": "x86_64",
    "checksum": "1691178971959743855",
    "hostname": "redhat",
    "codename": "7",
    "major_version": "7",
    "minor_version": "9",
    "name": "Redhat",
    "patch": "6",
    "platform": "rhel",
    "version": "7.9",
    "scan_time": "2023/08/04 19:56:11",
    "kernel_release": "5.4.0-155-generic",
    "kernel_name": "Linux",
    "kernel_version": "#172-Ubuntu SMP Fri Jul 7 16:10:02 UTC 2023"
  }                                       
}' https://0.0.0.0:27000/api/v1/vulnerability/scan | jq
{
  "message": "Error sending HTTP request: [Errno 13] Permission denied",
  "code": 2803
}
```

</details>

2024-10-10 14:24 UTC, nico-stefani requested changes

2024-10-14 14:08 UTC, nico-stefani approved these changes
LGTM

2024-10-15 09:59 UTC, fdalmaup requested changes

2024-10-15 09:59 UTC, fdalmaup commented on framework/wazuh/core/engine/vulnerability.py
> +                url=f'{self.API_URL}/vulnerability/scan',
```suggestion
                url=f'{self.API_URL}/{self.MODULE}/scan',
```

2024-10-15 15:25 UTC, fdalmaup approved these changes
LGTM!

2024-10-15 15:25 UTC, merged