Add timeout to HTTPX calls
wazuh/wazuh pull request #26222
Opened 2024-10-08 15:05 UTC by DamianNud

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/25973|

## Description

As commented [here](https://github.com/wazuh/wazuh/issues/25973#issuecomment-2397986246), it was decided to specify a timeout of 10 seconds to each `httpx` call, which sets 5 seconds by default, to be consistent across all calls and with the Management API.

No new definitions were added to the exception catching of each call because `httpx.TimeoutException` inherits from `httpx.RequestError`, which means that the specific timeout error will be caught with its parent class.

There were no changes in the behavior of the calls besides increasing the default timeout value.

2024-10-08 18:34 UTC, GGP1 requested changes
We could update the unit tests to assert that the `httpx.AsyncClient` mocked instances are being called with the timeouts specified.

This way, we ensure that if they are removed in the future, the tests will fail and we will notice it.

2024-10-08 18:34 UTC, GGP1 commented on framework/wazuh/core/manager.py
> +DEFAULT_TIMEOUT = 10.0
Add a new line to conform with the PEP8 style guide (classes should be separed by two empty lines)

```suggestion
DEFAULT_TIMEOUT = 10.0

```

2024-10-09 15:07 UTC, DamianNud commented
@GGP1 That is a good idea. I just added test cases checking that `httpx` is called with a timeout.

2024-10-09 15:45 UTC, GGP1 approved these changes
LGTM

2024-10-10 10:06 UTC, fdalmaup approved these changes
LGTM, although the ones related to the HAPHelper could have been omitted and the Bandit alerts dismissed since the component will be removed in 5.0.

2024-10-10 10:07 UTC, merged