Engine simplify cli
wazuh/wazuh pull request #26355
Opened 2024-10-16 18:20 UTC by juliancnn

Closes #25811

In summary this PR:
- Removes CLI11 from wazuh-engine.
- Remove all CLI wazuh-engine parameters
- Adapt all internal tools and tests to these changes.
- Fixes all workflows involved
- Add a new configuration module where the configurations are in order of priority: Environment variable > API > Default configuration.

This PR is for the epic, every change is in its issue .

2024-11-22 13:05 UTC, JavierBejMen requested changes
## Package Ubuntu24
```
test@WazPc:~$ sudo apt install ./wazuh-server_5.0.0-0_amd64_4e858b0.deb
[sudo] password for test:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'wazuh-server' instead of './wazuh-server_5.0.0-0_amd64_4e858b0.deb'
Suggested packages:
  expect
The following NEW packages will be installed:
  wazuh-server
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/286 MB of archives.
After this operation, 541 MB of additional disk space will be used.
Get:1 /home/test/wazuh-server_5.0.0-0_amd64_4e858b0.deb wazuh-server amd64 5.0.0-0 [286 MB]
Selecting previously unselected package wazuh-server.
(Reading database ... 40788 files and directories currently installed.)
Preparing to unpack .../wazuh-server_5.0.0-0_amd64_4e858b0.deb ...
Unpacking wazuh-server (5.0.0-0) ...
Setting up wazuh-server (5.0.0-0) ...
Processing triggers for libc-bin (2.39-0ubuntu8.3) ...
N: Download is performed unsandboxed as root as file '/home/test/wazuh-server_5.0.0-0_amd64_4e858b0.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
test@WazPc:~$ sudo su
root@WazPc:/home/test# systemctl start wazuh-server
root@WazPc:/home/test# systemctl status wazuh-server
● wazuh-server.service - Wazuh server
     Loaded: loaded (/usr/lib/systemd/system/wazuh-server.service; disabled; preset: enabled)
     Active: active (exited) since Fri 2024-11-22 12:38:37 CET; 4s ago
    Process: 682 ExecStart=/usr/bin/env /bin/wazuh-server start -r (code=exited, status=0/SUCCESS)
   Main PID: 688 (code=exited, status=0/SUCCESS)
      Tasks: 14 (limit: 9331)
     Memory: 1.0G ()
     CGroup: /system.slice/wazuh-server.service
             ├─1088 /usr/share/wazuh-server/framework/python/bin/python3 /usr/share/wazuh-server/api/scripts/wazuh>
             ├─1146 /usr/share/wazuh-server/framework/python/bin/python3 /usr/share/wazuh-server/api/scripts/wazuh>
             ├─1149 /usr/share/wazuh-server/framework/python/bin/python3 /usr/share/wazuh-server/api/scripts/wazuh>
             └─1152 /usr/share/wazuh-server/framework/python/bin/python3 /usr/share/wazuh-server/api/scripts/wazuh>

Nov 22 12:38:37 WazPc systemd[1]: Starting wazuh-server.service - Wazuh server...
Nov 22 12:38:37 WazPc systemd[1]: Started wazuh-server.service - Wazuh server.
```

## Python engine-suite installation
```
(.venv) test@WazPc:~/wazuh/src/engine$ pip3 install tools/api-communication
Processing ./tools/api-communication
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting protobuf==4.21 (from api-communication==1.0.0.dev0)
  Downloading protobuf-4.21.0-cp37-abi3-manylinux2014_x86_64.whl.metadata (62 bytes)
WARNING: The candidate selected for download or install is a yanked version: 'protobuf' candidate (version 4.21.0 at https://files.pythonhosted.org/packages/9d/82/b3131637daf2a27eab76b0de8e139ecf0f6624832c03531dce8a7d59ddc1/protobuf-4.21.0-cp37-abi3-manylinux2014_x86_64.whl (from https://pypi.org/simple/protobuf/))
Reason for being yanked: Required python version not configured correctly (https://github.com/protocolbuffers/protobuf/issues/10076)
Downloading protobuf-4.21.0-cp37-abi3-manylinux2014_x86_64.whl (407 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.6/407.6 kB 8.1 MB/s eta 0:00:00
Building wheels for collected packages: api-communication
  Building wheel for api-communication (pyproject.toml) ... done
  Created wheel for api-communication: filename=api_communication-1.0.0.dev0-py3-none-any.whl size=25204 sha256=816057750ac4ea8a3dcbc12aa503d818e73812be780099eb78016664e9c17c09
  Stored in directory: /home/test/.cache/pip/wheels/2c/7e/71/f8c4fa310f6965bf4a22af11ab32670f671c0e540648a83d00
Successfully built api-communication
Installing collected packages: protobuf, api-communication
Successfully installed api-communication-1.0.0.dev0 protobuf-4.21.0
(.venv) test@WazPc:~/wazuh/src/engine$ pip3 install tools/engine-suite/
Processing ./tools/engine-suite
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests (from engine-suite==1.0.0.dev0)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pyyaml (from engine-suite==1.0.0.dev0)
  Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting graphviz (from engine-suite==1.0.0.dev0)
  Downloading graphviz-0.20.3-py3-none-any.whl.metadata (12 kB)
Collecting lxml (from engine-suite==1.0.0.dev0)
  Downloading lxml-5.3.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting setuptools (from engine-suite==1.0.0.dev0)
  Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
Collecting charset-normalizer<4,>=2 (from requests->engine-suite==1.0.0.dev0)
  Downloading charset_normalizer-3.4.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->engine-suite==1.0.0.dev0)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->engine-suite==1.0.0.dev0)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->engine-suite==1.0.0.dev0)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Downloading graphviz-0.20.3-py3-none-any.whl (47 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.1/47.1 kB 5.4 MB/s eta 0:00:00
Downloading lxml-5.3.0-cp312-cp312-manylinux_2_28_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 31.7 MB/s eta 0:00:00
Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (767 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 767.5/767.5 kB 36.8 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 10.7 MB/s eta 0:00:00
Using cached setuptools-75.6.0-py3-none-any.whl (1.2 MB)
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.3/167.3 kB 22.4 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 20.6 MB/s eta 0:00:00
Downloading idna-3.10-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 7.9 MB/s eta 0:00:00
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 15.3 MB/s eta 0:00:00
Building wheels for collected packages: engine-suite
  Building wheel for engine-suite (pyproject.toml) ... done
  Created wheel for engine-suite: filename=engine_suite-1.0.0.dev0-py3-none-any.whl size=92027 sha256=059f9980b13aee7387b36cbb4da2bc5cff6f8539a51352c5e10453a9eda91050
  Stored in directory: /home/test/.cache/pip/wheels/dd/62/95/832b652c674ea5769a6d233995d6f97952f91cc0b024e57a2a
Successfully built engine-suite
Installing collected packages: urllib3, setuptools, pyyaml, lxml, idna, graphviz, charset-normalizer, certifi, requests, engine-suite
Successfully installed certifi-2024.8.30 charset-normalizer-3.4.0 engine-suite-1.0.0.dev0 graphviz-0.20.3 idna-3.10 lxml-5.3.0 pyyaml-6.0.2 requests-2.32.3 setuptools-75.6.0 urllib3-2.2.3
```

## engine-catalog

```
(.venv) root@WazPc:/home/test/wazuh/src/engine# engine-catalog get decoder
Error getting asset or collection: Collection 'decoder' does not exist on namespace 'user'
(.venv) root@WazPc:/home/test/wazuh/src/engine# engine-catalog create decoder -c "name: decoder/test/0"
(.venv) root@WazPc:/home/test/wazuh/src/engine# engine-catalog get decoder
- decoder/test
(.venv) root@WazPc:/home/test/wazuh/src/engine# engine-catalog -n system update decoder/test/0 -c "name: decoder/test/0"
Error updating asset: Could not update resource 'decoder/test/0': Does no [...]

2024-11-22 17:42 UTC, juliancnn commented on src/engine/tools/engine-suite/src/engine_policy/__main__.py
Multiples `-n` args :
```
╰─# engine-policy get -n user -n system -n wazuh
policy: policy/wazuh/0
hash: 11464515449720324140
assets:
  - integration/wazuh-core/0
  - integration/syslog/0
  - integration/system/0
  - integration/windows/0
  - integration/apache-http/0
  - integration/suricata/0
default_parents:
  - user: decoder/integrations/0
  - wazuh: decoder/integrations/0
```

2024-11-22 17:46 UTC, juliancnn commented on src/engine/tools/engine-suite/src/engine_geo/__main__.py
Fixed, This is because it accepts a path relative to the server's working directory, so I calculate the absolute path before loading it.

2024-11-25 12:51 UTC, JavierBejMen approved these changes
LGTM

2024-11-25 14:45 UTC, NahuFigueroa97 commented
# Success manual tests

## Package Centos7
```console
[vagrant@centos7 ~]$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
[root@centos7 vagrant]# ls /home/vagrant/
shared  wazuh-server_5.0.0-0_x86_64_a176945.rpm
[root@centos7 vagrant]# yum install wazuh-server_5.0.0-0_x86_64_a176945.rpm 
Loaded plugins: fastestmirror
Examining wazuh-server_5.0.0-0_x86_64_a176945.rpm: wazuh-server-5.0.0-0.x86_64
Marking wazuh-server_5.0.0-0_x86_64_a176945.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package wazuh-server.x86_64 0:5.0.0-0 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package        Arch     Version   Repository                              Size
================================================================================
Installing:
 wazuh-server   x86_64   5.0.0-0   /wazuh-server_5.0.0-0_x86_64_a176945   528 M

Transaction Summary
================================================================================
Install  1 Package

Total size: 528 M
Installed size: 528 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : wazuh-server-5.0.0-0.x86_64                                                                                                                                                              1/1 
  Verifying  : wazuh-server-5.0.0-0.x86_64                                                                                                                                                              1/1 

Installed:
  wazuh-server.x86_64 0:5.0.0-0                                                                                                                                                                             

Complete!
[root@centos7 vagrant]# systemctl start wazuh-server
[root@centos7 vagrant]# systemctl status wazuh-server
● wazuh-server.service - Wazuh server
   Loaded: loaded (/usr/lib/systemd/system/wazuh-server.service; disabled; vendor preset: disabled)
   Active: active (exited) since lun 2024-11-25 14:11:43 UTC; 18s ago
  Process: 21780 ExecStart=/usr/bin/env /bin/wazuh-server start -r (code=exited, status=0/SUCCESS)
 Main PID: 21786 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/wazuh-server.service
           ├─21788 /bin/wazuh-engine server start
           └─22159 /usr/share/wazuh-server/framework/python/bin/python3 /usr/share/wazuh-server/api/scripts/wazuh_apid.py -r

nov 25 14:11:42 centos7 systemd[1]: Starting Wazuh server...
nov 25 14:11:43 centos7 systemd[1]: Started Wazuh server.

```

2024-11-25 15:09 UTC, NahuFigueroa97 approved these changes
LGTM!

2024-11-25 16:23 UTC, JcabreraC approved these changes
LGTM !

2024-11-28 02:46 UTC, merged