Added Engine store installation on package building
wazuh/wazuh pull request #26363
Opened 2024-10-17 09:41 UTC by JavierBejMen

|Related issue|
|---|
|#26325|

Added function to download and extract the Engine store on package building.
The store modifies the file outputs to write on `/var/log/wazuh-server/engine/*.json` and adds the indexer output.
The store comes with the policy:
```yml
policy: policy/wazuh/0
hash: 5097757755928008490
assets:
  - integration/wazuh-core/0
  - rule/enrichment/0
  - integration/syslog/0
  - integration/system/0
  - integration/windows/0
  - integration/apache-http/0
  - integration/suricata/0
default_parents:
  - user: decoder/integrations/0
  - user: rule/enrichment/0
  - wazuh: decoder/integrations/0
  - wazuh: rule/enrichment/0
```

And the route:
```yml
- name: default
  policy: policy/wazuh/0
  filter: filter/allow-all/0
  priority: 254
  policy_sync: UPDATED
  entry_status: ENABLED
  uptime: 56
```

2024-10-21 14:55 UTC, JcabreraC reviewed
Review test failed:
- **Build Wazuh server / Build wazuh-server on (pull_request)**

2024-10-21 21:00 UTC, juliancnn requested changes
I test on ubuntu 24, works well.

I can't tested on centos 7 o oracle 9 by know issue:
```
# cat /etc/centos-release
CentOS Linux release 7.8.2003 (Core)
# wazuh-engine server -l info start
wazuh-engine: /lib64/libm.so.6: version `GLIBC_2.38' not found (required by wazuh-engine)
wazuh-engine: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by wazuh-engine)
wazuh-engine: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by wazuh-engine)
wazuh-engine: /lib64/libc.so.6: version `GLIBC_2.30' not found (required by wazuh-engine)
wazuh-engine: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by wazuh-engine)
wazuh-engine: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by wazuh-engine)
wazuh-engine: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by wazuh-engine)
wazuh-engine: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by wazuh-engine)
wazuh-engine: /lib64/libc.so.6: version `GLIBC_2.38' not found (required by wazuh-engine)
wazuh-engine: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by wazuh-engine)
wazuh-engine: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by wazuh-engine)
wazuh-engine: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by wazuh-engine)
wazuh-engine: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by wazuh-engine)
wazuh-engine: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by wazuh-engine)
wazuh-engine: /lib64/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by wazuh-engine)
wazuh-engine: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by wazuh-engine)
wazuh-engine: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by wazuh-engine)
wazuh-engine: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by wazuh-engine)
wazuh-engine: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by wazuh-engine)
wazuh-engine: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by wazuh-engine)
```
But I think it would be desirable to fix the post-installation script that seems to not create the /var/log/wazuh-server folder:
```
Running transaction test
Transaction test succeeded
Running transaction
  Installing : wazuh-server-5.0.0-0.x86_64                                                                                                                                                                                                               1/1 
chown: cannot access ‘/var/log/wazuh-server’: No such file or directory
find: ‘/var/log/wazuh-server’: No such file or directory
warning: %posttrans(wazuh-server-5.0.0-0.x86_64) scriptlet failed, exit status 1
Non-fatal POSTTRANS scriptlet failure in rpm package wazuh-server-5.0.0-0.x86_64
  Verifying  : wazuh-server-5.0.0-0.x86_64                                                                                                                                                                                                               1/1 

Installed:
  wazuh-server.x86_64 0:5.0.0-0                                                                                                                                                                                                                              

```

2024-10-25 14:48 UTC, JavierBejMen commented
## Tests
Build:
- [deb](https://github.com/wazuh/wazuh/actions/runs/11520322889) 
- [rpm](https://github.com/wazuh/wazuh/actions/runs/11520327043) 

Image:
- [deb](https://github.com/wazuh/wazuh/actions/runs/11520394230) 
- [rpm](https://github.com/wazuh/wazuh/actions/runs/11520396843)

2024-10-25 19:03 UTC, juliancnn approved these changes
LGTM!

2024-10-28 09:17 UTC, JcabreraC approved these changes
LGTM !

2024-10-28 11:20 UTC, Dwordcito approved these changes

2024-10-28 11:21 UTC, merged