Add special testing case for arm32 rpm packages
wazuh/wazuh pull request #26540
Opened 2024-10-25 09:29 UTC by mjcr99

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/26400|

## Description
Hi team,

The smoke test for the `arm32` packages in the rpm systems needed a special testing case since the package is built in a `arm32` docker hosted in a `arm64` machine.

This PR updates the command needed to install the generated package under its circumstances and makes the smoke test work as spected.

## Tests
The following jobs have been triggered to test it works both for `arm32` and `arm64` rpm packages.

Command: 
```
gh workflow run packages-build-linux-agent-arm.yml -r bug/26400-fix-armv7hl-compilation-workflow -f architecture=armv7hl -f system=rpm -f source_reference=fix/26400-compilation-errors-for-armhf-and-armv7hl-rpm -f id=test_arm32_rpm
```
Triggered job: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11515245098/job/32055528822

Command: 
```
gh workflow run packages-build-linux-agent-arm.yml -r bug/26400-fix-armv7hl-compilation-workflow -f architecture=aarch64 -f system=rpm -f source_reference=fix/26400-compilation-errors-for-armhf-and-armv7hl-rpm -f id=test_aarch64_rpm
```
Triggered job: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11515254603/job/32055558191

2024-10-25 11:51 UTC, jotacarma90 approved these changes
LGTM

Test:
https://github.com/wazuh/wazuh-agent-packages/pull/127#pullrequestreview-2395053213

2024-10-28 12:47 UTC, lchico requested changes
Nice solution @mjcr99. I left one comment.

2024-10-28 12:47 UTC, lchico commented on .github/actions/test-install-components/install_component.sh
> +        fi
If the installation is unsuccessful, we should exit with an error to avoid executing the rest of the code.

2024-10-29 11:31 UTC, MarcelKemp approved these changes

2024-10-29 12:01 UTC, lchico approved these changes
LGTM!

2024-10-29 13:09 UTC, merged