Adds the engine-kvdb tool
wazuh/wazuh pull request #26752
Opened 2024-11-07 19:22 UTC by juliancnn

Closes #26519 

Closes https://github.com/wazuh/wazuh/issues/25948

This PR create the engine-kvdb python tool that remplace the `wazuh-engine kvdb` cli command.

2024-11-11 10:58 UTC, JavierBejMen requested changes
Add protobuff dependendy:
```
Traceback (most recent call last):
  File "/home/dev/Projects/wazuh/src/engine/.venv/bin/engine-kvdb", line 5, in <module>
    from engine_kvdb.__main__ import main
  File "/home/dev/Projects/wazuh/src/engine/.venv/lib/python3.12/site-packages/engine_kvdb/__main__.py", line 6, in <module>
    from engine_kvdb.cmds.manager_list import configure as configure_manager_list
  File "/home/dev/Projects/wazuh/src/engine/.venv/lib/python3.12/site-packages/engine_kvdb/cmds/manager_list.py", line 2, in <module>
    from google.protobuf.json_format import ParseDict
ModuleNotFoundError: No module named 'google'
```

Incorrect default socket path?
```
Error getting the list of key-value databases: Error while connecting to API socket/var/run/wazuh/api.sock: [Errno 2] No such file or directory
```
By default it is in:
```
/var/run/wazuh-server/engine-api.socket
```

2024-11-12 00:47 UTC, NahuFigueroa97 approved these changes
LGTM!

2024-11-12 16:26 UTC, JavierBejMen approved these changes

2024-11-13 08:37 UTC, JcabreraC approved these changes
LGTM !

2024-11-13 08:37 UTC, merged