Remove legacy agent endpoints
wazuh/wazuh pull request #26762
Opened 2024-11-08 13:00 UTC by GGP1

|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/26554 |

## Description

Removes all endpoints and resources related agents from the code.

2024-11-19 13:45 UTC, nico-stefani requested changes
LGTM! But new conflicts appeared.

2024-11-19 19:57 UTC, nico-stefani submitted a review, later dismissed
LGTM

2024-11-20 09:12 UTC, fdalmaup requested changes

2024-11-20 12:53 UTC, fdalmaup approved these changes
LGTM!

2024-11-20 12:53 UTC, merged