Add nullptr check
wazuh/wazuh pull request #26842
Opened 2024-11-13 14:21 UTC by MiguelazoDS

|Related issue|
|---|
|#26823|

## Description (wip)

- Added nullptr check 
- Fix function name typo

2024-11-16 02:22 UTC, pereyra-m reviewed
GJ!

2024-11-16 02:22 UTC, pereyra-m commented on src/wazuh_modules/vulnerability_scanner/tests/unit/descriptionsHelper_test.cpp
+1: These tests seem to cover all the possible situations.

2024-11-16 02:32 UTC, MiguelazoDS commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/eventDetailsBuilder.hpp
> +                        ecsData["vulnerability"]["published_at"] = description.datePublished.empty()
That's a fantastic question but I don't have the answer XD. 

According to this is the the format of the "date" format, I'm not sure why it accepts the one we are using now. 
![image](https://github.com/user-attachments/assets/7752bd55-0b5d-44c6-8a7f-93f461f6ff4b)

I'll take a look for a better default value.

2024-11-16 02:32 UTC, MiguelazoDS commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/descriptionsHelper.hpp
> +                (cvssData.data && (cvssData.data->scoreBase() < 0.01f || cvssData.data->severity()->str().empty())))
yeap, thanks.

2024-11-17 21:39 UTC, MiguelazoDS commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/eventDetailsBuilder.hpp
> +                        ecsData["vulnerability"]["published_at"] = description.datePublished.empty()
I was trying different options and I could set this value 

![image](https://github.com/user-attachments/assets/70b299d9-e04c-46cd-8730-a713d0fd9969)

But for me, it is even worse than the one I used. 

We could use this option too

`ignore_malformed` 

Let's the team decide what is better.

2024-11-19 00:54 UTC, pereyra-m commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/eventDetailsBuilder.hpp
> +                        ecsData["vulnerability"]["published_at"] = description.datePublished.empty()
I agree, I don't have the answer either jaja
@sebasfalcone

2024-11-19 04:05 UTC, pereyra-m commented
## Testing :green_circle: 

I've compiled the dev branch and installed the manager on an Ubuntu 24.04 test host.
After enabling the manager scan, I selected a match to manually remove some descriptions and test the changes.

```
2024/11/19 02:49:21 wazuh-modulesd:vulnerability-scanner[36354] packageScanner.hpp:189 at scanPackageTranslation(): DEBUG: Translation for package 'coreutils' in platform 'ubuntu' not found. Using provided packageName.
2024/11/19 02:49:21 wazuh-modulesd:vulnerability-scanner[36354] packageScanner.hpp:713 at handleRequest(): DEBUG: Initiating a vulnerability scan for package 'coreutils' (deb) (ubuntu developers <ubuntu-devel-discuss@lists.ubuntu.com>) with CVE Numbering Authorities (CNA) 'canonical' on Agent '31b1f6d22450' (ID: '000', Version: 'v4.10.0').
2024/11/19 02:49:21 wazuh-modulesd:vulnerability-scanner[36354] packageScanner.hpp:549 at versionMatch(): DEBUG: Match found, the package 'coreutils' is vulnerable to 'CVE-2016-2781' due to default status. - Agent '31b1f6d22450' (ID: '000', Version: 'v4.10.0').
2024/11/19 03:38:59 wazuh-modulesd:vulnerability-scanner[49068] packageScanner.hpp:549 at versionMatch(): DEBUG: Match found, the package 'coreutils' is vulnerable to 'CVE-2016-2781' due to default status. - Agent '31b1f6d22450' (ID: '000', Version: 'v4.10.0').
2024/11/19 03:42:09 wazuh-modulesd:vulnerability-scanner[51220] packageScanner.hpp:549 at versionMatch(): DEBUG: Match found, the package 'coreutils' is vulnerable to 'CVE-2016-2781' due to default status. - Agent '31b1f6d22450' (ID: '000', Version: 'v4.10.0').
```

This is one of the CVEs found 

<details><summary>Details</summary>
<p>

```
{
  "took": 7,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "wazuh-states-vulnerabilities-31b1f6d22450",
        "_id": "000_19a725bf7c36af309a8967cad5f2e3240c6b11b5_CVE-2016-2781",
        "_score": 1,
        "_source": {
          "agent": {
            "id": "000",
            "name": "31b1f6d22450",
            "type": "Wazuh",
            "version": "v4.10.0"
          },
          "host": {
            "os": {
              "full": "Ubuntu 24.04.1 LTS (Noble Numbat)",
              "kernel": "6.6.54-2-MANJARO",
              "name": "Ubuntu",
              "platform": "ubuntu",
              "type": "ubuntu",
              "version": "24.04.1"
            }
          },
          "package": {
            "architecture": "amd64",
            "description": "GNU core utilities",
            "name": "coreutils",
            "size": 7110656,
            "type": "deb",
            "version": "9.4-3ubuntu6"
          },
          "vulnerability": {
            "category": "Packages",
            "classification": "CVSS",
            "description": "as of 2024-10-04, no viable solution",
            "detected_at": "2024-11-19T03:42:09.778Z",
            "enumeration": "CVE",
            "id": "CVE-2016-2781",
            "published_at": "2017-02-07T15:59:00Z",
            "reference": "http://seclists.org/oss-sec/2016/q1/452, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816320, https://bugzilla.redhat.com/show_bug.cgi?id=1312863, https://lore.kernel.org/patchwork/patch/793178/, https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.28/v2.28-ReleaseNotes, https://www.cve.org/CVERecord?id=CVE-2016-2781",
            "scanner": {
              "source": "Canonical Security Tracker",
              "vendor": "Wazuh"
            },
            "score": {
              "base": 2.1,
              "version": "2.0"
            },
            "severity": "Low",
            "under_evaluation": false
          },
          "wazuh": {
            "cluster": {
              "name": "31b1f6d22450"
            },
            "schema": {
              "version": "1.0.0"
            }
          }
        }
      }
    ]
  }
}
```

</p>
</details> 

Now I remove the canonical entry to force the NVD descriptions to be used.

```
root@31b1f6d22450:/workspaces/wazuh.worktrees/bug/wazuh-db-processes-pid# LD_LIBRARY_PATH=src/external/rocksdb/build src/external/rocksdb/build/tools/ldb --column_family=descriptions_canonical --db=/var/ossec/queue/vd/feed/ delete CVE-2016-2781
OK
root@31b1f6d22450:/workspaces/wazuh.worktrees/bug/wazuh-db-processes-pid# ./src/build/wazuh_modules/vulnerability_scanner/testtool/rocksDBQuery/rocks_db_query_testtool -d /var/ossec/queue/vd/feed/ -f /workspaces/wazuh.worktrees/bug/wazuh-db-processes-pid/src/wazuh_modules/vulnerability_scanner/schemas/vulnerabilityDescription.fbs -c descriptions_canonical -k CVE-2016-2781
Unable to find resource.
```

After the re-scan, no errors were found

```
root@31b1f6d22450:/var/ossec# grep "WARNING\|ERROR" logs/ossec.log 
2024/11/19 01:18:14 indexer-connector: WARNING: No username and password found in the keystore, using default values.
2024/11/19 01:18:14 indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-31b1f6d22450', retrying until the connection is successful.
```

And the new document is indexed with a different description and references

<details><summary>Details</summary>
<p>

```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "wazuh-states-vulnerabilities-31b1f6d22450",
        "_id": "000_19a725bf7c36af309a8967cad5f2e3240c6b11b5_CVE-2016-2781",
        "_score": 1,
        "_source": {
          "agent": {
            "id": "000",
            "name": "31b1f6d22450",
            "type": "Wazuh",
            "version": "v4.10.0"
          },
          "host": {
            "os": {
              "full": "Ubuntu 24.04.1 LTS (Noble Numbat)",
              "kernel": "6.6.54-2-MANJARO",
              "name": "Ubuntu",
              "platform": "ubuntu",
              "type": "ubuntu",
              "version": "24.04.1"
            }
          },
          "package": {
            "architecture": "amd64",
            "description": "GNU core utilities",
            "name": "coreutils",
            "size": 7110656,
            "type": "deb",
            "version": "9.4-3ubuntu6"
          },
          "vulnerability": {
            "category": "Packages",
            "classification": "CVSS",
            "description": "chroot in GNU coreutils, when used with --userspec, allows local users to escape to the parent session via a crafted TIOCSTI ioctl call, which pushes characters to the terminal's input buffer.",
            "detected_at": "2024-11-19T03:54:36.669Z",
            "enumeration": "CVE",
            "id": "CVE-2016-2781",
            "published_at": "2017-02-07T15:59:00Z",
            "reference": "http://www.openwall.com/lists/oss-security/2016/02/28/2, http://www.openwall.com/lists/oss-security/2016/02/28/3, https://lists.apache.org/thread.html/rf9fa47ab66495c78bb4120b0754dd9531ca2ff0430f6685ac9b07772%40%3Cdev.mina.apache.org%3E",
            "scanner": {
              "source": "Canonical Security Tracker",
              "vendor": "Wazuh"
            },
            "score": {
              "base": 2.1,
              "version": "2.0"
            },
            "severity": "Low",
            "under_evaluation": false
          },
          "wazuh": {
            "cluster": {
              "name": "31b1f6d22450"
            },
            "schema": {
              "version": "1.0.0"
            }
          }
        }
      }
    ]
  }
}
```

</p>
</details> 

Now, if we also remove the NVD entry

```
root@31b1f6d22450:/workspaces/wazuh.worktrees/bug/wazuh-db-processes-pid# LD_LIBRARY_PATH=src/external/rocksdb/build src/external/rocksdb/build/tools/ldb --column_family=descriptions
_nvd --db=/va [...]

2024-11-19 18:56 UTC, Dwordcito requested changes

2024-11-19 18:56 UTC, Dwordcito commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/eventDetailsBuilder.hpp
> +                        ecsData["vulnerability"]["published_at"] = description.datePublished.empty()
To be clear, we will use an explicit empty value in datetime, therefore the default value will be 0000-01-01T00:00:00Z

2024-11-19 19:39 UTC, MiguelazoDS commented
# Update 

After the changes discussed here https://github.com/wazuh/wazuh/pull/26842#discussion_r1844783332

```json
{
  "agent": {
    "id": "001",
    "name": "bullseye",
    "type": "Wazuh",
    "version": "v4.9.2"
  },
  "host": {
    "os": {
      "full": "Debian GNU/Linux 11 (bullseye)",
      "kernel": "5.10.0-32-amd64",
      "name": "Debian GNU/Linux",
      "platform": "debian",
      "type": "debian",
      "version": "11"
    }
  },
  "package": {
    "architecture": "amd64",
    "description": "Linux for x86-64 cloud (meta-package)",
    "name": "linux-image-cloud-amd64",
    "size": 13,
    "type": "deb",
    "version": "5.10.226-1"
  },
  "vulnerability": {
    "category": "Packages",
    "classification": "-",
    "description": "",
    "detected_at": "2024-11-19T19:31:45.013Z",
    "enumeration": "CVE",
    "id": "CVE-2024-50134",
    "published_at": "0000-01-01T00:00:00Z",
    "reference": "",
    "scanner": {
      "source": "Debian Security Tracker",
      "vendor": "Wazuh"
    },
    "score": {
      "base": -1,
      "version": "-"
    },
    "severity": "-",
    "under_evaluation": true
  },
  "wazuh": {
    "cluster": {
      "name": "jammy"
    },
    "schema": {
      "version": "1.0.0"
    }
  }
}
{
  "agent": {
    "id": "001",
    "name": "bullseye",
    "type": "Wazuh",
    "version": "v4.9.2"
  },
  "host": {
    "os": {
      "full": "Debian GNU/Linux 11 (bullseye)",
      "kernel": "5.10.0-32-amd64",
      "name": "Debian GNU/Linux",
      "platform": "debian",
      "type": "debian",
      "version": "11"
    }
  },
  "package": {
    "architecture": "amd64",
    "description": "Linux 5.10 for 64-bit PCs (signed)",
    "name": "linux-image-5.10.0-32-amd64",
    "size": 310614,
    "type": "deb",
    "version": "5.10.223-1"
  },
  "vulnerability": {
    "category": "Packages",
    "classification": "-",
    "description": "",
    "detected_at": "2024-11-19T19:31:36.606Z",
    "enumeration": "CVE",
    "id": "CVE-2024-50134",
    "published_at": "0000-01-01T00:00:00Z",
    "reference": "",
    "scanner": {
      "source": "Debian Security Tracker",
      "vendor": "Wazuh"
    },
    "score": {
      "base": -1,
      "version": "-"
    },
    "severity": "-",
    "under_evaluation": true
  },
  "wazuh": {
    "cluster": {
      "name": "jammy"
    },
    "schema": {
      "version": "1.0.0"
    }
  }
}
{
  "agent": {
    "id": "001",
    "name": "bullseye",
    "type": "Wazuh",
    "version": "v4.9.2"
  },
  "host": {
    "os": {
      "full": "Debian GNU/Linux 11 (bullseye)",
      "kernel": "5.10.0-32-amd64",
      "name": "Debian GNU/Linux",
      "platform": "debian",
      "type": "debian",
      "version": "11"
    }
  },
  "package": {
    "architecture": "amd64",
    "description": "Linux for 64-bit PCs (meta-package)",
    "name": "linux-image-amd64",
    "size": 13,
    "type": "deb",
    "version": "5.10.223-1"
  },
  "vulnerability": {
    "category": "Packages",
    "classification": "-",
    "description": "",
    "detected_at": "2024-11-19T19:31:40.247Z",
    "enumeration": "CVE",
    "id": "CVE-2024-50134",
    "published_at": "0000-01-01T00:00:00Z",
    "reference": "",
    "scanner": {
      "source": "Debian Security Tracker",
      "vendor": "Wazuh"
    },
    "score": {
      "base": -1,
      "version": "-"
    },
    "severity": "-",
    "under_evaluation": true
  },
  "wazuh": {
    "cluster": {
      "name": "jammy"
    },
    "schema": {
      "version": "1.0.0"
    }
  }
}
```

2024-11-19 22:34 UTC, sebasfalcone reviewed
# Testing 🟢 

## Use of NVD as fallback

Identified vulnerability that doesn't have reliable information in its ADP:
- `descriptionsHelper.hpp:235 at operator()(): DEBUG: Unreliable information for 'CVE-2023-52474' from redhat_8 source.`

```py
./rocks_db_query_testtool -d /var/ossec/queue/vd/feed/ -c descriptions_redhat_8 -f /home/sebas/Documents/work/development/wazuh-legacy/src/wazuh_modules/vulnerability_scanner/schemas/vulnerabilityDescription.fbs -k CVE-2023-52474

CVE-2023-52474 ==> {
  "accessComplexity": "",
  "assignerShortName": "Linux",
  "attackVector": "",
  "authentication": "",
  "availabilityImpact": "",
  "classification": "",
  "confidentialityImpact": "",
  "cweId": "",
  "datePublished": "2024-02-26T18:15:07Z",
  "dateUpdated": "2024-04-17T17:15:54Z",
  "description": "DOCUMENTATION: A flaw was found in hfi1 in the Linux Kernel. This issue is due to data corruption for user SDMA requests that have multiple payload iovecs where an iovec other than the tail iovec does not run up to the page boundary.",
  "integrityImpact": "",
  "privilegesRequired": "",
  "reference": "https://access.redhat.com/security/cve/CVE-2023-52474",
  "scope": "",
  "scoreVersion": "",
  "severity": "",
  "userInteraction": ""
}
```

It has no CVSS information
```py
./rocks_db_query_testtool -d /var/ossec/queue/vd/feed/ -c descriptions_nvd -f /home/sebas/Documents/work/development/wazuh-legacy/src/wazuh_modules/vulnerability_scanner/schemas/vulnerabilityDescription.fbs -k CVE-2023-52474

CVE-2023-52474 ==> {
  "accessComplexity": "",
  "assignerShortName": "Linux",
  "attackVector": "",
  "authentication": "",
  "availabilityImpact": "HIGH",
  "classification": "CVSS",
  "confidentialityImpact": "HIGH",
  "cweId": "",
  "datePublished": "2024-02-26T18:15:07Z",
  "dateUpdated": "2024-04-17T17:15:54Z",
  "description": "In the Linux kernel, the following vulnerability has been resolved:  IB/hfi1: Fix bugs with non-PAGE_SIZE-end multi-iovec user SDMA requests  hfi1 user SDMA request processing has two bugs that can cause data corruption for user SDMA requests that have multiple payload iovecs where an iovec other than the tail iovec does not run up to the page boundary for the buffer pointed to by that iovec.a  Here are the specific bugs: 1. user_sdma_txadd() does not use struct user_sdma_iovec->iov.iov_len.    Rather, user_sdma_txadd() will add up to PAGE_SIZE bytes from iovec    to the packet, even if some of those bytes are past    iovec->iov.iov_len and are thus not intended to be in the packet. 2. user_sdma_txadd() and user_sdma_send_pkts() fail to advance to the    next iovec in user_sdma_request->iovs when the current iovec    is not PAGE_SIZE and does not contain enough data to complete the    packet. The transmitted packet will contain the wrong data from the    iovec pages.  This has not been an issue with SDMA packets from hfi1 Verbs or PSM2 because they only produce iovecs that end short of PAGE_SIZE as the tail iovec of an SDMA request.  Fixing these bugs exposes other bugs with the SDMA pin cache (struct mmu_rb_handler) that get in way of supporting user SDMA requests with multiple payload iovecs whose buffers do not end at PAGE_SIZE. So this commit fixes those issues as well.  Here are the mmu_rb_handler bugs that non-PAGE_SIZE-end multi-iovec payload user SDMA requests can hit: 1. Overlapping memory ranges in mmu_rb_handler will result in duplicate    pinnings. 2. When extending an existing mmu_rb_handler entry (struct mmu_rb_node),    the mmu_rb code (1) removes the existing entry under a lock, (2)    releases that lock, pins the new pages, (3) then reacquires the lock    to insert the extended mmu_rb_node.     If someone else comes in and inserts an overlapping entry between (2)    and (3), insert in (3) will fail.     The failure path code in this case unpins _all_ pages in either the    original mmu_rb_node or the new mmu_rb_node that was inserted between    (2) and (3). 3. In hfi1_mmu_rb_remove_unless_exact(), mmu_rb_node->refcount is    incremented outside of mmu_rb_handler->lock. As a result, mmu_rb_node    could be evicted by another thread that gets mmu_rb_handler->lock and    checks mmu_rb_node->refcount before mmu_rb_node->refcount is    incremented. 4. Related to #2 above, SDMA request submission failure path does not    check mmu_rb_node->refcount before freeing mmu_rb_node object.     If there are other SDMA requests in progress whose iovecs have    pointers to the now-freed mmu_rb_node(s), those pointers to the    now-freed mmu_rb nodes will be dereferenced when those SDMA requests    complete.",
  "integrityImpact": "HIGH",
  "privilegesRequired": "LOW",
  "reference": "https://git.kernel.org/stable/c/00cbce5cbf88459cd1aa1d60d0f1df15477df127, https://git.kernel.org/stable/c/7e6010f79b58f45b204cf18aa58f4b73c3f30adc, https://git.kernel.org/stable/c/9c4c6512d7330b743c4ffd18bd999a86ca26db0d, https://git.kernel.org/stable/c/a2bd706ab63509793b5cd5065e685b7ef5cba678, https://git.kernel.org/stable/c/c76cb8f4bdf26d04cfa5485a93ce297dba5e6a80, https://git.kernel.org/stable/c/dce59b5443700fbd0d2433ec6e4d4cf063448844",
  "scope": "UNCHANGED",
  "scoreBase": 7.8,
  "scoreVersion": "3.1",
  "severity": "HIGH",
  "userInteraction": "NONE"
}
```

The NVD values are used for CVSS scoring and RedHat 8 for the descriptive one:

```json
{
  "_index": "wazuh-states-vulnerabilities-sebas-thinkpad",
  "_id": "001_19925e120611a2d5c4acf440079c390dc0ada4b8_CVE-2023-52474",
  "_score": 0,
  "_source": {
    "agent": {
      "id": "001",
      "name": "centos8",
      "type": "Wazuh",
      "version": "v4.9.2"
    },
    "host": {
      "os": {
        "full": "CentOS Linux 8.5.2111",
        "kernel": "4.18.0-348.7.1.el8_5.x86_64",
        "name": "CentOS Linux",
        "platform": "centos",
        "type": "centos",
        "version": "8.5.2111"
      }
    },
    "package": {
      "architecture": "x86_64",
      "description": "Python bindings for apps which will manipulate perf events",
      "installed": "2024-01-10T02:42:23.000Z",
      "name": "python3-perf",
      "size": 372789,
      "type": "rpm",
      "version": "4.18.0-348.7.1.el8_5"
    },
    "vulnerability": {
      "category": "Packages",
      "classification": "CVSS",
      "description": "DOCUMENTATION: A flaw was found in hfi1 in the Linux Kernel. This issue is due to data corruption for user SDMA requests that have multiple payload iovecs where an iovec other than the tail iovec does not run up to the page boundary.",
      "detected_at": "2024-11-19T21:59:37.646Z",
      "enumeration": "CVE",
      "id": "CVE-2023-52474",
      "published_at": "2024-02-26T18:15:07Z",
      "reference": "https://access.redhat.com/security/cve/CVE-2023-52474",
      "scanner": {
        "source": "Red Hat CVE Database",
        "vendor": "Wazuh"
      },
      "score": {
        "base": 7.8,
        "version": "3.1"
      },
      "severity": "High",
      "under_evaluation": false
    },
    "wazuh": {
      "cluster": {
        "name": "sebas-ThinkPad"
      },
      "schema": {
        "version": "1.0.0"
      }
    }
  },
  "fields": {
    "vulnerability.detected_at": [
      "2024-11-19T21:59:37.646Z"
    ],
    "package.installed": [
      "2024-01-10T02:42:23.000Z"
    ],
    "vulnerability.published_at": [
      "2024-02-26T18:15:07.000Z"
    ]
  }
}
```

## Use of default values

I've modified this same CVE information to make the NVD and RedHat 8 descriptive information unreliable:

```py
./rocks_db_query_testtool -d /var/ossec/queue/vd/feed/ -c descriptions_redhat_8 -f /home/sebas/Documents/work/development/wazuh-legacy/src/wazuh_modules/vulnerability_scanner/schemas/vulnerabilityDescription.fbs -k CVE-2023-52474

CVE-2023-52474 ==> {
  "accessComplexity": "",
  "assignerShortName": "",
  "attackVector": "",
  "authentication": "",
  "availabilityImpact": "",
  "classification": "",
  "confidentialityImpact": "",
  "cweId": "",
  "datePublished": "",
  "dateUpdated": "",
  "description" [...]

2024-11-20 01:47 UTC, pereyra-m approved these changes
LGTM!

2024-11-20 02:14 UTC, sebasfalcone commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/descriptionsHelper.hpp
> +        if (descriptionData.data)
This condition is always true if there is information in the DB even if it's not reliable

I inserted these values:
```py
CVE-2023-52474 ==> {
  "accessComplexity": "",
  "assignerShortName": "",
  "attackVector": "",
  "authentication": "",
  "availabilityImpact": "",
  "classification": "",
  "confidentialityImpact": "",
  "cweId": "",
  "datePublished": "",
  "dateUpdated": "",
  "description": "",
  "integrityImpact": "",
  "privilegesRequired": "",
  "reference": "",
  "scope": "",
  "scoreVersion": "",
  "severity": "",
  "userInteraction": ""
}
```

And because those are the ones used, the event failed to be indexed:
> d59d7a1c0c614456f7888_CVE-2023-52474","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [vulnerability.published_at] of type [date] in document with id '002_ca0eac1c904309b78f7d59d7a1c0c614456f7888_CVE-2023-52474'. Preview of field's value: ''","caused_by":{"type":"illegal_argument_exception","reason":"cannot parse empty date"}}}}


We may need to do something like this:
```
        const auto cvssIsReliable = [&cvssData, &cvssSource, &cve]()
        {
            if (!cvssData.data ||
                (cvssData.data && (cvssData.data->scoreBase() < 0.01f ||
                                   (cvssData.data->severity() && cvssData.data->severity()->str().empty()))))
            {
                logDebug2(WM_VULNSCAN_LOGTAG,
                          "Unreliable information for '%s' from %s source.",
                          cve.c_str(),
                          cvssSource.c_str());
                cvssData.data = nullptr;
                return false;
            }

            return true;
        };
```

2024-11-20 13:43 UTC, MiguelazoDS commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/descriptionsHelper.hpp
> +        if (descriptionData.data)
That check will only validate that description is not "not defined", but if I want to validate the case you propose I have to check each field individually.

2024-11-20 14:19 UTC, MiguelazoDS commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/descriptionsHelper.hpp
> +        if (descriptionData.data)
I still do not see if this is possible, but added some validations for empty dates.

2024-11-20 16:40 UTC, sebasfalcone approved these changes
# Testing

## Use of NVD as fallback 🟢 

Identified vulnerability that doesn't have reliable information in its ADP:
- `descriptionsHelper.hpp:235 at operator()(): DEBUG: Unreliable information for 'CVE-2023-52474' from redhat_8 source.`

```py
./rocks_db_query_testtool -d /var/ossec/queue/vd/feed/ -c descriptions_redhat_8 -f /home/sebas/Documents/work/development/wazuh-legacy/src/wazuh_modules/vulnerability_scanner/schemas/vulnerabilityDescription.fbs -k CVE-2023-52474

CVE-2023-52474 ==> {
  "accessComplexity": "",
  "assignerShortName": "Linux",
  "attackVector": "",
  "authentication": "",
  "availabilityImpact": "",
  "classification": "",
  "confidentialityImpact": "",
  "cweId": "",
  "datePublished": "2024-02-26T18:15:07Z",
  "dateUpdated": "2024-04-17T17:15:54Z",
  "description": "DOCUMENTATION: A flaw was found in hfi1 in the Linux Kernel. This issue is due to data corruption for user SDMA requests that have multiple payload iovecs where an iovec other than the tail iovec does not run up to the page boundary.",
  "integrityImpact": "",
  "privilegesRequired": "",
  "reference": "https://access.redhat.com/security/cve/CVE-2023-52474",
  "scope": "",
  "scoreVersion": "",
  "severity": "",
  "userInteraction": ""
}
```

It has no CVSS information
```py
./rocks_db_query_testtool -d /var/ossec/queue/vd/feed/ -c descriptions_nvd -f /home/sebas/Documents/work/development/wazuh-legacy/src/wazuh_modules/vulnerability_scanner/schemas/vulnerabilityDescription.fbs -k CVE-2023-52474

CVE-2023-52474 ==> {
  "accessComplexity": "",
  "assignerShortName": "Linux",
  "attackVector": "",
  "authentication": "",
  "availabilityImpact": "HIGH",
  "classification": "CVSS",
  "confidentialityImpact": "HIGH",
  "cweId": "",
  "datePublished": "2024-02-26T18:15:07Z",
  "dateUpdated": "2024-04-17T17:15:54Z",
  "description": "In the Linux kernel, the following vulnerability has been resolved:  IB/hfi1: Fix bugs with non-PAGE_SIZE-end multi-iovec user SDMA requests  hfi1 user SDMA request processing has two bugs that can cause data corruption for user SDMA requests that have multiple payload iovecs where an iovec other than the tail iovec does not run up to the page boundary for the buffer pointed to by that iovec.a  Here are the specific bugs: 1. user_sdma_txadd() does not use struct user_sdma_iovec->iov.iov_len.    Rather, user_sdma_txadd() will add up to PAGE_SIZE bytes from iovec    to the packet, even if some of those bytes are past    iovec->iov.iov_len and are thus not intended to be in the packet. 2. user_sdma_txadd() and user_sdma_send_pkts() fail to advance to the    next iovec in user_sdma_request->iovs when the current iovec    is not PAGE_SIZE and does not contain enough data to complete the    packet. The transmitted packet will contain the wrong data from the    iovec pages.  This has not been an issue with SDMA packets from hfi1 Verbs or PSM2 because they only produce iovecs that end short of PAGE_SIZE as the tail iovec of an SDMA request.  Fixing these bugs exposes other bugs with the SDMA pin cache (struct mmu_rb_handler) that get in way of supporting user SDMA requests with multiple payload iovecs whose buffers do not end at PAGE_SIZE. So this commit fixes those issues as well.  Here are the mmu_rb_handler bugs that non-PAGE_SIZE-end multi-iovec payload user SDMA requests can hit: 1. Overlapping memory ranges in mmu_rb_handler will result in duplicate    pinnings. 2. When extending an existing mmu_rb_handler entry (struct mmu_rb_node),    the mmu_rb code (1) removes the existing entry under a lock, (2)    releases that lock, pins the new pages, (3) then reacquires the lock    to insert the extended mmu_rb_node.     If someone else comes in and inserts an overlapping entry between (2)    and (3), insert in (3) will fail.     The failure path code in this case unpins _all_ pages in either the    original mmu_rb_node or the new mmu_rb_node that was inserted between    (2) and (3). 3. In hfi1_mmu_rb_remove_unless_exact(), mmu_rb_node->refcount is    incremented outside of mmu_rb_handler->lock. As a result, mmu_rb_node    could be evicted by another thread that gets mmu_rb_handler->lock and    checks mmu_rb_node->refcount before mmu_rb_node->refcount is    incremented. 4. Related to #2 above, SDMA request submission failure path does not    check mmu_rb_node->refcount before freeing mmu_rb_node object.     If there are other SDMA requests in progress whose iovecs have    pointers to the now-freed mmu_rb_node(s), those pointers to the    now-freed mmu_rb nodes will be dereferenced when those SDMA requests    complete.",
  "integrityImpact": "HIGH",
  "privilegesRequired": "LOW",
  "reference": "https://git.kernel.org/stable/c/00cbce5cbf88459cd1aa1d60d0f1df15477df127, https://git.kernel.org/stable/c/7e6010f79b58f45b204cf18aa58f4b73c3f30adc, https://git.kernel.org/stable/c/9c4c6512d7330b743c4ffd18bd999a86ca26db0d, https://git.kernel.org/stable/c/a2bd706ab63509793b5cd5065e685b7ef5cba678, https://git.kernel.org/stable/c/c76cb8f4bdf26d04cfa5485a93ce297dba5e6a80, https://git.kernel.org/stable/c/dce59b5443700fbd0d2433ec6e4d4cf063448844",
  "scope": "UNCHANGED",
  "scoreBase": 7.8,
  "scoreVersion": "3.1",
  "severity": "HIGH",
  "userInteraction": "NONE"
}
```

The NVD values are used for CVSS scoring and RedHat 8 for the descriptive one:

```json
{
  "_index": "wazuh-states-vulnerabilities-sebas-thinkpad",
  "_id": "009_19925e120611a2d5c4acf440079c390dc0ada4b8_CVE-2023-52474",
  "_score": 0,
  "_source": {
    "agent": {
      "id": "009",
      "name": "centos8",
      "type": "Wazuh",
      "version": "v4.9.2"
    },
    "host": {
      "os": {
        "full": "CentOS Linux 8.5.2111",
        "kernel": "4.18.0-348.7.1.el8_5.x86_64",
        "name": "CentOS Linux",
        "platform": "centos",
        "type": "centos",
        "version": "8.5.2111"
      }
    },
    "package": {
      "architecture": "x86_64",
      "description": "Python bindings for apps which will manipulate perf events",
      "installed": "2024-11-20T16:37:24.000Z",
      "name": "python3-perf",
      "size": 372789,
      "type": "rpm",
      "version": "4.18.0-348.7.1.el8_5"
    },
    "vulnerability": {
      "category": "Packages",
      "classification": "CVSS",
      "description": "DOCUMENTATION: A flaw was found in hfi1 in the Linux Kernel. This issue is due to data corruption for user SDMA requests that have multiple payload iovecs where an iovec other than the tail iovec does not run up to the page boundary.",
      "detected_at": "2024-11-20T16:37:35.021Z",
      "enumeration": "CVE",
      "id": "CVE-2023-52474",
      "published_at": "2024-02-26T18:15:07Z",
      "reference": "https://access.redhat.com/security/cve/CVE-2023-52474",
      "scanner": {
        "source": "Red Hat CVE Database",
        "vendor": "Wazuh"
      },
      "score": {
        "base": 7.8,
        "version": "3.1"
      },
      "severity": "High",
      "under_evaluation": false
    },
    "wazuh": {
      "cluster": {
        "name": "sebas-ThinkPad"
      },
      "schema": {
        "version": "1.0.0"
      }
    }
  },
  "fields": {
    "vulnerability.detected_at": [
      "2024-11-20T16:37:35.021Z"
    ],
    "package.installed": [
      "2024-11-20T16:37:24.000Z"
    ],
    "vulnerability.published_at": [
      "2024-02-26T18:15:07.000Z"
    ]
  }
}
```

## Use of default values 🟢 
I've modified this same CVE information to make the NVD and RedHat 8 descriptive information unreliable:

```py
./rocks_db_query_testtool -d /var/ossec/queue/vd/feed/ -c descriptions_redhat_8 -f /home/sebas/Documents/work/development/wazuh-legacy/src/wazuh_modules/vulnerability_scanner/schemas/vulnerabilityDescription.fbs -k CVE-2023-52474

CVE-2023-52474 ==> {
  "accessComplexity": "",
  "assignerShortName": "",
  "attackVector": "",
  "authentication": "",
  "availabilityImpact": "",
  "classification": "",
  "confidentialityImpact": "",
  "cweId": "",
  "datePublished": "",
  "dateUpdated": "",
  "descriptio [...]

2024-11-21 18:55 UTC, MiguelazoDS commented on src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/descriptionsHelper.hpp
> +    static constexpr const char* DEFAULT_SEVERITY_VALUE = "Untriaged";       ///< Default value for severity field.
Alert example 

```json
{
  "timestamp": "2024-11-21T15:53:01.489-0300",
  "rule": {
    "level": 3,
    "description": "CVE-2024-50134 affects linux-image-cloud-amd64",
    "id": "23508",
    "firedtimes": 168,
    "mail": false,
    "groups": [
      "vulnerability-detector"
    ],
    "gdpr": [
      "IV_35.7.d"
    ],
    "pci_dss": [
      "11.2.1",
      "11.2.3"
    ],
    "tsc": [
      "CC7.1",
      "CC7.2"
    ]
  },
  "agent": {
    "id": "001",
    "name": "bullseye",
    "ip": "192.168.33.90"
  },
  "manager": {
    "name": "jammy"
  },
  "id": "1732215181.2451143",
  "decoder": {
    "name": "json"
  },
  "data": {
    "vulnerability": {
      "classification": "-",
      "cve": "CVE-2024-50134",
      "enumeration": "CVE",
      "package": {
        "architecture": "amd64",
        "condition": "Package default status",
        "name": "linux-image-cloud-amd64",
        "source": "linux-signed-amd64 (5.10.226+1)",
        "version": "5.10.226-1"
      },
      "published": "0000-01-01T00:00:00Z",
      "score": {
        "base": "-1",
        "version": "-"
      },
      "severity": "-",
      "status": "Active",
      "title": "CVE-2024-50134 affects linux-image-cloud-amd64",
      "type": "Packages",
      "updated": "0000-01-01T00:00:00Z"
    }
  },
  "location": "vulnerability-detector"
}
```

2024-11-21 19:44 UTC, sebasfalcone approved these changes
# Testing 🟢 

## Alert generation with severity "-"

Baseline:
![image](https://github.com/user-attachments/assets/ce87c3a7-9a29-4089-95df-d721cb02703b)

New vulnerability:
![image](https://github.com/user-attachments/assets/15305397-de40-4d88-b2e9-053740d9d7cb)

Alert generated:
![image](https://github.com/user-attachments/assets/188ab6a9-f6d8-468f-b0aa-1fc3a635ba8f)

Rule '23508' triggered:
```json
{
  "timestamp": "2024-11-21T16:42:10.463-0300",
  "rule": {
    "level": 3,
    "description": "CVE-2023-52474 affects python3-perf",
    "id": "23508",
    "firedtimes": 1,
    "mail": false,
    "groups": [
      "vulnerability-detector"
    ],
    "gdpr": [
      "IV_35.7.d"
    ],
    "pci_dss": [
      "11.2.1",
      "11.2.3"
    ],
    "tsc": [
      "CC7.1",
      "CC7.2"
    ]
  },
  "agent": {
    "id": "018",
    "name": "centos8",
    "ip": "10.0.2.15"
  },
  "manager": {
    "name": "sebas-ThinkPad"
  },
  "id": "1732218130.10392938",
  "decoder": {
    "name": "json"
  },
  "data": {
    "vulnerability": {
      "classification": "-",
      "cve": "CVE-2023-52474",
      "enumeration": "CVE",
      "package": {
        "architecture": "x86_64",
        "condition": "Package default status",
        "name": "python3-perf",
        "source": " ",
        "version": "4.18.0-348.7.1.el8_5"
      },
      "published": "0000-01-01T00:00:00Z",
      "score": {
        "base": "-1",
        "version": "-"
      },
      "severity": "-",
      "status": "Active",
      "title": "CVE-2023-52474 affects python3-perf",
      "type": "Packages",
      "updated": "0000-01-01T00:00:00Z"
    }
  },
  "location": "vulnerability-detector"
}

```

2024-11-21 20:27 UTC, sebasfalcone commented on ruleset/rules/0520-vulnerability-detector_rules.xml
> +    <description>$(vulnerability.cve) affects $(vulnerability.package.name)</description>
```suggestion
    <description>$(vulnerability.cve) affects $(vulnerability.package.name) (Missing information, CVE awaiting analysis)</description>
```

2024-11-21 20:27 UTC, sebasfalcone approved these changes

2024-11-22 02:27 UTC, Dwordcito approved these changes

2024-11-22 02:27 UTC, merged