Change to type the agent's os
wazuh/wazuh pull request #27125
Opened 2024-12-02 13:52 UTC by javiersanchz

|Related issue|
|---|
| #27119  |

## Description

The agent's header section was modified by replacing `os.platform` with `os.type`.

```console
{
  "id": "0a96a0ab-5bef-415c-bb3c-ea3e294215a0",
  "name": "test",
  "key": "7b8276c3bf96aff5709346d368f04fed",
  "type": "endpoint",
  "groups": [],
  "version": "5.0.0",
  "host": {
        "architecture": "x86_64",
        "hostname": "wazuh-agent",
        "ip": ["127.0.0.1"],
        "os": {
        "name": "Debian 12 bookworm",
        "type": "Linux",
        "version": "tests"
        }
  }
}
'
```
```console
       "os": {
        "name": "Debian 12 bookworm",
        "type": "Linux",
        "version": "tests"
        }
```

2024-12-02 14:28 UTC, GGP1 requested changes

2024-12-02 14:28 UTC, GGP1 commented on framework/wazuh/core/indexer/models/agent.py
> +    type: str = None
This field is used in some unit tests, we should update them as well:

- https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/batcher/tests/test_client.py
- https://github.com/wazuh/wazuh/blob/master/apis/comms_api/core/test/test_events.py

2024-12-02 16:52 UTC, GGP1 submitted a review, later dismissed
LGTM

2024-12-04 11:42 UTC, fdalmaup approved these changes
LGTM

2024-12-04 12:28 UTC, fdalmaup approved these changes

2024-12-04 12:56 UTC, merged