Vulnerability Scanner - Fix to avoid infinite loop
wazuh/wazuh pull request #27239
Opened 2024-12-09 18:50 UTC by sebasfalcone

|Related issue|
|---|
| #7061 |

## Description

This PR ports the changes from #26922 to prevent infinite loops in the Vulnerability Scanner module

## Tests
WIP

2024-12-10 15:11 UTC, pereyra-m requested changes
Gj!

I'd move the UT. I'll begin with the manual tests.

2024-12-10 15:11 UTC, pereyra-m commented on src/shared_modules/utils/tests/rocksDBSafeQueuePrefix_test.cpp
This folder isn't being compiled, so these tests won't run.
They should be moved to `wazuh/src/engine/source/base/test/src/unit/utils/`.

I propose also to create a new issue to better manager these folders that cause confusion. Maybe move them under a `deprecated` folder? Maybe remove them completely?
This issue could verify that no UT is missing.

2024-12-11 02:59 UTC, pereyra-m commented
## Manual tests :green_circle: 

I've compiled the `indexer_connector_tool` from this development branch.
Then, using the Wazuh Docker repository, I tried different inputs with this configuration 

<details><summary>config.json</summary>
<p>

```json
{
  "name": "wazuh-states-vulnerabilities-cluster",
  "enabled": "yes",
  "hosts": [
    "https://wazuh.indexer:9200"
  ],
  "username": "admin",
  "password": "SecretPassword",
  "ssl": {
    "certificate_authorities": [
      "/etc/filebeat/certs/root-ca.pem"
    ],
    "certificate": "/etc/filebeat/certs/wazuh.indexer.pem",
    "key": "/etc/filebeat/certs/wazuh.indexer-key.pem"
  }
}
```

</p>
</details> 

### Valid input

<details><summary>example.json</summary>
<p>

```json
{
  "id": "000_pkghash_CVE-2022-1234",
  "operation": "INSERT",
  "data": {
    "agent": {
      "id": "000",
      "name": "agent_name_1",
      "type": "agent_type_1",
      "version": "1.0.0"
    },
    "message": "Sample message"
  }
}
```

</p>
</details> 

<details><summary>Result</summary>
<p>

```bash
╰─# ./indexer_connector_tool -c /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/config.json -e /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/example.json
Press enter to stop the indexer connector tool... 
2024-12-11 02:20:46.146 142087:142109 indexerConnector.cpp:270 at operator()::<lambda>handleSuccessfulPostResponse(): debug: Response: {"took":2041,"errors":false,"items":[{"index":{"_index":"wazuh-states-vulnerabilities-cluster","_id":"000_pkghash_CVE-2022-1234","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
```

</p>
</details> 

### Valid input without ID

<details><summary>example.json</summary>
<p>

```json
{
  "operation": "INSERT",
  "data": {
    "agent": {
      "id": "000",
      "name": "agent_name_1",
      "type": "agent_type_1",
      "version": "1.0.0"
    },
    "message": "Sample message"
  }
}
```

</p>
</details> 

<details><summary>Result</summary>
<p>

```bash
╰─# ./indexer_connector_tool -c /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/config.json -e /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/example.json
Press enter to stop the indexer connector tool... 
2024-12-11 02:34:04.511 147872:147893 indexerConnector.cpp:270 at operator()::<lambda>handleSuccessfulPostResponse(): debug: Response: {"took":2046,"errors":false,"items":[{"index":{"_index":"wazuh-states-vulnerabilities-cluster","_id":"8g2Qs5MB0tg7qP_g9-m4","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
```

</p>
</details> 

### Missing ID

<details><summary>example.json</summary>
<p>

```json
{
  "operation": "DELETE"
}
```

</p>
</details> 

<details><summary>Result</summary>
<p>

```bash
╰─# ./indexer_connector_tool -c /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/config.json -e /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/example.json
Press enter to stop the indexer connector tool... 
2024-12-11 02:31:10.695 146797:146818 indexerConnector.cpp:254 at operator()(): warning: Event required field (data) is missing: {"operation":"DELETE"}
```

</p>
</details> 

### Missing data

<details><summary>example.json</summary>
<p>

```json
{
  "id": "000_pkghash_CVE-2022-1234",
  "operation": "INSERT"
}
```

</p>
</details> 

<details><summary>Result</summary>
<p>

```bash
╰─# ./indexer_connector_tool -c /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/config.json -e /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/example.json
Press enter to stop the indexer connector tool... 
2024-12-11 02:32:10.642 147227:147248 indexerConnector.cpp:254 at operator()(): warning: Event required field (data) is missing: {"id":"000_pkghash_CVE-2022-1234","operation":"INSERT"}
```

</p>
</details> 

### Mixed input

The input is combination of valid and invalid inputs, 10000 elements of each one.
The missing field `data` prevents the invalid elements to reach the queue.

<details><summary>Result</summary>
<p>

![2024-12-10_23-46](https://github.com/user-attachments/assets/361db9d6-1b82-42ca-ae7d-b0d16107de01)

</p>
</details> 

### Mixed input with Indexer temporarily unavailable 

The input is combination of valid and invalid inputs, 10000 elements of each one.
The Indexer is down at the beginning, and then it's restarted.
The invalid elements contain invalid JSON

<details><summary>No server</summary>
<p>

```bash
2024-12-11 02:54:26.567 154181:154202 threadEventDispatcher.hpp:205 at singleAndOrdered(): error: Dispatch handler error: No available server
```

Queue DB

```bash
╰─# ls -lh
total 210M
drwxr-xr-x 3 root root 4.0K Dec 11 02:30 CMakeFiles
-rw-r--r-- 1 root root 1.3K Dec 11 02:30 cmake_install.cmake
-rw-r--r-- 1 root root  341 Dec 11 02:30 CTestTestfile.cmake
-rwxr-xr-x 1 root root 210M Dec 11 02:52 indexer_connector_tool
-rw-r--r-- 1 root root 6.6K Dec 11 02:30 Makefile
drwxr-xr-x 2 root root 4.0K Dec 11 02:52 wazuh-states-vulnerabilities-cluster
```

</p>
</details> 

<details><summary>Server up</summary>
<p>

Error message for invalid data
```bash
2024-12-11 02:56:51.150 154181:154202 indexerConnector.cpp:220 at operator()(): warning: Failed to parse event data: 
{
    "operation": "INSERT",
    "data": {
      "agent": {
        "id": "000",
        "name": "agent_name_1",
        "type": "agent_type_1",
        "version":
      },
      "message": "Sample message"
    }
  }
```

</p>
</details> 

<details><summary>Result</summary>
<p>

![2024-12-10_23-58](https://github.com/user-attachments/assets/25413a31-c07f-4805-98c5-922e87f0791c)

</p>
</details>

2024-12-23 20:23 UTC, GabrielEValenzuela submitted a review, later dismissed
## Manual tests :green_circle: 

I've compiled the `indexer_connector_tool` from this development branch.
Then, using Docker Compose I started an opensearch/kibana instance 

<details><summary>config.json</summary>
<p>

```json
{
  "name": "wazuh-states-vulnerabilities-cluster",
  "enabled": "yes",
  "hosts": [
    "http://127.0.0.1:9200"
  ],
  "username": "admin",
  "password": "WazuhEngine5+",
  "ssl": {
    "certificate_authorities": [
      "/workspaces/devContainer/opensearch/certs/wazuh-certificates/root-ca.pem"
    ],
    "certificate": "/workspaces/devContainer/opensearch/certs/wazuh-certificates/node-1.pem",
    "key": "/workspaces/devContainer/opensearch/certs/wazuh-certificates/node-1-key.pem"
  }
}
```

</p>
</details> 

### Valid input

<details><summary>example.json</summary>
<p>

```json
{
  "id": "000_pkghash_CVE-2022-1234",
  "operation": "INSERT",
  "data": {
    "agent": {
      "id": "000",
      "name": "agent_name_1",
      "type": "agent_type_1",
      "version": "1.0.0"
    },
    "message": "Sample message"
  }
}
```

</p>
</details> 

<details><summary>Result</summary>
<p>

```bash
╰─# ./indexer_connector_tool -c /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/config.json -e /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/example.json
Press enter to stop the indexer connector tool... 
2024-12-11 02:20:46.146 142087:142109 indexerConnector.cpp:270 at operator()::<lambda>handleSuccessfulPostResponse(): debug: Response: {"took":2041,"errors":false,"items":[{"index":{"_index":"wazuh-states-vulnerabilities-cluster","_id":"000_pkghash_CVE-2022-1234","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
```

</p>
</details> 

### Valid input without ID

<details><summary>example.json</summary>
<p>

```json
{
  "operation": "INSERT",
  "data": {
    "agent": {
      "id": "000",
      "name": "agent_name_1",
      "type": "agent_type_1",
      "version": "1.0.0"
    },
    "message": "Sample message"
  }
}
```

</p>
</details> 

<details><summary>Result</summary>
<p>

```bash
╰─# ./indexer_connector_tool -c /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/config.json -e /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/example.json
Press enter to stop the indexer connector tool... 
2024-12-11 02:34:04.511 147872:147893 indexerConnector.cpp:270 at operator()::<lambda>handleSuccessfulPostResponse(): debug: Response: {"took":2046,"errors":false,"items":[{"index":{"_index":"wazuh-states-vulnerabilities-cluster","_id":"8g2Qs5MB0tg7qP_g9-m4","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
```

</p>
</details> 

### Missing ID

<details><summary>example.json</summary>
<p>

```json
{
  "operation": "DELETE"
}
```

</p>
</details> 

<details><summary>Result</summary>
<p>

```bash
╰─# ./indexer_connector_tool -c /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/config.json -e /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/example.json
Press enter to stop the indexer connector tool... 
2024-12-11 02:31:10.695 146797:146818 indexerConnector.cpp:254 at operator()(): warning: Event required field (data) is missing: {"operation":"DELETE"}
```

</p>
</details> 

### Missing data

<details><summary>example.json</summary>
<p>

```json
{
  "id": "000_pkghash_CVE-2022-1234",
  "operation": "INSERT"
}
```

</p>
</details> 

<details><summary>Result</summary>
<p>

```bash
╰─# ./indexer_connector_tool -c /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/config.json -e /workspaces/5.x/wazuh/src/engine/source/indexerconnector/tool/input/example.json
Press enter to stop the indexer connector tool... 
2024-12-11 02:32:10.642 147227:147248 indexerConnector.cpp:254 at operator()(): warning: Event required field (data) is missing: {"id":"000_pkghash_CVE-2022-1234","operation":"INSERT"}
```

</p>
</details> 

### Mixed inputs

> [!NOTE]
> For this step I used this script


<details><summary>generator.sh</summary>

```bash
#!/bin/bash

# Paths to tools and input files
TOOL_PATH="/workspaces/devContainer/wazuh/src/engine/build/source/indexerconnector/tool/indexer_connector_tool"
CONFIG_PATH="/workspaces/devContainer/wazuh/src/engine/source/indexerconnector/tool/input/config.json"
EXAMPLE_PATH="/workspaces/devContainer/wazuh/src/engine/source/indexerconnector/tool/input/example.json"

# Helper function to generate a valid example.json
generate_valid_input() {
  cat > "$EXAMPLE_PATH" <<EOL
{
  "id": "$(printf "%03d" $((RANDOM % 1000)))_pkghash_CVE-2022-$((RANDOM % 9000 + 1000))",
  "operation": "INSERT",
  "data": {
    "agent": {
      "id": "$(printf "%03d" $((RANDOM % 1000)))",
      "name": "agent_name_$(printf "%03d" $((RANDOM % 1000)))",
      "type": "agent_type_$(printf "%03d" $((RANDOM % 1000)))",
      "version": "1.0.0"
    },
    "message": "Sample message"
  }
}
EOL
}

# Helper function to generate an invalid example.json
generate_invalid_input() {
  cat > "$EXAMPLE_PATH" <<EOL
{
  "id": "$(printf "%03d" $((RANDOM % 1000)))_pkghash_CVE-2022-$((RANDOM % 9000 + 1000))",
  "operation": "INSERT"
}
EOL
}

# Function to run the tool and simulate pressing Enter
run_with_enter() {
  echo "" | "$TOOL_PATH" -c "$CONFIG_PATH" -e "$EXAMPLE_PATH"
}

# Run valid inputs
echo "Processing 10,000 valid inputs..."
for i in $(seq 1 10000); do
  generate_valid_input
  run_with_enter
done

# Run invalid inputs
echo "Processing 10,000 invalid inputs..."
for i in $(seq 1 10000); do
  generate_invalid_input
  run_with_enter
done

echo "Done."
```

</details>

The input is a combination of valid and invalid inputs, 10000 elements of each one.
The missing field `data` prevents the invalid elements from reaching the queue.

<details><summary>Result</summary>
<p>

![2024-12-23_16-15_1](https://github.com/user-attachments/assets/203cfc13-388a-4379-a445-755a1a5deee9)


</p>
</details> 

### Mixed input with Indexer temporarily unavailable 

The input is a combination of valid and invalid inputs, 10000 elements of each one.
The Indexer is down at the beginning, and then it's restarted.
The invalid elements contain invalid JSON

<details><summary>No server</summary>
<p>

![2024-12-23_16-15](https://github.com/user-attachments/assets/eb25e739-b16b-4f2f-98b5-2892300b146a)


Queue DB

![2024-12-23_16-14](https://github.com/user-attachments/assets/0abf15e2-e721-439e-8b2d-4fdf492ee063)


</p>
</details> 

<details><summary>Server up</summary>
<p>

Error message for invalid data, once the test finished. Also, keep running the tool doesn't show a normally behaviour of a infinite loop

![2024-12-23_17-14](https://github.com/user-attachments/assets/41374287-f6ec-4eb9-a35e-103aaf76823b)


</p>
</details> 

<details><summary>Result (No changes on the indexer)</summary>
<p>

![2024-12-23_16-15_1](https://github.com/user-attachments/assets/203cfc13-388a-4379-a445-755a1a5deee9)

</p>
</details>

2025-01-06 11:34 UTC, Dwordcito requested changes

2025-01-06 11:34 UTC, Dwordcito commented on src/engine/source/indexerconnector/src/indexerConnector.cpp
> +                    LOG_WARNING("Failed to parse event data: {}", data.c_str());
spdlog/fmt handle std::string / std::string_view.


```suggestion
                    LOG_WARNING("Failed to parse event data: {}", data);
```

2025-01-06 11:34 UTC, Dwordcito commented on src/engine/source/indexerconnector/src/indexerConnector.cpp
> +                    LOG_WARNING("Event required field (operation) is missing: {}", data.c_str());
spdlog/fmt handle std::string / std::string_view.

```suggestion
                    LOG_WARNING("Event required field (operation) is missing: {}", data);
```

2025-01-06 11:34 UTC, Dwordcito commented on src/engine/source/indexerconnector/src/indexerConnector.cpp
> +                        LOG_WARNING("Event required field (id) is missing: {}", data.c_str());
spdlog/fmt handle std::string / std::string_view.
```suggestion
                        LOG_WARNING("Event required field (id) is missing: {}", data);
```

2025-01-06 11:34 UTC, Dwordcito commented on src/engine/source/indexerconnector/src/indexerConnector.cpp
> +                        LOG_WARNING("Event required field (data) is missing: {}", data.c_str());
spdlog/fmt handle std::string / std::string_view.

```suggestion
                        LOG_WARNING("Event required field (data) is missing: {}", data);
```

2025-01-06 11:34 UTC, Dwordcito commented on src/engine/source/indexerconnector/src/indexerConnector.cpp
>                      const auto& id = parsedData.at("id").get_ref<const std::string&>();
1. Shadow variable.
2. non necessary because the line #L235

```suggestion
```

2025-01-06 11:34 UTC, Dwordcito commented on src/engine/source/base/include/base/utils/threadSafeQueue.hpp
> +        std::lock_guard<std::mutex> lock {m_mutex};
```suggestion
        std::scoped_lock lock {m_mutex};
```

2025-01-06 11:34 UTC, Dwordcito commented on src/engine/source/base/include/base/utils/threadSafeQueue.hpp
remove line 16 (#include <iostream>)

2025-01-06 16:33 UTC, sebasfalcone commented
Failing tests fixed here:
- https://github.com/wazuh/wazuh/pull/27486

2025-01-10 03:05 UTC, Dwordcito approved these changes

2025-01-10 03:05 UTC, merged