Change compressed vuldet database path
wazuh/wazuh pull request #27250
Opened 2024-12-10 18:22 UTC by MiguelazoDS

|Related issue|
|---|
|#27229|

## Description

Changed vd compressed database path to `/var/lib/wazuh-server/tmp`

## DoD

- Using test tool 
![image](https://github.com/user-attachments/assets/686da331-dd7a-422d-893c-c02f20be9796)
![image](https://github.com/user-attachments/assets/ad4693f0-5f4c-40d7-bd92-150ef2248cb7)
![image](https://github.com/user-attachments/assets/a97f909d-3554-4d85-ae9e-319df6dbaa7f)

2024-12-19 19:19 UTC, sebasfalcone approved these changes
## Key changes
- Merged certs path is now configurable (this facilitated the testing)
- Temporary files moved to `/var/lib/wazuh-server/tmp/` instead of `/tmp`

## Testing
Provided by @MiguelazoDS 

- DB decompression 🟢 
- Merged certs generation 🟢

2025-01-06 11:01 UTC, Dwordcito commented
@MiguelazoDS this branch needs rebase.

2025-01-10 00:37 UTC, Dwordcito requested changes

2025-01-10 00:37 UTC, Dwordcito commented on src/engine/source/indexerconnector/include/indexerConnector/indexerConnector.hpp
> +        std::string merged_ca_path;      ///< The path containing the merged ca.
use camelCase.

2025-01-10 00:37 UTC, Dwordcito commented on src/engine/source/indexerconnector/test/component/indexerConnector_test.cpp
> +                                                          .merged_ca_path = MERGED_CA_PATH},
dito

2025-01-10 00:37 UTC, Dwordcito commented on src/engine/source/indexerconnector/src/indexerConnector.cpp
> +    std::string caRootCertificate = config.sslOptions.merged_ca_path;
dito

2025-01-10 01:26 UTC, MiguelazoDS commented on src/engine/source/indexerconnector/include/indexerConnector/indexerConnector.hpp
> +        std::string merged_ca_path;      ///< The path containing the merged ca.
Changed

2025-01-10 01:26 UTC, MiguelazoDS commented on src/engine/source/indexerconnector/src/indexerConnector.cpp
> +    std::string caRootCertificate = config.sslOptions.merged_ca_path;
Changed

2025-01-10 01:27 UTC, MiguelazoDS commented on src/engine/source/indexerconnector/test/component/indexerConnector_test.cpp
> +                                                          .merged_ca_path = MERGED_CA_PATH},
Changed

2025-01-10 11:27 UTC, sebasfalcone approved these changes

2025-01-16 18:41 UTC, Dwordcito approved these changes

2025-01-16 18:42 UTC, merged