Check Wazuh files ownership
wazuh/wazuh pull request #27287
Opened 2024-12-13 13:23 UTC by nico-stefani

|Related issue|
|---|
|#27263|

## Description

This PR closes #27263. Renames the default user and group to `wazuh-server` and removes the `-r` flag from the init templates. 

## Logs/Alerts example

<details><summary>Installed from sources</summary>
<p>

```console
root@dde7d4951b11:/pkg# apt info wazuh-server
N: Unable to locate package wazuh-server
N: Unable to locate package wazuh-server
E: No packages found
root@dde7d4951b11:/pkg# ll /etc/wazuh-server/
total 28
drwxr-x--- 5 wazuh-server wazuh-server 4096 Dec 13 13:11 ./
drwxr-xr-x 1 root         root         4096 Dec 13 13:11 ../
drwxr-x--- 3 wazuh-server wazuh-server 4096 Dec 13 13:11 api/
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 13 13:11 cluster/
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 13 13:11 shared/
-rw-r----- 1 wazuh-server wazuh-server  887 Dec 13 13:11 wazuh-server.yml
root@dde7d4951b11:/pkg# ll /run/wazuh-server/
total 16
drwxr-x--- 4 wazuh-server wazuh-server 4096 Dec 13 13:11 ./
drwxr-xr-x 1 root         root         4096 Dec 13 13:10 ../
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 13 13:11 cluster/
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 13 13:11 socket/
root@dde7d4951b11:/pkg# ll /var/lib/wazuh-server/
total 24
drwxr-x--- 5 wazuh-server wazuh-server 4096 Dec 13 13:10 ./
drwxr-xr-x 1 root         root         4096 Dec 13 13:10 ../
drwxr-x--- 4 root                  110 4096 Oct 18 12:28 engine/
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 13 13:10 indexer-connector/
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 13 13:10 vd/
root@dde7d4951b11:/pkg# ll /var/log/wazuh-server/
total 16
drwxr-x--- 3 wazuh-server wazuh-server 4096 Dec 13 13:10 ./
drwxr-xr-x 1 root         root         4096 Dec 13 13:10 ../
drwxr-xr-x 2 wazuh-server wazuh-server 4096 Dec 13 13:10 engine/
```

</p>
</details> 

<details><summary>DEB Package</summary>
<p>

```console
root@3357aa93e3ef:/pkg# apt info wazuh-server
Package: wazuh-server
Version: 5.0.0-test
Status: install ok installed
Priority: extra
Section: admin
Maintainer: Wazuh, Inc <info@wazuh.com>
Installed-Size: 546 MB
Depends: libc6 (>= 2.7), lsb-release, debconf, adduser
Suggests: expect
Replaces: wazuh-api
Homepage: http://www.wazuh.com
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Wazuh server
 Wazuh helps you to gain security visibility into your infrastructure by monitoring
 hosts at an operating system and application level. It provides the following
 capabilities: log analysis, file integrity monitoring, intrusions detection
 and policy and compliance monitoring.

root@3357aa93e3ef:/pkg# ll /etc/wazuh-server/
total 28
drwxr-x--- 5 wazuh-server wazuh-server 4096 Dec 13 10:15 ./
drwxr-xr-x 1 root         root         4096 Dec 13 10:15 ../
drwxr-x--- 3 wazuh-server wazuh-server 4096 Dec 13 10:15 api/
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 12 15:27 cluster/
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 12 15:27 shared/
-rw-r----- 1 wazuh-server wazuh-server  887 Dec 12 15:27 wazuh-server.yml
root@3357aa93e3ef:/pkg# ll /run/wazuh-server/
total 16
drwxr-x--- 4 wazuh-server wazuh-server 4096 Dec 13 10:15 ./
drwxr-xr-x 1 root         root         4096 Dec 13 10:15 ../
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 12 15:27 cluster/
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 12 15:27 socket/
root@3357aa93e3ef:/pkg# ll /var/lib/wazuh-server/
total 28
drwxr-x--- 6 wazuh-server wazuh-server 4096 Dec 13 10:15 ./
drwxr-xr-x 1 root         root         4096 Dec 13 10:15 ../
drwxr-x--- 5 wazuh-server wazuh-server 4096 Dec 13 10:15 engine/
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 12 15:26 indexer-connector/
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 13 10:15 tmp/
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 12 15:26 vd/
root@3357aa93e3ef:/pkg# ll /var/log/wazuh-server/
total 16
drwxr-xr-x 3 wazuh-server wazuh-server 4096 Dec 13 10:15 ./
drwxr-xr-x 1 root         root         4096 Dec 13 10:15 ../
drwxr-xr-x 2 wazuh-server wazuh-server 4096 Dec 12 15:26 engine/
```

</p>
</details> 

<details><summary>RPM Package</summary>
<p>

```console
[root@08f8285f603d pkg]# yum info wazuh-server
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
Installed Packages
Name        : wazuh-server
Arch        : x86_64
Version     : 5.0.0
Release     : test
Size        : 529 M
Repo        : installed
From repo   : /wazuh-server_5.0.0-test_x86_64_5ad2395492
Summary     : Wazuh helps you to gain security visibility into your infrastructure by monitoring hosts at an operating system and application level. It provides the following capabilities: log analysis, file
            : integrity monitoring, intrusions detection and policy and compliance monitoring
URL         : https://www.wazuh.com/
License     : GPL
Description : Wazuh helps you to gain security visibility into your infrastructure by monitoring
            : hosts at an operating system and application level. It provides the following capabilities:
            : log analysis, file integrity monitoring, intrusions detection and policy and compliance monitoring

[root@08f8285f603d pkg]# ll /etc/wazuh-server/
total 16
drwxr-xr-x 3 wazuh-server wazuh-server 4096 Dec 13 13:21 api
drwxr-xr-x 2 wazuh-server wazuh-server 4096 Dec 12 20:36 cluster
drwxr-xr-x 2 wazuh-server wazuh-server 4096 Dec 12 20:36 shared
-rw-r--r-- 1 wazuh-server wazuh-server  887 Dec 12 20:36 wazuh-server.yml
[root@08f8285f603d pkg]# ll /run/wazuh-server/
total 8
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 12 20:36 cluster
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 12 20:36 socket
[root@08f8285f603d pkg]# ll /var/lib/wazuh-server/
total 16
drwxr-x--- 5 wazuh-server wazuh-server 4096 Dec 13 13:21 engine
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 12 20:35 indexer-connector
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 13 13:21 tmp
drwxr-x--- 2 wazuh-server wazuh-server 4096 Dec 12 20:35 vd
[root@08f8285f603d pkg]# ll /var/log/wazuh-server/
total 4
drwxr-xr-x 2 wazuh-server wazuh-server 4096 Dec 12 20:35 engine
```

</p>
</details>

2024-12-13 17:26 UTC, GGP1 requested changes
We should remove the `root` flag from the development environment [entrypoint](https://github.com/wazuh/wazuh/blob/ec878802edfdafff74fae942e26acf1f3bee368a/apis/tools/env/wazuh-server/scripts/entrypoint.sh#L22)

2024-12-13 17:26 UTC, GGP1 commented on packages/debs/SPECS/debian/rules
> +	chown -R wazuh-server:wazuh-server $(TARGET_DIR)$(INSTALLATION_DIR)run/wazuh-server
We could declare two variables `WAZUH_USER` and `WAZUH_GROUP` to avoid repeating the name on every line

2024-12-13 17:26 UTC, GGP1 commented on packages/rpms/SPECS/wazuh-server.spec
> +chown -R wazuh-server:wazuh-server %{_localstatedir}var/lib/wazuh-server
Same for this file

2024-12-16 17:25 UTC, GGP1 submitted a review, later dismissed
LGTM

2024-12-16 19:45 UTC, fdalmaup requested changes
Changes LGTM, we need to rebase the dev branch before merging it

2024-12-17 11:38 UTC, fdalmaup approved these changes
LGTM!

2024-12-17 11:39 UTC, merged