Add pre-commit and ruff linter and formatter
wazuh/wazuh pull request #27435
Opened 2024-12-23 15:22 UTC by GGP1

|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/20753 |

## Description

Adds the pre-commit and ruff configuration for linting and formatting files. It also includes lint and format fixes.

## Tests

<details><summary>ruff check (excluding D and C901 rules)</summary>

```console
gasti@gasti:~/work/wazuh$ ruff check --exclude */test*
All checks passed!
```

</details>

<details><summary>ruff format</summary>

```console
gasti@gasti:~/work/wazuh$ ruff format
305 files left unchanged
```

</details>

2024-12-26 11:34 UTC, nico-stefani requested changes

2024-12-26 11:34 UTC, nico-stefani commented on api/api/configuration.py
> +    'The `cache` API configuration option was deprecated in {release} and will be removed ' 'in the next minor release.'
```suggestion
    'The `cache` API configuration option was deprecated in {release} and will be removed in the next minor release.'
```

2024-12-26 11:34 UTC, nico-stefani commented on api/api/encoder.py
> +    """ "
```suggestion
    """
```

2024-12-26 11:34 UTC, nico-stefani commented on api/api/middlewares.py
> -
Add the line ending here

2024-12-26 17:41 UTC, nico-stefani submitted a review, later dismissed
LGTM

2024-12-26 19:25 UTC, fdalmaup reviewed
Changes LGTM, nevertheless we are introducing several changes to files that are currently being reviewed due to the 5.0 developments. The issue will be blocked until a decision is made by management.

2025-02-07 17:58 UTC, nico-stefani requested changes
I'm requesting some small changes, the rest LGTM. Also, rebase to the `main` branch.

2025-02-10 14:07 UTC, nico-stefani approved these changes
LGTM

2025-02-10 14:23 UTC, fdalmaup approved these changes
LGTM

2025-02-10 14:24 UTC, merged