Add helper float_calculate
wazuh/wazuh pull request #27442
Opened 2024-12-24 13:36 UTC by NahuFigueroa97

|Related issue|
|---|
|#27373|

## Description

2025-01-07 19:01 UTC, juliancnn requested changes

2025-01-07 19:01 UTC, juliancnn commented on src/engine/source/builder/src/builders/opmap/opBuilderHelperMap.cpp
> +    std::function<float(float l, float r)> transformFunction;
This does not imply changing the name of the helper or anything like that, it is simply increasing the range or precision of the numbers. This will automatically re-fix the indexing if the target is float or double in the ECS since the output is a json.

2025-01-08 04:42 UTC, NahuFigueroa97 commented on src/engine/test/helper_tests/engine-helper-test/src/helper_test/test_cases_generator/argument.py
>      def configure_generation(
Because of this helper, we accept more than one subtype, that's why the change, it can be a string or a list

2025-01-08 14:29 UTC, juliancnn requested changes

2025-01-08 14:29 UTC, juliancnn commented on src/engine/source/builder/src/builders/opmap/opBuilderHelperMap.cpp
> +        fmt::format(R"([{}] -> Failure: Reference not found or not an float/integer: )", name)};
```suggestion
        fmt::format(R"([{}] -> Failure: Reference not found or not a number: )", name)};
```

2025-01-08 14:29 UTC, juliancnn commented on src/engine/source/builder/src/builders/opmap/opBuilderHelperMap.hpp
> +MapBuilder opBuilderHelperCalc(bool intCalc);
Fix the documentation

2025-01-08 14:29 UTC, juliancnn commented on src/engine/source/builder/src/builders/opmap/opBuilderHelperMap.hpp
> +MapBuilder opBuilderHelperCalc(bool intCalc);
change the name of the function,  is not a builder. Should be `getOpBuilderHelperCalc`

2025-01-09 19:03 UTC, juliancnn approved these changes
LGTM!

tested asset:
```yml
  - map:
      - a: -2
      - b: -2.1
      - c: -2.5
      - d: 0.1
      - e: 0.6
      - n1_r: float_calculate(div, $a, 3)
      - n2_r: float_calculate(div, $b, 3)
      - n3_r: float_calculate(div, $c, 3)
      - n4_r: float_calculate(div, $d, 3)
      - n5_r: float_calculate(div, $e, 3)
      - n1_t: float_calculate(div, $a, 2)
      - n2_t: float_calculate(div, $b, 2)
      - n3_t: float_calculate(div, $c, 2)
      - n4_t: float_calculate(div, $d, 2)
      - n5_t: float_calculate(div, $e, 2)

```

Output:
```
(venv) ╭─root@4e1c627e9718 /workspaces/engine-ubuntu-22/zz_tmp_files/testing_assets 
╰─# engine-test -c engine-test-conf.json run test -dd -n wazuh   

Enter any events [ENTER to send event, CTRL+C to finish]:

asd


---
traces:
[🔴] decoder/apache-access/0 -> failed
  ↳ [check: $event.module == apache-access] -> Failure
[🔴] decoder/apache-error/0 -> failed
  ↳ [check: $event.module == apache-error] -> Failure
[🟢] decoder/testing/0 -> success
  ↳ event.module: filter("test") -> Success
  ↳ a: map(-2) -> Success
  ↳ b: map(-2.1) -> Success
  ↳ c: map(-2.5) -> Success
  ↳ d: map(0.1) -> Success
  ↳ e: map(0.6) -> Success
  ↳ [n1_r: float_calculate("div", $a, 3)] -> Success
  ↳ [n2_r: float_calculate("div", $b, 3)] -> Success
  ↳ [n3_r: float_calculate("div", $c, 3)] -> Success
  ↳ [n4_r: float_calculate("div", $d, 3)] -> Success
  ↳ [n5_r: float_calculate("div", $e, 3)] -> Success
  ↳ [n1_t: float_calculate("div", $a, 2)] -> Success
  ↳ [n2_t: float_calculate("div", $b, 2)] -> Success
  ↳ [n3_t: float_calculate("div", $c, 2)] -> Success
  ↳ [n4_t: float_calculate("div", $d, 2)] -> Success
  ↳ [n5_t: float_calculate("div", $e, 2)] -> Success

output:
  a: -2
  agent:
    groups:
    - group1
    - group2
    host:
      architecture: x86_64
      hostname: wazuh-endpoint-linux
      ip:
      - 192.168.1.2
      os:
        name: Amazon Linux 2
        platform: Linux
    id: 2887e1cf-9bf2-431a-b066-a46860080f56
    name: wazuh-agent-name
    type: endpoint
    version: 5.0.0
  b: -2.1
  c: -2.5
  d: 0.1
  e: 0.6
  event:
    ingested: '2025-01-09T18:51:06Z'
    module: test
    original: asd
    provider: file
  log:
    file:
      path: /var/log/test.log
  n1_r: -0.6666666666666666
  n1_t: -1.0
  n2_r: -0.7000000000000001
  n2_t: -1.05
  n3_r: -0.8333333333333334
  n3_t: -1.25
  n4_r: 0.03333333333333333
  n4_t: 0.05
  n5_r: 0.19999999999999998
  n5_t: 0.3
  tags:
  - production-server



Enter any events [ENTER to send event, CTRL+C to finish]:

```

2025-01-10 13:12 UTC, JcabreraC commented
### Test:
```yml
  - map:  
      - a: -4  
      - b: -3.6  
      - c: 0.5  
      - d: 1.2  
      - n1_r: float_calculate(div, $a, 4)  
      - n2_r: float_calculate(div, $b, 4)  
      - n3_r: float_calculate(div, $c, 4)  
      - n4_r: float_calculate(div, $d, 4)  
      - n1_t: float_calculate(div, $a, 2)  
      - n2_t: float_calculate(div, $b, 2)  
      - n3_t: float_calculate(div, $c, 2)  
      - n4_t: float_calculate(div, $d, 2)  
```

Output:
```
# engine-test -c engine-test-conf.json run test -dd -n wazuh   

Enter any events [ENTER to send event, CTRL+C to finish]:  

test 

---  
traces:  
[🔴] decoder/apache-access/0 -> failed  
  ↳ [check: $event.module == apache-access] -> Failure  
[🔴] decoder/apache-error/0 -> failed  
  ↳ [check: $event.module == apache-error] -> Failure  
[🟢] decoder/testing/0 -> success  
  ↳ event.module: filter("test") -> Success  
  ↳ a: map(-4) -> Success  
  ↳ b: map(-3.6) -> Success  
  ↳ c: map(0.5) -> Success  
  ↳ d: map(1.2) -> Success  
  ↳ [n1_r: float_calculate("div", $a, 4)] -> Success  
  ↳ [n2_r: float_calculate("div", $b, 4)] -> Success  
  ↳ [n3_r: float_calculate("div", $c, 4)] -> Success  
  ↳ [n4_r: float_calculate("div", $d, 4)] -> Success  
  ↳ [n1_t: float_calculate("div", $a, 2)] -> Success  
  ↳ [n2_t: float_calculate("div", $b, 2)] -> Success  
  ↳ [n3_t: float_calculate("div", $c, 2)] -> Success  
  ↳ [n4_t: float_calculate("div", $d, 2)] -> Success  

output:  
  a: -4  
  agent:  
    groups:  
    - group1  
    - group2  
    host:  
      architecture: x86_64  
      hostname: wazuh-endpoint-linux  
      ip:  
      - 192.168.1.2  
      os:  
        name: Amazon Linux 2  
        platform: Linux  
    id: 2887e1cf-9bf2-431a-b066-a46860080f56  
    name: wazuh-agent-name  
    type: endpoint  
    version: 5.0.0  
  b: -3.6  
  c: 0.5  
  d: 1.2  
  event:  
    ingested: '2025-01-09T18:51:06Z'  
    module: test  
    original: test  
    provider: file  
  log:  
    file:  
      path: /var/log/test.log  
  n1_r: -1.0  
  n1_t: -2.0  
  n2_r: -0.9  
  n2_t: -1.8  
  n3_r: 0.125  
  n3_t: 0.25  
  n4_r: 0.3  
  n4_t: 0.6  
  tags:  
  - production-server  
```

2025-01-10 13:12 UTC, JcabreraC approved these changes
LGTM !

2025-01-22 16:56 UTC, merged