Add ends_with helper function
wazuh/wazuh pull request #27452
Opened 2024-12-26 22:14 UTC by NahuFigueroa97

|Related issue|
|---|
||

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2025-01-08 15:05 UTC, juliancnn requested changes

2025-01-08 15:05 UTC, juliancnn commented on src/engine/source/builder/src/builders/opfilter/opBuilderHelperFilter.cpp
> +            auto referenceString = referenceValue.getString().value();
```suggestion
            auto refPath = std::static_pointer_cast<Reference>(parameter)->jsonPath();          
            auto jRefValue = event->getString("refPath");
            if (jRefValue)
               // Not exist or is not a string
               return
              // rest of code
             
             
             
```

2025-01-08 15:05 UTC, juliancnn commented on src/engine/source/builder/src/builders/opfilter/opBuilderHelperFilter.hpp
> + * @brief Create `array_not_contains` helper function that filters events if the field
fix doc

2025-01-08 15:05 UTC, juliancnn commented on src/engine/test/helper_tests/helpers_description/filter/ends_with.yml
> +    Checks if the value stored in the field ends with the value provided.
```suggestion
    Checks if the string stored in the field ends with the value provided.
```

2025-01-08 15:05 UTC, juliancnn commented on src/engine/test/helper_tests/helpers_description/filter/ends_with.yml
> +    - undefined
```suggestion
    - string
```

2025-01-09 18:26 UTC, juliancnn approved these changes
LGTM!

![Uploading image.png…]()

2025-01-13 13:55 UTC, JcabreraC commented
## Decoder
```yml
name: decoder/testing/0
check:
- event.module: test

normalize:
  - check:
     - event.original: ends_with("end line")
    map:
      - end_line: true

  - check: ends_with($event.original, "end line 2")
    map:
      - end_line_2: true
```

## Test
```bash
# engine-test -c engine-test-conf.json run test                

Enter any events [ENTER to send event, CTRL+C to finish]:

hi end line


---
agent:
  groups:
  - group1
  - group2
  host:
    architecture: x86_64
    hostname: wazuh-endpoint-linux
    ip:
    - 192.168.1.2
    os:
      name: Amazon Linux 2
      platform: Linux
  id: 2887e1cf-9bf2-431a-b066-a46860080f56
  name: wazuh-agent-name
  type: endpoint
  version: 5.0.0
end_line: true
event:
  created: '2025-01-13T13:34:02Z'
  module: test
  original: hi end line
  provider: file
log:
  file:
    path: /var/log/test.log
tags:
- production-server



Enter any events [ENTER to send event, CTRL+C to finish]:

end line 2


---
agent:
  groups:
  - group1
  - group2
  host:
    architecture: x86_64
    hostname: wazuh-endpoint-linux
    ip:
    - 192.168.1.2
    os:
      name: Amazon Linux 2
      platform: Linux
  id: 2887e1cf-9bf2-431a-b066-a46860080f56
  name: wazuh-agent-name
  type: endpoint
  version: 5.0.0
end_line_2: true
event:
  created: '2025-01-13T13:34:08Z'
  module: test
  original: end line 2
  provider: file
log:
  file:
    path: /var/log/test.log
tags:
- production-server
```

2025-01-13 13:56 UTC, JcabreraC approved these changes
LGTM !

2025-01-22 17:00 UTC, merged