Feature/5536 upgrade multiple agents endpoints
wazuh/wazuh pull request #5586
Opened 2020-07-29 09:57 UTC by mcarmona99

**Related issue**
#5536 

Hello team,

This PR closes #5536 . In this PR I have added new API endpoints to allow receiving a list of agents to upgrade, or all of them. Endpoints upgrade custom and get upgrade results for a list of agents (or all of them) have been added, too.
Endpoints:
- PUT /agents/upgrade
- PUT /agents/upgrade_custom
- GET /agents/upgrade_result
New test cases added to:
- test_agents_PUT_endpoints.tavern.yaml
- test_rbac_black_agents_endpoints.tavern.yaml
- test_rbac_white_agents_endpoints.tavern.yaml

Changes on spec.yaml, agents_controller.py, changes.md and on the three integration tests mentioned above.

2020-09-09 09:21 UTC, AdriiiPRodri requested changes

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/controllers/agents_controller.py
> +async def put_upgrade_multiple_agents(request, list_agents, pretty=False, wait_for_complete=False, wpk_repo=None,
Remove old functions (407\~465, 557\~579) and remove the word "multiple"

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/controllers/agents_controller.py
> +async def put_upgrade_multiple_custom_agents(request, list_agents, pretty=False, wait_for_complete=False,
Remove "multiple"

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/controllers/agents_controller.py
> +async def get_agent_upgrade_multiple(request, list_agents, timeout=3, pretty=False, wait_for_complete=False):
Remove "multiple"

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/controllers/agents_controller.py
> +    """Upgrade agents using a WPK file from online repository.
Change the docstring to numpydoc

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/controllers/agents_controller.py
> +    """Upgrade agents using a local WPK file.'.
Change the docstring to numpydoc

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/controllers/agents_controller.py
> +    """Get upgrade results from agents.
Change the docstring to numpydoc

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/controllers/agents_controller.py
> +                          wait_for_complete=True,  # Force wait_for_complete until timeout problems are resolved
Now we can use the wait_for_complete parameter

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/controllers/agents_controller.py
> +                          wait_for_complete=True,  # Force wait_for_complete until timeout problems are resolved
Now we can use the wait_for_complete_parameter

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/controllers/agents_controller.py
> +    dapi = DistributedAPI(f=agent.upgrade_multiple_agents,
Change upgrade_multiple_agents for upgrade_agents (new function in framework side)

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/controllers/agents_controller.py
> +    dapi = DistributedAPI(f=agent.upgrade_multiple_custom_agents,
Change upgrade_multiple_agents for upgrade_agents (new function in framework side)

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/controllers/agents_controller.py
> +    dapi = DistributedAPI(f=agent.get_upgrade_multiple_result,
Remove "multiple"

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/spec/changes.md
>  ### PUT     /agents/{agent_id}/upgrade
Delete this endpoint

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/spec/spec.yaml
> +  /agents/upgrade:
Remove old endpoints (5661/~5770)

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/spec/spec.yaml
> +      operationId: api.controllers.agents_controller.put_upgrade_multiple_agents
Remove "multiple"

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/spec/spec.yaml
> +      operationId: api.controllers.agents_controller.put_upgrade_multiple_custom_agents
Remove "multiple"

2020-09-09 09:21 UTC, AdriiiPRodri commented on api/api/spec/spec.yaml
> +      operationId: api.controllers.agents_controller.get_agent_upgrade_multiple
Remove "multiple"

2020-10-16 15:10 UTC, mcarmona99 commented
The changes made in this PR have been merged into the branch `dev-5537-refactor_framework_upgrade_module` and will be merged into master in the PR: #5979 .

2020-10-16 15:10 UTC, closed without merging