Add condition to prevent syscheck double scan.
wazuh/wazuh pull request #5723
Opened 2020-08-12 12:49 UTC by antoniomanuelfr

|Related issue|
|---|
|#5376|

## Description
This PR aims to fix the issue #5376 by changing the `check_deleted_files` in order to return the number of deletions that have been performed in the DB and then check if there is any file that was not monitored before.

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [X] Source installation
- [ ] Package installation
- [X] Source upgrade
- [ ] Package upgrade

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

2020-08-20 10:16 UTC, Molter73 requested changes

2020-08-20 10:16 UTC, Molter73 commented on src/syscheckd/create_db.c
> +    w_mutex_unlock(&syscheck.fim_entry_mutex);
This 3 lines can be removed, the next scan does not use the `scanned` flag.

2020-08-20 10:16 UTC, Molter73 commented on src/syscheckd/create_db.c
> +    if (syscheck.file_limit_enabled && !syscheck.database->full && (nodes_count >= syscheck.file_limit)) {
We can remove `!syscheck.database->full` from this if, it will be checked in the upcoming while

2020-08-20 10:16 UTC, Molter73 commented on src/syscheckd/create_db.c
> +            nodes_count = fim_db_get_count_entry_path(syscheck.database);
This call to `fim_db_get_count_entry_path` no longer has a purpouse in this while, please remove it.

2020-08-20 10:16 UTC, Molter73 commented on src/syscheckd/create_db.c
> +    w_mutex_unlock(&syscheck.fim_entry_mutex);
Please fix indentation of the previous 3 lines.

2020-08-20 10:16 UTC, Molter73 commented on src/syscheckd/create_db.c
>          os_winreg_check();
Please fix the indentation in this line.

2020-08-20 10:16 UTC, Molter73 commented on src/syscheckd/create_db.c
> +        if (nodes_count < syscheck.file_limit) {
This condition should be replaced by checking the value of `syscheck.database->full` instead.

2020-08-27 09:22 UTC, bah07 approved these changes
LGTM!

2020-08-31 07:40 UTC, Molter73 approved these changes
LGTM!

2020-10-06 13:43 UTC, bah07 approved these changes
LGTM!

2020-10-09 16:04 UTC, merged