New authorization context login method revocation system
wazuh/wazuh pull request #5814
Opened 2020-08-25 10:33 UTC by AdriiiPRodri

|Related issue|
|---|
|#5736|

Hi team,

This PR closes #5736. In this PR we have added a new system to revoke tokens granted through the authorization contexts based authentication method. In addtion, we have added missing pretty parameters.

### Unittests results

```bash
adriiiprodri@wazuh python3 -m pytest -xs api/api/test/test_authentication.py
========================================================= test session starts =========================================================
platform linux -- Python 3.7.5, pytest-5.4.1, py-1.7.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: html-2.0.1, mock-1.10.0, asyncio-0.12.0, aiohttp-0.3.0, cov-2.8.1, testinfra-5.0.0, tavern-1.0.0, metadata-1.8.0
collected 10 items

api/api/test/test_authentication.py ..........

=================================================== 10 passed, 2 warnings in 0.55s ====================================================

adriiiprodri@wazuh python3 -m pytest -xs framework/wazuh/rbac/tests/
========================================================= test session starts =========================================================
platform linux -- Python 3.7.5, pytest-5.4.1, py-1.7.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/framework
plugins: html-2.0.1, mock-1.10.0, asyncio-0.12.0, aiohttp-0.3.0, cov-2.8.1, testinfra-5.0.0, tavern-1.0.0, metadata-1.8.0
collected 218 items

framework/wazuh/rbac/tests/test_auth_context.py ..
framework/wazuh/rbac/tests/test_decorators.py .........................................................................................................
framework/wazuh/rbac/tests/test_default_configuration.py ...............................................
framework/wazuh/rbac/tests/test_orm.py .....................................................
framework/wazuh/rbac/tests/test_preprocessor.py ...........

============================================= 218 passed, 3 warnings in 189.12s (0:03:09) =============================================
```

### Integrated results

```bash
adriiiprodri@wazuh python3 run_tests.py -rbac both -k security
Collected tests [6]:
test_rbac_black_security_endpoints.tavern.yaml, test_rbac_white_security_endpoints.tavern.yaml, test_security_DELETE_endpoints.tavern.yaml, test_security_GET_endpoints.tavern.yaml, test_security_POST_endpoints.tavern.yaml, test_security_PUT_endpoints.tavern.yaml

test_rbac_black_security_endpoints.tavern.yaml 
	 23 passed, 122 warnings

test_rbac_white_security_endpoints.tavern.yaml 
	 24 passed, 122 warnings

test_security_DELETE_endpoints.tavern.yaml 
	 14 passed, 87 warnings

test_security_GET_endpoints.tavern.yaml 
	 17 passed, 128 warnings

test_security_POST_endpoints.tavern.yaml 
	 6 passed, 62 warnings

test_security_PUT_endpoints.tavern.yaml 
	 8 passed, 51 warnings
```

Regards

2020-08-26 09:52 UTC, vicferpoy requested changes

2020-08-26 09:52 UTC, vicferpoy commented on api/test/integration/test_authorization_contexts_login_method.tavern.yaml
> +---
Change test name. Suggestions:
- test_authorization_context.tavern.yaml
- test_authorization_context_login.tavern.yaml

2020-08-26 09:52 UTC, vicferpoy commented on api/test/integration/test_authorization_contexts_login_method.tavern.yaml
> +        Authorization: "Basic {basic_auth:s}"
We are using the same `user:pass` as above. Is this correct? Take a look at the var `basic_auth` in `common.yaml`

2020-08-26 09:52 UTC, vicferpoy commented on framework/wazuh/rbac/orm.py
> +        nbf_invalid_until: The tokens that has an nbf prior to this timestamp will be invalidated
```suggestion
        nbf_invalid_until: The tokens that have an nbf prior to this timestamp will be invalidated
```

2020-08-26 09:52 UTC, vicferpoy commented on framework/wazuh/rbac/orm.py
> +    def is_token_valid(self,token_nbf_time: int, user_id: int = None, role_id: int = None):
```suggestion
    def is_token_valid(self, token_nbf_time: int, user_id: int = None, role_id: int = None):
```

2020-08-26 09:52 UTC, vicferpoy commented on framework/wazuh/rbac/orm.py
> +        List of removed users and roles rules
```suggestion
        List of removed user and role rules
```

2020-08-26 10:23 UTC, vicferpoy approved these changes

2020-08-26 13:08 UTC, davidjiglesias approved these changes

2020-08-27 08:22 UTC, davidjiglesias approved these changes

2020-08-27 08:22 UTC, merged