Fix some API integration tests cases
wazuh/wazuh pull request #5925
Opened 2020-09-04 12:13 UTC by mcarmona99

Hi team,

In this PR I have fixed some failed API integration test cases in:

```
test_cluster_endpoints.tavern.yaml
Before: 53 passed, 3 failed
Now: 54 passed, 2 failed
```

```
test_manager_endpoints.tavern.yaml
Before: 32 passed, 3 failed
Now: 34 passed, 1 failed
```

In both of these tests I have deleted expected items which were not returned in the response.

Regards,
Manuel.

2020-09-07 09:41 UTC, davidjiglesias requested changes

2020-09-07 09:41 UTC, davidjiglesias commented on api/test/integration/test_manager_endpoints.tavern.yaml
> +          total_affected_items: 21
Change this test to check for anything in the affected_items and any int in the total_affected_items

2020-09-09 10:49 UTC, mcarmona99 commented
Branch master merged into develop. Update test_manager in order to expect a more generic response.

**Test results**

```
test_cluster_endpoints.tavern.yaml 
	 1 failed, 55 passed, 72 warnings
test_manager_endpoints.tavern.yaml
         TODO waiting for "stop iteration" issue
```

2020-09-11 09:18 UTC, mcarmona99 commented
The requested changes in this PR have been done in the pull request: https://github.com/wazuh/wazuh/pull/5974, among others.
This PR is going to be closed.

2020-09-11 09:18 UTC, closed without merging