Implementation of the option report_changes for Windows registries
wazuh/wazuh pull request #5936
Opened 2020-09-07 10:11 UTC by jotacarma90

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/5865|

## Description
Branch work for the implementation of the report_changes option in the Windows registry improvement.

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

2020-09-17 08:49 UTC, Molter73 requested changes

2020-09-17 08:49 UTC, Molter73 commented on src/syscheckd/fim_diff_changes.c
> +int fim_diff_process_delete_file(char *filename){
```suggestion
int fim_diff_process_delete_file(const char *filename){
```

2020-09-17 08:49 UTC, Molter73 commented on src/syscheckd/fim_diff_changes.c
> +}
Consider the following alternate implementation of this function:
``` c
int fim_diff_process_delete_registry(const char *key_name, int arch) {
    char full_path[PATH_MAX];
    os_sha1 encoded_key;

    OS_SHA1_Str(key_name, strlen(key_name), encoded_key);

    if (arch) {
        snprintf(full_path, PATH_MAX, "%s/registry/[x64] %s", DIFF_DIR_PATH, encoded_key);
    } else {
        snprintf(full_path, PATH_MAX, "%s/registry/[x32] %s", DIFF_DIR_PATH, encoded_key);
    }

    if (fim_diff_delete_compress_folder(full_path) == -1) {
        return -1;
    }

    return 0;
}
```

2020-09-17 08:49 UTC, Molter73 commented on src/syscheckd/fim_diff_changes.c
> +}
Consider the following alternate implementation of this function:
``` c
int fim_diff_process_delete_value(const char *key_name, const char *value_name, int arch) {
    char full_path[PATH_MAX];
    os_sha1 encoded_key;
    os_sha1 encoded_value;

    OS_SHA1_Str(key_name, strlen(key_name), encoded_key);
    OS_SHA1_Str(value_name, strlen(value_name), encoded_value);

    if (arch) {
        snprintf(full_path, PATH_MAX, "%s/registry/[x64] %s/%s", DIFF_DIR_PATH, encoded_key, encoded_value);
    } else {
        snprintf(full_path, PATH_MAX, "%s/registry/[x32] %s/%s", DIFF_DIR_PATH, encoded_key, encoded_value);
    }

    if (fim_diff_delete_compress_folder(full_path) == -1) {
        return -1;
    }

    return 0;
}
```

2020-09-17 08:49 UTC, Molter73 commented on src/syscheckd/syscheck.h
> +char * fim_registry_value_diff(char *key_name, char *value_name, char *value_data, DWORD data_type, registry *configuration);
```suggestion
char *fim_registry_value_diff(const char *key_name,
                              const char *value_name,
                              const char *value_data,
                              DWORD data_type,
                              const registry *configuration);
```

2020-09-17 08:49 UTC, Molter73 commented on src/syscheckd/syscheck.h
> +int fim_diff_process_delete_file(char *filename);
```suggestion
int fim_diff_process_delete_file(const char *filename);
```

2020-09-17 08:49 UTC, Molter73 commented on src/syscheckd/syscheck.h
> +int fim_diff_process_delete_registry(char *key_name, int arch);
```suggestion
int fim_diff_process_delete_registry(const char *key_name, int arch);
```

2020-09-17 08:49 UTC, Molter73 commented on src/syscheckd/syscheck.h
> +int fim_diff_process_delete_value(char *key_name, char *value_name, int arch);
```suggestion
int fim_diff_process_delete_value(const char *key_name, const char *value_name, int arch);
```

2020-09-17 08:49 UTC, Molter73 commented on src/syscheckd/syscheck.h
> + * @brief Deletes the value diff folder and modify diff_folder_size if disk_quota enabled
```suggestion
 * @brief Deletes the value diff folder and modifies diff_folder_size if disk_quota enabled
```

2020-09-17 08:49 UTC, Molter73 commented on src/syscheckd/syscheck.h
> + * @param key_name Path of the registry that contain value deleted
```suggestion
 * @param key_name Path of the registry that contains the deleted value
```

2020-09-17 08:49 UTC, Molter73 commented on src/config/syscheck-config.c
> +void dump_registry_nodiff(syscheck_config *syscheck, char *entry, int arch) {
```suggestion
void dump_registry_nodiff(syscheck_config *syscheck, const char *entry, int arch) {
```

2020-09-17 08:49 UTC, Molter73 commented on src/config/syscheck-config.c
> +int dump_registry_nodiff_regex(syscheck_config *syscheck, char *regex, int arch) {
```suggestion
int dump_registry_nodiff_regex(syscheck_config *syscheck, const char *regex, int arch) {
```

2020-09-17 08:49 UTC, Molter73 commented on src/config/syscheck-config.c
> +                syscheck->registry_nodiff_regex);
```suggestion
                   syscheck->registry_nodiff_regex);
```

2020-09-17 08:49 UTC, Molter73 commented on src/config/syscheck-config.c
> +            syscheck->registry_nodiff_regex[ign_size].regex);
```suggestion
    os_calloc(1, sizeof(OSMatch), syscheck->registry_nodiff_regex[ign_size].regex);
```

2020-09-17 14:20 UTC, jotacarma90 commented on src/syscheckd/fim_diff_changes.c
> +    diff->file_size = (float)FileSize(diff->file_origin) / 1024;
This variable is used in the following "if" block as well. It is always necessary to initialize

2020-09-18 09:09 UTC, antoniomanuelfr commented on src/config/syscheck-config.c
> +                            return OS_INVALID;
The memory pointed by tag is not freed before returning `OS_INVALID`. 
This is the only bug reported by scan-build
```suggestion
                            mwarn(FIM_INVALID_REG_OPTION_SKIP, node[i]->values[j], node[i]->attributes[j], node[i]->content);
                            os_free(tag)
                            return OS_INVALID;
```

2020-09-18 09:34 UTC, antoniomanuelfr requested changes

2020-09-18 09:34 UTC, antoniomanuelfr commented on src/shared/syscheck_op.c
> +                    retval = -1;
Fix indentation.

2020-09-18 09:34 UTC, antoniomanuelfr commented on src/config/syscheck-config.c
> +                            mwarn(FIM_INVALID_REG_OPTION_SKIP, node[i]->values[j], node[i]->attributes[j], node[i]->content);
The memory pointed by `tag` is not freed.
This is the only bug reported by scan-build.
```suggestion
                            mwarn(FIM_INVALID_REG_OPTION_SKIP, node[i]->values[j], node[i]->attributes[j], node[i]->content);
                            os_free(tag);
```

2020-09-18 09:44 UTC, antoniomanuelfr approved these changes
LGTM!

2020-09-18 14:58 UTC, Molter73 approved these changes
LGTM!

2020-09-18 15:48 UTC, merged