[5730] RSYNC test tool
wazuh/wazuh pull request #5957
Opened 2020-09-08 19:52 UTC by konangc87

# Shared modules utils Generic Message Dispatcher class.

## **Related Issue**
[5730](https://github.com/wazuh/wazuh/issues/5730)

## Description
This issue aims to create a test tool to stress rsync and check that it's working correctly.

## DoD / Tasks
- [X] Implementation

Please fill the table above. Feel free to extend it at your convenience.
-->

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

2020-09-08 21:33 UTC, tinachoB requested changes

2020-09-08 21:33 UTC, tinachoB commented on src/shared_modules/rsync/testtool/agentEmulator.cpp
> +// #include <chrono>
remove unnecessary code

2020-09-08 21:33 UTC, tinachoB commented on src/shared_modules/rsync/testtool/agentEmulator.cpp
> +constexpr auto CRETE_STATEMENT{ "CREATE TABLE data_values(`key` BIGINT, `data1` BIGINT, `data2` BIGINT, `data3` BIGINT, PRIMARY KEY (`key`)) WITHOUT ROWID;"};
Typo -> CREATE_STATEMENT

2020-09-08 21:33 UTC, tinachoB commented on src/shared_modules/rsync/testtool/agentEmulator.cpp
> +							 const unsigned int maxDbItems,
indentation issues

2020-09-08 21:33 UTC, tinachoB commented on src/shared_modules/rsync/testtool/agentEmulator.cpp
> +			"Error creating rsync handle."
Error registering ID

2020-09-08 21:33 UTC, tinachoB commented on src/shared_modules/rsync/testtool/cmdArgsHelper.h
> + * July 02, 2020.
Wrong date

2020-09-08 21:33 UTC, tinachoB commented on src/shared_modules/rsync/testtool/main.cpp
> +        std::cout << ex.what() << std::endl;
Please, add `CmdLineArgs::showHelp();` call here.

2020-09-08 22:50 UTC, tinachoB approved these changes
:+1:

2020-09-09 02:11 UTC, Dwordcito requested changes

2020-09-09 12:44 UTC, tinachoB commented on src/shared_modules/rsync/testtool/agentEmulator.cpp
> +struct smartDeleterJson
And please, use Upper case for struct/class names. smartDeleterJson -> SmartDeleterJson

2020-09-09 17:52 UTC, Dwordcito approved these changes

2020-09-09 17:53 UTC, merged