[5777] RSYNC push message implementation
wazuh/wazuh pull request #5998
Opened 2020-09-11 13:01 UTC by konangc87

# Rsync ush message implementation.

## **Related Issue**
[5777](https://github.com/wazuh/wazuh/issues/5777)

## Description
This issue aims that after receiving a message from the manager, this message is redirected to remote sync, to process it according to the characteristics established by the callback or synchronization register #5773 .

This will dispatch the processing of these actions in dispatch threads according to the configuration.

## DoD / Tasks
- [X] Implementation
- [X] RTR
![image](https://user-images.githubusercontent.com/54002291/92928303-435ed380-f415-11ea-9a2b-8f9b30a2bcd4.png)

2020-09-11 19:11 UTC, tinachoB requested changes

2020-09-11 19:11 UTC, tinachoB commented on src/shared_modules/rsync/src/rsync.cpp
> +    // LCOV_EXCL_STOP
Please, move this excl_stop to the line 107

2020-09-11 19:34 UTC, tinachoB approved these changes

2020-09-12 00:34 UTC, Dwordcito approved these changes

2020-09-12 00:52 UTC, merged