Add restrict option to Windows registries
wazuh/wazuh pull request #6057
Opened 2020-09-18 14:47 UTC by jotacarma90

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/4150|

## Description
PR with the necessary changes to add the restrict option to the Windows registers.

2020-09-22 09:47 UTC, Molter73 requested changes

2020-09-22 09:47 UTC, Molter73 commented on src/syscheckd/registry/registry.c
> -#include "../db/fim_db_registries.h"
Excluding this header file causes many `implicit definition` warnings during compilation, please readd it.

2020-09-22 09:47 UTC, Molter73 commented on src/config/syscheck-config.c
> +                        str_lowercase(restrictfile);
We are not treating registry entries as case insensitive, please remove this `str_lowercase`.

2020-09-23 12:02 UTC, Molter73 approved these changes
LGTM!

2020-09-30 14:35 UTC, bah07 approved these changes

2020-09-30 14:36 UTC, merged