[5779] extend rsync testtool to process parameters through json format files
wazuh/wazuh pull request #6074
Opened 2020-09-22 17:27 UTC by konangc87

|Related issue|
|---|
|[5779](https://github.com/wazuh/wazuh/issues/5779)|

## Description
This issue aims to extend the functionality of rsync testtool to accept parameters through json format files to exercise both dbsync and rsync libraries.

## DoD:
- [X] Implementation

2020-09-22 17:43 UTC, tinachoB requested changes

2020-09-22 17:43 UTC, tinachoB commented on src/shared_modules/rsync/testtool/oneTimeSync.cpp
> +        // const auto dbsyncInput{ m_inputData[0].at("dbsync") };
Remove this please.

2020-09-22 17:43 UTC, tinachoB commented on src/shared_modules/rsync/testtool/config.json
> +{
I think we should move this config.json and input.json files into a new "input" folder to separate implementation and input data files

2020-09-22 17:43 UTC, tinachoB commented on src/shared_modules/rsync/testtool/oneTimeSync.h
> +#include <atomic>
Do we truly need these includes here?

2020-09-22 18:00 UTC, tinachoB approved these changes
Looks great!

2020-09-24 08:08 UTC, Dwordcito commented on src/shared_modules/rsync/testtool/oneTimeSync.h
> +class OneTimeSync
this could be "final" ?

2020-09-24 08:08 UTC, Dwordcito commented on src/shared_modules/rsync/testtool/oneTimeSync.cpp
> +    OneTimeSync* object{ reinterpret_cast<OneTimeSync*>(userData) };
this could be const ?

2020-09-24 08:08 UTC, Dwordcito commented on src/shared_modules/rsync/testtool/oneTimeSync.cpp
> +    const auto it{ m_inputData[0].find("dbsync") };
use at()

2020-09-24 08:08 UTC, Dwordcito commented on src/shared_modules/rsync/testtool/oneTimeSync.cpp
> +    if (it != m_inputData[0].end())
use at()

2020-09-24 08:08 UTC, Dwordcito commented on src/shared_modules/rsync/testtool/oneTimeSync.cpp
> +    const auto it{ m_inputData[0].find("rsync_push") };
use at()

2020-09-24 08:08 UTC, Dwordcito commented on src/shared_modules/rsync/testtool/oneTimeSync.cpp
> +    if (it != m_inputData[0].end())
use at()

2020-09-24 08:08 UTC, Dwordcito commented on src/shared_modules/rsync/testtool/oneTimeSync.cpp
> +    const auto it{ m_inputData[0].find("rsync_start_sync") };
use at()

2020-09-24 08:08 UTC, Dwordcito commented on src/shared_modules/rsync/testtool/cmdArgsHelper.h
> +    {
this class could be final ?

2020-09-24 08:08 UTC, Dwordcito commented on src/shared_modules/rsync/testtool/oneTimeSync.cpp
> +
remove \n

2020-09-24 13:33 UTC, tinachoB approved these changes

2020-09-24 14:51 UTC, Dwordcito approved these changes

2020-09-24 14:52 UTC, merged