Enrollment: Checking remote events service availability
wazuh/wazuh pull request #6150
Opened 2020-09-30 10:01 UTC by snaow

|Related issue|
|---|
|Closes https://github.com/wazuh/wazuh/issues/6146|

## Description

- Modified the remote events service to be able to receive and respond to a "ping" custom request.
- Modified the agent communication service to be able to send a ping request and wait for the response.
- Modified connection error log to include both port and protocol.

The enrollment process won't continue now if the remote events service is not up and healthy (respond to ping request), the only exceptions has been cover in the related issue description.

## Logs/Alerts example

No extra logs has been added with the ping/pong operation.
Modified the `1216` error log as following:

```
2020/09/30 09:08:42 ossec-agentd: ERROR: (1216): Unable to connect to '172.28.128.4:1514/udp': 'Connection refused'.
```

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [X] Source installation
- [X] Package installation
- [X] Source upgrade
- [X] Package upgrade
- [X] Review logs syntax and correct language
- [N/A ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retro compatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

2020-09-30 10:23 UTC, vikman90 requested changes
We need to add a test for `connect_server(*, true)` to check that no logs are being printed.

In addition, we need a unit test for `agent_ping_to_server()`.

2020-09-30 10:23 UTC, vikman90 commented on src/client-agent/start_agent.c
> +                    if(agent_ping_to_server(rc)){
Missing space after `if`.

2020-09-30 10:23 UTC, vikman90 commented on src/client-agent/sendmsg.c
> +}
Missing final newline.

2020-09-30 10:23 UTC, vikman90 commented on src/remoted/secure.c
> +    } else if(strncmp(buffer, "ping", 4) == 0) {
Missing space after `if`.

2020-09-30 10:23 UTC, vikman90 commented on src/remoted/secure.c
> +                error = errno;
Is `error` used?

2020-10-02 10:35 UTC, snaow commented on src/client-agent/sendmsg.c
> +}
Fixed

2020-10-02 10:37 UTC, snaow commented on src/remoted/secure.c
> +                error = errno;
It was not used, sorry. Fixed.

2020-10-06 10:34 UTC, vikman90 requested changes

2020-10-06 10:34 UTC, vikman90 commented on src/client-agent/sendmsg.c
> + * @retval true on message sent
`send_message` may return:
- `0` (`false`) on success.
- `OS_SOCKTERR` (`-6`) on failure (UDP) or on message size error (TCP).
- `-1` on general error (TCP).

2020-10-06 10:34 UTC, vikman90 commented on src/client-agent/start_agent.c
> + * @param is_ping The connection is just for pinging the remote service. Lower verbose.
Could we refactor `is_ping` to `verbose`?

2020-10-07 18:29 UTC, vikman90 commented
## Coverity scan

### CID 214883:  Integer handling issues  (NEGATIVE_RETURNS)

```
/remoted/secure.c: 248 in rem_handler_main()
242         mdebug1("Message handler thread started.");
243     
244         while (1) {
245             message = rem_msgpop();
246             if (message->sock == -1 || message->counter > rem_getCounter(message->sock)) {
247                 memcpy(buffer, message->buffer, message->size);
   CID 214883:  Integer handling issues  (NEGATIVE_RETURNS)
   "message->sock" is passed to a parameter that cannot be negative.
248                 HandleSecureMessage(buffer, message->size, &message->addr, message->sock);
249             } else {
250                 rem_inc_dequeued();
251             }
252             rem_msgfree(message);
253         }
```

This issue is not related to this development. `sock` is negative if and only if the protocol is UDP.

2020-10-07 18:29 UTC, vikman90 approved these changes

2020-10-08 15:39 UTC, merged