[6193] Module packet receiver and pusher
wazuh/wazuh pull request #6214
Opened 2020-10-06 13:18 UTC by konangc87

|Related issue|
|---|
|[6193](https://github.com/wazuh/wazuh/issues/6193)|

## Description
This issue aims to add the functionality of wmodules to receive sync messages from the manager.

## DoD:
- [X] Implementation

2020-10-06 13:40 UTC, tinachoB requested changes

2020-10-06 13:40 UTC, tinachoB commented on src/wazuh_modules/wmcom.c
> +    } else if (strcmp(rcv_comm, "sync") == 0){
Please, add an extra space between `)` and `{`

2020-10-06 13:40 UTC, tinachoB commented on src/wazuh_modules/wmcom.c
> +        if (!rcv_args){
Ditto

2020-10-07 06:46 UTC, Dwordcito approved these changes

2020-10-07 12:43 UTC, merged