6190 syscollector testtool
wazuh/wazuh pull request #6236
Opened 2020-10-07 19:44 UTC by konangc87

|Related issue|
|---|
|[6190](https://github.com/wazuh/wazuh/issues/6190)|

## Description
This issue aims to implement the syscollector test tool skeleton. Additionally a new cmake file was added to syscollector folder to handle the compilation of future .cpp files and the test tool as well.
## DoD:
- [X] Implementation
- [X] Successful agent compilation 
- [X] Successful win agent compilation

![image](https://user-images.githubusercontent.com/54002291/95379783-38844b00-08bc-11eb-98a1-b320853e4c00.png)
![image](https://user-images.githubusercontent.com/54002291/95379875-55b91980-08bc-11eb-8537-83680504eccc.png)

2020-10-07 19:48 UTC, tinachoB requested changes

2020-10-07 19:48 UTC, tinachoB commented on src/wazuh_modules/syscollector/CMakeLists.txt
> +project(dbsync)
Wrong name. This should be syscollector

2020-10-07 19:51 UTC, tinachoB approved these changes
Great work!

2020-10-07 20:53 UTC, Dwordcito approved these changes

2020-10-08 12:38 UTC, tinachoB approved these changes

2020-10-08 12:39 UTC, merged