Improve rids counter
wazuh/wazuh pull request #6278
Opened 2020-10-13 12:47 UTC by Nicogp

|Related issue|
|---|
|#6112|

## Description
This PR add the functionality to close a rids fp after a seted time. By default this time is 300 seconds and it´s configurable in the remote section of ossec.conf with tag "rids_closing_time".

## Configuration options
```
<remote>
   <rids_closing_time>10m</rids_closing_time>
</remote>
```

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)

2020-10-16 21:04 UTC, TomasTurina requested changes

2020-10-16 21:04 UTC, TomasTurina commented on src/remoted/secure.c
> +                    first_node_key->fp = NULL;
Move this line inside the if above.

2020-10-20 14:32 UTC, TomasTurina requested changes

2020-10-20 14:32 UTC, TomasTurina commented on src/os_crypto/shared/msgs.c
> +            w_mutex_unlock(&keys->keyentries[id]->mutex);
Close the mutex after increasing `rcv_count` to also protect that variable.

2020-10-20 14:32 UTC, TomasTurina commented on src/os_crypto/shared/msgs.c
> +            w_mutex_unlock(&keys->keyentries[id]->mutex);
Close the mutex after increasing `rcv_count` to also protect that variable.

2020-10-20 14:32 UTC, TomasTurina commented on src/os_crypto/shared/msgs.c
> +        w_mutex_unlock(&keys->keyentries[id]->mutex);
This is not necessary, you are already unlocking the mutex at the end of the function.

2020-10-21 19:47 UTC, nicolaspapp requested changes

2020-10-21 19:47 UTC, nicolaspapp commented on src/remoted/secure.c
> +        key_lock_write();
This looks expensive and rather unnecessary. In my understaing:
- key_lock_read(): Some thread that is reading the keystore
- keyentries[i]->mutex: Mutual exclusion of that key entry. Can modifcate keyentry information in the process
- key_lock_write(): Block all reads to the keystore. Possible needed when keystore is reloaded or new keys are added

In my opinion only read lock is needed here. Also need to take the keyentry mutex before evaulating the file pointer

2020-10-21 19:47 UTC, nicolaspapp commented on src/remoted/secure.c
> +                    first_node_key = (keyentry *)linked_queue_pop_ex(keys->opened_fp_queue);
mutex lock here

2020-10-21 19:47 UTC, nicolaspapp commented on src/remoted/secure.c
> +                    first_node_key->rids_node = NULL;
mutex_unlock

2020-10-23 14:49 UTC, TomasTurina approved these changes

2020-10-23 15:58 UTC, nicolaspapp approved these changes

2020-10-23 15:58 UTC, nicolaspapp commented on src/unit_tests/os_crypto/CMakeLists.txt
> +endif()
Add EOF

2020-10-23 15:58 UTC, nicolaspapp commented on src/unit_tests/os_crypto/shared/CMakeLists.txt
> +endforeach()
Add EOF

2020-10-23 15:58 UTC, nicolaspapp commented on src/unit_tests/os_crypto/shared/test_msgs.c
> +}
Add EOF

2020-10-23 15:58 UTC, nicolaspapp commented on src/unit_tests/remoted/test_secure.c
> +}
Add EOF

2020-10-23 18:21 UTC, TomasTurina approved these changes

2020-10-23 19:16 UTC, merged