6123 hw info
wazuh/wazuh pull request #6334
Opened 2020-10-20 02:32 UTC by konangc87

# Hardware Info on sysinfo

## **Related Issue**
[6123](https://github.com/wazuh/wazuh/issues/6123)

## Description
This issue aims to refactor the hw info provider for each os using C++ reducing the scope and responsibilities of the modules..
These changes have to be made in the various implementations according to the operating system targeted for this feature.

## DoD / Tasks
- [X] Implementation
- [X] Run testtool on linux/win/freebsd/macos/openbsd
- [X] RTR

2020-10-20 13:53 UTC, tinachoB requested changes

2020-10-20 13:53 UTC, tinachoB commented on src/shared_modules/utils/registryHelper.h
> +    class Registry
final

2020-10-20 13:53 UTC, tinachoB commented on src/shared_modules/utils/registryHelper.h
> +        std::string string(const std::string& valueName)
Could this method be const?

2020-10-20 13:53 UTC, tinachoB commented on src/wazuh_modules/syscollector/sysInfoWin.cpp
> +    Utils::Registry reg(HKEY_LOCAL_MACHINE, "HARDWARE\\DESCRIPTION\\System\\CentralProcessor\\0");
Maybe you can create a constexpr auto with this value and use it here (and in the line 142) and in the UTs.

2020-10-20 13:53 UTC, tinachoB commented on src/wazuh_modules/syscollector/sysInfo.hpp
> +    virtual std::string getCpuName();
maybe these methods could be const

2020-10-20 13:53 UTC, tinachoB commented on src/wazuh_modules/syscollector/sysInfoWin.cpp
> +        info["ram_total"] = statex.ullTotalPhys/1024;
Please, create a "constexpr auto KByte{1024};" as you did in sysInfoOpenBSD.cpp, line 18 and use it in both sides

2020-10-20 13:53 UTC, tinachoB commented on src/wazuh_modules/syscollector/syscollectorImp.h
> +    SysInfo                         m_info;
Please, fix indentation

2020-10-20 13:53 UTC, tinachoB commented on src/wazuh_modules/syscollector/syscollectorImp.h
> +class Syscollector
final

2020-10-20 17:58 UTC, tinachoB approved these changes
Looks great!

2020-10-21 16:26 UTC, Dwordcito requested changes

2020-10-21 16:26 UTC, Dwordcito commented on src/wazuh_modules/syscollector/sysInfoWin.cpp
> +            std::unique_ptr<unsigned char> buff{new unsigned char[size]};
std::make_unique(size)

2020-10-21 17:55 UTC, tinachoB approved these changes

2020-10-21 18:24 UTC, Dwordcito approved these changes

2020-10-21 18:32 UTC, merged