[Task] Add new endpoint to check status of tasks
wazuh/wazuh pull request #6402
Opened 2020-10-23 08:43 UTC by AdriiiPRodri

|Related issue|
|---|
|#6029|

Hi team,

This PR closes #6029. In this PR we have added a new endpoint to check the status of one or more tasks according to its task_id.

### Integration test
```
adriiiprodri@wazuh pytest -vv -x test_tasks_endpoints.tavern.yaml
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api/test/integration, configfile: pytest.ini
plugins: tavern-1.7.0
collected 2 items                                                                                                                                                         

test_tasks_endpoints.tavern.yaml::PUT /agents/upgrade PASSED                                                                                                        [ 50%]
test_tasks_endpoints.tavern.yaml::GET /tasks/status PASSED                                                                                                          [100%]

================================================================ 2 passed, 3 warnings in 387.07s (0:06:27) ================================================================
```

### Unittest
```
adriiiprodri@wazuh python3 -m pytest -x framework/wazuh/tests/test_tasks.py
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/framework
plugins: tavern-1.7.0
collected 2 items                                                                                                                                                         

framework/wazuh/tests/test_tasks.py ..                                                                                                                              [100%]

============================================================================ 2 passed in 0.08s ============================================================================
```

2020-11-10 10:31 UTC, davidjiglesias requested changes
Add documentation PR.
Rebase branch.

2020-11-10 11:42 UTC, davidjiglesias requested changes

2020-11-10 11:42 UTC, davidjiglesias commented on api/api/spec/spec.yaml
> +      summary: "Get the status of a specified list of tasks"
```suggestion
      summary: "List tasks"
```

2020-11-10 11:42 UTC, davidjiglesias commented on api/api/spec/spec.yaml
> +      description: "Returns all available information about the specified list of tasks"
```suggestion
      description: "Returns all available information about the specified tasks"
```

2020-11-10 11:42 UTC, davidjiglesias commented on api/api/spec/spec.yaml
> +              example:
Is this example a response from this endpoint?

2020-11-10 11:42 UTC, davidjiglesias commented on api/test/integration/test_tasks_endpoints.tavern.yaml
> +  - name: Missing task IDs
Why are we not giving back all tasks if nothing is specified? Does the task socket accept such petition?

2020-11-10 11:42 UTC, davidjiglesias commented on framework/wazuh/core/tasks.py
> +# Copyright (C) 2015-2019, Wazuh Inc.
```suggestion
# Copyright (C) 2015-2020, Wazuh Inc.
```

2020-11-10 11:42 UTC, davidjiglesias commented on framework/wazuh/core/tasks.py
> +    """Send command to upgrade module / task module
```suggestion
    """Send command to task module
```

2020-11-10 11:42 UTC, davidjiglesias commented on framework/wazuh/core/tasks.py
> +    Message received from the socket (Task module or Upgrade module)
```suggestion
    Message received from the socket
```

2020-11-10 11:42 UTC, davidjiglesias commented on framework/wazuh/core/tasks.py
> +    # Send upgrading command
????

2020-11-11 14:38 UTC, AdriiiPRodri commented
## Unittests
```
adriiiprodri@wazuh pytest wazuh/tests/test_tasks.py
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/framework
plugins: metadata-1.10.0, html-2.1.1, tavern-1.7.0
collected 2 items                                                                                                                                                         

wazuh/tests/test_tasks.py ..                                                                                                                                        [100%]

============================================================================ 2 passed in 0.10s ============================================================================
```

## Integrated tests
```
adriiiprodri@wazuh pytest -x test_tasks_endpoints.tavern.yaml 
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api/test/integration, configfile: pytest.ini
plugins: metadata-1.10.0, html-2.1.1, tavern-1.7.0
collected 2 items                                                                                                                                                         

test_tasks_endpoints.tavern.yaml ..                                                                                                                                 [100%]

================================================================ 2 passed, 3 warnings in 91.78s (0:01:31) =================================================================

```

2020-11-30 13:28 UTC, closed without merging