6352 packages bsd
wazuh/wazuh pull request #6421
Opened 2020-10-26 13:37 UTC by konangc87

|Related issue|
|---|
|#6352|

## **Description**

This issue aims to make use of the generic synchronization libraries, to use the synchronization solution algorithm that both shared modules provide.

These changes have to be made in the various implementations according to the operating system targeted for this feature.

## **DoD**
- [X] Implementation
- [X] **Run testtool on MAC**
![image](https://user-images.githubusercontent.com/54002291/97173617-9bf0f280-176f-11eb-85a9-6ea43cab9cc3.png)
- [X] **Run testtool on FreeBSD**
![image](https://user-images.githubusercontent.com/54002291/97173650-add29580-176f-11eb-840a-d9e183c0f334.png)
- [X] **RTR
![image](https://user-images.githubusercontent.com/54002291/97173791-e5d9d880-176f-11eb-82ce-4ed865d5cbd3.png)
- **SysInfo UTs:**
> **Linux:**
![image](https://user-images.githubusercontent.com/54002291/97174884-74028e80-1771-11eb-9d9b-a3f6c22618a2.png)
> **Windows:**
![image](https://user-images.githubusercontent.com/54002291/97178850-d4e09580-1776-11eb-8e98-d98bdca1de5b.png)

2020-10-26 20:09 UTC, tinachoB requested changes
Nice work

2020-10-26 20:09 UTC, tinachoB commented on src/shared_modules/utils/tests/filesystemHelper_test.cpp
> +	const auto items {Utils::enumerateDir(R"(C:\)")};
wrong indentation

2020-10-26 20:09 UTC, tinachoB commented on src/shared_modules/utils/tests/filesystemHelper_test.cpp
> +	const auto items {Utils::enumerateDir(R"(/usr)")};
ditto

2020-10-27 05:54 UTC, Dwordcito approved these changes
looks good

2020-10-27 12:01 UTC, tinachoB approved these changes

2020-10-27 13:42 UTC, tinachoB approved these changes

2020-10-27 13:45 UTC, merged