Fix vulnerability in Python's cryptography library
wazuh/wazuh pull request #6443
Opened 2020-10-28 10:50 UTC by AdriiiPRodri

|Related issue|
|---|
|#6442|

Hi team,

This PR closes #6442. In this PR we have updated the cryptography library version because a vulnerability has been found in the version we were using.

```
adriiiprodri@wazuh python3 run_tests.py -rbac both -k agents    
Collected tests [6]:
test_agents_DELETE_endpoints.tavern.yaml, test_agents_GET_endpoints.tavern.yaml, test_agents_POST_endpoints.tavern.yaml, test_agents_PUT_endpoints.tavern.yaml, test_rbac_black_agents_endpoints.tavern.yaml, test_rbac_white_agents_endpoints.tavern.yaml

test_agents_DELETE_endpoints.tavern.yaml 
	 7 passed, 8 warnings

test_agents_GET_endpoints.tavern.yaml 
	 90 passed, 91 warnings

test_agents_POST_endpoints.tavern.yaml 
	 5 passed, 6 warnings

test_agents_PUT_endpoints.tavern.yaml 
	 9 passed, 10 warnings

test_rbac_black_agents_endpoints.tavern.yaml 
	 39 passed, 40 warnings

test_rbac_white_agents_endpoints.tavern.yaml 
	 39 passed, 40 warnings
```

Regards

2020-10-29 07:39 UTC, davidjiglesias requested changes
Please run cluster unit tests and integration tests

2020-10-29 07:39 UTC, davidjiglesias commented on CHANGELOG.md
> +### Changed
```suggestion
### Changed

- **Framework:**
  - Update Python's cryptography library to version 3.2.1 ([#6442](https://github.com/wazuh/wazuh/issues/6442))
```

2020-10-29 07:39 UTC, davidjiglesias commented on CHANGELOG.md
> +- **Framework:**
```suggestion
```

2020-10-29 07:39 UTC, davidjiglesias commented on CHANGELOG.md
> +  - Fix Python's cryptography library ([#6442](https://github.com/wazuh/wazuh/issues/6442))
```suggestion
```

2020-10-29 10:31 UTC, AdriiiPRodri commented
> Please run cluster unit tests and integration tests

## Cluster integration tests
```adriiiprodri@wazuh python3 run_tests.py -rbac both -k cluster                  
Collected tests [3]:
test_cluster_endpoints.tavern.yaml, test_rbac_black_cluster_endpoints.tavern.yaml, test_rbac_white_cluster_endpoints.tavern.yaml


test_cluster_endpoints.tavern.yaml 
	 56 passed, 57 warnings

test_rbac_black_cluster_endpoints.tavern.yaml 
	 21 passed, 22 warnings

test_rbac_white_cluster_endpoints.tavern.yaml 
	 21 passed, 22 warnings```

2020-10-29 10:37 UTC, davidjiglesias approved these changes

2020-10-30 12:18 UTC, davidjiglesias approved these changes

2020-10-30 12:18 UTC, merged