Remove the limit of agents that a manager can support
wazuh/wazuh pull request #6450
Opened 2020-10-28 20:47 UTC by TomasTurina

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/6097|

## Description

This PR makes Wazuh independent of the number configured for the `MAX_AGENTS` limit.

This limit has been deprecated in the following components:

- **Remoted**: We have improved the RIDS logic so that now the number of open file handlers does not depend on the agent limit and depends on the number of agents connected at any given time. In addition, we have replaced the pending message queue, which was initialized with the size of the agent limit, with a linked queue that increases with the number of connected agents.

- **Rootcheck**: We have improved the mechanism that rootcheck uses to store information from agent scans. Now, each log is stored directly in the `pm_event` table of the corresponding agent through Wazuh DB. The files located at `/queue/rootcheck`, which were being tracked with arrays initialized with the agent size limit, are now not needed so they have been removed.

- **Upgrade module**: The upgrade queue had an initial size of the agent limit. Now, this queue has been replaced with a linked queue that increases with the number of agents queued to upgrade.

## Configuration options

```xml
<remote>
   <rids_closing_time>10m</rids_closing_time>
</remote>
```

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Added unit tests (for new features)

2020-11-10 19:18 UTC, vikman90 requested changes

2020-11-10 22:28 UTC, TomasTurina commented on etc/internal_options.conf
> +wazuh_database.sync_rootcheck=0
Removed in https://github.com/wazuh/wazuh/pull/6450/commits/44dd26da96548416e2f0e1ef0e2c57f8d1ac26f7

2020-11-10 22:28 UTC, TomasTurina commented on src/wazuh_modules/wm_database.c
> +    data.sync_rootcheck = 0; //getDefine_Int("wazuh_database", "sync_rootcheck", 0, 1);
Removed in https://github.com/wazuh/wazuh/pull/6450/commits/44dd26da96548416e2f0e1ef0e2c57f8d1ac26f7

2020-11-11 12:25 UTC, vikman90 requested changes

2020-11-11 12:25 UTC, vikman90 commented on src/config/remote-config.c
> +    const int default_rids_closing_time = 300;
This is a constant definition, it should be in capitals.

2020-11-11 12:25 UTC, vikman90 commented on src/config/authd-config.c
> +            mwarn("The <%s> tag is deprecated since version 4.1.0.", xml_limit_maxagents);
This line causes a warning log after upgrading.

2020-11-11 16:31 UTC, vikman90 approved these changes

2020-11-11 16:44 UTC, merged