Fix test_run_check unit test for Linux and Windows
wazuh/wazuh pull request #6481
Opened 2020-11-03 15:27 UTC by antoniomanuelfr

|Related issue|
|---|
|#6338|

## Description

After the development of #5576, the unit tests need to be adapted. This PR aims to adapt the tests in the file `test_run_check.c`
Closes #6338 
## Linux tests
```
[==========] Running 21 test(s).
[ RUN      ] test_fim_whodata_initialize
[       OK ] test_fim_whodata_initialize
[ RUN      ] test_log_realtime_status
[       OK ] test_log_realtime_status
[ RUN      ] test_fim_send_msg
[       OK ] test_fim_send_msg
[ RUN      ] test_fim_send_msg_retry
[       OK ] test_fim_send_msg_retry
[ RUN      ] test_fim_send_msg_retry_error
[       OK ] test_fim_send_msg_retry_error
[ RUN      ] test_fim_send_sync_msg_10_eps
[       OK ] test_fim_send_sync_msg_10_eps
[ RUN      ] test_fim_send_sync_msg_0_eps
[       OK ] test_fim_send_sync_msg_0_eps
[ RUN      ] test_send_syscheck_msg_10_eps
[       OK ] test_send_syscheck_msg_10_eps
[ RUN      ] test_send_syscheck_msg_0_eps
[       OK ] test_send_syscheck_msg_0_eps
[ RUN      ] test_fim_send_scan_info
[       OK ] test_fim_send_scan_info
[ RUN      ] test_fim_link_update
[       OK ] test_fim_link_update
[ RUN      ] test_fim_link_update_already_added
[       OK ] test_fim_link_update_already_added
[ RUN      ] test_fim_link_check_delete
[       OK ] test_fim_link_check_delete
[ RUN      ] test_fim_link_check_delete_lstat_error
[       OK ] test_fim_link_check_delete_lstat_error
[ RUN      ] test_fim_link_check_delete_noentry_error
[       OK ] test_fim_link_check_delete_noentry_error
[ RUN      ] test_fim_delete_realtime_watches
[       OK ] test_fim_delete_realtime_watches
[ RUN      ] test_fim_link_delete_range
[       OK ] test_fim_link_delete_range
[ RUN      ] test_fim_link_delete_range_error
[       OK ] test_fim_link_delete_range_error
[ RUN      ] test_fim_link_silent_scan
[       OK ] test_fim_link_silent_scan
[ RUN      ] test_fim_link_reload_broken_link_already_monitored
[       OK ] test_fim_link_reload_broken_link_already_monitored
[ RUN      ] test_fim_link_reload_broken_link_reload_broken
[       OK ] test_fim_link_reload_broken_link_reload_broken
[==========] 21 test(s) run.
[  PASSED  ] 21 test(s).
```
## Windows tests
```
wine test_run_check.exe 
[==========] tests: Running 17 test(s).
[ RUN      ] test_fim_whodata_initialize
[       OK ] test_fim_whodata_initialize
[ RUN      ] test_set_priority_windows_thread_highest
[       OK ] test_set_priority_windows_thread_highest
[ RUN      ] test_set_priority_windows_thread_above_normal
[       OK ] test_set_priority_windows_thread_above_normal
[ RUN      ] test_set_priority_windows_thread_normal
[       OK ] test_set_priority_windows_thread_normal
[ RUN      ] test_set_priority_windows_thread_below_normal
[       OK ] test_set_priority_windows_thread_below_normal
[ RUN      ] test_set_priority_windows_thread_lowest
[       OK ] test_set_priority_windows_thread_lowest
[ RUN      ] test_set_priority_windows_thread_idle
[       OK ] test_set_priority_windows_thread_idle
[ RUN      ] test_set_priority_windows_thread_error
[       OK ] test_set_priority_windows_thread_error
[ RUN      ] test_log_realtime_status
[       OK ] test_log_realtime_status
[ RUN      ] test_fim_send_msg
[       OK ] test_fim_send_msg
[ RUN      ] test_fim_send_msg_retry
[       OK ] test_fim_send_msg_retry
[ RUN      ] test_fim_send_msg_retry_error
[       OK ] test_fim_send_msg_retry_error
[ RUN      ] test_fim_send_sync_msg_10_eps
[       OK ] test_fim_send_sync_msg_10_eps
[ RUN      ] test_fim_send_sync_msg_0_eps
[       OK ] test_fim_send_sync_msg_0_eps
[ RUN      ] test_send_syscheck_msg_10_eps
[       OK ] test_send_syscheck_msg_10_eps
[ RUN      ] test_send_syscheck_msg_0_eps
[       OK ] test_send_syscheck_msg_0_eps
[ RUN      ] test_fim_send_scan_info
[       OK ] test_fim_send_scan_info
[==========] tests: 17 test(s) run.
[  PASSED  ] 17 test(s).

```
```
wine test_run_check_event.exe 
[==========] eventchannel_tests: Running 3 test(s).
[ RUN      ] test_set_whodata_mode_changes
[       OK ] test_set_whodata_mode_changes
[ RUN      ] test_fim_whodata_initialize_eventchannel
[       OK ] test_fim_whodata_initialize_eventchannel
[ RUN      ] test_fim_whodata_initialize_fail_set_policies
[       OK ] test_fim_whodata_initialize_fail_set_policies
[==========] eventchannel_tests: 3 test(s) run.
[  PASSED  ] 3 test(s).

```

2020-11-09 11:31 UTC, jesusjimsa commented on src/unit_tests/syscheckd/test_run_check.c
> +static void expect_w_send_sync_msg(const char *msg, const char *locmsg, int ret, int location) {
Move this function to the `mq_op_wrappers` file.

2020-11-09 11:54 UTC, jesusjimsa requested changes

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/syscheckd/test_run_check.c
> +static void expect_w_send_sync_msg(const char *msg, const char *locmsg, int ret, int location) {
Move this function to the `mq_op_wrappers` file.

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/syscheckd/test_run_check.c
> +    char location[10] = "fim_file\0";
Is the `\0` character necessary? If not, please delete it.

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/syscheckd/test_run_check.c
> +    char location[10] = "fim_file\0";
The same as above, is the null character necessary?

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/wrappers/wazuh/shared/mq_op_wrappers.c
> + * @brief This function load the expect and will_return calls for the function StartMQ
This function **loads**. Also, this doxygen comment should be in the _.h_ file instead.

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/wrappers/wazuh/syscheckd/create_db_wrappers.c
> + * @brief This function load the expect and will_return calls for the wrapper of fim_checker
This function **loads**. Also, this doxygen comment should be in the _.h_ file instead.

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/wrappers/wazuh/syscheckd/create_db_wrappers.c
> + * @brief This function load the expect and will_return calls for the wrapper of fim_configuration_directory
This function **loads**. Also, this doxygen comment should be in the _.h_ file instead.

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/wrappers/wazuh/syscheckd/fim_db_wrappers.c
> + * @brief This function load the expect and will_return calls for the wrapper of fim_db_get_path_range
This function **loads**. Also, this doxygen comment should be in the _.h_ file instead.

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/wrappers/wazuh/syscheckd/fim_db_wrappers.c
> + * @brief This function load the expect and will_return calls for the wrapper of fim_db_delete_range
This function **loads**. Also, this doxygen comment should be in the _.h_ file instead.

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/wrappers/wazuh/syscheckd/fim_db_wrappers.c
> +                                           int ret) {
These lines are over-indented.
```C
void expect_fim_db_get_path_range_call(const fdb_t *db,
                                       const char *start_str,
                                       const char *top_str,
                                       int storage,
                                       fim_tmp_file *tmp_file,
                                       int ret) {
```

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/wrappers/wazuh/syscheckd/fim_db_wrappers.h
> + * @brief This function load the expect and will_return calls for the wrapper of fim_db_get_path_range
This function **loads**.

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/wrappers/wazuh/syscheckd/fim_db_wrappers.h
> +                                    int ret);
These lines are under-indented.
```C
void expect_fim_db_get_path_range_call(const fdb_t *db,
                                       const char *start_str,
                                       const char *top_str,
                                       int storage,
                                       fim_tmp_file *tmp_file,
                                       int ret);
```

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/wrappers/wazuh/syscheckd/fim_db_wrappers.h
> +void expect_fim_db_delete_range_call(const fdb_t *db, int storage, const fim_tmp_file *file, int ret);
This function doesn't have doxygen information as the other ones you added.

2020-11-09 11:54 UTC, jesusjimsa commented on src/unit_tests/wrappers/windows/processthreadsapi_wrappers.c
> + * @brief This function load the expect and will_return calls for the wrapper of SetThreadPriority
This function **loads**. Also, this doxygen comment should be in the _.h_ file instead.

2020-11-10 08:46 UTC, jesusjimsa approved these changes
LGTM!

2020-11-13 17:53 UTC, Molter73 approved these changes
LGTM!

2020-11-13 17:54 UTC, merged