Fix warnings and variables usage in Wazuh DB unitests
wazuh/wazuh pull request #6486
Opened 2020-11-03 21:00 UTC by palaciosjeremias

|Related issue|
|---|
|6485|

## Description
This PR:
- Adds `-Wall` compilation flag in WazuhDB makefile to have visibility of the Warnings of this module.
- Fix all the warnings reported on WazuhDB UT
- Fix the agent ID variable used during the tests of wdb_global

- Compilation without warnings in every supported platform
  - [X] Linux

- UT
  - [X] UT build without warnings
  - [X] UT execution successfully

- Memory tests for Linux
  - [X] Valgrind (memcheck and descriptor leaks check)

2020-11-03 21:23 UTC, DProvinciani requested changes
There are some other test cases like `test_wdb_global_insert_agent_transaction_fail` that instead of passing directly `1` as agent ID, they make use of a variable `agent_id`.
I think that the way that you implemented is better, so, probably we could modify all the other test cases in the same file that make use of the variable to directly pass `1` to the Wazuh DB helper. So in this way, we will unify the criteria.

2020-11-04 03:35 UTC, palaciosjeremias commented
> There are some other test cases like `test_wdb_global_insert_agent_transaction_fail` that instead of passing directly `1` as agent ID, they make use of a variable `agent_id`.
> I think that the way that you implemented is better, so, probably we could modify all the other test cases in the same file that make use of the variable to directly pass `1` to the Wazuh DB helper. So in this way, we will unify the criteria.

Done. Now the agent id is passed directly in all test cases where the id is not central for the test case and is not used massively.

2020-11-04 15:47 UTC, DProvinciani approved these changes
Looks good!

2020-11-04 15:53 UTC, pereyra-m commented on src/unit_tests/wazuh_db/CMakeLists.txt
> +add_compile_options(-Wall)
Good idea!

2020-11-04 15:56 UTC, pereyra-m approved these changes
LGTM!

2020-11-04 18:54 UTC, merged