Add tests for registry functions in syscheck_op
wazuh/wazuh pull request #6504
Opened 2020-11-05 07:40 UTC by jesusjimsa

| Related issue |
| ------------- |
| #6342         |

## Description

This pull request adds unit tests for the new registry functions in the _syscheck_op_ file. These functions are:
* `get_file_user`
* `remove_empty_folders`
* `get_registry_group`
* `get_registry_permissions`
* `get_registry_mtime`

It also creates some expect_* functions to encapsulate the `expect_value`, `expect_string`, `will_return`... _cmocka_ calls.

This pull request closes #6342.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows

2020-11-06 15:10 UTC, antoniomanuelfr commented on src/unit_tests/shared/test_syscheck_op.c
> +} registry_group_information;
We should unify the names of the structures (i.e: `registry_group_information_t` instead of `registry_group_information`)

2020-11-06 16:25 UTC, antoniomanuelfr requested changes

2020-11-09 08:50 UTC, antoniomanuelfr approved these changes
LGTM

2020-11-11 11:40 UTC, Molter73 requested changes
Please exclude `get_registry_user` from the coverage report since it does not have specific tests for it.
https://github.com/wazuh/wazuh/blob/a1905c4757de10998c18caa2b3640d094104c711/src/shared/syscheck_op.c#L619-L621

2020-11-11 11:40 UTC, Molter73 commented on src/unit_tests/shared/test_syscheck_op.c
> +    char **not_null;
Please rename this variable to something a little more descriptive like `mock_directory_content`

2020-11-11 11:40 UTC, Molter73 commented on src/unit_tests/shared/test_syscheck_op.c
> +    char **not_null;
Same as previous comment.

2020-11-11 11:40 UTC, Molter73 commented on src/unit_tests/shared/test_syscheck_op.c
> +    char error_msg[OS_SIZE_1024];
Try to keep definition of variables at the start of the function/code block.

2020-11-12 10:58 UTC, Molter73 approved these changes
LGTM!

2020-11-12 10:58 UTC, merged