6354 os info win
wazuh/wazuh pull request #6510
Opened 2020-11-05 17:06 UTC by konangc87

|Related issue|
|---|
|#6354|

## **Description**

This issue aims to make use of the generic synchronization libraries, to use the synchronization solution algorithm that both shared modules provide.

These changes have to be made in the various implementations according to the operating system targeted for this feature.

## **DoD**
- [X] Implementation
- [X] **Run testtool on Win XP**
![image](https://user-images.githubusercontent.com/54002291/98264915-31a63200-1f67-11eb-90d4-1a0d0b3ec7cc.png)
- [X] **Run testtool on Win 7**
![image](https://user-images.githubusercontent.com/54002291/98262797-c9565100-1f64-11eb-8453-de98be26630c.png)
![image](https://user-images.githubusercontent.com/54002291/98265527-f0fae880-1f67-11eb-9c20-08cfce41bc55.png)
- [X] **Run testtool on Win 10**
![image](https://user-images.githubusercontent.com/54002291/98262980-ff93d080-1f64-11eb-8ef6-b7cee7177af4.png)
- **SysInfo UTs:**
> **Linux:**
![image](https://user-images.githubusercontent.com/54002291/98272612-0d028800-1f70-11eb-9a59-6e9aaf7dac5e.png)
> **Windows:**
![image](https://user-images.githubusercontent.com/54002291/98271691-f576cf80-1f6e-11eb-9ad8-5bb3cd0eb8fd.png)

2020-11-05 17:45 UTC, tinachoB requested changes

2020-11-05 17:45 UTC, tinachoB commented on src/wazuh_modules/syscollector/tests/sysInfo/sysOsInfo_test.cpp
> + * October 19, 2020.
Wrong header title and date

2020-11-05 17:55 UTC, Dwordcito requested changes

2020-11-05 17:55 UTC, Dwordcito commented on src/wazuh_modules/syscollector/sysInfoWin.cpp
> +        new SysOsInfoProviderWindows
use make_shared

2020-11-05 17:55 UTC, Dwordcito commented on src/wazuh_modules/syscollector/sysOsInfo/sysOsInfoWin.cpp
> +            const auto majorAndMinor{Utils::split(fullVersion, '.')};
check if size is 2, to avoid exception for missing information.

2020-11-05 17:55 UTC, Dwordcito commented on src/wazuh_modules/syscollector/sysOsInfo/sysOsInfoWin.cpp
> +            const auto majorAndMinor{Utils::split(fullVersion, '.')};
add enum OS_VERSION { MAJOR, MINOR, SIZE };

2020-11-05 17:55 UTC, Dwordcito commented on src/wazuh_modules/syscollector/sysOsInfo/sysOsInfoWin.cpp
> +    if (arch == "AMD64" || arch == "IA64" || arch == "ARM64")
add static map for this condition

2020-11-05 17:55 UTC, Dwordcito commented on src/wazuh_modules/syscollector/sysOsInfo/sysOsInfoWin.cpp
> +    if (arch == "AMD64" || arch == "IA64" || arch == "ARM64")
in sharedDefs.h is a good place.

2020-11-05 18:51 UTC, tinachoB approved these changes

2020-11-06 00:59 UTC, Dwordcito approved these changes

2020-11-06 01:01 UTC, merged