Added all fim_db (files and registries) unit tests in the Fim registry improvement
wazuh/wazuh pull request #6545
Opened 2020-11-10 07:45 UTC by jotacarma90

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/6340|

## Description

This PR add and modiry some files related to unit tests for **fim_db.c**, **fim_db_registries.c** and **fim_db_files.c**.
We created some libraries like **expect_fim_db** to auxiliary functions in the tests.

2020-11-13 15:31 UTC, antoniomanuelfr requested changes

2020-11-13 15:31 UTC, antoniomanuelfr commented on src/unit_tests/syscheckd/db/test_fim_db_files.c
> +    ret = fim_db_insert(test_data->fim_sql, test_data->entry->file_entry.path, test_data->entry->file_entry.data, test_data->saved);
Avoid code lines longer than 120 characters.

2020-11-13 15:31 UTC, antoniomanuelfr commented on src/unit_tests/syscheckd/db/test_fim_db_files.c
> +    ret = fim_db_insert(test_data->fim_sql, test_data->entry->file_entry.path, test_data->entry->file_entry.data, test_data->saved);
Avoid code lines longer than 120 characters.

2020-11-13 15:31 UTC, antoniomanuelfr commented on src/unit_tests/syscheckd/db/test_fim_db_files.c
> +    ret = fim_db_insert(test_data->fim_sql, test_data->entry->file_entry.path, test_data->entry->file_entry.data, test_data->saved);
Avoid code lines longer than 120 characters.

2020-11-13 15:31 UTC, antoniomanuelfr commented on src/unit_tests/syscheckd/db/test_fim_db_files.c
> +    ret = fim_db_insert(test_data->fim_sql, test_data->entry->file_entry.path, test_data->entry->file_entry.data, test_data->saved);
Avoid code lines longer than 120 characters.

2020-11-13 15:31 UTC, antoniomanuelfr commented on src/unit_tests/syscheckd/db/test_fim_db_files.c
> +    ret = fim_db_insert(test_data->fim_sql, test_data->entry->file_entry.path, test_data->entry->file_entry.data, test_data->saved);
Avoid code lines longer than 120 characters.

2020-11-16 08:32 UTC, Molter73 commented on src/unit_tests/syscheckd/db/test_fim_db_files.c
> +    ret = fim_db_insert(test_data->fim_sql, test_data->entry->file_entry.path, test_data->entry->file_entry.data, test_data->saved);
Done.

2020-11-16 08:32 UTC, Molter73 commented on src/unit_tests/syscheckd/db/test_fim_db_files.c
> +    ret = fim_db_insert(test_data->fim_sql, test_data->entry->file_entry.path, test_data->entry->file_entry.data, test_data->saved);
Done.

2020-11-16 08:32 UTC, Molter73 commented on src/unit_tests/syscheckd/db/test_fim_db_files.c
> +    ret = fim_db_insert(test_data->fim_sql, test_data->entry->file_entry.path, test_data->entry->file_entry.data, test_data->saved);
Done.

2020-11-16 08:32 UTC, Molter73 commented on src/unit_tests/syscheckd/db/test_fim_db_files.c
> +    ret = fim_db_insert(test_data->fim_sql, test_data->entry->file_entry.path, test_data->entry->file_entry.data, test_data->saved);
Done.

2020-11-16 08:32 UTC, Molter73 commented on src/unit_tests/syscheckd/db/test_fim_db_files.c
> +    ret = fim_db_insert(test_data->fim_sql, test_data->entry->file_entry.path, test_data->entry->file_entry.data, test_data->saved);
Done.

2020-11-16 08:51 UTC, antoniomanuelfr approved these changes
LGTM!

2020-11-16 09:16 UTC, merged