Adding sqlite3_finalize() to wdb_global_check_manager_keepalive()
wazuh/wazuh pull request #6697
Opened 2020-11-20 21:14 UTC by pereyra-m

|Related issue|
|---|
||

## Description

There were some issues in the upgrade process of the **global.db** database due a pending statement.
This PR finalizes the query inside the **wdb_global_check_manager_keepalive()** method to allow a proper upgrade.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Source upgrade
- [ ] Review logs syntax and correct language

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Valgrind (memcheck and descriptor leaks check)
- [ ] Added unit tests (for new features)

2020-11-20 22:47 UTC, palaciosjeremias approved these changes
LGTM!

2020-11-21 01:38 UTC, DProvinciani approved these changes
Looks good!

2020-12-09 11:35 UTC, DProvinciani approved these changes
New changes approved

2020-12-09 12:01 UTC, palaciosjeremias requested changes

2020-12-10 06:12 UTC, pereyra-m commented on src/wazuh_db/wdb_upgrade.c
> +int wdb_global_check_manager_keepalive(wdb_t *wdb) {
Fixed!

2020-12-10 12:45 UTC, palaciosjeremias approved these changes

2020-12-11 14:45 UTC, merged