Fim registry monitorization improvements
wazuh/wazuh pull request #6735
Opened 2020-11-26 11:33 UTC by Molter73

|Related issue|
|---|
|#5576|

## Description

This PR groups together all the changes needed to monitor registry keys and values as separate entities, allowing users to get more detailed information on changes that might occur in their Windows registry. As a result, we have modified the registry scan algorithm, added new configuration options and alter the existing agent fim database.

The synchronization mechanism has also been modified in order to properly exchange information of both files and registry entries between agents and their manager.

On the manager side, a new set of sycheck decoders have been created, these will be in charge of handling registry events.

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

2020-11-26 17:23 UTC, Molter73 commented
Scan-build reported 2 defects under windows compilation, neither of them were introduced by this PR.

[scan-build-winagent.zip](https://github.com/wazuh/wazuh/files/5604366/scan-build-winagent.zip)

Both server and agent scan-build compilations reported no errors.

2020-11-27 15:56 UTC, jesusjimsa commented
There is only one bug reported by scan-build in macOS, but it was not introduced in this pull request.
[scan-build-mac.zip](https://github.com/wazuh/wazuh/files/5608653/scan-build-mac.zip)

2020-12-02 13:00 UTC, vikman90 requested changes
Team, this is a great change!

We need to update `wazuh-template.json`.

Thanks!

2020-12-03 09:38 UTC, Molter73 commented on src/syscheckd/registry/registry.c
> +        SHA1_Update(sha1_ctx, buffer, length);
I've changed the type of the length paramter of `fim_registry_update_digests` to be `size_t` and removed the cast from `MD5_Update`, no warnings were issued by the compiler and seems a little more coherent now.

2020-12-03 09:38 UTC, Molter73 commented on src/syscheckd/registry/registry.c
> +        SHA256_Update(sha256_ctx, buffer, length);
I've changed the type of the length paramter of `fim_registry_update_digests` to be `size_t` and removed the cast from `MD5_Update`, no warnings were issued by the compiler and seems a little more coherent now.

2020-12-03 09:38 UTC, Molter73 commented on src/syscheckd/registry/registry.c
> +        for (n = 0; n < 16; n++) {
Done!

2020-12-15 09:57 UTC, vikman90 approved these changes

2020-12-15 10:00 UTC, merged