Fix bugs that caused symbolic links to not work correctly
wazuh/wazuh pull request #6789
Opened 2020-12-01 15:14 UTC by jesusjimsa

| Related issue |
| ------------- |
| #6690         |

## Description

This pull request fixes a series of bugs that, under certain circumstances, caused symbolic links to not work as expected.

This pull request closes #6690.

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
- Memory tests for Windows
  - [ ] Scan-build report
- Memory tests for macOS
  - [ ] Scan-build report

2020-12-03 11:43 UTC, jotacarma90 approved these changes

2020-12-03 11:43 UTC, jotacarma90 commented
LGTM

2020-12-09 16:00 UTC, Molter73 requested changes

2021-01-21 11:08 UTC, Molter73 commented
I've rerun all integration tests with the latest changes. When running locally some failures were reported but they look more related to my test environment than to the changes in this PR, I will take a closer look to them just to be sure.

#### Centos, Ubuntu and Windows in whodata and realtime modes:
[agent_ubuntu_html_report_test_integration_B1028_20210120165311.zip](https://github.com/wazuh/wazuh/files/5848807/agent_ubuntu_html_report_test_integration_B1028_20210120165311.zip)
[agent_windows_html_report_test_integration_B1028_20210120165311.zip](https://github.com/wazuh/wazuh/files/5848808/agent_windows_html_report_test_integration_B1028_20210120165311.zip)
[agent_centos_html_report_test_integration_B1028_20210120165311.zip](https://github.com/wazuh/wazuh/files/5848809/agent_centos_html_report_test_integration_B1028_20210120165311.zip)

#### Centos, Ubuntu and Windows in scheduled mode:
[Centos scheduled - symlinks.zip](https://github.com/wazuh/wazuh/files/5848812/Centos.scheduled.-.symlinks.zip)
[Ubuntu scheduled - symlinks.zip](https://github.com/wazuh/wazuh/files/5848813/Ubuntu.scheduled.-.symlinks.zip)
[Windows scheduled - symlinks.zip](https://github.com/wazuh/wazuh/files/5848816/Windows.scheduled.-.symlinks.zip)

#### Macos and Solaris:
[agent_macos_html_report_test_integration_B1029_20210120165322.zip](https://github.com/wazuh/wazuh/files/5848817/agent_macos_html_report_test_integration_B1029_20210120165322.zip)
[agent_solaris_html_report_test_integration_B1029_20210120165322.zip](https://github.com/wazuh/wazuh/files/5848818/agent_solaris_html_report_test_integration_B1029_20210120165322.zip)

2021-01-21 15:36 UTC, antoniomanuelfr approved these changes
LGTM!

2021-01-22 16:44 UTC, vikman90 approved these changes

2021-01-22 16:49 UTC, vikman90 approved these changes

2021-01-22 16:50 UTC, merged