Fix wrong alerts when file limit is reached
wazuh/wazuh pull request #6802
Opened 2020-12-02 10:42 UTC by antoniomanuelfr

|Related issue|
|---|
|#5718|

## Description
This PR aims to fix the issue described in #5718 by adding a new SQLite query that gets the information of all the files in a specific folder.

Closes #5718

- Compilation without warnings in every supported platform
  - [X] Linux
  - [X] Windows
  - [ ] MAC OS X
- [X] Source installation
- [ ] Package installation
- [X] Source upgrade
- [ ] Review logs syntax and correct language

- Memory tests for Linux
  - [X] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
- Memory tests for Windows
  - [X] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory

2020-12-09 11:13 UTC, jesusjimsa requested changes

2020-12-09 14:01 UTC, jesusjimsa approved these changes
LGTM!

2020-12-17 12:25 UTC, antoniomanuelfr commented
These are the Jenkins reports of the integration tests: 

[agent_solaris_html_report_test_integration_B842_20201217103547.zip](https://github.com/wazuh/wazuh/files/5709314/agent_solaris_html_report_test_integration_B842_20201217103547.zip)
[agent_macos_html_report_test_integration_B842_20201217103547.zip](https://github.com/wazuh/wazuh/files/5709315/agent_macos_html_report_test_integration_B842_20201217103547.zip)
[agent_windows_html_report_test_integration_B841_20201217103527.zip](https://github.com/wazuh/wazuh/files/5709316/agent_windows_html_report_test_integration_B841_20201217103527.zip)
[agent_ubuntu_html_report_test_integration_B841_20201217103527.zip](https://github.com/wazuh/wazuh/files/5709317/agent_ubuntu_html_report_test_integration_B841_20201217103527.zip)
[agent_centos_html_report_test_integration_B841_20201217103527.zip](https://github.com/wazuh/wazuh/files/5709318/agent_centos_html_report_test_integration_B841_20201217103527.zip)

2020-12-17 14:27 UTC, jotacarma90 approved these changes

2021-01-07 12:00 UTC, Molter73 approved these changes
LGTM!

2021-01-13 16:55 UTC, merged