Refactor framework tasks module
wazuh/wazuh pull request #6804
Opened 2020-12-02 11:28 UTC by AdriiiPRodri

|Related issue|
|---|
|#6029|

Hi team,

This PR closes #6029. In this PR we have adapted the whole part of the Framework related to the tasks module. In this way we now take advantage of the last changes made with wazuhdb and the task module.

### Integration tests
```
adriiiprodri@wazuh pytest -x test_tasks_endpoints.tavern.yaml 
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api/test/integration, configfile: pytest.ini
plugins: metadata-1.10.0, html-2.1.1, tavern-1.7.0
collected 4 items                                                                                                                                                         

test_tasks_endpoints.tavern.yaml ....

================================================================ 4 passed, 5 warnings in 155.67s (0:02:35) ================================================================
```

### Unittests
```
adriiiprodri@wazuh pytest -x wazuh/tests/test_tasks.py
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/framework
plugins: metadata-1.10.0, html-2.1.1, tavern-1.7.0
collected 28 items                                                                                                                                                        

wazuh/tests/test_tasks.py ............................

=========================================================================== 28 passed in 0.25s ============================================================================
```

2020-12-04 16:14 UTC, davidjiglesias requested changes
task.py in core
review default rbac resources
add documentation

2020-12-04 16:14 UTC, davidjiglesias commented on framework/wazuh/rbac/default/relationships.yaml
> +        - tasks_status
task status?

2020-12-09 15:20 UTC, Selutario approved these changes

2020-12-09 16:19 UTC, CarlosRS9 commented on api/api/controllers/task_controller.py
> +    request
Remove empty `request` parameter from docstring. It is not present in any other controller definitions.

2020-12-09 16:26 UTC, CarlosRS9 approved these changes

2020-12-09 16:45 UTC, merged