5761 audit rules not removed after symlink update
wazuh/wazuh pull request #6999
Opened 2020-12-21 15:59 UTC by antoniomanuelfr

|Related issue|
|---|
|#5761|

## Description
This PR aims to fix the problem described in #5761. When a symlink is updated or removed, the audit rule is removed.

## Configuration options
```xml
    <directories whodata="yes" follow_symbolic_link="yes">/test_link,/test_link2,/test_link3</directories>
```
## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

2020-12-23 15:49 UTC, antoniomanuelfr commented
scan-build did not report any error: 
```
Done building server

scan-build: Analysis run complete.
scan-build: Removing directory '/tmp/scan-build-2020-12-23-164707-103237-1' because it contains no reports.
scan-build: No bugs found.
```

2020-12-28 09:16 UTC, jotacarma90 requested changes

2020-12-28 09:16 UTC, jotacarma90 commented on src/unit_tests/syscheckd/test_syscheck_audit.c
> +        //cmocka_unit_test_setup_teardown(test_add_audit_rules_syscheck_not_added, setup_add_audit_rules, teardown_add_audit_rules),
This test is commented

2020-12-28 11:41 UTC, jotacarma90 approved these changes

2020-12-28 11:42 UTC, jotacarma90 submitted a review, later dismissed
LGTM

2021-01-07 15:04 UTC, Molter73 requested changes

2021-01-07 15:04 UTC, Molter73 commented on src/unit_tests/syscheckd/test_syscheck_audit.c
> +    will_return(__wrap_audit_add_rule, EEXIST);
Should this be `-EEXIST`?

2021-01-07 15:04 UTC, Molter73 commented on src/unit_tests/syscheckd/test_syscheck_audit.c
> +    will_return(__wrap_audit_add_rule, EEXIST);
Should this be `-EEXIST`?

2021-01-20 09:35 UTC, antoniomanuelfr commented
This is the result of the execution of the integration test locally (tier 0 and tier 1):
[report_audit.zip](https://github.com/wazuh/wazuh/files/5841403/report_audit.zip)

2021-01-20 11:08 UTC, antoniomanuelfr commented
These are the result of the execution of the integration tests in Jenkins:

[agent_centos_html_report_test_integration_B1025_20210120092604.zip](https://github.com/wazuh/wazuh/files/5841926/agent_centos_html_report_test_integration_B1025_20210120092604.zip)
[agent_ubuntu_html_report_test_integration_B1025_20210120092604.zip](https://github.com/wazuh/wazuh/files/5841927/agent_ubuntu_html_report_test_integration_B1025_20210120092604.zip)
[agent_windows_html_report_test_integration_B1025_20210120092604.zip](https://github.com/wazuh/wazuh/files/5841928/agent_windows_html_report_test_integration_B1025_20210120092604.zip)

2021-01-20 18:05 UTC, Molter73 requested changes

2021-01-21 15:32 UTC, Molter73 approved these changes
LGTM!

2021-01-22 14:41 UTC, antoniomanuelfr commented
These are the result of the integration test after all the modifications: 

[agent_macos_html_report_test_integration_B1039_20210122132156.zip](https://github.com/wazuh/wazuh/files/5856510/agent_macos_html_report_test_integration_B1039_20210122132156.zip)
[agent_solaris_html_report_test_integration_B1039_20210122132156.zip](https://github.com/wazuh/wazuh/files/5856511/agent_solaris_html_report_test_integration_B1039_20210122132156.zip)

2021-01-27 07:10 UTC, antoniomanuelfr commented
After the latest changes in this PR (rebase to master to fix conflicts with https://github.com/wazuh/wazuh/pull/6789) these are the results of the integration tests executed in Jenkins:
[agent_centos_html_report_test_integration_B1046_20210126162246.zip](https://github.com/wazuh/wazuh/files/5878310/agent_centos_html_report_test_integration_B1046_20210126162246.zip)
[agent_macos_html_report_test_integration_B1047_20210126162317.zip](https://github.com/wazuh/wazuh/files/5878311/agent_macos_html_report_test_integration_B1047_20210126162317.zip)
[agent_solaris_html_report_test_integration_B1047_20210126162317.zip](https://github.com/wazuh/wazuh/files/5878312/agent_solaris_html_report_test_integration_B1047_20210126162317.zip)
[agent_ubuntu_html_report_test_integration_B1046_20210126162246.zip](https://github.com/wazuh/wazuh/files/5878313/agent_ubuntu_html_report_test_integration_B1046_20210126162246.zip)
[agent_windows_html_report_test_integration_B1046_20210126162246.zip](https://github.com/wazuh/wazuh/files/5878314/agent_windows_html_report_test_integration_B1046_20210126162246.zip)
Kind regards

2021-01-27 14:47 UTC, Molter73 requested changes
I just tried to replace a monitored symbolic link with a directory and the rule for the target remains configured.

Monitoring:
```xml
<directories whodata="yes" follow_symbolic_link="yes">/home/vagrant/link</directories>
```

With `/home/vagrant/link -> /home/vagrant/monitored-wd`, I issued the following command:
```
vagrant@server:~$ rm link && mkdir link && touch link/test
```

After the links and audit rules are reloaded I get:
```
root@server:/home/vagrant# auditctl -l
-w /etc/group -p wa
-w /home/vagrant/monitored-wd -p wa -k wazuh_fim
-w /home/vagrant/link -p wa -k wazuh_fim
```

And if I stop `wazuh-syscheckd` only the rule pointing to `/home/vagrant/link` is removed.

I also found some memory leaks by running the daemon compiled with AddressSanitizer:
```
=================================================================
==5498==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 82 byte(s) in 12 object(s) allocated from:
    #0 0x7fc319f74538 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x77538)
    #1 0x5612d9bb9ff6 in fim_get_real_path syscheckd/create_db.c:1239
    #2 0x5612d9bc666b in fim_link_update syscheckd/run_check.c:600
    #3 0x5612d9bc62f5 in symlink_checker_thread syscheckd/run_check.c:553
    #4 0x7fc3193706da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)

Direct leak of 27 byte(s) in 1 object(s) allocated from:
    #0 0x7fc319f74538 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x77538)
    #1 0x5612d9bc8353 in fim_link_reload_broken_link syscheckd/run_check.c:765
    #2 0x5612d9bc651f in symlink_checker_thread syscheckd/run_check.c:573
    #3 0x7fc3193706da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)

Direct leak of 27 byte(s) in 1 object(s) allocated from:
    #0 0x7fc319f74538 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x77538)
    #1 0x5612d9c2347c in dump_syscheck_file config/syscheck-config.c:213
    #2 0x5612d9c28aae in read_attr config/syscheck-config.c:1282
    #3 0x5612d9c2cf99 in Read_Syscheck config/syscheck-config.c:1803
    #4 0x5612d9bf2802 in read_main_elements config/config.c:105
    #5 0x5612d9bf3f72 in ReadConfig config/config.c:279
    #6 0x5612d9bbb3e4 in Read_Syscheck_Config syscheckd/config.c:89
    #7 0x5612d9bc8b2c in main syscheckd/main.c:108
    #8 0x7fc318f99b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: 136 byte(s) leaked in 14 allocation(s).
```

2021-01-28 07:49 UTC, antoniomanuelfr commented
Hi!!

I have been investigating the bug that @Molter73 described and I found the cause:
https://github.com/wazuh/wazuh/blob/93573876eafc2c5c38b7e4b4e5567ef3b348d9c1/src/syscheckd/run_check.c#L588-L616

When `syscheckd` enters in `fim_link_update` it checks if the new path is already added (line 614 in the above code snippet ). This check is done by comparing if there is an entry in `syscheck.dir` with the same path, and as the new folder has the same name as the link, the comparison is true, `fim_link_update` discards the link and returns.

 I'm going to do some testing here, but I think that instead of using `syscheck.dir` to check if the path is already configured, using `fim_get_real_path`  will do the trick and avoid this problem.

In the meantime, I will move this PR to draft.

Kind regards

2021-02-01 12:27 UTC, antoniomanuelfr commented
These are the integration tests with the latest changes:
[agent_centos_html_report_test_integration_B1077_20210201104211.zip](https://github.com/wazuh/wazuh/files/5903888/agent_centos_html_report_test_integration_B1077_20210201104211.zip)
[agent_macos_html_report_test_integration_B1078_20210201104233.zip](https://github.com/wazuh/wazuh/files/5903889/agent_macos_html_report_test_integration_B1078_20210201104233.zip)
[agent_solaris_html_report_test_integration_B1078_20210201104233.zip](https://github.com/wazuh/wazuh/files/5903890/agent_solaris_html_report_test_integration_B1078_20210201104233.zip)
[agent_ubuntu_html_report_test_integration_B1077_20210201104211.zip](https://github.com/wazuh/wazuh/files/5903891/agent_ubuntu_html_report_test_integration_B1077_20210201104211.zip)
[agent_windows_html_report_test_integration_B1077_20210201104211.zip](https://github.com/wazuh/wazuh/files/5903892/agent_windows_html_report_test_integration_B1077_20210201104211.zip)

2021-02-12 12:00 UTC, antoniomanuelfr commented
These are the integration test with the latest changes 
[agent_centos_html_report_test_integration_B1251_20210212093530.zip](https://github.com/wazuh/wazuh/files/5971550/agent_centos_html_report_test_integration_B1251_20210212093530.zip)
[agent_windows_html_report_test_integration_B1251_20210212093530.zip](https://github.com/wazuh/wazuh/files/5971554/agent_windows_html_report_test_integration_B1251_20210212093530.zip)
[agent_ubuntu_html_report_test_integration_B1251_20210212093530.zip](https://github.com/wazuh/wazuh/files/5971553/agent_ubuntu_html_report_test_integration_B1251_20210212093530.zip)
[agent_macos_html_report_test_integration_B1252_20210212093554.zip](https://github.com/wazuh/wazuh/files/5971551/agent_macos_html_report_test_integration_B1252_20210212093554.zip)
[agent_solaris_html_report_test_integration_B1252_20210212093554.zip](https://github.com/wazuh/wazuh/files/5971552/agent_solaris_html_report_test_integration_B1252_20210212093554.zip)

There is one failed test in CentOS. After looking at the logs, it seems to be a false negative. The test monitors a nonexisting folder and waits for a message that informs that the audit rule can't be created. After that, the test creates a folder and wait until the rule is added (30 seconds). The timeout between these two events is 30 seconds and in this execution, the test failed, but looking at the logs, both events appear. 

I have increased the timeout of this test to 32 seconds, in order to avoid this error in future executions.

2021-03-03 14:11 UTC, Molter73 approved these changes
LGTM!

2021-03-05 15:58 UTC, merged