Add new endpoint to get logcollector stats
wazuh/wazuh pull request #7200
Opened 2021-01-15 15:51 UTC by Selutario

|Related issue|
|---|
|Closes #7128|

## Description

Hello team!

A new endpoint is developed in this PR as requested in #7128:
```
GET /agents/{agent_id}/stats/logcollector
```

It can retrieve information from both, managers (000) and agents (!=000). Example output from the agent `003` is:
```Python
{
  "data": {
    "affected_items": [
      {
        "global": {
          "start": "Fri Jan 15 13:55:56 2021",
          "end": "Fri Jan 15 15:49:18 2021",
          "files": [
            {
              "targets": [
                {
                  "name": "agent",
                  "drops": 0
                }
              ],
              "location": "df -P",
              "bytes": 9020,
              "events": 100
            },
            {
              "targets": [
                {
                  "name": "agent",
                  "drops": 0
                }
              ],
              "location": "/var/log/dpkg.log",
              "bytes": 0,
              "events": 0
            },
            {
              "targets": [
                {
                  "name": "agent",
                  "drops": 0
                }
              ],
              "location": "/var/ossec/logs/active-responses.log",
              "bytes": 0,
              "events": 0
            },
            {
              "targets": [
                {
                  "name": "agent",
                  "drops": 0
                }
              ],
              "location": "last -n 20",
              "bytes": 660,
              "events": 10
            }
          ]
        },
        "interval": {
          "start": "Fri Jan 15 15:49:13 2021",
          "end": "Fri Jan 15 15:49:18 2021",
          "files": [
            {
              "targets": [
                {
                  "name": "agent",
                  "drops": 0
                }
              ],
              "location": "df -P",
              "bytes": 0,
              "events": 0
            },
            {
              "targets": [
                {
                  "name": "agent",
                  "drops": 0
                }
              ],
              "location": "/var/log/dpkg.log",
              "bytes": 0,
              "events": 0
            },
            {
              "targets": [
                {
                  "name": "agent",
                  "drops": 0
                }
              ],
              "location": "/var/ossec/logs/active-responses.log",
              "bytes": 0,
              "events": 0
            },
            {
              "targets": [
                {
                  "name": "agent",
                  "drops": 0
                }
              ],
              "location": "last -n 20",
              "bytes": 0,
              "events": 0
            }
          ]
        }
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Obtained logcollector stats from all selected agents",
  "error": 0
}
```

## Tests output
### Integration tests
New integration tests have been added inside `test_agent_GET_endpoints`, `test_rbac_white_agent_endpoints` and `test_rbac_black_agent_endpoints`:

```
pytest -vv test_agent_GET_endpoints.tavern.yaml --disable-warnings
============================================================================================ test session starts =============================================================================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.2, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.5', 'Platform': 'Linux-5.4.0-58-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.4.3', 'py': '1.8.2', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '1.10.0', 'testinfra': '5.0.0', 'tavern': '1.2.2', 'cov': '2.10.0', 'asyncio': '0.14.0', 'html': '2.0.1'}}
rootdir: /home/selu/Git/wazuh/api/test/integration, inifile: pytest.ini
plugins: metadata-1.10.0, testinfra-5.0.0, tavern-1.2.2, cov-2.10.0, asyncio-0.14.0, html-2.0.1
collected 91 items                                                                                                                                                                                           

test_agent_GET_endpoints.tavern.yaml::GET /agents PASSED                                                                                                                                               [  1%]
test_agent_GET_endpoints.tavern.yaml::GET /agents with single agent id PASSED                                                                                                                          [  2%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/config/{component}/{configuration} PASSED                                                                                                 [  3%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/group/is_sync PASSED                                                                                                                      [  4%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/key PASSED                                                                                                                                [  5%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/stats/logcollector PASSED                                                                                                                 [  6%]
test_agent_GET_endpoints.tavern.yaml::GET /groups PASSED                                                                                                                                               [  7%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[md5] PASSED                                                                                                                              [  8%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha1] PASSED                                                                                                                             [  9%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha224] PASSED                                                                                                                           [ 10%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha256] PASSED                                                                                                                           [ 12%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha384] PASSED                                                                                                                           [ 13%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha512] PASSED                                                                                                                           [ 14%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[blake2b] PASSED                                                                                                                          [ 15%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[blake2s] PASSED                                                                                                                          [ 16%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha3_224] PASSED                                                                                                                         [ 17%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha3_256] PASSED                                                                                                                         [ 18%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha3_384] PASSED                                                                                                                         [ 19%]
test_agent_GET [...]

2021-01-26 16:46 UTC, vicferpoy commented
## Issue update
Hello team,

we decided to rework the endpoint to allow future component additions without developing new endpoints. The new endpoint is `GET /agents/{agent_id}/stats/{component}`. Right now, `component` is an enum with the following value:
- `logcollector`

API spec, unit and integration tests have been updated as well.

### Test results
#### Unit tests
```
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.2, pluggy-0.13.1
rootdir: /home/vicferpoy/Desktop/Git/wazuh/framework
plugins: metadata-1.10.0, asyncio-0.12.0, cov-2.10.1, html-2.0.1
collected 1612 items                                                                                                                                                                        

wazuh/core/cluster/dapi/tests/test_dapi.py ......................                                                                                                                     [  1%]
wazuh/core/cluster/tests/test_cluster.py ...................                                                                                                                          [  2%]
wazuh/core/cluster/tests/test_common.py .......                                                                                                                                       [  2%]
wazuh/core/cluster/tests/test_control.py .....                                                                                                                                        [  3%]
wazuh/core/cluster/tests/test_local_client.py .                                                                                                                                       [  3%]
wazuh/core/cluster/tests/test_utils.py .......                                                                                                                                        [  3%]
wazuh/core/cluster/tests/test_worker.py ................                                                                                                                              [  4%]
wazuh/core/tests/test_active_response.py ............                                                                                                                                 [  5%]
wazuh/core/tests/test_agent.py ...................................................................................................................................................... [ 14%]
...                                                                                                                                                                                   [ 15%]
wazuh/core/tests/test_cdb_list.py .................................                                                                                                                   [ 17%]
wazuh/core/tests/test_common.py .......                                                                                                                                               [ 17%]
wazuh/core/tests/test_configuration.py ..................................                                                                                                             [ 19%]
wazuh/core/tests/test_decoder.py ................                                                                                                                                     [ 20%]
wazuh/core/tests/test_input_validator.py ...                                                                                                                                          [ 20%]
wazuh/core/tests/test_logtest.py ..                                                                                                                                                   [ 20%]
wazuh/core/tests/test_manager.py ...............................                                                                                                                      [ 22%]
wazuh/core/tests/test_ossec_queue.py ...................                                                                                                                              [ 24%]
wazuh/core/tests/test_pyDaemonModule.py ......                                                                                                                                        [ 24%]
wazuh/core/tests/test_results.py ........................................                                                                                                             [ 26%]
wazuh/core/tests/test_rootcheck.py ..........                                                                                                                                         [ 27%]
wazuh/core/tests/test_rule.py ......................                                                                                                                                  [ 28%]
wazuh/core/tests/test_stats.py ...                                                                                                                                                    [ 29%]
wazuh/core/tests/test_syscollector.py ...                                                                                                                                             [ 29%]
wazuh/core/tests/test_utils.py ...................................................................................................................................................... [ 38%]
............................................................                                                                                                                          [ 42%]
wazuh/core/tests/test_wazuh_socket.py ....................                                                                                                                            [ 43%]
wazuh/core/tests/test_wdb.py .....................                                                                                                                                    [ 44%]
wazuh/rbac/tests/test_auth_context.py ..                                                                                                                                              [ 44%]
wazuh/rbac/tests/test_decorators.py .........................................................................................................                                         [ 51%]
wazuh/rbac/tests/test_default_configuration.py ...................................................                                                                                    [ 54%]
wazuh/rbac/tests/test_orm.py .....................................................                                                                                                    [ 57%]
wazuh/rbac/tests/test_preprocessor.py ...........                                                                                                                                     [ 58%]
wazuh/tests/test_active_response.py .........                                                                                                                                         [ 59%]
wazuh/tests/test_agent.py ....................................................................................                                                                        [ 64%]
wazuh/tests/test_cdb_list.py ...............................................                                                                                                          [ 67%]
wazuh/tests/test_ciscat.py ..                                                                                                                                                         [ 67%]
wazuh/tests/test_cluster.py .......                            [...]

2021-01-27 09:31 UTC, davidjiglesias requested changes

2021-01-27 09:31 UTC, davidjiglesias commented on CHANGELOG.md
> +  - Added new endpoint to get logcollector stats from an agent. ([#7128](https://github.com/wazuh/wazuh/issues/7128))
```suggestion
  - Added new endpoint to get agent stats from different components. ([#7128](https://github.com/wazuh/wazuh/issues/7128))
```

2021-01-27 09:31 UTC, davidjiglesias commented on api/api/controllers/agent_controller.py
> +    """Get a specified agent's logcollector stats.
```suggestion
    """Get a specified agent's component stats.
```

2021-01-27 09:31 UTC, davidjiglesias commented on api/api/controllers/agent_controller.py
> +        Logcollector stats.
```suggestion
        Module stats.
```

2021-01-27 09:31 UTC, davidjiglesias commented on framework/wazuh/core/agent.py
> +    def getstats(self, daemon):
get_stats?

2021-01-27 09:31 UTC, davidjiglesias commented on framework/wazuh/core/agent.py
> +    def getstats(self, daemon):
component instead of daemon?

2021-01-27 09:31 UTC, davidjiglesias commented on framework/wazuh/stats.py
> +node_id = get_node().get('node') if cluster_enabled else 'manager'
what is this change for?

2021-01-27 11:56 UTC, davidjiglesias approved these changes

2021-01-27 11:56 UTC, merged