5823 false alert database
wazuh/wazuh pull request #7268
Opened 2021-01-26 13:31 UTC by jotacarma90

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/5823|

## Description

This PR fixes an error in the log messages caused by the output of a function not being checked correctly.
It now checks that the **nodes_count** variable cannot be negative, and also, the type of the variable has been changed to match the type of the function.
Added the unit test that tests this specific case.

## Logs/Alerts example

When nodes_count is negative, we got this warning:
`(6947): Unable to get the number of entries in database.`
And function **fim_check_db_state** will terminate in that point.

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
 
- [ ] Source installation
- [ ] Review logs syntax and correct language

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Valgrind (memcheck and descriptor leaks check)

- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity

2021-01-27 09:01 UTC, jotacarma90 commented
Jenkins integration test result:
[agent_solaris_html_report_test_integration_B1045_20210126145852.zip](https://github.com/wazuh/wazuh/files/5878860/agent_solaris_html_report_test_integration_B1045_20210126145852.zip)
[agent_macos_html_report_test_integration_B1045_20210126145852.zip](https://github.com/wazuh/wazuh/files/5878861/agent_macos_html_report_test_integration_B1045_20210126145852.zip)
[agent_windows_html_report_test_integration_B1044_20210126145837.zip](https://github.com/wazuh/wazuh/files/5878862/agent_windows_html_report_test_integration_B1044_20210126145837.zip)
[agent_ubuntu_html_report_test_integration_B1044_20210126145837.zip](https://github.com/wazuh/wazuh/files/5878863/agent_ubuntu_html_report_test_integration_B1044_20210126145837.zip)
[agent_centos_html_report_test_integration_B1044_20210126145837.zip](https://github.com/wazuh/wazuh/files/5878864/agent_centos_html_report_test_integration_B1044_20210126145837.zip)

Local scheduled integration test:
[Scheduled-local-5823.zip](https://github.com/wazuh/wazuh/files/5878868/Scheduled-local-5823.zip)

2021-01-27 17:42 UTC, Molter73 requested changes
I'm getting several compile warnings complaining about comparisons made between `nodes_count` and `syscheck.file_limit` because they differ in signedness.

```
syscheckd/create_db.c: In function ‘fim_scan’:
syscheckd/create_db.c:105:53: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (syscheck.file_limit_enabled && (nodes_count >= syscheck.file_limit)) {
                                                     ^~
syscheckd/create_db.c: In function ‘fim_check_db_state’:
syscheckd/create_db.c:499:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (nodes_count >= syscheck.file_limit) {
                         ^~
syscheckd/create_db.c:504:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ((nodes_count < syscheck.file_limit) && (nodes_count >= syscheck.file_limit * 0.9)) {
                          ^
syscheckd/create_db.c:539:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (nodes_count >= syscheck.file_limit) {
                     ^~
```
Since `syscheck.file_limit` is already capped at the maximum positive integer I suggest turning it into a signed integer. This will also need a small change in `syscheck-config.c`, since initialization of this variable requires `syscheck.file_limit` to be unsigned to work properly.

2021-01-28 10:06 UTC, jotacarma90 commented
Local schedule test result for file_limit integration tests:
[schedule_local_file_limit_5823.zip](https://github.com/wazuh/wazuh/files/5886338/schedule_local_file_limit_5823.zip)

Jenkins result for file_limit integration tests:

2021-01-28 17:08 UTC, Molter73 approved these changes
LGTM!

2021-02-01 15:57 UTC, merged