Modifying syscheck static fields into dynamic fields
wazuh/wazuh pull request #7358
Opened 2021-02-03 14:01 UTC by jotacarma90

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/5002|

## Description
This PR is intended to remove all syscheck's static fields in the Eventinfo structure. Some of them were duplicated and it is simply necessary to remove the static ones, while for others it is also necessary to create the dynamic field taking care that the functionality remains the same.

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

2021-02-15 08:04 UTC, jotacarma90 commented
FIM Jenkins integration test results:
[agent_windows_html_report_test_integration_B1260_20210212150330.zip](https://github.com/wazuh/wazuh/files/5980190/agent_windows_html_report_test_integration_B1260_20210212150330.zip)
[agent_ubuntu_html_report_test_integration_B1260_20210212150330.zip](https://github.com/wazuh/wazuh/files/5980191/agent_ubuntu_html_report_test_integration_B1260_20210212150330.zip)
[agent_centos_html_report_test_integration_B1260_20210212150330.zip](https://github.com/wazuh/wazuh/files/5980192/agent_centos_html_report_test_integration_B1260_20210212150330.zip)
[agent_solaris_html_report_test_integration_B1261_20210212150335.zip](https://github.com/wazuh/wazuh/files/5980193/agent_solaris_html_report_test_integration_B1261_20210212150335.zip)
[agent_macos_html_report_test_integration_B1261_20210212150335.zip](https://github.com/wazuh/wazuh/files/5980194/agent_macos_html_report_test_integration_B1261_20210212150335.zip)

2021-02-24 16:26 UTC, Molter73 requested changes
Apart from the comments, src/analysisd/analysisd.c only has whitespace changes. In order to prevent potential conflicts with other PRs we should revert it back to how it was.

2021-02-24 16:26 UTC, Molter73 commented on src/analysisd/format/to_json.c
> +            if (strcmp(lf->fields[FIM_TAG].value, "") != 0) {
```suggestion
        if(lf->fields[FIM_TAG].value && *lf->fields[FIM_TAG].value != '\0') {
```

2021-02-24 16:26 UTC, Molter73 commented on src/unit_tests/analysisd/test_log.c
> +    char aux1[12];
```suggestion
```

2021-02-24 16:26 UTC, Molter73 commented on src/unit_tests/analysisd/test_log.c
> +    }
Could we get away with this?
```suggestion
    lf->fields= df;
```

2021-02-25 10:07 UTC, jotacarma90 commented on src/analysisd/alerts/log.c
> +        if (lf->fields[FIM_UID].value && lf->fields[FIM_UNAME].value && *lf->fields[FIM_UNAME].value != '\0') {
Just in the if below was doing that check, I unified the conditionals

2021-02-25 10:07 UTC, jotacarma90 commented on src/analysisd/alerts/log.c
> +        if (lf->fields[FIM_GID].value && lf->fields[FIM_GNAME].value && *lf->fields[FIM_GNAME].value != '\0') {
Just in the if below was doing that check, I unified the conditionals

2021-02-25 10:18 UTC, jotacarma90 commented on src/headers/syscheck_op.h
> +    FIM_EVENT_TYPE_STR,
Changed the other static buffer to FIM_EVENT_TYPE_ARRAY

2021-02-25 11:41 UTC, jotacarma90 commented on src/analysisd/decoders/syscheck.c
> +            if (strcmp(lf->fields[FIM_EVENT_TYPE_STR].value, SYSCHECK_EVENT_STRINGS[FIM_ADDED]) == 0) {
Created `syscheck_event_t event_type` and added a parameter to `fim_alert` and `fim_generate_alert` to be more efficient deleting some strcmp.

2021-03-03 07:50 UTC, jotacarma90 commented
Integration test for analysisd passed:
[manager_html_report_test_integration_B1362_20210302092909.zip](https://github.com/wazuh/wazuh/files/6074347/manager_html_report_test_integration_B1362_20210302092909.zip)
[agent_windows_html_report_test_integration_B1372_20210302144938.zip](https://github.com/wazuh/wazuh/files/6074348/agent_windows_html_report_test_integration_B1372_20210302144938.zip)
[agent_ubuntu_html_report_test_integration_B1363_20210302092912.zip](https://github.com/wazuh/wazuh/files/6074349/agent_ubuntu_html_report_test_integration_B1363_20210302092912.zip)
[agent_centos_html_report_test_integration_B1363_20210302092912.zip](https://github.com/wazuh/wazuh/files/6074350/agent_centos_html_report_test_integration_B1363_20210302092912.zip)

2021-03-09 16:14 UTC, jotacarma90 commented
Integration test in local for test_analysisd
[analysisd-integrados-local-5002.zip](https://github.com/wazuh/wazuh/files/6109859/analysisd-integrados-local-5002.zip)

2021-03-19 08:50 UTC, antoniomanuelfr requested changes
The PR looks good, but some style changes are requested.

2021-03-19 08:50 UTC, antoniomanuelfr commented on src/analysisd/decoders/syscheck.c
> +        {
```suggestion
        if(newsum->sha256 && newsum->sha256[0] != '\0')  {
```

2021-03-19 08:50 UTC, antoniomanuelfr commented on src/analysisd/decoders/syscheck.c
>              if (!strcmp(attr_it->string, "perm")) {
Can you change these `strcmp` to match the same structure? 
```suggestion
            if (strcmp(attr_it->string, "perm") == 0) {
```

2021-03-19 08:50 UTC, antoniomanuelfr commented on src/analysisd/eventinfo.c
> +    char *module_name = strstr(location, "->");
Check if location is `NULL` before calling `strstr`

2021-03-19 08:50 UTC, antoniomanuelfr commented on src/analysisd/eventinfo.c
> +        module_name = location;
This line produces the following warning: 
```
analysisd/eventinfo.c: In function 'extract_module_from_location':
analysisd/eventinfo.c:1171:21: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 1171 |         module_name = location;
      |                     ^
    CC analysisd/labels-live.o
```

2021-03-25 09:01 UTC, antoniomanuelfr approved these changes

2021-03-25 17:10 UTC, Molter73 requested changes

2021-04-09 12:01 UTC, JoseAntonioMHerrera submitted a review, later dismissed

2021-04-09 13:02 UTC, jotacarma90 commented
test_analysisd result on Jenkins:
[manager_html_report_test_integration_B1570_20210409101812.zip](https://github.com/wazuh/wazuh/files/6285885/manager_html_report_test_integration_B1570_20210409101812.zip)

2021-04-13 11:30 UTC, antoniomanuelfr submitted a review, later dismissed

2021-06-18 11:49 UTC, vikman90 approved these changes

2021-06-18 11:50 UTC, merged