Change the behavior when changing from realtime to scheduled
wazuh/wazuh pull request #7414
Opened 2021-02-09 08:28 UTC by antoniomanuelfr

|Related issue|
|---|
|#7263|

## Description
This PR aims to fix issue #7263 by changing the behavior when changing from `realtime` to `scheduled` when the system is not compatible with `realtime`.

This PR also changes the function `fim_db_remove_path` to only remove paths from the DB instead of triggering the alerts.

## Configuration options
```xml
<directories realtime="yes">/test</directories>
```

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

2021-02-10 15:17 UTC, Molter73 requested changes
Refactoring of `fim_db_remove_path` is looking great! Keep it up!

2021-02-10 15:17 UTC, Molter73 commented on src/syscheckd/db/fim_db_files.c
> +    return rows;
Returning `rows` here does not make much sense, we should change the function to return `FIMDB_ERR` if any operation fails and `FIMDB_OK` if everything works as planned.

2021-02-10 15:17 UTC, Molter73 commented on src/syscheckd/syscheck.h
> + * @brief Create the delete event and removes the entry from the database.
```suggestion
 * @brief Creates a delete event and removes the entry from the database.
```

2021-02-11 16:50 UTC, Molter73 approved these changes
LGTM!

2021-02-12 07:46 UTC, antoniomanuelfr commented
These are the integration test executed in Jenkins with the latest changes:
[agent_centos_html_report_test_integration_B1245_20210211172108.zip](https://github.com/wazuh/wazuh/files/5970278/agent_centos_html_report_test_integration_B1245_20210211172108.zip)
[agent_macos_html_report_test_integration_B1246_20210211172108.zip](https://github.com/wazuh/wazuh/files/5970280/agent_macos_html_report_test_integration_B1246_20210211172108.zip)
[agent_solaris_html_report_test_integration_B1246_20210211172108.zip](https://github.com/wazuh/wazuh/files/5970281/agent_solaris_html_report_test_integration_B1246_20210211172108.zip)
[agent_ubuntu_html_report_test_integration_B1245_20210211172108.zip](https://github.com/wazuh/wazuh/files/5970283/agent_ubuntu_html_report_test_integration_B1245_20210211172108.zip)
[agent_windows_html_report_test_integration_B1245_20210211172108.zip](https://github.com/wazuh/wazuh/files/5970284/agent_windows_html_report_test_integration_B1245_20210211172108.zip)

2021-02-19 11:23 UTC, Molter73 approved these changes
LGTM!

2021-02-19 13:13 UTC, vikman90 approved these changes

2021-02-19 13:20 UTC, merged