Add test to check RBAC is correctly applied in all endpoints.
wazuh/wazuh pull request #7447
Opened 2021-02-11 12:51 UTC by Selutario

|Related issue|
|---|
| Closes #7385 |

## Description

Hello team,

As requested in #7385, this PR adds a new API tavern test file which tests every Wazuh endpoint. 

The aim is to make sure that, when a user has no permissions, no endpoint can be run under they token. To achieve it:
- A user without assigned roles is created.
- All endpoints are expected to return Error code 4000 or empty list result.

Some tests which do not need RBAC permissions (`GET /`, `GET /security/user/authenticate`, etc), are not included.

## Output
```
pytest -vv test_rbac_white_all_endpoints.tavern.yaml
============================================================================================ test session starts =============================================================================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.2, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.5', 'Platform': 'Linux-5.4.0-65-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.4.3', 'py': '1.8.2', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '1.10.0', 'testinfra': '5.0.0', 'tavern': '1.2.2', 'cov': '2.10.0', 'asyncio': '0.14.0', 'html': '2.0.1'}}
rootdir: /home/selu/Git/wazuh/api/test/integration, inifile: pytest.ini
plugins: metadata-1.10.0, testinfra-5.0.0, tavern-1.2.2, cov-2.10.0, asyncio-0.14.0, html-2.0.1
collected 147 items                                                                                                                                                                                          

test_rbac_white_all_endpoints.tavern.yaml::PUT /active-response PASSED                                                                                                                                 [  0%]
test_rbac_white_all_endpoints.tavern.yaml::DELETE /agents PASSED                                                                                                                                       [  1%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents PASSED                                                                                                                                          [  2%]
test_rbac_white_all_endpoints.tavern.yaml::POST /agents PASSED                                                                                                                                         [  2%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/{agent_id}/config/{component}/{configuration} PASSED                                                                                            [  3%]
test_rbac_white_all_endpoints.tavern.yaml::DELETE /agents/{agent_id}/group PASSED                                                                                                                      [  4%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/{agent_id}/group/is_sync PASSED                                                                                                                 [  4%]
test_rbac_white_all_endpoints.tavern.yaml::DELETE /agents/{agent_id}/group/{group_id} PASSED                                                                                                           [  5%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/{agent_id}/group/{group_id} PASSED                                                                                                              [  6%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/{agent_id}/key PASSED                                                                                                                           [  6%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/{agent_id}/restart PASSED                                                                                                                       [  7%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/upgrade PASSED                                                                                                                                  [  8%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/upgrade_custom PASSED                                                                                                                           [  8%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/upgrade_result PASSED                                                                                                                           [  9%]
test_rbac_white_all_endpoints.tavern.yaml::DELETE /agents/group PASSED                                                                                                                                 [ 10%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/group PASSED                                                                                                                                    [ 10%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/group/{group_id}/restart PASSED                                                                                                                 [ 11%]
test_rbac_white_all_endpoints.tavern.yaml::POST /agents/insert PASSED                                                                                                                                  [ 12%]
test_rbac_white_all_endpoints.tavern.yaml::POST /agents/insert/quick PASSED                                                                                                                            [ 12%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/no_group PASSED                                                                                                                                 [ 13%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/node/{node_id}/restart PASSED                                                                                                                   [ 14%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/outdated PASSED                                                                                                                                 [ 14%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/restart PASSED                                                                                                                                  [ 15%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/stats/distinct PASSED                                                                                                                           [ 16%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/summary/os PASSED                                                                                                                               [ 17%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/summary/status PASSED                                                                                                                           [ 17%]
test_rbac_white_all_endpoints.tavern.yaml::GET /ciscat/{agent_id}/results PASSED                                                                                                                       [ 18%]
test_rbac_white_all_endpoints.tavern.yaml::GET /cluster/local/info PASSED                                                                                                                              [ 19%]
test_rbac_white_all_endpoints.tavern.yaml::GET /cluster/nodes PASSED                                                                                                                                   [ 19%]
test_rbac_white_all_endpoints.tavern.yaml::GET /cluster/healthcheck PASSED                                                                                                                             [ 20%]
test_rbac_white_all_endpoints.tavern.yaml::GET /cluster/local/config PASSED                                                                                                                            [ 21%]
test_rbac_white_all_endpoints.tavern.y [...]

2021-02-12 09:14 UTC, davidjiglesias requested changes
Add specific (403) and generic (200, empty) to all endpoints with said functionality.

2021-02-12 09:14 UTC, davidjiglesias commented on api/test/integration/env/configurations/all/manager/base_security_test.sql
> + * Copyright (C) 2015-2020, Wazuh Inc.
```suggestion
 * Copyright (C) 2015-2021, Wazuh Inc.
```

2021-02-12 09:14 UTC, davidjiglesias commented on api/test/integration/env/configurations/all/manager/base_security_test.sql
> + * February 13, 2019.
```suggestion
 * February 12, 2021.
```

2021-02-12 09:14 UTC, davidjiglesias commented on api/test/integration/env/configurations/all/manager/base_security_test.sql
> + * SQL Schema security tests
```suggestion
 * SQL Schema all denied tests
```

2021-02-12 13:37 UTC, Selutario commented
## Output
```
pytest -vv test_rbac_white_all_endpoints.tavern.yaml
============================================================================================ test session starts =============================================================================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.2, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.5', 'Platform': 'Linux-5.4.0-65-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.4.3', 'py': '1.8.2', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '1.10.0', 'testinfra': '5.0.0', 'tavern': '1.2.2', 'cov': '2.10.0', 'asyncio': '0.14.0', 'html': '2.0.1'}}
rootdir: /home/selu/Git/wazuh/api/test/integration, inifile: pytest.ini
plugins: metadata-1.10.0, testinfra-5.0.0, tavern-1.2.2, cov-2.10.0, asyncio-0.14.0, html-2.0.1
collected 147 items                                                                                                                                                                                          

test_rbac_white_all_endpoints.tavern.yaml::PUT /active-response PASSED                                                                                                                                 [  0%]
test_rbac_white_all_endpoints.tavern.yaml::DELETE /agents PASSED                                                                                                                                       [  1%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents PASSED                                                                                                                                          [  2%]
test_rbac_white_all_endpoints.tavern.yaml::POST /agents PASSED                                                                                                                                         [  2%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/{agent_id}/config/{component}/{configuration} PASSED                                                                                            [  3%]
test_rbac_white_all_endpoints.tavern.yaml::DELETE /agents/{agent_id}/group PASSED                                                                                                                      [  4%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/{agent_id}/group/is_sync PASSED                                                                                                                 [  4%]
test_rbac_white_all_endpoints.tavern.yaml::DELETE /agents/{agent_id}/group/{group_id} PASSED                                                                                                           [  5%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/{agent_id}/group/{group_id} PASSED                                                                                                              [  6%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/{agent_id}/key PASSED                                                                                                                           [  6%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/{agent_id}/restart PASSED                                                                                                                       [  7%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/upgrade PASSED                                                                                                                                  [  8%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/upgrade_custom PASSED                                                                                                                           [  8%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/upgrade_result PASSED                                                                                                                           [  9%]
test_rbac_white_all_endpoints.tavern.yaml::DELETE /agents/group PASSED                                                                                                                                 [ 10%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/group PASSED                                                                                                                                    [ 10%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/group/{group_id}/restart PASSED                                                                                                                 [ 11%]
test_rbac_white_all_endpoints.tavern.yaml::POST /agents/insert PASSED                                                                                                                                  [ 12%]
test_rbac_white_all_endpoints.tavern.yaml::POST /agents/insert/quick PASSED                                                                                                                            [ 12%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/no_group PASSED                                                                                                                                 [ 13%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/node/{node_id}/restart PASSED                                                                                                                   [ 14%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/outdated PASSED                                                                                                                                 [ 14%]
test_rbac_white_all_endpoints.tavern.yaml::PUT /agents/restart PASSED                                                                                                                                  [ 15%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/stats/distinct PASSED                                                                                                                           [ 16%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/summary/os PASSED                                                                                                                               [ 17%]
test_rbac_white_all_endpoints.tavern.yaml::GET /agents/summary/status PASSED                                                                                                                           [ 17%]
test_rbac_white_all_endpoints.tavern.yaml::GET /ciscat/{agent_id}/results PASSED                                                                                                                       [ 18%]
test_rbac_white_all_endpoints.tavern.yaml::GET /cluster/local/info PASSED                                                                                                                              [ 19%]
test_rbac_white_all_endpoints.tavern.yaml::GET /cluster/nodes PASSED                                                                                                                                   [ 19%]
test_rbac_white_all_endpoints.tavern.yaml::GET /cluster/healthcheck PASSED                                                                                                                             [ 20%]
test_rbac_white_all_endpoints.tavern.yaml::GET /cluster/local/config PASSED                                                                                                                            [ 21%]
test_rbac_white_all_endpoints.tavern.yaml::GET /cluster/status PASSED                                                                                                                                  [ 21%]
test_rbac_white_all_endpoints.tavern.yaml::GET /cluster/api/config PASSED                                                                                                                              [ 22%]
test_rbac_white_all_endpoints.tavern.yaml::GET /cluster/{node_id}/status PASSED                                                                        [...]

2021-02-15 10:18 UTC, davidjiglesias approved these changes

2021-02-15 14:56 UTC, davidjiglesias approved these changes

2021-02-15 14:57 UTC, merged