Remoted tcp udp secure connection handler
wazuh/wazuh pull request #7449
Opened 2021-02-11 14:21 UTC by juliancnn

|Related issue|
|---|
|closes #7371|
|closes #7373|

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

2021-02-17 19:11 UTC, nmkoremblum approved these changes
LGTM thanks! :D

2021-02-17 21:54 UTC, jnasselle commented on src/config/remote-config.c
> +            } else if(strcasecmp(word, REMOTED_NET_PROTOCOL_UDP_STR) == 0) {
Add space between `if` and parenthesis

2021-02-17 21:54 UTC, jnasselle commented on src/remoted/manager.c
> +        return (-1);
Remove parenthesis for return value

2021-02-18 10:46 UTC, JcabreraC requested changes

2021-02-18 10:46 UTC, JcabreraC commented on src/config/remote-config.h
> +#define REMOTED_NET_PROTOCOL_TCP_STR "TCP"
The following defines are duplicated:
- REMOTED_PROTO_TCP_STR
- REMOTED_PROTO_UDP_STR
- REMOTED_PROTO_DEFAULT_STR

2021-02-18 11:31 UTC, jnasselle approved these changes

2021-02-18 13:16 UTC, JcabreraC approved these changes

2021-02-18 14:44 UTC, merged