Allow OS Regex match empty strings
wazuh/wazuh pull request #7495
Opened 2021-02-15 13:17 UTC by vikman90

|Related issues|
|---|
|#7386 and #3583|

As explained at https://github.com/wazuh/wazuh/issues/7386#issuecomment-777754563, the basic OS Regex algorithm iterates over the input string to validate the regular expression. Then it validates the empty condition (the regex pattern must be fully consumed).

According to this procedure, if the input string is empty, nothing happens, and hence `_OS_Regex` returns the default value (null). Mind that an empty regex does validate anything, and `^$` (or simply `$`) must only match an empty string.

## Proposed fix

As empty strings are valid, we propose to set the initial result of the regex execution to the input string (valid) instead of `null`).

### Tests

In addition to the currently defined tests, we add the following checks:

|Regex|Input|Result|
|---|---|---|
|`""`|`""`|Match|
|`""`|`""`|Match|
|`""`|`""`|Match|
|`""`|`""`|Match|
|`""`|`""`|Match|

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

2021-02-15 15:34 UTC, Molter73 approved these changes
LGTM!

2021-02-15 15:44 UTC, vikman90 commented
## Ruleset tests

The fix prevents decoder "vsftpd" from matching logs.

### Expected output
```
Starting wazuh-logtest v4.2.0
Type one log per line

Wed Jul 27 18:32:27 2016 [pid 2] CONNECT: Client "fe80::baac:6fff:fe7d:d2e0"

**Phase 1: Completed pre-decoding.
	full event: 'Wed Jul 27 18:32:27 2016 [pid 2] CONNECT: Client "fe80::baac:6fff:fe7d:d2e0"'

**Phase 2: Completed decoding.
	name: 'vsftpd'
	parent: 'vsftpd'
	action: 'CONNECT'
	srcip: 'fe80::baac:6fff:fe7d:d2e0'

**Phase 3: Completed filtering (rules).
	id: '11401'
	level: '3'
	description: 'vsftpd: FTP session opened.'
	groups: '['syslog', 'vsftpd', 'connection_attempt']'
	firedtimes: '1'
	mail: 'False'
**Alert to be generated.
```

### This branch's implementation output

```
Starting wazuh-logtest v4.2.0
Type one log per line

Wed Jul 27 18:32:27 2016 [pid 2] CONNECT: Client "fe80::baac:6fff:fe7d:d2e0"

**Phase 1: Completed pre-decoding.
	full event: 'Wed Jul 27 18:32:27 2016 [pid 2] CONNECT: Client "fe80::baac:6fff:fe7d:d2e0"'

**Phase 2: Completed decoding.
	name: 'pix'
```

2021-02-15 17:18 UTC, vikman90 commented
## PIX decoders

This regex made the decoder match everything:
```
^%PIX-|^\w\w\w \d\d \d\d\d\d \d\d:\d\d:\d\d: %PIX-|
```

## Panda PAPS decoders

The second half of the regexes of this kind made them match the entire log:

```
devTime=(\.*)\t|(\.*)$
```

Fix:
```
devTime=(\.*)\t|devTime=(\.*)
```

Patching 110 occurrences of this issue.

2021-02-15 18:05 UTC, Molter73 requested changes
I think you missed a decoder here:
https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/decoders/0470-panda-paps_decoders.xml#L507

There are also some other instances of regexes with `|` as the ending character that I feel we should remove at the following locations:
https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/decoders/0305-squid_decoders.xml#L46
https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/decoders/0090-dragon-nids_decoders.xml#L17-L24
https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/rules/0585-win-application_rules.xml#L2123-L2130
https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/rules/0585-win-application_rules.xml#L2296-L2301

2021-02-16 10:16 UTC, Molter73 approved these changes
After discussing it with the team, the remaining decoders and rules to be fixed will be dealt with in #7505

2021-02-16 12:12 UTC, merged