Refactor core/manager and common functions
wazuh/wazuh pull request #7497
Opened 2021-02-15 14:54 UTC by vicferpoy

Hello team,
this closes #7148 .

This PR includes the refactor to the core/manager module and all the common functions used in the development. We have common tools now in core/utils that are used across the rules, decoders, files and manager modules. In addition, a major cleanup has been done and we fixed the `expand_resourcess` function to prevent wrong behaviours when trying to expand rules, decoders or cdb lists.

New unit and integration tests have been added. Some outdated ones were removed.

## Tests performed
### Unit tests
```
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.2, pluggy-0.13.1
rootdir: /home/vicferpoy/Desktop/Git/wazuh/framework
plugins: metadata-1.10.0, asyncio-0.12.0, cov-2.10.1, html-2.0.1
collected 1619 items                                                                                                                                                                        

wazuh/core/cluster/dapi/tests/test_dapi.py ......................                                                                                                                     [  1%]
wazuh/core/cluster/tests/test_cluster.py ...................                                                                                                                          [  2%]
wazuh/core/cluster/tests/test_common.py .......                                                                                                                                       [  2%]
wazuh/core/cluster/tests/test_control.py .....                                                                                                                                        [  3%]
wazuh/core/cluster/tests/test_local_client.py .                                                                                                                                       [  3%]
wazuh/core/cluster/tests/test_utils.py .......                                                                                                                                        [  3%]
wazuh/core/cluster/tests/test_worker.py ................                                                                                                                              [  4%]
wazuh/core/tests/test_active_response.py ............                                                                                                                                 [  5%]
wazuh/core/tests/test_agent.py ...................................................................................................................................................... [ 14%]
.                                                                                                                                                                                     [ 14%]
wazuh/core/tests/test_cdb_list.py ......................................                                                                                                              [ 17%]
wazuh/core/tests/test_common.py .......                                                                                                                                               [ 17%]
wazuh/core/tests/test_configuration.py ....................................                                                                                                           [ 19%]
wazuh/core/tests/test_decoder.py ................                                                                                                                                     [ 20%]
wazuh/core/tests/test_input_validator.py ...                                                                                                                                          [ 21%]
wazuh/core/tests/test_logtest.py ..                                                                                                                                                   [ 21%]
wazuh/core/tests/test_manager.py .................                                                                                                                                    [ 22%]
wazuh/core/tests/test_ossec_queue.py ...................                                                                                                                              [ 23%]
wazuh/core/tests/test_pyDaemonModule.py ......                                                                                                                                        [ 23%]
wazuh/core/tests/test_results.py ........................................                                                                                                             [ 26%]
wazuh/core/tests/test_rootcheck.py ..........                                                                                                                                         [ 26%]
wazuh/core/tests/test_rule.py ......................                                                                                                                                  [ 28%]
wazuh/core/tests/test_syscollector.py ...                                                                                                                                             [ 28%]
wazuh/core/tests/test_utils.py ...................................................................................................................................................... [ 37%]
.......................................................................                                                                                                               [ 42%]
wazuh/core/tests/test_wazuh_socket.py ....................                                                                                                                            [ 43%]
wazuh/core/tests/test_wdb.py .....................                                                                                                                                    [ 44%]
wazuh/rbac/tests/test_auth_context.py ..                                                                                                                                              [ 44%]
wazuh/rbac/tests/test_decorators.py .........................................................................................................                                         [ 51%]
wazuh/rbac/tests/test_default_configuration.py .....................................................                                                                                  [ 54%]
wazuh/rbac/tests/test_orm.py .....................................................                                                                                                    [ 57%]
wazuh/rbac/tests/test_preprocessor.py ...........                                                                                                                                     [ 58%]
wazuh/tests/test_active_response.py .........                                                                                                                                         [ 58%]
wazuh/tests/test_agent.py ....................................................................................                                                                        [ 64%]
wazuh/tests/test_cdb_list.py .....................................................                                                                                                    [ 67%]
wazuh/tests/test_ciscat.py ..                                                                                                                                                         [ 67%]
wazuh/tests/test_cluster.py .......                                                    [...]

2021-02-15 16:16 UTC, Selutario approved these changes

2021-02-16 10:23 UTC, davidjiglesias requested changes

2021-02-16 10:23 UTC, davidjiglesias commented on framework/wazuh/core/utils.py
> +def prettify_xml(xml_file):
REMOVE

2021-02-16 10:30 UTC, davidjiglesias approved these changes

2021-02-16 10:30 UTC, merged