Fix API integrtation tests failing in master
wazuh/wazuh pull request #7545
Opened 2021-02-18 13:48 UTC by mcarmona99

|Related issue|
|---|
| #7502 |

Hi team,

This PR closes #7502.

I have updated a lot of API integration tests and healthchecks to avoid random fails in the nightly results in MASTER.

**DECODERS TESTS:**

`q: 'details.prematch.pattern~wazuh'` is failing

After debugging, I have realized the API call returns Wazuh internal error when iterating on an affected item with `prematch.pattern = None`. I have included a condition in the `utils.py` function  `filter_array_by_query` to avoid errors like this one.

**SYSCHECK TESTS:**

The specific healthchecks (in this case syscheck) also need the base healthcheck as the race condition can still appear (and it appears in this specific failed test). I have updated our testing environment to use it.

https://ci.wazuh.info/blue/organizations/jenkins/test_integration_api_endpoints/detail/test_integration_api_endpoints/304/pipeline/5750

With this PR, we will be adding the base healthcheck to the `tmp` folder when we have a specific healthcheck. The base healthcheck will be named `base_healthcheck.py` and we will need to import the `get_manager_health_base` or `get_agent_health_base` functions in the specific module healthcheck in order to use it.

If there is no specific healthcheck, the base healthcheck will be `healthcheck.py`. When the specific module test we are running doesn't need an agents healthcheck, the `base_healthcheck.py` function will be copied into the `tmp` folder but we won't use it.

**ACTIVE RESPONSE TESTS:**

I have changed the `restart-wazuh0` command. We don't need to test always with a restart command as we are only testing the endpoint responses. In this case using `restart-wazuh0` was causing race conditions and failed tests sometimes. I have used `custom` as command.

**SCA TESTS:**

Agents with Wazuh version 4.2.0 have only 1 cis benchamark (they don't have L1 and L2). I have changed all our tests. I have also deleted redundant ones.

**SECURITY_PUT TESTS:**

Fixed with fix to api entrypoint (merged in 4.1)

All security tests passed in jenkins:
https://ci.wazuh.info/job/test_integration_api_endpoints/315/

**ROOTCHECK TESTS:** (failing in 4.1)

https://ci.wazuh.info/blue/organizations/jenkins/test_integration_api_endpoints/detail/test_integration_api_endpoints/310/pipeline

I have added `sort=cis` to avoid this error. By default the endpoint response is sorted by the last scan time, so the position of the cis result in the response could vary.

## TESTS RESULTS:

```
test_active_response_endpoints.tavern.yaml 
	 2 passed, 4 warnings

test_rbac_black_active_response_endpoints.tavern.yaml 
	 2 passed, 4 warnings

test_rbac_white_active_response_endpoints.tavern.yaml 
	 2 passed, 4 warnings

```
```
test_rbac_black_syscheck_endpoints.tavern.yaml 
	 4 passed, 6 warnings

test_rbac_white_syscheck_endpoints.tavern.yaml 
	 4 passed, 6 warnings

test_syscheck_endpoints.tavern.yaml 
	 35 passed, 39 warnings
```

```
test_decoder_endpoints.tavern.yaml 
	 23 passed, 29 warnings

test_rbac_black_decoder_endpoints.tavern.yaml 
	 4 passed, 6 warnings

test_rbac_white_decoder_endpoints.tavern.yaml 
	 4 passed, 6 warnings
```

```
test_rbac_black_sca_endpoints.tavern.yaml 
	 2 passed, 4 warnings

test_rbac_white_sca_endpoints.tavern.yaml 
	 2 passed, 4 warnings

test_sca_endpoints.tavern.yaml 
	 4 passed, 6 warnings
```

```
test_rbac_black_rootcheck_endpoints.tavern.yaml 
	 4 passed, 6 warnings

test_rbac_white_rootcheck_endpoints.tavern.yaml 
	 4 passed, 6 warnings

test_rootcheck_endpoints.tavern.yaml 
	 4 passed, 6 warnings
```

```
test_manager_endpoints.tavern.yaml 
	 33 passed, 36 warnings

test_rbac_black_manager_endpoints.tavern.yaml 
	 17 passed, 19 warnings

test_rbac_white_manager_endpoints.tavern.yaml 
	 17 passed, 19 warnings
```

Regards,
Manuel.

2021-02-22 09:28 UTC, davidjiglesias requested changes
Apply rootcheck, sca and prematch.pattern checks.

2021-02-23 11:45 UTC, mcarmona99 commented
### PR STATUS:

New tests are failing after merging `4.1` into `master`:

```
test_cluster_endpoints.tavern.yaml 
	 12 failed, 32 passed, 1 xpassed, 58 warnings

test_manager_endpoints.tavern.yaml 
	 2 failed, 29 passed, 34 warnings
	 
test_rbac_black_manager_endpoints.tavern.yaml 
	 2 failed, 13 passed, 17 warnings
	 
test_rbac_white_all_endpoints.tavern.yaml 
	 1 failed, 146 passed, 3 xfailed, 152 warnings
```
	 
Test passing:

```
test_cdb_list_endpoints.tavern.yaml 
	 5 passed, 7 warnings

test_decoder_endpoints.tavern.yaml 
	 25 passed, 31 warnings

test_active_response_endpoints.tavern.yaml 
	 2 passed, 4 warnings

test_rbac_black_cdb_list_endpoints.tavern.yaml 
	 5 passed, 7 warnings

test_rbac_white_cdb_list_endpoints.tavern.yaml 
	 5 passed, 7 warnings
	 
test_rbac_black_cluster_endpoints.tavern.yaml 
	 17 passed, 19 warnings

test_rbac_white_cluster_endpoints.tavern.yaml 
	 17 passed, 19 warnings

test_rbac_black_decoder_endpoints.tavern.yaml 
	 6 passed, 8 warnings

test_rbac_white_decoder_endpoints.tavern.yaml 
	 6 passed, 8 warnings

test_rbac_white_manager_endpoints.tavern.yaml 
	 15 passed, 17 warnings
	 
test_rbac_black_rule_endpoints.tavern.yaml 
	 8 passed, 10 warnings

test_rbac_white_rule_endpoints.tavern.yaml 
	 8 passed, 10 warnings

test_rule_endpoints.tavern.yaml 
	 15 passed, 17 warnings
	 
test_rbac_black_cdb_list_endpoints.tavern.yaml 
	 5 passed, 7 warnings

test_rbac_white_cdb_list_endpoints.tavern.yaml 
	 5 passed, 7 warnings
	 
test_security_GET_endpoints.tavern.yaml 
	 18 passed, 21 warnings

```

2021-02-23 13:19 UTC, mcarmona99 commented
After merging `4.1` into `master`, some changes from `ossec` to `wazuh` were reverted, I have made the proprerly changes again.

Test results:

```
test_cluster_endpoints.tavern.yaml 
	 44 passed, 1 xpassed, 58 warnings
	 
test_manager_endpoints.tavern.yaml 
	 31 passed, 34 warnings

test_rbac_black_manager_endpoints.tavern.yaml 
	 15 passed, 17 warnings

test_rbac_white_all_endpoints.tavern.yaml 
	 147 passed, 3 xfailed, 152 warnings
```

These tests are being passed by jenkins here: https://ci.wazuh.info/job/test_integration_api_endpoints/356/

2021-02-23 14:34 UTC, davidjiglesias approved these changes

2021-02-23 14:45 UTC, merged