Add parameters to DELETE /agents. Update tests.
wazuh/wazuh pull request #7577
Opened 2021-02-22 10:53 UTC by Selutario

|Related issue|
|---|
| Closes #6366 |

## Description

Hi team!

This PR adds new parameters to `DELETE /agents` endpoint. Now, it accepts all filters that could be used in `GET /agents`. Therefore, it is now possible to remove agents based on multiple factors, or a combination of all: 
- status
- older_than
- q
- os.platform
- os.version
- os.name
- manager
- version
- node_name
- name
- ip
- registerIP

The error message has also been updated. Now it shows which filters were used as a hint of what might fail. `Status` and `agents_list` parameters are still mandatory.

## Example outputs

> DELETE /agents?agents_list=all&status=all&older_than=0s&os.platform=Windows

```JSON
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 3,
    "failed_items": [
      {
        "error": {
          "code": 1731,
          "message": "Agent is not eligible for removal: some of the requirements are not met -> status: ['all'], older_than: 0s, os.platform: Windows",
          "remediation": "Please, make sure the agent meets the requirements."
        },
        "id": [
          "199",
          "200",
          "201"
        ]
      }
    ]
  },
  "message": "No agents were deleted",
  "error": 1
}
```

> DELETE /agents?agents_list=all&status=all&older_than=0s&q=(group%3Dgroup1,group%3Ddefault)%3Bid%3C6

Multiple groups and conditions can be used, as in this example.
`q=(group=group1,group=default);id<6`
```JSON
{
  "data": {
    "affected_items": [
      "004"
    ],
    "total_affected_items": 1,
    "total_failed_items": 4,
    "failed_items": [
      {
        "error": {
          "code": 1731,
          "message": "Agent is not eligible for removal: some of the requirements are not met -> status: ['all'], older_than: 0s, q: (group=group1,group=default);id<6",
          "remediation": "Please, make sure the agent meets the requirements."
        },
        "id": [
          "006",
          "008",
          "010",
          "012"
        ]
      }
    ]
  },
  "message": "Some agents were not deleted",
  "error": 2
}
```

Regards,
Selu.

2021-03-08 12:10 UTC, davidjiglesias requested changes
Add 1731 to exclude codes

2021-03-24 08:51 UTC, davidjiglesias approved these changes

2021-03-24 09:57 UTC, AdriiiPRodri requested changes

2021-03-24 09:57 UTC, AdriiiPRodri commented on framework/wazuh/agent.py
> +                        extra_message="some of the requirements are not met -> {}".format(
```suggestion
                        extra_message="Some of the requirements are not met -> {}".format(
```

2021-03-24 10:02 UTC, AdriiiPRodri approved these changes

2021-03-24 10:09 UTC, davidjiglesias approved these changes

2021-03-24 10:09 UTC, merged

2023-01-05 11:08 UTC, y0d4a commented
Hi Selutario, i am sorry for writing here, but i have problem with using this options.
I try:
`curl  -k -XDELETE 'https://localhost:55000/agents?status=disconnected&older_than=6h&q=(group=roll)' -H  "Authorization: Bearer $TOKEN"`

and getting:
_{"title": "Bad Request", "detail": "Missing query parameter 'agents_list'"}_

where i am wrong?

thank you