Add new endpoint for users' run_as parameter modification
wazuh/wazuh pull request #7588
Opened 2021-02-23 10:48 UTC by AdriiiPRodri

|Related issue|
|---|
|#6651|

Hi team,

This PR closes #6651. In this PR we have added a new endpoint to enable/disable the run_as parameter of the users.

## Tests

### Unittests
```
adriiiprodri@wazuh pytest -xs  wazuh/tests
=========================================== test session starts ===========================================
platform linux -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/framework
plugins: metadata-1.11.0, html-3.1.1, tavern-1.13.1
collected 707 items                                                                                       

wazuh/tests/test_active_response.py ............
wazuh/tests/test_agent.py ....................................................................................
wazuh/tests/test_cdb_list.py ...............................................
wazuh/tests/test_ciscat.py .................................
wazuh/tests/test_cluster.py .....ss
wazuh/tests/test_decoders.py ...............................
wazuh/tests/test_group.py ........
wazuh/tests/test_logtest.py ......
wazuh/tests/test_manager.py ......................................
wazuh/tests/test_mitre.py ....................................................................................................................................................................................
wazuh/tests/test_rootcheck.py .................................................
wazuh/tests/test_rule.py ....................................................
wazuh/tests/test_sca.py .......
wazuh/tests/test_security.py .........................................................................
wazuh/tests/test_stats.py ................
wazuh/tests/test_syscheck.py ........................
wazuh/tests/test_syscollector.py ............
wazuh/tests/test_task.py ............................

========================= 705 passed, 2 skipped, 17 warnings in 76.24s (0:01:16) ==========================
```
```
adriiiprodri@wazuh pytest -xs  wazuh/core/tests 
=========================================== test session starts ===========================================
platform linux -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/framework
plugins: metadata-1.11.0, html-3.1.1, tavern-1.13.1
collected 647 items                                                                                       

wazuh/core/tests/test_active_response.py ..............
wazuh/core/tests/test_agent.py .........................................................................................................................................................
wazuh/core/tests/test_cdb_list.py .................................
wazuh/core/tests/test_common.py ......{}
wazuh/core/tests/test_configuration.py ..................................
wazuh/core/tests/test_decoder.py ................
wazuh/core/tests/test_input_validator.py ...
wazuh/core/tests/test_logtest.py ..
wazuh/core/tests/test_manager.py ...............................
wazuh/core/tests/test_ossec_queue.py ...................
wazuh/core/tests/test_pyDaemonModule.py ......
wazuh/core/tests/test_results.py ........................................
wazuh/core/tests/test_rootcheck.py ..........
wazuh/core/tests/test_rule.py ......................
wazuh/core/tests/test_stats.py ...
wazuh/core/tests/test_syscollector.py ...
wazuh/core/tests/test_utils.py ..................................................................................................................................................................................................................
wazuh/core/tests/test_wazuh_socket.py ....................
wazuh/core/tests/test_wdb.py .....................

==================================== 647 passed, 12 warnings in 2.85s =====================================
```
```
adriiiprodri@wazuh pytest -xs  wazuh/rbac/tests             
=========================================== test session starts ===========================================
platform linux -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/framework
plugins: metadata-1.11.0, html-3.1.1, tavern-1.13.1
collected 224 items                                                                                       

wazuh/rbac/tests/test_auth_context.py ..
wazuh/rbac/tests/test_decorators.py .........................................................................................................
wazuh/rbac/tests/test_default_configuration.py ....................................................
wazuh/rbac/tests/test_orm.py ......................................................
wazuh/rbac/tests/test_preprocessor.py ...........

=============================== 224 passed, 2 warnings in 248.96s (0:04:08) ===============================
```

### Integration tests
```
adriiiprodri@wazuh python3 run_tests.py -k security -rbac both
Collected tests [6]:
test_rbac_black_security_endpoints.tavern.yaml, test_rbac_white_security_endpoints.tavern.yaml, test_security_DELETE_endpoints.tavern.yaml, test_security_GET_endpoints.tavern.yaml, test_security_POST_endpoints.tavern.yaml, test_security_PUT_endpoints.tavern.yaml

test_rbac_black_security_endpoints.tavern.yaml 
	 25 passed, 27 warnings

test_rbac_white_security_endpoints.tavern.yaml 
	 25 passed, 27 warnings

test_security_DELETE_endpoints.tavern.yaml 
	 15 passed, 17 warnings

test_security_GET_endpoints.tavern.yaml 
	 18 passed, 20 warnings

test_security_POST_endpoints.tavern.yaml 
	 7 passed, 9 warnings

test_security_PUT_endpoints.tavern.yaml 
	 9 passed, 11 warnings
```

2021-02-23 12:18 UTC, davidjiglesias requested changes
What happens with newly created wazuh and wazuh-wui users? They should have allow_run_as enabled, do they?

2021-02-23 12:18 UTC, davidjiglesias commented on framework/wazuh/rbac/tests/test_orm.py
> +    """Check update a user's run_as flag in the database"""
```suggestion
    """Check update a user's allow_run_as flag in the database"""
```

2021-02-23 12:18 UTC, davidjiglesias commented on framework/wazuh/security.py
> +    """Enable/Disable the user's run_as flag
```suggestion
    """Enable/Disable the user's allow_run_as flag
```

2021-02-23 12:18 UTC, davidjiglesias commented on framework/wazuh/security.py
> +        Enable authorization context login method for the new user
```suggestion
        Enable or disable authorization context login method for the specified user
```

2021-02-23 12:18 UTC, davidjiglesias commented on framework/wazuh/security.py
> +    result = AffectedItemsWazuhResult(none_msg='The parameter run_as could not be enabled for the user',
What if we are disabling, instead of enabling? Wrong messages

2021-02-23 12:18 UTC, davidjiglesias commented on framework/wazuh/security.py
> +    result = AffectedItemsWazuhResult(none_msg='The parameter run_as could not be enabled for the user',
```suggestion
    result = AffectedItemsWazuhResult(none_msg=f"The parameter allow_run_as could not be {'enabled' if allow_run_as else 'disabled'} for the user",
```

2021-02-23 12:18 UTC, davidjiglesias commented on framework/wazuh/security.py
> +                                      all_msg='Parameter run_as has been enabled for the user')
```suggestion
                                      all_msg=f"The parameter allow_run_as has been {'enabled' if allow_run_as else 'disabled'} for the user")
```

2021-02-23 12:18 UTC, davidjiglesias commented on framework/wazuh/tests/data/security/rbac_catalog.yml
> +        description: Change the value of the run_as flag for a user
```suggestion
        description: Change the value of the allow_run_as flag for a user
```

2021-02-23 12:18 UTC, davidjiglesias commented on framework/wazuh/tests/data/security/rbac_catalog.yml
> +      security:run_as:
```suggestion
      security:edit_run_as:
```

2021-02-23 12:18 UTC, davidjiglesias commented on framework/wazuh/tests/data/security/rbac_catalog.yml
> +            - security:run_as
```suggestion
            - security:edit_run_as
```

2021-02-23 12:18 UTC, davidjiglesias commented on framework/wazuh/tests/data/security/users_test_cases.yml
> +enable_run_as:
```suggestion
edit_run_as:
```

2021-02-23 14:53 UTC, davidjiglesias approved these changes

2021-03-03 08:34 UTC, davidjiglesias approved these changes

2021-03-09 09:37 UTC, vicferpoy commented
## Status update
Hello team. Some of the API integration tests checks failed but they pass on local machines. We should investigate this in another issue. As for now, these are the results for those tests:

```
Collected tests [4]:
test_rbac_white_sca_endpoints.tavern.yaml, test_rbac_white_syscheck_endpoints.tavern.yaml, test_rbac_white_syscollector_endpoints.tavern.yaml, test_rbac_white_task_endpoints.tavern.yaml


test_rbac_white_sca_endpoints.tavern.yaml 
	 2 passed, 4 warnings

test_rbac_white_syscheck_endpoints.tavern.yaml 
	 4 passed, 6 warnings

test_rbac_white_syscollector_endpoints.tavern.yaml 
	 9 passed, 11 warnings

test_rbac_white_task_endpoints.tavern.yaml 
	 1 passed, 3 warnings

```

Regards,
Víctor Fernández

2021-03-09 09:39 UTC, merged