Add new endpoint to get CVEs by agent. Add tests.
wazuh/wazuh pull request #7647
Opened 2021-02-26 13:00 UTC by Selutario

|Related issue|
|---|
| Closes #7520 |

## Description

Hello team!

As requested in #7520, this PR adds a new endpoint that can be used to query the vulnerabilities of any agent. 

## Use exmaples
### Get first 3 items
```JSON
curl -k -X GET "https://localhost:55000/agents/000/cve?limit=3&pretty=true" -H  "Authorization: Bearer $TOKEN"

{
   "data": {
      "affected_items": [
         {
            "cve": "CVE-2020-27350",
            "version": "1.6.12ubuntu0.1",
            "architecture": "amd64",
            "name": "apt"
         },
         {
            "cve": "CVE-2020-35493",
            "version": "2.30-21ubuntu1~18.04.4",
            "architecture": "amd64",
            "name": "binutils"
         },
         {
            "cve": "CVE-2020-35495",
            "version": "2.30-21ubuntu1~18.04.4",
            "architecture": "amd64",
            "name": "binutils"
         }
      ],
      "total_affected_items": 39,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected vulnerabilities were returned",
   "error": 0
```

### Filter CVE where architecture = amd64
```JSON
curl -k -X GET "https://localhost:55000/agents/000/cve?limit=3&architecture="amd64"&pretty=true" -H  "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "cve": "CVE-2020-27350",
            "version": "1.6.12ubuntu0.1",
            "architecture": "amd64",
            "name": "apt"
         },
         {
            "cve": "CVE-2020-35493",
            "version": "2.30-21ubuntu1~18.04.4",
            "architecture": "amd64",
            "name": "binutils"
         },
         {
            "cve": "CVE-2020-35495",
            "version": "2.30-21ubuntu1~18.04.4",
            "architecture": "amd64",
            "name": "binutils"
         }
      ],
      "total_affected_items": 38,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected vulnerabilities were returned",
   "error": 0
}
```

### Filter architecture = amd64 and version<0.8
```JSON
curl -G --data-urlencode "q=architecture=amd64;version<0.8" -k -X GET "https://localhost:55000/agents/000/cve?limit=3&pretty=true" -H  "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "version": "0.23.9-2",
            "name": "libp11-kit0",
            "architecture": "amd64",
            "cve": "CVE-2020-29361"
         },
         {
            "version": "0.23.9-2",
            "name": "libp11-kit0",
            "architecture": "amd64",
            "cve": "CVE-2020-29362"
         },
         {
            "version": "0.23.9-2",
            "name": "libp11-kit0",
            "architecture": "amd64",
            "cve": "CVE-2020-29363"
         }
      ],
      "total_affected_items": 3,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected vulnerabilities were returned",
   "error": 0
}
```

Regards,
Selu.

2021-03-04 09:10 UTC, davidjiglesias requested changes
CVE files?
vulnerability ossec_conf always?

2021-03-04 09:10 UTC, davidjiglesias commented on api/test/integration/env/configurations/vulnerability/manager/healthcheck/healthcheck.py
> +        "grep -q 'wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '\\''002'\\''' /var/ossec/logs/ossec.log"))
agent 002?

2021-03-04 09:10 UTC, davidjiglesias commented on api/test/integration/test_rbac_black_vulnerability_endpoints.tavern.yaml
> +  - name: Try to get vulnerabilities information for manager (000)
No 000 pls

2021-03-04 09:10 UTC, davidjiglesias commented on api/test/integration/test_rbac_white_all_endpoints.tavern.yaml
> +  - name: Try to get agent 000 vulnerabilities
Same

2021-03-04 09:10 UTC, davidjiglesias commented on api/test/integration/test_rbac_white_vulnerability_endpoints.tavern.yaml
> +  - name: Get vulnerabilities information for manager (000)
Same

2021-03-04 09:10 UTC, davidjiglesias commented on api/test/integration/test_vulnerability_endpoints.tavern.yaml
> +    request: &cve_request_000
Same

2021-03-04 09:10 UTC, davidjiglesias commented on framework/wazuh/core/vulnerability.py
> +class WazuhDBQueryCVE(WazuhDBQuery):
Prefer WazuhDBQueryVulnerability

2021-03-04 09:10 UTC, davidjiglesias commented on framework/wazuh/rbac/default/policies.yaml
> +    description: Allow read agents' vulnerabilities information.
```suggestion
    description: Allow reading agents' vulnerabilities information.
```

2021-03-04 09:10 UTC, davidjiglesias commented on framework/wazuh/tests/data/security/rbac_catalog.yml
> +        description: Allow read agents' vulnerabilities information
```suggestion
        description: Allow reading agents' vulnerabilities information
```

2021-03-04 09:10 UTC, davidjiglesias commented on framework/wazuh/vulnerability.py
> +    db_query = WazuhDBQueryCVE(agent_id=agent_list[0], offset=offset, limit=limit, sort=sort, search=search,
If agent_list is empty, this can return all, careful.

2021-03-04 13:42 UTC, Selutario commented on CHANGELOG.md
> +  - Added new endpoint to get CVEs that affect an agent. ([#7520](https://github.com/wazuh/wazuh/issues/7520))
Changelog update was removed from this PR.

2021-03-08 11:24 UTC, davidjiglesias approved these changes

2021-03-08 14:51 UTC, merged