Clear vuln_cve table on Vulnerability Detector init
wazuh/wazuh pull request #7699
Opened 2021-03-02 00:16 UTC by palaciosjeremias

|Related issue|
|---|
|7698|

## Description
This PR adds the functionality to clear the vuln_cve table of each agent in the manager during the init of Vulnerabilty Detector.
This clear is performed even if Vulnerability Detector is disabled to guarantee that there will be no outdated data on the table.
It also creates the UT for the new function.

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
- [X] Source installation

- Memory tests for Linux
  - [X] Scan-build report

2021-03-02 02:16 UTC, DProvinciani approved these changes
Looks good!

2021-03-02 21:40 UTC, DProvinciani requested changes
According to the discussion that we had with the team, and the behavior that we observed in the Vulnerability Detector restart, we decided to clean the database in two scenarios:

1. During the Vulnerability Detector initialization if it is disabled.
2. Right before running a full scan.

Please, apply changes according to this decision.

2021-03-02 22:06 UTC, palaciosjeremias commented
> According to the discussion that we had with the team, and the behavior that we observed in the Vulnerability Detector restart, we decided to clean the database in two scenarios:
> 
> 1. During the Vulnerability Detector initialization if it is disabled.
> 2. Right before running a full scan.
> 
> Please, apply changes according to this decision.

Done.
The vuln_cve clean is done only when Vulnerability Detector is disabled now.

2021-03-03 00:37 UTC, pereyra-m approved these changes
LGTM!

2021-03-03 01:08 UTC, DProvinciani approved these changes
Looks good!

2021-03-03 01:09 UTC, merged