Fixed returns in the sacl functions to differentiate between errors
wazuh/wazuh pull request #7754
Opened 2021-03-05 10:42 UTC by jotacarma90

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/6419|

## Description

This PR fixes how the functions `check_object_sacl` and `is_valid_sacl` work with the returns values, to make the functionality of error handling more accurate.

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

2021-03-09 10:54 UTC, jotacarma90 commented
Integration test in Jenkins passed:
[agent_ubuntu_html_report_test_integration_B1399_20210305191820.zip](https://github.com/wazuh/wazuh/files/6107935/agent_ubuntu_html_report_test_integration_B1399_20210305191820.zip)
[agent_solaris_html_report_test_integration_B1400_20210305191820 (1).zip](https://github.com/wazuh/wazuh/files/6107937/agent_solaris_html_report_test_integration_B1400_20210305191820.1.zip)
[agent_macos_html_report_test_integration_B1400_20210305191820.zip](https://github.com/wazuh/wazuh/files/6107938/agent_macos_html_report_test_integration_B1400_20210305191820.zip)
[agent_windows_html_report_test_integration_B1399_20210305191820.zip](https://github.com/wazuh/wazuh/files/6107939/agent_windows_html_report_test_integration_B1399_20210305191820.zip)
[agent_centos_html_report_test_integration_B1399_20210305191820.zip](https://github.com/wazuh/wazuh/files/6107940/agent_centos_html_report_test_integration_B1399_20210305191820.zip)

There are some failures in the Ubuntu build, they should not since the changes only affect Windows. Reviewing.

2021-03-09 15:29 UTC, Molter73 requested changes
It would be greatly appreciated if we could add doxygen documentation to the functions being modified. They return integers and is a little hard to follow exactly what each number is supposed to mean. Other than that and a minor refactor, the PR is looking good.

2021-03-09 15:29 UTC, Molter73 commented on src/syscheckd/whodata/win_whodata.c
> +    switch (is_valid_sacl(old_sacl, (syscheck.wdata.dirs_status[position].object_type == WD_STATUS_FILE_TYPE) ? 1 : 0)) {
I know this was not changed in this PR but is really hard to understand, could we refactor it to something like this? The definition of `is_file` can be moved up in the function.
```suggestion
    int is_file = syscheck.wdata.dirs_status[position].object_type == WD_STATUS_FILE_TYPE) ? 1 : 0;
    
    switch (is_valid_sacl(old_sacl, is_file) {
```

2021-03-30 14:49 UTC, Molter73 submitted a review, later dismissed
The PR is looking good, just a minor style change and a fix in a doxygen description. The PR might need a rebase to pass Jenkins tests but other than that, it should be good to go.

2021-04-09 08:46 UTC, jotacarma90 commented
Integration test on Jenkins:
[agent_windows_html_report_test_integration_B1562_20210408160638.zip](https://github.com/wazuh/wazuh/files/6284376/agent_windows_html_report_test_integration_B1562_20210408160638.zip)
[agent_ubuntu_html_report_test_integration_B1562_20210408160638.zip](https://github.com/wazuh/wazuh/files/6284377/agent_ubuntu_html_report_test_integration_B1562_20210408160638.zip)
[agent_centos_html_report_test_integration_B1562_20210408160638.zip](https://github.com/wazuh/wazuh/files/6284378/agent_centos_html_report_test_integration_B1562_20210408160638.zip)

2021-04-09 11:44 UTC, JoseAntonioMHerrera approved these changes

2021-04-15 10:29 UTC, merged