Use jsonschema validator for API config
wazuh/wazuh pull request #7803
Opened 2021-03-09 13:05 UTC by Selutario

|Related issue|
|---|
| Closes #7195 |

## Description

Hello team!

As explained in #7195, currently only first level keys in the API (and security) configuration were validated. Therefore, things like below were incorrectly allowed:
```YAML
 https:
     new_invalid_option: "whatever"
```

JSONschema has been used in order to specify the accepted config structure, so anything different (at any level), will raise an exception like this:
```
Configuration not valid: 2000 - Some parameters are not expected in the configuration file (WAZUH_PATH/api/configuration/api.yaml): Additional properties are not allowed ('invalid_option' was unexpected).
```

In order to keep consistency with the default configuration dicts shown below, those are validated too against the schema when starting Wazuh:
https://github.com/wazuh/wazuh/blob/49f89fa9b92f062fba21627b599222387db7b740/api/api/configuration.py#L22-L71

## API tests output
```
python3 -m pytest api/api/ --disable-warnings
=================================================== test session starts ===================================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/selu/Git/wazuh/api
plugins: trio-0.6.0, asyncio-0.14.0
collected 180 items                                                                                                       

api/api/test/test_alogging.py ........                                                                              [  4%]
api/api/test/test_authentication.py ..........                                                                      [ 10%]
api/api/test/test_configuration.py .......                                                                          [ 13%]
api/api/test/test_util.py ...................................                                                       [ 33%]
api/api/test/test_validator.py .................................................................................... [ 80%]
....................................                                                                                [100%]

============================================ 180 passed, 16 warnings in 1.01s =============================================
```

Regards!
Selu.

2021-03-12 08:14 UTC, davidjiglesias approved these changes

2021-03-15 08:27 UTC, davidjiglesias requested changes
Add more cases to wrong config.
Add complete parametrized test to json_schema

2021-03-16 09:54 UTC, davidjiglesias approved these changes

2021-03-16 11:13 UTC, vicferpoy approved these changes
LGTM!

2021-03-16 12:05 UTC, davidjiglesias approved these changes

2021-03-16 12:05 UTC, merged