[7758] AStyle coding style tool added as part of RTR tool
wazuh/wazuh pull request #7812
Opened 2021-03-09 21:32 UTC by tinachoB

|Related issue|
|---|
|Closes #7758 |

## **Description**
This issue aims to be able to add a code style checker, this with enough configuration, will automatically help to respect certain standards defined in the project's [C++ coding style](https://github.com/wazuh/wazuh/wiki/Coding-style-guide-(C-plus-plus)).

In this way, do not open new code that does not comply with what is defined.

**URL:** http://astyle.sourceforge.net/

**Wazuh-jenkins related issue:** https://github.com/wazuh/wazuh-jenkins/issues/2419

## **DoD**
- [X] Update of rtr tool
- [X] Update Readme.md with new options
- [X] RTR tool execution with new flag
![image](https://user-images.githubusercontent.com/22640902/110540300-16118a80-8105-11eb-9fca-9bdff56bcab1.png)
- [ ] CI PASS

2021-03-10 15:06 UTC, Dwordcito requested changes

2021-03-11 11:51 UTC, tinachoB commented on src/data_provider/src/ports/portLinuxWrapper.h
> +constexpr auto IPv6AddressHexSize
Will do

2021-03-11 11:51 UTC, tinachoB commented on src/data_provider/src/sysInfoMac.cpp
>              if (ports["ports"].end() == std::find_if(ports["ports"].begin(), ports["ports"].end(),
Yes. Will fix it in my next commit.

2021-03-11 11:52 UTC, tinachoB commented on src/shared_modules/dbsync/tests/interface/dbsync_test.cpp
> +                               };
Yes. Will fix it in my next commit.

2021-03-11 11:52 UTC, tinachoB commented on src/shared_modules/dbsync/tests/interface/dbsync_test.cpp
> +                               };
Yes. Will fix it in my next commit.

2021-03-11 11:52 UTC, tinachoB commented on src/shared_modules/dbsync/tests/pipelineFactory/dbsyncPipelineFactory_test.cpp
> +    [](ReturnTypeCallback, const nlohmann::json&) {}),
Yes. Will fix it in my next commit.

2021-03-11 11:52 UTC, tinachoB commented on src/shared_modules/dbsync/tests/pipelineFactory/dbsyncPipelineFactory_test.cpp
> +    [](ReturnTypeCallback, const nlohmann::json&) {}),
Yes. Will fix it in my next commit.

2021-03-11 11:52 UTC, tinachoB commented on src/shared_modules/utils/tests/pipelineNodes_test.cpp
> +        {
Yes. Will fix it in my next commit.

2021-03-11 13:43 UTC, Dwordcito commented on src/data_provider/src/sysInfoWin.cpp
> +    2
this could be one line constexpr ?

2021-03-11 13:45 UTC, Dwordcito commented on src/shared_modules/dbsync/include/db_exception.h
> +    std::make_pair(1, "Unspecified type during factory instantiation")
this could be one line consexpr ?

2021-03-12 13:16 UTC, tinachoB commented on src/data_provider/src/sysInfoWin.cpp
> +    2
Yes. I'll do it

2021-03-12 13:58 UTC, tinachoB commented on src/shared_modules/dbsync/include/db_exception.h
> +    std::make_pair(1, "Unspecified type during factory instantiation")
Yes. I'll do it

2021-05-17 13:31 UTC, tinachoB commented
@Dwordcito  - Please re check this. Thanks!

2021-05-17 14:40 UTC, konangc87 approved these changes

2021-05-21 16:27 UTC, Dwordcito approved these changes

2021-05-21 17:04 UTC, merged