Adapt data provider to work with Arch Linux packages
wazuh/wazuh pull request #7838
Opened 2021-03-10 17:36 UTC by alromeros

|Related issue|
|---|
|#7764|

## Description

Hi team,

This PR aims to modify the **Syscollector**'s data provider to work with **Arch Linux** packages. In order to accomplish that goal, two main goals have been met:

- Data provider supports **Arch**'s **pacman** package inventory.
- _Unit tests_ are updated to cover the new code for the data provider.

## Configuration options

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
- [ ] Source installation
- [ ] Source upgrade

2021-04-06 10:36 UTC, chemamartinez requested changes

2021-04-06 15:34 UTC, chemamartinez approved these changes

2021-04-06 17:46 UTC, konangc87 requested changes

2021-04-06 17:46 UTC, konangc87 commented on src/data_provider/src/packages/packagesLinuxParserHelper.h
> +        alpm_pkg_t* pkg{reinterpret_cast<alpm_pkg_t*>(item->data)};
I believe this can be const auto (if alpm_pkg_getxx are const correct).

2021-04-06 17:46 UTC, konangc87 commented on src/data_provider/src/packages/packagesLinuxParserHelper.h
> +        auto alpmWrapper
can this be static const?

2021-04-06 17:46 UTC, konangc87 commented on src/data_provider/src/sysInfoLinux.cpp
>      BerkeleyRpmDBReader db(std::make_shared<BerkeleyDbWrapper>(RPM_DATABASE));
use {} initializer

2021-04-06 17:46 UTC, konangc87 commented on src/data_provider/src/sysInfoLinux.cpp
>      for (std::string row = db.getNext() ; !row.empty() ; row = db.getNext())
use {} initializer instead of =

2021-04-06 17:46 UTC, konangc87 commented on src/data_provider/tests/sysInfoPackagesLinuxHelper/sysInfoPackagesLinuxHelper_test.cpp
> +    const std::unique_ptr<__alpm_list_t>    spMock{new struct __alpm_list_t};
prefer using const auto spMock{std::make_unique<__alpm_xx_t>()}

2021-04-06 17:46 UTC, konangc87 commented on src/data_provider/tests/sysInfoPackagesLinuxHelper/sysInfoPackagesLinuxHelper_test.cpp
> +    EXPECT_EQ("firefox", jsPackageInfo["name"]);
you can use the constexpr defined above instead of literals.

2021-04-06 17:46 UTC, konangc87 commented on src/data_provider/tests/sysInfoPackagesLinuxHelper/sysInfoPackagesLinuxHelper_test.cpp
> +    const std::unique_ptr<__alpm_list_t>    spMock{new struct __alpm_list_t};
same comment about const auto make_unique

2021-04-06 17:46 UTC, konangc87 commented on src/data_provider/tests/sysInfoPackagesLinuxHelper/sysInfoPackagesLinuxHelper_test.cpp
> +    const std::unique_ptr<__alpm_list_t>    spMock{new struct __alpm_list_t};
same comment about const auto make_unique

2021-04-06 17:51 UTC, tinachoB requested changes

2021-04-06 17:51 UTC, tinachoB commented on src/data_provider/tests/sysInfoPackagesLinuxHelper/sysInfoPackagesLinuxHelper_test.cpp
> +    spData->groups->next  = NULL;
Please, use `nullptr` instead of `NULL` in all needed cases

2021-04-07 05:09 UTC, Dwordcito requested changes
Good Job, some minor changes.

Regarding CI Checks:
https://github.com/wazuh/wazuh/pull/7838/checks?check_run_id=2279508231 -> you need move to line 335 in https://github.com/wazuh/wazuh/blob/7764-adapt-data-provider-archlinux/src/data_provider/cppcheckSuppress.txt

for everything that is not Linux, we should not try not to include alpm in the cmake and neither in the makefile. this should cause the problems in solaris. 

for compilation errors in linux in ci, possibly the problem is that they compiled the dependencies(libarchive) with a very new version of gcc / glibc, try something a little earlier, since in CI they use for some old environments:
```
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 5.5.0
```

Congratulations Alvaro !! continue like this!

2021-04-07 11:34 UTC, konangc87 reviewed
In UTs there's no need to use smart pointers to hold the mocking structs.

2021-04-08 21:51 UTC, konangc87 requested changes

2021-04-08 21:51 UTC, konangc87 commented on src/data_provider/tests/sysInfoPackagesLinuxHelper/sysInfoPackagesLinuxHelper_test.cpp
> +    __alpm_pkg_t   data;
use default {} initializer with plain old data structs

2021-04-08 21:51 UTC, konangc87 commented on src/data_provider/tests/sysInfoPackagesLinuxHelper/sysInfoPackagesLinuxHelper_test.cpp
> +    const auto      spDataFourthGroup {std::make_unique<__alpm_list_t>()};
no need to be a smart pointer, can be a local var.

2021-04-08 21:51 UTC, konangc87 commented on src/data_provider/tests/sysInfoPackagesLinuxHelper/sysInfoPackagesLinuxHelper_test.cpp
> +    const auto      spDataGroups {std::make_unique<__alpm_list_t>()};
no need to be a smart pointer, can be a local var.

2021-04-08 21:51 UTC, konangc87 commented on src/data_provider/tests/sysInfoPackagesLinuxHelper/sysInfoPackagesLinuxHelper_test.cpp
> +    const auto     spDataGroups {std::make_unique<__alpm_list_t>()};
no need to be a smart pointer, can be a local var.

2021-04-08 21:51 UTC, konangc87 commented on src/data_provider/tests/sysInfoPackagesLinuxHelper/sysInfoPackagesLinuxHelper_test.cpp
> +    __alpm_pkg_t    data;
use default {} initializer with plain old data structs

2021-04-08 21:51 UTC, konangc87 commented on src/data_provider/tests/sysInfoPackagesLinuxHelper/sysInfoPackagesLinuxHelper_test.cpp
> +    __alpm_pkg_t    data;
use default {} initializer with plain old data structs

2021-04-08 22:00 UTC, tinachoB approved these changes
LGTM!

2021-04-08 22:08 UTC, Dwordcito approved these changes

2021-04-09 08:40 UTC, merged

2021-04-09 08:41 UTC, chemamartinez commented
Thank you @Dwordcito , @tinachoB and @konangc87 for your useful review and tips!