4227 syslog hostnames
wazuh/wazuh pull request #7885
Opened 2021-03-16 16:16 UTC by jotacarma90

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/4227|

## Description
This PR adds the option to configure syslog_output with a hostname instead of the IP.
I removed the chroot from the **csyslogd** daemon, used the `resolveHostname` function to get the IP, and created a function, `get_ip_from_resolvedHostname`, that extracts the IP from the format returned by `resolveHostname`.
I also added extra functionality in `OS_Alert_SendSyslog` and `OS_Alert_SendSyslog_JSON` to try to reconnect to the socket at least one more time if it shows as disconnected.

2021-03-25 11:54 UTC, antoniomanuelfr commented on src/shared/os_utils.c
> +}
```suggestion
    char ip_str[128] = {0};
    if (f_ip) {
        snprintf(ip_str, 127, "%s/%s", *hostname, f_ip);
        free(f_ip);
    } else {
        snprintf(ip_str, 127, "%s/", *hostname);
    }
    free(*hostname);
    os_strdup(ip_str, *hostname);
}

```

2021-03-26 12:40 UTC, antoniomanuelfr approved these changes
LGTM

2021-03-29 18:29 UTC, Molter73 requested changes
`src/wazuh-logtest-legacy` should not be part of this PR, please remove it.

We should also add unit tests to `resolveHosname` and `get_ip_from_resolved_hostname`.

2021-03-31 18:45 UTC, Molter73 approved these changes
LGTM!

2021-04-07 08:08 UTC, antoniomanuelfr approved these changes

2021-04-12 16:59 UTC, merged