Verify inodes saved on FIM DB before updating file data
wazuh/wazuh pull request #7990
Opened 2021-03-23 17:39 UTC by Molter73

|Related issue|
|---|
|#7829|

## Description

This PR closes #7829.

A method for preventing files that have had their inodes changed from overwriting metadata from other files has been put in place. This method consists of validating that the dev/inode pair read from the file system is either the same as the file had on the previous scan or the inode obtained is not being used by another file. In case the inode is being used by another file, we scan those files first to find one that has an inode that meets the previous requirements.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
- [x] Source installation
- [x] Source upgrade
- [x] Review logs syntax and correct language
- [x] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Dr. Memory

- [x] Added unit tests (for new features)

2021-03-24 14:29 UTC, Molter73 commented
Scan-build has found a defect on agent and server compilations, but it is not due to the changes in this PR.
[scan-build-agent.zip](https://github.com/wazuh/wazuh/files/6198000/scan-build-agent.zip)
[scan-build-server.zip](https://github.com/wazuh/wazuh/files/6198001/scan-build-server.zip)

2021-03-25 09:18 UTC, jotacarma90 requested changes

2021-03-25 09:18 UTC, jotacarma90 commented on src/syscheckd/create_db.c
>      fim_file_data * data = NULL;
```suggestion
fim_file_data *fim_get_data(const char *file, const fim_element *item) {
    fim_file_data *data = NULL;
```

2021-03-25 09:27 UTC, Molter73 commented on src/syscheckd/db/fim_db_files.c
> +    os_calloc(2, sizeof(char *), paths);
Allocating 1 or 2 pointers is not a major difference in memory usage. Additionally, if the allocated memory is the same as the one being reallocated GNU libc will return the same block, saving us 1 realloc operation.

2021-03-25 09:56 UTC, jotacarma90 submitted a review, later dismissed

2021-03-25 11:33 UTC, Molter73 commented
Integration tests on realtime and whodata mode have passed without any failures:
[agent_centos_html_report_test_integration_B1492_20210324124116.zip](https://github.com/wazuh/wazuh/files/6204267/agent_centos_html_report_test_integration_B1492_20210324124116.zip)
[agent_ubuntu_html_report_test_integration_B1492_20210324124116.zip](https://github.com/wazuh/wazuh/files/6204268/agent_ubuntu_html_report_test_integration_B1492_20210324124116.zip)
[agent_windows_html_report_test_integration_B1492_20210324124116.zip](https://github.com/wazuh/wazuh/files/6204269/agent_windows_html_report_test_integration_B1492_20210324124116.zip)

When run on scheduled, Centos and Ubuntu show errors on the synchronization of the FIM DB, but when those same tests are run independently they pass correctly. Looks like a problem in my environment.
[agent_centos_inodes.zip](https://github.com/wazuh/wazuh/files/6204299/agent_centos_inodes.zip)
[agent_ubuntu_inodes.zip](https://github.com/wazuh/wazuh/files/6204305/agent_ubuntu_inodes.zip)

2021-03-25 16:17 UTC, jotacarma90 approved these changes

2021-03-26 17:39 UTC, merged