Change the way we obtain the Wazuh revision
wazuh/wazuh pull request #8082
Opened 2021-03-31 14:47 UTC by CarlosRS9

Hello team,

This PR closes #7522. The `DatabaseManager.get_api_revision` function from the `orm` has been removed. The current API revision will be obtained from `common.get_wazuh_revision` instead, which uses `wazuh-control info` to obtain this information instead of having to load the `spec.yaml` to get this information.

To ensure we have the right permissions to read the Wazuh revision from the `wazuh-control` we had call this function before dropping the privileges from `root` to `ossec` in `wazuh-apid`.

**Note: Jenkins integration tests will fail until the #8037 is merged.** This is not related to the changes introduced in this PR but a problem with the dependencies.

## Tests results

2021-04-05 07:48 UTC, davidjiglesias requested changes
common.get_wazuh_revision() can return  "ERROR", I would like to handle this case. We can print a message in API log saying there was an error obtaining current version, and the database will remain unchanged for this restart.

2021-04-12 14:50 UTC, vicferpoy approved these changes
LGTM!

2021-04-13 08:30 UTC, davidjiglesias requested changes

2021-04-13 08:30 UTC, davidjiglesias commented on api/scripts/wazuh-apid.py
> -    # Load the SPEC file into memory to use as a reference for future calls
Do not remove

2021-04-13 08:38 UTC, CarlosRS9 commented on api/scripts/wazuh-apid.py
> -    # Load the SPEC file into memory to use as a reference for future calls
Restored

2021-04-13 09:16 UTC, davidjiglesias approved these changes

2021-04-13 09:16 UTC, merged