Fix agent add manual race condition and thread lock
wazuh/wazuh pull request #8148
Opened 2021-04-07 15:29 UTC by davidjiglesias

Hello team,

This PR closes #8122. It adds several fixes to improve `add_manual` and `remove_manual` framework functions to avoid race conditions among threads. It also uses a better approach to `client.keys.tmp` handling. Lastly, an unique `ThreadpoolExecutor` is used for the wazuh-apid process.

Regards,

David J. Iglesias

2021-04-07 15:54 UTC, AdriiiPRodri requested changes

2021-04-07 15:54 UTC, AdriiiPRodri commented on api/api/authentication.py
> +from concurrent.futures import ThreadPoolExecutor
This import can be optimized

2021-04-07 15:54 UTC, AdriiiPRodri commented on framework/wazuh/core/agent.py
> +                if not is_authd_running:
```suggestion
            if use_only_authd and not is_authd_running:
```

2021-04-07 15:54 UTC, AdriiiPRodri commented on framework/wazuh/core/agent.py
> +            raise WazuhError(1757, extra_message=str(e))
Maybe this WazuhError should be a WazuhInternalError?

2021-04-07 16:12 UTC, AdriiiPRodri approved these changes

2021-04-07 17:26 UTC, vikman90 approved these changes

2021-04-08 09:26 UTC, vicferpoy approved these changes
LGTM!

2021-04-09 09:02 UTC, merged