Implement triggers for vuln det scans
wazuh/wazuh pull request #8154
Opened 2021-04-07 22:32 UTC by palaciosjeremias

|Related issue|
|---|
|#7924|

## Description
This PR implements the triggers to decide if Vulnerability Detector must generate a BASELINE_SCAN, a PARTIAL_SCAN or a FULL_SCAN.
The BASELINE_SCAN is performed when vuln_det is enabled for the first time and LAST_FULL_SCAN is 0.
The FULL_SCAN is performed when there is a change in the feed related to the scanned agent and the minimum time for full_scans is reached.
The PARTIAL_SCAN is done as the default action.

- Compilation without warnings in every supported platform
  - [ ] Linux
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Valgrind (memcheck and descriptor leaks check)

2021-04-08 16:03 UTC, palaciosjeremias commented
Scan-build test:
![image](https://user-images.githubusercontent.com/11434230/114059490-cc829f80-986a-11eb-8fb2-79b6c880b0f1.png)

2021-04-08 16:11 UTC, palaciosjeremias commented
Valgrind on UT:
![image](https://user-images.githubusercontent.com/11434230/114060051-5df21180-986b-11eb-8be1-f95c140d28a8.png)

2021-04-08 21:35 UTC, pereyra-m commented on src/wazuh_db/schema_agents.sql
> +INSERT INTO vuln_metadata (LAST_PARTIAL_SCAN, LAST_FULL_SCAN, HOTFIX_SCAN_ID)
Same comment about the column types.

2021-04-08 21:45 UTC, pereyra-m approved these changes
LGTM!

2021-04-09 20:54 UTC, palaciosjeremias commented on src/wazuh_db/schema_upgrade_v8.sql
> +    SELECT '0', '0', '0' WHERE NOT EXISTS (
You are right. This is legacy and looks like it works anyway. But these values should be **0** as an integer.
Fixed

2021-04-09 20:54 UTC, palaciosjeremias commented on src/wazuh_db/schema_agents.sql
> +INSERT INTO vuln_metadata (LAST_PARTIAL_SCAN, LAST_FULL_SCAN, HOTFIX_SCAN_ID)
Fixed

2021-04-12 13:39 UTC, DProvinciani requested changes
Please, apply changes according to the comments.

2021-04-12 13:39 UTC, DProvinciani commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
> +STATIC bool wm_vuldet_feed_changed (update_node** feeds, scan_agent* agent, time_t last_scan);
```suggestion
STATIC bool wm_vuldet_feed_changed(update_node** feeds, scan_agent* agent, time_t last_scan);
```

2021-04-12 17:48 UTC, DProvinciani approved these changes
Looks good!

2021-04-12 17:48 UTC, merged