[8028] execd as wazuh module
wazuh/wazuh pull request #8245
Opened 2021-04-17 03:31 UTC by tinachoB

|Related issue|
|---|
|Closes #8028 |

## **Description**
This issue points to the unification of processes on the agent side, in which it aims to only have wazuh-agentd and wazuh-modulesd.

One of the biggest challenges here is to decompose the main of the old module, separating what is the initialization, from the main processing loop, as well as the rearrangement of the configuration reading.

For this type of modification, the main thing is to normalize the module, to maintain the structure and design of wazuh-modulesd, as it is used in the pre-existing modules.

## **DoD**
- [x] Remove process from installation.
- [x] Add to makefile wazuh-modulesd rule, the dependency of execd compilation.
- [x] Expose methods (Mainloop, read config, communication, shutdown).
- [x] Normalize configuration and read this.
- [x] Initialize module and call the main loop.
- [ ] Fix unit tests
- [ ] PR CI Pass

2021-04-19 11:52 UTC, konangc87 requested changes

2021-04-19 11:52 UTC, konangc87 commented on src/shared/wmodules_health_status.c
> +        const char *jsonErrPtr;
unused variable.

2021-04-19 11:52 UTC, konangc87 commented on src/wazuh_modules/wm_execd.c
> +int wm_execd_message(const char *data);
not needed.

2021-04-22 10:49 UTC, konangc87 approved these changes

2021-04-22 14:38 UTC, Dwordcito requested changes

2021-04-22 14:38 UTC, Dwordcito commented on src/config/wmodules-config.c
> +    else if (!strcmp(node->values[0], WM_EXECD_CONTEXT.name)) {
Hi, this is used?

2021-04-22 14:38 UTC, Dwordcito commented on src/logcollector/read_win_event_channel.c
> +                channel->evt_log, wprovider_name);
Revert this!

2021-04-22 14:38 UTC, Dwordcito commented on src/os_execd/execd.h
> + *
AMAZING!

2021-04-22 14:38 UTC, Dwordcito commented on src/shared/wmodules_health_status.c
> +            mdebug2("Parse JSON error '%s'", msg);
jsonErrPtr could be used here!

2021-04-22 14:41 UTC, tinachoB commented on src/config/wmodules-config.c
> +    else if (!strcmp(node->values[0], WM_EXECD_CONTEXT.name)) {
Nope. I'll remove this!

2021-04-22 14:41 UTC, tinachoB commented on src/logcollector/read_win_event_channel.c
> +                channel->evt_log, wprovider_name);
Will do.

2021-04-22 14:43 UTC, tinachoB commented on src/shared/wmodules_health_status.c
> +            mdebug2("Parse JSON error '%s'", msg);
will do.

2021-04-22 15:19 UTC, Dwordcito approved these changes

2021-04-22 15:26 UTC, merged