Duplicated modification alerts about the same 32-bit registry in windows agent
wazuh/wazuh pull request #8256
Opened 2021-04-19 12:35 UTC by JoseAntonioMHerrera

|Related issue|
|---|
|#6797|

## Description

The statement evaluating the new registry entry readed from syscheck module in ossec.conf was changed from strcmp to strcasecmp to avoid duplicated entries being monitored and generating duplicated alerts due to windows being case insensitive. 

## Tests
- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [X] Source installation

- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory

2021-04-26 12:25 UTC, antoniomanuelfr submitted a review, later dismissed
LGTM

2021-04-27 14:14 UTC, Molter73 requested changes
When configuring more than one entry to the same key with different case, we are correctly replacing the configuration but the entry keeps being displayed with the case of the first configured entry, which can be a little confusing.

We should add the necessary code so that the path correctly reflects the entry that is actually being used.

2021-05-05 12:45 UTC, Molter73 submitted a review, later dismissed
LGTM!

2021-06-29 10:01 UTC, Molter73 approved these changes

2021-08-19 11:02 UTC, antoniomanuelfr approved these changes
LGTM

2021-09-16 12:00 UTC, merged