8045 scanbuild in rtr
wazuh/wazuh pull request #8289
Opened 2021-04-20 14:30 UTC by konangc87

|Related issue|
|---|
| #8045 |

## Description
This PR aims to add the scan-build option to the RTR tool. It performs all the necessary steps to build the specified target (agent, server, winagent) and run the scan build analysis tool on it.

2021-04-20 19:09 UTC, tinachoB requested changes

2021-04-20 19:09 UTC, tinachoB commented on src/ci/utils.py
> +    makeDeps(targetName)
For Windows, you should use the new argument added (`make deps EXTERNAL_SRC_ONLY=yes`) to get non-compiled libraries.

2021-04-21 03:01 UTC, tinachoB approved these changes
LGTM!

2021-04-21 05:04 UTC, Dwordcito approved these changes

2021-04-21 05:04 UTC, merged