Add Solarwinds rules and tests
wazuh/wazuh pull request #8296
Opened 2021-04-20 18:15 UTC by juanrricci

|Related issue|
|---|
|Closes #7226|

## Description
This PR is meant to add decoders, rules and tests for Supernova trojan detection.

## Tests
- Compilation without warnings in every supported platform
  - [ ] Linux
- [ ] Source installation
- [ ] Added unit tests (runtests.py)

2021-06-16 14:03 UTC, fabamatic requested changes

2021-06-16 14:31 UTC, NicoGuini reviewed
Comments made

2021-06-16 14:31 UTC, NicoGuini commented on ruleset/rules/0715-solarwinds_rules.xml
> +    <description>Supernova trojan detected in $(win.eventdata.imageLoaded) library.</description>
I'd set description field after  if_sid tag. This will help to read the target 1st and then the behavior.

2021-06-16 14:31 UTC, NicoGuini commented on ruleset/rules/0715-solarwinds_rules.xml
> +      <id>T1587</id>
I'd not agree to set a subtechnique and a technique at the same time. If can match to different subtechniques, just list them... if it matches all or none, just use the technique id

2021-06-16 14:31 UTC, NicoGuini commented on ruleset/rules/0715-solarwinds_rules.xml
> +      <id>T1588</id>
All these techniques are part of PRE-Attack matrix... Do we really want to have pre-attack techniques?

2021-06-16 14:31 UTC, NicoGuini commented on ruleset/rules/0715-solarwinds_rules.xml
> +  <rule id="66500" level="12">
Why not lvl 15?

2021-09-24 10:38 UTC, 72nomada commented
Moved to MITRE related issues

2021-09-24 10:38 UTC, closed without merging