Let wcom execute check-manager-config query.
wazuh/wazuh pull request #8357
Opened 2021-04-26 06:59 UTC by antoniomanuelfr

|Related issue|
|---|
|#8356|

## Description
This PR aims to avoid `execd` to execute API requests. Now, the requests that were executed by `execd` will be executed by the `wcom` thread. This will avoid the problems described in #7968 once this development is completed.

If the `check-manager-config` request is sent to execd after the change, the following error will appear:
```
2021/04/26 06:57:29 wazuh-execd: ERROR: (1311): Invalid command name 'check-manager-configuration' provided.
```

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
- [X] Source installation
- [ ] Source upgrade

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer

2021-04-26 17:51 UTC, Molter73 requested changes

2021-04-26 17:51 UTC, Molter73 commented on src/os_execd/wcom.c
> +            os_calloc(size + 1, sizeof(char), msg);
What happens if the for loop has run once or twice before failing and calling this `os_calloc`? I believe the `wm_strcat`call in line 346 could have allocated memory and stored it in `msg`, making this call a memory leak.

We should try to rethink how we handle this case, memory leak aside, it's a little messy and hard to follow.

2021-04-28 15:53 UTC, Molter73 submitted a review, later dismissed
LGTM!

2021-04-30 10:41 UTC, Molter73 submitted a review, later dismissed

2021-05-12 14:59 UTC, vikman90 approved these changes

2021-05-12 15:00 UTC, merged