Fix API unexpected error when starting
wazuh/wazuh pull request #8378
Opened 2021-04-26 14:07 UTC by AdriiiPRodri

|Related issue|
|---|
|#8361|

Hi team,

This PR closes #8361. In this PR we have removed the error that appeared when starting Wazuh if the API found a bug in the ossec.conf file. Now the user is notified and the execution of the command continues.

Regards

2021-04-27 09:27 UTC, vicferpoy requested changes
Missing a new unit test case to test this new parameter.

2021-04-27 09:27 UTC, vicferpoy commented on framework/wazuh/core/cluster/utils.py
> +def read_cluster_config(config_file=common.ossec_conf, run_import=False) -> typing.Dict:
```suggestion
def read_cluster_config(config_file=common.ossec_conf, from_import=False) -> typing.Dict:
```
I believe this name is more accurate. Take this as a suggestion, not a requirement.

2021-04-27 12:03 UTC, davidjiglesias approved these changes

2021-04-27 12:06 UTC, vicferpoy approved these changes
LGTM!

2021-04-28 10:05 UTC, davidjiglesias submitted a review, later dismissed

2021-04-28 10:56 UTC, davidjiglesias approved these changes

2021-04-28 10:56 UTC, merged