Generate OS and Kernel packages for Amazon Linux to match NVD vulnerabilities
wazuh/wazuh pull request #8449
Opened 2021-04-29 15:09 UTC by MarcelKemp

|Related issue|
|---|
|#8369|

## Description

This PR aims to generate the OS and kernel packages for Amazon Linux, so that they match with the NVD.

In the case of the generation of the OS package, currently we can only see cases in the NVD with the following format:
`cpe:2.3:o:amazon:linux_2:20180925:*:*:*:*:*:*:*`

So to address all possible cases that could be added in the future within the NVD, we have added the following formats:
```
Amazon Linux 1:
cpe:2.3:o:amazon:linux:*:*:*:*:*:*:*:*
cpe:2.3:o:amazon:linux_1:*:*:*:*:*:*:*:*
```
```
Amazon Linux 2:
cpe:2.3:o:amazon:linux_2:*:*:*:*:*:*:*:*
```
Also, in the event that the Amazon Linux feed is detected, we will try to detect all possible CPEs, because where the `os_release` should go is the date of the release notes.

2021-05-03 16:09 UTC, alromeros approved these changes
LGTM!

2021-05-12 16:25 UTC, chemamartinez requested changes

2021-05-12 16:25 UTC, chemamartinez commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
> +            product_name[1] = V_KERNEL;
Better to use here `"linux"` directly to avoid confusion between a product name and the vendor for the Kernel package, even they are the same.

2021-05-12 16:25 UTC, chemamartinez commented on src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
> +        if (agent->dist == FEED_ALAS){
We could replace the value of `agent->os_release` with `*`. That way we avoid repeating this piece of code.

2021-05-14 16:14 UTC, chemamartinez approved these changes

2021-05-14 16:14 UTC, merged