Fix the sort parameter to maintain the order of the fields
wazuh/wazuh pull request #8548
Opened 2021-05-05 14:59 UTC by Espectro123

|Related issue|
|---|
||

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

2021-05-10 10:24 UTC, mcarmona99 requested changes

2021-05-10 10:24 UTC, mcarmona99 commented on api/test/integration/test_agent_GET_endpoints.tavern.yaml
> +  - name: Get all agents sort by multiple fields
Use `sorted` instead of `sort`

2021-05-10 10:24 UTC, mcarmona99 commented on api/test/integration/test_agent_GET_endpoints.tavern.yaml
> +
Just 1 endline here

2021-05-10 10:24 UTC, mcarmona99 commented on api/test/integration/test_agent_GET_endpoints.tavern.yaml
> +
Just 1 endline here

2021-05-10 10:24 UTC, mcarmona99 commented on api/test/integration/test_agent_GET_endpoints.tavern.yaml
> +
Just 1 endline here

2021-05-10 10:24 UTC, mcarmona99 commented on framework/wazuh/core/tests/test_utils.py
> +def test_WazuhDBQuery_protected_add_sort_order_query(mock_socket_conn, mock_isfile, mock_conn_db, mock_glob,
Change test name, check params too.
Review docstring too, verbs in bare form, . at the end of sentences.

2021-05-10 10:24 UTC, mcarmona99 commented on framework/wazuh/core/tests/test_utils.py
> +
Just 2 endlines

2021-05-10 10:24 UTC, mcarmona99 commented on framework/wazuh/core/utils.py
> +        fields_allowed = True
You don't need to use this variable, just return False inside the if statement and return True after the for loop.

2021-05-10 10:24 UTC, mcarmona99 commented on framework/wazuh/tests/data/schema_global_test.sql
> +-- Connected agent in group-1
Description?
In my opinion, use `agent with different OS` or something similar.

2021-05-10 10:24 UTC, mcarmona99 commented on framework/wazuh/tests/test_agent.py
> +    """Test `sort` parameter of GET /agents endpoint
. at the end of the description
Params missing in docstring.

2021-05-10 10:24 UTC, mcarmona99 commented on framework/wazuh/tests/test_agent.py
> +    distinct = get_agents(agent_list=agent_list, select=fields, sort={'fields': fields, 'order': order[0]})
Why is order a list?? order could be a string and you will avoid using order[0].
Also change variable name as it may be confusing.

2021-05-12 09:05 UTC, davidjiglesias requested changes

2021-05-12 09:05 UTC, davidjiglesias commented on api/test/integration/tavern_utils.py
> +        Dictionary shorted by the key.
sorted

2021-05-12 09:05 UTC, davidjiglesias commented on api/test/integration/tavern_utils.py
> +        Indicates either the items are going to be ordered in ascending or descending order.
either -> wheter

2021-05-12 09:05 UTC, davidjiglesias commented on api/test/integration/tavern_utils.py
> +    Use the auxiliary function _sort_items to sort the elements.
_sort_items or sort_items?

2021-05-12 09:05 UTC, davidjiglesias commented on api/test/integration/tavern_utils.py
> +        Keys expected to sort by separate with a comma (os.name,os.major).
Comma separated keys to be sorted

2021-05-12 09:05 UTC, davidjiglesias commented on api/test/integration/tavern_utils.py
> +    # Create a new lists with the disconnected agents deleting them from the items list
Try a generic approach to handle non-existing fields in the response

2021-05-12 09:05 UTC, davidjiglesias commented on api/test/integration/tavern_utils.py
> +    # Order the items list
Sort

2021-05-12 09:05 UTC, davidjiglesias commented on api/test/integration/tavern_utils.py
> +    # If the order is descending, the disconnected agents will be at top
at the top

2021-05-12 09:05 UTC, davidjiglesias commented on framework/wazuh/core/tests/test_utils.py
> +@pytest.mark.parametrize('sort, expected_items, fields', [
If sort and expected_items is always the same, why do we have it 2 times?

2021-05-12 09:05 UTC, davidjiglesias commented on framework/wazuh/core/utils.py
> +    def _check_allowed_sort_fields(self, allowed_sort_fields):
Use a set cast of the array instead of this

2021-05-12 11:09 UTC, davidjiglesias submitted a review, later dismissed

2021-05-17 10:28 UTC, davidjiglesias approved these changes

2021-05-17 10:28 UTC, merged