Fix GET /agents/stats/distinct
wazuh/wazuh pull request #8599
Opened 2021-05-10 10:40 UTC by Selutario

|Related issue|
|---|
| Closes #8538 |

## Description

Hi team!

This PR fixes the error in `GET /agents/stats/distinct` that was reported in #8538. Now, ID field is not included unless the user specifies it, so it will not be shown as `unknown`:

> GET /agents/stats/distinct?fields=node_name,id&select=node_name

```JSON
{
  "data": {
    "affected_items": [
      {
        "node_name": "master-node",
        "count": 1
      },
      {
        "node_name": "unknown",
        "count": 1
      },
      {
        "node_name": "unknown",
        "count": 1
      },
      {
        "node_name": "worker1",
        "count": 1
      },
      {
        "node_name": "unknown",
        "count": 1
      },
      {
        "node_name": "unknown",
        "count": 1
      }
    ],
    "total_affected_items": 6,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

In addition, a bug has been fixed. Before, if `fields` and `select` used different values, an error like the one below was raised:

> GET /agents/stats/distinct?fields=os.codename&select=node_name
```JSON
{
  "title": "Bad Request",
  "detail": "Error in wazuhdb request: Cannot execute Global database query; near \"from\": syntax error",
  "remediation": "Make sure the request is correct",
  "dapi_errors": {
    "master-node": {
      "error": "Error in wazuhdb request: Cannot execute Global database query; near \"from\": syntax error"
    }
  },
  "error": 2003
}
```

Now, an exception with a more explanatory message has been added:
```JSON
{
  "title": "Bad Request",
  "detail": "Select fields have to be a subset of the filter fields: select fields: ['node_name'], filter fields: ['os.codename']",
  "dapi_errors": {
    "master-node": {
      "error": "Select fields have to be a subset of the filter fields: select fields: ['node_name'], filter fields: ['os.codename']"
    }
  },
  "error": 1760
}
```

Regards,
Selu.

2021-05-21 10:59 UTC, CarlosRS9 requested changes

2021-05-21 10:59 UTC, CarlosRS9 commented on api/test/integration/test_agent_GET_endpoints.tavern.yaml
> +  - name: Select is different to filter fields
```suggestion
  - name: Select is different from filter fields
```

2021-05-28 08:01 UTC, CarlosRS9 approved these changes

2021-05-31 11:34 UTC, mcarmona99 commented
### PR update

We have decided to remove the select parameter from the `GET /agents/stats/distinct` endpoint.

With this change, the error will be fixed. `fields` will be the parameter to indicate how to distinct and select.

- Test results:

```
test_agent_GET_endpoints.tavern.yaml 
	 91 passed, 93 warnings
```

```
framework/wazuh/core/tests/
======= 667 passed, 1 xfailed, 2 xpassed, 9 warnings in 4.21s =======

framework/wazuh/tests/
======= 587 passed, 13 warnings in 54.29s =======
```

Regards,
Manuel.

2021-06-01 12:03 UTC, vicferpoy approved these changes
LGTM!

2021-06-09 13:21 UTC, vicferpoy approved these changes
LGTM!

2021-06-10 13:47 UTC, davidjiglesias approved these changes

2021-06-10 13:51 UTC, merged