Fix MSI uninstallation procedure tmp file locked
wazuh/wazuh pull request #8731
Opened 2021-05-19 09:16 UTC by okynos

|Related issue|
|---|
| Closes #6947 |

Hello team,

## Description

This PR aims to improve the uninstall procedure, we have changed the `StopWinService`, `StopOssecService` and `DeleteOssecService` to match the new CMD execution. This way to stop the process is more natural to Windows systems.
We have added a binary key that references the CMD executable.
We have changed the order of service execution inside the install sequence scheme.

## Tests

We have tested install and uninstall steps.
We have tried to reproduce the issue with this new change without success.

- Compilation without warnings in every supported platform
  - [x] Windows
- [x] Package installation
- [x] Package upgrade
- [x] Review logs syntax and correct language

- [x] Retrocompatibility with older Wazuh versions

Regards.

2021-05-20 09:19 UTC, DFolchA approved these changes
LGTM

2021-05-20 13:55 UTC, DProvinciani approved these changes
Looks good!

2021-05-20 15:15 UTC, alberpilot requested changes
As per conversations, the path can't be harcoded. @okynos will develop another approach.

2021-05-20 15:15 UTC, alberpilot commented on src/win32/wazuh-installer.wxs
> +        <Binary Id="CMDPath" SourceFile="C:\Windows\System32\cmd.exe" />
As per conversations, the path can't be harcoded. @okynos will develop another approach.

2021-05-21 11:08 UTC, DFolchA approved these changes

2021-05-21 13:01 UTC, DProvinciani approved these changes
Looks good!

2021-05-21 13:24 UTC, alberpilot approved these changes
LGTM

2021-05-21 16:07 UTC, merged