Add log message when cluster is restarted
wazuh/wazuh pull request #8749
Opened 2021-05-20 12:38 UTC by Selutario

|Related issue|
|---|
| Closes #8718 |

## Description

Hi team!

Before, when any cluster node was stopped/restarted, no related information was shown in the `cluster.log` file. This is an example where the last log says nothing about the cluster process being stopped.
```
2021/05/20 11:21:53 INFO: [Master] [Local integrity] Starting.
2021/05/20 11:21:53 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 11 files.
2021/05/20 11:21:53 DEBUG: [Worker worker2] [Main] Command received: b'sync_a_w_m_p'
```

After this PR and as requested in #8718, a message following the same pattern that those in the `ossec.log` is shown, in both workers and master:
```
2021/05/20 12:32:28 DEBUG: [Cluster] [D API] Starting to execute request locally
2021/05/20 12:32:28 DEBUG: [Cluster] [D API] Finished executing request locally
2021/05/20 12:32:28 DEBUG: [Worker worker2] [D API] Time calculating request result: 0.003s
2021/05/20 12:32:28 INFO: [Cluster] [Main] SIGNAL [(15)-(SIGTERM)] received. Exit...
```

The signal is being handled in the [wazuh-clusterd.py](https://github.com/wazuh/wazuh/blob/master/framework/scripts/wazuh-clusterd.py) script so it is common for both types of nodes. It will handle SIGTERM singals whatever its procedence is (API requset, using binary, etc).

Although the issue suggested show it as a `DEBUG` message, I decided to make it `INFO` so it is consistent with those in the `ossec.log`:
```
2021/05/20 12:36:26 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
```

Regards,
Selu.

2021-05-24 12:20 UTC, AdriiiPRodri requested changes

2021-05-24 12:20 UTC, AdriiiPRodri commented on framework/scripts/wazuh-clusterd.py
> +    global original_sig_handler
This line is not necessary
```suggestion
```

2021-05-28 07:43 UTC, davidjiglesias approved these changes

2021-05-28 07:45 UTC, AdriiiPRodri approved these changes

2021-05-28 07:45 UTC, merged