Remove libwazuhshared.so in clean-internals
wazuh/wazuh pull request #8917
Opened 2021-06-08 09:02 UTC by antoniomanuelfr

## Description
Hi team!
I noticed that `libwazuhshared.so` is not removed when cleaning the internals dependencies. This PR aims to fix this behavior

## Windows
```
root@ubuntuagent:/home/vagrant/wazuh/src# ls
active-response  ci             error_messages   libwazuhshared.dll  os_crypto      os_maild  Readme.md  selinux         util
addagent         client-agent   external         logcollector        os_csyslogd    os_net    remoted    shared          VERSION
agentlessd       config         headers          Makefile            os_dbd         os_regex  reportd    shared_modules  wazuh_db
analysisd        data_provider  init             monitord            os_execd       os_xml    REVISION   syscheckd       wazuh_modules
build.py         Doxyfile       libwazuhext.dll  os_auth             os_integrator  os_zlib   rootcheck  unit_tests      win32
root@ubuntuagent:/home/vagrant/wazuh/src# make clean-internals TARGET=winagent
..............................................
...........................................
rm -rf wazuh_modules/syscollector/build
rm -rf data_provider/build
rm -rf libwazuhext
root@ubuntuagent:/home/vagrant/wazuh/src# ls
active-response  build.py      data_provider   headers       monitord     os_dbd         os_net    Readme.md  rootcheck       syscheckd   wazuh_db
addagent         ci            Doxyfile        init          os_auth      os_execd       os_regex  remoted    selinux         unit_tests  wazuh_modules
agentlessd       client-agent  error_messages  logcollector  os_crypto    os_integrator  os_xml    reportd    shared          util        win32
analysisd        config        external        Makefile      os_csyslogd  os_maild       os_zlib   REVISION   shared_modules  VERSION
```

## Linux
```
root@ubuntuagent:/home/vagrant/wazuh/src# ls
active-response  config                 headers         libwazuhshared.so  os_csyslogd    os_zlib        rootcheck.a     VERSION             wazuh-syscheckd
addagent         data_provider          host-deny       logcollector       os_dbd         pf             route-null      wazuh-agentd        win32
agent-auth       default-firewall-drop  init            Makefile           os_execd       Readme.md      selinux         wazuh_db
agentlessd       disable-account        ip-customblock  manage_agents      os_integrator  remoted        shared          wazuh-execd
analysisd        Doxyfile               ipfw            monitord           os_maild       reportd        shared_modules  wazuh-logcollector
build.py         error_messages         kaspersky       npf                os_net         restart-wazuh  syscheckd       wazuh_modules
ci               external               libwazuh.a      os_auth            os_regex       REVISION       unit_tests      wazuh-modulesd
client-agent     firewalld-drop         libwazuhext.so  os_crypto          os_xml         rootcheck      util            wazuh-slack
root@ubuntuagent:/home/vagrant/wazuh/src# make clean-internals
.......
.......
rm -rf libwazuhext
root@ubuntuagent:/home/vagrant/wazuh/src# ls
active-response  build.py      data_provider   headers       monitord     os_dbd         os_net    Readme.md  rootcheck       syscheckd   wazuh_db
addagent         ci            Doxyfile        init          os_auth      os_execd       os_regex  remoted    selinux         unit_tests  wazuh_modules
agentlessd       client-agent  error_messages  logcollector  os_crypto    os_integrator  os_xml    reportd    shared          util        win32
analysisd        config        external        Makefile      os_csyslogd  os_maild       os_zlib   REVISION   shared_modules  VERSION
``` 

- Compilation without warnings in every supported platform
  - [X] Linux
  - [X] Windows
  - [ ] MAC OS X

2021-06-08 11:34 UTC, Molter73 submitted a review, later dismissed
LGTM!

2021-06-08 12:07 UTC, tinachoB approved these changes
LGTM!

2021-06-08 12:45 UTC, tinachoB requested changes
After a deeper check on this, we should change the current change by:
`rm -f $(WAZUH_LIB)` 
This will remove the libwazuhshared.dylib if Wazuh solution is being compiled on MAC Operating System.

2021-06-08 13:39 UTC, tinachoB submitted a review, later dismissed

2021-06-08 15:17 UTC, Molter73 submitted a review, later dismissed

2021-06-18 13:37 UTC, Molter73 approved these changes

2021-06-18 14:47 UTC, merged