Add new vuln endpoint and new parameters
wazuh/wazuh pull request #9028
Opened 2021-06-16 07:59 UTC by Selutario

|Related issue|
|---|
| Closes #8863 |

## Description

Hello team!

This PR adds the following new fields in the API response to `GET /vulnerability/{agent_id}` endpoint:
- cvss2_score
- cvss3_score
- detection_time
- severity

However, only severity has been added as a filter on the endpoint. The rest of the new fields, as they are numeric, make more sense to be used to obtain ranges that can be specified within the q parameter, such as: 

> `GET /vulnerability/001?q=cvss3_score>9&severity=critical`
```JSON
{
  "data": {
    "affected_items": [
      {
        "architecture": "amd64",
        "severity": "Critical",
        "version": "3.8.5-1~20.04",
        "name": "python3.8-minimal",
        "cvss2_score": 7.5,
        "cve": "CVE-2021-3177",
        "cvss3_score": 9.8,
        "type": "PACKAGE",
        "detection_time": "2021-06-14T11:25:46Z",
        "status": "VALID"
      }
    ],
    "total_affected_items": 67,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected vulnerabilities were returned",
  "error": 0
}
```

Regards,
Selu.

2021-06-18 08:00 UTC, AdriiiPRodri requested changes

2021-06-18 08:00 UTC, AdriiiPRodri commented on framework/wazuh/core/vulnerability.py
> +from datetime import datetime
Imports are not sorted

2021-06-18 08:00 UTC, AdriiiPRodri commented on framework/wazuh/vulnerability.py
> -logger = logging.getLogger('wazuh')
Unused import `logging`

2021-06-18 08:00 UTC, AdriiiPRodri commented on framework/wazuh/core/vulnerability.py
> +                return value
```suggestion
                    pass

            return value
```

2021-06-18 08:13 UTC, Selutario commented on framework/wazuh/vulnerability.py
> -logger = logging.getLogger('wazuh')
It was removed

2021-06-18 08:25 UTC, AdriiiPRodri approved these changes
LGTM!

2021-06-21 10:26 UTC, davidjiglesias requested changes

2021-06-21 10:26 UTC, davidjiglesias commented on framework/wazuh/core/vulnerability.py
> +            if field_name in ['detection_time', 'last_partial_scan', 'last_full_scan']:
Isnt it better to define a variable (maybe class one) with all date fields?

2021-06-21 10:26 UTC, davidjiglesias commented on framework/wazuh/vulnerability.py
> +    """Return when the last full and partial vulnerability scan of a specified agent end.
```suggestion
    """Return when the last full and partial vulnerability scan of a specified agent ended.
```

2021-06-23 10:12 UTC, davidjiglesias approved these changes

2021-06-23 10:13 UTC, merged