Improve `DELETE /groups` endpoint
wazuh/wazuh pull request #9046
Opened 2021-06-17 07:38 UTC by vicferpoy

|Related issue|
|---|
| closes #9014 |

## Description

Hello team,

As it was summed up in an [issue comment](https://github.com/wazuh/wazuh/issues/9014#issuecomment-862999914), the main reason why this endpoint did not scale at all with a high number of agents was because of the cache management. After a few improvements, this is the result:

![image](https://user-images.githubusercontent.com/37274979/122352692-a3a81600-cf4f-11eb-9fb5-4160e3862b32.png)

## Tests performed
### Unit tests
```
============================= test session starts ==============================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/vicferpoy/Desktop/Git/wazuh/framework
plugins: cov-2.12.0, asyncio-0.15.1
collected 1587 items                                                           

wazuh/core/cluster/dapi/tests/test_dapi.py .......................       [  1%]
wazuh/core/cluster/tests/test_cluster.py ...................             [  2%]
wazuh/core/cluster/tests/test_common.py .......                          [  3%]
wazuh/core/cluster/tests/test_control.py .....                           [  3%]
wazuh/core/cluster/tests/test_local_client.py .                          [  3%]
wazuh/core/cluster/tests/test_utils.py .......                           [  3%]
wazuh/core/cluster/tests/test_worker.py .................                [  4%]
wazuh/core/tests/test_active_response.py ..............                  [  5%]
wazuh/core/tests/test_agent.py ......................................... [  8%]
........................................................................ [ 12%]
.........................................................                [ 16%]
wazuh/core/tests/test_cdb_list.py ...................................... [ 18%]
                                                                         [ 18%]
wazuh/core/tests/test_common.py .......                                  [ 19%]
wazuh/core/tests/test_configuration.py ................................. [ 21%]
...                                                                      [ 21%]
wazuh/core/tests/test_decoder.py ................                        [ 22%]
wazuh/core/tests/test_input_validator.py ...                             [ 22%]
wazuh/core/tests/test_logtest.py ..                                      [ 22%]
wazuh/core/tests/test_manager.py ...............                         [ 23%]
wazuh/core/tests/test_mitre.py .............                             [ 24%]
wazuh/core/tests/test_pyDaemonModule.py ......                           [ 25%]
wazuh/core/tests/test_results.py ....................................... [ 27%]
.                                                                        [ 27%]
wazuh/core/tests/test_rootcheck.py ..........                            [ 28%]
wazuh/core/tests/test_rule.py ......................                     [ 29%]
wazuh/core/tests/test_stats.py ....                                      [ 29%]
wazuh/core/tests/test_syscollector.py ...                                [ 30%]
wazuh/core/tests/test_utils.py ......................................... [ 32%]
........................................................................ [ 37%]
........................................................................ [ 41%]
......................................                                   [ 44%]
wazuh/core/tests/test_vulnerability.py .                                 [ 44%]
wazuh/core/tests/test_wazuh_queue.py ..................                  [ 45%]
wazuh/core/tests/test_wazuh_socket.py ....................               [ 46%]
wazuh/core/tests/test_wdb.py ......................                      [ 48%]
wazuh/rbac/tests/test_auth_context.py ..                                 [ 48%]
wazuh/rbac/tests/test_decorators.py .................................... [ 50%]
.....................................................................    [ 54%]
wazuh/rbac/tests/test_default_configuration.py ......................... [ 56%]
..............................                                           [ 58%]
wazuh/rbac/tests/test_orm.py ........................................... [ 60%]
...........                                                              [ 61%]
wazuh/rbac/tests/test_preprocessor.py ...........                        [ 62%]
wazuh/tests/test_active_response.py ............                         [ 63%]
wazuh/tests/test_agent.py .............................................. [ 65%]
...............................................................          [ 69%]
wazuh/tests/test_cdb_list.py ........................................... [ 72%]
..........                                                               [ 73%]
wazuh/tests/test_ciscat.py .................................             [ 75%]
wazuh/tests/test_cluster.py .......                                      [ 75%]
wazuh/tests/test_decoder.py ...................................          [ 78%]
wazuh/tests/test_group.py ........                                       [ 78%]
wazuh/tests/test_logtest.py ......                                       [ 78%]
wazuh/tests/test_manager.py ..................................           [ 81%]
wazuh/tests/test_mitre.py .......                                        [ 81%]
wazuh/tests/test_rootcheck.py .......................................... [ 84%]
.......                                                                  [ 84%]
wazuh/tests/test_rule.py ............................................... [ 87%]
.........                                                                [ 88%]
wazuh/tests/test_sca.py .......                                          [ 88%]
wazuh/tests/test_security.py ........................................... [ 91%]
.................................                                        [ 93%]
wazuh/tests/test_stats.py ................                               [ 94%]
wazuh/tests/test_syscheck.py ........................                    [ 95%]
wazuh/tests/test_syscollector.py ............                            [ 96%]
wazuh/tests/test_task.py ............................                    [ 98%]
wazuh/tests/test_vulnerability.py ..........................             [100%]

================ 1587 passed, 14 warnings in 249.25s (0:04:09) =================

```

Regards,
Víctor

2021-06-18 09:18 UTC, AdriiiPRodri requested changes

2021-06-18 09:18 UTC, AdriiiPRodri commented on framework/wazuh/agent.py
>                                    WazuhDBQueryMultigroups(group_id=group_id, limit=None).run()['items']))
This way is a little faster:
```suggestion
            agent_list = [agent['id'] for agent in WazuhDBQueryMultigroups(group_id=group_id, limit=None).run()['items']]
```

2021-06-18 10:47 UTC, AdriiiPRodri approved these changes
LGTM

2021-06-21 12:26 UTC, davidjiglesias requested changes

2021-06-21 12:26 UTC, davidjiglesias commented on api/api/spec/spec.yaml
> +          description: "List of removed groups with the agents which belonged to the it and might have been reassigned to group default"
```suggestion
          description: "List of removed groups with the agents which belonged to it and might have been reassigned to group default"
```

2021-06-23 10:27 UTC, AdriiiPRodri approved these changes

2021-06-23 10:32 UTC, davidjiglesias approved these changes

2021-06-23 10:32 UTC, merged