Fix double file handle closing in Logcollector
wazuh/wazuh pull request #9067
Opened 2021-06-19 10:54 UTC by vikman90

|Related issue|
|---|
|#9066|

This PR aims to remove every call to `CloseHandle()` on files closed by `fclose()` in Logcollector on Windows agents, as the underlying file handle is implicitly closed, as explained at #9066.

## Tests

- [X] Build agent on Windows.
- [ ] Stress test on the Windows agent.
- [ ] Check that this change won't cause handle leaks.
- [ ] Run a Coverity scan on this branch.

2021-06-19 20:13 UTC, Dwordcito requested changes
It would be a good practice to remove from the struct _logreader and remove all reference to the handle, this would avoid cleaning up everywhere the misuse due to the change of ownership of the handle with _open_osfhandle and _fdopen.

2021-06-19 20:13 UTC, Dwordcito commented on src/logcollector/logcollector.c
>      if (GetFileInformationByHandle(lf->h, &lpFileInformation) == 0) {
Replace line 961 to _close(fd) based on [_open_osfhandle docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-osfhandle?view=msvc-160)

2021-06-19 20:13 UTC, Dwordcito commented on src/logcollector/logcollector.c
>      if (GetFileInformationByHandle(lf->h, &lpFileInformation) == 0) {
Same comment for the reload_file function behavior

2022-02-02 12:45 UTC, vikman90 commented
@Dwordcito thanks for your review.

As discussed privately, Logcollector requires the current file handler ([`GetFileInformationByHandle`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileinformationbyhandle)) to fetch its properties ([https://docs.microsoft.com/en-us/windows/win32/api/fileapi/ns-fileapi-by_handle_file_information`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/ns-fileapi-by_handle_file_information)):

- `nFileIndexLow` and `nFileIndexHigh`
- `nFileSizeLow` and `nFileSizeHigh`

Should we remove the handler (`h`) from the structure `_logreader`, we would need to retrieve the file handler from the file pointer, like this:
```c
GetFileInformationByHandle(_get_osfhandle(_fileno(lf->fp)));
```

This way we would need to replace a value already obtained by a chain of calls, to which must be added the error check. This is why the simplest option is the current one.

2022-02-03 11:29 UTC, Dwordcito approved these changes
looks good!!!

2022-02-03 11:33 UTC, merged