Improve api and cluster processes behavior
wazuh/wazuh pull request #9077
Opened 2021-06-22 08:28 UTC by AdriiiPRodri

|Related issue|
|---|
|#7190|

Hi team,

This PR closes #7190. In this PR we have added the PID of the cluster processes and the API when these processes are started in foreground mode. 

We have also improved the pidfile deletion, now both the API and the cluster will delete their pidfile when they receive a SIGTERM signal.

Finally, we have fixed a bug that was causing the API to not create any pidfile when started in foreground mode. This caused wazuh-control to not know its status.

Regards

2021-06-24 15:16 UTC, Selutario requested changes

2021-06-24 15:16 UTC, Selutario commented on api/scripts/wazuh-apid.py
> +        print(f"Starting API in foreground (pid: {pid})")
```suggestion
        print(f"Starting API in the foreground (pid: {pid})")
```

2021-06-24 15:16 UTC, Selutario commented on framework/scripts/wazuh-clusterd.py
> +        print(f"Starting cluster in foreground (pid: {pid})")
```suggestion
        print(f"Starting cluster in the foreground (pid: {pid})")
```

2021-06-24 15:16 UTC, Selutario commented on framework/wazuh/core/pyDaemonModule.py
> +        pass
Since now Exception 3003 is no longer used, maybe we should delete it.

2021-06-25 08:29 UTC, Selutario approved these changes
LGTM!

2021-06-28 13:50 UTC, davidjiglesias approved these changes

2021-06-28 13:51 UTC, merged