Fix memory leaks in Unit Tests
wazuh/wazuh pull request #9099
Opened 2021-06-24 08:48 UTC by antoniomanuelfr

|Related issue|
|---|
|#5782|

## Description
This PR aims to fix several memory errors in the unit tests. In order to improve them, we have added sanitizers when compiling the unit tests, making them fail when a memory leak is detected. This will only work on Linux systems.

Closes #5782 

- Compilation without warnings in every supported platform
  - [X] Linux
  - [X] Windows

2021-06-24 13:50 UTC, Molter73 requested changes
Just a few minor changes, other than those the PR is looking good.

2021-06-24 13:50 UTC, Molter73 commented on src/unit_tests/logcollector/test_logcollector.c
>  }
We should not do any extra changes to tests that need to revisited other than comment them out, please leave the function as it was and comment it out.

2021-06-24 13:50 UTC, Molter73 commented on src/unit_tests/logcollector/test_logcollector.c
> +*/
Same as with the previous commented test, don't make any extra changes to it, just comment it out.

2021-06-24 13:50 UTC, Molter73 commented on src/unit_tests/server.cmake
> +link_libraries("-fsanitize=address -fsanitize=undefined")
```suggestion
link_libraries(-fsanitize=address -fsanitize=undefined)
```

2021-06-24 13:50 UTC, Molter73 commented on src/unit_tests/syscheckd/test_fim_sync.c
> +    pthread_mutex_t *mutex = (pthread_mutex_t *) 1;
```suggestion
    pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
```

2021-06-24 13:50 UTC, Molter73 commented on src/unit_tests/syscheckd/test_fim_sync.c
> +    pthread_mutex_t *mutex = (pthread_mutex_t *) 1;
```suggestion
    pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
```

2021-06-24 13:50 UTC, Molter73 commented on src/unit_tests/syscheckd/test_fim_sync.c
> +    pthread_mutex_t *mutex = (pthread_mutex_t *) 1;
```suggestion
    pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
```

2021-06-24 13:50 UTC, Molter73 commented on src/unit_tests/syscheckd/test_fim_sync.c
> +    pthread_mutex_t *mutex = (pthread_mutex_t *) 1;
```suggestion
    pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
```

2021-06-24 13:50 UTC, Molter73 commented on src/unit_tests/syscheckd/test_fim_sync.c
> +    pthread_mutex_t *mutex = (pthread_mutex_t *) 1;
```suggestion
    pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
```

2021-06-24 14:41 UTC, jotacarma90 commented on src/unit_tests/wrappers/wazuh/shared/integrity_op_wrappers.c
This lines needs to be formatted

2021-06-25 09:54 UTC, Molter73 requested changes
A few more changes that might have escaped my initial review.

2021-06-25 09:54 UTC, Molter73 commented on src/unit_tests/logcollector/test_logcollector.c
> +    if (setup_hashmap(NULL) == 1) {
```suggestion
    if (setup_hashmap(NULL) != 0) {
```

2021-06-25 09:54 UTC, Molter73 commented on src/unit_tests/logcollector/test_logcollector.c
> +    if (data = calloc(1, sizeof(os_file_status_t)), data == NULL) {
```suggestion
    data = calloc(1, sizeof(os_file_status_t));
    if (data == NULL) {
```

2021-06-25 09:54 UTC, Molter73 commented on src/unit_tests/logcollector/test_logcollector.c
> +    teardown_hashmap(state);
We should check the return value of this teardown and fail ourselves if it fails. We might also want to move it down so if it fails the rest of the memory is correctly free'd

2021-06-25 13:25 UTC, Molter73 approved these changes
LGTM!

2021-06-25 13:29 UTC, jotacarma90 submitted a review, later dismissed
LGTM

2021-07-02 11:01 UTC, jotacarma90 approved these changes
LGTM

2021-07-02 13:48 UTC, Molter73 requested changes
A few comment on where we are placing some declarations, other than those the PR is looking good.

2021-07-02 13:48 UTC, Molter73 commented on src/unit_tests/syscheckd/whodata/test_win_whodata.c
> +void *__real_OSHash_Get(const OSHash *self, const char *key);
Same as a previous comment on `__real_OSHash_Create`, we might want to move this declarations to `hash_op_wrappers.h`

2021-07-05 08:41 UTC, Molter73 approved these changes
LGTM!

2021-11-10 10:50 UTC, chemamartinez approved these changes

2021-11-10 10:51 UTC, merged