Add new `max_upload_size` API option
wazuh/wazuh pull request #9100
Opened 2021-06-24 12:21 UTC by Selutario

|Related issue|
|---|
| Closes #9054 |

## Description

Hello team,

As requested in #9054, this PR adds a new API config option called `max_upload_size`. It lets the user choose how big can the body be in the API requests. If the limit is exceeded, a 413 code (Request Entity Too Large) is returned:
```JSON
{
  "title": "Request Entity Too Large",
  "detail": "Maximum request body size 10 exceeded, actual body size 41"
}
```

The following can be specified so there is no limit on the body size:
```YAML
# Maximum body size that the API can accept, in bytes (0 -> limitless)
max_upload_size: 0
```

Regards,
Selu.

2021-06-25 07:24 UTC, vicferpoy requested changes
Missing changes on spec (response examples) and documentation PR.

2021-06-25 08:37 UTC, vicferpoy submitted a review, later dismissed
LGTM!

2021-06-29 15:26 UTC, davidjiglesias approved these changes

2021-06-29 15:31 UTC, davidjiglesias approved these changes

2021-06-29 15:31 UTC, merged