Move MITRE reference with `external_id` to the exterior level of the response for all MITRE endpoints
wazuh/wazuh pull request #9144
Opened 2021-06-29 09:31 UTC by mcarmona99

|Related issue|
|---|
| #8879 |

Hi team

This PR closes #8879.

In this pull request, I have included the reference with `external_id` out of the references list of each MITRE item.

I have updated unittest and API integration tests to include this change.

`GET /mitre/mitigations?wait_for_complete=true&limit=1`

<details>

<summary>Response</summary>

```
{
  "data": {
    "affected_items": [
      {
        "deprecated": 1,
        "created_time": "2018-10-17 00:14:20.652000",
        "name": "Password Filter DLL Mitigation",
        "mitre_version": "1.0",
        "id": "course-of-action--00d7d21b-69d6-4797-88a2-c86f3fc97651",
        "description": "Ensure only valid password filters are registered. Filter DLLs must be present in Windows installation directory (<code>C:\\Windows\\System32\\</code> by default) of a domain controller and/or local computer with a corresponding entry in <code>HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\Notification Packages</code>. (Citation: Microsoft Install Password Filter n.d)",
        "modified_time": "2019-07-25 11:22:19.139000",
        "techniques": [
          "attack-pattern--b8c5c9dd-a662-479d-9428-ae745872537c"
        ],
        "references": [
          {
            "source": "Microsoft Install Password Filter n.d",
            "url": "https://msdn.microsoft.com/library/windows/desktop/ms721766.aspx",
            "description": "Microsoft. (n.d.). Installing and Registering a Password Filter DLL. Retrieved November 21, 2017."
          }
        ],
        "source": "mitre-attack",
        "external_id": "T1174",
        "url": "https://attack.mitre.org/mitigations/T1174"
      }
    ],
    "total_affected_items": 266,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "MITRE mitigations information was returned",
  "error": 0
}
```

</details>

With these changes, we can now sort by external_id, source and url:

`GET /mitre/mitigations?wait_for_complete=true&limit=3&sort=-external_id&select=external_id,name
`

<details>

<summary>Response</summary>

```
{
  "data": {
    "affected_items": [
      {
        "external_id": "T1501",
        "name": "Systemd Service Mitigation",
        "id": "course-of-action--83130e62-bca6-4a81-bd4b-8e233bd49db6"
      },
      {
        "external_id": "T1500",
        "name": "Compile After Delivery Mitigation",
        "id": "course-of-action--ae56a49d-5281-45c5-ab95-70a1439c338e"
      },
      {
        "external_id": "T1499",
        "name": "Endpoint Denial of Service Mitigation",
        "id": "course-of-action--82c21600-ccb6-4232-8c04-ef3792b56628"
      }
    ],
    "total_affected_items": 266,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "MITRE mitigations information was returned",
  "error": 0
}
```

</details>

### Test results:

```
pytest framework/wazuh/core/tests/test_mitre.py 
=================== 13 passed, 2 warnings in 0.17s ===================

pytest framework/wazuh/tests/test_mitre.py 
=================== 7 passed, 2 warnings in 0.19s ===================
```

```
test_mitre_endpoints.tavern.yaml 
	 7 passed, 13 warnings

test_rbac_black_mitre_endpoints.tavern.yaml 
	 7 passed, 13 warnings

test_rbac_white_mitre_endpoints.tavern.yaml 
	 7 passed, 13 warnings
```

Regards,
Manuel.

2021-06-30 08:27 UTC, CarlosRS9 commented on framework/wazuh/core/mitre.py
> +            if reference_external_id in mitigation['references']:
```suggestion
            if reference_external_id:
```
If the `reference_external_id` is not empty it is guaranteed to be in `mitigation['references']`

2021-06-30 08:27 UTC, CarlosRS9 commented on framework/wazuh/core/mitre.py
> +            if reference_external_id in tactic['references']:
```suggestion
            if reference_external_id:
```

2021-06-30 08:27 UTC, CarlosRS9 commented on framework/wazuh/core/mitre.py
> +            if reference_external_id in technique['references']:
```suggestion
            if reference_external_id:
```

2021-06-30 08:27 UTC, CarlosRS9 commented on framework/wazuh/core/mitre.py
> +            if reference_external_id in group['references']:
```suggestion
            if reference_external_id:
```

2021-06-30 08:27 UTC, CarlosRS9 commented on framework/wazuh/core/mitre.py
> +            if reference_external_id in software['references']:
```suggestion
            if reference_external_id:
```

2021-06-30 08:34 UTC, CarlosRS9 submitted a review, later dismissed
LGTM!

2021-07-08 11:11 UTC, davidjiglesias requested changes
Add new references handling to father class

2021-07-13 08:51 UTC, davidjiglesias approved these changes

2021-07-13 08:51 UTC, merged