Remove tmp variables from `GET /cluster/healthcheck` response
wazuh/wazuh pull request #9147
Opened 2021-06-29 13:50 UTC by vicferpoy

|Related issue|
|---|
| closes #9021 |

## Description
 
Hello team,

This PR adds a change in the `.to_dict` method of the class `MasterHandler` to remove any temporal variables used for inner processing.

### `GET /cluster/healthcheck` response

```json
{
  "data": {
    "affected_items": [
      {
        "info": {
          "name": "master-node",
          "type": "master",
          "version": "4.3.0",
          "ip": "wazuh-master",
          "n_active_agents": 1
        }
      },
      {
        "info": {
          "name": "worker1",
          "type": "worker",
          "version": "4.3.0",
          "ip": "172.18.0.6",
          "n_active_agents": 0
        },
        "status": {
          "sync_integrity_free": true,
          "sync_extravalid_free": true,
          "last_check_integrity": {
            "date_start_master": "2021-06-29 11:33:58.053970",
            "date_end_master": "2021-06-29 11:33:58.072101"
          },
          "last_sync_integrity": {
            "date_start_master": "n/a",
            "date_end_master": "n/a",
            "total_extra_valid": 0,
            "total_files": {
              "missing": 0,
              "shared": 0,
              "extra": 0,
              "extra_valid": 0
            }
          },
          "last_sync_agentinfo": {
            "date_start_master": "2021-06-29 11:33:58.053970",
            "date_end_master": "2021-06-29 11:33:58.072101"
          },
          "last_keep_alive": "2021-06-29 11:33:45.862957"
        }
      },
      {
        "info": {
          "name": "worker2",
          "type": "worker",
          "version": "4.3.0",
          "ip": "172.18.0.2",
          "n_active_agents": 0
        },
        "status": {
          "sync_integrity_free": true,
          "sync_extravalid_free": true,
          "last_check_integrity": {
            "date_start_master": "2021-06-29 11:33:58.055449",
            "date_end_master": "2021-06-29 11:33:58.075284"
          },
          "last_sync_integrity": {
            "date_start_master": "n/a",
            "date_end_master": "n/a",
            "total_extra_valid": 0,
            "total_files": {
              "missing": 0,
              "shared": 0,
              "extra": 0,
              "extra_valid": 0
            }
          },
          "last_sync_agentinfo": {
            "date_start_master": "2021-06-29 11:33:58.055449",
            "date_end_master": "2021-06-29 11:33:58.075284"
          },
          "last_keep_alive": "2021-06-29 11:33:45.864200"
        }
      }
    ],
    "total_affected_items": 3,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected nodes healthcheck information was returned",
  "error": 0
}
```

No changes were needed for tests as the API integration tests only check that the keys within the response appear and have a specific value. 

## Tests performed
### Unit tests
```
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/vicferpoy/Desktop/Git/wazuh/framework
plugins: cov-2.12.0, asyncio-0.15.1
collected 1581 items                                                                                                                                                                        

wazuh/core/cluster/dapi/tests/test_dapi.py .......................                                                                                                                    [  1%]
wazuh/core/cluster/tests/test_cluster.py ...................                                                                                                                          [  2%]
wazuh/core/cluster/tests/test_common.py .......                                                                                                                                       [  3%]
wazuh/core/cluster/tests/test_control.py .....                                                                                                                                        [  3%]
wazuh/core/cluster/tests/test_local_client.py .                                                                                                                                       [  3%]
wazuh/core/cluster/tests/test_utils.py .......                                                                                                                                        [  3%]
wazuh/core/cluster/tests/test_worker.py .................                                                                                                                             [  4%]
wazuh/core/tests/test_active_response.py ..............                                                                                                                               [  5%]
wazuh/core/tests/test_agent.py ...................................................................................................................................................... [ 15%]
...............                                                                                                                                                                       [ 16%]
wazuh/core/tests/test_cdb_list.py ......................................                                                                                                              [ 18%]
wazuh/core/tests/test_common.py .......                                                                                                                                               [ 19%]
wazuh/core/tests/test_configuration.py ....................................                                                                                                           [ 21%]
wazuh/core/tests/test_decoder.py ................                                                                                                                                     [ 22%]
wazuh/core/tests/test_input_validator.py ...                                                                                                                                          [ 22%]
wazuh/core/tests/test_logtest.py ..                                                                                                                                                   [ 22%]
wazuh/core/tests/test_manager.py ...............                                                                                                                                      [ 23%]
wazuh/core/tests/test_mitre.py .............                                                                                                                                          [ 24%]
wazuh/core/tests/test_pyDaemonModule.py .....                                                                                                                                         [ 24%]
wazuh/core/tests/test_results.py ........................................                                                                                                             [ 27%]
wazuh/core/tests/test_rootcheck.py ..........                                                                                                                                         [ 28%]
wazuh/core/tests/test_rule.py ......................                                                                                                                                  [ 29%]
wazuh/core/tests/test_stats.py ....                                                                                                                                                   [ 29%]
wazuh/core/tests/test_syscollector.py ...                                                                                                                                             [ 29%]
wazuh/core/tests/test_ [...]

2021-06-29 14:37 UTC, Selutario requested changes

2021-06-29 14:37 UTC, Selutario commented on framework/wazuh/core/cluster/master.py
> +                           'last_sync_agentinfo': self.integrity_check_status,
```suggestion
                           'last_sync_agentinfo': self.sync_agent_info_status,
```

2021-07-05 08:00 UTC, mcarmona99 approved these changes
LGTM!

2021-07-05 10:10 UTC, davidjiglesias approved these changes

2021-07-05 10:11 UTC, merged