Add context variable to indicate origin module in socket messages
wazuh/wazuh pull request #9209
Opened 2021-07-06 13:24 UTC by mcarmona99

|Related issue|
|---|
| #7368 |

Hi team,

This PR closes #7368.

In this Pull request I have added a new context variable to `wazuh/core/common.py` to indicate if the wazuh socket messages created come from the **API** or from the **framework** module. 

This is used to delete the hardcoded variables when creating this messages.

For instance, when we try to restart agents, the following message is created and sent to its correspondant socket:

```
msg_queue = json.dumps(
        create_wazuh_socket_message(origin={'name': node_name, 'module': common.origin_module.get()},
                                    command=command,
                                    parameters={'extra_args': arguments if arguments else [],
                                                'alert': alert if alert else {}}))
```
                                                
If this request is called from the Wazuh API, the message will be the following:

`{"version": 1, "origin": {"name": "master-node", "module": "api"}, "command": "restart-ossec0", "parameters": {"extra_args": [], "alert": {}}}`

If the request is called from the framework itself (using the embedded python interpreter), the following message is created:

`{"version": 1, "origin": {"name": "master-node", "module": "framework"}, "command": "restart-ossec0", "parameters": {"extra_args": [], "alert": {}}}`

I have also reviewed unit tests and API integration tests:

```
framework/wazuh/core/tests/
============= 678 passed, 9 warnings in 4.07s =============

framework/wazuh/tests/
============= 598 passed, 13 warnings in 57.93s =============
```

Regards,
Manuel.

2021-07-07 07:11 UTC, vicferpoy requested changes

2021-07-07 07:21 UTC, mcarmona99 commented on framework/wazuh/core/cluster/dapi/dapi.py
> +        self.origin_module = origin_module
`self.origin_module = 'API'` will be the final solution after having talked about it

2021-07-07 07:25 UTC, vicferpoy approved these changes
LGTM!

2021-07-08 10:53 UTC, davidjiglesias approved these changes

2021-07-08 10:53 UTC, merged