Fix error in filter q when using dates. Standardization of dates in API outputs.
wazuh/wazuh pull request #9227
Opened 2021-07-07 14:57 UTC by AdriiiPRodri

|Related issue|
|---|
|#9079|

Hi team,

This PR closes #9079. We have changed the format of all dates in the API outputs in this PR, so we have standardized within the Framework the ISO 8601 format.

In addition, we have fixed a bug that caused the 'q' filter to not work properly when dates were added to it.

More information here: https://github.com/wazuh/wazuh/issues/9079#issuecomment-875658462

2021-07-09 14:52 UTC, vicferpoy requested changes

2021-07-09 14:52 UTC, vicferpoy commented on api/api/controllers/default_controller.py
> +        'timestamp': datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
I suggest using global variables for both standard date format and with decimals.

2021-07-12 12:04 UTC, vicferpoy approved these changes
LGTM!

2021-07-13 08:59 UTC, davidjiglesias submitted a review, later dismissed

2021-07-13 09:05 UTC, vicferpoy approved these changes

2021-07-13 10:27 UTC, davidjiglesias approved these changes

2021-07-13 10:27 UTC, merged