Style changes in RTR scripts
wazuh/wazuh pull request #9244
Opened 2021-07-09 09:14 UTC by antoniomanuelfr

## Description
Hi team! this PR aims to fix some style problems in RTR scripts.

## Tests
RTR pass on:

- [ ] shared_modules/utils 
- [ ] shared_modules/rsync
- [ ] shared_modules/dbsync
- [ ] data_provider
- [ ] wazuh_modules/syscollector

2021-07-09 15:33 UTC, Molter73 approved these changes
LGTM!

2021-07-12 12:27 UTC, konangc87 commented on src/ci/utils.py
> +            printFail('Execute astyle --options=ci/input/astyle.config moduleName/*.h moduleName/*.cpp for further'
This seems to be a legacy issue but I believe it won't print the failing module correctly.

2021-07-12 12:58 UTC, tinachoB reviewed
The changes look good to me. @antoniomanuelfr , could you please start, manually, the CI checks so that we ensure everything is working as expected? Once this is done, I'll proceed with my approval. Good job ;)

2021-07-12 13:54 UTC, konangc87 submitted a review, later dismissed

2021-07-12 14:00 UTC, jnasselle requested changes

2021-07-12 14:00 UTC, jnasselle commented on src/ci/utils.py
> +                      f'lcov_branch_coverage=0 --exclude="*/tests/*" --include "{includeDir}/*" -q'
PEP8 linter show "continuation line over-indented for visual indent" [E127](https://www.flake8rules.com/rules/E127.html)
```suggestion
    coverageCommand = f'lcov {folders} --capture --output-file {reportFolder}/code_coverage.info -rc ' \
                       f'lcov_branch_coverage=0 --exclude="*/tests/*" --include "{includeDir}/*" -q'
```

2021-07-12 17:24 UTC, jnasselle commented on src/ci/utils.py
> +                      f'lcov_branch_coverage=0 --exclude="*/tests/*" --include "{includeDir}/*" -q'
Hi agail @antoniomanuelfr ,

There are multiples python linters (flake8, pylint), and only in one of them his change was suggested. But this change generate alerts in the other ones, so i will mark this as solved.

Sorry about this misunderstanding. 

Regards,
Nico

2021-07-12 17:24 UTC, jnasselle approved these changes

2021-08-24 19:30 UTC, tinachoB approved these changes
LGTM!

2021-08-25 11:11 UTC, merged