Improve framework regexes
wazuh/wazuh pull request #9332
Opened 2021-07-19 14:26 UTC by vicferpoy

|Related issue|
|---|
| closes #9286  |

## Description

Hello team,
This PR improves all the framework regexes in order to make them more specific and prevent high CPU usage. The API ones did not need any change.

## Tests performed
### Unit tests
```
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/vicferpoy/Desktop/Git/wazuh/framework
plugins: cov-2.12.0, asyncio-0.15.1
collected 1589 items                                                                                                                                                                        

wazuh/core/cluster/dapi/tests/test_dapi.py .......................                                                                                                                    [  1%]
wazuh/core/cluster/tests/test_cluster.py ...................                                                                                                                          [  2%]
wazuh/core/cluster/tests/test_common.py .......                                                                                                                                       [  3%]
wazuh/core/cluster/tests/test_control.py .....                                                                                                                                        [  3%]
wazuh/core/cluster/tests/test_local_client.py .                                                                                                                                       [  3%]
wazuh/core/cluster/tests/test_utils.py .......                                                                                                                                        [  3%]
wazuh/core/cluster/tests/test_worker.py .................                                                                                                                             [  4%]
wazuh/core/tests/test_active_response.py ..............                                                                                                                               [  5%]
wazuh/core/tests/test_agent.py ...................................................................................................................................................... [ 15%]
................                                                                                                                                                                      [ 16%]
wazuh/core/tests/test_cdb_list.py ......................................                                                                                                              [ 18%]
wazuh/core/tests/test_common.py .......                                                                                                                                               [ 19%]
wazuh/core/tests/test_configuration.py ....................................                                                                                                           [ 21%]
wazuh/core/tests/test_decoder.py ................                                                                                                                                     [ 22%]
wazuh/core/tests/test_input_validator.py ...                                                                                                                                          [ 22%]
wazuh/core/tests/test_logtest.py ..                                                                                                                                                   [ 22%]
wazuh/core/tests/test_manager.py ...............                                                                                                                                      [ 23%]
wazuh/core/tests/test_mitre.py .............                                                                                                                                          [ 24%]
wazuh/core/tests/test_pyDaemonModule.py .....                                                                                                                                         [ 24%]
wazuh/core/tests/test_results.py ........................................                                                                                                             [ 27%]
wazuh/core/tests/test_rootcheck.py ..........                                                                                                                                         [ 27%]
wazuh/core/tests/test_rule.py ......................                                                                                                                                  [ 29%]
wazuh/core/tests/test_stats.py ....                                                                                                                                                   [ 29%]
wazuh/core/tests/test_syscollector.py ...                                                                                                                                             [ 29%]
wazuh/core/tests/test_utils.py ...................................................................................................................................................... [ 39%]
..............................................................................                                                                                                        [ 44%]
wazuh/core/tests/test_vulnerability.py .                                                                                                                                              [ 44%]
wazuh/core/tests/test_wazuh_queue.py ..................                                                                                                                               [ 45%]
wazuh/core/tests/test_wazuh_socket.py ....................                                                                                                                            [ 46%]
wazuh/core/tests/test_wdb.py ......................                                                                                                                                   [ 47%]
wazuh/rbac/tests/test_auth_context.py ..                                                                                                                                              [ 48%]
wazuh/rbac/tests/test_decorators.py .........................................................................................................                                         [ 54%]
wazuh/rbac/tests/test_default_configuration.py .......................................................                                                                                [ 58%]
wazuh/rbac/tests/test_orm.py ......................................................                                                                                                   [ 61%]
wazuh/rbac/tests/test_preprocessor.py ...........                                                                                                                                     [ 62%]
wazuh/tests/test_active_response.py ............                                                                                                                                      [ 62%]
wazuh/tests/test_agent.py .............................................................................................................                                               [ 69%]
wazuh/tests/test_cdb_list.py .....................................................                                                                                                    [ 73%]
wazuh/tests/test_ciscat.p [...]

2021-07-21 10:52 UTC, mcarmona99 requested changes

2021-07-21 10:52 UTC, mcarmona99 commented on framework/wazuh/core/configuration.py
> +    regex_check = re.compile(r"^\s?(.+)\s!\s?(.+)\s?::\s?(.+)")
In lines 413-414, strips to each group are made, so we could avoid using \s in this regex:

```suggestion
    regex_check = re.compile(r"^(.+)!(.+)::(.+)")
```


This suggested regex is also passed by regexploit:

```
regexploit-py framework/wazuh/core/configuration.py 
Processed 13 regexes
```

2021-07-21 10:52 UTC, mcarmona99 commented on framework/wazuh/core/configuration.py
> +    regex_binary_check = re.compile(r"^\s?(.+)\s!\s?(.+)\s?!")
Same as above

2021-07-21 10:52 UTC, mcarmona99 commented on framework/wazuh/rbac/orm.py
>                          # Regular expression that prevents the creation of invalid policies
Remove or change this comment as the regex is not defined here

2021-07-21 10:52 UTC, mcarmona99 commented on framework/wazuh/rbac/orm.py
>                          # Regular expression that prevents the creation of invalid policies
Same as above

2021-07-21 10:52 UTC, mcarmona99 commented on framework/wazuh/rbac/orm.py
> +        self.resource_regex = r'^[a-zA-Z_\-*]+:[\w_\-*]+:[\w_\-\/.*]+$'
Wouldn't it be more appropriate if these 2 instance variables were class variables? Their values will always be the same in all instances of the class.

2021-07-21 12:15 UTC, mcarmona99 requested changes

2021-07-21 12:15 UTC, mcarmona99 commented on framework/wazuh/core/configuration.py
> +    regex_check = re.compile(r"^\s?(.+)\s!\s?(.+)\s?::\s?(.+)")
In lines 413-414, strips to each group are made, so we could avoid using \s in this regex:

```suggestion
    regex_check = re.compile(r"^(.+)!(.+)::(.+)")
```

2021-07-21 12:16 UTC, mcarmona99 commented on framework/wazuh/core/configuration.py
> +    regex_check = re.compile(r"^\s?(.+)\s!\s?(.+)\s?::\s?(.+)")
Also check this in the regex defined in lines 434, 435

2021-07-21 14:21 UTC, mcarmona99 approved these changes
LGTM

2021-08-09 08:33 UTC, davidjiglesias approved these changes

2021-08-09 08:33 UTC, merged