9203 agent disconnection handling and alerting charter
wazuh/wazuh pull request #9346
Opened 2021-07-20 11:42 UTC by jnasselle

|Related issue|
|---|
|#9203|

This PR aims to add the monitord sequence diagram and description related to agent disconnection and alerting handling.

![agent-disconnection-handling](https://user-images.githubusercontent.com/1791430/126318021-d584bf4a-18e7-4feb-a463-23abff16ee7d.png)

Regards,
Nico

2021-07-23 15:50 UTC, tinachoB requested changes

2021-07-23 15:50 UTC, tinachoB commented on src/diagrams/architecture/agent_disconnection_handling/Readme.md
> +As secuence diagram shows, agent disconnection handling and alerting feature has four mayors activities:
sequence

2021-07-23 15:50 UTC, tinachoB commented on src/diagrams/architecture/agent_disconnection_handling/Readme.md
> +- Scheduler with seconds granularity that trigger the next activities.
triggers

2021-07-23 15:50 UTC, tinachoB commented on src/diagrams/architecture/agent_disconnection_handling/Readme.md
> +- In case `monitord.monitor_agents` is enabled, generate alert for those disconnected agents using configured `agents_disconnection_alert_time` criteria.
In case of

2021-07-23 15:50 UTC, tinachoB commented on src/diagrams/architecture/agent_disconnection_handling/Readme.md
> +- In case `monitord.monitor_agents` and `monitord.delete_old_agents` are enabled, delete all disconnected agents using configured `monitord.delete_old_agents`criteria.
In case of

2021-07-23 15:50 UTC, tinachoB commented on src/diagrams/architecture/agent_disconnection_handling/Readme.md
> +- **Prevent pending agents from keepping their state indefinitely [#8975](https://github.com/wazuh/wazuh/issues/8975)]**.
keepping -> keeping

2021-07-26 13:36 UTC, konangc87 requested changes

2021-07-26 13:36 UTC, konangc87 commented on src/diagrams/architecture/agent_disconnection_handling/001-sequence.puml
> +                                    monitord -> authd : auth_remove_agent(agent)
I believe authd++ and authd-- are missing.

2021-07-26 13:36 UTC, konangc87 commented on src/diagrams/architecture/agent_disconnection_handling/001-sequence.puml
> +                    monitord -> wdb : wdb_get_agent_info(agent)
I believe wdb++ and wdb-- are missing.

2021-07-27 06:46 UTC, Dwordcito reviewed
try to communicate a design phase with the diagram, which allows it to be interpreted without having to read it as a call tree in a sequence diagram, I understand that this should be prior to implementation, but let's make an effort to avoid changes of states (since this would go in a state diagram), and let's illustrate the interactions between the different objects / entities logically.

Imagine that you are an engineer reading the diagram for the first time, and you will see how difficult it is to interpret.

2021-08-04 10:58 UTC, jnasselle commented on src/diagrams/architecture/agent_disconnection_handling/001-sequence.puml
> +
Solved!

2021-08-04 14:34 UTC, tinachoB approved these changes
LGTM!

2021-08-04 15:51 UTC, Dwordcito approved these changes

2021-08-05 13:49 UTC, merged