[9270] Added wm_azure sequence diagram and Readme.md
wazuh/wazuh pull request #9358
Opened 2021-07-21 01:05 UTC by tinachoB

|Related issue|
|---|
|Related issue: #9270 |

## Description

As part of wm_azure memory consumption analysis, a sequence diagram has been created as well as a Readme.md file explaining the feature itself.

## Tests

These are documentation changes only. No code changes has been made on this PR.

2021-07-21 01:17 UTC, Dwordcito approved these changes

2021-07-21 01:44 UTC, konangc87 approved these changes

2021-07-21 11:24 UTC, jnasselle requested changes

2021-07-21 11:24 UTC, jnasselle commented on architecture/azure/001-sequence.puml
> +@enduml
```suggestion
@enduml

```

2021-07-21 11:25 UTC, jnasselle approved these changes

2021-07-22 23:12 UTC, tinachoB commented
Closing because these changes need to be merged on `4.2` instead of `master`.

2021-07-22 23:12 UTC, closed without merging