Make RBAC policies case insensitive
wazuh/wazuh pull request #9433
Opened 2021-08-02 09:31 UTC by vicferpoy

|Related issue|
|---|
| closes #9333 |

## Description

Hello team,

As it was discussed in the issue, we needed to make the RBAC policy comparison case insensitive. This does not include the resource IDs like `group:id:New_Group`.

### Example
#### JSON
```json
{
  "name": "testing",
  "policy": {
    "actions": [
      "Agent:Read"
    ],
    "resources": ["Agent:ID:001&gRouP:iD:CAPS_gRoup"],
    "effect": "aLLoW"
  }
}
```

#### Response
```json
{
  "data": {
    "affected_items": [
      {
        "id": 100,
        "name": "testing",
        "policy": {
          "actions": [
            "agent:read"
          ],
          "resources": [
            "agent:id:001&group:id:CAPS_gRoup"
          ],
          "effect": "allow"
        },
        "roles": []
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Policy was successfully created",
  "error": 0
}
```

## Tests performed
### Unit tests
```
========================================= test session starts ==========================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/vicferpoy/Desktop/Git/wazuh/framework
plugins: cov-2.12.0, asyncio-0.15.1
collected 1599 items                                                                                   

wazuh/core/cluster/dapi/tests/test_dapi.py .......................                               [  1%]
wazuh/core/cluster/tests/test_cluster.py ...................                                     [  2%]
wazuh/core/cluster/tests/test_common.py .......                                                  [  3%]
wazuh/core/cluster/tests/test_control.py .....                                                   [  3%]
wazuh/core/cluster/tests/test_local_client.py .                                                  [  3%]
wazuh/core/cluster/tests/test_utils.py .......                                                   [  3%]
wazuh/core/cluster/tests/test_worker.py .................                                        [  4%]
wazuh/core/tests/test_active_response.py ..............                                          [  5%]
wazuh/core/tests/test_agent.py ................................................................. [  9%]
................................................................................................ [ 15%]
.....                                                                                            [ 16%]
wazuh/core/tests/test_cdb_list.py ......................................                         [ 18%]
wazuh/core/tests/test_common.py .......                                                          [ 19%]
wazuh/core/tests/test_configuration.py ....................................                      [ 21%]
wazuh/core/tests/test_decoder.py ................                                                [ 22%]
wazuh/core/tests/test_input_validator.py ...                                                     [ 22%]
wazuh/core/tests/test_logtest.py ..                                                              [ 22%]
wazuh/core/tests/test_manager.py ...............                                                 [ 23%]
wazuh/core/tests/test_mitre.py .............                                                     [ 24%]
wazuh/core/tests/test_pyDaemonModule.py .....                                                    [ 24%]
wazuh/core/tests/test_results.py ........................................                        [ 27%]
wazuh/core/tests/test_rootcheck.py ..........                                                    [ 27%]
wazuh/core/tests/test_rule.py ......................                                             [ 29%]
wazuh/core/tests/test_stats.py ....                                                              [ 29%]
wazuh/core/tests/test_syscollector.py ...                                                        [ 29%]
wazuh/core/tests/test_utils.py ................................................................. [ 33%]
................................................................................................ [ 39%]
...................................................................                              [ 43%]
wazuh/core/tests/test_vulnerability.py .                                                         [ 43%]
wazuh/core/tests/test_wazuh_queue.py ..................                                          [ 45%]
wazuh/core/tests/test_wazuh_socket.py ....................                                       [ 46%]
wazuh/core/tests/test_wdb.py ......................                                              [ 47%]
wazuh/rbac/tests/test_auth_context.py ..                                                         [ 47%]
wazuh/rbac/tests/test_decorators.py ............................................................ [ 51%]
.............................................                                                    [ 54%]
wazuh/rbac/tests/test_default_configuration.py ................................................. [ 57%]
......                                                                                           [ 57%]
wazuh/rbac/tests/test_orm.py ......................................................              [ 61%]
wazuh/rbac/tests/test_preprocessor.py ...........                                                [ 61%]
wazuh/tests/test_active_response.py ............                                                 [ 62%]
wazuh/tests/test_agent.py ...................................................................... [ 66%]
.......................................                                                          [ 69%]
wazuh/tests/test_cdb_list.py .....................................................               [ 72%]
wazuh/tests/test_ciscat.py .................................                                     [ 74%]
wazuh/tests/test_cluster.py .......                                                              [ 75%]
wazuh/tests/test_decoder.py ...................................                                  [ 77%]
wazuh/tests/test_group.py ........                                                               [ 77%]
wazuh/tests/test_logtest.py ......                                                               [ 78%]
wazuh/tests/test_manager.py ....................................                                 [ 80%]
wazuh/tests/test_mitre.py .......                                                                [ 80%]
wazuh/tests/test_rootcheck.py ..................................................                 [ 84%]
wazuh/tests/test_rule.py ........................................................                [ 87%]
wazuh/tests/test_sca.py .......                                                                  [ 88%]
wazuh/tests/test_security.py ................................................................... [ 92%]
...................                                                                              [ 93%]
wazuh/tests/test_stats.py ................                                                       [ 94%]
wazuh/tests/test_syscheck.py .......................                                             [ 95%]
wazuh/tests/test_syscollector.py ............                                                    [ 96%]
wazuh/tests/test_task.py ............................                                            [ 98%]
wazuh/tests/test_vulnerability.py ..........................                                     [100%]

============================ 1599 passed, 14 warnings in 260.77s (0:04:20) =============================
```

### Integration tests
```
Collected tests [2]:
test_security_POST_endpoints.tavern.yaml, test_security_PUT_endpoints.tavern.yaml

test_security_POST_endpoints.tavern.yaml 
	 7 passed, 9 warnings

test_security_PUT_endpoints.tavern.yaml 
	 9 passed, 11 warnings

```

Regards,
Víctor

2021-08-02 11:00 UTC, AdriiiPRodri requested changes

2021-08-02 11:00 UTC, AdriiiPRodri commented on framework/wazuh/security.py
> +    load_spec, update_security_conf, REQUIRED_FIELDS, SORT_FIELDS, SORT_FIELDS_GET_USERS, sanitize_rbac_policy
```suggestion
from wazuh.core.security import invalid_users_tokens, invalid_roles_tokens, invalid_run_as_tokens, revoke_tokens,\
    load_spec, sanitize_rbac_policy, update_security_conf, REQUIRED_FIELDS, SORT_FIELDS, SORT_FIELDS_GET_USERS
```

2021-08-02 12:24 UTC, AdriiiPRodri approved these changes

2021-08-09 08:46 UTC, davidjiglesias approved these changes

2021-08-09 08:46 UTC, merged