Cluster - refactor walk_dir method
wazuh/wazuh pull request #9708
Opened 2021-08-12 20:19 UTC by Kondent

|Related issue|
|---|
| #9440 |

# Description
* `os.walk`: I made some changes on `walk_dir` method under `core/cluster/cluster.py`. After this refactor, it's using `os.walk` instead of recursive function.
* Few fixes following PEP8 standard on `core/cluster/cluster.py`.
* Fixes in related unit test.
* About the problem around the possibility of files being deleted while this method is running:
  * ![image](https://user-images.githubusercontent.com/84642680/129261744-40ea2e03-92aa-47bf-9edb-d7a2790021c8.png)
  * Its currently working like this, a log in debugger mode. I personally suggest this is a viable way to manage this problem. Other solution could be catching this exception and `pass` without a log.
---
# Tests
## UNIT: Api
```
⬦⬦⬦ ~/git/wazuh/framework ⨘ cd ~/git/wazuh/api && python3 -m pytest -x -v api --disable-warnings
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/unittest-env/bin/python3
cachedir: .pytest_cache
rootdir: /home/kondent/git/wazuh/api
plugins: asyncio-0.15.1, cov-2.12.1
collected 238 items                                                                                                                                                                          

api/models/test/test_model.py::test_model_from_dict PASSED                                                                                                                             [  0%]
...
...
...
api/test/test_validator.py::test_validation_json_ko[local_rules.xml,test_rule-xml_filename] PASSED                                                                                     [100%]

============================================================================== 238 passed, 14 warnings in 1.07s ==============================================================================
```

## UNIT: Framework
```
⬦⬦⬦ ~/git/wazuh/api ⨘ cd ~/git/wazuh/framework && python3 -m pytest -x -v wazuh --disable-warnings
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/unittest-env/bin/python3
cachedir: .pytest_cache
rootdir: /home/kondent/git/wazuh/framework
plugins: asyncio-0.15.1, cov-2.12.1
collected 1596 items                                                                                                                                                                         

wazuh/core/cluster/dapi/tests/test_dapi.py::test_DistributedAPI[kwargs0] PASSED                                                                                                        [  0%]
...
...
...
wazuh/tests/test_vulnerability.py::test_get_agent_cve_select[params2-expected_fields2] PASSED                                                                                          [100%]

======================================================================= 1596 passed, 14 warnings in 234.01s (0:03:54) ========================================================================
```

## Integration: 
* test_cluster_endpoints
* test_rbac_black_cluster_endpoints
* test_rbac_white_cluster_endpoints
```
⬦⬦⬦ ~/git/wazuh/api/test/integration ⨘ pytest -vv test_cluster_endpoints.tavern.yaml --disable-warnings && pytest -vv test_rbac_black_cluster_endpoints.tavern.yaml --disable-warnings && pytest -vv test_rbac_white_cluster_endpoints.tavern.yaml --disable-warnings 
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.0.0, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/inttest-env/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.5', 'Platform': 'Linux-5.11.0-25-generic-x86_64-with-glibc2.31', 'Packages': {'pytest': '5.0.0', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.11.0', 'tavern': '1.2.2'}}
rootdir: /home/kondent/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, metadata-1.11.0, tavern-1.2.2
collected 45 items                                                                                                                                                                           

test_cluster_endpoints.tavern.yaml::GET /cluster/local/config PASSED                                                                                                                   [  2%]
...
...
...
test_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/configuration PASSED                                                                                                        [100%]

===================================================================== 44 passed, 1 xpassed, 1 warnings in 663.90 seconds =====================================================================
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.0.0, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/inttest-env/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.5', 'Platform': 'Linux-5.11.0-25-generic-x86_64-with-glibc2.31', 'Packages': {'pytest': '5.0.0', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.11.0', 'tavern': '1.2.2'}}
rootdir: /home/kondent/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, metadata-1.11.0, tavern-1.2.2
collected 17 items                                                                                                                                                                           

test_rbac_black_cluster_endpoints.tavern.yaml::/cluster/local/config PASSED                                                                                                            [  5%]
...
...
...
test_rbac_black_cluster_endpoints.tavern.yaml::PUT /cluster/restart PASSED                                                                                                             [100%]

========================================================================== 17 passed, 1 warnings in 120.49 seconds ===========================================================================
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.0.0, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/inttest-env/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.5', 'Platform': 'Linux-5.11.0-25-generic-x86_64-with-glibc2.31', 'Packages': {'pytest': '5.0.0', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.11.0', 'tavern': '1.2.2'}}
rootdir: /home/kondent/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, metadata-1.11.0, tavern-1.2.2
collected 17 items                                                                                                                                                                           

test_rbac_white_cluster_endpoints.tavern.yaml::/cluster/local/config PASSED                                                                                                            [  5%]
...
...
...
test_rbac_white_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/configuration PASSED                                                                                             [100%]

============================================= [...]

2021-08-17 09:08 UTC, Selutario requested changes
- Add/restore comments in `walk_dir` code. 
- Run [integrity_sync system test](https://github.com/wazuh/wazuh-qa/tree/master/tests/system/test_cluster/test_integrity_sync) and paste the results in this PR too.

2021-08-17 14:12 UTC, Kondent commented on framework/wazuh/core/cluster/cluster.py
> +                                if file_mod_time == previous_status[relative_file_path]:
My bad here, I deleted `['mod_time']` by accident

2021-08-17 14:13 UTC, Kondent commented on framework/wazuh/core/cluster/cluster.py
> -        # If file is inside 'excluded_files' or file extension is inside 'excluded_extensions', skip over.
Will add comments to explain each block

2021-08-18 07:12 UTC, Selutario approved these changes

2021-08-25 10:35 UTC, davidjiglesias approved these changes

2021-08-25 10:58 UTC, davidjiglesias requested changes

2021-08-25 10:58 UTC, davidjiglesias commented on framework/wazuh/core/cluster/cluster.py
> +                    except Exception as e:
We should add two different Exception catches for IOError. File not existing or any other problem with permissions.

2021-08-31 09:14 UTC, merged