Fix RBAC Responses
wazuh/wazuh pull request #9721
Opened 2021-08-13 18:11 UTC by Kondent

|Related issue|
|---|
| #9695 |

# Description
This PR closes #9695.
test_rbac_black_vulnerability_endpoints.tavern.yaml

2021-08-19 06:37 UTC, vicferpoy requested changes
Missing changes on RBAC black tests.

2021-08-19 06:37 UTC, vicferpoy commented on api/test/integration/test_rbac_white_agent_endpoints.tavern.yaml
> -         total_failed_items: 0
As you can read in the test name, this test permissions are partially allowed (we are asking for for distinct stats in all agents). This means that the `count` field needs to be `6` exactly, as we have read permissions for 6 agents in this environment.

2021-08-19 14:09 UTC, Kondent commented
# Update
Requested changes were added.

## Int test: test_rbac_black_agent & test_rbac_white_agent
```
↪ ~/git/wazuh/api/test/integration ⊶ fix/9695-rbac-integration-response ⨘ pytest -vv test_rbac_black_agent_endpoints.tavern.yaml --disable-warnings && pytest -vv test_rbac_white_agent_endpoints.tavern.yaml --disable-warnings 
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.0.0, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/inttest-env/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.5', 'Platform': 'Linux-5.11.0-27-generic-x86_64-with-glibc2.31', 'Packages': {'pytest': '5.0.0', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.11.0', 'tavern': '1.2.2'}}
rootdir: /home/kondent/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, metadata-1.11.0, tavern-1.2.2
collected 41 items                                                                                                                                                                           

test_rbac_black_agent_endpoints.tavern.yaml::GET /agents PASSED                                                                                                                        [  2%]
...
...
test_rbac_black_agent_endpoints.tavern.yaml::PUT /agents/node/{node_id}/restart PASSED                                                                                                 [100%]

========================================================================== 41 passed, 1 warnings in 632.29 seconds ===========================================================================
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.0.0, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/inttest-env/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.5', 'Platform': 'Linux-5.11.0-27-generic-x86_64-with-glibc2.31', 'Packages': {'pytest': '5.0.0', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.11.0', 'tavern': '1.2.2'}}
rootdir: /home/kondent/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, metadata-1.11.0, tavern-1.2.2
collected 41 items                                                                                                                                                                           

test_rbac_white_agent_endpoints.tavern.yaml::GET /agents PASSED                                                                                                                        [  2%]
...
...
test_rbac_white_agent_endpoints.tavern.yaml::PUT /agents/node/{node_id}/restart PASSED                                                                                                 [100%]

========================================================================== 41 passed, 1 warnings in 607.30 seconds ===========================================================================
```

2021-08-25 14:50 UTC, closed without merging

2021-08-25 14:52 UTC, Kondent commented
# Update
Im closing this PR since I had some problems trying to change root branch.
New PR: `9904`