Smokescreen add kavi
wazuh/wazuh pull request #9813
Opened 2021-08-23 04:11 UTC by open-source-techie

|Related issue|
|---|
||

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2021-08-23 20:47 UTC, NicoGuini commented
For pfsense decoder and the related ini file, please check comments and changes requested made here: https://github.com/wazuh/wazuh/pull/9503

2021-08-24 00:03 UTC, NicoGuini requested changes
* Some improvements requested with their suggestions.
* Some fields need to be reviewed to handle them equally
Do you have plans to add some detection rules?


Also suggested to remove decoders and test files related to pfsense because they already are beeing reviewed in another PR

2021-08-28 17:34 UTC, open-source-techie commented
Hi @NicoGuini, Thanks for the suggestions. Will check and update on all proposed suggestions asap.

2021-08-28 18:18 UTC, open-source-techie commented
> For pfsense decoder and the related ini file, please check comments and changes requested made here: #9503
> 
> I would suggest to remove both files, and only leave those related to SmokeScreen to avoid merging issues in the future

pfsense files are removed from smokescreen PR. Thanks for update. It was by mistake. :)

2021-08-29 17:09 UTC, open-source-techie commented on ruleset/decoders/0570-smokescreen-decoder.xml
> +    <regex type="pcre2">"decoy.id":"(\S+)","decoy.name":"(\S+)","decoy.group":"(\S+)","decoy.type":"(\S+)","type":"(\S+)","kill_chain_phase":"(.*?)","sub_type":"(\S+)","attacker.name":"(\S+)","attack
Hi @NicoGuini the above regex is throwing error. decoy.id will be number always.

Error:
![image](https://user-images.githubusercontent.com/86832373/131259033-2cb33f2c-ada0-48e6-b211-e0f4afcbead5.png)

2021-08-31 02:56 UTC, open-source-techie commented
@NicoGuini required changes are made except 1 for which I have added my comment. Kindly have a look and update :) Thanks in advance.

2021-09-03 06:51 UTC, open-source-techie commented
Hi @NicoGuini any updates here ?

2025-02-19 19:17 UTC, closed without merging