Adjust RBAC API integration test responses
wazuh/wazuh pull request #9904
Opened 2021-08-25 14:50 UTC by Kondent

|Related issue|
|---|
| #9695 |

# Description
This PR closes #9695.
I updated `test_rbac_white_agent_endpoints.tavern.yaml`.
Generic responses were deleted since for testing purposes we only need status codes.

## Int test: test_rbac_black_agent & test_rbac_white_agent
```
↪ ~/git/wazuh/api/test/integration ⊶ fix/9695-rbac-integration ⨘ pytest -vv test_rbac_black_agent_endpoints.tavern.yaml --disable-warnings && pytest -vv test_rbac_white_agent_endpoints.tavern.yaml --disable-warnings 
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.0.0, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/inttest-env/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.5', 'Platform': 'Linux-5.11.0-27-generic-x86_64-with-glibc2.31', 'Packages': {'pytest': '5.0.0', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.11.0', 'tavern': '1.2.2'}}
rootdir: /home/kondent/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, metadata-1.11.0, tavern-1.2.2
collected 41 items                                                                                                                                                                           

test_rbac_black_agent_endpoints.tavern.yaml::GET /agents PASSED                                                                                                                        [  2%]
...
...
test_rbac_black_agent_endpoints.tavern.yaml::PUT /agents/node/{node_id}/restart PASSED                                                                                                 [100%]

========================================================================== 41 passed, 1 warnings in 632.29 seconds ===========================================================================
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-5.0.0, py-1.10.0, pluggy-0.13.1 -- /home/kondent/pythonEnv/inttest-env/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.5', 'Platform': 'Linux-5.11.0-27-generic-x86_64-with-glibc2.31', 'Packages': {'pytest': '5.0.0', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.11.0', 'tavern': '1.2.2'}}
rootdir: /home/kondent/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, metadata-1.11.0, tavern-1.2.2
collected 41 items                                                                                                                                                                           

test_rbac_white_agent_endpoints.tavern.yaml::GET /agents PASSED                                                                                                                        [  2%]
...
...
test_rbac_white_agent_endpoints.tavern.yaml::PUT /agents/node/{node_id}/restart PASSED                                                                                                 [100%]

========================================================================== 41 passed, 1 warnings in 607.30 seconds ===========================================================================
```

2021-09-06 08:20 UTC, vicferpoy requested changes

2021-09-06 08:20 UTC, vicferpoy commented on api/test/integration/test_rbac_black_agent_endpoints.tavern.yaml
> -            error: !anystr
Look at the test name. If we remove this block, this test will not do anything.  `dapi_errors` does not always show the node where the error occurred.  It depends on the `cluster:read` permission.  

We have this kind of test in other test modules as well. We should remove all of them and test it within `test_cluster_endpoints` using a distributed API call, but that is another issue. For now, do not remove it.

2021-09-06 08:20 UTC, vicferpoy commented on api/test/integration/test_rbac_white_agent_endpoints.tavern.yaml
> -            error: !anystr
Same as the comment above.

2021-09-08 07:25 UTC, vicferpoy approved these changes
LGTM!

2021-09-09 10:35 UTC, davidjiglesias approved these changes

2021-09-09 10:35 UTC, merged